### ISSUE TITLE
markrjr/Salut/v0.3.1 build issue

### ISSUE THREAD

**Issue by markrjr** [jitpack/jitpack.io#100]
Current Build Log: https://jitpack.io/com/github/markrjr/Salut/v0.3.1/build.log

I originally started with this problem below.
Old Build Log: https://jitpack.io/com/github/markrjr/Salut/v0.3/build.log

I thought I could fix this by adding the following to my build.gradle file, now however, it cannot find any of my dependencies.

```
    dependencies {
        classpath 'com.android.tools.build:gradle:1.2.3'
    }
```

**Comment by jitpack-io** [comment]
Hi!

You need to add the jcenter repository:
```
repositories {
        jcenter()
    }
```

it exists under buildscripts but you need it also outside of buildscripts.

**Comment by markrjr** [comment]
Thanks! That did it.
