### ISSUE TITLE
wiremock/2.4.1 build

### ISSUE THREAD

**Issue by NeilCannon** [jitpack/jitpack.io#1015]
Log https://jitpack.io/com/github/BridgeInternationalAcademies/wiremock/2.4.1/build.log

**Comment by jitpack-io** [comment]
Hi @NeilCannon 

Looks like the build failed due to missing `npm`.
`> A problem occurred starting process 'command 'npm'' `

If npm is requied then it's recommended to install it with pre-install commands:
https://jitpack.io/docs/BUILDING/#build-customization

**Comment by jaggs6** [comment]
@NeilCannon try './gradlew --stop' and then re-run the task
