### ISSUE TITLE
WorldGuard/-6.1.2-g46cca2b-29 build

### ISSUE THREAD

**Issue by TryHardDood** [jitpack/jitpack.io#1016]
Log https://jitpack.io/com/github/sk89q/WorldGuard/-6.1.2-g46cca2b-29/build.log

**Comment by jitpack-io** [comment]
Hi,

The log shows some issues with maven repositories in this build. One error: 
`Connection to http://localhost refused`

**Comment by TryHardDood** [comment]
There's an option to restart?
