### ISSUE TITLE
Document gradle repository ordering

### ISSUE THREAD

**Issue by joshfriend** [jitpack/jitpack.io#102]
I was somehow unaware that gradle searches repos for dependencies in the order they are declared. This made my build times agonizingly slow when I had jitpack listed first. Doing the following cleared things right up:

```groovy
repositories {
    mavenLocal()
    mavenCentral()
    maven { url 'https://jitpack.io' }
}
```

It should be mentioned somewhere in the docs/website that the order of the repo list will affect your build times and suggest a reasonable ordering.

**Comment by jitpack-io** [comment]
Completely agree. It should be placed at the end since requesting a dependency can also trigger a build.
Added a note to documentation until we find a better place for it.
Thanks for bringing this up!

**Comment by hamen** [comment]
Thank you @joshfriend

**Comment by jitpack-io** [comment]
Now documented on the website as well
