### ISSUE TITLE
Build failure in case of transitive dependency

### ISSUE THREAD

**Issue by Gaurav21Batra** [jitpack/jitpack.io#1026]
I have two repositories(Repo 1, Repo 2) hosted on jitpack and both are private repositories. Repo 1 is dependent on Repo 2, so the build of Repo 1 is failing due to authentication failure. How can I provide Repo1 access to Repo2 ?

**Comment by jitpack-io** [comment]
Hi @Gaurav21Batra 

Transitive dependencies should work automatically if you use this syntax to specify authentication:
```
 repositories {
        maven {
            url "https://jitpack.io"
            credentials { username authToken }
        }
 }
```
It is important that both of them have the property called `authToken`.

https://jitpack.io/docs/PRIVATE/
