### ISSUE TITLE
gabrielemariotti/colorpickercollection/v1.1.0 build issue on jitpack.io

### ISSUE THREAD

**Issue by jayseejc** [jitpack/jitpack.io#103]
Log https://jitpack.io/com/github/gabrielemariotti/colorpickercollection/v1.1.0/build.log

**Comment by jitpack-io** [comment]
Hi!
Did you want to get colorpickercollection as a library or as an application? 
https://github.com/gabrielemariotti/colorpickercollection/blob/master/ColorPicker/AndroidManifest.xml#L11
