### ISSUE TITLE
mohataher/ferma/9fd351c8d6 build issue

### ISSUE THREAD

**Issue by mohataher** [jitpack/jitpack.io#104]
Log https://jitpack.io/com/github/mohataher/ferma/9fd351c8d6/build.log

**Comment by jitpack-io** [comment]
Hi

The compilation fails due to missing java.util.function package which is in Java 8. The project is being compiled with Java 7 because of compiler settings in pom.xml
https://github.com/mohataher/Ferma/blob/master/pom.xml#L178-L179
Should that be 1.8 instead?

**Comment by mohataher** [comment]
Thanks a lot for your feedback.

**Comment by jitpack-io** [comment]
Welcome!
Closing the ticket for now. Please reopen if there's still an issue
