### ISSUE TITLE
Semantria/semantria-sdk/35e0697bad build issue

### ISSUE THREAD

**Issue by ryanrozich** [jitpack/jitpack.io#105]
Log https://jitpack.io/com/github/Semantria/semantria-sdk/35e0697bad/build.log

**Comment by jitpack-io** [comment]
Hi! Looks like an encoding problem
http://stackoverflow.com/a/10786268/3975649

**Comment by jitpack-io** [comment]
Fixed! We're now using UTF-8 as the default.
https://jitpack.io/#Semantria/semantria-sdk/35e0697bad
