### ISSUE TITLE
How to create a multi modular android library?

### ISSUE THREAD

**Issue by YoonjaeYoo** [jitpack/jitpack.io#1064]
I've successfully published an android library, [Solar](https://github.com/YoonjaeYoo/Solar), which can be found in [JitPack Page](https://www.jitpack.io/#YoonjaeYoo/Solar).

The problem is, it has one gradle module [solar-kuiper](https://github.com/YoonjaeYoo/Solar/tree/master/solar-kuiper) now, but there will be additional ones (solar-mars, solar-mercury and so on).
***I want to make each one of them as separate library, so that users can add them such as:***

```gradle
    compile 'com.github.YoonjaeYoo.Solar:solar-kuiper:1.0.0'
    compile 'com.github.YoonjaeYoo.Solar:solar-mars:1.0.0'
    compile 'com.github.YoonjaeYoo.Solar:solar-mercury:1.0.0'
```

But now, [JitPack Page](https://www.jitpack.io/#YoonjaeYoo/Solar) only shows one project, not multi subprojects. So I can use it in other projects only in this way:

```gradle
    compile 'com.github.YoonjaeYoo:Solar:1.0.0'
```

Any advice? Thank you.

**Comment by colinsheppard** [comment]
I'm in the exact same situation (I'm set up for a multi-module project but only have one sub-module at the moment) and just struggled with this issue for many hours. When I read your issue I realized that maybe I need a second sub-module and it worked! 

So my recommendation would be to create one of your planned new projects, even if it's totally empty and add the `include 'subproject'` it to the master settings.gradle file.

**Comment by jitpack-io** [comment]
Hi all,

Added a note in the documentation regarding projects with one module https://github.com/jitpack/jitpack.io/commit/76a2fd81fde9dd513d050a868576746ebecdf0ff#diff-396d0b75211f5646b2fa730fbdf80a40R82

>  If your project only has a *single* module then the dependency for that module is just `com.github.User:Repo:Tag`

Sorry about the confusion. Suggestions or other feedback welcome

**Comment by YoonjaeYoo** [comment]
@jitpack-io Many thanks!
