### ISSUE TITLE
surveyjs/0.10.3 build

### ISSUE THREAD

**Issue by JonBetts** [jitpack/jitpack.io#1080]
Log https://jitpack.io/com/github/andrewtelnov/surveyjs/0.10.3/build.log

**Comment by jitpack-io** [comment]
Hi @JonBetts 

Isn't this package already available on npm? At the moment we don't build npm projects but it is something we're looking into

**Comment by JonBetts** [comment]
I'm not sure, but I use Maven for my project dependencies. I can get in touch with the original developer to potentially look into the build issue.
