### ISSUE TITLE
SquidLib/90db62c037 build (no build.gradle, but it still builds as a Gradle project)

### ISSUE THREAD

**Issue by tommyettinger** [jitpack/jitpack.io#1097]
Log https://jitpack.io/com/github/SquidPony/SquidLib/90db62c037/build.log

I have a pom.xml file in the root directory along with a Gradle project file. The pom.xml should be the only way to build releases of the project, and the Gradle file should not be used for normal builds. The Gradle project has gone through multiple names, from build.gradle to optional_build.gradle to build.alt_gradle , and JitPack seems to consider it the only way to build the project regardless of name.  This means JitPack isn't doing what its docs say it should, that it should prefer a pom.xml (or the appropriate SBT or Leiningen build file) when build.gradle isn't present. For now, I'll be putting the Gradle configuration in a .zip file and telling users to extract it if they want to use Gradle, which is far from a clean solution. Is it possible to make JitPack behave as its documentation says it does regarding build tools? Or simply to update the JitPack docs to say the actual behavior JitPack uses to determine what build system it will use? I am guessing that the presence of a Gradle wrapper or some other Gradle file is making JitPack think that the project uses Gradle primarily, but Gradle support was only added as a convenience for users (ha), not to build the multi-module setup this should use and which works when using Maven.

**Comment by jitpack-io** [comment]
Hi @tommyettinger 

We support custom build commands that you can configure to run maven: 
https://jitpack.io/docs/BUILDING/#build-customization
Would that work for you?

**Comment by tommyettinger** [comment]
Yep, seems to work. The result is mostly be the same as what JitPack builds without a jitpack.yml (ignoring the Gradle build as intended), but for some reason there's no signing done for any artifacts other than pom.xml ones (which get a .md5 and a .sha1 file generated), while older builds signed everything. The only difference I can see in the command specified is that I use `mvn clean install -Dskiptests` in the current jitpack.yml file, while without that file JitPack runs `mvn install -Dskiptests`, though the environment may be different.

For the artifacts produced, here's the before:

https://jitpack.io/com/github/SquidPony/SquidLib/548d4422d2/build.log

And the after:

https://jitpack.io/com/github/SquidPony/SquidLib/111057d024/build.log

This isn't really a problem for me now, but it might be nice to understand why there's a difference, and that might be important for someone encountering this in the future (especially if signing is important to them for any reason).
