### ISSUE TITLE
Build by commit id

### ISSUE THREAD

**Issue by jitpack** [jitpack/jitpack.io#11]
Instead of a tag use the commit id as the version

**Comment by ysangkok** [comment]
This will make jitpack usable on a lot more projects (even the ones that never heard about jitpack), since most projects don't do Github releases.

**Comment by vbauer** [comment]
:+1:

**Comment by jitpack** [comment]
Ok, then. It is now possible to build by commit id. You can use the short version or the full sha1. 
Here's one example: https://jitpack.io/#jitpack/android-example/0ce2ec9226
