### ISSUE TITLE
tools/aeb6ef85cf build

### ISSUE THREAD

**Issue by yevster** [jitpack/jitpack.io#1100]
Log https://jitpack.io/com/github/yevster/tools/aeb6ef85cf/build.log

Compilation attempted with java 1.6, even though 1.8 is specified in the POM file.

**Comment by jitpack-io** [comment]
Hi @yevster 

For that version the pom seems to specify 1.6 https://github.com/yevster/tools/blob/aeb6ef85cf7b14bf65f115e88362dc6865e2c946/pom.xml#L209-L210

Another option is to specify java version via a yml file https://jitpack.io/docs/BUILDING/#java-version
