### ISSUE TITLE
Force cache revisit

### ISSUE THREAD

**Issue by jjkoehorst** [jitpack/jitpack.io#1103]
I read in a previous thread that there is a cache available of 1 hour. I can understand the reasons behind this but is there a click way to force the cache to reload? As we develop continuously here and sometimes make private repos public after we checked with jitpack and then we have to wait for an hour to continue (not a bad coffee break but stil...)

**Comment by jitpack-io** [comment]
Hi @jjkoehorst 
There's an option to make private repositories public with [artifact sharing](https://jitpack.io/docs/PRIVATE/#artifact-sharing). 
Would that work for you? 

We could also provide a way to reload the cache. Perhaps via an API call

**Comment by jjkoehorst** [comment]
For me personally as projects that we are supplying through jitpack will be 100% open a api call or something similar would be best.

**Comment by jitpack-io** [comment]
Should be fixed now. Whenever you 'Look up' a repository on jitpack.io we will re-check if repository is still private.
