### ISSUE TITLE
etaty/rediscala/1.4.1 build issue

### ISSUE THREAD

**Issue by the21st** [jitpack/jitpack.io#111]
Log https://jitpack.io/com/github/etaty/rediscala/1.4.1/build.log

I think the problem is that using a `build.sbt` file is just one way a project can be built by SBT. See [here](http://www.scala-sbt.org/release/tutorial/Full-Def.html)

**Comment by jitpack-io** [comment]
You're right. We also look for 'project/Build.scala' and 'project/build.sbt' but the project has different structure.

**Comment by jitpack-io** [comment]
Fixed now
