### ISSUE TITLE
Pan/0.9.6 build

### ISSUE THREAD

**Issue by beautifulSoup** [jitpack/jitpack.io#1113]
Log https://jitpack.io/com/github/campusappcn/Pan/0.9.6/build.log

The build failed. How can I fix it.

```
What went wrong:
A problem occurred evaluating project ':app-test'.
Failed to apply plugin [id 'com.android.application']
    Minimum supported Gradle version is 3.3. Current version is 2.14.1. If using the gradle wrapper, try editing the distributionUrl in /home/jitpack/build/gradle/wrapper/gradle-wrapper.properties to gradle-3.3-all.zip
```

**Comment by jitpack-io** [comment]
Probably best to upgrade gradle to 3.3 in `gradle/wrapper/gradle-wrapper.properties` and submit a PR
Will also need an upgrade of https://github.com/campusappcn/Pan/blob/master/build.gradle#L9 to version 1.5

**Comment by beautifulSoup** [comment]
Thank you. You save my time.
