### ISSUE TITLE
beeswax-api/6ef1c10ed9 build

### ISSUE THREAD

**Issue by darkcrawler01** [jitpack/jitpack.io#1117]
Log https://jitpack.io/com/github/BeeswaxIO/beeswax-api/6ef1c10ed9/build.log

Looks like the `protoc` version is a bit outdated. 
- In the start of the build, can we capture which version of protoc is being used 
``` protoc --version```
- Can we update the protoc version to `3.0.0`?

**Comment by jitpack-io** [comment]
Would it be possible to install `protoc` before the build with custom commands?
They can be specified in jitpack.yml https://jitpack.io/docs/BUILDING/#build-customization
