### ISSUE TITLE
Lastest Release

### ISSUE THREAD

**Issue by jrvansuita** [jitpack/jitpack.io#1118]
Is there a way can I compile as a dependency the lastest release published?

Rather than
       compile 'com.github.jrvansuita:PickImage:v2.0.4'
use like
       compile 'com.github.jrvansuita:PickImage:+'

**Comment by jitpack-io** [comment]
Yes, using `+` as the version should work if the project has already been built. It finds the latest built version.

**Comment by jrvansuita** [comment]
Perfect, thank you so much!
