### ISSUE TITLE
spring-test-dbunit/spring-test-dbunit-1.3.0 build

### ISSUE THREAD

**Issue by LouisWayne** [jitpack/jitpack.io#1133]
Log https://jitpack.io/com/github/springtestdbunit/spring-test-dbunit/spring-test-dbunit-1.3.0/build.log

Please help

**Comment by jitpack-io** [comment]
Hi @LouisWayne 

Looks like there might be an issue with the project's build files. It builds version 1.3.0 but then the Sample depends on 1.3.0-SNAPSHOT which does not exist.
One option is to fork the project and fix the versions.

**Comment by LouisWayne** [comment]
@jitpack-io Thank you!
