### ISSUE TITLE
jitpack detect errors compiling my github project?

### ISSUE THREAD

**Issue by pablopatarca** [jitpack/jitpack.io#1147]
I was trying diferents ways to add my github project like a dependency in android studio & find out that jitpack is logging an error: 
https://jitpack.io/com/github/pablopatarca/FloatingActionButton/v1.6.6/build.log
For example: In the project I added the support v7 library & I imported the class used in the next line:
`public class FloatingActionButton extends AppCompatImageButton {`
So, What's going on?
Thanks!

**Comment by jitpack-io** [comment]
Hi,

After a quick look it seems that javadoc generation failed:
`:library:androidJavadocs FAILED`

**Comment by pablopatarca** [comment]
That was! when I did the fork I forgot remove the "../gradle-mvn-push.gradle" file reference of my build.gradle (that generated the custom javadoc).

Thanks!

**Comment by jitpack-io** [comment]
That's great news and also the latest build succeeded
Happy building!
