### ISSUE TITLE
Receiving 401 "No read access to repo" for public Bitbucket Maven projects

### ISSUE THREAD

**Issue by admackin** [jitpack/jitpack.io#1148]
(first time Jitpack user, so hopefully I'm not missing anything obvious)

I can't get Jitpack to work with Bitbucket repos at all. I've followed the documentation, but I simply see 401 errors, with message "No read access to repo".

The repo I'm trying to access is a public Maven-built package at https://bitbucket.org/nicta_biomed/brateval . If I [put this URL in](https://jitpack.io/#org.bitbucket.nicta_biomed/brateval) at https://jitpack.io, I simply get a string of 401s in the console eg for URL `https://jitpack.io/api/tags/org.bitbucket.nicta_biomed/brateval`. I also made a public fork to my personal account at https://bitbucket.org/andymackinlay/brateval but I get identical results from that version. I also got similar results from [a package built using SBT](https://bitbucket.org/nicta_biomed/metagraph).

**Comment by jitpack-io** [comment]
Hi @admackin 

Looks like that one is a Mercurial (hg) repository. We only support Git at the moment

**Comment by admackin** [comment]
Ah, of course! Thanks.

I wonder if it would be worth having a more informative error message in cases like this. Even a 404 would make more sense than a 401.

Another useful change would be to remind idiots like me that hg is not supported when you mention Bitbucket, where hg repos are quite common.

**Comment by jitpack-io** [comment]
Agreed, but when we try to clone a Hg repository we don't get a meaningful message from BitBucket. We only get `not found`

There is some mention that this is for git only 
https://github.com/jitpack/jitpack.io/blob/f1152b832b49afe9974960700e23bc29a88c72b1/README.md#other-git-hosts
but we do accept PRs on any improvements to the docs too.
