### ISSUE TITLE
upgrade/1.0.1 build

### ISSUE THREAD

**Issue by abcdqianlei1990** [jitpack/jitpack.io#1155]
Log https://jitpack.io/com/github/abcdqianlei1990/upgrade/1.0.1/build.log

**Comment by jitpack-io** [comment]
Hi

The library is being built with Java 7 instead of Java 8. 
We will have a look at why this is happening. In the meantime you could set it in jitpack.yml: https://jitpack.io/docs/BUILDING/#java-version
