### ISSUE TITLE
Get builds by branch

### ISSUE THREAD

**Issue by jitpack-io** [jitpack/jitpack.io#1156]
Add ability to see builds on a specific branch and not just master

**Comment by jitpack-io** [comment]
Branches are selectable on the website

**Comment by bsideup** [comment]
wow, that was fast! Thanks!

**Comment by jitpack-io** [comment]
Way overdue:) 
Should be usefull to a lot of users. In any case all feedback appreciated

**Comment by bsideup** [comment]
@jitpack-io it seems like the module selector is missing when a branch is selected. Other than that works good :)

**Comment by jitpack-io** [comment]
@bsideup Quite right, will need to fix that. Thanks for noticing!

**Comment by jitpack-io** [comment]
@bsideup Should be fixed now
