### ISSUE TITLE
Failed to sync Gradle project

### ISSUE THREAD

**Issue by abcdqianlei1990** [jitpack/jitpack.io#1157]
project root gradle：
![image](https://cloud.githubusercontent.com/assets/8790004/23458170/03b0c908-feb6-11e6-873c-4fe83ad9635b.png)

module gradle：
![image](https://cloud.githubusercontent.com/assets/8790004/23458229/4e5daf5c-feb6-11e6-803d-7e70caaf9a60.png)

![image](https://cloud.githubusercontent.com/assets/8790004/23458249/6c0fa58c-feb6-11e6-930a-e7b0cf644155.png)

**Comment by jitpack-io** [comment]
Related to #1155
