### ISSUE TITLE
membrane/service-proxy/v4.0.23 build issue

### ISSUE THREAD

**Issue by helpermethod** [jitpack/jitpack.io#116]
Log https://jitpack.io/com/github/membrane/service-proxy/v4.0.23/build.log

The enforcer plugin requires this project to be build with JDK 1.7. While I could for the repository and remove this restriction, it would be nice if the JDK version could be configured somehow.

**Comment by jitpack-io** [comment]
Hi!
Would it be possible to change the (enforcer rule)[https://github.com/membrane/service-proxy/blob/master/pom.xml#L440] from `[1.7,1.8)` to just `1.7`?

We do support that syntax.

The other option is to use a `.jitpack.yml` config file in the repo and specify a jdk version there.

**Comment by jitpack-io** [comment]
@helpermethod Fixed! Now inferring java version from enforcer rules as well

**Comment by helpermethod** [comment]
Thank you very much, just what I needed!
