### ISSUE TITLE
Android cmake build fails

### ISSUE THREAD

**Issue by Tobi29** [jitpack/jitpack.io#1177]
Even though the cmake tools appear to be installed, they report an outdated NDK version.

Example log:
https://jitpack.io/com/github/Tobi29/ScapesEngineAndroidTest/987d0c6351/build.log

I was also able to reproduce this by trying to build an ndk sample app.

**Comment by jitpack-io** [comment]
Hi @Tobi29 

Updated NDK and the build was successful.
