### ISSUE TITLE
gdx-pd-patchbank/master-e574573569-1 build

### ISSUE THREAD

**Issue by mgsx-dev** [jitpack/jitpack.io#1179]
Log https://jitpack.io/com/github/mgsx-dev/gdx-pd-patchbank/master-e574573569-1/build.log

My gradle build script needs to run nodejs script in order to generate documentation. The node gradle plugin automatically download npm and run well on my Linux machine (without npm and nodejs installed) but it fails on your build platform.

Did you faced same issue ? If so, do you know a workaround ?

Thanks !

**Comment by jitpack-io** [comment]
Haven't seen this issue before. Seems like it should be working but perhaps more debug output will help to diagnose the issue.
Alternatively you can run custom instal commands https://jitpack.io/docs/BUILDING/#build-customization

**Comment by mgsx-dev** [comment]
I made some attempts and it appears there is a kind of timeout issue : 

With the following custom build (jitpack.yml) : 
```
install:
   - echo "Running a custom install command"
   - ./gradlew --stacktrace build publishToMavenLocal
```

the build succeed after 31.87 secs : https://jitpack.io/com/github/mgsx-dev/gdx-pd-patchbank/svg-1d86550efc-1/build.log

But when I removed the custom build file (jitpack.yml), the build failed after 9.745 secs : https://jitpack.io/com/github/mgsx-dev/gdx-pd-patchbank/svg-2ea63a8b94-1/build.log

I'm wondering if there is a kind of timeout configured within your default build command. Any thoughts ?

**Comment by jitpack-io** [comment]
Strange indeed. The default timeout is 15 minutes so it shouldn't have kicked in

**Comment by mgsx-dev** [comment]
Since I have a workaround now with custom build command, it's OK by me.

Thanks!
