### ISSUE TITLE
No toolchains found in the NDK toolchains folder for ABI with prefix: arm-linux-androideabi

### ISSUE THREAD

**Issue by zuhriyansauqi** [jitpack/jitpack.io#1197]
It seems everyone getting this error right now. Please fix this. Thanks

**Comment by jitpack-io** [comment]
Hi @zuhriyansauqi 

Should be fixed now.
Thanks

**Comment by r17171709** [comment]
It hapens again

**Comment by bhavinpadhiyar** [comment]
I get the same error

No toolchains found in the NDK toolchains folder for ABI with prefix: arm-linux-androideabi

**Comment by kabouzeid** [comment]
Same here

**Comment by whalemare** [comment]
Same here error. Fix please

**Comment by jitpack-io** [comment]
@whalemare @kabouzeid @bhavinpadhiyar @r17171709 Could you retry?

**Comment by whalemare** [comment]
@jitpack-io nice! Compile and running, thanks!!

**Comment by AllanWang** [comment]
I'm still having the same issue. I'm building a Kotlin Android project.

**Comment by duke79** [comment]
I'm too am facing this issue. [Logs](https://jitpack.io/com/github/Baliyaan/Android-Library/-0.0.3-g89e8c40-2/build.log)

**Comment by AllanWang** [comment]
@duke79 check again. Mine was just fixed

**Comment by duke79** [comment]
@AllanWang yes, it's fixed. Thanks 👍

**Comment by lsjwzh** [comment]
https://github.com/jitpack/jitpack.io/issues/1795

It hapens again

**Comment by lsjwzh** [comment]
it's fixed.

**Comment by EstevaoCoelho647** [comment]
it hapens again :/
https://jitpack.io/com/github/EstevaoCoelho647/FileDownloadManager/v0.0.4/build.log

**Comment by PPWasin** [comment]
I also face the same issue: https://jitpack.io/com/github/PPWasin/AutoInjector/0.6/build.log
Details: 
Language Kotlin
It happend after i use kotlin object, lazy delegator ( ... by layzy { .... } )

**Comment by giladna** [comment]
same here
