### ISSUE TITLE
Support GitHub Enterprise

### ISSUE THREAD

**Issue by jitpack** [jitpack/jitpack.io#12]
There seemed to be some interest on HN to use JitPack with GitHub Enterprise

**Comment by thenixan** [comment]
+1

**Comment by bbarnhill** [comment]
+1

**Comment by cdiaz-concur** [comment]
+10000000000

**Comment by jitpack-io** [comment]
Good news everyone! Starting to roll out the beta of JitPack Enterprise.
If you'd like to participate, drop an email to jitpack@jitpack.io and we'll reply with a download link.
