### ISSUE TITLE
LettersAvatar/v1.0.1 build

### ISSUE THREAD

**Issue by Runly** [jitpack/jitpack.io#1205]
Log https://jitpack.io/com/github/Runly/LettersAvatar/v1.0.1/build.log

----------------------------------------------------

I do not know how to fix it...

**Comment by jitpack-io** [comment]
Fixed and rebuilt

**Comment by Runly** [comment]
thanks!

2017-03-16 16:31 GMT+08:00 JitPack.io <notifications@github.com>:
