### ISSUE TITLE
[Feature Request] Publish repository submodules

### ISSUE THREAD

**Issue by ozodrukh** [jitpack/jitpack.io#1209]
Those project who added another modules, how can we publish submodules (Repo-moduleName)?

Example i have a repository [CircularReveal](https://github.com/ozodrukh/CircularReveal) and now on i have implemented submodule with extension to the CircularReveal, how can i publish it without creating a new repository as submodule of existing?

 ```python
## EXAMPLE
'com.github.ozodrukh:CircularReveal' #main module
'com.github.ozodrukh:CircularReveal-spring' #submodule
```

**Comment by jitpack-io** [comment]
Hi

Submodules are supported and you won't need to do anything extra to publish them. It is already working for your repository:
https://jitpack.io/#ozodrukh/CircularReveal/fe8aee3

There should be a Subproject dropdown where you can select a module.

**Comment by ozodrukh** [comment]
Wow such an amazing support, thanks guys 😎

**Comment by jitpack-io** [comment]
You're very welcome! Happy building!
