### ISSUE TITLE
Android-ZBLibrary/14.0 build

### ISSUE THREAD

**Issue by TommyLemon** [jitpack/jitpack.io#1219]
Log https://jitpack.io/com/github/TommyLemon/Android-ZBLibrary/14.0/build.log

**Comment by TommyLemon** [comment]
JitPack is wonderful! I love it😊

**Comment by jitpack-io** [comment]
@TommyLemon Thanks! Glad to be of service:)

Looks like there's an issue with one of the Java files. The JSON class should be in a file called JSON.java (all uppercase) while currently it is in Json.java.
https://jitpack.io/com/github/TommyLemon/Android-ZBLibrary/14.0/build.log

**Comment by TommyLemon** [comment]
@jitpack-io Yeah, thank you for reminding. I found the problem last night and have renamed Json.java to JSON.java. Then I made a new release 14.0.1 in GitHub. Is there anything else I need to do?

**Comment by jitpack-io** [comment]
That's it. Seems to work fine

**Comment by TommyLemon** [comment]
@jitpack-io Thank you~
