### ISSUE TITLE
sweet-alert-dialog/v1.1 build

### ISSUE THREAD

**Issue by adamis** [jitpack/jitpack.io#1231]
Error:Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : Attribute application@icon value=(@mipmap/ic_launcher) from AndroidManifest.xml:19:9-43
	is also present at [com.pnikosis:materialish-progress:1.0] AndroidManifest.xml:13:9-45 value=(@drawable/ic_launcher).
	Suggestion: add 'tools:replace="android:icon"' to <application> element at AndroidManifest.xml:17:5-42:19 to override.

**Comment by jitpack-io** [comment]
Hi @adamis 

Do you believe the error was caused by JitPack? Does the project build on your machine?

**Comment by adamis** [comment]
I can not change the APP icon once the library forces it to use: android: icon = "@ drawable / ic_launcher" from the library not in my folder.
