### ISSUE TITLE
webpartners/WPEditText/1.0 build issue

### ISSUE THREAD

**Issue by whaleswallce** [jitpack/jitpack.io#124]
Log https://jitpack.io/com/github/webpartners/WPEditText/1.0/build.log

My android studio cannot find this repository. Do something please

**Comment by jitpack-io** [comment]
@whaleswallce Fixed! Thanks for reporting!
You may have to run gradle with `--refresh-dependencies` to get it.

**Comment by whaleswallce** [comment]
thank you very much
