### ISSUE TITLE
Build problem: I deleted and recreated a repository the same name of "Logger"

### ISSUE THREAD

**Issue by Ayvytr** [jitpack/jitpack.io#1252]
Then I added JitPack dependencies and use my library Logger, but caught an error below:

Error:Could not find Logger.jar (com.github.Ayvytr:Logger:1.0.0).
Searched in the following locations:
    https://jitpack.io/com/github/Ayvytr/Logger/1.0.0/Logger-1.0.0.jar

**Comment by jitpack-io** [comment]
Hi,

The jar file did not get published by the build.
https://jitpack.io/com/github/Ayvytr/Logger/1.0.0/build.log

Does the jar get published when you run the build locally? The command JitPack used is:
`./gradlew clean -Pgroup=com.github.Ayvytr -Pversion=1.0.0 -xtest -xlint build publishToMavenLocal`
