### ISSUE TITLE
CircularReveal/2.1.0 build

### ISSUE THREAD

**Issue by guoyangd** [jitpack/jitpack.io#1257]
Log https://jitpack.io/com/github/ozodrukh/CircularReveal/2.1.0/build.log

Hello, I can't catch 2.1.0 Version from jitpack.

**Comment by jitpack-io** [comment]
Hi @guoyangd 

Rebuilt. There are two depednencies from this project:
```
com.github.ozodrukh.CircularReveal:spring-revealmanager:2.1.0
com.github.ozodrukh.CircularReveal:circualreveal:2.1.0
```

https://jitpack.io/#ozodrukh/CircularReveal/2.1.0
