### ISSUE TITLE
Cannot allocate memory

### ISSUE THREAD

**Issue by Enalmada** [jitpack/jitpack.io#126]
Build log:

```
Java HotSpot(TM) 64-Bit Server VM warning: INFO: os::commit_memory(0x0000000100d46000, 131072, 0) failed; error='Cannot allocate memory' (errno=12)
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (mmap) failed to map 131072 bytes for committing reserved memory.
# An error report file with more information is saved as:
# /build/hs_err_pid161.log
No build artifacts found
```
https://jitpack.io/com/github/enalmada/play-jsonp-filter/1.3/build.log

**Comment by jitpack-io** [comment]
Thanks for bringing this up! Rebuilt after freeing memory on servers and that version is now fine. 
Let's keep the issue open for now.

**Comment by jitpack-io** [comment]
Increases resources on build servers and we shouldn't be seeing this issue anymore.
Tried with latest commit and it was successfull https://jitpack.io/com/github/enalmada/play-jsonp-filter/46a3b242c3/build.log
Thanks for reporting!
