### ISSUE TITLE
OpenIAB/0.9.8.6 build

### ISSUE THREAD

**Issue by wima68** [jitpack/jitpack.io#1261]
Hi 
I tried to use the library through jitpack but failed :

Log https://jitpack.io/com/github/onepf/OpenIAB/0.9.8.6/build.log

Same thing happened when I tried other versions (0.9.8.4 & 0.9.8.3)
Android studio 1.5

**Comment by jitpack-io** [comment]
Hi,

The build failed because of
```
Execution failed for task ':OpenIab Library:install'.
> Could not publish configuration 'archives'
   > Unable to initialize POM pom-default.xml: Failed to validate POM for project com.github.onepf:OpenIab Library at /home/jitpack/build/library/build/poms/pom-default.xml
```

Does it work locally if you run `./gradlew install`?

**Comment by wima68** [comment]
It worked, Fixed the problem
Closing the issue
