### ISSUE TITLE
Jitpack Support for Ant

### ISSUE THREAD

**Issue by omervk** [jitpack/jitpack.io#127]
Log https://jitpack.io/com/github/google/gcm/352dcc97ee/build.log

jitpack does not support build.xml :(

**Comment by jitpack-io** [comment]
Hi @omervk!
We could support build.xml by running ant. But ant doesn't tell you what the dependencies of the project are. Would a jar file be useful to you on its own without its dependencies?

**Comment by omervk** [comment]
That's a good question. There are more questions, like which target to run and where the output is located, which would require reading the build.xml.

Those are a lot of very good questions and I think proper thinking and design is needed here to support this feature...

**Comment by jitpack-io** [comment]
Quite right. We might go for the approach that Travis has http://docs.travis-ci.com/user/languages/java/#Projects-Using-Ant

**Comment by omervk** [comment]
That might be a good idea, but would still require a convention I'm not sure exists in Ant.

**Comment by jitpack-io** [comment]
Hi all,

Ant is now supported however the build.xml file needs to be in the root of the project.
