### ISSUE TITLE
Add more info on javadocs publishing

### ISSUE THREAD

**Issue by joshfriend** [jitpack/jitpack.io#128]
I was unable to find "official" docs in the jitpack.io readme on how to generate the javadocs jar properly, but I managed to figure it out from other projects and StackOverflow. 

Here's what I came up with for reference:

``` groovy
task sourcesJar(type: Jar) {
    from android.sourceSets.main.java.srcDirs
    classifier = 'sources'
}

task javadoc(type: Javadoc) {
    failOnError  false
    source = android.sourceSets.main.java.sourceFiles
    classpath += project.files(android.getBootClasspath().join(File.pathSeparator))
}

task javadocJar(type: Jar, dependsOn: javadoc) {
    classifier = 'javadoc'
    from javadoc.destinationDir
}

artifacts {
    archives sourcesJar
    archives javadocJar
}
```

**Comment by jitpack-io** [comment]
Good point. Also it depends on the project and it will be different for non Android projects.
Added link to our Android example here  https://github.com/jitpack/jitpack.io/blob/master/README.md#other-features

**Comment by joshfriend** [comment]
Nice, thank you!
