### ISSUE TITLE
Artifact on Jitpack is empty

### ISSUE THREAD

**Issue by aaajanp** [jitpack/jitpack.io#1283]
The [build log](https://jitpack.io/com/github/YTech/YNSDK-And-Core/cad4c0415a/build.log) says everything is fine but the artifact doesn't contain any code. Tested it in Android Studio as a gradle dependency and by manually downloading .jar file and opening it up. 

The artifact from master works fine, this is a new branch and I tried targeting the branch SNAPSHOT and the actual commit. Both are empty. It only contains "META-INF" folder with a "MANIFEST.MF" file.

**Comment by jitpack-io** [comment]
Hi @aaajanp 

Investigating.

**Comment by jitpack-io** [comment]
Ok, found the problem. The project sets Java 7 in .jitpack.yml but building with that version produces an empty jar.
Building with Java 8 creates a jar with all the classes.

**Comment by aaajanp** [comment]
Thanks for the quick response. Why would building with Java 7 create an empty jar? The problem we've got is that we're building the artifacts for an Android app which means we *need* to use Java 7 (the fact we use Java 8 as well is an unrelated bug).

**Comment by jitpack-io** [comment]
Not sure yet. If you build the jar locally with Java7, does it have all the classes?

**Comment by aaajanp** [comment]
I've tested it out and you're right. It also helped us find the issue, it was one of the dependencies we were using which had problems with Java 7.
Thanks for your help!
