### ISSUE TITLE
jmfayard/restinparse

### ISSUE THREAD

**Issue by jmfayard** [jitpack/jitpack.io#1291]
Hello, I try jitpack for the first time for a gradle/java/kotlin project.

My build.gradle is here, heavily inspired by `gradle-simple`

https://github.com/jmfayard/restinparse/blob/9aad99a9e3c2de798cb09dba929a6b8500bb35ac/build.gradle

https://github.com/jitpack/gradle-simple/blob/master/build.gradle

My build log says `BUILD SUCCESSFUL` but `Total time: 0.671 secs` which is frankly suspicious :)

The resulting jars are empty, it seems that no compilation is done.

The log says  

`Running: gradle clean -Pgroup=com.github.jmfayard -Pversion=9aad99a9e3 -xtest install` 

Running this works like a charm on my dekstop

Any helps would be appreciated

Logs are attached
https://jitpack.io/com/github/jmfayard/restinparse/9aad99a9e3/build.log

**Comment by jitpack-io** [comment]
Hi @jmfayard 

Seems like in that commit there are no sources https://github.com/jmfayard/restinparse/tree/9aad99a9e3c2de798cb09dba929a6b8500bb35ac/src/

**Comment by jmfayard** [comment]
oops, very sorry

**Comment by jitpack-io** [comment]
No worries
