### ISSUE TITLE
social-login-helper/1.0.0 build

### ISSUE THREAD

**Issue by mukeshsolanki** [jitpack/jitpack.io#1304]
Can you please help me out with this not sure what seems to be the issue here. I have recently created a library for android and I'm trying to distribute it using jitpack but for some reason it keeps failing to build.

Log https://jitpack.io/com/github/mukeshsolanki/social-login-helper/1.0.0/build.log

**Comment by jitpack-io** [comment]
Hi @mukeshsolanki 

Compilation failed with an unusual error:
```
:sociallogin:compileReleaseJavaWithJavac
An exception has occurred in the compiler (1.8.0_101). Please file a bug against the Java compiler via the Java bug reporting page (http://bugreport.java.com) after checking the Bug Database (http://bugs.java.com) for duplicates. Include your program and the following diagnostic in your report. Thank you.
com.sun.tools.javac.code.Symbol$CompletionFailure: class file for java.lang.invoke.MethodType not found
:sociallogin:compileReleaseJavaWithJavac FAILED
```

Does it build on your machine with command 
`./gradlew clean -Pgroup=com.github.mukeshsolanki -Pversion=1.0.0 install` and Java 8?

**Comment by mukeshsolanki** [comment]
downgrading from java 8 seems to fix this
