### ISSUE TITLE
build servers missing android maven artifacts 

### ISSUE THREAD

**Issue by dbachelder** [jitpack/jitpack.io#131]
probably need to run this to deploy various artifacts:

https://github.com/simpligility/maven-android-sdk-deployer

here is an example build that is failing:
https://jitpack.io/com/github/johncarl81/transfuse/2d9d5e44e3b020ea88d52a97a52b4b54a269eedb/build.log

**Comment by jitpack-io** [comment]
Deployed missing artifacts. Looks better now:
https://jitpack.io/com/github/johncarl81/transfuse/2d9d5e44e3/build.log
