### ISSUE TITLE
TabAPI/B.0.1.17 build

### ISSUE THREAD

**Issue by missionarydev** [jitpack/jitpack.io#1310]
Log https://jitpack.io/com/github/net32/TabAPI/B.0.1.17/build.log

**Comment by jitpack-io** [comment]
The project tries to download some artifacts from this repo which doesn't seem to exist anymore or is behind a firewall:
```
(http://repo.bukkit.org/content/groups/public): repo.bukkit.org: Unknown host repo.bukkit.org
```

**Comment by missionarydev** [comment]
Ill just install the compiled jar to my local maven repo. Thanks.
