### ISSUE TITLE
Support for tag folders

### ISSUE THREAD

**Issue by FRosner** [jitpack/jitpack.io#132]
Hey guys,

I recently discovered JitPack and I like it a lot! I wanted to use it to get one of my GitHub projects as an SBT dependency but unfortunately I was not able to get it to work:

https://github.com/FRosner/spawncamping-dds

The reason seems to be that JitPack does not like my release folder for the release tags. Whenever I tag a release, I create it like git tag -a release/x.y.z. However, when I put this into JitPack, it gives me:

```xml
 <dependency>
     <groupId>com.github.FRosner</groupId>
     <artifactId>spawncamping-dds</artifactId>
     <version>release</version>
     <type>2.1.0</type>
 </dependency>
```

Which is obviously wrong. When I choose a release which is not in a folder, it works fine. Do you have any suggestions how to pull tags inside folders?

Thanks for your help!

Frank

**Comment by FRosner** [comment]
Reply from JitPack so far:

>Hi Frank,
>
>Very glad you like JitPack!:)
>You're quite right, it doesn't work with tag folders. Even if you put 'release/x.y.z' as the version in >pom.xml it makes Maven confused. It starts looking for: /com/github/FRosner/spawncamping-dds/release/x.y.z/spawncamping-dds-release/x.y.z.pom
> 
>Not sure yet if we can fix it. The only thing we can suggest is not using folders : )
>If you like you could open a GitHub issue and then we might come back to it one day if we come up with a solution
> 
>Best,
>
>JitPack

**Comment by jaggs6** [comment]
:+1:  please fix this, as it does not work with default GitFlow :(

**Comment by jitpack-io** [comment]
Wasn't aware it causes issues for GitFlow setups. We can't use the `/` symbol in the version but we could replace it with something else.

@FRosner @jaggs6 : How about a `~`? 

So when you request a tag called `feature/abc` you'd put the version `feature~abc`.

**Comment by FRosner** [comment]
The idea of `/` is that it is treated as a folder. GitX e.g. allows you to group the branches also visually in a folder structure.

I like to organize my branches in folders like this to distinguish branches for issues from branches for some experimentation and tags for releases from tags that just annotate some wip.

**Comment by jitpack-io** [comment]
Agreed. Branches and tags should stay the same so we're looking for a way to install them via JitPack. The proposal is to use this kind of dependency for tag folders:
```xml
<dependency>
     <groupId>com.github.User</groupId>
     <artifactId>Repo</artifactId>
     <version>feature~abc</version>
 </dependency>
```
to get the tag `feature/abc`. Since `~` is not allowed in tags there shouldn't be any conflicts.

**Comment by jaggs6** [comment]
I don't mind using ```~``` as long as I can still have branches with ```/``` in the name

**Comment by FRosner** [comment]
@jitpack-io gotcha. Sorry I misunderstood your first point. I agree with @jaggs6

**Comment by jitpack-io** [comment]
All right, let's try with `~`. Will post updates here

**Comment by jitpack-io** [comment]
Good news everyone! You can use tag folders with JitPack with the `~` symbol instead of `/`.
The website has been updated so code snippets show the right thing.

**Comment by jaggs6** [comment]
Great stuff. Will try it and report back.

**Comment by FRosner** [comment]
Nice! :+1:
