### ISSUE TITLE
beakerx/jitpack-ildipo~beaker-in-bunsen2-g55ce5a3-2068 build

### ISSUE THREAD

**Issue by hadim** [jitpack/jitpack.io#1326]
Log https://jitpack.io/com/github/hadim/beakerx/jitpack-ildipo~beaker-in-bunsen2-g55ce5a3-2068/build.log

**Comment by hadim** [comment]
Would it be possible to add pip and npm in your builders ?

**Comment by hadim** [comment]
Or is there is a way to remove `beakerx` module install from the build ? (without modifying the repo)

**Comment by jitpack-io** [comment]
We could add pip and npm but that might not work for everyone. Some projects depend on specific versions of these tools.
Ideally projects would install dependencies with custom commands in jitpack.yml https://jitpack.io/docs/BUILDING/#build-customization

**Comment by hadim** [comment]
Thank you I'll have a look.
