### ISSUE TITLE
onboarding/f8b29e9cd4 build issue

### ISSUE THREAD

**Issue by dbachelder** [jitpack/jitpack.io#133]
Log https://jitpack.io/com/github/ryanjohn1/onboarding/f8b29e9cd4/build.log

**Comment by dbachelder** [comment]
Looks like the machine can't allocate memory

**Comment by jitpack-io** [comment]
Rebuilt. Now there's a different error related to repository urls. Should work if these properties are used instead of plain urls:
https://github.com/chrisbanes/gradle-mvn-push/blob/master/gradle-mvn-push.gradle#L24-L32

**Comment by dbachelder** [comment]
Thanks!
