### ISSUE TITLE
How to get also source code (Kotlin)

### ISSUE THREAD

**Issue by elect86** [jitpack/jitpack.io#1330]
I am using jitpack since a while now, and it's amazing

There is only one thing bothering me, I never succeed getting also the source code along with the dependencies.

This is one [dependency](https://github.com/java-opengl-labs/modern-jogl-examples/blob/master/build.gradle#L25) example in one of my projects

What am I missing?

**Comment by jitpack-io** [comment]
Hi @elect86 

You will see the source code if your dependencies publish a `-sources.jar` alongside their main jar.
Looks like this particular dependency does not publish it at the moment. It would show up in the log: https://jitpack.io/com/github/kotlin-graphics/glm/4d1ae8bd6a/build.log

Perhaps the glm project could tweak their gradle build file to publish a sources.jar.

**Comment by elect86** [comment]
Thanks, 

```
task packageSources(type: Jar, dependsOn: 'classes') {
    from sourceSets.main.allSource
    classifier = 'sources'
}

artifacts { archives packageSources }
```

worked like a charm!

**Comment by sunilson** [comment]
How would I do this for an Android library?
