### ISSUE TITLE
android-rest-client/parent-1.7.0 build issue

### ISSUE THREAD

**Issue by chouex** [jitpack/jitpack.io#134]
Log https://jitpack.io/com/github/darko1002001/android-rest-client/parent-1.7.0/build.log

1.6.1 work

**Comment by jitpack-io** [comment]
```
java.lang.ClassNotFoundException: org.eclipse.aether.spi.connector.Transfer$State
```
usually this is caused by Maven version mismatch. We're building using 3.2.5

**Comment by jitpack-io** [comment]
Usually this error means there is a mismatch of Maven versions. We're building with 3.2.5

**Comment by jitpack-io** [comment]
Newer version seems to work fine https://jitpack.io/#darko1002001/android-rest-client/0c2284084b

**Comment by jitpack-io** [comment]
Also available on maven central https://github.com/darko1002001/android-rest-client/issues/6
