### ISSUE TITLE
ChatKit/0.3.1 build - Weird Gradle issue

### ISSUE THREAD

**Issue by mradzinski** [jitpack/jitpack.io#1352]
Log: https://jitpack.io/com/github/mradzinski/ChatKit/0.3.1/build.log

My gradle-wrapper.properties are:
```
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-3.3-all.zip
```

I do have gradlew and gradlew.bat files in the repo.

**Comment by jitpack-io** [comment]
Hi,

Looks like the properties file is there but not the .jar file
https://github.com/mradzinski/ChatKit/tree/0.3.1/gradle/wrapper

**Comment by mradzinski** [comment]
Yep, had to manually add the .jar. Weird because it was not .gitignore'd but for some reason was not present (probably the owner of the repo chose to use a local version of the wrapper).
