### ISSUE TITLE
JazzyViewPager/05fab56459 build issue

### ISSUE THREAD

**Issue by avgurf** [jitpack/jitpack.io#139]
Log https://jitpack.io/com/github/jfeinstein10/JazzyViewPager/05fab56459/build.log

hi, i've added:
compile 'com.github.jfeinstein10:JazzyViewPager:05fab56459' to my dependencies and:
    repositories {
        maven {
            url "https://jitpack.io"
        }
    }
to my buildscript{} in my project's build.gradle
which resulted in the following error:
Error:(20, 13) Failed to resolve: com.github.jfeinstein10:JazzyViewPager:05fab56459

**Comment by jitpack-io** [comment]
Hi,
JitPack.io shouldn't be added under buildscript but just under repositories.
Anyhow, the project is old and doesn't have a build file (build.gradle). So JitPack can't build it.
