### ISSUE TITLE
Strange build-stopping behavior with dependencies on commits

### ISSUE THREAD

**Issue by tommyettinger** [jitpack/jitpack.io#1409]
Build Log: https://jitpack.io/com/github/SquidPony/SquidLib/fdb6eefd4f/build.log

Does it build locally: yes, using Maven; a jitpack.yml file should ensure that JitPack also uses Maven.

Problem: Depending on SquidLib at any recent commit for the version simply doesn't complete the download from JitPack as a repository. The situation has improved, marginally, from earlier today; it was previously the case that clicking the build.log file would send my browser (Opera) into a sequence of redirects that the browser would terminate after 21 attempts as a security measure. The actual build files occasionally load successfully in the browser, but never from my IDE (I'm depending on SquidLib from a Gradle project; the versions used can be seen here https://github.com/tommyettinger/ColorGuard/blob/master/gradle.properties ). A tiny sha1 file, https://jitpack.io/com/github/SquidPony/SquidLib/squidlib-util/fdb6eefd4f/squidlib-util-fdb6eefd4f.pom.sha1 , downloads successfully in the browser but seems to halt the IDE when it tries to download it (a single short line of text...). I have no idea what's causing this currently; I altered the history of the repo to remove a large amount of redundant documentation files (using https://rtyley.github.io/bfg-repo-cleaner/ ), and that changed older hashes for commits, but it shouldn't affect commits after that history cleaning. I'm not the only person with this issue, and someone submitted an issue to SquidLib ( https://github.com/SquidPony/SquidLib/issues/151 ) because JitPack isn't working as an option to get the lib right now. This is certainly frustrating, because there's no indication on jitpack.io that anything's wrong but clearly these files are not accessible for some reason.

Any ideas what the issue might be? I've tried using 10-character commit hashes and full-length commit hashes as the dependency versions. I've gotten used to manually finding the 10-char commit hash because JitPack has been not showing recent commits consistently, though until the last few days it built a project just fine if given a valid short commit hash. I'm generally puzzled here.

**Comment by tommyettinger** [comment]
It seems to be working now, though I don't know if it will continue to do so. I'll leave this open in case there's some solvable issue this is related to.

**Comment by tommyettinger** [comment]
It's happening again, exactly as before -- a .pom file downloads, but the second file, which is a .pom.sha1 file, cannot seem to complete, and holds the whole Gradle build hostage while it waits without end. This is happening on this version: https://jitpack.io/com/github/SquidPony/SquidLib/99542ec0fe/build.log , and the build.log is only intermittently accessible.

**Comment by jitpack-io** [comment]
Hi @tommyettinger 
Should be working now.
We will be working on upgrades to mitigate this in the future

**Comment by tommyettinger** [comment]
Thanks for the info! I gave the updates a rest for a while and when I came back they were working. You can close this if you want, or if you feel like the problem is well-understood and the upgrades will solve it.
