### ISSUE TITLE
New Build Tools and new Google libs not Supported?

### ISSUE THREAD

**Issue by afollestad** [jitpack/jitpack.io#141]
First, I noticed build tools 23.0.0 (the release candidate versions) were not supported. Second, I noticed the remote build server couldn't resolve version 22.2.1 of Support Annotations, which I'm assuming would also apply to the Support Library, App Compat, etc.

```Gradle
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':bridge'.
> Could not resolve all dependencies for configuration ':bridge:_debugCompile'.
   > Could not find com.android.support:support-annotations:22.2.1.
     Searched in the following locations:
         https://jcenter.bintray.com/com/android/support/support-annotations/22.2.1/support-annotations-22.2.1.pom
         https://jcenter.bintray.com/com/android/support/support-annotations/22.2.1/support-annotations-22.2.1.jar
         file:/android/extras/android/m2repository/com/android/support/support-annotations/22.2.1/support-annotations-22.2.1.pom
         file:/android/extras/android/m2repository/com/android/support/support-annotations/22.2.1/support-annotations-22.2.1.jar
         file:/android/extras/google/m2repository/com/android/support/support-annotations/22.2.1/support-annotations-22.2.1.pom
         file:/android/extras/google/m2repository/com/android/support/support-annotations/22.2.1/support-annotations-22.2.1.jar
```

**Comment by afollestad** [comment]
I haven't used JitPack.io before this, I could see this being a very large problem in the future since I always update to the latest version of Google's libraries immediately. Couldn't updating via the SDK Manager be automated?

**Comment by jitpack-io** [comment]
Hi!
Yes, we should make android library updates automatic. Will be looking into it.

**Comment by jitpack-io** [comment]
Upgraded Platform tools to 23 rc4 and support library to 22.2.1
Thanks for raising the issue!

**Comment by afollestad** [comment]
Great, thanks! 

Looking forward to automatic updates in the future if possible.

**Comment by dbachelder** [comment]
@jitpack-io heads up that new tools and stuff came out today... support libs too, but I don't yet see them as available.. but the release notes are out.

**Comment by afollestad** [comment]
@jitpack-io Gradle Plugin 1.3.0 and Build Tools 23.0.0 are both available, but yeah I haven't been able to get Support/Design/Annotations/etc. v23 yet.

**Comment by jitpack-io** [comment]
Hey @dbachelder @afollestad !
Thanks for the heads up! Support library and SDK 23 installed
