### ISSUE TITLE
build issue https://github.com/johncarl81/transfuse

### ISSUE THREAD

**Issue by dbachelder** [jitpack/jitpack.io#143]
https://jitpack.io/com/github/johncarl81/transfuse/9207b1b28d47a83be308997a84446ce7393f0f3a/build.log

**Comment by jitpack-io** [comment]
Looks like the build failed due to lack of memory. Second build was ok.

**Comment by dbachelder** [comment]
@jitpack-io same problem on this build? 

https://jitpack.io/com/github/johncarl81/transfuse/4006dc5822287ce7c48d69deb26c39b6d2bc2a59/build.log

can you redo that one as well? or is there a way for me to do it?

**Comment by jitpack-io** [comment]
Yes, unfortunately same problem. You should be able to delete old builds on jitpack.io if you have push permissions on that repository.

Also planning box upgrades to prevent these types of issues

**Comment by jitpack-io** [comment]
Build boxes now should have more resources. Transfuse builds succeeded on first try.
