### ISSUE TITLE
Feature request: download stats

### ISSUE THREAD

**Issue by afollestad** [jitpack/jitpack.io#145]
An advantage that Bintray (jCenter) has is download stats.

**Comment by jitpack-io** [comment]
Download stats are definitely planned. Probably the next big feature.

**Comment by shkschneider** [comment]
+1

**Comment by totalvoidness** [comment]
+1

**Comment by haibison** [comment]
@jitpack-io You might want to merge this issue with your own #6 (and close this one).

Would you reveal that this feature will be available as paid one or free? I'm just curious, and no answer is ok  :-)

**Comment by jitpack-io** [comment]
Good news everyone!

Starting to roll out download statistics. Once you are Signed In you might see something like this:
![image](https://cloud.githubusercontent.com/assets/11161622/11763625/7e240ef8-a10a-11e5-8e32-64fda19e0d73.png)
At the moment just showing weekly and monthly downloads but there'll be more improvements over time.
The stats are for all files (pom,aar,javadocs) that are downloaded from your project.

**Comment by HeinrichReimer** [comment]
@jitpack-io any chance to have this as a badge like this:  
![Downloads](https://img.shields.io/badge/downloads-32k-brightgreen.svg)

**Comment by jitpack-io** [comment]
@HeinrichReimer Experimental download badges:
`![Downloads](https://jitpack.io/v/USER/PROJECT/month.svg)`
and
`![Downloads](https://jitpack.io/v/USER/PROJECT/week.svg)`

For example:
![Downloads](https://jitpack.io/v/PhilJay/MPAndroidChart/month.svg)

**Comment by HeinrichReimer** [comment]
Wow, that was fast! Huge thanks to you @jitpack-io and thanks for this awesome service!

**Comment by HeinrichReimer** [comment]
@jitpack-io after some testing now it appears that the badges need very long time to load which causes GitHub to display a placeholder sometimes.
![unbenannt](https://cloud.githubusercontent.com/assets/5065698/24280211/2a7b3168-104f-11e7-81a6-6bd30013e54e.png)

**Comment by jitpack-io** [comment]
@HeinrichReimer We've added caching to download stats which should get rid of these timeouts. If you still encounter it let us know. Thanks for reporting!

**Comment by HeinrichReimer** [comment]
@jitpack-io Thank you!

**Comment by MarcinOrlowski** [comment]
Any chance stats badge could show downloads per tag (version) not totals?

**Comment by StephenOTT** [comment]
@jitpack-io  what happened to the statistics info on the page??

**Comment by StephenOTT** [comment]
are download stats not a public info on the site?  Not beneficial to have people seeing how much OSS gets used?

**Comment by lnewcomer1** [comment]
Are downloads counted as one per IP address?

**Comment by jitpack-io** [comment]
Download count gets incremented when a file from the repository is downloaded, from any IP address.

Coming up next - downloads per each version. In fact, you can already get download stats via api. For example: https://jitpack.io/api/downloads/com.github.philjay/mpandroidchart/v3.0.2

**Comment by amalChandran** [comment]
The download stat via api always gives me this:

> {"week":0,"month":0}

The Jitpack dashboard does not load the weekly and months stats all the time. I have to keep refreshing the page to see it. And some times that data never shows up. Please take a look.

**Comment by lamba92** [comment]
What about total downloads?

**Comment by AsianKoala** [comment]
Any update on total downloads?

**Comment by ndriqa** [comment]
Any update on total downloads yet?

**Comment by hamza-cskn** [comment]
Any update on total downloads still?

**Comment by ronenfe** [comment]
Total downloads counter?
