### ISSUE TITLE
Can I deploy a gradle plugin on jitpack?

### ISSUE THREAD

**Issue by chaooooooo** [jitpack/jitpack.io#1459]
I have a simple gradle plugin,
Can I deploy a gradle plugin on jitpack?

**Comment by aadrian** [comment]
> Can I deploy a gradle plugin on jitpack?

You can, but IMHO it doesn't make much sense, since Gradle plug-ins are supposed to be hosted on https://plugins.gradle.org/

**Comment by AllanWang** [comment]
Bringing this back, but do you have an example somewhere? Hosting plugins for jitpack is definitely useful if you'd like to keep everything inline with other dependencies. With one push, you'll be able to use the commit versions, assuming that is how it works.

**Comment by Xerus2000** [comment]
Same question. I am working on a plugin that I don't want to publish yet but I want to test it already...

**Comment by LSafer** [comment]
Same question. It is annoying for me to wait for gradle to `manually` approve my plugin.

**Comment by elect86** [comment]
Hi, any news on this?

**Comment by LSafer** [comment]
Let the code explain: 
```gradle
apply plugin: 'java'
apply plugin: 'plugin-id'

buildscript() {
	repositories {
		maven {
			url 'https://jitpack.io'
		}
	}
	dependencies {
		classpath 'com.github.User:Repo:Version'
	}
}
```

Example:
```gradle
apply plugin: 'java'
apply plugin: 'jamplate'

buildscript() {
	repositories {
		maven {
			url 'https://jitpack.io'
		}
	}
	dependencies {
                //replace 'TAG' with the desired version
		classpath 'com.github.cufyorg:jamplate-gradle-plugin:TAG'
	}
}
```

**Comment by elect86** [comment]
Awesome, let me try

**Comment by elect86** [comment]
@LSafer 

Did you try to make this work with the new `plugins { }` dsl?

**Comment by LSafer** [comment]
@elect86 yes I did. But, it was a long time for me to remember the conclusion. I think it is not possible. But, It might work by playing around with plugin repositories.

**Comment by LSafer** [comment]
@elect86 see the plugin I published https://github.com/cufyorg/jamplate-gradle-plugin for latest updates of my approaches to deliver it.

**Comment by elect86** [comment]
Gotcha!

`build.gradle.kts`:
```
plugins {
    ...
    id("com.github.elect86.docs") version "5335fdf4"
}
```

`settings.gradle.kts`:
```
pluginManagement {
    resolutionStrategy {
        eachPlugin {
            if(requested.id.toString() == "com.github.elect86.docs")
                useModule("com.github.elect86:docs:5335fdf4")
        }
    }
    repositories {
        gradlePluginPortal()
        maven("https://jitpack.io")
    }
}
```
**And** make sure to set the id plugin as the annotation:
```
gradlePlugin {
    // Define the plugin
    val greeting by plugins.creating {
        id = "com.github.elect86.docs"
        implementationClass = "docs.DocsPlugin"
    }
}
```

**Comment by itsnotoger** [comment]
Expanding on elect86's solution:
```kotlin
pluginManagement {
    resolutionStrategy {
        eachPlugin {
            requested.apply {
                if ("$id".startsWith("com.github.")) {
                    val (_, _, user, name) = "$id".split(".", limit = 4)
                    useModule("com.github.$user:$name:$version")
                }
            }
        }
    }

    repositories {
        maven("https://jitpack.io")
        gradlePluginPortal()
    }
}
```

Then use like
```kotlin
plugins {
    id("com.github.itsnotoger.gradle-plugin") version "278e62eaa8"
}
```

And publish like
```kotlin
gradlePlugin {
    plugins {
        register("OgerPlugin") {
            id = "$group.$githubProjectName"
            implementationClass = "oger.util.java.OgerPlugin"
        }
    }
}
```
