### ISSUE TITLE
truetime-android/3fd45e9476 build

### ISSUE THREAD

**Issue by kaushikgopal** [jitpack/jitpack.io#1470]
Log https://jitpack.io/com/github/instacart/truetime-android/3fd45e9476/build.log

Thought this was an issue with upgrading the android gradle plugin. doesn't appear so as reverting the versions didn't help either

```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApk'.
   > A problem occurred configuring project ':library'.
      > No toolchains found in the NDK toolchains folder for ABI with prefix: arm-linux-androideabi
```

**Comment by jitpack-io** [comment]
Hi,

Yes, it was todo with android sdk installation on our side.
Rebuilt 3fd45e9476
