### ISSUE TITLE
Strange 401 error on TestNG master-SNAPSHOT

### ISSUE THREAD

**Issue by juherr** [jitpack/jitpack.io#1478]
Hi,

We had to change all our links to jitpack because `master-SNAPSHOT` stopped to work.
At the same time, it looks `master` is working well.
You can check https://github.com/testng-team/testng-team.github.io/pull/21

Is it the expected behavior?

**Comment by jitpack-io** [comment]
hi

what is the dependency you were using?

**Comment by juherr** [comment]
None. We use jitpack to host the up2date javadoc.

Before: https://jitpack.io/com/github/cbeust/testng/master-SNAPSHOT/javadoc/ worked like a charm
Now: the url asks for an authentication.

As a workaround, we use https://jitpack.io/com/github/cbeust/testng/master/javadoc/ now but I'd like to know if we are doing the right thing.

**Comment by juherr** [comment]
Ping @jitpack-io What is the expected (new) url for javadoc on master?

**Comment by jitpack-io** [comment]
Hi,

Could you try this for now?
https://jitpack.io/com/github/cbeust/testng/-SNAPSHOT/javadoc/

Will look into why 'master-SNAPSHOT' is not working for that repo

**Comment by juherr** [comment]
`-SNAPSHOT` is working too

**Comment by juherr** [comment]
Ping @jitpack-io
