### ISSUE TITLE
Module build error.

### ISSUE THREAD

**Issue by wenerme** [jitpack/jitpack.io#15]
this build ok
```
https://jitpack.io/com/github/NanoHttpd/nanohttpd/Release-2.1.0/build.log
```

require url format is
```
Expecting: /com/github/user/repo[/module]/version/repo-version.pom
```

But in pom, the coordinate is 
```
<groupId>fi.iki.elonen</groupId>
    <artifactId>nanohttpd-project</artifactId>
    <version>2.1.0</version>
    <packaging>pom</packaging>
```

So, how can I get the pom with jitpack way ?

I can not open this url
```
https://jitpack.io/com/github/NanoHttpd/core/nanohttpd/Release-2.1.0/nanohttpd-Release-2.1.0.pom
```

even if I can , then how to put the core module in dependency ?
```
<dependency>
            <groupId>com.github.NanoHttpd</groupId>
            <artifactId>nanohttpd</artifactId>
            <version>Release-2.1.0</version>
        </dependency>
```
Where to tell jitpack I need core ?

**Comment by wenerme** [comment]
https://jitpack.io/#NanoHttpd/nanohttpd/ show build error, but why ?
Home page do not show a way to use module in a repo.

**Comment by jitpack** [comment]
Hi

It looks like you have a multi module build. Yes, you need to tell that you want the core module and the artifactId of the core module is 'nanohttpd'.

The resulting artifactId should be `Repo.Module`. So this works:
```xml
      <dependency>
            <groupId>com.github.NanoHttpd</groupId>
            <artifactId>nanohttpd.nanohttpd</artifactId>
            <version>Release-2.1.0</version>
        </dependency>
```

See also https://github.com/jitpack/jitpack.io/blob/master/BUILDING.md#multi-module-projects

Hope that works for you. If not please get in touch and thanks for reporting!

**Comment by jitpack** [comment]
Closing for now. If it still happens feel free to reopen
