### ISSUE TITLE
gradle kotlin-dsl build not started

### ISSUE THREAD

**Issue by fboldog** [jitpack/jitpack.io#1528]
Log https://jitpack.io/com/github/fboldog/moviest-miner/0.0.1/build.log

Build not executed, when using kotlin-dsl (build.gradle.kts) for gradle build.
https://github.com/gradle/kotlin-dsl

**Comment by jitpack-io** [comment]
Done!

**Comment by fboldog** [comment]
Tested & perfect. Thanks.
