### ISSUE TITLE
homepoint-dlna/1.0.0 build issue

### ISSUE THREAD

**Issue by LaurentSouchet-Orange** [jitpack/jitpack.io#153]
Log https://jitpack.io/com/github/LaurentSouchet-Orange/homepoint-dlna/1.0.0/build.log

Hi, 

May I use an another repository with Github ?
I use this for dlna module

    maven { url 'http://4thline.org/m2' }

Best Regards,
  Laurent

**Comment by jitpack-io** [comment]
Hi @LaurentSouchet-Orange 

That should be fine but when your sample depends on the library its better to use the 
`compile project(':library')` dependency syntax. 

Otherwise the repo depends on itself and can't build.

**Comment by LaurentSouchet-Orange** [comment]
Thanks for your answer.
I'm sorry of my fault.
It's ok now.
Best regards,
  Laurent

**Comment by jitpack-io** [comment]
No problem at all. Happy building!
