### ISSUE TITLE
Circular dependency error

### ISSUE THREAD

**Issue by demongaorui** [jitpack/jitpack.io#1532]
Log https://jitpack.io/com/github/money-design/theo/RELEASE_THEO_SERVER_20170621_DO_NOT_RELEASE_THIS_TAG/build.log

I could run './gradlew install' locally, while JitPack builds failed. Any ideas to solve this problem?

**Comment by demongaorui** [comment]
Close this issue, because company and product names included here.  Please help to delete this issue and also #1531 for private info safety if you could. Thank you very much.

**Comment by jitpack-io** [comment]
There's a warning in the log:
```
Gradle 'install' task not found. Please add the 'maven' or 'android-maven' plugin.
See the documentation and examples: https://jitpack.io/docs/
```

**Comment by demongaorui** [comment]
In the log, I also saw that `Adding maven plugin` , so I guess jitpack added the plugin automatically. Then we encounter to `Circular dependency error`.

BTW, thank you very much for deleting the log URL which contains private infos.

**Comment by jitpack-io** [comment]
It added the plugin automatically but would recommend adding it in the project and re-running `./gradlew install`.
The circular dependency doesn't appear to be caused by jitpack but rather by gradle build file.
