### ISSUE TITLE
Provide an Android @aar library file for multi-module projects

### ISSUE THREAD

**Issue by tynn** [jitpack/jitpack.io#1539]
Regarding [multi-module Android projects](https://jitpack.io/docs/BUILDING/#multi-module-projects) we do get the artifacts published to be consumed with alone by itself.

Trying to use the auto-generated collection

    compile 'com.github.User:Repo:Tag'

results in following error

    Error: Module 'com.github.User:Repo:Tag' depends on one or more Android Libraries but is a jar

Since this `@jar` artifact is in fact empty, not providing anything, it should be replaced by an Android `@aar` artifact not providing anything. This one needs to be the default artifact as well. Otherwise the dependencies are not pulled in transitively.

In addition it's necessary to set minimal and maximal Android Api SDK levels for this library as well as a package name which could be configured with _.jitpack.yml_.

**Comment by jitpack-io** [comment]
Hi,

Would you have an example project where an `aar` module depends on another `aar` module?

**Comment by tynn** [comment]
I've set it up for [_Supplies_](https://github.com/volders/Supplies).

At the moment it's done manually in a separate module

    compile "berlin.volders.supplies:all:$suppliesVersion"

while it would be nice to be able to just depend on the parent

    compile "berlin.volders:supplies:$suppliesVersion"

**Comment by tynn** [comment]
_Supplies_ was removed and therefore is not available in the repos anymore.
The [AsapiLvEx](https://github.com/asapi/AsapiLvEx) has submodules as well and the following should return an `aar` file with `minSdkVersion=21` and `maxSdkVersion=22`.

    compile 'com.github.asapi:asapilvex:0.0'
