### ISSUE TITLE
Private Repository error 401

### ISSUE THREAD

**Issue by CLucera** [jitpack/jitpack.io#1547]
Got a 401 error while trying to compile a project with gradle:

compile 'org.bitbucket.appmap:proximitylib:-SNAPSHOT'

> Could not GET 'https://jitpack.io/org/bitbucket/appmap/proximitylib/-SNAPSHOT/maven-metadata.xml'. Received status code 401 from server: Unauthorized

the username is set (as auth token) in the main build.gradle file, the import was correctly working some days ago

**Comment by jitpack-io** [comment]
Hi,

it appears that the trial has expired for bitbucket.org:appmap

**Comment by CLucera** [comment]
uh, looks like i didn't noticed that the private repository was a paid feature! thank you for your support
