### ISSUE TITLE
cx-android-sdk/CXSDK-552-3.2.1-g3a3376b-10 build

### ISSUE THREAD

**Issue by DeKaN** [jitpack/jitpack.io#1549]
This branch does not exist, build was deleted, but build appear each day with same log.

Log https://jitpack.io/com/cxpublic/cx-android-sdk/CXSDK-552-3.2.1-g3a3376b-10/build.log

**Comment by DeKaN** [comment]
@jitpack-io This branch was deleted more than 2 months ago, but I see new build: https://jitpack.io/com/cxpublic/cx-android-sdk/CXSDK-552-3.2.1-gc451321-7/build.log

**Comment by jitpack-io** [comment]
Hi @DeKaN 

The project builds because the commit hash `c451321` is available in the repo. At the moment we don't check if the actual branch still exists as this is an edge case.
