### ISSUE TITLE
Classes compiled with different version of java compiler

### ISSUE THREAD

**Issue by MadMan0708** [jitpack/jitpack.io#155]
Hi guys. Firstly, thank you for jitpack, it's great tool. I did use jitpack to make a dependency out of public repository on github and it all worked well. However, during testing of our project we discovered that the jar was compiled with Java 7 and broke compatibility of our project with Java 6. I red more on how to configure it and placed the file .jitpack.yml with content
jdk:
oraclejdk6
to the root or our app repository, but the jar fetched from the server still has Java major version 51 ( Java 7). Am I doing something wrong ? Thank you for help!

**Comment by jitpack-io** [comment]
Hi @MadMan0708 

A better approach would be to specify source/target compatibility in your build
tool. In gradle that would be:
https://github.com/jitpack/gradle-simple/blob/master/build.gradle#L6-L7

**Comment by MadMan0708** [comment]
Hi

thank you for the reply. The problem is that the git project I want to include as dependency it's not my project (particularly this one https://github.com/ronmamo/reflections) and in the project's pom.xml file there is java jdk 1.7 sed which is used by jitpack to cimpile this dependency.

**Comment by jitpack-io** [comment]
I see. If they have specified 1.7 then we have to use that to build since they might be using Java 7 features.
One option would be to ask the maintainers to change it to 1.6 or just to fork the project and change there.

**Comment by MadMan0708** [comment]
They have maven profile for jdk 1.5 but it's not default profile. Anyway, I forked the repo and will use it until there's official library release. It was easier like this :)

Thanks a lot!
