### ISSUE TITLE
naruto-library/1.0.0 build issue

### ISSUE THREAD

**Issue by naruto-wbb** [jitpack/jitpack.io#156]
Log https://jitpack.io/com/github/naruto-wbb/naruto-library/09254f6a4c/build.log

**Comment by jitpack-io** [comment]
Hi,
Looks like this part is missing from build.gradle:
https://github.com/jitpack/android-example/blob/master/build.gradle#L3-L11

After that just add this line:
https://github.com/jitpack/android-example/blob/master/library/build.gradle#L2

**Comment by jitpack-io** [comment]
Hi @naruto-wbb 

Closing the issue for now but feel free to reopen if you still have an issue
