### ISSUE TITLE
Build is fine but it cannot retrieve the dependency

### ISSUE THREAD

**Issue by elect86** [jitpack/jitpack.io#1568]
1. [Build log](https://jitpack.io/com/github/kotlin-graphics/glm/57ca4d6e22/build.log) is fine
 2. Does the project build on your machine? yes

However when I synchronize Gradle, it gets stuck on retrieving the glm dependency

It's curious because if I visit https://jitpack.io/#kotlin-graphics/glm I see double build entries for the last two commits...

![Imgur](http://i.imgur.com/Ysom79e.png)

What's wrong?

**Comment by elect86** [comment]
On ubuntu [this](https://gist.github.com/elect86/2ddc60234a8e7014301ea5ba99f4b564) is the output of 

`./gradlew build --info --debug`

**Comment by mkaflowski** [comment]
My 2 libs releases don't work too. Whole day looking for soultion.

**Comment by jitpack-io** [comment]
The lib was in the build queue for a long time that's why it appeared to be stuck. This should be now resolved.
@elect86 The output shows multiple jitpack links with `?building=1` ... `?building=5` parameters which shows the project was building/queueing.
https://status.jitpack.io/776679744

**Comment by elect86** [comment]
ok, back online

thanks for solving it
