### ISSUE TITLE
webhook not working

### ISSUE THREAD

**Issue by elect86** [jitpack/jitpack.io#1569]
I followed the [wiki](https://jitpack.io/docs/BUILDING/#building-ahead-of-time)

but the webhook seems not working..

![Imgur](http://i.imgur.com/B4kvQHQ.png)

**Comment by elect86** [comment]
On ubuntu [this](https://gist.github.com/elect86/2ddc60234a8e7014301ea5ba99f4b564) is the output of 

`./gradlew build --info --debug`

**Comment by jitpack-io** [comment]
Hi,

The content type should be `application/json`.
Will be adding this to docs.

**Comment by elect86** [comment]
Ok, did that.

I see when I push that is building the `-SNAPTSHOT`, and after ready, also the relative commit will be flagged as built (green report)

However, when I pull it, I see jitpack building it again.. (the rotating animations)

**Comment by jitpack-io** [comment]
Hi,

what dependency are you using in your build file?

**Comment by elect86** [comment]
pushed [`gli`](https://github.com/kotlin-graphics/gli/blob/master/build.gradle) and pulled it in [`uno`](https://github.com/kotlin-graphics/uno-sdk/blob/master/build.gradle)

**Comment by jitpack-io** [comment]
It appears you are using an exact commit in uno. Webhooks will build a snapshot build which is slightly different, although it builds the same commit. 
Would recommend using the `-SNAPSHOT` version if you want to avoid re-building.

**Comment by elect86** [comment]
tried `-SNAPSHOT`, yet no success

I tried to push glm, wait for the build by looking online, and then fetch it by `-SNAPSHOT` from gli, it still re-builds it..  and I can see it also online, again the circle, although it was already built

**Comment by jitpack-io** [comment]
Ok, will have a look.
In the meantime could you also try `master-SNAPSHOT` version to see if it fixes it?

**Comment by elect86** [comment]
`master-SNAPSHOT` worked like a charm

only disadvantage, I can't check directly the commit number in the dependencies list, it appear in fact just as `master-SNAPSHOT`...

I'll try to switch completely all my project to this way and see how that will work out

thanks for your help
