### ISSUE TITLE
android-spinnerwheel/library build issue

### ISSUE THREAD

**Issue by tompad2** [jitpack/jitpack.io#158]
Log https://jitpack.io/com/github/ai212983/android-spinnerwheel/library/build.log

empty page when clicking on Build

**Comment by jitpack-io** [comment]
Hi @tompad2 

That repo is not yet ready but will be after this PR is merged https://github.com/ai212983/android-spinnerwheel/pull/57

In the mean time this fork works: https://jitpack.io/#jitpack-io/android-spinnerwheel/0.1

**Comment by tompad2** [comment]
Ok, thanks!
