### ISSUE TITLE
Java 9 support

### ISSUE THREAD

**Issue by jitpack-io** [jitpack/jitpack.io#1592]
- install Java 9 on build servers
- allow specifying java 9 in jitpack.yml
- autodetect if project is using java 9

**Comment by jitpack-io** [comment]
Now supported in jitpack.yml https://jitpack.io/docs/BUILDING/#build-customization:
```yml
jdk: 
 - oraclejdk9
```

**Comment by sormuras** [comment]
A current [build log](https://jitpack.io/com/github/sormuras/beautiful_logger/bach-632db6d3e1-1/build.log) reports:

```
java 9
Java(TM) SE Runtime Environment (build 9+181)
Java HotSpot(TM) 64-Bit Server VM (build 9+181, mixed mode)
```

Is it possible to update the version?

OpenJDK *9.0.4* is available from http://jdk.java.net/9/
OpenJDK *jdk-10-ea+42*  is available from http://jdk.java.net/10/

**Comment by jitpack-io** [comment]
@sormuras Updated to 9.04

**Comment by JavaSaBr** [comment]
When I setup oraclejdk9, I see that jitpack uses openJDK9. It isn't correct, because oracleJDK includes javaFX, but openJDK doesn't.

**Comment by xzel23** [comment]
Sorry, but how is this an enhancement? Java 9 support is advertised, but it is incomplete. Alas, JavaFX has been part of Java SE for 5 years now:

> [As of JavaFX 2.2 and Java SE 7 update 6, the JavaFX libraries are installed as part of Java SE; a standalone version of JavaFX 2.2 will remain available for Java SE 6 users (Windows only) until Java SE 6 reaches End-of-Life in February 2013](http://www.oracle.com/technetwork/java/javafx/overview/faq-1446554.html#5)
