### ISSUE TITLE
MaterialPreferenceLibrary/3 build issue

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [jitpack/jitpack.io#160]
Log https://jitpack.io/com/github/AndroidDeveloperLB/MaterialPreferenceLibrary/3/build.log

Why can't I let other people use this release?

**Comment by jitpack-io** [comment]
It appears someone tried to install version 3 before the release was published on GitHub. So JitPack remembered that no such version exists and wasn't retrying. 
Going to change this behaviour so that it does re-try.

In the meantime rebuilt version 3 and its available now.

**Comment by AndroidDeveloperLB** [comment]
This is quite impossible, as I've put version 3, and only then I've published that it's available.
Also, Why should it be removed? Maybe there was a connection/server error, and it just needs to be re-checked soon after...

**Comment by AndroidDeveloperLB** [comment]
Anyway thank you. Hope now it works fine.
