### ISSUE TITLE
[Feature Request] Exclude specific submodules

### ISSUE THREAD

**Issue by AllanWang** [jitpack/jitpack.io#1615]
I have a library with many submodules, and one of them is a sample app. I automate building it through travis and I have private encrypted files that are used to sign the app. This module is not necessary for the library, but Jitpack will still try to compile it and fail because the files are still encrypted. Is there any way to "ignore" the module?

As of now the workaround is to check if the file exists first and ignore signing if it doesn't

**Comment by jitpack-io** [comment]
One option is to configure your build to exclude the module when it is being built on JitPack.
All builds have an environment variable "JITPACK" that is set to "true" that your build can check.

**Comment by AllanWang** [comment]
Thank you. I've resolved this by simply adding

```gradle
if (!System.env.JITPACK)
    include ':sample'
```

For future reference for other devs, the environment variables are specified [here](https://jitpack.io/docs/BUILDING/#build-environment)

**Comment by Osiris-Team** [comment]
Hey has anyone here a solution for maven?
