### ISSUE TITLE
bitreserve-sdk-android/b80d81aee3 build issue

### ISSUE THREAD

**Issue by SandroMachado** [jitpack/jitpack.io#162]
@jitpack-io Can you please tell me where I can set the location of the build.gralde? Or it needs to be in the root of the repository? My build.gradle is inside a folder and not in the root of repository.

You can find the repo here: https://github.com/bitreserve/bitreserve-sdk-android

Log https://jitpack.io/com/github/bitreserve/bitreserve-sdk-android/b80d81aee3/build.log

**Comment by jitpack-io** [comment]
Hi @SandroMachado 

A build file needs to be in the root or in a subfolder. In that repo the buildfile is two levels deep and JitPack won't find it.
