### ISSUE TITLE
ultimatedogg/maven-python-distribute-plugin

### ISSUE THREAD

**Issue by UltimateDogg** [jitpack/jitpack.io#1621]
Hello,

https://jitpack.io/com/github/ultimatedogg/maven-python-distribute-plugin/3b40f78979/build.log shows as success and when i go to https://jitpack.io/com/github/ultimatedogg/maven-python-distribute-plugin/3b40f78979/ i do see the build output but going to https://jitpack.io/com/github/ultimatedogg/maven-python-distribute-plugin/maven-metadata.xml produces no file and so the maven builds that depend on this file dont work. Do i need to do anything else to get it to showup?

**Comment by jitpack-io** [comment]
Hi,

Looks like the latest release hadn't been built which is why metadata didn't show up. Should be working now:
https://jitpack.io/com/github/ultimatedogg/maven-python-distribute-plugin/maven-metadata.xml

**Comment by UltimateDogg** [comment]
Hey yes it looks like it did build when i incremented to a new version. Odd it didnt show up for the first one.

Thanks!
