### ISSUE TITLE
I have many library in one Repo，how can i distinguish them to pack？

### ISSUE THREAD

**Issue by MasonLiuChn** [jitpack/jitpack.io#163]

**Comment by jitpack-io** [comment]
Hi @MasonLiuChn 

Sounds like you are using a project with multiple modules. If you are using standard JitPack dependency then you'll get all modules. If you want just some of them then there's documentation here: 
https://jitpack.io/docs/BUILDING/#multi-module-projects

Does that help? If not we can have a look at your repo
