### ISSUE TITLE
Support for multiple-libraries repos

### ISSUE THREAD

**Issue by bryant1410** [jitpack/jitpack.io#165]
In [GreenDAO](https://github.com/greenrobot/greenDAO) they have multiple libraries in their repo, like the core, the generator and examples. It would be nice if we could add a dependency to just one of them

**Comment by jitpack-io** [comment]
Hi,

Multi-module projects are supported and you can get them individually https://jitpack.io/docs/BUILDING/#multi-module-projects
For V1.3.7 of GreenDAO there are tree modules:
- com.github.greenrobot.greenDAO:**DaoCore**:V1.3.7
- com.github.greenrobot.greenDAO:**DaoExampleGenerator**:V1.3.7
- com.github.greenrobot.greenDAO:**DaoGenerator**:V1.3.7

All the modules are listed in the project's root pom:
https://jitpack.io/com/github/greenrobot/greenDAO/V1.3.7/greenDAO-V1.3.7.pom

**Comment by bryant1410** [comment]
Ah, didn't realize. Thanks!
