### ISSUE TITLE
groovy-maven-jacoco/SNAPSHOT build issue

### ISSUE THREAD

**Issue by bytekast** [jitpack/jitpack.io#166]
Log https://jitpack.io/com/github/bytekast/groovy-maven-jacoco/SNAPSHOT/build.log

Hi I am a paid subscriber but I seem to be having lots of issues when using the SNAPSHOT builds.

Can you please take a look at this sample project

**Comment by jitpack-io** [comment]
Hi @bytekast 

There was a problem getting snapshots from Maven for repositories that don't have any tags. It was working from Gradle but now the issue is fixed for Maven as well. This works:
```xml
   <dependency> 
        <groupId>com.github.bytekast</groupId>
        <artifactId>groovy-maven-jacoco</artifactId>
        <version>-SNAPSHOT</version>
    </dependency>
```

Sorry for the inconvenience. Would be great to hear if it works for you as well.
