### ISSUE TITLE
kotlinx.html/jsoup-support-kotlinx-html-0.6.3-gdb94b08-13 build

### ISSUE THREAD

**Issue by apsoyka** [jitpack/jitpack.io#1667]
Log https://jitpack.io/com/github/ddsoyka/kotlinx.html/jsoup-support-kotlinx-html-0.6.3-gdb94b08-13/build.log

The project builds successfully on my local machine.

**Comment by jitpack-io** [comment]
Hi,

The project seems to rely on `karma` which is not available on the build machine.
Could it be installed before the build with a custom command?
https://jitpack.io/docs/BUILDING/#build-customization
