### ISSUE TITLE
uniter/0.0.2 build

### ISSUE THREAD

**Issue by cortexdesign** [jitpack/jitpack.io#1669]
I need some help with my android library written in Kotlin and build with gradle (4.1-milestone-1). I tryed to deploy it with jitpack but with no success 
Log https://jitpack.io/org/bitbucket/MG83/uniter/0.0.2/build.log

**Comment by cortexdesign** [comment]
Is gradle 4.1 supported?
https://github.com/dcendents/android-maven-gradle-plugin
3.0+ is the latest supported version...

**Comment by jitpack-io** [comment]
Hi @cortexdesign 

Gradle 4.1 is partially supported. Projects with Gradle 4.1 should build fine and will get published.

There is an open issue `https://github.com/dcendents/android-maven-gradle-plugin/issues/61`
to support api/implementation dependencies.

**Comment by jitpack-io** [comment]
In the uniter project `mvvm/build.gradle` defines the group property.
It should be just:
`group='org.bitbucket.MG83'`

**Comment by cortexdesign** [comment]
Ah, thank you so much! 

This fixed my issue
> group='org.bitbucket.MG83'
