### ISSUE TITLE
Build private GitHub repositories

### ISSUE THREAD

**Issue by jitpack** [jitpack/jitpack.io#17]
Users will need to grant JitPack access

**Comment by ciela** [comment]
+1
I look forward to it.

**Comment by syama666** [comment]
+1
Amazing!

**Comment by smiklosovic** [comment]
Any progress on this?

**Comment by jitpack-io** [comment]
@smiklosovic The development of this feature is ongoing. There'll be an option to build a private repo with public jar or keep the jar private. Which one would you be after? Thanks for checking in!

**Comment by smiklosovic** [comment]
i basically need to build something in private repository and i need to keep that jar private. I do not understand the difference between public and private jar. Could you elaborate?

**Comment by jitpack-io** [comment]
A public jar would be available to everyone just like jars from public repositories right now. So in gradle you would add `compile 'com.github.User:PrivateRepo:Tag'`. 
A private jar would be protected by authentication and would only be available to you for download.

**Comment by smiklosovic** [comment]
yes, so I am for the latter option - private jars kept private and protected by authentication.

**Comment by smiklosovic** [comment]
in the end ... it seem like these options are equal. I think that it is "hard" to guess the name of your private repository from blue sky. However, if that ever happen, I would protect it by authentication so leaking of private builds are impossible for outsiders.

**Comment by dbachelder** [comment]
how will the authentication work?

**Comment by jitpack-io** [comment]
@dbachelder You'll get an authentication token on the JitPack website and it will be used in credentials:
```gradle
maven { 
 url "https://jitpack.io"
 credentials { username "myUniqueAuthenticationToken" }
}
```

**Comment by jitpack-io** [comment]
Good news everyone! JitPack just added private repository support.
Here's a link to get started: https://jitpack.io/private
Let us know what you think!

**Comment by smiklosovic** [comment]
@snatchev

**Comment by jitpack-io** [comment]
@smiklosovic Was that a notification?

**Comment by smiklosovic** [comment]
@jitpack-io yes I wanted to notify my colleague about this exciting feature :)

**Comment by ppamorim** [comment]
+1

**Comment by jitpack-io** [comment]
Big thanks to everyone who tested private repository builds! We can probably now close this issue.
Happy building!
