### ISSUE TITLE
Swipecards/1.0.8 build issue

### ISSUE THREAD

**Issue by X4mp** [jitpack/jitpack.io#172]
Log https://jitpack.io/com/github/zamliman/Swipecards/1.0.8/build.log

**Comment by jitpack-io** [comment]
Hi @X4mp 
Some changes to the project are required for the build to succeed. 
There are instructions in https://jitpack.io/docs/ but can also give you specific changes here.

**Comment by X4mp** [comment]
@jitpack-io  it looks like the problem is due to the multi module project I tried to include.
according to #29 there must not be a example app module which depends on the library.

I forked to lib and removed the 'example' module, but I can't rebuild it on jitpick.io because you have cached the old 'multi-project' build.  How long do I have to wait until I can rebuild it?

cheers

**Comment by jitpack-io** [comment]
It won't be re-built on its own. If you have push permissions to the repository then you can login on jitpack.io and remove the broken build.
