### ISSUE TITLE
Downloading external dependency fails (sora-android-sdk/1.1.0-rc1 build)

### ISSUE THREAD

**Issue by shino** [jitpack/jitpack.io#1728]
Hi Team,

First of all, thanks a lot for fabulous platform for maven/gradle and git/github collaboration 👍 

Now I have build failure on jitpack
Log https://jitpack.io/com/github/shiguredo/sora-android-sdk/1.1.0-rc1/build.log

The project [1] is for android library and its build includes downloading AAR file from
public accessible URL [2]

My questions are:
- Can I access network/internet and download files inside jitpack building environment?
- Does jitpack.io support multiple module gradle project?

Thanks again

[1] https://github.com/shiguredo/sora-android-sdk
[2] https://github.com/shiguredo/sora-webrtc-android/releases/download/60.11.0/libwebrtc.aar.zip

**Comment by shino** [comment]
Additional notes:

- I confirmed gradle build works in my local (laptop) environment by `./gradlew assembleRelease` including downloading a file.
- If there is a way to set debugging build switch like `./gradlew --stacktrace` or `./gradlew --info`, it's very helpful. But,  now, I couldn't find a doc which mentions about it.

**Comment by jitpack-io** [comment]
Hi @shino 

Hard to say why the build fails. Tried to download libwebrtc.aar.zip from one of the build servers and it is accessible. There is an error message about a cookie but that's about it.
To answer your questions:
- You can download external files from the internet.
- Multi module gradle projects are supported https://jitpack.io/docs/BUILDING/#multi-module-projects
- It's possible to set debugging with custom build commands: https://jitpack.io/docs/BUILDING/#build-customization

**Comment by shino** [comment]
@jitpack-io Thanks for fast reply! I will try custom build commands.

**Comment by shino** [comment]
Thanks for your help. Everything works perfect 😄 

For downloading error, it was my fault (working directory and relative path thing..). I apologize for that.

Thanks again both nice service and kind help!
