### ISSUE TITLE
android-shapeLoadingView/2e02de9e1d build issue

### ISSUE THREAD

**Issue by george5613** [jitpack/jitpack.io#174]
Log https://jitpack.io/com/github/zzz40500/android-shapeLoadingView/2e02de9e1d/build.log

**Comment by jitpack-io** [comment]
Hi @george5613 
There seems to be an error with resources:
```
Position 4:25-47 : No resource found that matches the given name (at 'background' with value '@drawable/aa_dialog_bg'
```
It needs to fixed in the project itself.
