### ISSUE TITLE
Add License to POM file automatically

### ISSUE THREAD

**Issue by tynn** [jitpack/jitpack.io#1744]
Google released a [License Activity](https://developers.google.com/android/guides/opensource) using the data provided with the POM file.

Many repositories contain a kind of _LICENSE_ file. Maybe named with an extension like _LICENSE.txt_. This data could be analyses and [written to the POM file](https://maven.apache.org/pom.html#Licenses) automatically.

This would make it even more easy to use _JitPack_ productively.

**Comment by jitpack-io** [comment]
Hi,

This should already be happening.
JitPack uses GitHub API to detect the license and adds it to the pom.
If pom already has a license then it keeps it.

**Comment by tynn** [comment]
Ok, I'll check further; maybe my builds where too old.

**Comment by tynn** [comment]
It seems to be an issue with my license files, though I think it was working _GitHub_ before. I tried to build a commit of [tynn/auto-value-factory](https://github.com/tynn/auto-value-factory) which has the license displayed at _GitHub_, but none was added to the POM file. Anything else I'm missing here?

**Comment by Zhuinden** [comment]
This seems to have stopped happening sometime between March and July.
