### ISSUE TITLE
disruptor-proxy/2ef4491aa4 build issue

### ISSUE THREAD

**Issue by sirinath** [jitpack/jitpack.io#176]
Log https://jitpack.io/com/github/LMAX-Exchange/disruptor-proxy/2ef4491aa4/build.log

Above does not build.

**Comment by jitpack-io** [comment]
Hi @sirinath 

All that's needed is the maven plugin:
https://github.com/jitpack/gradle-simple/blob/master/build.gradle#L2

Then it should build.

**Comment by sirinath** [comment]
This is not my repo. I can send a PR but I will be great if you can find a way to use it without having this option.

**Comment by jitpack-io** [comment]
Agree, would be much more convenient. Will look into that so let's keep this issue open

**Comment by jitpack-io** [comment]
Fixed and rebuilt that version
