### ISSUE TITLE
No read access to repo

### ISSUE THREAD

**Issue by SureshSc** [jitpack/jitpack.io#1808]
When i try to put repo in GitLab i am getting **No read access to repo**

[Repo URL](https://gitlab.com/suresh.chandrababu/MaterialChipsInput/)

**Comment by AllanWang** [comment]
It may be due to the period in your name?

**Comment by jitpack-io** [comment]
Hi @SureshSc 

@AllanWang is right, the period in the username causes the error.
At the moment these kind of repositories are not supported.

**Comment by imrantoolyt** [comment]
facing the same issue. https://i.stack.imgur.com/Y12ds.png

**Comment by Hokwai** [comment]
Has someone fixed it?I meet it and don't know how to fix.
