### ISSUE TITLE
build issue johncarl81/transfuse

### ISSUE THREAD

**Issue by dbachelder** [jitpack/jitpack.io#181]
Could not find artifact com.android.support:support-v4:aar:22.2.0 in central (https://repo.maven.apache.org/maven2) -> [Help 1]

https://jitpack.io/com/github/johncarl81/transfuse/79b17d9a5219a00676a8ee08911ec3adc6c9ac76/build.log

**Comment by jitpack-io** [comment]
Fixed! 
Android jars that were installed in the local maven repository were missing. We did some internal cleanup of docker images and forgot to include these in the new image, sorry about that.
