### ISSUE TITLE
no jar download of gradle subproject - brainless-studios/openrts

### ISSUE THREAD

**Issue by meltzow** [jitpack/jitpack.io#185]
Hi,

while the pom is downloadable: 
https://jitpack.io/com/github/brainless-studios/openrts/core/-SNAPSHOT/core--11241a6153-1.pom
the jar file is not found (HTTP 404): 
https://jitpack.io/com/github/brainless-studios/openrts/core/-SNAPSHOT/core--11241a6153-1.jar

thats my gradle build debug log:
15:31:52.114 [ERROR] [org.gradle.BuildExceptionReporter] * What went wrong:
15:31:52.114 [ERROR] [org.gradle.BuildExceptionReporter] Could not resolve all dependencies for configuration ':compile'.
15:31:52.114 [ERROR] [org.gradle.BuildExceptionReporter] > Artifact 'core.jar (com.github.brainless-studios.openrts:core:-SNAPSHOT)' not found.
15:31:52.114 [ERROR] [org.gradle.BuildExceptionReporter]   Searched in the following locations:
15:31:52.114 [ERROR] [org.gradle.BuildExceptionReporter]       https://jitpack.io/com/github/brainless-studios/openrts/core/-SNAPSHOT/core--11241a6153-1.jar

in build.gradle i just add: 
compile 'com.github.brainless-studios.openrts:core:-SNAPSHOT' 

why the core jar isn't found?

thx.

**Comment by jitpack-io** [comment]
Hi @meltzow 
That should have worked. Investigating...

**Comment by jitpack-io** [comment]
Ok it looks like the jar file is quite large (61M) and that causes some issues for transport between build servers and web servers. Will be working on a fix
Thanks for raising the issue!

**Comment by meltzow** [comment]
thanks for feedback. So I will wait.

**Comment by jitpack-io** [comment]
Should be fixed now. Turns out we had time-out settings too eager for files this size. Apologies for the hiccup
