### ISSUE TITLE
SDK-Android/v0.7.1 build

### ISSUE THREAD

**Issue by Sushma7785** [jitpack/jitpack.io#1879]
Error: You have not accepted the license agreements of the following SDK components:
  [CMake 3.6.4111459].
Log https://jitpack.io/com/github/YUNEEC/Yuneec-SDK-Android/v0.7.1/build.log

**Comment by julianoes** [comment]
For travis-ci, we were able to fix this by adding:
```
echo "y" | sdkmanager "cmake;3.6.4111459"
```
For jitpack, we're not sure what to do.

**Comment by wangdongyi** [comment]
I can  run  on myself  ，where I  can  add  echo "y" | sdkmanager "cmake;3.6.4111459"

**Comment by julianoes** [comment]
@wangdongyi I added this for travis-ci to fix this problem. I don't know how this can be used for jitpack.

**Comment by jitpack-io** [comment]
JitPack also supports custom commands

**Comment by julianoes** [comment]
@jitpack-io thanks for responding. What does that mean?

Could we do: `echo "y" | sdkmanager "cmake;3.6.4111459"` ?

**Comment by jitpack-io** [comment]
Yes, that should work https://jitpack.io/docs/BUILDING/#build-customization

Sdkmanager might not be on the path but the $ANDROID_HOME environment variable is available

**Comment by julianoes** [comment]
Thanks a lot @jitpack-io.

We were able to fix it by adding the file `jitpack.yml` with the contents below:

```
before_install:
  - echo "Running a custom install command to fix cmake license issue"
  - echo "y" | $ANDROID_HOME/tools/bin/sdkmanager "cmake;3.6.4111459"
```
