### ISSUE TITLE
can't find log4j version

### ISSUE THREAD

**Issue by dtracers** [jitpack/jitpack.io#188]
https://jitpack.io/com/github/pjklauser/protobuf-rpc-pro/1.1.0/build.log

But when I run it locally on my computer it does not fail to find log4j.

In the project itself they use slf4j and logback but not log4j so I do not think it is anything the project maintainer can fix.

**Comment by jitpack-io** [comment]
What's interesting is that the groupId is apache-log4j. Which is different from the one in maven central. Need to look more into this...

**Comment by dtracers** [comment]
so I don't know why this specific problem is but he removed the releases and using the latest commit hash it builds fine.

So I in my mind it is fixed.  :+1: 

https://jitpack.io/com/github/pjklauser/protobuf-rpc-pro/57efac2b9f25f5163409606161cef17ba86c3330/build.log

**Comment by jitpack-io** [comment]
fair enough, might have been an outdated release. glad it's fixed!
