### ISSUE TITLE
Build error in Gradle project

### ISSUE THREAD

**Issue by cypressious** [jitpack/jitpack.io#19]
When I try to include a gradle project (https://github.com/cypressious/MaterialEditText) in my app, I get the following error:

```
Error:Could not GET 'https://jitpack.io/com/github/cypressious/MaterialEditText/1.8.2/MaterialEditText-1.8.2.pom'. Received status code 500 from server: Not found
<a href="toggle.offline.mode">Enable Gradle 'offline mode' and sync project</a>
```

On your webpage it also says "Build error" for the corresponding version and the log says:

```
Running: gradle --daemon -Pgroup=com.github.cypressious -Pversion=1.8.2.1 install
RELEASE BUILD

FAILURE: Build failed with an exception.

* What went wrong:
Task 'install' is ambiguous in root project 'build'. Candidates are: 'installDebug', 'installDebugTest'.

* Try:
Run gradle tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
```

**Comment by jitpack** [comment]
Hello!

It looks like the android-maven plugin is not enabled on MaterialEditText project.
Adding it is quite easy: https://github.com/jitpack/jitpack.io/blob/master/ANDROID.md

**Comment by cypressious** [comment]
Thanks for the quick reply. I added the dependency classpath and plugin to the library subproject. On my machine I can run ```gradlew install``` but on jitpack it still fails. Here's the log: https://www.jitpack.io/com/github/cypressious/MaterialEditText/1.8.2.2/build.log

**Comment by jitpack** [comment]
Ok, I think the problem now is that the android-maven plugin isn't added to the root build.gradle file. We have an example here: https://github.com/jitpack/android-example/blob/master/build.gradle#L9

**Comment by cypressious** [comment]
You're right, semms like I forgot to commit the file.
