### ISSUE TITLE
Gradle wrapper not found even adding it to the repository.

### ISSUE THREAD

**Issue by sandro-csimas** [jitpack/jitpack.io#1918]
I commited the embedded gradle on my repository, but its not working.
````
gradle / wrapper /
    gradle-wrapper.jar
    gradle-wrapper.properties
````
Log https://jitpack.io/org/bitbucket/chatz/chatz-android/0.0.2/build.log
````
ERROR: Gradle wrapper not found. Please add. Using default gradle to build.
````

**Comment by sandro-csimas** [comment]
OK, solved! It was missing gradlew file on the project root folder.

**Comment by Poul-xtf** [comment]
Hello, I also encountered this problem, can you tell me your solution?

**Comment by eliasmeireles** [comment]
> Hello, I also encountered this problem, can you tell me your solution?

I've solved the problema just adding the gradlew and gradle from root project folder to git.

![Screen Shot 2020-11-08 at 07 42 46](https://user-images.githubusercontent.com/13203692/98462856-09e8e100-2196-11eb-9827-ab12f9480ca3.png)

**Comment by SHamzaHMergn** [comment]
Any update on this ?
