### ISSUE TITLE
401 from public repository

### ISSUE THREAD

**Issue by ben-manes** [jitpack/jitpack.io#1939]
When upgrading my dependencies, it failed with the newer version or ErrorProne.

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':caffeine:compileJavaPoetJava'.
> Could not resolve all files for configuration ':caffeine:errorprone'.
   > Could not resolve com.github.stephenc.jcip:jcip-annotations:1.0-1.
     Required by:
         project :caffeine > com.google.errorprone:error_prone_core:2.1.2
      > Could not resolve com.github.stephenc.jcip:jcip-annotations:1.0-1.
         > Could not get resource 'https://jitpack.io/com/github/stephenc/jcip/jcip-annotations/1.0-1/jcip-annotations-1.0-1.pom'.
            > Could not HEAD 'https://jitpack.io/com/github/stephenc/jcip/jcip-annotations/1.0-1/jcip-annotations-1.0-1.pom'. Received status code 401 from server: Unauthorized
```

The dependency is on Maven Central. However, the unauthorized response causes the build to fail immediately rather than query other repositories.

**Comment by ben-manes** [comment]
In this case, I was able to work around it by using a dependency substitution. I think a 401 is too strong of an error to return and either jitpack needs to uses 404 or request that Gradle not halt on this response.

```gradle
configurations.all {
  resolutionStrategy.dependencySubstitution {
    substitute module('com.github.stephenc.jcip:jcip-annotations') with module('net.jcip:jcip-annotations:1.0')
  }
}
```

**Comment by jitpack-io** [comment]
Hi Ben,

Is mavenCentral() above `jitpack.io` in the repositories section?

JitPack is returning unauthorized because github.com/stephenc/jcip is not accessible. It could mean its not there or it could be a private repository which requires authentication. If we always returned 404 then Gradle would not try to authenticate.
Agree that Gradle should not be stopping on 401.

**Comment by ben-manes** [comment]
Okay, that seems to work. Thanks!

**Comment by kaushil111** [comment]
I am having the same issue. Here is build.gradle:
```
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        google()
        jcenter()
        maven {
            url 'https://maven.fabric.io/public'
        }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.2.1'
        classpath 'com.google.gms:google-services:4.1.0'
        classpath 'io.fabric.tools:gradle:+'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        google()
        maven { url "$rootDir/../node_modules/react-native/android" }
        maven { url "https://jitpack.io" }
        jcenter()
    }
}

```

**Comment by jcornaz** [comment]
This issue is obviously not solved. I also encounter the same problem using a public repository: https://jitpack.io/#jcornaz/collekt

@jitpack-io: please reopen the issue.

**Comment by jitpack-io** [comment]
@jcornaz Perhaps you can open a new issue with details of your project? Will have a look

**Comment by jcornaz** [comment]
@jitpack-io. It seems to work right now. 

I suspect I did a mistake in the coordinate. However if it is the case a `404` would be more meaningful and would help finding the issue.

**Comment by csquan** [comment]
not solved ,is there any bug ?
