### ISSUE TITLE
Mu5ViewPager/v1.0 build

### ISSUE THREAD

**Issue by JmStefanAndroid** [jitpack/jitpack.io#1946]
Log https://jitpack.io/com/github/JmStefanAndroid/Mu5ViewPager/v1.0/build.log

**Comment by qssq** [comment]
66,jcenter你还能用吗我现在已经添加到jcenter了也审核通过了的但是就是看不到 而且我打开bintray地址查看了 我的有些库是成功了，但是某些却没有。所以我才转jitpack.io

**Comment by JmStefanAndroid** [comment]
已解决，需要在liibrary中上传自己的gradle文件夹，否则找不到gradle的配置
