### ISSUE TITLE
RxBonjour/0.3.0 build issue

### ISSUE THREAD

**Issue by aurae** [jitpack/jitpack.io#199]
Log https://jitpack.io/com/github/aurae/RxBonjour/0.3.0/build.log
The `build.gradle` in question: https://github.com/aurae/RxBonjour/blob/master/lib/build.gradle

**Comment by jitpack-io** [comment]
Hi @aurae 
Fixed and rebuilt! Sorry for the hiccup. 
Would recommend adding the android-maven plugin to your build file https://jitpack.io/docs/ANDROID/

**Comment by aurae** [comment]
I'll look into that. Thanks for the quick response!
