### ISSUE TITLE
"Build error" in GitPack UI and "BUILD SUCCESS" in Maven logs

### ISSUE THREAD

**Issue by vbauer** [jitpack/jitpack.io#20]
You can check it using this repo: https://github.com/vbauer/commons-vfs2-cifs
Just look it up using search form on home page (https://jitpack.io)

*UPD:* logs: https://jitpack.io/com/github/vbauer/commons-vfs2-cifs/1.0.0/build.log

**Comment by jitpack** [comment]
Fixed the build status: https://jitpack.io/#vbauer/commons-vfs2-cifs

I think the groupId is confusing the build. Sent you a PR to change it and got it building my own fork.

**Comment by vbauer** [comment]
Hmm.. Maybe you're right.

JFYI: Strange, but it worked on my another repository (with incorrect groupId): https://github.com/vbauer/avconv4java

**Comment by jitpack** [comment]
Yes, normally a different groupId isn't be a problem but with org.apache.commons things got tricky. It's a bug in jitpack so will leave this ticket open

**Comment by vbauer** [comment]
Btw, thank you for quick response and PR! I've already fixed it on the second repo.

**Comment by jitpack** [comment]
Nice one! :+1:

**Comment by jitpack-io** [comment]
Ok, this should be now resolved
