### ISSUE TITLE
android-viewbadger/master build issue

### ISSUE THREAD

**Issue by whaleswallce** [jitpack/jitpack.io#200]
Log https://jitpack.io/com/github/jgilfelt/android-viewbadger/master/build.log

**Comment by jitpack-io** [comment]
Hi @whaleswallce 
'master' is not a version syntax that we support. You could try a commit id or the `-SNAPSHOT` version. Snapshot will build from the master branch.

**Comment by jitpack-io** [comment]
Also see this issue https://github.com/jitpack/jitpack.io/issues/115
