### ISSUE TITLE
"Unable to resolve" some releases, but others pass

### ISSUE THREAD

**Issue by nanooq** [jitpack/jitpack.io#2000]
This issue is about resolving releases of projects where some releases pass and others fail.

I want to resolve to the current [geckodriver](https://github.com/mozilla/geckodriver/releases), but Idea tells me, it is not able to do so:
```com.github.mozilla:geckodriver:v0.19.1``` 
-> not resolvable. 

I then started cut'n'pasted a few examples from the internet using jetpack.io. 
```compile 'com.github.jitpack:android-example:1.0.1```
-> resolvable

The current tag is "1.0.4", so I changed the tag.
```compile 'com.github.jitpack:android-example:1.0.4```
-> not resolvable

I then tried the previous release "1.0.3", because the current one is also tagged "latest" and maybe things get mangled:
```compile 'com.github.jitpack:android-example:1.0.3```
-> resolvable. And previous releases ones, too.

So, I then tried the previous version of the geckodriver I want to use "v0.19.0":
```com.github.mozilla:geckodriver:v0.19.0``` 
-> not resolvable. nor any previous releases.

Resolving using short commits hashes behaved similarly.

**Comment by jitpack-io** [comment]
Hi,

It is not resolvable because the builds failed: https://jitpack.io/#mozilla/geckodriver
