### ISSUE TITLE
android-range-seek-bar doesn't work as multi-module project

### ISSUE THREAD

**Issue by bryant1410** [jitpack/jitpack.io#201]
I try with this fork, but doesn't catch the module:

```groovy
compile 'com.github.xmartlabs.android-range-seek-bar:rangeseekbar:dd4768c773'
```

It only works as a non mult-module project.

**Comment by jitpack-io** [comment]
Hi @bryant1410 

Looks like the project has a library and a sample project. Only the library is published so from JitPack's point of view its a single module. 
On the other hand its possible to publish the sample if you like.

**Comment by bryant1410** [comment]
Where it's published?

**Comment by jitpack-io** [comment]
Just meant that by default JitPack only publishes libraries. Internally it uses the https://github.com/dcendents/android-maven-gradle-plugin#note-on-releases plugin to publish to local maven repository ($HOME/.m2). 

But its also possible to apply the plugin to apps. Then both will be published and each will be in a separate module.

**Comment by bryant1410** [comment]
Oh, so great!
