### ISSUE TITLE
material-range-bar/v1.0.1-fork build issue

### ISSUE THREAD

**Issue by hide92795** [jitpack/jitpack.io#202]
Log https://jitpack.io/com/github/hide92795/material-range-bar/v1.0.1-fork/build.log

Same commit (9afae7c0d8) has been successful to build.
Could you re-run the build?

**Comment by jitpack-io** [comment]
Rebuilt!
Btw, if you like you can rebuild your repos too https://jitpack.io/docs/BUILDING/#rebuilding
