### ISSUE TITLE
Can't get a multi-module Android library to work

### ISSUE THREAD

**Issue by afollestad** [jitpack/jitpack.io#203]
The library is here: https://github.com/afollestad/material-dialogs. I'm using a custom domain, so the group is `com.afollestad`.

The project contains a `core` module, and a `commons` module. Android Studio is unable to find the individual modules (e.g. with `compile 'com.afollestad:material-dialogs:core:0.8.0.0`). I also need it to be an AAR, since the library contains resources, but using the @aar suffix doesn't seem to work.

I did include the repository, also. A few of my other projects use JitPack, but I decided to switch this one over today since Bintray has become too complex.

**Comment by afollestad** [comment]
The library is here: https://github.com/afollestad/material-dialogs. I'm using a custom domain, so the group is `com.afollestad`.

The project contains a `core` module, and a `commons` module. Android Studio is unable to find the individual modules (e.g. with `compile 'com.afollestad:material-dialogs:core:0.8.0.0`). I also need it to be an AAR, since the library contains resources, but using the @aar suffix doesn't seem to work.

I did include the repository, also. A few of my other projects use JitPack, but I decided to switch this one over today since Bintray has become too complex.

**Comment by jitpack-io** [comment]
Hi @afollestad 

The 0.8.0.0 release seems to be missing https://github.com/afollestad/material-dialogs/releases

**Comment by afollestad** [comment]
Hi, @jitpack-io,

I had deleted it so users of my library didn't see it. I published the release again now so you can see it.

https://github.com/afollestad/material-dialogs/releases/tag/0.8.0.0

**Comment by jitpack-io** [comment]
Got it, makes sense.

It could be that there is a small typo in the dependency:
```
compile 'com.afollestad:material-dialogs:core:0.8.0.0' 
compile 'com.afollestad.material-dialogs:core:0.8.0.0' // should be this
```

Apart from that everything seems to work.

**Comment by afollestad** [comment]
Wow, no wonder, thanks for your help!

**Comment by jitpack-io** [comment]
No worries, enjoy!:)
