### ISSUE TITLE
Received status code 401 from server: Repository not found or requires authentication

### ISSUE THREAD

**Issue by joselufo** [jitpack/jitpack.io#204]
Hi,

I have upload my library and seems that everything is working but then when I add my library to some project I'm receiving the error 

**Could not GET 'https://jitpack.io/com/github/mobilejazz/library/0.1/library-0.1.pom'. Received status code 401 from server: Repository not found or requires authentication**

Jitpack link: https://jitpack.io/#mobilejazz/cacheio
Github link: https://github.com/mobilejazz/CacheIO

**Comment by jitpack-io** [comment]
Hi @joselufo 

Looks like it works with your latest changes. Now the library is published and instead of the apk: 
https://jitpack.io/#mobilejazz/cacheio/c269866d38

**Comment by joselufo** [comment]
@jitpack-io Thanks for the answer!

I don't know why if I use the version tag doesn't work because I receive this error:

** compile 'com.github.mobilejazz:cacheio:0.2'**

**Warning:Dependency com.github.mobilejazz:cacheio:0.2 on project app resolves to an APK archive which is not supported as a compilation dependency. File: /Users/user/.gradle/caches/modules-2/files-2.1/com.github.mobilejazz/cacheio/0.2/178f629a73143f5dfe6c2d13fb77ef39507fb31f/cacheio-0.2.apk**

but if I use the last commit works:

**compile 'com.github.mobilejazz:cacheio:c269866d38'**

I don't know what's going on.

**Comment by jitpack-io** [comment]
It appears version 0.2 does not have the very latest changes. Creating a new release should work

**Comment by joselufo** [comment]
@jitpack-io Yes, now it's working. Thanks!
