### ISSUE TITLE
mv2m/0.1.1 build issue

### ISSUE THREAD

**Issue by fabioCollini** [jitpack/jitpack.io#206]
Log https://jitpack.io/com/github/fabioCollini/mv2m/0.1.1/build.log

**Comment by jitpack-io** [comment]
Hi @fabioCollini 
Looks like you got it working with 0.1.5. Should we close this issue?

**Comment by fabioCollini** [comment]
No, I fixed it reverting to previous version. Can you add latest version of support testing library?
Thanks!

**Comment by jitpack-io** [comment]
Added.
