### ISSUE TITLE
jitpack is asking for token for public github repo with submodule

### ISSUE THREAD

**Issue by kilokahn** [jitpack/jitpack.io#2063]
Thanks for the amazing tool!
I am fairly certain that I am messing up the submodule scheme, but I can't figure it out myself. I am trying to access:

```
dependencies {
    compile 'com.github.Kotlin.kotlinx.cli:kotlinx.cli.jvm:2bb0196241'
}
```
It is failing with a `401` as :
```
Could not GET 'https://jitpack.io/com/github/Kotlin/kotlinx/cli/kotlinx.cli.jvm/2bb0196241/kotlinx.cli.jvm-2bb0196241.pom'. Received status code 401 from server: Unauthorized
```
https://jitpack.io/#Kotlin/kotlinx.cli/2bb0196241 is the url I used to verify the coordinates

**Comment by jitpack-io** [comment]
Hi,

The dot in project's name is causing an issue because it is a special character in Maven/Gradle dependencies.

**Comment by kilokahn** [comment]
Thanks for getting back on this. The build tool as such seems to be happy with the module name. Just wondering, if it would make sense for jitpack to fine tune its logic to serve this content out as well? Thanks!
