### ISSUE TITLE
fresco/v0.7.0 build issue

### ISSUE THREAD

**Issue by lushan1314** [jitpack/jitpack.io#208]
Log https://jitpack.io/com/github/lushan1314/fresco/v0.7.0/build.log

**Comment by jitpack-io** [comment]
Hi @lushan1314 
We don't support NDK builds yet. There's a ticket for tracking #24

**Comment by jitpack-io** [comment]
@lushan1314 NDK builds are now supported! Rebuilt your repository but there seems to be another error. It would be easy to fix and I can submit a PR if you are interested

**Comment by lushan1314** [comment]
great!
Supported NDK builds is a big milestone.
sure, im interested.can u send email to me?my email address is "wanglushan3344@gmail.com"  .thank u
