### ISSUE TITLE
Toasty/1.2.6 build

### ISSUE THREAD

**Issue by GrenderG** [jitpack/jitpack.io#2088]
Log https://jitpack.io/com/github/GrenderG/Toasty/1.2.6/build.log

Error:
`Could not find com.android.tools.build:gradle:3.0.1.`

**Comment by kirtan403** [comment]
You might need add `google()` maven in your build.gradle ?

**Comment by GrenderG** [comment]
@kirtan03 it is already added.

**Comment by kirtan403** [comment]
I see it is not added, see this lines from log. It has not searched in it: 

```
> Could not find com.android.tools.build:gradle:3.0.1.
     Searched in the following locations:
         https://jcenter.bintray.com/com/android/tools/build/gradle/3.0.1/gradle-3.0.1.pom
         https://jcenter.bintray.com/com/android/tools/build/gradle/3.0.1/gradle-3.0.1.jar
         https://repo1.maven.org/maven2/com/android/tools/build/gradle/3.0.1/gradle-3.0.1.pom
         https://repo1.maven.org/maven2/com/android/tools/build/gradle/3.0.1/gradle-3.0.1.jar
     Required by:
         project :
```

**Comment by GrenderG** [comment]
https://github.com/GrenderG/Toasty/blob/master/build.gradle

**Comment by kirtan403** [comment]
You need to add google() to line number 6.

**Comment by GrenderG** [comment]
Oops, didn't know that.  I have created a new release, do you know how long it will take JitPack to do a build again?

**Comment by kirtan403** [comment]
It will be pretty quick. It will be published by now. That section is used by the dependencies mentioned in the buildscript. What you have mentioned is used by the dependencies for your library module.

**Comment by kirtan403** [comment]
Btw, I have seen your library and its awesome

**Comment by GrenderG** [comment]
Thanks a lot @kirtan403! (The build hasn't occurred yet :disappointed:).

**Comment by jitpack-io** [comment]
Official docs: https://developer.android.com/studio/build/gradle-plugin-3-0-0-migration.html#apply_plugin

```
buildscript {
    repositories {
        ...
        // You need to add the following repository to download the
        // new plugin.
        google()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.0.1'
    }
}
```
