### ISSUE TITLE
Feature Request: Download badge for all time?

### ISSUE THREAD

**Issue by kirtan403** [jitpack/jitpack.io#2092]
I see download badges for weekly and monthly downloads. Is there any way to get download badge of all time? Not monthly, but in total?

Thank you!

**Comment by jitpack-io** [comment]
Hi,

Thank you for the suggestion!
Not possible at the moment but we should be able to add this feature.

**Comment by kirtan403** [comment]
I'll be waiting for it!

**Comment by mrudultora** [comment]
@jitpack-io Any update on this issue. It would be helpful to show total number of downloads in badges (rather than monthly or weekly downloads).

**Comment by ice1000** [comment]
🥺

**Comment by kirtan403** [comment]
@jitpack-io Waiting to get this implemented? Any timeline?

**Comment by ice1000** [comment]
Nooooo this is unsolved
