### ISSUE TITLE
Display modules for multi-module builds on the website

### ISSUE THREAD

**Issue by jitpack** [jitpack/jitpack.io#21]
So that it's easier to pick one using a code snippet

**Comment by meltzow** [comment]
+1

**Comment by jitpack-io** [comment]
Showing subproject selector on the website now. 
![image](https://cloud.githubusercontent.com/assets/11161622/12218510/4c12c1d2-b719-11e5-9b17-d5bf21ee3fe1.png)
Will work for new builds.
