### ISSUE TITLE
Consider support for preprocess hooks to include native deps

### ISSUE THREAD

**Issue by gberche-orange** [jitpack/jitpack.io#211]
Some java projects require native binaries prior to launching the maven build, e.g. https://github.com/cloudfoundry/cf-java-client#protocol-buffer-compiler

When building on travis-ci, such projects specify a pre-install hook to fetch their native dependency.
https://github.com/cloudfoundry/cf-java-client/blob/master/.travis.yml#L5

Is there any way to build such projects with jitpack ?

https://jitpack.io/com/github/cloudfoundry/cf-java-client/14792849018e05ac8afd8603fff566e67147fdf1/build.log 
`
[ERROR] Failed to execute goal com.github.igor-petruk.protobuf:protobuf-maven-plugin:0.6.3:run (default) on project cloudfoundry-client-lib: Cannot execute 'protoc': Cannot run program "protoc": error=2, No such file or directory -> 
` 

Is there a workaround to include these libs as part of the maven build in a more portable way ?

Would otherwise, jitpack consider adding support for some pre-install steps similar to travis-ci ?

/CC @s-bortolussi @o-orand

**Comment by jitpack-io** [comment]
Hi @gberche-orange 

Good idea! We should add before_install to .jitpack.yml. Could probably even read it from .travis.yml

**Comment by gberche-orange** [comment]
Thanks @jitpack-io, it would be great to have jitpack support reading pre install steps directly from travis.yml

Related to the ["sudo make install"](https://github.com/cloudfoundry/cf-java-client/blob/master/bin/install-protoc-apt.sh#L10) command, I guess this is only to install the binary in part of the filesystem with root permission (such as /usr/bin/protbuf ) and could be adapted to make it available in another directory with write user permissions that will be added to the $PATH .

**Comment by jitpack-io** [comment]
That's a really good point! If we make the whole filesystem writable to the user then it should work. Will have a look how we could do this on our side.

**Comment by jitpack-io** [comment]
Update: It is now possible to execute custom install commands before the build https://jitpack.io/docs/BUILDING/#build-customization
