### ISSUE TITLE
Task 'install' is ambiguous in root project

### ISSUE THREAD

**Issue by budowski** [jitpack/jitpack.io#2121]
1. Trying to build this Android library: https://github.com/budowski/android-maps-utils
2. This is just a forked version of: https://github.com/googlemaps/android-maps-utils
3. The output of `gradlew install`:
`Task 'install' is ambiguous in root project 'android-maps-utils'. Candidates are: 'installDebug', 'installDebugAndroidTest'.`
3. Looking at a similar closed issue (#19), it seems that the error is caused by android-maven plugin not being installed.
4. However, the plugin is installed (as instructed here: https://jitpack.io/docs/BUILDING/)
See here: 
https://github.com/budowski/android-maps-utils/blob/master/build.gradle#L27
https://github.com/budowski/android-maps-utils/blob/master/library/build.gradle#L2
https://github.com/budowski/android-maps-utils/blob/master/demo/build.gradle#L2

**Comment by budowski** [comment]
Managed to work it out by looking at other forks of android-maps-utlis that used jitpack.
Still getting the same error locally, though.

**Comment by EbenezerGH** [comment]
Worked for me after adding the classpath to root gradle and applying plugin to the library

    classpath 'com.github.dcendents:android-maven-gradle-plugin:2.1'

    apply plugin: 'com.github.dcendents.android-maven'


https://github.com/jitpack/jitpack.io/blob/master/ANDROID.md

**Comment by AndroidDeveloperLB** [comment]
I'm having the same issue, but it didn't occur before. How come?

I got it here on v3 here, but not on the older version, v2 :
https://jitpack.io/#AndroidDeveloperLB/ArcAnimator/

Only after adding what "EbenezerGH" wrote, it worked fine (published on v6) ...

What's so special about this? I never had to add this before...
