### ISSUE TITLE
group from gradle build configuration

### ISSUE THREAD

**Issue by lex-em** [jitpack/jitpack.io#2160]
I have a several questions
1. How I can build snapshots with specified in build.gradle version on brunch "develop"?
2. I have jitpack build for project https://jitpack.io/#lex-em/zuul-springfox-swagger and have txt record https://dnschecker.org/#TXT/git.reliabletech.ru, but I cant find https://jitpack.io/#ru.reliabletech/zuul-springfox-swagger, why?
3. Why I cant just build with specified in build.gradle groupId? https://github.com/lex-em/zuul-springfox-swagger/blob/master/build.gradle
It is realy magic :) on my machine I build like jitpack:
`gradle clean -Pgroup=com.github.lex-em -Pversion=0.1.1 -xtest build publishToMavenLocal`

and get groupId from build.gradle!
```
  <groupId>ru.reliabletech</groupId>
  <artifactId>zuul-springfox-swagger</artifactId>
  <version>0.1.2-SNAPSHOT</version>
```

**Comment by lex-em** [comment]
4. and how I can force build? :)

**Comment by jitpack-io** [comment]
Hi @lex-em 

1. For branch snapshots use version like this: `develop-SNAPSHOT`
2. The DNS record is pointing to https://github.com/reliabletech-ru so JitPack looks for 
 repository https://github.com/reliabletech-ru/zuul-springfox-swagger. You could change the DNS record to point to https://github.com/lex-em and then it will work.
3. On JitPack groupId is always automatic to avoid clashes. If we take groupId from your build file then it would be easy to publish library with someone else's domain.

**Comment by lex-em** [comment]
Hi, @jitpack-io 

2,3 - works fine, groupid is right

1 - how I can fire build? I configure webhook and it was successed 
![image](https://user-images.githubusercontent.com/1404372/34514336-ddf6fcc0-f08e-11e7-8304-d7dbfa3af8eb.png)

**Comment by jitpack-io** [comment]
The webhook should start a build.

But also the first time you fetch the library from JitPack it will start to build.

**Comment by lex-em** [comment]
all is ok, thnx!
