### ISSUE TITLE
MultiLevelLibrary/v1.0 build

### ISSUE THREAD

**Issue by JianxunMaster** [jitpack/jitpack.io#2174]
Log https://jitpack.io/com/github/JianxunMaster/MultiLevelLibrary/v1.0/build.log

**Comment by JianxunMaster** [comment]
首次添加gradle没问题，修改了readme.md后就报错了

**Comment by jitpack-io** [comment]
`ERROR: Gradle wrapper not found. Please add. Using default gradle to build.`
