### ISSUE TITLE
DrawableView/0.6.0 build issue

### ISSUE THREAD

**Issue by echer** [jitpack/jitpack.io#218]
Log https://jitpack.io/com/github/PaNaVTEC/DrawableView/0.6.0/build.log

Problem to get version 0.6.0 from jitpack =/

**Comment by jitpack-io** [comment]
Hi @echer 
This project has an interesting configuration that we don't handle yet. Will be working on a fix

**Comment by chenupt** [comment]
I have the same problem. 
Log https://jitpack.io/com/github/chenupt/Android-PullToRefresh/2.3/build.log

**Comment by jitpack-io** [comment]
Hi @chenupt 
It looks like in your script it deploys to a local directory https://github.com/chenupt/Android-PullToRefresh/blob/master/library/build.gradle#L38 and that's why jitpack doesn't see any build artifacts.
