### ISSUE TITLE
Google libraries cannot be found

### ISSUE THREAD

**Issue by MFlisar** [jitpack/jitpack.io#2187]
I've seen this issue: https://github.com/jitpack/jitpack.io/issues/141

Are automatic updates working in the meantime? I can't get my library build working with android support library v26.1.0 (https://jitpack.io/com/github/MFlisar/FeedbackManager/0.13/build.log)

	A problem occurred configuring root project 'build'.
	> Could not resolve all dependencies for configuration ':_debugPublishCopy'.
	   > Could not find com.android.support:support-core-ui:26.1.0.
		 Searched in the following locations:
			 file:/android/extras/android/m2repository/com/android/support/support-core-ui/26.1.0/support-core-ui-26.1.0.pom
			 file:/android/extras/android/m2repository/com/android/support/support-core-ui/26.1.0/support-core-ui-26.1.0.jar
			 file:/home/jitpack/build/sdk-manager/com/android/support/support-core-ui/26.1.0/support-core-ui-26.1.0.jar
			 
Adding the `google()` repo does not work, this as well throws a build exception that this repo can't be found. Am I missing something?

**Comment by hendrawd** [comment]
Are you using the newest gradle plugin? What happens if you replace `google()` with `maven { url "https://maven.google.com" }`

**Comment by MFlisar** [comment]
Adding `maven { url "https://maven.google.com" }` worked, supporting `google()` instead would be nice though.

Thanks

**Comment by felipefpx** [comment]
Same problem for me. I am using the newest gradle plugin and Android Studio versions. When I add maven { url "https://maven.google.com" } then Android Studio shows an error. When I use google() to solve the error, jitpack shows this error... lol

**Comment by jitpack-io** [comment]
Hi,

Would recommend adding the Gradle Wrapper to the project.
That way you can control the Gradle version used in the build and new versions support `google()`.

**Comment by echorebel** [comment]
i have a similar issue 
```
Could not resolve com.google.android.gms:play-services-tasks:[15.0.1,16.0.0)
Could not resolve com.google.android.gms:play-services-basement:[15.0.1,16.0.0)
Could not resolve com.google.android.gms:play-services-base:[15.0.1,16.0.0)
```
although we use gradle wrapper, google() at the top of repositories (seems not to be used) and jitpack is failing with the above.
tried with `maven.google.com` but same issue.
