### ISSUE TITLE
Download library takes forever

### ISSUE THREAD

**Issue by hendrawd** [jitpack/jitpack.io#2189]
When i add a library that hosted at jitpack from a gradle file, for example
`implementation 'com.github.IONsoft-Indonesia:RandomNumberAnimation:1.2'`
Then i sync gradle, it will takes forever. It will stuck at
`Gradle: Metadata of https://jitpack.io/com/github/IONsoft-Indonesia/RandomNumberAnimation/1.2/RandomAnimationAnimation-1.2-sources.jar`
At first i think it is because of the library problem, but the problem also exist on other libraries.
I already tried to change my internet connection, use vpn, invalidate caches and restart android studio,  tried on both my iMac and Macbook, but still no luck.

**Comment by zeropercenthappy** [comment]
Same question here.
And check build.log's Files list, there is not exist a file end with sources.jar.
what's wrong we meet?How to fix?

**Comment by zeropercenthappy** [comment]
```
task sourcesJar(type: Jar) {
    from android.sourceSets.main.java.srcDirs
    classifier = 'sources'
}

artifacts {
    archives sourcesJar
}
```
Add above configuration to library's build.gradle

**Comment by ooftf** [comment]
There was no such problem before, and it appeared today.

**Comment by fgustovo** [comment]
same as me.

**Comment by r17171709** [comment]
Same question here.There was no such problem before, and it appeared today.

**Comment by fgustovo** [comment]
same problem here and occurred today.

**Comment by appersiano** [comment]
Same problem.... 👎

**Comment by hendrawd** [comment]
Silly me, i just added the library module directly to my project without knowing that it can be solved with @zeropercenthappy workaround 🙄

**Comment by ooftf** [comment]
I just want to know whether it's a server problem or a code problem

**Comment by Julesssss** [comment]
I had the same issue, and fixed it by following the instructions on this page: https://jitpack.io/docs/ANDROID/

**Comment by r17171709** [comment]
@Julesssss No Use

**Comment by Julesssss** [comment]
@r17171709 Did you add this code to the library project of the client project?

**Comment by Alexander-Krause** [comment]
Is there any official statement from the @jitpack-io team, that we can reference here?

**Comment by hendrawd** [comment]
@Alexander-Krause Not yet when I posted this issue, because I have googled and searched for it.

**Comment by Jawnnypoo** [comment]
This must be a server problem, as it was not breaking before today. It sounds like it could be a path issue or something similar where the server is not returning a 404 or a different response when the sources jar is not found, therefore causing the entire dependency to be unresolved. So therefore only libraries with properly set up sources.jars will be able to resolve.

**Comment by ooftf** [comment]
Why no official reply has been received until now

**Comment by r17171709** [comment]
@Julesssss client project

**Comment by jitpack-io** [comment]
Hi all,
There was an issue getting files that don't exist - the request would hang. This was caused by a system upgrade during the weekend but has now been rolled back. Due to lower amount of traffic on weekends we didn't spot an issue straight away and existing files were resolving fine.
We've been dealing with it through our support system so apologies for missing this ticket. Will be taking steps to ensure we check this scenario in future upgrades.

**Comment by elect86** [comment]
Does anyone still have the problem?

I added 

```
task sourcesJar(type: Jar, dependsOn: classes) {
    classifier = 'sources'
    from sourceSets.main.allSource
}

task javadocJar(type: Jar, dependsOn: javadoc) {
    classifier = 'javadoc'
    from javadoc.destinationDir
}

artifacts {
    archives sourcesJar
    archives javadocJar
}
```

But nothing changed

**Comment by ooftf** [comment]
If you have the same problem with us，You don't have to do anything because the official has  repaired that

**Comment by elect86** [comment]
Well, not for me unfortunately..

As I wrote, I still have the problem, click [here](https://jitpack.io/#kotlin-graphics/glm) and then on "Commits", you'll see all the recent commits hanging indefinitely

**Comment by ooftf** [comment]
I think we have the different problem.
I add  "com.github.kotlin-graphics:glm:v1.0.1". I stuck it in jcenter Instead of  jitpack-io

**Comment by OmerUygurOzer** [comment]
Started having this issue today.

**Comment by Just-a-Unity-Dev** [comment]
bump

**Comment by BullyWiiPlaza** [comment]
I just ran into this issue today. [IntelliJ](https://www.jetbrains.com/idea) is stuck at `Resolving maven dependencies...`. The project I added was [this](https://jitpack.io/#JnCrMx/discord-game-sdk4j) one. I'm developing a Java Desktop application (not Android).
