### ISSUE TITLE
unit-ri/0.7.1 build issue

### ISSUE THREAD

**Issue by borismarin** [jitpack/jitpack.io#219]
Log https://jitpack.io/com/github/unitsofmeasurement/unit-ri/0.7.1/build.log

**Comment by jitpack-io** [comment]
Hi @borismarin 
Is the issue gone?

**Comment by borismarin** [comment]
Hello, sorry for changing my mind so quickly =)
The problem is: my maven builds using jitpack repos fail, e.g.
```
[WARNING] The POM for com.github.unitsofmeasurement:unit-ri:jar:0.7 is missing, no dependency information available
...
[ERROR] Failed to execute goal on project expr_parser: Could not resolve dependencies for project expr_parser:expr_parser:jar:0.0.1: The following artifacts could not be resolved: com.github.unitsofmeasurement.unit-api:unit-api:bundle:0.7, com.github.unitsofmeasurement:unit-ri:jar:0.7: Failure to find com.github.unitsofmeasurement.unit-api:unit-api:bundle:0.7 in https://jitpack.io was cached in the local repository, resolution will not be reattempted until the update interval of jitpack.io has elapsed or updates are forced -> [Help 1]
```
But since your local log reports successful builds, I assume the problem is on my side.

**Comment by jitpack-io** [comment]
No worries, will have a look

**Comment by jitpack-io** [comment]
Ok, there was an error on the server side and thanks to you it is now fixed!:) Basically the build was successful but the jar files didn't get published.
Rebuilt the project and now you should be able to get it as a dependency.
