### ISSUE TITLE
Support build file located in a subfolder

### ISSUE THREAD

**Issue by tinsukE** [jitpack/jitpack.io#22]
I'm trying to use Adjust through JitPack, but since the build.gradle file is located at a subfolder, JitPack can't build it.
https://github.com/adjust/android_sdk
https://github.com/adjust/android_sdk/tree/master/Adjust

It would be useful if JitPack scanned some subfolders (at least 1 level deep) for build files.

**Comment by jitpack** [comment]
Thanks for the suggestion! That sounds like a nice feature, seen it in a few projects. 
I guess the only ambiguity is when there are multiple subfolders and each has a build.gradle. I guess for now we will only build if there's just one.

**Comment by jitpack** [comment]
@tinsukE You've got it: https://jitpack.io/#adjust/android_sdk/v3.6.2

JitPack now can find and build build.gradle files in subfolders.

**Comment by tinsukE** [comment]
Great! The feeling of deleting 3rd party source code from your repo.
![n52b6551aa1225](https://cloud.githubusercontent.com/assets/1063155/6393531/2cd17c02-bdcb-11e4-8517-ff56b63178f0.png)

**Comment by jitpack** [comment]
@tinsukE  Ha Ha, that's brilliant!

**Comment by DannyVlasenko** [comment]
Is Jitpack looking for build scripts only in 1st level subfolders?

**Comment by Steppschuh** [comment]
I also have [one repo](https://github.com/Steppschuh/Java-Markdown-Generator) where JitPack can't find the build file. Here's the [build.log](https://jitpack.io/com/github/Steppschuh/Java-Markdown-Generator/1.3.1.1/build.log). Any help would be appreciated!

**Comment by jitpack-io** [comment]
Hi,

You could use custom build commands to build in a subfolder:
https://jitpack.io/docs/BUILDING/#custom-commands
