### ISSUE TITLE
pTune/357cfa7e9f build issue

### ISSUE THREAD

**Issue by RaphaBrito** [jitpack/jitpack.io#224]
Log https://jitpack.io/com/github/wespay/pTune/357cfa7e9f/build.log

**Comment by jitpack-io** [comment]
Hi @RaphaBrito 
As far as I can tell pTune is an application and we don't build those without gradle. Did you want to get the .apk?

**Comment by RaphaBrito** [comment]
Hi @jitpack-io 
No, Thanks. can use its audio processing classes in my application ?

**Comment by jitpack-io** [comment]
Probably only if you fork the project and convert to a library using Gradle
