### ISSUE TITLE
Does Jitpack work with android? Cannot resolve build variants

### ISSUE THREAD

**Issue by wadijm** [jitpack/jitpack.io#2249]
Hello, jitpack is not working with android build variants. 
The output is the following:

_Run gradle build
Gradle build script
Found gradle version: 3.5.
Using sdkman gradle
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Djavax.xml.accessExternalSchema=all

------------------------------------------------------------
Gradle 3.5
------------------------------------------------------------

Build time:   2017-04-10 13:37:25 UTC
Revision:     b762622a185d59ce0cfc9cbc6ab5dd22469e18a6

Groovy:       2.4.10
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_131 (Oracle Corporation 25.131-b11)
OS:           Linux 4.10.0-28-generic amd64

0m0.728s
Getting a list of gradle tasks
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Djavax.xml.accessExternalSchema=all
0001-01-01T00:00:00Z
Exit code: 0
Timed out
No build artifacts found_

**Comment by jitpack-io** [comment]
Hi,

It does but gradle needs to be configured to publish variants as artifacts.
Here's one example: https://github.com/jitpack-io/android-jitpack-library-example

**Comment by franciscozuccala** [comment]
Hi there,
The same is happening to me, did you find a solution? The example isn't working for me :confused:

**Comment by ubuntudroid** [comment]
@jitpack-io Having the same problem - builds time out after some time without even executing the gradle task - cause that's what actually happens for successful builds in the line where the log says `0001-01-01T00:00:00Z` in case of a timeout. Sometimes just creating a new tag works. Sometimes the builds get stuck for over an hour before resulting in a failure. Having that problem right now over here: https://jitpack.io/private#stanwood/Analytics_Framework_android

Really frustrating as you cannot check the log during build, so it's all guess work until the build finally times out. Mine are running for over an hour now... Did no code changes related to gradle/maven configuration whatsoever.

**Comment by ubuntudroid** [comment]
I should point out that this started to happen last week for the first time for us. This library has 10 modules, might have something to do with this issue. But now it blocks us from releasing our apps. :(
