### ISSUE TITLE
Custom Domains not working?

### ISSUE THREAD

**Issue by afollestad** [jitpack/jitpack.io#225]
They had been working before, but they seemed to have stopped. Not sure if there's a certain condition about my library that would make it not work.

This can't be resolved:

```Gradle
compile('com.afollestad.material-dialogs:core:0.8.2.0@aar') {
        transitive = true
}
```

But this can:

```Gradle
compile('com.github.afollestad.material-dialogs:core:0.8.2.0@aar') {
        transitive = true
}
```

Executing `dig txt git.afollestad.com` resolves the correct information.

**Comment by jitpack-io** [comment]
Hi,
Looks version 0.8.2.0 was requested before the tag was created. In these cases when you look at the build.log JitPack will try to find the tag again.
Rebuilt and it looks ok now.

**Comment by afollestad** [comment]
Great, thank you

**Comment by afollestad** [comment]
@jitpack-io this seems to be happening again with:

```Gradle
compile('com.github.afollestad.material-dialogs:core:0.8.4.1@aar') {
        transitive = true
}
compile('com.github.afollestad.material-dialogs:commons:0.8.4.1@aar') {
        transitive = true
}
```

**Comment by afollestad** [comment]
@jitpack-io this seems to be happening again with:

```Gradle
compile('com.afollestad.material-dialogs:core:0.8.4.1@aar') {
    transitive = true
}
compile('com.afollestad.material-dialogs:commons:0.8.4.1@aar') {
    transitive = true
}
```

**Comment by jitpack-io** [comment]
Hi,
The libs are available so not sure why they don't show up for you https://jitpack.io/com/afollestad/material-dialogs/0.8.4.2/build.log

Perhaps try running gradle with `--refresh-dependencies`

**Comment by afollestad** [comment]
It's working with 0.8.4.2, the problem was originally with 0.8.4.1 but I published a release right after it so it went away. 

Thank you anyways!
