### ISSUE TITLE
Javadocs not building properly

### ISSUE THREAD

**Issue by AllanWang** [jitpack/jitpack.io#2258]
[Build log](https://jitpack.io/ca/mcgill/tepid-commons/-4169dbe6fd-1/build.log)

In some instances, it seems like the source jar or javadocs jar doesn't exist. If I were to build it locally, I will get the following files for the retrofit submodule in the lib folder:

```
-rwxrwxrwx 1 ... users 46477 Oct 28 23:23 data-1.0-SNAPSHOT.jar
-rwxrwxrwx 1 ... users 25511 Oct 28 23:23 data-1.0-SNAPSHOT-javadoc.jar
-rwxrwxrwx 1 ... users 16067 Oct 28 23:23 data-1.0-SNAPSHOT-sources.jar
-rw-r--r-- 1 ... users  5293 Jan 24 19:26 retrofit-1.0.0-sources.jar
-rwxrwxrwx 1 ... users  4244 Oct 29 00:14 retrofit.jar
-rwxrwxrwx 1 ... users 25511 Oct 29 00:14 retrofit-javadoc.jar
-rwxrwxrwx 1 ... users  1325 Oct 29 00:14 retrofit-sources.jar

```

However, the javadocs page is [blank](https://jitpack.io/ca/mcgill/tepid-commons/retrofit/-4169dbe6fd-1/javadoc/index.html).

For cases like `core`, it does seem to [generate something](https://jitpack.io/ca/mcgill/tepid-commons/core/-4169dbe6fd-1/javadoc/index.html).

It also looks like for multi gradle module projects, linking the main javadocs page is blank, and you have to specify the submodules yourself in the url. 

I've adapted our main `build.gradle` to generate the javadocs and sources like the jitpack example.

Our gradle and all the other bits can be found [here](https://gitlab.science.mcgill.ca/TEPID/tepid-commons/blob/dev/build.gradle#L21)

**Comment by viggy96** [comment]
I've found that I had to add a few extra lines to my `build.gradle` to get JitPack to pick up the Javadoc.

```
publishing {
  publications {
    mavenJava(MavenPublication) {
      from components.java
      afterEvaluate {
        artifact javadocJar
        artifact sourcesJar
      }
    }
  }
}
```
Turns out the "afterEvaluate" block is critical.

**Comment by viggy96** [comment]
Keeping this open.
