### ISSUE TITLE
Sub-module name same as project. Won't build.

### ISSUE THREAD

**Issue by OmerUygurOzer** [jitpack/jitpack.io#2286]
I have this project 

> compile 'com.github.OmerUygurOzer:jet:v1.0.10'

it has a module name that's same as the project name . It won't even build. Not sure how to access the module that has the same name as the project name because it would have the same path as the project itself but the project contains an annotation processor so I need to access modules separately. Any ideas on how this can be achieved without having to change the module or the project name?

**Comment by jitpack-io** [comment]
These modules are available:
```
com.github.OmerUygurOzer.jet:jetannotations:v1.1.0
com.github.OmerUygurOzer.jet:jetlib:v1.1.0
com.github.OmerUygurOzer.jet:jetprocessor:v1.1.0
```

https://jitpack.io/#OmerUygurOzer/jet/v1.1.0
