### ISSUE TITLE
protobuf-java-format/f49a36259a build issue

### ISSUE THREAD

**Issue by qiutiaoming** [jitpack/jitpack.io#229]
Log https://jitpack.io/com/github/bivas/protobuf-java-format/f49a36259a/build.log

**Comment by jitpack-io** [comment]
Hi @qiutiaoming 
Looks like the build is looking for Protocol Buffers (protoc command). Do you know if they are expected to be installed for this project?

**Comment by qiutiaoming** [comment]
@jitpack-io ,Thanks for your response. I  forked protobuf-java-format project and delete all tests(which needed  protoc to compile Protocol Buffers files ),and Everything works fine.
Thanks again.
