### ISSUE TITLE
Build successful on local machine, but failed on JitPack server

### ISSUE THREAD

**Issue by haibison** [jitpack/jitpack.io#231]
I build my project successfully on local machine. However it's failed on JitPack server.

Would you please have a look on this [log file](https://jitpack.io/com/github/haibison/chocon/5.0.7/build.log)?

Thank you.

**Comment by xingrz** [comment]
seems to be the same problem with #232 #233 that occurred in `Script '/script/maven-plugin.gradle' line: 5`... @jitpack-io

**Comment by jitpack-io** [comment]
Hi @haibison @xingrz 
Having a look...

**Comment by jitpack-io** [comment]
Fixed! Sorry for the inconvenience!

**Comment by haibison** [comment]
@jitpack-io Thank you for your great service.

**Comment by jitpack-io** [comment]
No problem! The new log looks better https://jitpack.io/com/github/haibison/chocon/5.0.7/build.log
