### ISSUE TITLE
JavaFX is not supported Java 9 builds

### ISSUE THREAD

**Issue by xzel23** [jitpack/jitpack.io#2310]
After providing a jitpack.yml file with `jdk: oraclejdk9`, I can observe that the build is now using Java 9. However, JavaFX is not present. Seems like OpenJDK 9 is installed, not OracleJDK.

To fix this, either OracleJDK 9 should be used, or OpenJFX should be installed alongside OpenJDK9.

I get these two errors in my build:

```
/home/jitpack/build/src/main/java/module-info.java:10: error: module not found: javafx.controls
    requires javafx.controls;
                   ^
/home/jitpack/build/src/main/java/module-info.java:11: error: module not found: javafx.web
    requires javafx.web;
                   ^
2 errors
:compileJava FAILED
```

 1. [build.log.txt](https://github.com/jitpack/jitpack.io/files/1733611/build.log.txt) from https://jitpack.io/com/github/xzel23/utility/3276caf/build.log 
 2. Project builds without problems on both my local machine (MACOS) and in office (Windows 7)

**Comment by JavaSaBr** [comment]
I have the same issue :(

**Comment by xzel23** [comment]
Just saw your comment on #1592. I'd be willing to help solve this, but I don't see where to start.

**Comment by xzel23** [comment]
I changed the bug description since this apparently has nothing to do with the module system.

**Comment by Xerus2000** [comment]
This issue just started occuring to me, seems like they recently updated their images. But this time it's in Java 8. This is what it says:
```
JVM:          1.8.0_171 (Oracle Corporation 25.171-b11)
```
and then hundreds of messages about javafx missing, here a few:
```
e: /home/jitpack/build/javafx/src/xerus/ktutil/javafx/Constructors.kt: (3, 8): Unresolved reference: javafx
e: /home/jitpack/build/javafx/src/xerus/ktutil/javafx/Constructors.kt: (4, 8): Unresolved reference: javafx
e: /home/jitpack/build/javafx/src/xerus/ktutil/javafx/Constructors.kt: (5, 8): Unresolved reference: javafx
e: /home/jitpack/build/javafx/src/xerus/ktutil/javafx/Constructors.kt: (6, 8): Unresolved reference: javafx
e: /home/jitpack/build/javafx/src/xerus/ktutil/javafx/Constructors.kt: (7, 8): Unresolved reference: javafx
```
Log: https://jitpack.io/com/github/Xerus2000/util/master-266bb15e77-1/build.log

**Comment by jitpack-io** [comment]
Hi @Xerus2000 ,

Should be working now for Java 8. Rebuilt that version and it succeeded.
We're updated our [Dockerfile](https://github.com/jitpack-io/dockerfiles/blob/master/base/Dockerfile) to include openjfx.

Does anyone have commands how to install JavaFX on Java 10?

**Comment by Xerus2000** [comment]
Thanks! Oracle seems to offer OpenJFX Early-Acess builds for JDK 10/11 here: http://jdk.java.net/openjfx/

**Comment by lubshilk** [comment]
Hi,

Tried to use jitpack for building soapUI jars as explained:
added repository
```
<repository>
	    <id>jitpack.io</id>
	    <url>https://jitpack.io</url>
</repository>
```
and dependency		
```
<dependency>
    <groupId>com.github.SmartBear</groupId>
     <artifactId>soapui</artifactId>
     <version>5.3.0</version>
</dependency>
```
Using jdk1.8.0_131

While installing receive the error:
_Failed to execute goal on project cellactAutomationBig: Could not resolve dependencies for project com.cellact:cellactAutomationBig:jar:1.1.0-SNAPSHOT: Could not find artifact javafx:jfxrt:jar:2.2 at specified path C:\Program Files\Java\jdk1.8.0_131\jre/lib/jfxrt.jar -> [Help 1]_

jfxrt.jar is located in C:\Program Files\Java\jdk1.8.0_131\jre\lib\ext

What is wrong? How to solve the problem?

Thanks in advance

**Comment by jitpack-io** [comment]
@Xerus2000 Thanks! The zip contains a bunch of libraries:
```
        0  2018-08-29 13:51   javafx-sdk-11/
        0  2018-08-29 13:51   javafx-sdk-11/lib/
    27537  2018-08-29 13:51   javafx-sdk-11/lib/libjavafx_font_freetype.so
   354931  2018-08-29 13:51   javafx-sdk-11/lib/libglassgtk3.so
    36804  2018-08-29 13:51   javafx-sdk-11/lib/javafx-swt.jar
```
Is it enough to unzip the zip in the JDK folder?

**Comment by goxr3plus** [comment]
I can't compile [this Project](https://github.com/goxr3plus/JavaFX-Web-Browser)  under JDK 10 it produces the below error log 

https://jitpack.io/com/github/goxr3plus/JavaFX-Web-Browser/V10.0.0/build.log

and `https://jitpack.io/com/github/goxr3plus/JavaFX-Web-Browser/V10.0.0/build.log` blah blah what happens? I can't build any Java 9 projects and above i have :(

**Comment by xzel23** [comment]
@goxr3plus: It's because JavaFX is not included in OpenJDK 10 but is in Oracle JDK. Maybe you should just switch to Java 11 now that Java 10 is obsolete: in Java 11, the situation is quite clear: JavaFX is not part of the distribution anymore - be it OpenJDK or Oracle - and you have to add a dependency. The OpenJFX project has a sample on how to use [JavaFx with Maven](https://openjfx.io/openjfx-docs/#maven). Note that starting with Java 11 you'd better switch to OpenJDK anyway if you want to distribute or use your software in production and haven't obtained a license from Oracle.

**Comment by goxr3plus** [comment]
The problem is i have to make all the project modular and is not... we
speak about big effort.

**Comment by xzel23** [comment]
@goxr3plus Why do you have to make your project modular? You can still use the classpath in Java 11. This has nothing to do with jitpack.

**Comment by goxr3plus** [comment]
Okay so the project is working as is in Java10, mvn clean package works
great locally and that's how it should work successfully with Jitpack too.
No dependencies missing or nothing.... but check the latest report of
jitpack for that project it's an error.... like how do you explain that?

**Comment by xzel23** [comment]
@goxr3plus when you do `java -version` locally, is it Oracle or OpenJDK? If it's Oracle, you have the answer. As I said above:

> It's because JavaFX is not included in OpenJDK 10 but is in Oracle JDK.

**Comment by xzel23** [comment]
Since Java 9/10 is now obsolete, and this doesn't apply to Java 11, I close this issue.

**Comment by Merudo** [comment]
Java 9/10 will be obsolete only when the new jpackage is released.

**Comment by xzel23** [comment]
@Merudo: feel free to open a new issue. I opened this one because the jdk 9 build did not include Javafx (while Oracle jdk 9 included Java fx). Since starting with jdk 10 Java fx isn't included in both openjdk and Oracle jdk anymore anyway, jdk 9 support is not an issue for me (I changed my child scripts to include a dependency on the openjfx builds).

I also meant obsolete in the sense of "having reached EOL". Since a jpackage substitute won't make it into the jdk before version 14, maybe you could look for alternatives?

Anyway, since the only official supported versions as of now are 8, 11 and 12, I closed this issue.
