### ISSUE TITLE
Gradle wrapper not recognised

### ISSUE THREAD

**Issue by MFlisar** [jitpack/jitpack.io#2311]
Log https://jitpack.io/com/github/marvinlabs/android-unlocker-library/-1.0.0-ga59809b-5/build.log

Why is it still not finding the wrapper? It's placed here

https://github.com/marvinlabs/android-unlocker-library/tree/master/gradle/wrapper

I have added the `gradle-wrapper.jar`  and the `gradle-wrapper.properties` file and still the log says that it dod not find any gradle wrapper

**Comment by MFlisar** [comment]
Found the issue...

I would suggest adjusting the docs here: https://jitpack.io/docs/ANDROID/

I'm always having problems to know which files I need, and this time it took me quite long to figure out.

Would suggest to add a checklist like following to the readme:

**Checklist**
* root build.gradle
  - [ ] add classpath 'com.github.dcendents:android-maven-gradle-plugin:2.0'
* `library/build.gradle`:
  - [ ] apply plugin: 'com.github.dcendents.android-maven'  
  - [ ] group='com.github.YourUsername'
* `gradle wrapper`
  - [ ] create it by running `gradle wrapper` in your root project
  - [ ] make sure to add **all 4 files** to your reop
    - [ ] `gradlew`
    - [ ] `gradlew.bat`
    - [ ] `gradle\wrapper\gradle-wrapper.jar`
    - [ ] `gradle\wrapper\gradle-wrapper.properties`

**Comment by Vipinbalakrishnan** [comment]
@Prabha10cs 

Please create a file named 'jitpack.yml' in the root of the project for JAVA 11 support. 

Create a file with name as 'jitpack.yml' with the following content

`jdk:
  - openjdk11`

**Comment by SHamzaHMergn** [comment]
> Found the issue...
> 
> I would suggest adjusting the docs here: https://jitpack.io/docs/ANDROID/
> 
> I'm always having problems to know which files I need, and this time it took me quite long to figure out.
> 
> Would suggest to add a checklist like following to the readme:
> 
> **Checklist**
> 
> * root build.gradle
>   
>   * [ ]  add classpath 'com.github.dcendents:android-maven-gradle-plugin:2.0'
> * `library/build.gradle`:
>   
>   * [ ]  apply plugin: 'com.github.dcendents.android-maven'
>   * [ ]  group='com.github.YourUsername'
> * `gradle wrapper`
>   
>   * [ ]  create it by running `gradle wrapper` in your root project
>   * [ ]  make sure to add **all 4 files** to your reop
>     
>     * [ ]  `gradlew`
>     * [ ]  `gradlew.bat`
>     * [ ]  `gradle\wrapper\gradle-wrapper.jar`
>     * [ ]  `gradle\wrapper\gradle-wrapper.properties`
> 
> I forget the `gradlew` and `gradlew.bat` file and got the error "gradle wrapper not found" which was not very helpful. Maybe the error could be changed to also tell the user which file is missing???

Thank you, that is so accurate.
Errors need to be appopiate
