### ISSUE TITLE
pull-back-layout/1.0.0 build issue

### ISSUE THREAD

**Issue by xingrz** [jitpack/jitpack.io#232]
Log https://jitpack.io/com/github/oxoooo/pull-back-layout/1.0.0/build.log

Seems not a bug of my library itself, since I succeed building it in my computer.
Is it any way to rebuild it?

**Comment by xingrz** [comment]
now it is 'error: Exception'

**Comment by jitpack-io** [comment]
Having a look...

**Comment by xingrz** [comment]
@jitpack-io great, it works.
