### ISSUE TITLE
Multi-module project - Unauthorized [401]  (SharedSequence.kt/0.1.5)

### ISSUE THREAD

**Issue by JurajBegovac** [jitpack/jitpack.io#2322]
Github link:
https://github.com/NoTests/SharedSequence.kt

Hi,
I'm trying to publish multi-module library through jitpack. I followed your docs and build went well, here is log: https://jitpack.io/com/github/NoTests/SharedSequence.kt/0.1.5/build.log

I'm trying to use the library in some other project with gradle like this:

- root gradle:
```
allprojects {
	repositories {
		// ...
		maven { url 'https://jitpack.io' }
}
```

- module gradle:
```
dependencies {
    // ...
   implementation 'com.github.notests.SharedSequence.kt:SharedSequence:0.1.5'
}
```

But I'm getting this error:

```
Could not resolve com.github.notests.SharedSequence.kt:SharedSequence:0.1.5.
Required by:
    project :app
 > Could not resolve com.github.notests.SharedSequence.kt:SharedSequence:0.1.5.
    > Could not get resource 'https://jitpack.io/com/github/notests/SharedSequence/kt/SharedSequence/0.1.5/SharedSequence-0.1.5.pom'.
          > Could not GET 'https://jitpack.io/com/github/notests/SharedSequence/kt/SharedSequence/0.1.5/SharedSequence-0.1.5.pom'. Received status code 401 from server: Unauthorized
```

Android Studio: 3.0.1
Gradle: 4.1

Thank you in advance :)

**Comment by jitpack-io** [comment]
Hi,

The issue is the '.' in the project name because it is a special character in Maven/Gradle dependencies.

**Comment by JurajBegovac** [comment]
Hmmmm...

You mean `.` before `kt`? 

We made it like this because we have the same lib in swift (SharedSequence.swift)

**Comment by JurajBegovac** [comment]
Is it possible to change this through `jitpack.yml` file?

**Comment by JurajBegovac** [comment]
Seems it's working with '.' in name of project
