### ISSUE TITLE
eobot-android-sdk/1.0.0 build issue

### ISSUE THREAD

**Issue by odemolliens** [jitpack/jitpack.io#233]
Log https://jitpack.io/com/github/odemolliens/eobot-android-sdk/1.0.0/build.log

Can you help me on that?

**Comment by jitpack-io** [comment]
Hi @odemolliens 
Will have a look

**Comment by jitpack-io** [comment]
Fixed!
It'd be a good to apply these steps to your project https://jitpack.io/docs/ANDROID/ to avoid issues like this. Basically there was a mismatch between the gradle version and the maven plugin.
