### ISSUE TITLE
RoundOverlayProgress/1.0.9 build issue

### ISSUE THREAD

**Issue by jkwiecien** [jitpack/jitpack.io#234]
Log https://jitpack.io/com/github/Schibsted-Tech-Polska/RoundOverlayProgress/1.0.9/build.log

**Comment by jitpack-io** [comment]
Hi @jkwiecien 
Is there still an issue with this project? Seems ok now https://jitpack.io/com/github/Schibsted-Tech-Polska/RoundOverlayProgress/1.0.9/RoundOverlayProgress-1.0.9.pom

**Comment by jkwiecien** [comment]
You guys are fast. Seems like temporary problems.

**Comment by jitpack-io** [comment]
Yeah, there was. Sorry about that! Working on improvements
