### ISSUE TITLE
ViewPagerIndicator/2.4.1 build issue

### ISSUE THREAD

**Issue by EdwardQuixote** [jitpack/jitpack.io#236]
Log https://jitpack.io/com/github/JakeWharton/ViewPagerIndicator/2.4.1/build.log -- via JitPack.IO

**Comment by jitpack-io** [comment]
Hi @EdwardQuixote 

Should be available. Could you retry?

**Comment by EdwardQuixote** [comment]
@jitpack-io 
Yeah, it works now.

Thanks.
