### ISSUE TITLE
csc301-java-utils/0.0.4 build issue

### ISSUE THREAD

**Issue by joeyfreund** [jitpack/jitpack.io#237]
Log https://jitpack.io/com/github/csc301-fall-2015/csc301-java-utils/0.0.4/build.log

From the log file it seems like a network glitch, but I am not sure.

 * Our GitHub repo hasn't changed in 10 days
 * We've been using JitPack (with this repo and version) for the past 10 days, without a problem.

The one thing that I still don't understand - It seems odd that JitPack tried to build the project again, it was built about 10 days ago (when it was first fetched).

**Comment by jitpack-io** [comment]
Hi, 
Sorry about that, there were some issues today. Rebuilt again and its allright now.

**Comment by joeyfreund** [comment]
@jitpack-io , thank you so much for the quick reply.
