### ISSUE TITLE
Need to add @aar to include my new version

### ISSUE THREAD

**Issue by SandroMachado** [jitpack/jitpack.io#238]
I released a new version of an Android library and now I need to use:
```
compile ('com.github.username:library:0.2@aar') {
    transitive = true
}
```

To use my previous version I just need to use: 
```
compile 'com.github.username:library:0.1'
```

Any idea of what could be the problem?

**Comment by jitpack-io** [comment]
That is strange, shouldn't really make a difference. What happens if you don't use the aar?

**Comment by SandroMachado** [comment]
Gives an error saying that it cannot find the jar. Something like this:
```
Error:A problem occurred configuring project ':app'.
> Artifact 'library.jar (com.github.username:library:0.0.2)' not found.
  Searched in the following locations:
      https://jitpack.io/com/github/username/library/0.0.2/library-0.0.2.jar
```

**Comment by jitpack-io** [comment]
Oh ok, it's looking for the jar and not the aar. It might be the packaging type is not specified in the generated pom file. Does the pom have this line?
```xml
<packaging>aar</packaging>
```

**Comment by SandroMachado** [comment]
Yes, it does. I also tried to invalidate the caches in Android Studio and the problem persists.

**Comment by jitpack-io** [comment]
Invalidating caches might not be sufficient. What if you delete $HOME/.gradle/caches and project_dir/.gradle/?

**Comment by SandroMachado** [comment]
Yup, removing those directories fixed the issue. Thanks for the help.
