### ISSUE TITLE
android-cropimage/v1.1.1 build issue

### ISSUE THREAD

**Issue by philjk1987** [jitpack/jitpack.io#239]
Log https://jitpack.io/com/github/philjk1987/android-cropimage/v1.1.1/build.log

**Comment by jitpack-io** [comment]
Hi @philjk1987 
Problem is its trying to upload to a local directory 
https://github.com/philjk1987/android-cropimage/blob/master/CropImage/build.gradle#L35

Should work without that line as it will upload to local maven repository.
