### ISSUE TITLE
Build a module inside a repository

### ISSUE THREAD

**Issue by nitsanw** [jitpack/jitpack.io#242]
I'm the JCTools maintainer/author. I would like jitpack to pick up only the jctools-core module, which is the one I release to maven central.
The project has a parent build file which is a convenience to allow a one command build. It is rather annoying to have the default profile not just build everything. I've had this setup in place to support jitpack but it confuses people trying to hack on JCTools. I have now reverted to maintaining the jctools-core pom as the release pom with all the required details and the rest as sekeleton for convenient building. As such jitpack will not be able to build JCTools from source unless you allow specifying a module inside a repo.
I'd like the coordinates to look like this maybe:

     <dependency>
	    <groupId>com.github.JCTools</groupId>
	    <artifactId>JCTools.jctools-core</artifactId>
	    <version>1.1</version>
	</dependency>

I'm very grateful for your effort in making jitpack work for JCTools before and I hope we can make this work again.

**Comment by jitpack-io** [comment]
Hi @nitsanw 

Shouldn't be a problem as JitPack can build all modules and then users can pick out which ones they want. Our current syntax for modules is:
```xml
<dependency>
    <groupId>com.github.JCTools.JCTools</groupId>
    <artifactId>jctools-core</artifactId>
    <version>1.1</version>
</dependency>
```

**Comment by jitpack-io** [comment]
Another option is to use a custom domain name for groupId https://jitpack.io/docs/#custom-domain-name

**Comment by nitsanw** [comment]
Great, that works for me. I'll re-instate the instructions in the readme.
Thanks!
