### ISSUE TITLE
cacheio/0.2.4 build issue

### ISSUE THREAD

**Issue by joselufo** [jitpack/jitpack.io#245]
I don't know why but today my last version of the library has an error in jitpack. I didn't make anything and I can't sync my project.

is it something from jitpack? or is it something of my project?

Log https://jitpack.io/com/github/mobilejazz/cacheio/0.2.4/build.log

**Comment by jitpack-io** [comment]
Hi @joselufo 
There was a brief network error. Rebuild and its ok now. Sorry about that
