### ISSUE TITLE
Could not resolve all files for configuration ':demo:classpath'

### ISSUE THREAD

**Issue by mkaflowski** [jitpack/jitpack.io#2456]
Are there any problems with jipack? I cannot build any of my libs since yesterday. Examples:
[https://jitpack.io/#mkaflowski/HybridMediaPlayer](https://jitpack.io/#mkaflowski/HybridMediaPlayer)
[https://jitpack.io/#mkaflowski/Android-Five-Stars-Dialog-Library](https://jitpack.io/#mkaflowski/Android-Five-Stars-Dialog-Library)
I have made no changes in the second one, just wanted to test if it will build.

**Comment by furkanayaz** [comment]
If you changed "isMinifyEnabled" property as a true, it's probably occurs the problem from this changes. Please try again by changing "isMinifyEnabled = false"
