### ISSUE TITLE
Can't build compile 'com.github.eddydn:AndroidGridLayout:-SNAPSHOT' on my android studio. I put the correct statements in the right places in the gradle build

### ISSUE THREAD

**Issue by sachiverma** [jitpack/jitpack.io#2470]
New feature requests are very welcome!

If submitting a build issue please provide:
 1. Build log from https://jitpack.io 
 2. Does the project build on your machine?

Thank you!

**Comment by jitpack-io** [comment]
From the build log: https://jitpack.io/com/github/eddydn/AndroidGridLayout/-62c61d214f-1/build.log
```
WARNING:
Gradle 'install' task not found. Please add the 'maven' or 'android-maven' plugin.
See the documentation and examples: https://jitpack.io/docs/
```
