### ISSUE TITLE
Recieved status code 403 from server-Forbidden(Help please-desperate)

### ISSUE THREAD

**Issue by nasos7** [jitpack/jitpack.io#2482]
Hi,
I try to sync a gradle project but i get this error 
"Error:Could not GET 'https://jitpack.io/com/github/udacity/android-assistant-gradle-plugin/-SNAPSHOT/maven-metadata.xml'. Received status code 403 from server: Forbidden"
I have been searching every possible forum for one month but i haven't find a solution yet.I think that the error has to do with jitpack.I would be grateful for a little help!
Thank you!!

![image](https://user-images.githubusercontent.com/38044337/38257483-f81147ca-3768-11e8-8427-d2d02af18023.png)

**Comment by nasos7** [comment]
In case it has to do with the subscription i have joined the  udacity cource "Google Developer Challenge Scholarship" so i think it had to cover me

**Comment by jitpack-io** [comment]
Hi,
At the moment there isn't a subscription for github.com/udacity repositories
/cc @jwill

**Comment by nasos7** [comment]
Unfortunately i don't understand what does this mean.
I reffered the case of subscription because when i search this url: https://jitpack.io/com/github/udacity/android-assistant-gradle-plugin/-SNAPSHOT/maven-metadata.xml
on the browser io get this message.
![default](https://user-images.githubusercontent.com/38044337/38273127-dbee3398-3793-11e8-9fd6-40dbbd382bcd.png)

**Comment by nasos7** [comment]
So what i can do to solve the problem?
Thank you

**Comment by priyankagupta-ITT** [comment]
> Hi, I try to sync a gradle project but i get this error "Error:Could not GET 'https://jitpack.io/com/github/udacity/android-assistant-gradle-plugin/-SNAPSHOT/maven-metadata.xml'. Received status code 403 from server: Forbidden" I have been searching every possible forum for one month but i haven't find a solution yet.I think that the error has to do with jitpack.I would be grateful for a little help! Thank you!!
> 
> ![image](https://user-images.githubusercontent.com/38044337/38257483-f81147ca-3768-11e8-8427-d2d02af18023.png)

can you provide solution here what you did to solve it
