### ISSUE TITLE
Can it support for the project with some jar

### ISSUE THREAD

**Issue by tianzhijiexian** [jitpack/jitpack.io#249]
Start: Wed Oct 21 15:47:59 UTC 2015
Git:
1.0
commit 582aaa5e789394f62730ca292a89751ff77cae21
Author: tianzhijiexian 
Date:   Thu Jul 23 17:12:04 2015 +0800

    ignore

submodule status:
Run gradle build
Gradle build script
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
Downloading https://services.gradle.org/distributions/gradle-2.2.1-all.zip
..................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
Unzipping /home/jitpack/.gradle/wrapper/dists/gradle-2.2.1-all/6dibv5rcnnqlfbq9klf8imrndn/gradle-2.2.1-all.zip to /home/jitpack/.gradle/wrapper/dists/gradle-2.2.1-all/6dibv5rcnnqlfbq9klf8imrndn
Set executable permissions for: /home/jitpack/.gradle/wrapper/dists/gradle-2.2.1-all/6dibv5rcnnqlfbq9klf8imrndn/gradle-2.2.1/bin/gradle

------------------------------------------------------------
Gradle 2.2.1
------------------------------------------------------------

Build time:   2014-11-24 09:45:35 UTC
Build number: none
Revision:     6fcb59c06f43a4e6b1bcb401f7686a8601a1fb4a

Groovy:       2.3.6
Ant:          Apache Ant(TM) version 1.9.3 compiled on December 23 2013
JVM:          1.7.0_76 (Oracle Corporation 24.76-b04)
OS:           Linux 3.13.0-36-generic amd64

Getting a list of gradle tasks
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8

FAILURE: Build failed with an exception.

* Where:
Build file '/build/app/build.gradle' line: 30

* What went wrong:
A problem occurred evaluating project ':app'.
> java.net.URISyntaxException: Illegal character in opaque part at index 2: E:\Github\sign_key.jks 

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8

FAILURE: Build failed with an exception.

* Where:
Build file '/build/app/build.gradle' line: 30

* What went wrong:
A problem occurred evaluating project ':app'.
> java.net.URISyntaxException: Illegal character in opaque part at index 2: E:\Github\sign_key.jks 

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
Gradle 'install' task not found. Please add the 'maven' or 'android-maven' plugin.
See the documentation and examples: https://jitpack.io/docs/

Found android library build file ./share/build.gradle
Running: ./gradlew clean -Pgroup=com.github.tianzhijiexian -Pversion=1.0 install
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
Parallel execution is an incubating feature.
Gradle version 2.2.1

FAILURE: Build failed with an exception.

* Where:
Build file '/build/app/build.gradle' line: 30

* What went wrong:
A problem occurred evaluating project ':app'.
> java.net.URISyntaxExcepti
![qq 20151021235202](https://cloud.githubusercontent.com/assets/9552155/10642097/c4e34e42-784e-11e5-9f93-3967a1eb82d7.png)
on: Illegal character in opaque part at index 2: E:\Github\sign_key.jks 

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 5.183 secs
No build artifacts found

**Comment by tianzhijiexian** [comment]
Start: Wed Oct 21 16:02:46 UTC 2015
Git:
1.0-26-g5effe2e
commit 5effe2ea4109f36deafc7b8d4182a2de22bd3f59
Author: Kale 
Date:   Thu Oct 22 00:00:34 2015 +0800

    更新测试用例

submodule status:
Run gradle build
Gradle build script
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8

------------------------------------------------------------
Gradle 2.7
------------------------------------------------------------

Build time:   2015-09-14 07:26:16 UTC
Build number: none
Revision:     c41505168da69fb0650f4e31c9e01b50ffc97893

Groovy:       2.3.10
Ant:          Apache Ant(TM) version 1.9.3 compiled on December 23 2013
JVM:          1.7.0_76 (Oracle Corporation 24.76-b04)
OS:           Linux 3.13.0-36-generic amd64

Getting a list of gradle tasks
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
Gradle 'install' task not found. Please add the 'maven' or 'android-maven' plugin.
See the documentation and examples: https://jitpack.io/docs/

Found android library build file ./share/build.gradle
Running: gradle clean -Pgroup=com.github.tianzhijiexian -Pversion=5effe2ea41 install
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
Download https://jcenter.bintray.com/com/github/dcendents/android-maven-gradle-plugin/1.3/android-maven-gradle-plugin-1.3.pom
Download https://jcenter.bintray.com/com/github/dcendents/android-maven-gradle-plugin/1.3/android-maven-gradle-plugin-1.3.jar
Gradle version 2.7

FAILURE: Build failed with an exception.

* Where:
Script '/script/maven-plugin.gradle' line: 3

* What went wrong:
A problem occurred evaluating script.
> org/gradle/api/publication/maven/internal/DefaultMavenFactory

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 10.227 secs
No build artifacts found

**Comment by jitpack-io** [comment]
Hi Kale

The gradle wrapper seems to be missing from your repository. Its best to commit and push it.

**Comment by tianzhijiexian** [comment]
Thank you very much... :+1: :100:
