### ISSUE TITLE
Getting 403 forbidden error

### ISSUE THREAD

**Issue by wiziq-jit** [jitpack/jitpack.io#2492]
Hi,

I am using jitpack with my private bitbucket repository to distribute an android library for my organization. 

While this was working fine until yesterday, I am unable to resolve newer versions of my library from jitpack - while the older versions seem to be accessible still. The bitbucket repo itself is readable in my jitpack account - I can see my latest commits, tags etc. But when I press 'get it' and use the generated compile statement in gradle - it throws a 403 unresolved error. I am also not seeing any logs generated for the new builds in jitpack. 

I have checked and rechecked - I have not altered any config related code for jitpack, only my functional android code. My bitbucket app password is in place as well.

Also, when I try to fetch a SNAPSHOT version of my library - I get the suggestion that there is a "newer" version available which is actually an older version [SNAPSHOTS should be the latest versions, shouldn't they?]

**Comment by hugheba** [comment]
I'm having the same issue from Bitrise.io and CircleCI

Looks like they put Cloudflare in front of the domain and it's rate limiting requests.

If you're on a CI service then there's probably a lot of other people requesting artifacts from jitpack and trigger the 403's.

**Comment by jitpack-io** [comment]
Hi @hugheba 

You're right, we are using Cloudflare and it is likely that too many requests are coming from CI services.
Looking into it.

**Comment by jitpack-io** [comment]
@wiziq-jit After a closer look found out that 403 happens when a JitPack subscription is not active.

Would recommend visiting https://jitpack.io/w/user to see if there is an issue

**Comment by farazhassan** [comment]
^ Have the same issue but the subscription is active. How do I get support on issues like these apart from Github issues which is taking days to get even a single response?

**Comment by e-power** [comment]
Same here. My subscription is active but I get a 403 on gradle.

**Comment by umarpazir11** [comment]
I already purchased but still getting this issue.

Subscription is not active right now
Requested subscription: bitbucket.org/egoteamapp. 
Your subscriptions are listed in https://jitpack.io/w/user
Please contact Support or repository admins if you need assistance.

**Comment by ptsiogas** [comment]
We are getting the same error while our subscription is active. This is causing us a major problem.

**Comment by priyankagupta-ITT** [comment]
please provide solution here how to fix this

**Comment by Spyne-Tech** [comment]
Account status is INACTIVE from yesterday and i have yearly subscription. After payment @jitpack-io sent a mail with me that your payment is done and account is active and ready to use but showing Inactive status over account. PFA for more details.

 Getting below error. 

Subscription is not active right now
Requested subscription: bitbucket.org/egoteamapp.
Your subscriptions are listed in https://jitpack.io/w/user
Please contact Support or repository admins if you need assistance.

<img width="1083" alt="Screenshot 2023-07-18 at 12 16 08 PM" src="https://github.com/jitpack/jitpack.io/assets/120455818/2b9b0ee5-1ce3-488b-8f9f-a01f3f1575f6">
<img width="731" alt="Screenshot 2023-07-18 at 12 02 26 PM" src="https://github.com/jitpack/jitpack.io/assets/120455818/aee56d95-59ed-4d16-bd35-4adf9279e95a">
