### ISSUE TITLE
Bitbucket support

### ISSUE THREAD

**Issue by dpisarenko** [jitpack/jitpack.io#25]
Bitbucket allows you to have an unlimited number of private repositories (as long as you have less than 5 users) for free. GitHub doesn't allow you to create private repositories for free.

If Jitpack.io supported Bitbucket, we would have a free, cloud-based build system.

**Comment by jitpack-io** [comment]
Good idea! Though without authentication the library from your private repo will be accessible to anyone. Assuming they know the repo url.

**Comment by jitpack-io** [comment]
Ok, initial BitBucket support has arrived! 
For example: https://jitpack.io/#org.bitbucket.jitpack/maven-simple

**Comment by shkschneider** [comment]
Just awesome!

**Comment by jitpack-io** [comment]
@shkschneider Thanks! Enjoy!:)

**Comment by dpisarenko** [comment]
Thanks for implementing this feature. Now I'm trying to use it. Imagine, I have a project X on BitBucket and I want to use it as a dependency in project Y.

What do I need to do in X in order to be able to use it in Y?

In other words: When I specify Jitpack-based dependency X in Y's pom.xml, how will JitPack know

a) that X is hosted at BitBucket and
b) what its repository name is?

**Comment by dpisarenko** [comment]
For the sake of simplicity, let's assume that project X is hosted in a public BitBucket repository.

**Comment by jitpack-io** [comment]
It will infer that its BitBucket from the artifact groupId: 'org.bitbucket.User:Repo:Tag'.
Btw, you can also paste the BitBucket repository url on the website to get gradle/maven coordinates:)

**Comment by dpisarenko** [comment]
Thanks. If I've called `git tag -a 1.2-SNAPSHOT -m 1.2-SNAPSHOT` in my public repo, then pushed the changes to BitBucket, what else do I need to do in order to be able to refer to the dependency using Jitpack?

Example: https://bitbucket.org/altruix/primcity-api

When I try to use in another project using 

```
<dependency>
  <groupId>org.bitbucket.altruix</groupId>
  <artifactId>primcity-api</artifactId>
  <version>1.2-SNAPSHOT</version>
</dependency>
```

but I'm getting errors duing Maven build.

I'm also fine with using a commit ID as a version designator (it's even better for me), but neither 

```
      	<dependency>
           <groupId>org.bitbucket.altruix</groupId>
           <artifactId>primcity-api</artifactId>
           <version>eb896b3d595b3cf201eace1f759dc9b1d5ca7294</version>
	     </dependency>
```
nor

```
<dependency>
  <groupId>org.bitbucket.altruix</groupId>
  <artifactId>primcity-api</artifactId>
  <version>e182e76</version>
</dependency>
```
worked.

**Comment by jitpack-io** [comment]
Strange that the tags dont show up on the projects BB page https://bitbucket.org/altruix/primcity-api#tags

**Comment by dpisarenko** [comment]
Is `git tag -a ... -m ...` command correct for tagging?

**Comment by jitpack-io** [comment]
yes, but also you need to push them `git push --tags`

**Comment by dpisarenko** [comment]
@jitpack-io Thanks. That was the problem. Now it seems to work. Thanks again for implementing this feature!

**Comment by jitpack-io** [comment]
Fantastic! You're welcome

**Comment by jitpack-io** [comment]
Hi all,Got an update on this: We now support BitBucket repositories on https://jitpack.io website.
If you Sign In and click on your username (https://jitpack.io/w/user.html)
you'll see a new setting called *BitBucket API Key*. Set it to your Team API Key and then Look Up your repositories on  https://jitpack.io.
