### ISSUE TITLE
Build issue with custom domain, but can't see it?

### ISSUE THREAD

**Issue by afollestad** [jitpack/jitpack.io#251]
The following should work:

```Gradle
compile('com.afollestad:material-cab:0.1.6@aar') {
        transitive = true
}
```

But it doesn't; I don't see any build log from the website.

**Comment by jitpack-io** [comment]
It appears version 0.1.6 was requested before the tag was added. The log should have appeared on the website so we're going to fix that.
In general the url for build logs is like this:
https://jitpack.io/com/afollestad/material-cab/0.1.6/build.log
and when you look at the build log JitPack will do another check to see if the tag exists.

**Comment by afollestad** [comment]
Oh okay, thank you!
