### ISSUE TITLE
Problem with custom domain name

### ISSUE THREAD

**Issue by saulvargas** [jitpack/jitpack.io#254]
Hi!

I am having problems with the custom domain name ranksys.org with the following project https://github.com/RankSys/cosa. Specifically, I am trying to make the following maven dependency work:
~~~
        <dependency>
            <groupId>org.ranksys</groupId>
            <artifactId>cosa</artifactId>
            <version>0.1</version>
        </dependency>    
~~~
The DNS resolution seems to work fine (https://jitpack.io/#org.ranksys/cosa/0.1) and the depencency is built and downloaded when I use the original GitHub groupId. I have succesfully used other custom domains for other projects and I believe I repeated the same steps for this case.

Any clue?

**Comment by jitpack-io** [comment]
Hi 

Fixed. It should have worked for you the first time but somehow dns resolution wasn't propagated to all parts of our system. Now looking into why

**Comment by saulvargas** [comment]
Awesome! Now it works perfectly. Thanks a lot!

**Comment by strokine** [comment]
I have the same problem:
[https://jitpack.io/#ws.dashing/dynamic-config](https://jitpack.io/#ws.dashing/dynamic-config)
Everything looks normal, the JAR is built.
But, when I'm using this dependency:
```xml
<dependency>
	<groupId>ws.dashing</groupId>
	<artifactId>dynamic-config</artifactId>
	<version>1.0</version>
</dependency>
```
maven failes to download the jar.

But that one works fine:
```xml
<dependency>
	<groupId>com.github.dashing-ws</groupId>
	<artifactId>dynamic-config</artifactId>
	<version>1.0</version>
</dependency>
```

I wish I could use the original one. Please help. Thanks,
