### ISSUE TITLE
Can't access logs and not returning the jars/poms

### ISSUE THREAD

**Issue by pasviegas** [jitpack/jitpack.io#256]
Hey!

I have a problem here:
https://jitpack.io/private#intelimen/occ-middleware/f0b6fe8d4d

Really urgent as this project is used in a production environment and we need to release a new version.

Thanks

**Comment by jitpack-io** [comment]
Hi @pasviegas 
Having a look

**Comment by jitpack-io** [comment]
Hi,
It wasn't built yet so triggered a build for that commit. Sorry about the hiccup. Looks all right now:
https://jitpack.io/com/github/intelimen/occ-middleware/f0b6fe8d4d/build.log
