### ISSUE TITLE
android-support-v4-preferencefragment/717a45433b build issue

### ISSUE THREAD

**Issue by itvdonsk** [jitpack/jitpack.io#257]
Log https://jitpack.io/com/github/kolavar/android-support-v4-preferencefragment/717a45433b/build.log

**Comment by jitpack-io** [comment]
Hi Alexandr

Looks like this project deploys to some local directory
https://github.com/kolavar/android-support-v4-preferencefragment/blob/master/build.gradle#L46

and that's why JitPack can't find the artifacts. It should instead deploy to local maven repository $HOME/.m2/repository.
