### ISSUE TITLE
Publish javadocs

### ISSUE THREAD

**Issue by jitpack-io** [jitpack/jitpack.io#26]
If the project builds a javadoc jar, unzip and host the javadocs on jitpack.io

**Comment by sanity** [comment]
+1 ;)

**Comment by jitpack-io** [comment]
@sanity https://jitpack.io/com/github/sanity/quickml/0.7.4/javadoc/

**Comment by jitpack-io** [comment]
Javadocs are now published just-in-time when first requested using the url:
 - `https://jitpack.io/com/github/USER/REPO/VERSION/javadoc/`
