### ISSUE TITLE
FirebaseUI-Android/adf79e351c build

### ISSUE THREAD

**Issue by SUPERCILEX** [jitpack/jitpack.io#2602]
Log https://jitpack.io/com/github/SUPERCILEX/FirebaseUI-Android/adf79e351c/build.log

**Comment by bgiori** [comment]
Hi I'm having the same issue. We're you able to find a solution?

**Comment by SUPERCILEX** [comment]
Nope. @jitpack-io please help

**Comment by bgiori** [comment]
I just found the solution from a previously closed issue  #2600 
my issue #2623

basically, upgrade to or add "com.android.support:appcompat-v7:27.1.1"

**Comment by SUPERCILEX** [comment]
I'm already using that version though. TBH, it seems like changing something that messes with the cache fixes things but I'm not sure. I'll try your solution and see.

**Comment by bgiori** [comment]
I also needed to add this to the failing module's `build.gradle`:
```
configurations.all {
    resolutionStrategy {
        force 'com.android.support:support-annotations:27.1.1'
        force 'com.android.support:support-core-utils:27.1.1'
        force 'com.android.support:support-compat:27.1.1'
    }
}
```

**Comment by jitpack-io** [comment]
Hi @SUPERCILEX 

This issue should be resolved.
The latest commit on master succeeded https://jitpack.io/com/github/SUPERCILEX/FirebaseUI-Android/-1.2.0-gec2e8de-596/build.log

**Comment by SUPERCILEX** [comment]
Yeah, it fixed itself.
