### ISSUE TITLE
Badge is not working

### ISSUE THREAD

**Issue by SandroMachado** [jitpack/jitpack.io#263]
I tired to add the jitpack badge to my project but I think it is not working. In the example, the badge is also broken.

<img width="697" alt="screen shot 2015-11-02 at 16 11 37" src="https://cloud.githubusercontent.com/assets/631739/10886992/9c6ff1f4-817c-11e5-996e-b3b68e213f1b.png">

**Comment by jitpack-io** [comment]
Hi Sandro

You're right, there's an issue lately with showing GitHub releases in badges. We've alerted Shields.io https://twitter.com/Shields_io/status/651736410706288640 and it might get resolved soon.
Also considering providing our own badges without relying on external services.

**Comment by SandroMachado** [comment]
Thanks @jitpack-io !

**Comment by SandroMachado** [comment]
@jitpack-io any updates about this? The badge is not stable. Sometimes it works, sometimes not...

**Comment by jitpack-io** [comment]
There's an ongoing effort in https://github.com/badges/shields project with a few open issues (529, 564).

**Comment by jitpack-io** [comment]
Now providing own badges https://github.com/jitpack/jitpack.io/blob/master/README.md#badges

**Comment by SandroMachado** [comment]
Hum, it is also broken:

<img width="875" alt="screen shot 2016-01-11 at 15 18 48" src="https://cloud.githubusercontent.com/assets/631739/12237471/b77c7590-b876-11e5-8861-1e28fd89ecf2.png">

**Comment by SandroMachado** [comment]
It is working now! Thanks, this is great!

**Comment by projectdelta6** [comment]
Some years later, it seems the badge for private repos is not working again/still
My badge just will not load, but the one on my public repos it works fine.

[![](https://jitpack.io/v/appoly/FormolyEngine-Android.svg)](https://jitpack.io/#appoly/FormolyEngine-Android)
