### ISSUE TITLE
Motion4Droid/v0.2.0 build issue

### ISSUE THREAD

**Issue by JayveeHe** [jitpack/jitpack.io#268]
Log https://jitpack.io/com/github/JayveeHe/Motion4Droid/v0.2.0/build.log

> failed to find Build Tools revision 23.0.2

I have try to run ./gradlew install in my project root path, and build successfully.
Is the latest Android Build Tools available?

**Comment by jitpack-io** [comment]
It is now! Thanks for raising the issue!
