### ISSUE TITLE
Cannot build when using android support 26.1.0  :( :(

### ISSUE THREAD

**Issue by yosriz** [jitpack/jitpack.io#2685]
using some library from android support ver 26.1.0 will fail the build, this is a minimal example test library with this problem:
https://jitpack.io/com/github/yosriz/jit-pack-test/64ad5fde3b/build.log
( a real library with this issue here:
https://jitpack.io/com/github/kinecosystem/kin-core-android/4e1c838aba/build.log)
when using the same code with downgraded support library of 26.0.2 build is fine:
https://jitpack.io/com/github/yosriz/jit-pack-test/519ee33a4f/build.log
(and on a real library:
https://jitpack.io/com/github/kinecosystem/kin-core-android/19cc6e9583/build.log)

I see no problem with downloading this support library version directly:
https://dl.google.com/dl/android/maven2/com/android/support/support-annotations/26.1.0/support-annotations-26.1.0.jar

**Comment by jitpack-io** [comment]
Hi @yosriz 

This issue should now be resolved and we've rebuilt that version:
https://jitpack.io/com/github/yosriz/jit-pack-test/64ad5fde3b/build.log
