### ISSUE TITLE
maven-karma-plugin/maven-karma-plugin-2.0.2 build issue

### ISSUE THREAD

**Issue by ominaiev** [jitpack/jitpack.io#271]
Log https://jitpack.io/com/github/aliebling/maven-karma-plugin/maven-karma-plugin-2.0.2/build.log

**Comment by jitpack-io** [comment]
Hi @ominaiev 
This project seems to have a circular dependency on itself https://github.com/aliebling/maven-karma-plugin/blob/master/pom.xml#L67-L71
so it doesn't build.
