### ISSUE TITLE
Module in fork of DBFlow not caught

### ISSUE THREAD

**Issue by bryant1410** [jitpack/jitpack.io#272]
I try this, and it's not working:

```groovy
compile 'com.github.xmartlabs.DBFlow:DBFlow:194af3593d'
```

Any help?

Thank you

**Comment by jitpack-io** [comment]
Hi,

It also fails locally when running `./gradlew tasks`.
The problem is that it defines the android-maven and the usual maven plugin: https://github.com/xmartlabs/DBFlow/blob/master/DBFlow-Core/build.gradle#L2

It also has this line in DBFlow-Compiler module. Without these lines it should work.
