### ISSUE TITLE
unbale to Create dependency from private repo of self hosted domain of gitlab

### ISSUE THREAD

**Issue by ashishgupta2510** [jitpack/jitpack.io#2730]
Hello 

My company have self hosted domain of gitlab and create private repo and create a branch in repo for me as a developer and now i push the code is my branch and go to git pack and put access token and git server url in jitpack, after all these peocess when i click on lookup of jitpack ,it is unable to access my repo.
Is there anyone to help me out from this issue.

 
Thank you!

**Comment by niwoshijie** [comment]
Have you solved your problem?I have the same problem
