### ISSUE TITLE
JitPack not accetting SDK licences anymore

### ISSUE THREAD

**Issue by paolorotolo** [jitpack/jitpack.io#2743]
JitPack is not automatically accepting SDK licences:
```
* What went wrong:
A problem occurred configuring project ':app'.
> Failed to install the following Android SDK packages as some licences have not been accepted.
     platforms;android-27 Android SDK Platform 27
     build-tools;27.0.3 Android SDK Build-Tools 27.0.3
  To build this project, accept the SDK license agreements and install the missing components using the Android Studio SDK Manager.
  Alternatively, to transfer the license agreements from one workstation to another, see http://d.android.com/r/studio-ui/export-licenses.html
  
  Using Android SDK: /android
```

Log https://jitpack.io/com/github/2coffees1team/GlideToVectorYou/v1.1.0/build.log

**Comment by paolorotolo** [comment]
Rebuilding after 30 minutes "just fixed" the issue.
Thanks anyway.

**Comment by hasan5151** [comment]
same problem again

**Comment by aveenashmandhwani** [comment]
Hey!!!

Just open terminal or git bash and head over to your android studio directory.

For windows users:
`cd C:\Users\{USERNAME}\AppData\Local\Android\Sdk\tools\bin`

and then run this to accept unaccepted licenses.
`sdkmanager.bat --licenses`

and then just review and accept them by typing 'y' and hit enter till its done..

Reference:

https://www.youtube.com/watch?v=c7HmwiTtYPE&t=580s
