### ISSUE TITLE
jenkins-automation/latest build issue

### ISSUE THREAD

**Issue by imuchnik** [jitpack/jitpack.io#275]
Log https://jitpack.io/com/github/cfpb/jenkins-automation/latest/build.log

Build failing FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all dependencies for configuration ':compile'.
> Could not find com.github.cfpb:jenkins-automation:d35cee2b4e.
  Searched in the following locations:
      https://repo1.maven.org/maven2/com/github/cfpb/jenkins-automation/d35cee2b4e/jenkins-automation-d35cee2b4e.pom
      https://repo1.maven.org/maven2/com/github/cfpb/jenkins-automation/d35cee2b4e/jenkins-automation-d35cee2b4e.jar
      https://jcenter.bintray.com/com/github/cfpb/jenkins-automation/d35cee2b4e/jenkins-automation-d35cee2b4e.pom
      https://jcenter.bintray.com/com/github/cfpb/jenkins-automation/d35cee2b4e/jenkins-automation-d35cee2b4e.jar
      http://repo.jenkins-ci.org/releases/com/github/cfpb/jenkins-automation/d35cee2b4e/jenkins-automation-d35cee2b4e.pom
      http://repo.jenkins-ci.org/releases/com/github/cfpb/jenkins-automation/d35cee2b4e/jenkins-automation-d35cee2b4e.jar
      https://jitpack.io/com/github/cfpb/jenkins-automation/d35cee2b4e/jenkins-automation-d35cee2b4e.pom
      https://jitpack.io/com/github/cfpb/jenkins-automation/d35cee2b4e/jenkins-automation-d35cee2b4e.jar
  Required by:
      cfpb.jenkins:migrations:1.0-SNAPSHOT

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 5.606 secs
Could not find com.github.cfpb:jenkins-automation:d35cee2b4e.
Searched in the following locations:
    https://repo1.maven.org/maven2/com/github/cfpb/jenkins-automation/d35cee2b4e/jenkins-automation-d35cee2b4e.pom
    https://repo1.maven.org/maven2/com/github/cfpb/jenkins-automation/d35cee2b4e/jenkins-automation-d35cee2b4e.jar
    https://jcenter.bintray.com/com/github/cfpb/jenkins-automation/d35cee2b4e/jenkins-automation-d35cee2b4e.pom
    https://jcenter.bintray.com/com/github/cfpb/jenkins-automation/d35cee2b4e/jenkins-automation-d35cee2b4e.jar
    http://repo.jenkins-ci.org/releases/com/github/cfpb/jenkins-automation/d35cee2b4e/jenkins-automation-d35cee2b4e.pom
    http://repo.jenkins-ci.org/releases/com/github/cfpb/jenkins-automation/d35cee2b4e/jenkins-automation-d35cee2b4e.jar
    https://jitpack.io/com/github/cfpb/jenkins-automation/d35cee2b4e/jenkins-automation-d35cee2b4e.pom
    https://jitpack.io/com/github/cfpb/jenkins-automation/d35cee2b4e/jenkins-automation-d35cee2b4e.jar
Required by:
    cfpb.jenkins:migrations:1.0-SNAPSHOT
11:16:02 AM: External task execution finished 'build'.

**Comment by jitpack-io** [comment]
Hi!

Almost there. The only thing missing is the the maven plugin. 
https://jitpack.io/docs/BUILDING/#gradle-projects
