### ISSUE TITLE
ThreeTenABP/1.0.2 build issue

### ISSUE THREAD

**Issue by pengrad** [jitpack/jitpack.io#277]
Log https://jitpack.io/com/github/jakewharton/ThreeTenABP/1.0.2/build.log

**Comment by jitpack-io** [comment]
Hi @pengrad 

The trouble is that it doesn't use properties everywhere in the build file as in here 
https://github.com/chrisbanes/gradle-mvn-push/blob/master/gradle-mvn-push.gradle#L24-L32

so the build script tried to upload files to sonatype and fails.

**Comment by pengrad** [comment]
Thanks!

**Comment by jitpack-io** [comment]
For now you could try our fork https://jitpack.io/#jitpack-io/ThreeTenABP/c811212
or vote on the PR https://github.com/JakeWharton/ThreeTenABP/pull/18

**Comment by jitpack-io** [comment]
1.0.2 now also works
