### ISSUE TITLE
Cant compile lib related to jitpack

### ISSUE THREAD

**Issue by adamvarhegyi** [jitpack/jitpack.io#278]
Hi, im trying to compile the lib called **material-dialogs** 

link: https://github.com/afollestad/material-dialogs

I got the **following error:**

    Information:Gradle tasks [:DoToDoSenderApp:assembleDebug]
    Error:A problem occurred configuring project ':DoToDoSenderApp'.
    > Could not resolve all dependencies for configuration ':DoToDoSenderApp:_debugCompile'.
    > Could not find com.github.afollestad.material-dialogs:core:0.8.5.0.
    Searched in the following locations:
    https://jcenter.bintray.com/com/github/afollestad/material-dialogs/core/0.8.5.0/core-0.8.5.0.pom
    https://jcenter.bintray.com/com/github/afollestad/material-dialogs/core/0.8.5.0/core-0.8.5.0.aar
    https://repo1.maven.org/maven2/com/github/afollestad/material-dialogs/core/0.8.5.0/core-0.8.5.0.pom
    https://repo1.maven.org/maven2/com/github/afollestad/material-dialogs/core/0.8.5.0/core-0.8.5.0.aar
    file:/C:/Users/Joying/AppData/Local/Android/sdk/extras/android/m2repository/com/github/afollestad/material-dialogs/core/0.8.5.0/core-0.8.5.0.pom
    file:/C:/Users/Joying/AppData/Local/Android/sdk/extras/android/m2repository/com/github/afollestad/material-dialogs/core/0.8.5.0/core-0.8.5.0.aar
    file:/C:/Users/Joying/AppData/Local/Android/sdk/extras/google/m2repository/com/github/afollestad/material-dialogs/core/0.8.5.0/core-0.8.5.0.pom
    file:/C:/Users/Joying/AppData/Local/Android/sdk/extras/google/m2repository/com/github/afollestad/material-dialogs/core/0.8.5.0/core-0.8.5.0.aar
    Required by:
    DoToDo_as:DoToDoSenderApp:unspecified > DoToDo_as:DoToDoEssentials:unspecified
    Information:BUILD FAILED
    Information:Total time: 2.98 secs
    Information:1 error
    Information:0 warnings
    Information:See complete output in console

This is **my gradle file:**

    apply plugin: 'com.android.library'

    android {
    compileSdkVersion 23
    buildToolsVersion "23.0.1"

    defaultConfig {
        minSdkVersion 19
        targetSdkVersion 22
        versionCode 1
        versionName "1.0"
        multiDexEnabled true
    }
    buildTypes {
        release {
        minifyEnabled false
        proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    }
    repositories {
    mavenCentral()
    maven { url "https://jitpack.io" }
    }

    dependencies {

    compile 'com.android.support:appcompat-v7:23.+' //appcompat for navigation drawer
    compile 'com.android.support:design:23.+' //views
    compile 'com.android.support:support-v13:23.+' //views

    compile 'com.google.android.gms:play-services-gcm:8.1.0' //google gcm pushes
    compile 'com.google.android.gms:play-services-location:8.1.0' //google location functions
    compile 'com.google.android.gms:play-services-maps:8.1.0' //google maps

    compile 'com.facebook.android:facebook-android-sdk:4.6.0' //facebook lib
    compile 'de.hdodenhof:circleimageview:2.0.0' //circle image view
    compile 'com.squareup.picasso:picasso:2.5.2' //image downloader lib
    compile 'com.google.code.gson:gson:2.4' //gson for serialization
    compile 'com.squareup.okio:okio:1.6.0'  //okhttp dependency
    compile 'com.squareup.okhttp:okhttp:2.5.0'   //networking lib
    compile 'com.googlecode.libphonenumber:libphonenumber:5.5' //phone number library

    compile('com.github.afollestad.material-dialogs:core:0.8.5.0@aar') {
        transitive = true
    }

    compile fileTree(dir: 'libs', include: ['*.jar'])
    }

**I have added**

    maven { url "https://jitpack.io" } 

**as well as**

    compile('com.github.afollestad.material-dialogs:core:0.8.5.0@aar') {
        transitive = true
    }

(Gradle is in online mode)

Developer of **material-dialogs** said that it is an jitpack issue. I have some doubt about it altough i must post this because i have no other options in the other topic.

If it is not a jitpack issue sorry for stealing your time.

**Comment by jitpack-io** [comment]
Hi,

It seems your build doesn't look inside JitPack for the lib. 
Just something to try out quickly, in your root build.gradle try adding:
```gradle
allprojects {
        repositories { 
            jcenter()
            maven { url "https://jitpack.io" }
        }
}
```
If you have allprojects, just add jitpack. Does that make a difference?

**Comment by adamvarhegyi** [comment]
It is solved my issue, thank you very much.

**Comment by jitpack-io** [comment]
Great!
