### ISSUE TITLE
jahirfiquitiva/KustomAPI build error

### ISSUE THREAD

**Issue by jahirfiquitiva** [jitpack/jitpack.io#2789]
1. Build log from https://jitpack.io --> https://jitpack.io/com/jahirfiquitiva/KustomAPI/bb4732d/build.log
2. Does the project build on your machine? --> Yes, it does

Errors say:
`error: package android.support.annotation does not exist`
`error: cannot find symbol import org.kustom.api.dashboard.R;`

But again, the project builds properly in my machine and everything is working normally

Can you help me find where the issue is? :thinking:
Thanks in advance :blush:

**Comment by ubuntudroid** [comment]
We're seeing the exact same issue: https://jitpack.io/com/github/stanwood/CRM_Framework_android/4e676bb44f/build.log

**Comment by jitpack-io** [comment]
Hi,

Does it build on your machine with the same command?
`./gradlew clean -Pgroup=com.jahirfiquitiva -Pversion=bb4732d -xtest -xlint install`

The normal compilation succeeds but the error comes from `:api:javadoc` task

**Comment by jitpack-io** [comment]
Could you give this a try: https://stackoverflow.com/q/29663918/4562758

**Comment by ubuntudroid** [comment]
Tried the stuff over there - got rid of the annotation issue, but still have it for nearly all other dependencies which is super weird.

Used https://stackoverflow.com/a/49172753/304266 as we already had everything in there except for the `configurations.implementation.setCanBeResolved(true)` line.

We'll investigate next week and get back here once we have a solution for this.

**Comment by jitpack-io** [comment]
Perhaps as a temporary workaround you could disable the `javadoc` tasks.

**Comment by ubuntudroid** [comment]
The good thing is, that the build itself works and creates artifacts, just no javadoc.
