### ISSUE TITLE
helpdroid/v0.6.0 build

### ISSUE THREAD

**Issue by EhsanMashhadi** [jitpack/jitpack.io#2818]
Log https://jitpack.io/com/github/EhsanMashhadi/helpdroid/v0.6.0/build.log
I have no problem since today. I can run this command locally and everything is OK. What is the problem on Jitpack?

**Comment by jitpack-io** [comment]
Hi,

This error:
`> A problem occurred starting process 'command '/android/ndk-bundle/toolchains/mips64el-linux-android-4.9/prebuilt/linux-x86_64/bin/mips64el-linux-android-strip''`

usually means that Gradle and the Android SDK plugin need to be updated to the latest.

**Comment by EhsanMashhadi** [comment]
@jitpack-io Thanks it works.
