### ISSUE TITLE
prautobeans/1.0 build issue

### ISSUE THREAD

**Issue by jnorthrup** [jitpack/jitpack.io#282]
Log https://jitpack.io/com/github/0xCopy/prautobeans/1.0/build.log

built fine, jars missing

**Comment by jnorthrup** [comment]
https://gist.github.com/anonymous/d3db7f87a70ee5eda0e0 pom that fails to fetch subproject

**Comment by jnorthrup** [comment]
https://gist.github.com/anonymous/cfc8179c2dc4b00c6367 build failures

**Comment by jitpack-io** [comment]
Hi

Rebuilt the project and the jars are there now.

**Comment by jnorthrup** [comment]
was there a self-serve purge option i missed?

**Comment by jitpack-io** [comment]
We have an option to delete the old build. Requesting again will result in a fresh build https://jitpack.io/docs/BUILDING/#rebuilding
