### ISSUE TITLE
How Can I authorize another jitpack project in maven ?

### ISSUE THREAD

**Issue by KorkugunuB** [jitpack/jitpack.io#2848]
Log https://jitpack.io/org/bitbucket/valemc/vmodule/1.0/build.log
How Can I authorize another jitpack project ?

**Comment by jitpack-io** [comment]
Hi @KorkugunuB 

Are you using your jitpack token in `$HOME/.m2/settings`?
It should be the same one as here: https://jitpack.io/private#auth

**Comment by KorkugunuB** [comment]
yeah, I did it at local. but there's a problem with maven build.

**Comment by KorkugunuB** [comment]
Error log:
`[ERROR] Failed to execute goal on project vmodule: Could not resolve dependencies for project com.valemc:vmodule:jar:1.0: Failed to collect dependencies at org.bitbucket.valemc:vutil:jar:1.3: Failed to read artifact descriptor for org.bitbucket.valemc:vutil:jar:1.3: Could not transfer artifact org.bitbucket.valemc:vutil:pom:1.3 from/to jitpack.io (https://jitpack.io): Not authorized , ReasonPhrase:Unauthorized. -> [Help 1]`

**Comment by jitpack-io** [comment]
Ok, then your should get passed to the dependency automatically. Having a look at why it didn't

**Comment by jitpack-io** [comment]
For now built it by setting a `TOKEN` environment variable so the dependency should be resolving.

**Comment by KorkugunuB** [comment]
I'm trying.

**Comment by sadiktech** [comment]
How did you done ? please share the steps to setup env variables in maven

**Comment by csquan** [comment]
same questions ,how did you done?
