### ISSUE TITLE
How can i add more than one token ?

### ISSUE THREAD

**Issue by KorkugunuB** [jitpack/jitpack.io#2856]
Log https://jitpack.io/org/bitbucket/valemc/vcommands-bukkit/1.0/build.log
How can i add more than one token ?
https://imgur.com/FvyiFsx I added it here. but it didn't.

**Comment by KorkugunuB** [comment]
@jitpack-io can you help me?

**Comment by jitpack-io** [comment]
Hi @KorkugunuB 

We made some improvements today and `TOKEN` variables should no longer be necessary.
Rebuilt version 1.0 without tokens and it was fine.

**Comment by KorkugunuB** [comment]
thanks for your help.
