### ISSUE TITLE
FormGenerator/v2.1.0 Build Issue

### ISSUE THREAD

**Issue by jguerinet** [jitpack/jitpack.io#286]
Log: https://jitpack.io/com/github/jguerinet/form-generator/2.1.0/build.log
I believe it's because I updated the support libraries to v23.1.1 (released this morning) and they probably have not been downloaded/updated on the machine building the project.

**Comment by jitpack-io** [comment]
Quite right. Updated the libs and re-built.
Looks ok now

**Comment by jguerinet** [comment]
Thanks !
