### ISSUE TITLE
No build artifacts found

### ISSUE THREAD

**Issue by MarsXan** [jitpack/jitpack.io#2861]
Hi
Jetpack was unable to build and publish artifacts from my project when more than one Android library module was added to the repo

Log https://jitpack.io/com/github/MarsXan/floatingsearchview/2.1.2/build.log

**Comment by jitpack-io** [comment]
Hi,

If you have multiple library modules then would recommend adding the android-maven plugin to each module: https://jitpack.io/docs/ANDROID/#gradle
