### ISSUE TITLE
the version is not appearing in jitpack when tag is text

### ISSUE THREAD

**Issue by KorkugunuB** [jitpack/jitpack.io#2864]
Bitbucket project tags: https://imgur.com/UnI4GEN 
Jitpack Project versions: https://imgur.com/ledYr0J
Jitpack Project: https://jitpack.io/#org.bitbucket.valemc/vutil
it doesn't appear in the versions section.

**Comment by KorkugunuB** [comment]
@jitpack-io help.

**Comment by jitpack-io** [comment]
Hi @KorkugunuB 

JitPack sorts versions using semantic versioning so the text would come last even if it was added later.

**Comment by jitpack-io** [comment]
To get the latest build of your library would recommend using `master-SNAPSHOT` as version.

**Comment by KorkugunuB** [comment]
thanks
