### ISSUE TITLE
Multiple Artifacts in Ant project

### ISSUE THREAD

**Issue by shannah** [jitpack/jitpack.io#2865]
I'm using Ant with a project that produces two distinct jar files that should be published as distinct artifacts.  E.g.

~~~
$ ant jar
~~~

Generates `dist/mylibrary-thin.jar` and `dist/mylibrary-fat.jar`

I would like to publish mylibrary-thin.jar and mylibrary-fat.jar as distinct artifacts.  Is this possible?

**Comment by Odhita-Kamayana-ConnectedLab** [comment]
I'm also having this issue. Any workarounds? Is it possible?

**Comment by jitpack-io** [comment]
It is possible just not very easily. The rough procedure is:
1. Generate two pom.xml files in build directory (must have groupId/artifactId)
2. Install jars and pom files into local maven repo ~/.m2 under proper groupId/artifactId directory

All in all, it would be easier to do with Maven than Ant
