### ISSUE TITLE
BottomSheet/b345188459 build issue

### ISSUE THREAD

**Issue by adrianpop1990** [jitpack/jitpack.io#287]
Log https://jitpack.io/com/github/soarcn/BottomSheet/b345188459/build.log

**Comment by jitpack-io** [comment]
Hi 

The project's build file is trying to deploy to sonatype and that's why it fails. It would need to be changed in order to work with JitPack

**Comment by jitpack-io** [comment]
Hi @adrianpop1990 
It's fixed now.
