### ISSUE TITLE
Rewrite Maven `dependencyManagement` sections

### ISSUE THREAD

**Issue by Stephan202** [jitpack/jitpack.io#2886]
Jitpack rewrites the `groupId` of Maven `<dependencies>` in POMs so as to match the `com.github.$USER` or `com.github.$USER.$ARTIFACT` format. But it does not do this for dependency declarations in `dependencyManagement` sections, it seems. In [this `jitpack.yml` file](https://github.com/PicnicSupermarket/spring-boot-admin/blob/feature/jitpack-support/jitpack.yml) I work around this limitation, but it'd be nice if this were supported out of the box. That way, projects that define a BOM (Bill Of Materials) which includes one or more modules of the same multi-module build "just work".

**Comment by jitpack-io** [comment]
Good point

**Comment by Stephan202** [comment]
@jitpack-io since you seemed sympathetic to the idea back then; are there plans to implement this functionality (or has this been implemented in the mean time)?
