### ISSUE TITLE
"Failed to resolve" for Android multi-module project

### ISSUE THREAD

**Issue by danialgoodwin** [jitpack/jitpack.io#29]
Hi, I've been playing around with JitPack for awhile now but still can't seem to get it to work unfortunately.

[Here's my GitHub repo](https://github.com/danialgoodwin/android-global-overlay). The setup for testing JitPack is two modules. One is the library with maven plugin setup. The other module strictly doesn't have a local dependency on that library, instead it has dependency on the "com.github..." and tries to use JitPack.

Here's a quick checklist of the things that I have gone through so far (and haven't worked):
- For the project ("app") trying to use the library:
  - `https://jitpack.io` is in the buildscript repositories closure
  - I've tried the regular dependency from [jitpack homepage](https://jitpack.io/#danialgoodwin/android-global-overlay/0.1)
  - I've tried the `Repo.Module` dependency pattern as mentioned in the [gradle-modular example](https://github.com/jitpack/gradle-modular)
- For the library project ("globaloverlay"):
  - I've added the android-maven plugin as mentioned in the [android-example](https://github.com/jitpack/android-example)
ed in the [android-example](https://github.com/jitpack/android-example). And, doing `gradle install` does work.
  - I've added `ANDROID_HOME` to my Android SDK path as mentioned in [a different JitPack Android file](https://github.com/jitpack/jitpack.io/blob/master/ANDROID.md)
  - Not using NDK
  - Tried multiple GitHub releases

Any ideas?

**Comment by danialgoodwin** [comment]
Some other information I'm not sure is needed:
- Windows 8.1
- My project is in `C:/`, but Android SDK in `D:/`
- Using Android Studio 1.1.0

**Comment by jitpack-io** [comment]
Hi @danialgoodwin! 

If your app depends on your library you should add the dependency in app/build.gradle as:

    compile project(':globaloverlay')

Here's one project that has a library and a sample app: https://github.com/PhilJay/MPAndroidChart

Submitted you PR https://github.com/danialgoodwin/android-global-overlay/pull/1

**Comment by danialgoodwin** [comment]
Thank you, I'll take a look at the PR soon. But, my purpose with this project was to learn and use JitPack. Adding the local dependency is one way, but that doesn't get me working with JitPack. Basically, that "app" module in my project would be an example for how others can get the library to work on their projects. And, others using the library wouldn't be able to use the local dependency `compile project(':globaloverlay')`

**Comment by jitpack-io** [comment]
Oh, right, see what you mean now. 
Using your library from a different project should be no problem. Looks like it already built: https://jitpack.io/#danialgoodwin/android-global-overlay/0.1

If you want to provide a sample app then it might be easier to create a separate GitHub project for that. There you can add the dependency directly:

    compile 'com.github.danialgoodwin:android-global-overlay:0.1'

The problem of using a dependency like this in the same project is:
 1. jitpack builds your whole project with library and app
 2. app depends on a library in jitpack.io
 3. gradle asks jitpack for the library but the library is currently building. Goes to step 1:)

**Comment by danialgoodwin** [comment]
Awesome! Thank you very much! The library and demo projects are working flawlessly now! And, the readme has been updated to explain the dependency better (along with everything else).

I was thinking recursion too, and was going to suggest that next. ;)
Though, just one last thing that still puzzles me. I tried using the [`Repo.Module`](https://github.com/jitpack/gradle-modular) pattern so that the demo module wouldn't be built by jitpack.

So, possible bug? Or, something else I could be missing?

To test this, in my working [stand-alone demo project](https://github.com/danialgoodwin/android-global-overlay-demo/blob/master/app/build.gradle) that uses `compile 'com.github.danialgoodwin:android-global-overlay:v0.8'`, when I change it to `compile 'com.github.danialgoodwin:android-global-overlay.globaloverlay:v0.8'` I get the gradle error "Failed to resolve".

Thank you,
 - Danial -

**Comment by almozavr** [comment]
Multiproject notation like `compile 'com.github.myrepo:project.library:1.0'` doesn't work for us anymore :(

**Comment by almozavr** [comment]
It worked well on Friday, 13 though.

**Comment by jitpack-io** [comment]
@danialgoodwin Running `gradle install` only publishes the library in the local maven repository and doesn't publish the app. So at the end there is just one module - the library.

**Comment by jitpack-io** [comment]
@almozavr What project and module were you trying to use? Would like to have a look

**Comment by almozavr** [comment]
@jitpack-io project is https://github.com/techery/snapper/tree/0.1.2
It contains library and sample. So, dependency is `compile 'com.github.techery:snapper.library:0.1.2'`
The point of interest could be excluded dep. module and included with newer version inside `library`
see [here](https://github.com/techery/snapper/blob/0.1.2/library/build.gradle)
```
dependencies {
    compile('com.snappydb:snappydb-lib:0.5.0') {
        exclude module: 'kryo'
    }
    compile 'com.esotericsoftware:kryo:3.0.0'
    compile 'com.innahema:collections-query:0.2.8'
}
```

**Comment by almozavr** [comment]
The interesting thing is when I add 
`compile 'com.github.techery:snapper:0.1.2'` (without `library` restriction)
I still see excluded module (kryo version 2 should be excluded)
compile - Classpath for compiling the main sources.
```
+--- com.android.support:appcompat-v7:21.0.3
|    \--- com.android.support:support-v4:21.0.3
|         \--- com.android.support:support-annotations:21.0.3
+--- com.github.techery:snapper:0.1.2
|    +--- com.esotericsoftware:kryo:3.0.0
|    |    +--- com.esotericsoftware:reflectasm:1.10.0
|    |    |    \--- org.ow2.asm:asm:4.2
|    |    +--- com.esotericsoftware:minlog:1.3.0
|    |    \--- org.objenesis:objenesis:2.1
|    +--- com.snappydb:snappydb-lib:0.5.0
|    |    \--- com.esotericsoftware.kryo:kryo:2.24.0
|    |         +--- com.esotericsoftware.minlog:minlog:1.2
|    |         \--- org.objenesis:objenesis:2.1
|    \--- com.innahema:collections-query:0.2.8
+--- com.github.jitpack:gradle-modular.server:1.0
+--- com.jakewharton:butterknife:6.1.0
\--- com.jakewharton.timber:timber:2.7.1
```

The proper dependencies should look like this
```
compile - Classpath for compiling the main sources.
+--- com.android.support:appcompat-v7:21.0.3
|    \--- com.android.support:support-v4:21.0.3
|         \--- com.android.support:support-annotations:21.0.3
+--- project :library
|    +--- com.snappydb:snappydb-lib:0.5.0
|    +--- com.esotericsoftware:kryo:3.0.0
|    |    +--- com.esotericsoftware:reflectasm:1.10.0
|    |    |    \--- org.ow2.asm:asm:4.2
|    |    +--- com.esotericsoftware:minlog:1.3.0
|    |    \--- org.objenesis:objenesis:2.1
|    \--- com.innahema:collections-query:0.2.8
+--- com.jakewharton:butterknife:6.1.0
\--- com.jakewharton.timber:timber:2.7.1
```

**Comment by jitpack-io** [comment]
@almozavr Yes, its enough to specify `compile 'com.github.techery:snapper:0.1.2'` since only the library is published. 
Not yet sure about the exclusion, seems like it should work...

**Comment by almozavr** [comment]
Exclusion does work well when using local lib-project (`compile project(':library')`) and doesn't work when using `jitpack` – seems like a bug?

**Comment by jitpack-io** [comment]
@almozavr The exclusion works with `project :library` because gradle sees the exclusion in the library project. The problem is that this exclusion is not translated to maven's `<exclusions>` when doing `gradle install`. If the exclusion was present in pom.xml it would work.

**Comment by almozavr** [comment]
Could you advise what to do in such case? Assume, we have to provide `pom.xml` besides `build.gradle` files?

**Comment by jitpack-io** [comment]
Not sure yet what is the best workaround, seems like a missing feature in the android-maven plugin [#14](https://github.com/dcendents/android-maven-plugin/issues/14). 

The pom needs to have:
```xml
    <dependency>
      <groupId>com.snappydb</groupId>
      <artifactId>snappydb-lib</artifactId>
      <version>0.5.0</version>
      <scope>compile</scope>
      <exclusions>
        <exclusion>
           <groupId>com.esotericsoftware.kryo</groupId>
           <artifactId>kryo</artifactId>
         </exclusion>
       </exclusions>
    </dependency>
  </dependencies>
```

**Comment by almozavr** [comment]
Seems like a missing feature, right. Thanks!

**Comment by dcendents** [comment]
The maven plugin will not add exclusions based only on the module name (artifactId), it also requires the group (groupId) to be explicitely set, even if gradle does not care about it.

See my pull request: techery/snapper/pull/9
