### ISSUE TITLE
oksse/0.9.0 build

### ISSUE THREAD

**Issue by skimarxall** [jitpack/jitpack.io#2905]
Log https://jitpack.io/com/github/heremaps/oksse/0.9.0/build.log

Not really sure why it fails since the other builds worked. The only difference is I updated the README from the project.

**Comment by lmorda** [comment]
Could this be an Android Studio issue

**Comment by lmorda** [comment]
I was also using this successfully:

implementation 'com.github.heremaps:oksse:master-SNAPSHOT'

before this issue.  Maybe that will help to solve problem.

**Comment by jitpack-io** [comment]
Hi @lmorda 

The reason is that Maven Central recently deprecated TLS v1.1 https://blog.gradle.org/unable-to-download-maven-central-bintray
We've implemented a fix and re-built your project

**Comment by lmorda** [comment]
Verified 
implementation 'com.github.heremaps:oksse:0.9.0'
Working!

**Comment by gunjotSinghMansa** [comment]
Giving issue? :(
