### ISSUE TITLE
Subscription not active

### ISSUE THREAD

**Issue by KorkugunuB** [jitpack/jitpack.io#2913]
Log https://jitpack.io/org/bitbucket/valemc/vutil/2.1/build.log

**Comment by drawwbdev** [comment]
help @jitpack-io

**Comment by drawwbdev** [comment]
I wonder what the maximum number of free projects is.

**Comment by jitpack-io** [comment]
Hi @KorkugunuB @drawwbdev 

It seems you had a free trial which has now expired.
Extended your trial for a couple of days so you can decide if you'd like to order a [subscription](https://jitpack.io/private#subscribe).

**Comment by drawwbdev** [comment]
how did we get past the free trial?
maximum project count?

**Comment by jitpack-io** [comment]
The trial was 14 days and during that time there is no limit on the number of projects.

**Comment by chanjungkim** [comment]
Well, There's no such thing like free trial now. And I am only using one private repo from team repo to create a library by Jitpack. However, I get this error.

```
Subscription is not active right now
Requested subscription: github.com/myteam. 
Your subscriptions are listed in https://jitpack.io/w/user
Please contact Support or repository admins if you need assistance.
```

**Comment by tauseeq-grace** [comment]
Solution:

1. Go to https://jitpack.io/private and ‘Look up’ your private repository.
2. Click on Icon Setting 
![image](https://github.com/jitpack/jitpack.io/assets/144904817/a398e96f-f24d-4304-9e7f-aead6cb1609f)

3. Once the Lock icon turns to unlocked the project’s build artifacts become public. That means your users will be able to install your library without needing an authentication token.
![image](https://github.com/jitpack/jitpack.io/assets/144904817/65e328bc-a0b6-434b-ab49-f91dddbcd50a)

Now the artifact will be accessible

**Comment by JoeBakalor** [comment]
@jitpack-io we are having the same issue.  Our account has an active subscription but under account settings the status is shown as "Inactive" and we are not able to access any of our libraries

**Comment by DysaniazzZ** [comment]
@tauseeq-grace not work for a new build

**Comment by devops1mg** [comment]
Hi Team, 

I am TATA 1MG Healthcare Solutions pvt ltd. . my email- devops@1mg.com. Getting a subscription is not active while subscription has already renewed. Please  resolve issue asap.
