### ISSUE TITLE
buck/f2a2372448 build Failure

### ISSUE THREAD

**Issue by shepting** [jitpack/jitpack.io#2921]
This build seems to have never completed.
Log https://jitpack.io/com/github/airbnb/buck/f2a2372448/build.log

**Comment by shepting** [comment]
The particular issue seems to be a failure to clone after 30 seconds?

**Comment by jitpack-io** [comment]
Hi @shepting 

Indeed, cloning took longer than 30 seconds because of the size of the repo.
We have now increased the timeout to 60 seconds and re-built.
