### ISSUE TITLE
Build failure with authToken for transitive dependency

### ISSUE THREAD

**Issue by michaelcosta** [jitpack/jitpack.io#2928]
I have two private repositories hosted on jitpack where `api-mobile` depends on `common` via jitpack compile dependency.
`common` builds a jar using the maven plugin in gradle and I have verified that locally I can build `api-mobile` with it as a dependency.

When I push `api-mobile` to jitpack (which depends on `common`) I get the following error in the build: 
> Could not get unknown property 'authToken' for Credentials [username: null] of type org.gradle.api.internal.artifacts.repositories.DefaultPasswordCredentials_Decorated.

The build.gradle file for `api-mobile` sets up the maven repo as mentioned in the docs https://jitpack.io/docs/PRIVATE/ but it doesn't appear to be populating the authToken when being built on jitpack
```gradle
//api-mobile/build.gradle
repositories {
    mavenCentral()
    maven {
        url 'https://jitpack.io'
        credentials { username authToken }
    }
}
```

Related issues: 
[Private jitpack used in jitpack repo #2538](https://github.com/jitpack/jitpack.io/issues/2538)
[Build failure in case of transitive dependency #1026](https://github.com/jitpack/jitpack.io/issues/1026)

Thank you!

**Comment by michaelcosta** [comment]
@jitpack-io does it make a difference if I am defining a custom install command? The build script needs to be run from a subdirectory so I had to define a custom jitpack.yml file. Other than this the setup is very standard and doesn't provide useful debugging information
```yml
install:
  - ./build/android/gradlew install -p build/android```

**Comment by jitpack-io** [comment]
Hi @michaelcosta 

Yes, the issue is that your build runs with a custom command. In that case the token is available in an environment variable called `TOKEN`.
So one solution is:
```
install:
  - ./build/android/gradlew install -PauthToken=$TOKEN -p build/android
```

Another - you could run this command in `before_install`:
 - `echo authToken=$TOKEN >> ~/.gradle/gradle.properties`

**Comment by michaelcosta** [comment]
Thanks, passing in the authToken as a gradle project property has fixed the issue
