### ISSUE TITLE
amber-java-clients/0.6 build issue

### ISSUE THREAD

**Issue by SuderPawel** [jitpack/jitpack.io#298]
Cannot build mvn package due to missing `protoc` command

**Comment by jitpack-io** [comment]
Hi Pawel

Protocol buffers is not installed on the build servers. Any chance it could be install using maven?

**Comment by SuderPawel** [comment]
Hello Team,

Thank you for your reply,

This command is in protobuf-compiler package. Not sure if there is any 
maven package which will provide protoc command or similar ability to 
generate protobuf classes. Will try to find a workaround for this.

Best regards,
Pawel

Pozdrawiam,
Paweł Suder

**Comment by SuderPawel** [comment]
Hello Team,

Issue can be closed due to fact that I manually added generated sources in branch used for release.

Cheers
Pawel
