### ISSUE TITLE
Using Nexus proxy pom files are invalid

### ISSUE THREAD

**Issue by domarmstrong** [jitpack/jitpack.io#2998]
Hi, I am trying to use org.everit.json.schema via our nexus proxy. The jars are found as expected but we get dependency issues. After a bit of digging it looks like the pom files nexus gets are just a single string, which is obviously invalid:
`cat org.everit.json.schema-1.9.1.pom`
`com/github/everit-org/json-schema/org.everit.json.schema/1.9.1/org.everit.json.schema-1.9.1.pom`

I've also tried other libraries and get the same, just a string.

Using them directly without the proxy I don't have that problem.

**Comment by jitpack-io** [comment]
Hi @domarmstrong 

Which version of Nexus are you using? JitPack is know to have been working with 2 and 3: https://github.com/jitpack/jitpack.io/issues/506#issuecomment-267338823

What's strange about that single line is that JitPack doesn't return that for artifact requests so hard to say where Nexus got it from. If Nexus just downloads the pom then it should be working:
`curl -H 'User-Agent: Nexus/3' https://jitpack.io/com/github/everit-org/json-schema/org.everit.json.schema/1.9.1/org.everit.json.schema-1.9.1.pom`

Would be interesting to find out what requests Nexus is making to get that single line.

**Comment by domarmstrong** [comment]
I dug into the logs and it turns out there was a repository higher up the order `javaxt.com` which responds with.. 200 and the package string you asked for.. `curl www.javaxt.com/maven/com/github/everit-org/json-schema/org.everit.json.schema/1.9.1/org.everit.json.schema-1.9.1.pom`.

So that's what was causing the problem, moved that to the lowest order and it works fine. Sorry I didn't check the logs before ^^.
