### ISSUE TITLE
Doc says Java 8 is used, but it looks like build is using Java 6

### ISSUE THREAD

**Issue by nitsanw** [jitpack/jitpack.io#30]
https://jitpack.io/com/github/JCTools/JCTools/2c8e85b386/build.log:
Apache Maven 3.2.5 (12a6b3acb947671f09b81f49094c53f426d8cea1; 2014-12-14T17:29:23+00:00)
Maven home: /usr/share/maven
Java version: 1.6.0_45, vendor: Sun Microsystems Inc.
Java home: /usr/lib/jvm/java-6-oracle/jre

I suspect this is because the project has Java 6 binary compatibility, but requires the Java 8 compiler to build

**Comment by jitpack-io** [comment]
Yes you're right. Java 8 is available but jitpack looks for source compatibility in the pom and then builds with that version. This is a bug and needs to be fixed but also we need to infer the version your project requires.

**Comment by jitpack-io** [comment]
A quick workaround right now is to add a .travis.yml file https://github.com/jitpack-io/JCTools/blob/master/.travis.yml 
Works in this forked project: https://jitpack.io/#jitpack-io/JCTools/1.0

**Comment by jitpack-io** [comment]
@nitsanw Fixed. Now building with Java 8 based on the enforcer rule: https://jitpack.io/#JCTools/JCTools
