### ISSUE TITLE
Changes at Jitpack.io causing build to fail

### ISSUE THREAD

**Issue by ialokim** [jitpack/jitpack.io#3006]
Compare these two logs for builds of the same library: [master-b11dba1ea2-1](https://jitpack.io/com/github/schildbach/public-transport-enabler/master-b11dba1ea2-1/build.log) and [b11dba1](https://jitpack.io/com/github/schildbach/public-transport-enabler/b11dba1/build.log).

These are exactly the same commits, the first build happend back in March, the last one today. However, it seems there were some changes at jitpack.io since then (adding a new `JAVA_TOOL_OPTION`: ` -Dhttps.protocols=TLSv1.2`, e.g.) and now all new builds fail with a lot of `> Received fatal alert: protocol_version`.

Perhaps you could check what you've changed and if there are any workarounds to be applied to the source code to make it build successful again.

**Comment by jitpack-io** [comment]
Hi @grote 

Due to changes in Maven Central we now have to enforce the new TLS version however there are solutions:
https://stackoverflow.com/a/51090973/4562758

**Comment by ialokim** [comment]
Thanks a lot for your quick reaction, we [got it to work](https://gitlab.com/opentransitmap/public-transport-enabler/issues/3#note_89082233) adding the gradle wrapper in the required version.
