### ISSUE TITLE
LColorPallette/1.0 build issue

### ISSUE THREAD

**Issue by emreaktrk** [jitpack/jitpack.io#301]
Log https://jitpack.io/com/github/emreaktrk/LColorPallette/1.0/build.log

**Comment by jitpack-io** [comment]
Hi 
In order to build on JitPack the project needs some updating according to guide here: https://jitpack.io/docs/ANDROID/
Also would need upgrading to a newver version of Gradle.

**Comment by emreaktrk** [comment]
Thanks. I give it a try
