### ISSUE TITLE
spring-social-instagram/55e661b7ab build issue

### ISSUE THREAD

**Issue by fvlad** [jitpack/jitpack.io#304]
Log https://jitpack.io/com/github/mattupstate/spring-social-instagram/55e661b7ab/build.log
It needs to build from subproject spring-social-instagram.

**Comment by jitpack-io** [comment]
Hi

Noticed that gradlew script is there in the repo but there is no gradle folder with the actual wrapper. Without the wrapper JitPack doesn't know which version of Gradle to use for building.

**Comment by fvlad** [comment]
Seems like an outdated version of gradle is used.
There is a wrapper folder in buildSrc.

**Comment by jitpack-io** [comment]
I see. That won't be picked up unfortunately as we only support the default layout.
One option is to fork the project and do the change there.
