### ISSUE TITLE
Incompatible with com.android.tools.build:gradle:1.3.1

### ISSUE THREAD

**Issue by tinsukE** [jitpack/jitpack.io#306]
In order to try out the new "Instant Run" Android Studio feature, your gradle build tools version must be com.android.tools.build:gradle:1.3.1 (Gradle 2.8). But after updating the build.gradle files through Android Studio, the Jitpack dependencies are not found anymore, with "Failed to resolve X" errors showing.

http://android-developers.blogspot.nl/2015/11/android-studio-20-preview.html

**Comment by markmooibroek** [comment]
I have the same issue here, after upgrading to the 'InstaRun' required gradle version

**Comment by tinsukE** [comment]
After changing repo from mavenCentral() to jcenter() in my root build.gradle file I could run gradlew from the command line and see the libraries it failed to load (all jitpack).

The jar and aar files were really not there. One example is `https://jitpack.io/com/github/tinsukE/svg-android/2.0.6-1/svg-android-2.0.6-1.jar`

After trying to read the log file, via `https://jitpack.io/com/github/tinsukE/svg-android/2.0.6-1/build.log`, I could see that it triggered the build, and when refreshing I could see it ongoing until it finished.

Done that for all my failing dependencies, and now the build work, at least temporarily.

**Comment by jitpack-io** [comment]
@tinsukE Glad you got it working. If the problem persists, let us know and we'll look into it.

@markmooibroek Would you have an example project that shows your issue?
