### ISSUE TITLE
Can't see organization repos

### ISSUE THREAD

**Issue by imrantoolyt** [jitpack/jitpack.io#3062]
I created an organization and I have a private repo there...all in github.

When I log into jitpack with my github personal account...it does not show the repos in my organization.

I have subscribed for jitpack trial.

This link is not working; https://help.github.com/articles/connecting-with-third-party-applications/#third-party-applications-and-organizations

![xxx](https://user-images.githubusercontent.com/41935674/43562576-006a2096-963b-11e8-9e6f-75505062c947.PNG)

**Comment by jitpack-io** [comment]
Hi @imrantoolyt,

Here is an up-to-date link:
https://help.github.com/articles/approving-oauth-apps-for-your-organization/

Can you see releases if you enter the repository's GitHub url and press 'Look up' on jitpack.io?
