### ISSUE TITLE
Downloading dependencies failed (it differ with every artifact)

### ISSUE THREAD

**Issue by knockmark10** [jitpack/jitpack.io#3070]
Log https://jitpack.io/org/bitbucket/mchaveza/commons-kotlin/1.7.0.7.12/build.log

Everytime I publish, there's a different error (related to downloading some dependencies). What's happening?

**Comment by knockmark10** [comment]
Log1: https://jitpack.io/org/bitbucket/mchaveza/commons-kotlin/1.7.0.7.12/build.log
Log2: https://jitpack.io/org/bitbucket/mchaveza/commons-kotlin/1.7.0.7.11/build.log
As you can see, everytime I build it, it fails on different links. I'd never had this kind of problemas before, and it's not the first time I make changes to my library.

**Comment by jitpack-io** [comment]
Hi,

The problem should now be fixed and the builds succeed after rebuilding.

```
> Could not find support-v4.aar (com.android.support:support-v4:26.1.0).
  Searched in the following locations:
      file:/android/extras/android/m2repository/com/android/support/support-v4/26.1.0/support-v4-26.1.0.aar
```
