### ISSUE TITLE
SeekArc/f84ade705e build issue

### ISSUE THREAD

**Issue by Havock94** [jitpack/jitpack.io#308]
Log https://jitpack.io/com/github/TriggerTrap/SeekArc/f84ade705e/build.log

Failed to resolve: com.github.TriggerTrap:SeekArc:f84ade705

**Comment by jitpack-io** [comment]
Hi @Havock94 

The project should add Gradle build files in order to build on JitPack properly. There's some additional steps for android libraries: https://jitpack.io/docs/ANDROID/
