### ISSUE TITLE
riot-api-java/v3.7.1 build issue

### ISSUE THREAD

**Issue by ReenanCampos** [jitpack/jitpack.io#311]
Log https://jitpack.io/com/github/rithms/riot-api-java/v3.7.1/build.log

Está com erro, diz que não existe nada no caminho do pom.xml

**Comment by jitpack-io** [comment]
Hi
There's a problem with the project setup. It compiles for java 1.5 
https://github.com/rithms/riot-api-java/blob/master/pom.xml#L17

but then uses java 1.8 lambdas in https://github.com/rithms/riot-api-java/blob/master/src/util/Convert.java

**Comment by rithms** [comment]
The project setup has been updated to compile for java 1.8. https://github.com/rithms/riot-api-java/commit/24f4e9f6f019a04b35287ce4e2b2cabe36a8b43e

**Comment by jitpack-io** [comment]
@rithms Works like a charm! https://jitpack.io/com/github/rithms/riot-api-java/24f4e9f/build.log
