### ISSUE TITLE
JavaFX suddenly not supported anymore?

### ISSUE THREAD

**Issue by Frotty** [jitpack/jitpack.io#3121]
Hi, I have been using Jitpack for a long time now, and even thogh nothing really changed in my project, it now doesn't build anymore.

As you can see here https://jitpack.io/#inwc3/wc3libs/ under the "Builds" tab, with f1d455013f suddenly javafx errors pop up in the log which never happened before: https://jitpack.io/com/github/inwc3/wc3libs/f1d455013f/build.log

Is javafx not supported anymore or will this be fixed?

**Comment by jitpack-io** [comment]
Hi,

Thanks for reporting!
It should not have been removed. Looking into it.

**Comment by jitpack-io** [comment]
Should be fixed now. Rebuild https://jitpack.io/com/github/inwc3/wc3libs/f1d455013f/build.log

**Comment by Frotty** [comment]
Sweet, it's working again, thanks 👍
