### ISSUE TITLE
metrics_publish_java/2.0.1 build issue

### ISSUE THREAD

**Issue by 0xbaadf00d** [jitpack/jitpack.io#313]
Log https://jitpack.io/com/github/newrelic-platform/metrics_publish_java/2.0.1/build.log

**Comment by jitpack-io** [comment]
Hi!
Looks like this project uses ant as a build tool which we currently don't support. #127

**Comment by jitpack-io** [comment]
Hi @0xbaadf00d 

It has been a while but Ant builds are now supported so that project builds.
