### ISSUE TITLE
ExtendsFX/v1.0.0-alpha.2 build issue

### ISSUE THREAD

**Issue by johnzeringue** [jitpack/jitpack.io#315]
Log https://jitpack.io/com/github/johnzeringue/ExtendsFX/v1.0.0-alpha.2/build.log

Based on the build log, the build server seems to be unable to download the Gradle wrapper.

**Comment by johnzeringue** [comment]
It's building again, thanks.

**Comment by jitpack-io** [comment]
Indeed, looked like a connectivity issue. Triggered a new build. 
Most welcome!
