### ISSUE TITLE
SublimePicker/2.0.0 build issue

### ISSUE THREAD

**Issue by john990** [jitpack/jitpack.io#316]
Log https://jitpack.io/com/github/vikramkakkar/SublimePicker/2.0.0/build.log

**Comment by jitpack-io** [comment]
Hi @john990 

There doesn't seem to be a 2.0.0 tag in the GitHub repo
Latest commit seems fine though:
https://jitpack.io/#vikramkakkar/SublimePicker/bb405d8d14

**Comment by john990** [comment]
You are right.I Looked mistake.
