### ISSUE TITLE
material-camera/0.1.1 build issue

### ISSUE THREAD

**Issue by jd-alexander** [jitpack/jitpack.io#317]
Log https://jitpack.io/com/github/afollestad/material-camera/0.1.1/build.log

Even though it's successful I am still not able to import it. Its saying not found.

I have JitPack as a maven repository. There are other libs I'm using from it that are working fine.

**Comment by jitpack-io** [comment]
Hi @jd-alexander 

That is strange indeed. Tried in AS and got it downloaded.
Perhaps you could run `./gradlew build` from the terminal and paste the output? Curious if its looking inside JitPack for the library.

**Comment by jd-alexander** [comment]
It was a naming issue which has now been corrected.
