### ISSUE TITLE
Odd build issue that many users of my libraries have experienced

### ISSUE THREAD

**Issue by afollestad** [jitpack/jitpack.io#318]
Here's an example:

<img width="877" alt="screen shot 2015-12-02 at 1 47 09 pm" src="https://cloud.githubusercontent.com/assets/1820165/11542102/65d4d93e-98fb-11e5-87dd-8fb67d4813e9.png">

Even though I specified `@aar`, it tried to download the library as a JAR. 

Not sure if this is Android Studio related, or if anyone else has had this issue. It happens in multiple projects with this specific version of my library. (even after I clear the build from your website and try building it again)

**Comment by afollestad** [comment]
Also, this is the library: https://github.com/afollestad/material-dialogs

If you search through closed issues, many, many users have had issues with getting builds to work with your service.

**Comment by jitpack-io** [comment]
Hi
That is an odd issue indeed. Is it still happening? Would be 

Looking at our build logs it seems you've cleared the build multiple times and got it rebuild. Generally this isn't a problem but can affect your users that are installing at that time. It's best to keep the rebuilds to a minimum.

Another issue is that users often add jitpack under `buildscript` in their gradle files. Some users were asking about material-dialogs in our chat and that's how we resolved their issue. Perhaps its worth adding a warning in the readme?
```gradle
buildscript {
	repositories {
		// Do not add here
	}
}
repositories {
    maven { url "https://jitpack.io" }
}
```
It's ok if they add it in both places but the second one is the one that matters.

**Comment by jitpack-io** [comment]
Added material-dialogs 0.8.5.2 to our monitoring system to check every 5 minutes if its available. That way we'll get an alert if its unavailable for some reason and we'll also have a history.

Also updated our gradle snippet on the website to avoid confusion with buildscript:
```gradel
	allprojects {
		repositories {
			...
			maven { url "https://jitpack.io" }
		}
	}
```
Would recommend changing the snippet in your readme as well.

**Comment by afollestad** [comment]
That appears to have worked, thank you for your time!

**Comment by free5ty1e** [comment]
I still have endless issues due to this library being deployed to jitpack instead of the standard jcentral.  Just putting it out there.  

Why jitpack ever?  Ugh.

**Comment by afollestad** [comment]
@free5ty1e my library? All of mine have been on jCenter for quite a long time now.

**Comment by free5ty1e** [comment]
oh hayyyyyy - you're right!!  I can totally get rid of jitpack from my project now, thank you!  That was, by the way, the build issue we were facing.... "more than one library with material-dialogs" -- all gone now that jitpack is not listed in the project repos :)


Thank you!!

**Comment by roshaplus** [comment]
compile 'com.afollestad.material-dialogs:core:0.9.6.0'
