### ISSUE TITLE
Jdk specified in jitpack.yml is ignored

### ISSUE THREAD

**Issue by jcornaz** [jitpack/jitpack.io#3187]
If submitting a build issue please provide:
 1. Build log from https://jitpack.io: https://jitpack.io/com/github/jcornaz/miop/7073533e7bc10eb03de633cb51c04f5f43926d6d/build.log
 2. Does the project build on your machine? Yes

***

Build fails because doesn't find `javafx`. And the cause is that jitpack uses a JDK 11:
>------------------------------------------------------------
>Gradle 4.9
>------------------------------------------------------------
>
>Build time:   2018-07-16 08:14:03 UTC
>Revision:     efcf8c1cf533b03c70f394f270f46a174c738efc
>
>Kotlin DSL:   0.18.4
>Kotlin:       1.2.41
>Groovy:       2.4.12
>Ant:          Apache Ant(TM) version 1.9.11 compiled on March 23 2018
>JVM:          11 (Oracle Corporation 11+17-Debian-2)
>OS:           Linux 4.14.12-xxxx-std-ipv6-64 amd64

But it should use oracle java 10 as specified in my `jitpack.yml`:
```yml
jdk:
  - oraclejdk10
```

**Comment by jitpack-io** [comment]
Hi,

Rebuilt and it is now picking up JDK 10

**Comment by jcornaz** [comment]
thank you!
