### ISSUE TITLE
Support maven-toolchains-plugin

### ISSUE THREAD

**Issue by vlsi** [jitpack/jitpack.io#319]
Maven toolchains plugin allows using specific jdk version to build specific modules: https://maven.apache.org/guides/mini/guide-using-toolchains.html

From configuration point of view, it requires just a `~/.m2/toolchains.xml` file at jitpack side with paths to jdk versions.

**Comment by jitpack-io** [comment]
Added ~/.m2/toolchains.xml to build servers with locations of jdk 6, 7, 8.

**Comment by vlsi** [comment]
Would you please update https://jitpack.io/docs/BUILDING/#java-version to document "toolchains" support?

**Comment by jitpack-io** [comment]
Good point! Its worth documenting this. 
But before that wanted to confirm with you if its working.

**Comment by vlsi** [comment]
I'll create a repository for testing that
