### ISSUE TITLE
Build error with android library

### ISSUE THREAD

**Issue by florianmski** [jitpack/jitpack.io#32]
Hey!

Apparently there's an error while trying to build [my lib](https://github.com/florianmski/SpongeFramework) (works locally).
Here is my [latest attempt](https://jitpack.io/com/github/florianmski/SpongeFramework/c6f17638e5d32a0128586c85648f31531b889ac8/build.log), do you guys have any idea on what's wrong here?

Thanks!

**Comment by jitpack-io** [comment]
@florianmski Looks like the build succeeded. Let's see why the artifacts are not available...

**Comment by jitpack-io** [comment]
@florianmski There is no .pom file generated in local maven repository after doing `gradle install`. Not sure yet why...

**Comment by jitpack-io** [comment]
Ok, the problem is caused by this line in library/build.gradle:

     publishNonDefault true

Which created debug/release aar files but no .pom. Without that line it works

**Comment by florianmski** [comment]
Awesome, thanks a lot!
I used this [workaround](https://code.google.com/p/android/issues/detail?id=52962#c35) to be able to know in my lib if it was debug or release (to activate debug logging for instance), not sure how to proceed now :/
