### ISSUE TITLE
Python no longer available on jitpack build nodes

### ISSUE THREAD

**Issue by kageiit** [jitpack/jitpack.io#3200]
It seems python was suddenly removed from the build machines without any announcement. We rely on python to package pex binaries of https://github.com/facebook/buck

Python is available by default as a most basic package on most *nix platforms. Can you please bring it back? It prevents us from packaging our software and deploying it via jitpack

build url: https://jitpack.io/com/github/kageiit/buck/0fcb833e676f6653363a2426fe22c407f1ff057b/build.log

**Comment by jitpack-io** [comment]
Hi,

Indeed, will be bringing it back.
