### ISSUE TITLE
Jitpack can't build a new version of a project (with a different tag). It uses the build from the previous versions 

### ISSUE THREAD

**Issue by BrokenEarthDev** [jitpack/jitpack.io#3205]
When I update a project, which means creating a new version (tag), and adding the jar file to the releases, and after building the new version, i add the dependency for the new version. However, that "new" version is basically like older versions. I checked the jar file in the releases (in the new version) and that jar file is indeed a new version. But, after adding the dependencies, instead of seeing the new version update (classes/ets), I see it exactly like the previous version.

Build Log: https://pastebin.com/nkSUwkyL

Demonstration: 
  1) Create a simple project with like 2 classes
  2) Release it
  3) Build it in Jitpack
  4) Update that project (maybe add two more classes)
  5) Release the update with a different tag (version)
  6) Build it
  7) Add the dependency (the updated project's dependency) in a random project
  8) Is it the same as the "Simple project with 2 classes?"

Thank you for considering this issue

**Comment by jitpack-io** [comment]
Hi,

These releases point to the same git commit `786d0c3`:
https://github.com/BrokenEarthDev/EventBus/releases

and that's why JitPack builds the same jar file.

**Comment by BrokenEarthDev** [comment]
Thanks for the fast response!
