### ISSUE TITLE
oauth-consumer/master-03803833c9-1 build issue

### ISSUE THREAD

**Issue by jnorthrup** [jitpack/jitpack.io#322]
Log https://jitpack.io/com/github/jnorthrup/oauth-consumer/master-03803833c9-1/build.log

the reports check out, the builds happen, the jars are not being served.

**Comment by jitpack-io** [comment]
Hi,

Newer builds should be ok now. There was an issue with finding published jars when groupId isn't specified in the root pom. The issue is fixed now.
