### ISSUE TITLE
spoon-gradle-plugin/v1.0.3 build issue

### ISSUE THREAD

**Issue by ruchikalra** [jitpack/jitpack.io#323]
Log https://jitpack.io/com/github/jainsahab/spoon-gradle-plugin/v1.0.3/build.log

it's trying to upload the artifacts, but couldn't find 'nexusUsername' and 'nexusPassword'

**Comment by jitpack-io** [comment]
Its trying to upload since that's the default behaviour for the nexus plugin.

This behaviour can be customized with gradle properties and helper methods like here: 
https://github.com/chrisbanes/gradle-mvn-push/blob/master/gradle-mvn-push.gradle#L20-L40

Then adding them to build.gradle:
```gradle
nexus {
     sign = isReleaseBuild()
     repositoryUrl = getReleaseRepositoryUrl()
     snapshotRepositoryUrl = getSnapshotRepositoryUrl()
}
```
