### ISSUE TITLE
cordova-android/5.0.0 build issue

### ISSUE THREAD

**Issue by broglep-koubachi** [jitpack/jitpack.io#324]
Log https://jitpack.io/com/github/apache/cordova-android/5.0.0/build.log

Interestingly, an artefact should have been found, but in the end it tells that is was not found:

```
Total time: 22.738 secs
Looking for artifacts...
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
Found artifact: com.github.apache:framework:5.0.0
2015-12-07T13:58:31.580530758Z
Exit code: 0
No build artifacts found
```

**Comment by jitpack-io** [comment]
Hi,
Just tried this locally. The odd thing is that this project installs an 'aar' file in the local Maven repository but does not install a pom file. As a result it is not picked up by JitPack at the moment
