### ISSUE TITLE
License not included in POM.xml

### ISSUE THREAD

**Issue by mmoczkowski** [jitpack/jitpack.io#3240]
## Problem
Licenses being not generated by *Open Source Notices* plugin.

## How does the plugin identify license?
From the [official plugin documentation](https://developers.google.com/android/guides/opensource)

> Gradle plugin that collects license terms from included libraries as declared in their POM files

## How does Jitpack identify license?

Jitpack claims that license info is taken via Github API and that no additional steps are required.

[source 1](https://github.com/jitpack/jitpack.io/issues/169)
[source 2](https://github.com/jitpack/jitpack.io/issues/1744)

## Investigation data
For the purpose of this investigation, following data has been collected from various sources. Two representative libraries were selected for the sample: one which cooperates with the plugin, the other which does not. 

|Library|POM|License present in repo?|License returned by Github API?\*|License present in POM?|License generated by plugin?|
|-|-|-|-|-|-|
|Dialog_Framework_android|[link](https://jitpack.io/com/github/stanwood/Dialog_Framework_android/1.0.1/Dialog_Framework_android-1.0.1.pom)|YES|YES|YES|YES|
|Analytics_Framework_android|[link](https://jitpack.io/com/github/stanwood/Analytics_Framework_android/1.3.0/Analytics_Framework_android-1.3.0.pom)|YES|YES|**NO**|**NO**|

\*[Github API documentation](https://developer.github.com/v3/licenses/)

## Conclusion
Both libraries:
1. Have license file present in the repo
2. Have license file returned by Github API

However, `Analytics_Framework_android` does not have `<license>` tag present in the `POM.xml` file. This leads to believe, that the fault lays on Jitpack's side. For some reason, Jitpack fails to include the license, even though it is returned by Github API.

**Comment by jitpack-io** [comment]
Hi,

Thanks for the detailed report!
We can see licenses in the latest snapshot build:
https://jitpack.io/com/github/stanwood/Analytics_Framework_android/core/master-1.3.0-gdeb8f0b-1/core-master-1.3.0-gdeb8f0b-1.pom

but not in the 1.3.0 release. Needs more investigation
