### ISSUE TITLE
Loki/v1.8.9-SNAPSHOT build -> Missing JavaFX on JDK8?

### ISSUE THREAD

**Issue by RicardoMonteiroSimoes** [jitpack/jitpack.io#3242]
Log https://jitpack.io/com/github/HephaistosCorp/Loki/v1.8.9-SNAPSHOT/build.log

I've been having this issue yesterday too. Apparently it cant build the javafx package, which is an issue in JDK9, but shouldnt in JDK8.

**Comment by jitpack-io** [comment]
Hi,

Rebuilt
