### ISSUE TITLE
riot-api-java/v3.7.1 build issue (Bump source version)

### ISSUE THREAD

**Issue by iglosiggio** [jitpack/jitpack.io#326]
Log https://jitpack.io/com/github/rithms/riot-api-java/v3.7.1/build.log

[ERROR] /build/src/util/Convert.java:[25,62] lambda expressions are not supported in -source 1.5
[ERROR] (use -source 8 or higher to enable lambda expressions)

**Comment by jitpack-io** [comment]
Hi
There's a problem with the project setup. It compiles for java 1.5 
https://github.com/rithms/riot-api-java/blob/master/pom.xml#L17

but then uses java 1.8 lambdas in https://github.com/rithms/riot-api-java/blob/master/src/util/Convert.java

**Comment by iglosiggio** [comment]
Disculpas, pensé que era el repo del proyecto y publiqué sin mirar

[Bad english]
Sorry, i tought that this was the project repo and posted without checking
