### ISSUE TITLE
work failed on AS but well on console

### ISSUE THREAD

**Issue by zsigui** [jitpack/jitpack.io#327]
Hello！

I tried to use 'jitpack.io' in my project.
I have defined like below
```gradle
allprojects {
	repositories {
		jcenter()
		maven { url "https://jitpack.io"}
	}
}
```
and use like this
```gradle
dependencies {
	compile 'com.github.bauerca:drag-sort-listview:0.6.1@aar'
	compile 'com.github.lopspower:ListViewAnimations:2.0.2@aar'
}
```
but I got a error of 'Failed to resolve'.

And it works well when I build directly by using gradle console.

Can it work directly on AS ? How can I fix the AS failed problem ? 

Thanks for help!

**Comment by jitpack-io** [comment]
Hi
It looks like ListViewAnimations is a private Git repository. 
So you also need to add your authentication token https://jitpack.io/private#auth
```gradle
allprojects {
    repositories {
        jcenter()
        maven {
            url "https://jitpack.io" 
            credentials { username authToken }
        }
    }
}
```

**Comment by jitpack-io** [comment]
If there's still an issue, feel free to reopen.
