### ISSUE TITLE
[Feature Request] Deploying jar with javadoc 

### ISSUE THREAD

**Issue by BrokenEarthDev** [jitpack/jitpack.io#3271]
Hi.
Thank you for supporting the community that you created.

I'd like you to implement a feature where you can deploy a jar file with javadocs instead of using bytecode. 
So users can browse javadoc in (such as) intellij with a project deployed with jitpack.

Thanks for your consideration!

**Comment by BrokenEarthDev** [comment]
Thanks for the response!

**Comment by retrodaredevil** [comment]
Hi,
I got my javadoc working thanks to the maven-javadoc-plugin, and my javadocs are viewable using that URL. However, it does not show up in Android Studio (intelliJ) when I do the documentation.

I assume that this is something that can be fixed via a gradle configuration to link the documentation to the gradle project itself.

I was hoping this was something one of you have come across. If not, I'll keep searching.
Thanks
