### ISSUE TITLE
Does not recognise Gradle Kotlin DSL Files

### ISSUE THREAD

**Issue by Xerus2000** [jitpack/jitpack.io#3279]
```
ERROR:
No build file found. Looking for Gradle/Maven/Sbt/Lein build file in the root of the project
See the documentation at https://jitpack.io/docs/
Files: 
README.md
build.gradle.kts
license.txt
settings.gradle.kts
```

Jitpack should detect Gradle Kotlin DSL buildfiles and build the project with gradle accordingly.

**Comment by jitpack-io** [comment]
Hi,

Thanks for reporting!
Should be recognising build.gradle.kts now.

**Comment by sschuberth** [comment]
Nit: A [build](https://jitpack.io/com/github/heremaps/oss-review-toolkit/c5d3d3964e/build.log) that uses `build.gradle.kts` still shows

> grep: build.gradle: No such file or directory

which it not so nice.
