### ISSUE TITLE
File not found. Build ok

### ISSUE THREAD

**Issue by jasonwyatt** [jitpack/jitpack.io#3295]
Build log shows success, but trying to access any of the jars/poms is returning "File not found. Build ok"

I don't want to provide the build log here, as this is for a private repo, but I can share it via email if you need it.

**Comment by jasonwyatt** [comment]
Here's a link: https://jitpack.io/com/github/nosidewen/edison-clide/44e60df7e1/build.log

**Comment by ThiagoTGM** [comment]
Exact same issue here. Tried different commits on different branches on different repos (and even on a remote computer), same issue in all cases. Build logs have this odd ``/script/buildit.sh: line 48: [: missing `]'`` line around the beginning too.

**Comment by Sserra90** [comment]
Same thing here. 
File not found. Build ok when accessing jars.
Build is successful.

**Comment by jitpack-io** [comment]
Hi,

Looking into it

**Comment by Sserra90** [comment]
Hi, 

I don't know if you guys fixed something but it started working for me.
However i don't know if it's because i added the following task to build.gradle for every module. I was jus trying "crazy stuff" because this was driving my crazy is the last hours.

task androidSourcesJar(type: Jar) {
    classifier = 'sources'
    from android.sourceSets.main.java.srcDirs
}

**Comment by markrebhan** [comment]
Appears to be up again.

**Comment by Sserra90** [comment]
All good now. Thanks!

**Comment by JeremeLau** [comment]
same issue here.

**Comment by yjfnypeu** [comment]
I found the same problem yesterday. But today I found that the corresponding file already exists in the repository, and Android Studio still can't download the dependency. None of the previous versions found this issue。

build log: https://jitpack.io/com/github/yjfnypeu/EasyAndroid/da11ce0db4/build.log

**Comment by Shevchik** [comment]
Same issue. Build successful, but file is missing

**Comment by Zhuinden** [comment]
Now instead of `file not found, build ok` it just says `not found` 🤨

**Comment by Zhuinden** [comment]
This should not be closed. This is still an issue

**Comment by N7ghtm4r3** [comment]
Same problem, **File not found. Build ok**

- Log: https://jitpack.io/com/github/N7ghtm4r3/Pandoro/0.0.0.7/build.log
- Result: https://jitpack.io/com/github/N7ghtm4r3/Pandoro/0.0.0.7/Pandoro-0.0.0.7.jar

**Comment by N7ghtm4r3** [comment]
@jitpack-io

**Comment by culmat** [comment]
We have recurring observation of this issue too, see https://github.com/baloise/proxy/issues/11

Triggering a build via the commit hash has fixed it once.

**Comment by starry-shivam** [comment]
@jitpack-io Facing exact same issue, here's the [build log](https://jitpack.io/com/github/Pool-Of-Tears/KtScheduler/1.1.3/build.log).
As far as i can see it builds the project successfully and all of the required files are present, yet I'm getting `File not found. Build ok` when clicking on any of the packages in [documentation page](https://javadoc.jitpack.io/com/github/Pool-Of-Tears/KtScheduler/latest/javadoc/index.html).

**Comment by floriegl** [comment]
@jitpack-io I also have this issue a lot with [TeamNewPipe/NewPipeExtractor](https://jitpack.io/#TeamNewPipe/NewPipeExtractor). A lot of releases and builds are missing all or parts of their artifacts. They existed some weeks ago but randomly don't get served anymore.

**Comment by AhlaamK-tap** [comment]
@jitpack-io  Many of our builds have gone missing giving error 
All were working few weeks ago
https://github.com/Tap-Payments/goSellSDK-AndroidX
<img width="1458" alt="Screen Shot 2024-09-01 at 11 04 40" src="https://github.com/user-attachments/assets/7117b349-7e2c-4706-a9b3-04623e9fdc2e">

**Comment by floriegl** [comment]
I found the solution for my issue in https://github.com/TeamNewPipe/NewPipeExtractor/issues/1066#issuecomment-1622617046. Try using an all lowercase Group ID e.g., `com.github.tap-payments:goSellSDK-AndroidX` instead of `com.github.Tap-Payments:goSellSDK-AndroidX`

**Comment by ByteHamster** [comment]
This seems to have started again. We have several dependencies that suddenly just show "File not found. Build ok". Sometimes it also switches to just "Not found". See for example:

https://jitpack.io/com/github/mfietz/fyydlin/v0.5.0/
https://jitpack.io/com/github/ByteHamster/SearchPreference/2.7.1/
