### ISSUE TITLE
realm-searchview/68c871f9f7 build issue

### ISSUE THREAD

**Issue by thorbenprimke** [jitpack/jitpack.io#330]
Log https://jitpack.io/com/github/thorbenprimke/realm-searchview/68c871f9f7/build.log

```
Git error:
Checkout conflict with files: 
library/build.gradle
https://github.com/thorbenprimke/realm-searchview
```

I cannot figure out what's wrong with the `library/build.gradle` file / what would cause a conflict. 

It builds fine with gradle but I suppose here it fails on the git checkout step.

**Comment by jitpack-io** [comment]
Hi

Rebuilt that version and looking into the issue. Sorry about the interruption! Will post updates here...

**Comment by thorbenprimke** [comment]
Thanks @jitpack-io!

**Comment by thorbenprimke** [comment]
Hmm. I ran it for another release and it yields the same results. 

https://jitpack.io/com/github/thorbenprimke/realm-searchview/0.9.3/build.log

**Comment by jitpack-io** [comment]
Deployed fixes a few days back. We shouldn't see this kind of issue anymore

**Comment by thorbenprimke** [comment]
thanks @jitpack-io - looks like it is working fine for the realm-searchview repro now. I bumped the release version today and the new version built fine. Thanks for providing the jitpack service!
