### ISSUE TITLE
Sudden "No read access to repo"

### ISSUE THREAD

**Issue by ssardina** [jitpack/jitpack.io#3306]
Hi,

I have used Jitpack with various Bitbucket repo, and so far so good. Suddenly one of the repos now get the message

**No read access to repo**

systematically, every time. The repo is public and used to work until a few days ago: `org.bitbucket.ssardina-research/sarl-prolog-cap`

https://bitbucket.org/ssardina-research/sarl-prolog-cap

Other repos under the same account work perfectly, for example:

https://jitpack.io/#org.bitbucket.ssardina-research/sarl-agtcity-mw

A few days ago there were issues with Bitbucket Webhooks so every repo had that message, but now all is good on Bitbucket and I keep receiving that error only for that repo.

Thank you for any hint of what may be happening here!

**Comment by jitpack-io** [comment]
Hi,

Does it work for you now? The versions seem to be loading.

**Comment by ssardina** [comment]
Hi. Thanks. They do now. It has been shaky for a couple of days but it got into normal operation now. While sometime back Bitbucket had issues with the Webhooks, Jitpack got that way after that was resolved, days after. Not sure what happened. It is working now, thanks. If I find problems, I will re-open. THANKS.

**Comment by Hala-Nearmotion** [comment]
I'm facing the same issue now! Any help?
