### ISSUE TITLE
AppiumTestDistribution/1.0.1-SNAPSHOT build issue

### ISSUE THREAD

**Issue by saikrishna321** [jitpack/jitpack.io#331]
Log https://jitpack.io/com/github/saikrishna321/AppiumTestDistribution/1.0.1-SNAPSHOT/build.log

**Comment by jitpack-io** [comment]
Hi

It's just that there is no git tag '1.0.1-SNAPSHOT'. Should work with `master-SNAPSHOT`.
The error message isn't very informative, sorry.

**Comment by saikrishna321** [comment]
Yeah i got it working .. thanks .. closing the issue
