### ISSUE TITLE
Could not resolve com.github.dcendents:android-maven-gradle-plugin:2.0.

### ISSUE THREAD

**Issue by showang** [jitpack/jitpack.io#3313]
Log https://jitpack.io/com/github/showang/Recyct/0.0.2/build.log

* What went wrong:
A problem occurred configuring root project 'build'.
> Could not resolve all files for configuration ':classpath'.
   > Could not resolve com.github.dcendents:android-maven-gradle-plugin:2.0.
     Required by:
         project :
      > Could not resolve com.github.dcendents:android-maven-gradle-plugin:2.0.
         > Could not get resource 'https://jcenter.bintray.com/com/github/dcendents/android-maven-gradle-plugin/2.0/android-maven-gradle-plugin-2.0.pom'.
            > Could not GET 'https://jcenter.bintray.com/com/github/dcendents/android-maven-gradle-plugin/2.0/android-maven-gradle-plugin-2.0.pom'.
               > Read timed out

**Comment by jitpack-io** [comment]
Hi @showang 

Seems like that error is not caused by JitPack. Anyway, the build succeeded after a re-build.
