### ISSUE TITLE
Use a module of material-range-bar

### ISSUE THREAD

**Issue by bryant1410** [jitpack/jitpack.io#334]
How can I use the module `rangebar` of this repo https://github.com/xmartlabs/material-range-bar? I have tried the following and didn't work:

```groovy
compile 'com.github.xmartlabs.material-range-bar:rangebar:-SNAPSHOT'
```

**Comment by jitpack-io** [comment]
Hi

The dependency is correct but there was an issue with the projects build files https://jitpack.io/com/github/xmartlabs/material-range-bar/-08213e07b2-1/build.log

**Comment by bryant1410** [comment]
Ah, yeah, I reported it too, but I though this was a problem with dashes. Thanks

**Comment by bryant1410** [comment]
Now it's working the plain way, but not this way

**Comment by jitpack-io** [comment]
Oh ok, in this particular case there is only one one module so that's why the dependency is plain.

**Comment by bryant1410** [comment]
Ah, I though it would grab the sample too

**Comment by jitpack-io** [comment]
You could do that too. The sample just needs the android-maven plugin 
https://jitpack.io/docs/ANDROID/#gradle
