### ISSUE TITLE
Builds down

### ISSUE THREAD

**Issue by jahirfiquitiva** [jitpack/jitpack.io#3343]
Hi ... I am trying to get builds from my library `jahirfiquitiva/kext`, but this is all I get

![captura de pantalla 2018-10-02 a la s 14 27 32](https://user-images.githubusercontent.com/10360816/46372560-1d3d3000-c651-11e8-8fbe-9d04c9a501bf.png)

**Comment by jasonwyatt** [comment]
Still down for me too.

**Comment by jahirfiquitiva** [comment]
Another state of the site:

![captura de pantalla 2018-10-02 a la s 16 39 12](https://user-images.githubusercontent.com/10360816/46378601-c1c76e00-c661-11e8-87b2-f5c28132d00c.png)

**Comment by Parth-Brahmbhatt** [comment]
+1 , builds are still down. On the top level UI it shows build is in queued state and clicking on build link shows the error @jahirfiquitiva pasted after a long timeout.

**Comment by ninjapretzel** [comment]
+1
Their status shows the Queue as down for ~7hours as of posting this.
https://status.jitpack.io/
```
It was recorded (for the monitor Queue) on 2018-10-02 16:59:06 and the downtime lasted for 7 hrs, 7 mins.
```
Ongoing ^

Unfortunately it has been a pain all day trying to get an alternative build for dependencies.

**Comment by jahirfiquitiva** [comment]
Seems like it's back to normal! 😀
