### ISSUE TITLE
Maven properties not interpolated when in artifact ID

### ISSUE THREAD

**Issue by jdimeo** [jitpack/jitpack.io#3344]
We are injecting the scala major version into our artifact ID via a property to make it compliant with SBT in a more robust way than just hard-coding it:
```
<properties>
	<scala.major.version>2.11</scala.major.version>
</properties>

<artifactId>gsi-commons-scala_${scala.major.version}</artifactId>
```

When the project is built with Maven, all is good at this step:
```
[INFO] Installing /home/jitpack/build/scala/pom.xml to /home/jitpack/.m2/repository/com/glyphicsoftware/gsi-commons-scala_2.11/0.1.3-hotfix.1/gsi-commons-scala_2.11-0.1.3-hotfix.1.pom
```

But the final artifact and files don't have the scala major version interpolated and I can't figure out how to get SBT to download the dependency via Jitpack:
```
Build artifacts:
com.github.GlyphicSoftware.GSI-Commons:gsi-commons-scala_${scala.major.version}:gsi-parent-0.1.3-hotfix.1
```

Thank you! I know this is a weird/edge case, so no worries if the answer is - we have to hard code it in

**Comment by jitpack-io** [comment]
Hi,

Hard coding it is probably the simplest solution.
Our code that finds Build Artifacts simply reads <artifactId> from the .pom file. Adding property parsing and lookup doesn't seem like a quick fix.
Another option could be to run some custom commands after the build and replace properties in pom files.
