### ISSUE TITLE
Could not find method implementation() for arguments [directory 'libs'] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

### ISSUE THREAD

**Issue by kuhadiyadharmesh** [jitpack/jitpack.io#3345]
> Configure project :
Project evaluation failed including an error in afterEvaluate {}. Run with --stacktrace for details of the afterEvaluate {} error.

FAILURE: Build failed with an exception.

* Where:
Build file '/home/jitpack/build/build.gradle' line: 58

* What went wrong:
A problem occurred evaluating root project 'build'.
> Could not find method implementation() for arguments [directory 'libs'] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
See https://docs.gradle.org/4.8.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 3s
EXIT_CODE=1
2018-10-03T04:21:38.964498544Z
Exit code: 1
No build artifacts found

for more details check : https://jitpack.io/com/github/kuhadiyadharmesh/Testlibrary/0.0.0.1/build.log

**Comment by jitpack-io** [comment]
Hi,

Does it build on your local machine with the same command?
`./gradlew clean -Pgroup=com.github.kuhadiyadharmesh -Pversion=0.0.0.1 install`
