### ISSUE TITLE
Gradle settings.gradle.kts is ignored in Kotlin DSL build

### ISSUE THREAD

**Issue by matfax** [jitpack/jitpack.io#3356]
I guess this build fails because the `settings.gradle.kts` is not found or parsed. In this file, the missing repositories are declared inside the `pluginManagement`. The `settings.gradle.kts` is also not parsed, if Gradle finds a non-Kotlin-DSL `settings.gradle` file that overrides the kts one.

### Build log from https://jitpack.io

> FAILURE: Build failed with an exception.
> * Where:
Build file '/home/jitpack/build/library/build.gradle.kts' line: 1
> * What went wrong:
Plugin [id: 'org.jetbrains.kotlin.jvm'] was not found in any of the following sources:

Complete log: https://jitpack.io/com/github/matfax/kotlinpoet/1.0.0-rc.2/build.log

### Does the project build on your machine?
Yes, with a clean gradlew build, it succeeds, as well on Travis CI.

**Comment by matfax** [comment]
The Kotlin DSL support was just recently introduced as per #3279.

**Comment by matfax** [comment]
The same issue occurs in my next repo.
https://jitpack.io/com/github/matfax/klassindex/4.0.0-rc.0/build.log

**Comment by jitpack-io** [comment]
Hi,

Does `./gradlew install` work for you locally? There's a warning in the log

**Comment by matfax** [comment]
@jitpack-io Thank you for this hint. I was not aware that the maven plugin had to be declared explicitly in Kotlin DSL. Now it works.

**Comment by masterofdaemon** [comment]
I can't make this works:   repositories {
        google()
        mavenCentral()
        maven { url = uri("https://www.jitpack.io" ) }

    }

**Comment by HarshPatel-02** [comment]
madarchod
