### ISSUE TITLE
Add support for gitlab

### ISSUE THREAD

**Issue by dalewking** [jitpack/jitpack.io#337]
For personal reasons I will not use github or bitbucket for publishing my code and instead use gitlab. Can you support gitlab as well?

**Comment by jitpack-io** [comment]
Hi

Sure, we can add GitLab support. Are you using the cloud version of GitLab.com or hosting it yourself?

**Comment by dalewking** [comment]
The cloud version and am only concerned with public repos so I assume it should be fairly trivial.

I don't need it but there are many other repo hosts out there that people use that you should look at supporting: https://git.wiki.kernel.org/index.php/GitHosting

**Comment by jitpack-io** [comment]
Done
https://jitpack.io/#com.gitlab.jitpack-io/gradle-simple

**Comment by dalewking** [comment]
Thanks for the incredibly fast response.

**Comment by Mariovc** [comment]
And if Gitlab is hosted by myself with private repos? is it also supported?

**Comment by sapher** [comment]
@Mariovc +1

**Comment by smiklosovic** [comment]
what about private repository with self-hosted gitlab?

**Comment by Matthew-Jannace** [comment]
@smiklosovic +1

**Comment by pasku** [comment]
@smiklosovic +1

**Comment by jitpack-io** [comment]
If you host GitLab yourself then you'll need to set up a custom domain
https://jitpack.io/docs/#custom-domain-name

Then use that custom domain as your groupId.

**Comment by pasku** [comment]
I'm using a private repository with self-hosted GitLab, what's the IP range for incoming requests? Want to whitelist it.

**Comment by AllanWang** [comment]
@jitpack-io Are there examples from users who have set this up with their own domain?

We have this library pack under our university:

https://gitlab.science.mcgill.ca/TEPID/tepid-commons

and we've set up the following DNS:

```
git.TEPID.gitlab.science.mcgill.ca    600   IN   TXT   "https://gitlab.science.mcgill.ca/TEPID"
```

Is this the proper DNS? We may still be waiting for it to propagate 

[Jitpack for reference](https://jitpack.io/#ca.mcgill.science.gitlab.TEPID/tepid-commons)

We've already tried it without `TEPID` but that didn't work

**Comment by dalewking** [comment]
Here is a library of mine that used gitlab and jitpack:

https://gitlab.com/NobleworksSoftware/NobleInjection

But that is in the cloud version of gitlab and it looks like you are talking about a hosted version of gitlab.

**Comment by AllanWang** [comment]
@dalewking Yes, I am referring to our own hosted version.

**Comment by timfei** [comment]
@pasku Hello, Did you set up successful on private repo with self-hosted GitLab? 
I did some try, but only public repo work fine, the private repo always show No read access to repo on https://jitpack.io/private#cn.gokuai/MyPrivate

**Comment by pasku** [comment]
@timfei Contact support and they will help you diligently.

**Comment by ashishgupta2510** [comment]
@timfei have your problem resolved..if yes then please provide me the steps it will helpful for me
thanks in adavance

**Comment by timfei** [comment]
@ashishgupta2510 Sorry, I did not solve this problem with using self-host gitlab , in the end I choose use gitlab.com and it works fine.
Now JitPack has a better support on self-host gitlab, you can do more try .
https://jitpack.io/docs/PRIVATE/#self-hosted-git

**Comment by micheljung** [comment]
GitLab doesn't seem to work anymore: https://jitpack.io/#com.gitlab.jitpack-io/gradle-simple

I expect some result but nothing happens?

**Comment by axel1200** [comment]
Same here as for micheljung

**Comment by axel1200** [comment]
Lots of warnings in the console when i hit look up
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://github.com/login/oauth/authorize?client_id=0a9d3985d363409b960f&redirect_uri=https%3A%2F%2Fjitpack.io%2Fcallback%3Fclient_name%3Dgithub2&scope=repo%2Cuser%3Aemail%2Cread%3Aorg%2Cadmin%3Arepo_hook. (Reason: CORS request did not succeed).[Learn More]
```

**Comment by axel1200** [comment]
maybe we should open a new issue

**Comment by micheljung** [comment]
https://github.com/jitpack/jitpack.io/issues/3793

**Comment by jitpack-io** [comment]
Hi all,

Occasionally JitPack is getting rate-limited by GitLab.com and our requests fail. This is usually temporary and resolves by itself within a few hours. We have raised the issue with them a few times and are looking for a way to work around this.
