### ISSUE TITLE
fix generated gradle dependency to use compile and double quotes

### ISSUE THREAD

**Issue by jillesvangurp** [jitpack/jitpack.io#3370]
Minor issue but it would be nice to have double quotes on the generated gradle dependency. This allows you to inject e.g. versions and other variables. Also it is kind of weird that it defaults to implementation instead of compile. I think mostly compile or testCompile should be what people use for dependencies in gradle. So compile is a better default. I notice that for the maven dependency you are not setting a custom scope of runtime, which would be roughly the equivalent of using implementation instead of compile in gradle.

So please change 

`implementation 'com.github.User:Repo:Tag'`

to

`compile "com.github.User:Repo:Tag"`

**Comment by jitpack-io** [comment]
Hi @jillesvangurp 

Thank you for bringing this up! 
We've always had `compile` in the past but now Gradle docs recommend `api`/`implementation`: https://docs.gradle.org/current/userguide/java_library_plugin.html#sec:java_library_separation

**Comment by jitpack-io** [comment]
Sorry for the late reply, still haven't decided on this. At the moment we're seeing this warning when using compile with Gradle 4.6: 
```
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
```

**Comment by jillesvangurp** [comment]
Gradle 4.10.2 is current. I see no such warnings for compile dependencies on any of my projects.  So this is not deprecated in Gradle as far as I know.

It looks like this is android specific (the link is not pointing to any gradle specific issue or documentation). It states: "The table also compares these configurations to those that were deprecated as of Android Gradle Plugin 3.0.0. ". So, this has to do with how that plugin behaves. I don't do android projects so I don't use this plugin. 

Removing this in Gradle would break an enormous amount of build files on github; so I can't imagine that gradle is planning to do that and willingly break just about any gradle project out there for no good reason. Both maven central and bintray will provide compile dependencies.

I can tell you that the behavior of implementation is different from compile though with plugins I use. Basically with the `com.github.jengelman.gradle.plugins:shadowz` plugin, implementation dependencies are skipped and not included in the jar. In my case that is the opposite of what I want. It seems that gradle semantics for these things are a bit all over the place. Maven had fewer and better defined scopes.
