### ISSUE TITLE
the usual

### ISSUE THREAD

**Issue by jnorthrup** [jitpack/jitpack.io#338]
jim@DREAMCATCHER ~
$ curl -vvv https://jitpack.io/com/github/0xCopy/RelaxFactory/rxf-core/1.0/rxf-
core-1.0.jar
*   Trying 178.62.102.56...
* Connected to jitpack.io (178.62.102.56) port 443 (#0)
* successfully set certificate verify locations:
*   CAfile: C:\Program Files (x86)\Git\bin\curl-ca-bundle.crt
  CApath: none
* TLSv1.0, TLS handshake, Client hello (1):
* TLSv1.0, TLS handshake, Server hello (2):
* TLSv1.0, TLS handshake, CERT (11):
* TLSv1.0, TLS handshake, Server key exchange (12):
* TLSv1.0, TLS handshake, Server finished (14):
* TLSv1.0, TLS handshake, Client key exchange (16):
* TLSv1.0, TLS change cipher, Client hello (1):
* TLSv1.0, TLS handshake, Finished (20):
* TLSv1.0, TLS change cipher, Client hello (1):
* TLSv1.0, TLS handshake, Finished (20):
* SSL connection using TLSv1.0 / DHE-RSA-AES128-SHA
* Server certificate:
*        subject: OU=Domain Control Validated; OU=Gandi Standard SSL; CN=jitpack.io
*        start date: 2015-01-09 00:00:00 GMT
*        expire date: 2016-01-09 23:59:59 GMT
*        subjectAltName: jitpack.io matched
*        issuer: C=FR; ST=Paris; L=Paris; O=Gandi; CN=Gandi Standard SSL CA 2
*        SSL certificate verify ok.
> GET /com/github/0xCopy/RelaxFactory/rxf-core/1.0/rxf-core-1.0.jar HTTP/1.1
> User-Agent: curl/7.41.0
> Host: jitpack.io
> Accept: */*
>
< HTTP/1.1 404 Not found
< Content-Length: 0
<
* Connection #0 to host jitpack.io left intact

**Comment by jitpack-io** [comment]
Had to rebuild. How does it look now?

**Comment by jnorthrup** [comment]
i have propogated manual releases to n=3 inheritance of RelaxFactory into
the kouchdb project at that time.  as luck would have it, i am rebooting
the kouchdb project and wont rely on any of this for a while longer.   im
really not happy with a flurry of pom version updates to break the pattern
of using -SNAPSHOT .
