### ISSUE TITLE
Building maven: 403 forbidden from maven central

### ISSUE THREAD

**Issue by OrigamiDream** [jitpack/jitpack.io#3388]
Log https://jitpack.io/com/github/OrigamiDream/juikit/v1.1-SNAPSHOT/build.log

Everything works fine in my local.
How can I solve this problem?

**Comment by jdimeo** [comment]
A lot of builds are failing with this today, including my private ones and other public ones if you look at other issues that have been filed recently. This is a blocking issue- thanks for any help you can offer!

**Comment by gdejohn** [comment]
@jitpack-io It looks like JitPack may be getting rate limited by Maven Central. Something similar happened with Travis CI a month ago, many issues similar to this:

https://github.com/travis-ci/travis-ci/issues/10053

It was resolved by white listing their build servers, but Sonatype suggested running a repository manager to cache Maven Central artifacts.

https://twitter.com/sonatypeDev/status/1036734093529047040
https://github.com/travis-ci/travis-ci/issues/1441

**Comment by jdimeo** [comment]
@gdejohn I think you're exactly right. But forgive my ignorance- how is it possible that it is just now becoming an issue? Wouldn't this happen daily given the number of builds they do? What's really funny is that I just signed up for this service in the last week or so- I apologize to everyone if my builds were the last straw that broke the camel's back! 😄

**Comment by gdejohn** [comment]
@jdimeo Yeah, I assume that's exactly what the situation is: the straw that broke the camel's back. It was fine until it wasn't.

**Comment by jitpack-io** [comment]
Hi,

We're looking into it. You're probably right that we've exceeded some quota on Maven Central.
Fortunately just one server is getting Forbidden responses and others are fine.
You can try rebuilding the builds that failed.

**Comment by jdimeo** [comment]
@jitpack-io Thank you! Glad to know that this service is doing well enough to have this problem :-) However, it is a big problem. I tried probably about a dozen builds over a four hour period and couldn't get a successful build, which jeopardized a time-critical release.  Not complaining, just communicating that it wasn't a one-time fluke. Perhaps you can ask Sonatype to whitelist all servers while a long term solution is worked on?

**Comment by elifarley** [comment]
@jitpack-io @jdimeo Maybe Jitpack can use JCenter as an additional source:
https://bintray.com/bintray/jcenter

**Comment by jitpack-io** [comment]
Hi all,

Maven Central have whitelisted our servers so you no longer should encounter this issue

**Comment by CalamarBicefalo** [comment]
Well it still doesn't work for me...

> Could not resolve all artifacts for configuration ':classpath'.
   > Could not resolve org.jetbrains.kotlin:kotlin-gradle-plugin:1.2.71.
     Required by:
         project :
      > Could not resolve org.jetbrains.kotlin:kotlin-gradle-plugin:1.2.71.
         > Could not get resource 'https://repo.maven.apache.org/maven2/org/jetbrains/kotlin/kotlin-gradle-plugin/1.2.71/kotlin-gradle-plugin-1.2.71.pom'.
            > Could not GET 'https://repo.maven.apache.org/maven2/org/jetbrains/kotlin/kotlin-gradle-plugin/1.2.71/kotlin-gradle-plugin-1.2.71.pom'. Received status code 403 from server: Forbidden

**Comment by CalamarBicefalo** [comment]
Well it still doesn't work for me @jitpack-io 

> Could not resolve all artifacts for configuration ':classpath'.
   > Could not resolve org.jetbrains.kotlin:kotlin-gradle-plugin:1.2.71.
     Required by:
         project :
      > Could not resolve org.jetbrains.kotlin:kotlin-gradle-plugin:1.2.71.
         > Could not get resource 'https://repo.maven.apache.org/maven2/org/jetbrains/kotlin/kotlin-gradle-plugin/1.2.71/kotlin-gradle-plugin-1.2.71.pom'.
            > Could not GET 'https://repo.maven.apache.org/maven2/org/jetbrains/kotlin/kotlin-gradle-plugin/1.2.71/kotlin-gradle-plugin-1.2.71.pom'. Received status code 403 from server: Forbidden
