### ISSUE TITLE
ViewPagerIndicator/2.4.1 build issue

### ISSUE THREAD

**Issue by aoemerson** [jitpack/jitpack.io#340]
Status is showing an issue but the log appears to be empty...at least nothing is loading for me for the URL below.

Log https://jitpack.io/com/github/JakeWharton/ViewPagerIndicator/2.4.1/build.log

**Comment by jitpack-io** [comment]
Hi

The artifacts are there though so now it should work as a dependency
https://jitpack.io/com/github/JakeWharton/ViewPagerIndicator/2.4.1/
Could you retry?
