### ISSUE TITLE
Version badges don't seem to be working

### ISSUE THREAD

**Issue by afollestad** [jitpack/jitpack.io#342]
This started happening a day or two ago, for many libraries. For an example:

[ ![Release](https://img.shields.io/github/release/afollestad/material-dialogs.svg?label=jitpack) ](https://jitpack.io/#afollestad/material-dialogs)

Literal text: 

```Markdown
[ ![Release](https://img.shields.io/github/release/afollestad/material-dialogs.svg?label=jitpack) ](https://jitpack.io/#afollestad/material-dialogs)
```

**Comment by jitpack-io** [comment]
Hi

There's an ongoing discussion [here](http://git.io/v07gy). 
It appears Shields.io have hit GH rate limits and are waiting for them to be increased. We might have to start hosting our own badges if its not resolved...

**Comment by afollestad** [comment]
Oh, that makes sense, thank you

**Comment by jitpack-io** [comment]
Hi

JitPack now provides its own badges https://github.com/jitpack/jitpack.io/blob/master/README.md#badges

**Comment by afollestad** [comment]
Great, thank you! 😀
