### ISSUE TITLE
Missing module from multi-module project (StorIO)

### ISSUE THREAD

**Issue by fstephany** [jitpack/jitpack.io#3436]
When building StorIO ( https://github.com/pushtorefresh/storio ) with Jitpack it seems to miss a few modules. 

For example, building commit f6c7d22  results in the log:
https://jitpack.io/com/github/pushtorefresh/storio/f6c7d22/build.log

We can see that the built artifacts are

```
Build artifacts:
com.github.pushtorefresh.storio:storio-content-resolver-annotations-processor:f6c7d22
com.github.pushtorefresh.storio:storio-common-annotations-processor:f6c7d22
com.github.pushtorefresh.storio:storio-sqlite-annotations:f6c7d22
com.github.pushtorefresh.storio:storio-content-resolver-annotations:f6c7d22
com.github.pushtorefresh.storio:storio-sqlite-annotations-processor:f6c7d22
```

All the other modules (e.g., storio-sqlite, storio-common) are not built.  
Any hint of what I am missing?

**Comment by jitpack-io** [comment]
Hi,

JitPack should pick up all modules that are published by the build.
One way to debug is to run this locally:
./gradlew clean -Pgroup=com.github.pushtorefresh -Pversion=f6c7d22 -xtest -xlint install
and see if those modules get installed in ~/.m2/
