### ISSUE TITLE
kotterknife/36ae6d5ecb build issue

### ISSUE THREAD

**Issue by dalewking** [jitpack/jitpack.io#345]
Log https://jitpack.io/com/github/JakeWharton/kotterknife/36ae6d5ecb/build.log

**Comment by jitpack-io** [comment]
Hi

It's because the buildfile tries to upload to sonatype:
https://github.com/JakeWharton/kotterknife/blob/master/gradle/gradle-mvn-push.gradle#L42-L45

would work if repository url is replaced by properties:
https://github.com/chrisbanes/gradle-mvn-push/blob/master/gradle-mvn-push.gradle#L52-L57

**Comment by jitpack-io** [comment]
@dalewking It builds now
Thanks!
