### ISSUE TITLE
Parse-SDK-Android/1.11.0 build issue

### ISSUE THREAD

**Issue by faustinoloeza** [jitpack/jitpack.io#347]
Log https://jitpack.io/com/github/ParsePlatform/Parse-SDK-Android/1.11.0/build.log

**Comment by jitpack-io** [comment]
Hi

The project is configured to upload to sonatype and that's why it fails. It should instead be configured to install in it's local maven repository $HOME/.m2/repository. Easy to do with properties:
https://github.com/chrisbanes/gradle-mvn-push/blob/master/gradle-mvn-push.gradle#L52-L57

**Comment by jitpack-io** [comment]
Fixed
