### ISSUE TITLE
How do you produce a jar that you can browse its javadoc from your IDE

### ISSUE THREAD

**Issue by Poiding** [jitpack/jitpack.io#3480]
Please write explaining steps on how you do that. I looked a lot and found no valuable information. Please explain how, and on a non-android project. Using gradle

**Comment by jitpack-io** [comment]
Hi,

Your gradle or maven build should produce -sources.jar and -javadoc.jar artifacts. JitPack will then publish those artifacts and IDE will be able to download them.
Here's one example https://github.com/jitpack/gradle-simple/blob/master/build.gradle
