### ISSUE TITLE
android-gradle builds with old buildtools (classpath "com.android.tools.build:gradle:3.0.0" and older) fail

### ISSUE THREAD

**Issue by k3b** [jitpack/jitpack.io#3484]
This error even happens, if the current gralde project does not need ndk.

Error message in build.log (i.e. [build.log](https://jitpack.io/com/github/k3b/SimplePanorama/0.3.2/build.log) using gradle-2.14.1 and com.android.tools.build:gradle:3.0.1}

> No toolchains found in the NDK toolchains folder for ABI with prefix: mips64el-linux-android

Cause: Google has removed ABI cpu support and old buildtools fail because they check for "ABI" :-(

See https://stackoverflow.com/questions/35128229/error-no-toolchains-found-in-the-ndk-toolchains-folder-for-abi-with-prefix-llv for details.

Is it possible that you add the missing directory into the ndk installation?

Else every jitpack-android-lib developer has to upgrade buildtools and gradleversion to make jitpack work with new lib versions (as i had to do here [build.log](https://jitpack.io/com/github/k3b/SimplePanorama/0.3.3/build.log)  using gradle-4.4 and com.android.tools.build:gradle:3.1.0)

**Comment by jitpack-io** [comment]
Hi,

Added the workaround.
Thank you for the suggestion!
