### ISSUE TITLE
How to get working with moditect?

### ISSUE THREAD

**Issue by lukehutch** [jitpack/jitpack.io#3487]
Hi, I'm trying to get JitPack working with Moditect -- https://github.com/moditect/moditect

There are three problems:

(1) Moditect is added as a plugin, not as a Maven dependency: 

https://github.com/classgraph/classgraph/blob/master/pom.xml#L89

(2) I don't want the deployable Maven package of my project (ClassGraph) to depend upon Moditect, I only want to add the dependency at build-time.

(3) If I put in the GitHub URL for the moditect project, Jitpack website only shows the Maven rule for depending upon the main Moditect project, but I want to depend upon the Maven plugin subproject that is pushed to Maven Central as `org.moditect/moditect-maven-plugin`.

**Comment by jitpack-io** [comment]
Hi,

If you build the whole project on JitPack then you can add a dependency on a single module:
```xml
	    <groupId>com.github.moditect.moditect</groupId>
	    <artifactId>maven-plugin</artifactId>
	    <version>$VERSION</version>
```
JitPack will show rules for individual modules once there's a successful build.
