### ISSUE TITLE
Pom downloading taking forever

### ISSUE THREAD

**Issue by chenjianjx** [jitpack/jitpack.io#349]
````
Downloading: https://jitpack.io/com/github/chenjianjx/swagger2html/1.0.4/swagger2html-1.0.4.pom
````
It takes forever.   

I've already created such a [release of my project](https://github.com/chenjianjx/swagger2html/releases/tag/1.0.4) . Why doesn't it work?  Was it some server clitch on your site?

**Comment by jitpack-io** [comment]
Hi

It should be working now. The build got queued up so it appeared to be taking for ever. Sorry about the delay.

**Comment by chenjianjx** [comment]
Thanks.
