### ISSUE TITLE
Server can't build a library which uses one or more libraries but not yet built

### ISSUE THREAD

**Issue by haibison** [jitpack/jitpack.io#350]
For example I have an Android library A which uses library B (via JitPack). Both A & B are not built yet on JitPack server (they are mine so I know that, because I've just released new versions of them).

According to [FAQ], a build can take up to 15 minutes.

Now I have an app C which uses A. When building C with `gradle clean assembleRelease`, I waited for about 20 minutes, and had to Ctrl-C to stop my local build. Note that both libraries A & B are pretty small. It takes like 15-25 seconds to build each of them, on my machine dual-core.

Then I moved to root folder of A, built it with `gradle clean assembleRelease`. This triggered the server to build B, successfully.

Finally I tried to build app C again. Since B was built successfully on JitPack server, it triggerd the server to build A, successfully. And I could ~~built~~ build C then.

---

Would you please check to see if that's a bug?

Thank you,

[FAQ]: https://jitpack.io/docs/FAQ/

**Comment by jitpack-io** [comment]
Hi,

Build jobs got queued up today and that's probably why you experienced a delay. It should be resolved now but if you still see an issue, we'll have another look. Sorry about the interruption.

**Comment by haibison** [comment]
@jitpack-io 

Thank you. I remember that it worked great before. Perhaps the server was tired  `:-D`

Happy holiday  `:-)`
