### ISSUE TITLE
publishing a submodule via com.github.USER.REPO:MODULE:VERSION does not work

### ISSUE THREAD

**Issue by k3b** [jitpack/jitpack.io#3503]
I want to reference the gradle j2se sub-module "libK3bZip" of my android gradle project https://github.com/k3b/ToGoZip/
using format com.github.USER.REPO:MODULE:VERSION via

    compile 'com.github.k3b:ToGoZip:libK3bZip:7e561e5222db9f6743412ce53e75f56f0fab75b1' 
	
When accessing https://jitpack.io/com/github/k3b/ToGoZip/libK3bZip/7e561e5222db9f6743412ce53e75f56f0fab75b1/build.log i get a not found error

Jitpack has generated an empty directory https://jitpack.io/com/github/k3b/ToGoZip/libK3bZip/ with no content.

calling https://jitpack.io/com/github/k3b/ToGoZip/7e561e5222db9f6743412ce53e75f56f0fab75b1/build.log (without submodule libK3bZip) works as expected: it generates the apk with pom in directory https://jitpack.io/com/github/k3b/ToGoZip/7e561e5222db9f6743412ce53e75f56f0fab75b1/.

---

according to https://jitpack.io/docs/#features

> ...
> Other Features

> ...
> For a multi module project, the artifacts are published under com.github.USER.REPO:MODULE:VERSION, 
> where MODULE is the artifact id of the module (not necessarily the same as the directory it lives in)

I have an android gradle project  https://github.com/k3b/ToGoZip/ that contains subprojects 

* app (android app)  	
* libK3bZip (j2se lib used by app)

My goal: use com.github.k3b.ToGoZip:libK3bZip:VERSION in an other project.

How do i need to change my subproject to make "com.github.USER.REPO:MODULE:VERSION" work?

---

I also looked into the jipack github example https://github.com/jitpack/gradle-multiple-jars.

The corresponding https://jitpack.io/com/github/jitpack/gradle-multiple-jars/

also contain two empty subdirectories

	build-api/
	build-impl/

**Comment by jitpack-io** [comment]
Hi,

The log is published at the root of the project (without modules in path): https://jitpack.io/com/github/k3b/ToGoZip/7e561e5222db9f6743412ce53e75f56f0fab75b1/build.log

You might need to add android-maven plugin to your library modules https://jitpack.io/docs/ANDROID/#gradle

**Comment by k3b** [comment]
now it is working for me. thanks a lot

what confused me was that 

* https://jitpack.io/com/github/k3b/ToGoZip/libK3bZip/ 

was shown as empty so i did not assume that there is a dir 

* https://jitpack.io/com/github/k3b/ToGoZip/libK3bZip/L2.0.15/

with the requested data
