### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by oleersoy** [jitpack/jitpack.io#351]
Hi,

I'm attempting to use [firefly-math-precision](https://github.com/firefly-math/firefly-math-precision) as a jipack enabled dependency.  I have it declared in a different project like this:

``` xml
          <dependency>
               <groupId>com.github.firefly-math</groupId>
               <artifactId>firefly-math-precision</artifactId>
               <version>anyBranch-SNAPSHOT</version>
          </dependency>

```
The message I get when trying to compile looks like this:

``` console
[ERROR] Failed to execute goal on project firefly-math-levenberg-marquardt: Could not resolve dependencies for project com.fireflysemantics.math:firefly-math-levenberg-marquardt:jar:0.0.0: Failure to find com.github.firefly-math:firefly-math-precision:jar:anyBranch-SNAPSHOT in https://jitpack.io was cached in the local repository, resolution will not be reattempted until the update interval of jitpack.io has elapsed or updates are forced -> [Help 1]
```

Thoughts?

Ole

**Comment by jitpack-io** [comment]
Hi

You can put `<version>master-SNAPSHOT</version>` or a different branch.

**Comment by oleersoy** [comment]
OK - So the branch name must match the master-SNAPSHOT tag?  If I just leave the version as master will that work?

**Comment by jitpack-io** [comment]
Yes, it can be master-SNAPSHOT, someOtherBranch-SNAPSHOT or simply `-SNAPSHOT`. https://jitpack.io/docs/#snapshots

Just master is not supported so it won't work. One of the reasons is that it's a changing artifact and -SNAPSHOT tells maven that it needs to check for new versions.
