### ISSUE TITLE
WebRTC/webRTCTrial build issue

### ISSUE THREAD

**Issue by yoshi23** [jitpack/jitpack.io#352]
Log https://jitpack.io/com/github/yoshi23/WebRTC/webRTCTrial/build.log

**Comment by jitpack-io** [comment]
Hi

What build system is this project using? We currently support Gradle/Maven/Sbt/Leiningen

**Comment by yoshi23** [comment]
Hi,

I am using Gradle. I am tring to import a compiled WebRTC repository. 

Thanks for your response!

**Comment by yoshi23** [comment]
http://stackoverflow.com/questions/26250790/what-does-aar-means-in-gradle-compile-task

This might be a solution to my problem. I am sorry, I am very new to the field, but I have dived into deep water.
