### ISSUE TITLE
Add support for Kobalt

### ISSUE THREAD

**Issue by cbeust** [jitpack/jitpack.io#353]
Kobalt: http://beust.com/kobalt

What needs to be done:
1. Detect the existence of `kobalt/src/Build.kt`
2. Run `./kobaltw install`
3. Grab the artifacts from `kobaltBuild/libs` and put those in your maven repo

Thanks!

**Comment by jitpack-io** [comment]
Hi

Is there a way for to install the libs in the local maven repo as well?

**Comment by cbeust** [comment]
@jitpack-io By "local maven repo", do you mean the repo cache (Maven puts it in `~/.m2/repository`, Kobalt in `~/.kobalt/repository`) or a local running instance such as artifactory?

**Comment by jitpack-io** [comment]
Just the `~/.m2/repository` but `~/.kobalt/repository` would do as well.

**Comment by cbeust** [comment]
No, `install` doesn't do that. Nor should it: these cache directories are only touched by the build tool (whether it be gradle or kobalt). If Kobalt encounters this dependency in a build file, then it will download that artifact in the cache directory.

Do you need the artifacts to be in these cache directories?

**Comment by jitpack-io** [comment]
~/.m2/repository would be the simplest since that's how JitPack finds artifacts from other build tools.

**Comment by sanity** [comment]
Just wanted to check in on this

cc: @cbeust @jitpack-io

**Comment by jitpack-io** [comment]
Hi @sanity 

There's really just one small issue. JitPack was designed to pick up artifacts from ~/.m2/repository so making it pick up `kobaltBuild/libs` is an internal change. Not saying it can't be done but there are priorities.
If anyone has a script/lib that can publish `kobaltBuild/libs` to ~/.m2 then that'd be the quickest way to support kobalt.

**Comment by pabl0rg** [comment]
this is now configurable in Kobalt (http://beust.com/kobalt/documentation/index.html)  search for ~/kobalt/settings.xml

**Comment by pabl0rg** [comment]
I think the maven repository problem can be fixed by including @ethauvin plugin https://github.com/ethauvin/kobalt-maven-local

**Comment by pabl0rg** [comment]
I managed to publish [this project](https://github.com/pabl0rg/kobalt-mixed-example) with jitpack and use it from another project with full success.  In summary, I used @ethauvin's plugin and added this `jitpack.yml` 
```
install:
   - echo "Running kobalt publishToMavenLocal"
   - rm -rf .kobalt/build
   - ./kobaltw --log 2 clean publishToMavenLocal
```
[this is the resulting build log](https://jitpack.io/com/github/pabl0rg/kobalt-mixed-example/f7434a4cbc83b9b39fbadde10ef5ce19f5095292/build.log)

**Comment by cbeust** [comment]
Same, I haven't had any issues jitpack the few times I tried. Please reopen if you have an example that doesn't work.
