### ISSUE TITLE
Multi-module project with flavors: module does not include other modules it depends on

### ISSUE THREAD

**Issue by connected-kli** [jitpack/jitpack.io#3544]
Hi,

We have a multi-module project in which some modules depend on other modules. These modules also have flavors.

We followed the example in https://github.com/mirceanis/multi-flavor-lib-demo in order to get JitPack to properly publish the project's artifacts, and things are mostly working fine.

However, we found the following issue. Let's say `:moduleA` depends on `:moduleB` (via `api project(:moduleB)`), and both modules have flavors. The POM for `:moduleA` does not include `:moduleB`, which means consumers will have to know to add `:moduleB` as a dependency in their project. This makes consuming our library cumbersome.

This issue does not occur if we do not have flavors in both modules (and thus we can revert the change we learned from `multi-flavor-lib-demo`).

Is there a way to get `:moduleA`'s POM to include `:moduleB`'s artifacts?

Thanks in advance.

**Comment by Honwhy** [comment]
one more specific example here,
in modular-project https://github.com/Honwhy/ftpcp2
moduleA: ftpcp, depends on commons-net and commons-pool,
moduleB: ftpcp-spring-boot-starter depends on moduleA,
all JUnit Test works fine in the modular-project,

as another example project https://github.com/Honwhy/ftpcp2-starter-test depends on 
moduleB, configuration following,
```
<repositories>
        <repository>
            <id>jitpack.io</id>
            <url>https://jitpack.io</url>
        </repository>
    </repositories>

<dependency>
            <groupId>com.github.honwhy.ftpcp2</groupId>
            <artifactId>ftpcp-spring-boot-starter</artifactId>
            <version>0.0.1</version>
        </dependency>
```
but miss commons-net and commons-pool
