### ISSUE TITLE
tess-two/-5.3.0-g864334c-18 build issue

### ISSUE THREAD

**Issue by rmtheis** [jitpack/jitpack.io#355]
Does Jitpack support manually calling out to `ndk-build` from my build script? If not, would you consider adding support for this?

The gradle-experimental plugin doesn't yet provide enough flexibility to run this library's NDK build, so this library is using the gradle-stable plugin.

Log https://jitpack.io/com/github/rmtheis/tess-two/-5.3.0-g864334c-18/build.log

**Comment by jitpack-io** [comment]
Hi

Manually calling ndk-build will work but it's located in $ANDROID_HOME/ndk on the builds servers. The `${ndk.dir}` gradle property is configured to point to that directory so you could use it in:
https://github.com/rmtheis/tess-two/blob/master/tess-two/build.gradle#L38

Before the build we write this property to local.properties file.

ndk-build command is also available on the $PATH so running it without `./` should work too.

**Comment by rmtheis** [comment]
Thanks for the reply. I've changed the library's build.gradle files and I'm no longer seeing that same problem.

Now I'm getting a timeout on the build, apparently. I don't see a log file generated, and I see the following message in Android Studio:

      > Could not resolve com.github.rmtheis:tess-two:-SNAPSHOT.
         > Could not get resource 'https://jitpack.io/com/github/rmtheis/tess-two/-SNAPSHOT/tess-two--SNAPSHOT.pom'.
            > Could not GET 'https://jitpack.io/com/github/rmtheis/tess-two/-SNAPSHOT/tess-two--SNAPSHOT.pom'.
               > The target server failed to respond

    * Try:
    Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
    
    BUILD FAILED
    
    Total time: 20 mins 14.665 secs

**Comment by jitpack-io** [comment]
Ok, looks like the build is taking more than 15 minutes and times out. Most of the time is spent in the native code building. How long does it take normally?
Perhaps it could be split up...

**Comment by rmtheis** [comment]
It takes about 7 minutes when running locally, so upwards of 15 minutes on the virtual machine is reasonable. I don't think splitting up the build and the associated complications is worth it just to bring the build time down. I'll take a new look when things change in the build in the future.

**Comment by jitpack-io** [comment]
Hi

We're testing new hardware upgrades. The build now takes about 6-7 minutes: 
https://jitpack.io/com/github/rmtheis/tess-two/a2dfdbc053/build.log
