### ISSUE TITLE
ViewPagerIndicator/2.4.2 build issue, Rebuilding a library

### ISSUE THREAD

**Issue by jrejaud** [jitpack/jitpack.io#356]
Log https://jitpack.io/com/github/jrejaud/ViewPagerIndicator/2.4.2/build.log

I deleted this release and released it, but jitpack didn't seem to rebuild the library after I did this. Is there a way to force it to do it again?

**Comment by jitpack-io** [comment]
Hi

Rebuilt it but not sure it made a difference. Looks like that project was setup to work with an older version of maven and we are building using 3.2.5.
Any chance this could be migrated to Gradle?

**Comment by jrejaud** [comment]
Hi there,

I moved the project to another repo and migrated it to gradle (https://github.com/jrejaud/ViewPagerIndicator2) and it's working great now. Thank you :+1:
