### ISSUE TITLE
Download Stats API not working

### ISSUE THREAD

**Issue by hrishikesh-kadam** [jitpack/jitpack.io#3563]
Repo - https://github.com/codetoart/r2-streamer-kotlin

API - https://jitpack.io/api/stats/com.github.codetoart/r2-streamer-kotlin

Response - 
```
{
    "week": 0,
    "month": 0,
    "status": "ok"
}
```

We have at least 10 to 15 downloads everyday. Why is this api not showing any numbers?

**Comment by jitpack-io** [comment]
Hi,

We're rebuilding our stats feature so should get more accurate data when it's live.
