### ISSUE TITLE
Build artifacts and files having wrong names

### ISSUE THREAD

**Issue by mandar2812** [jitpack/jitpack.io#3573]
Recently builds generated by JitPack for [DynaML](http://github.com/transcendent-ai-labs/DynaML) have wrong names for the build artifacts. See the [log](https://jitpack.io/com/github/transcendent-ai-labs/DynaML/-bayesLearn-1.1-ga18093d-1564/build.log) for more details. `bayesLearn` is infact the previous name of DynaML.

**Comment by mandar2812** [comment]
Posting the relevant extract from the log here.

```
Exit code: 0

Build artifacts:
com.github.transcendent-ai-labs.DynaML:dynaml-examples_2.11:-bayesLearn-1.1-ga18093d-1564
com.github.transcendent-ai-labs.DynaML:dynaml-core_2.11:-bayesLearn-1.1-ga18093d-1564
com.github.transcendent-ai-labs.DynaML:dynaml_2.11:-bayesLearn-1.1-ga18093d-1564
com.github.transcendent-ai-labs.DynaML:dynaml-repl_2.11:-bayesLearn-1.1-ga18093d-1564
com.github.transcendent-ai-labs.DynaML:dynaml-pipes_2.11:-bayesLearn-1.1-ga18093d-1564
```

**Comment by jitpack-io** [comment]
Hi,

The last part of the file name is the version: `-bayesLearn-1.1-ga18093d-1564`.
For snapshot builds JitPack uses `git describe` to create the version so bayesLearn is probably from a tag. If you add a new tag then the snapshot version will change too.

**Comment by mandar2812** [comment]
@jitpack-io But this was not the case for previous builds. Bayes Learn is the previous name of the repository, there is no apparent reason why it would appear in the snapshot build artifact, especially since this started happening very recently.

**Comment by mandar2812** [comment]
@jitpack-io I figured out why this was happening, something to do with annotated tags, its fixed now
