### ISSUE TITLE
GithubDemo/0.3 build

### ISSUE THREAD

**Issue by gowcage** [jitpack/jitpack.io#3580]
This time, I added some necessary configurations based on the document, and the warnings in the build log were gone, but they were unsuccessful.

This is my log***************
Build starting...
Start: Mon Nov 19 09:29:18 UTC 2018 614a679d0a2a
Git:
0.3-0-gcf22b0f
commit cf22b0f4d0e7d651c8dd8f2e115598141d49376a
Author: gowcage 
Date:   Mon Nov 19 17:26:39 2018 +0800

    commit message

Run gradle build
Gradle build script
Using gradle wrapper
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Djavax.xml.accessExternalSchema=all -Dhttps.protocols=TLSv1.2
Downloading https://services.gradle.org/distributions/gradle-4.6-all.zip
.....................................................................................................
Unzipping /home/jitpack/.gradle/wrapper/dists/gradle-4.6-all/bcst21l2brirad8k2ben1letg/gradle-4.6-all.zip to /home/jitpack/.gradle/wrapper/dists/gradle-4.6-all/bcst21l2brirad8k2ben1letg
Set executable permissions for: /home/jitpack/.gradle/wrapper/dists/gradle-4.6-all/bcst21l2brirad8k2ben1letg/gradle-4.6/bin/gradle

------------------------------------------------------------
Gradle 4.6
------------------------------------------------------------

Build time:   2018-02-28 13:36:36 UTC
Revision:     8fa6ce7945b640e6168488e4417f9bb96e4ab46c

Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.9 compiled on February 2 2017
JVM:          1.8.0_181 (Oracle Corporation 25.181-b13)
OS:           Linux 4.10.0-28-generic amd64

0m4.416s
Getting tasks: ./gradlew tasks --all
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Djavax.xml.accessExternalSchema=all -Dhttps.protocols=TLSv1.2
Running: ./gradlew clean -Pgroup=com.github.gowcage -Pversion=0.3 -xtest -xlint install
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Djavax.xml.accessExternalSchema=all -Dhttps.protocols=TLSv1.2
:clean UP-TO-DATE
:app:clean UP-TO-DATE
:app:install

BUILD SUCCESSFUL in 0s
3 actionable tasks: 1 executed, 2 up-to-date
Looking for artifacts...
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Djavax.xml.accessExternalSchema=all -Dhttps.protocols=TLSv1.2

Welcome to Gradle 4.8.1!

Here are the highlights of this release:
 - Dependency locking
 - Maven Publish and Ivy Publish plugins improved and marked stable
 - Incremental annotation processing enhancements
 - APIs to configure tasks at creation time

For more details see https://docs.gradle.org/4.8.1/release-notes.html

Looking for pom.xml in build directory and ~/.m2
EXIT_CODE=0
2018-11-19T09:29:49.473448468Z
Exit code: 0
No build artifacts found

**Comment by MotiAmarFlir** [comment]
Does U solve the problem? I have the same issue :\
