### ISSUE TITLE
7z available on Jitpack

### ISSUE THREAD

**Issue by freimair** [jitpack/jitpack.io#3582]
Hi there,

we are using jitpack to provide tor binaries in maven disguise ([here](https://github.com/JesusMcCloud/tor-binary)).

However, when we try repackaging MacOS binaries (.dmg) we cannot extract them because there is no 7z available on the build platform.

Would you please consider adding 7z binaries to your build machines?
thanks a ton!

**Comment by jitpack-io** [comment]
Hi,

Perhaps you could install 7z with custom commands in jitpack.yml

**Comment by freimair** [comment]
Thanks for the hint! However, as there is no bz2 tool installed on your machines I tried it with Ant like so:
```
<get src="https://sourceforge.net/projects/p7zip/files/p7zip/16.02/p7zip_16.02_x86_linux_bin.tar.bz2/download"
    dest="${project.build.directory}/p7zip.tar.bz2"
    skipexisting="true"/>
<bunzip2 src="${project.build.directory}/p7zip.tar.bz2" />
<untar src="${project.build.directory}/p7zip.tar"
    dest="${project.build.directory}/p7zip/" />

<chmod dir="${project.build.directory}/p7zip/p7zip_16.02/bin/" perm="+x" includes="**/*"/>

<exec executable="${project.build.directory}/p7zip/p7zip_16.02/bin/7z" failonerror="true">
    ...
</exec>
```

and it works, even if it is nasty. Just for reference.

Thanks a ton!
