### ISSUE TITLE
AzortisLib/0.1.1 build

### ISSUE THREAD

**Issue by YourPalJake** [jitpack/jitpack.io#3584]
Build log: https://jitpack.io/com/azortis/AzortisLib/0.1.1/build.log

I can see where the error lies but I am going to need a solution to this as I need those dependencies in my project that I have to be able on JitPack. So I have 2 modules v1_13_R1 and v1_13_R2 those require a dependency that is not available on a public repository and require me to install them via [BuildTools](https://www.spigotmc.org/wiki/buildtools/) I allread tried making the dependencies optional. But I am really gonna need a workaround this issue as I cannot avoid using the dependencies.

**Comment by jitpack-io** [comment]
Hi,

How would you build this project in a CI? Perhaps there is a way to install the dependency with custom commands in jitpack.yml?

**Comment by YourPalJake** [comment]
I'm sorry but can you please explain to me what CI is.

**Comment by YourPalJake** [comment]
Also the reason why the artifacts aren’t hosted on a public repository is the fact that some old developer DMCA the thing for some reason

**Comment by YourPalJake** [comment]
Well, there may be perhaps a way to include build tools and add in the jitpack.yml the commands for building the dependencies for the local repo

**Comment by YourPalJake** [comment]
Because you only need the dependencies for compiling right and not sharing etc? Also, will it give me all the modules from the project if I just use AzortisLib as the artifact?

**Comment by YourPalJake** [comment]
> Hi,
> 
> How would you build this project in a CI? Perhaps there is a way to install the dependency with custom commands in jitpack.yml?

How would I do this, so I have the build tools jar that builds those dependencies in a local repository so how would I use custom commands???
