### ISSUE TITLE
mega/-9a229634aa-1 build issue

### ISSUE THREAD

**Issue by shamoh** [jitpack/jitpack.io#361]
Hello.

Log https://jitpack.io/com/github/shamoh/mega/-9a229634aa-1/build.log:

```
Gradle 'install' task not found. Please add the 'maven' or 'android-maven' plugin.
```

But the project uses `maven` plugin, see `gradle/maven.gradle` that is applied from root `build.gradle`.

Thanks for any help,
Libor

**Comment by jitpack-io** [comment]
Hi

Indeed it wasn't finding the install task in your case. Fixed task detection and rebuilt the project. Should be working from now on.
