### ISSUE TITLE
Guava-Optional/79e2d82dda build issue

### ISSUE THREAD

**Issue by blazmag** [jitpack/jitpack.io#362]
Log https://jitpack.io/com/github/plastiv/Guava-Optional/79e2d82dda/build.log

**Comment by jitpack-io** [comment]
Hi

It appears the project has a dependency on itself https://github.com/plastiv/Guava-Optional/blob/master/library/build.gradle#L53

**Comment by blazmag** [comment]
Thanks for checking so quickly! I'll let the owner know.

**Comment by jitpack-io** [comment]
:+1:
