### ISSUE TITLE
JitPack status 500

### ISSUE THREAD

**Issue by tynn** [jitpack/jitpack.io#3622]
Consider a simple elixir project

```
defmodule Cf do
  use Tesla
  adapter Tesla.Adapter.Httpc

  def cf do
    get! "https://www.cloudflare.com/"
  end

  def jp do
    get! "https://jitpack.io/"
  end
end
```

```
defmodule Cf.MixProject do
  use Mix.Project

  def project do
    [
      app: :cf,
      version: "0.1.0",
      elixir: "~> 1.7",
      start_permanent: Mix.env() == :prod,
      deps: [
        { :tesla, "~> 1.2.0" },
        { :hackney, "~> 1.10" }
      ]
    ]
  end
end
```

Calling `Cf.cf()` results in a status of `200` while calling `Cf.jp()` has a status of `500`. Using `adapter Tesla.Adapter.Hackney` instead resolves the issue. The error itself states that cookies have to be enabled. But since `Cloudflare` itselfs works with the given configuration, I'd assume that there is an issue or additional restriction within the setup of _JitPack_.

Maybe there's an issue you want to resolve on your side. If you know about the reason, I'd be interested as well. It just changed sometime the last months.

**Comment by jitpack-io** [comment]
Hi,

Not familiar with Elixir, what does this program do?
We can check logs on our side but we need to know the URLs that the program is requesting.

**Comment by tynn** [comment]
It's a simple Http Client. So it only sends a GET request to https://jitpack.io/

But the same behavior was observable for the repositories.

I can try different other endpoints you'd deem more meaningful.

**Comment by jitpack-io** [comment]
Not sure how we can reproduce this, `curl -v https://jitpack.io/` returns 200.

**Comment by jitpack-io** [comment]
You could also try `https://jitpack.io/api/status`
