### ISSUE TITLE
Build error: Configuration with name 'api' not found.

### ISSUE THREAD

**Issue by johnjohndoe** [jitpack/jitpack.io#3641]
# Links to build logs
https://jitpack.io/com/github/johnjohndoe/snackengage/gradle-versions-plugin-040a2292aa-1/build.log
https://jitpack.io/com/github/johnjohndoe/snackengage/gradle-wrapper-b0e273a29d-1/build.log
https://jitpack.io/com/github/johnjohndoe/snackengage/a92d7cd/build.log

# Does the project build on your machine with the same commands?
Yes, `./gradlew clean test assemble` succeeds.

# What error are you seeing?
All builds I tried fail with the same error:
``` bash
FAILURE: Build failed with an exception.

* Where:
Script '/script/maven-plugin.gradle' line: 2

* What went wrong:
A problem occurred evaluating script.
> Failed to apply plugin [id 'com.github.dcendents.android-maven']
   > Configuration with name 'api' not found.
```

**Comment by jitpack-io** [comment]
Hi,

There's a warning in the logs about a missing `installl` task. Would recommend adding the android-maven plugin: https://jitpack.io/docs/ANDROID/#gradle

**Comment by johnjohndoe** [comment]
Thank you for the hint. - I figured out that JitPack automatically injects the **latest** version of [`android-maven-gradle-plugin`](https://github.com/dcendents/android-maven-gradle-plugin) (currently 2.1) if it is not defined by the library project. Due to its requirements (Gradle wrapper, Android plugin for Gradle) the latest version of the `android-maven-gradle-plugin` is not compatible with every library project. For example if the library still uses the Android plugin for Gradle 2.3.3 then the build will fail as posted above.

I therefore tried to define `android-maven-gradle-plugin` 1.5 in the project. This [build fails](https://jitpack.io/com/github/johnjohndoe/snackengage/df66904/build.log) for a different reason: the [Android plugin for Gradle 2.3.3](https://bintray.com/android/android-tools/com.android.tools.build.gradle/2.3.3) cannot be retrieved from jCenter.

```
> Could not resolve all files for configuration ':classpath'.
   > Could not find com.android.tools.build:gradle:2.3.3.
     Searched in the following locations:
         https://jcenter.bintray.com/com/android/tools/build/gradle/2.3.3/gradle-2.3.3.pom
         https://jcenter.bintray.com/com/android/tools/build/gradle/2.3.3/gradle-2.3.3.jar
         https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/2.3.3/gradle-2.3.3.pom
         https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/2.3.3/gradle-2.3.3.jar
     Required by:
         project :
```
