### ISSUE TITLE
Could not find com.google.ads.interactivemedia.v3:interactivemedia:3.9.4.

### ISSUE THREAD

**Issue by adduri536** [jitpack/jitpack.io#3656]
Please provide: Could not find com.google.ads.interactivemedia.v3:interactivemedia:3.9.4.

- Link to build log from https://jitpack.io
https://jitpack.io/com/github/adduri536/Player/1.0.3/build.log

Could not resolve all files for configuration ':player:releaseCompileClasspath'.
> [Could not find com.google.ads.interactivemedia.v3:interactivemedia:3.9.4.](url)

Thank you!

**Comment by oahmedazab** [comment]
Hello,

there is problem in google repos
https://issuetracker.google.com/issues/120759347

there are a workaround for now
add this to your project build gradle

maven { url 'https://dl.bintray.com/google/interactivemedia/' }

in 
allprojects {
    repositories {
      maven { url 'https://dl.bintray.com/google/interactivemedia/' }
    }
}
