### ISSUE TITLE
sbt: "No build artifacts found" despite artifacts copied succesfully

### ISSUE THREAD

**Issue by ArturGajowy** [jitpack/jitpack.io#3657]
Hi! Thank you for your great work! I love to see that jitpack keeps evolving! :)

I've got a problem with jitpack not finding jars after a successful build:

- Link to build log from https://jitpack.io
https://jitpack.io/com/github/vcherkassky/sbt-optimizer/sbt-1.x-v0.1.2-g6348b2d-2/build.log

- Does the project build on your machine with the same commands?
The build passes on jitpack. Jitpack can't seem to find the jars that were put into .m2.

- What error are you seeing?

It seems to me, that the jitpack can't find the jars where it expects them. It is though unclear to me (after reading the docs) what are the rules for sbt artifacts (where jitpack will look).

```
[info] Done packaging.
[info] 	published sbt-optimizer to file:/home/jitpack/.m2/repository/net/virtual-void/sbt-optimizer_2.12_1.0/0.1.3/sbt-optimizer-0.1.3.pom
[info] 	published sbt-optimizer to file:/home/jitpack/.m2/repository/net/virtual-void/sbt-optimizer_2.12_1.0/0.1.3/sbt-optimizer-0.1.3.jar
[info] 	published sbt-optimizer to file:/home/jitpack/.m2/repository/net/virtual-void/sbt-optimizer_2.12_1.0/0.1.3/sbt-optimizer-0.1.3-sources.jar
[info] 	published sbt-optimizer to file:/home/jitpack/.m2/repository/net/virtual-void/sbt-optimizer_2.12_1.0/0.1.3/sbt-optimizer-0.1.3-javadoc.jar
[success] Total time: 8 s, completed Dec 12, 2018 12:40:02 PM
Looking for artifacts...
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Djavax.xml.accessExternalSchema=all -Dhttps.protocols=TLSv1.2
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Djavax.xml.accessExternalSchema=all -Dhttps.protocols=TLSv1.2
Looking for pom.xml in build directory and ~/.m2
Found artifact: net.virtual-void:sbt-optimizer:0.1.3
EXIT_CODE=0
2018-12-12T12:40:05.564637687Z
Exit code: 0
No build artifacts found
```

Is it due to the artifacts being put under `net/virtual-void` and not `com/github/vcherkassky`?
Or is it due to sbt plugins' fancy artifact scheme (including not only scala version, but sbt version as well)?

Is there a way for me to tell jitpack where the artifacts are going to be / copy them to the expected place without modifying the build? Can I do it with .jitpakck.yml somehow?

What would the expected place be?

Also, I think the https://jitpack.io/docs/BUILDING/ page is not in sync with what's in https://github.com/jitpack/jitpack.io/blob/master/BUILDING.md

Thank you!

**Comment by jitpack-io** [comment]
Hi,

Does your build also create pom.xml files in the build directory? The publishing might not be working because of the sbt version included in file name.
Perhaps this will be helpful: https://github.com/jitpack/jitpack.io/issues/377#issuecomment-183660424

**Comment by ArturGajowy** [comment]
Thx for the hints, will give them a try and reopen if needed! :)
