### ISSUE TITLE
jitpack.io not up to date with github repo

### ISSUE THREAD

**Issue by ArturGajowy** [jitpack/jitpack.io#3658]
Hi!

I think the https://jitpack.io/docs/BUILDING/ page is not in sync with what's in https://github.com/jitpack/jitpack.io/blob/master/BUILDING.md - as mentioned in #3657 

Cheers!

**Comment by jitpack-io** [comment]
Thanks! Docs should get deployed within a week

**Comment by jitpack-io** [comment]
Should be up to date now. The older version might still be cached on CDN for a while
