### ISSUE TITLE
dependencies question by api

### ISSUE THREAD

**Issue by luhaoaimama1** [jitpack/jitpack.io#3659]
A dependencies B ,B dependencies other(C) by api, but A not find other (C)lib. B publish by Jitpack.
demo: 
api 'com.github.luhaoaimama1:zone-sdk:1.0.98'
to use GsonUtils  you will found the picture
![](https://ws4.sinaimg.cn/large/006tNbRwgy1fy53sw8r3rj30xi0nejsw.jpg)

**Comment by jitpack-io** [comment]
Hi,

We rely on https://github.com/dcendents/android-maven-gradle-plugin to produce accurate pom file so it might be an issue there.

One thing you could try is upgrading Gradle to the latest and see if that changes anything
