### ISSUE TITLE
Build is stuck in queue

### ISSUE THREAD

**Issue by yosriz** [jitpack/jitpack.io#3660]
The build is stuck since yesterday on this library, I've tried with several different commits/branches, also deleted and started again, but nothing seems to work.
A build for example:
https://jitpack.io/com/github/kinecosystem/kin-ecosystem-android-sdk/a57d94b0cc/build.log 
The library:
https://github.com/kinecosystem/kin-ecosystem-android-sdk

This library is being built for a quite long time with jitpack, and is built successfully using circle ci.

**Comment by jitpack-io** [comment]
Hi,

Should be completed now

**Comment by yosriz** [comment]
solved, thanks.
