### ISSUE TITLE
Build fails for ModelCC

### ISSUE THREAD

**Issue by eklinger** [jitpack/jitpack.io#3665]
Can't build maven project due to pom.xml not being in the root of the project. Can it be possible to specify the full root, e.g. https://bitbucket.org/fberzal/modelcc/src/master/ModelCC/
So that it will build properly?

Build starting...
Start: Wed Dec 5 00:48:47 UTC 2018 1b58ceda77e5
Git:
1832e8d
commit 1832e8d6d9431fd7458b8042ade105000b3d8994
Author: Fernando Berzal 
Date:   Thu Feb 11 18:18:28 2016 +0100

    [modelcc.language] Builder.cast() method
    

ERROR:
No build file found. Looking for Gradle/Maven/Sbt/Lein build file in the root of the project
See the documentation at https://jitpack.io/docs/
Files: 
ModelCC
README.md
2018-12-05T00:48:47.367323472Z
Exit code: 1
No build artifacts found

Thanks

**Comment by jitpack-io** [comment]
Hi,

If you have access to the repository then you could build with custom commands: https://jitpack.io/docs/BUILDING/#custom-commands
