### ISSUE TITLE
Support Kotlin JS projects (requires NodeJS)

### ISSUE THREAD

**Issue by rnett** [jitpack/jitpack.io#3666]
Currently, JitPack does not support Kotlin JS projects.

This is because the JitPack server doesn't have NodeJS installed, which causes the :npm-install task to fail.

Kotlin JS projects are publishable on maven repos as jars (see [Ktor Client JS](https://mvnrepository.com/artifact/io.ktor/ktor-client-js)), it would be nice if JitPack supported this.

[Build Log](https://jitpack.io/com/github/rnett/kframejs/-42852132e5-1/build.log).

**Comment by jitpack-io** [comment]
Hi,

There are many versions of node so not sure we can support all of them. Seems like it would be simpler to use a Gradle plugin for installing Node during your build - https://plugins.gradle.org/plugin/com.moowork.node.
Would that work for you?

**Comment by rnett** [comment]
Thanks.  As it turns out, the kotlin frontend plugin includes a node download task, it just isn't documented anywhere.   Using that worked.
