### ISSUE TITLE
Task 'install' not found in root project 'build'

### ISSUE THREAD

**Issue by liangzhengang** [jitpack/jitpack.io#3667]
Please provide:

- Link to build log from https://jitpack.io
https://jitpack.io/com/github/liangzhengang/tipviewdemo/v1.4/build.log
- Does the project build on your machine with the same commands?
yes
- What error are you seeing?
Task 'install' not found in root project 'build'
I have tried to add  classpath 'com.github.dcendents:android-maven-gradle-plugin:2.1',but it didn't work.
And I have tried to ./gradlew install on my machine ,it done well;I don't know how to solve this problem..

**Comment by jitpack-io** [comment]
Hi,

You also need to `apply` the plugin in your library: https://jitpack.io/docs/ANDROID/ (Step 2)

**Comment by liangzhengang** [comment]
> Hi,
> 
> You also need to `apply` the plugin in your library: https://jitpack.io/docs/ANDROID/ (Step 2)
thx...i fix  solve this problem now....
