### ISSUE TITLE
PEX Build Failure

### ISSUE THREAD

**Issue by ghost** [jitpack/jitpack.io#3668]
Please provide:

- https://jitpack.io/com/github/PEXPlugins/PermissionsEx/STABLE-1.23.4/build.log

- yes

- https://jitpack.io/com/github/PEXPlugins/PermissionsEx/STABLE-1.23.4/build.log

Thank you!

**Comment by jitpack-io** [comment]
Looks like this repo is timing out http://repo.gravitydevelopment.net
