### ISSUE TITLE
Groups and Subgroup

### ISSUE THREAD

**Issue by ppking2897** [jitpack/jitpack.io#3671]
Hi , i want to build private from gitlab , url is https://gitlab.com/TrackAndroid/android/track-libary

i created group and subgroup , but i can't build this url , the error show "No read access to repo"

Is there a way to solve this problem? or it just build without subgroup

Thank You!!

**Comment by jitpack-io** [comment]
Hi,

At the moment JitPack only builds without subgroups.

**Comment by jitpack-io** [comment]
Hi,

Building private repositories requires a JitPack subscription https://jitpack.io/private but there's also a free trial
