### ISSUE TITLE
Build failing with Gradle 5.1 and Kotlin DSL

### ISSUE THREAD

**Issue by ihorh** [jitpack/jitpack.io#3673]
Please provide:

- Link to build log from https://jitpack.io: https://jitpack.io/com/gitlab/jaspery-public-libraries/just-cache/5-use-api-dependency-scope-in-form-of-api-f8b22948b3-1/build.log

- Does the project build on your machine with the same commands? not sure, but it builds with ./gradlew clean assemble

- What error are you seeing?

FAILURE: Build failed with an exception.

* What went wrong:
Task 'test' not found in root project 'just-cache'.

Also I'm not sure if it is related to Gradle 5.1 and/or Kotlin dsl, it's just that  my other builds with Gradle 4+ and groovy scripts seems to work find.

Thank you!

**Comment by ihorh** [comment]
I've been able to fix that by adding maven plugin. It's just strange the other builds don't require it. Feel free to close this issue.

**Comment by jitpack-io** [comment]
Thank's for sharing your fix!

**Comment by shehabic** [comment]
@jitpack-io @ihorh can you share more details about the fix?

**Comment by ihorh** [comment]
@shehabic 

In that case I just added maven plugin to the root build.gradle.kts file like this:

```
subprojects {
    apply { plugin("maven") }
    ...
```

In similar case when I tried Kotlin Multiplatform buld in other project I've fixed similar issues by adding maven publish plugin like this:

```
allprojects {
    apply(plugin = "maven-publish")
}
```

In projects where I use pure gradle build script (without kotlin DSL) build works well without adding maven or maven-publish plugin.

All projects use gradle 5.2.+
