### ISSUE TITLE
Allow -SNAPSHOT version also for javadoc

### ISSUE THREAD

**Issue by shamoh** [jitpack/jitpack.io#368]
Is it possible to access javadoc using `-SNAPSHOT` in javadoc URL?

Revision URL correctly presents project javadoc: https://jitpack.io/com/github/shamoh/mega/mega-runtime/-59ae6b30d6-1/javadoc/

But SNAPSHOT URL is not available: https://jitpack.io/com/github/shamoh/mega/mega-runtime/-SNAPSHOT/javadoc/

**Comment by jitpack-io** [comment]
Hi,

At at the moment it's not supported but we could. Will have a look

**Comment by jitpack-io** [comment]
Should be working now. Thanks for the suggestion, it's an awesome idea!

**Comment by shamoh** [comment]
It works, thanks.
