### ISSUE TITLE
Failed to install the following Android SDK packages as some licences have not been accepted.

### ISSUE THREAD

**Issue by SilenceDut** [jitpack/jitpack.io#3685]
- https://jitpack.io/com/github/silencedut/diffadapter/1.2.1/build.log

- ./gradlew tasks --all build scuuess on my machine

-  this issue "https://github.com/jitpack/jitpack.io/issues/2743" is related ,but It don't solve my problem

Thank you!

**Comment by mightea** [comment]
Experiencing the same issue with Android SDK Build-Tools 28.0.3

```
> Failed to install the following Android SDK packages as some licences have not been accepted.
     build-tools;28.0.3 Android SDK Build-Tools 28.0.3
     platforms;android-28 Android SDK Platform 28
  To build this project, accept the SDK license agreements and install the missing components using the Android Studio SDK Manager.
  Alternatively, to transfer the license agreements from one workstation to another, see http://d.android.com/r/studio-ui/export-licenses.html
  
  Using Android SDK: /opt/android-sdk-linux
```

**Comment by TonyTangAndroid** [comment]
Please refer to this method to temporarily resolve your problem.
https://github.com/jitpack/jitpack.io/issues/3685#issuecomment-455777708

**Comment by noamtamim** [comment]
See here for an alternative solution: https://github.com/jitpack/jitpack.io/issues/3687#issuecomment-455901608

**Comment by aveenashmandhwani** [comment]
Hey!!!

Just open terminal or git bash and head over to your android studio directory.

For windows users:
`cd C:\Users\{USERNAME}\AppData\Local\Android\Sdk\tools\bin`

and then run this to accept unaccepted licenses.
`sdkmanager.bat --licenses`

and then just review and accept them by typing 'y' and hit enter till its done..

Reference:

https://www.youtube.com/watch?v=c7HmwiTtYPE&t=580s
