### ISSUE TITLE
 Failed to install the following Android SDK packages as some licences have not been accepted.

### ISSUE THREAD

**Issue by ligi** [jitpack/jitpack.io#3686]
Please provide:

- Link to build log from https://jitpack.io

https://jitpack.io/com/github/ligi/KAXT/0.21/build.log

- Does the project build on your machine with the same commands?

yes

- What error are you seeing?
```

* What went wrong:
A problem occurred configuring project ':lib'.
> Failed to install the following Android SDK packages as some licences have not been accepted.
     build-tools;28.0.3 Android SDK Build-Tools 28.0.3
     platforms;android-28 Android SDK Platform 28
  To build this project, accept the SDK license agreements and install the missing components using the Android Studio SDK Manager.
  Alternatively, to transfer the license agreements from one workstation to another, see http://d.android.com/r/studio-ui/export-licenses.html
  
  Using Android SDK: /opt/android-sdk-linux

```

**Comment by TonyTangAndroid** [comment]
Please refer to this method to temporarily resolve your problem.
https://github.com/jitpack/jitpack.io/issues/3685#issuecomment-455777708

**Comment by ligi** [comment]
I think this might be the wrong link - I do not see a workaround there

**Comment by TonyTangAndroid** [comment]
@ligi Apologize. I had referenced the wrong link. I have made the update.

**Comment by ligi** [comment]
@TonyTangAndroid no need to apologize - thanks for the link!

**Comment by noamtamim** [comment]
See here for an alternative solution: https://github.com/jitpack/jitpack.io/issues/3687#issuecomment-455901608

**Comment by aveenashmandhwani** [comment]
Hey!!!

Just open terminal or git bash and head over to your android studio directory.

For windows users:
`cd C:\Users\{USERNAME}\AppData\Local\Android\Sdk\tools\bin`

and then run this to accept unaccepted licenses.
`sdkmanager.bat --licenses`

and then just review and accept them by typing 'y' and hit enter till its done..

Reference:

https://www.youtube.com/watch?v=c7HmwiTtYPE&t=580s
