### ISSUE TITLE
Failed to install the following Android SDK packages as some licences have not been accepted.

### ISSUE THREAD

**Issue by 1993hzw** [jitpack/jitpack.io#3688]
https://jitpack.io/com/github/1993hzw/Doodle/5.4/build.log

**Comment by superandrew213** [comment]
Duplicate https://github.com/jitpack/jitpack.io/issues/3687

**Comment by TonyTangAndroid** [comment]
Please refer to this method to temporarily resolve your problem.
https://github.com/jitpack/jitpack.io/issues/3685#issuecomment-455777708

**Comment by jitpack-io** [comment]
Hi,

Should be working now
