### ISSUE TITLE
 You have not accepted the license agreements of the following SDK components? how to solve this problem？

### ISSUE THREAD

**Issue by JunGenius** [jitpack/jitpack.io#3689]
* What went wrong:
A problem occurred configuring project ':app'.
> You have not accepted the license agreements of the following SDK components:
  [Android SDK Platform 27, Android SDK Build-Tools 26.0.2].
  Before building your project, you need to accept the license agreements and complete the installation of the missing components using the Android Studio SDK Manager.
  Alternatively, to learn how to transfer the license agreements from one workstation to another, go to http://d.android.com/r/studio-ui/export-licenses.html

**Comment by TonyTangAndroid** [comment]
Please refer to this method to temporarily resolve your problem.
https://github.com/jitpack/jitpack.io/issues/3685#issuecomment-455777708

**Comment by noamtamim** [comment]
See here for an alternative solution: https://github.com/jitpack/jitpack.io/issues/3687#issuecomment-455901608
