### ISSUE TITLE
Jitpack not accepting SDK licenses produces failed builds

### ISSUE THREAD

**Issue by knockmark10** [jitpack/jitpack.io#3690]
I'd like to report the fact that jitpack's server is not accepting SDK licenses anymore.

I'm currently developing a library, which I've been deploying the whole week. I recently made a very small change in the library when I faced this issue, that I wasnt seeing yesterday, when I last deployed.

Could you fix this??

**Comment by superandrew213** [comment]
Duplicate https://github.com/jitpack/jitpack.io/issues/3687

**Comment by TonyTangAndroid** [comment]
Please refer to this method to temporarily resolve your problem.
https://github.com/jitpack/jitpack.io/issues/3685#issuecomment-455777708

**Comment by jitpack-io** [comment]
Hi,

Should be working now

**Comment by knockmark10** [comment]
This has been resolved. I'm closing this issue.
