### ISSUE TITLE
Failed to install the following Android SDK packages as some licences have not been accepted

### ISSUE THREAD

**Issue by alkammar** [jitpack/jitpack.io#3691]
Please provide:

- Link to build log from https://jitpack.io
https://jitpack.io/com/github/alkammar/tectonic/2.1.9/build.log

- Does the project build on your machine with the same commands?
Yes

- What error are you seeing?
Failed to resolve: com.github.alkammar:tectonic:2.1.9

Thank you!

**Comment by sicmu** [comment]
I have the same problem.
how to resolve it ?

**Comment by sicmu** [comment]
@alkammar do you resolve the problem?

**Comment by superandrew213** [comment]
Duplicate https://github.com/jitpack/jitpack.io/issues/3687

**Comment by alkammar** [comment]
Closing this as it is duplicate of #3687
