### ISSUE TITLE
Could not find tools.jar in system classpath, which is required for kapt to work

### ISSUE THREAD

**Issue by jhh** [jitpack/jitpack.io#3692]
Please provide:

- [build log](https://jitpack.io/com/github/strykeforce/thirdcoast/19.1.1/build.log)

- Does the project build on your machine with the same commands?
Yes, `./gradlew clean -Pgroup=com.github.strykeforce -Pversion=19.1.1 -xtest build publishToMavenLocal` runs successfully on my machine.

- What error are you seeing?
```
Execution failed for task ':telemetry:kaptKotlin'.
> Could not find tools.jar in system classpath, which is required for kapt to work
```
Thank you!

**Comment by jitpack-io** [comment]
Hi,

Seems like the build runs with JDK 11 and tools.jar was removed in JDK 9.

**Comment by jhh** [comment]
Thanks,

According to this [Jetbrains issue](https://youtrack.jetbrains.com/issue/KT-27188), they claim to have fixed this in Kotlin 1.3.20. I upgraded to 1.3.20 and am still seeing the issue. I will reference this on their issue and keep looking.

**Comment by elect86** [comment]
be double sure the updated kotlin is being actually used in the build, look in the jitpack logs

**Comment by RicoApfelbeck** [comment]
I have the same warning with <kotlin.version>1.3.61</kotlin.version> in maven

**Comment by Dudeplayz** [comment]
Error is still there, had to fix it by copying the tools.jar from JDK8 to JDK11. Im using maven.

**Comment by GlenKPeterson** [comment]
Getting this warning with <kotlin.version>1.3.70</kotlin.version> in maven, though I'm having other problems at the same time.
