### ISSUE TITLE
ailed to install the following Android SDK packages as some licences have not been accepted.

### ISSUE THREAD

**Issue by gyymz1993** [jitpack/jitpack.io#3695]
* What went wrong:
A problem occurred configuring project ':app'.
> Failed to install the following Android SDK packages as some licences have not been accepted.
     build-tools;28.0.3 Android SDK Build-Tools 28.0.3
     platforms;android-28 Android SDK Platform 28
  To build this project, accept the SDK license agreements and install the missing components using the Android Studio SDK Manager.
  Alternatively, to transfer the license agreements from one workstation to another, see http://d.android.com/r/studio-ui/export-licenses.html
  
  Using Android SDK: /opt/android-sdk-linux

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

**Comment by erkutaras** [comment]
I solve the issue with https://github.com/jitpack/jitpack.io/issues/3687#issuecomment-455885806
