### ISSUE TITLE
since their licenses or those of the packages they depend on were not accepted:

### ISSUE THREAD

**Issue by acoderleex** [jitpack/jitpack.io#3699]
Accept? (y/N): Skipping following packages as the license is not accepted:
Android SDK Build-Tools 27.0.3
The following packages can not be installed since their licenses or those of the packages they depend on were not accepted:
  build-tools;27.0.3
Found gradle
Gradle build script

**Comment by jitpack-io** [comment]
Hi,

Should be fixed now

**Comment by jitpack-io** [comment]
@xuexiangjys Seems like that build succeeded. Does it not work for you?

**Comment by xuexiangjys** [comment]
follow https://github.com/jitpack/jitpack.io/issues/3687#issuecomment-455901608 i build succeeded @jitpack-io

**Comment by acoderleex** [comment]
worked now
