### ISSUE TITLE
https://jitpack.io/com/github/lxj-helloworld/basePro/1.11.49/build.log

### ISSUE THREAD

**Issue by lxj-helloworld** [jitpack/jitpack.io#3701]
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> You have not accepted the license agreements of the following SDK components:
  [Android SDK Platform 27, Android SDK Build-Tools 27.0.3].
  Before building your project, you need to accept the license agreements and complete the installation of the missing components using the Android Studio SDK Manager.
  Alternatively, to learn how to transfer the license agreements from one workstation to another, go to http://d.android.com/r/studio-ui/export-licenses.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
EXIT_CODE=1
2019-01-21T10:33:41.895642671Z
Exit code: 1
No build artifacts found

https://jitpack.io/com/github/lxj-helloworld/basePro/1.11.49/build.log

**Comment by jitpack-io** [comment]
Looks like it succeeded after rebuilding
