### ISSUE TITLE
android build-tools 26.0.2 android sdk not accept the license

### ISSUE THREAD

**Issue by bxvip** [jitpack/jitpack.io#3704]
A problem occurred configuring project ':lib-ui-tocleanmvp'.
> You have not accepted the license agreements of the following SDK components:
  [Android SDK Platform 26, Android SDK Build-Tools 26.0.2].
  Before building your project, you need to accept the license agreements and complete the installation of the missing components using the Android Studio SDK Manager.
  Alternatively, to learn how to transfer the license agreements from one workstation to another, go to http://d.android.com/r/studio-ui/export-licenses.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

**Comment by dujianchi** [comment]
I got a same problem.

> Failed to install the following Android SDK packages as some licences have not been accepted.
>      platforms;android-27 Android SDK Platform 27
>      build-tools;28.0.3 Android SDK Build-Tools 28.0.3
>   To build this project, accept the SDK license agreements and install the missing components using the Android Studio SDK Manager.
>   Alternatively, to transfer the license agreements from one workstation to another, see http://d.android.com/r/studio-ui/export-licenses.html
>   
>   Using Android SDK: /opt/android-sdk-linux

**Comment by MrChaz** [comment]
Same for me using 28.0.3

**Comment by MrChaz** [comment]
looks to be resolved now

**Comment by jitpack-io** [comment]
Yes, should be resolved now. If you have a failed build then you can try rebuilding

**Comment by bxvip** [comment]
thank you very mach,it's ok!

JitPack.io <notifications@github.com> 于2019年1月23日周三 下午6:49写道：
