### ISSUE TITLE
Failed to publish publication 'aar' to repository 'mavenLocal'

### ISSUE THREAD

**Issue by avshvetsov** [jitpack/jitpack.io#3705]
Please provide:

- Link to build log from https://jitpack.io
https://jitpack.io/com/github/avshvetsov/FastScroll/6801e3c588/build.log

- Does the project build on your machine with the same commands?
No

- What error are you seeing?
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':fastscroll:publishAarPublicationToMavenLocal'.
> Failed to publish publication 'aar' to repository 'mavenLocal'
   > Invalid publication 'aar': artifact file does not exist: '/home/jitpack/build/fastscroll/build/outputs/aar/fastscroll-release.aar'

Thank you!

**Comment by jitpack-io** [comment]
Hi,

Not quite sure what is causing the error.
If the project is not building on your machine then JitPack won't be able to build it either.

**Comment by devilk10** [comment]
fastscroll-release.aar try replacing this with fastscroll.aar, which will look like artifact("$buildDir/outputs/aar/fastscroll.aar") in the build.gradle of the module.
