### ISSUE TITLE
"BUILD SUCCESSFUL", Status: Error

### ISSUE THREAD

**Issue by avshvetsov** [jitpack/jitpack.io#3706]
Can anyone help me?
I have "BUILD SUCCESSFUL", but Status: Error
https://jitpack.io/com/github/avshvetsov/FastScroll/83e7965aca/build.log

Thank you!

**Comment by jitpack-io** [comment]
Hi,

Doesn't seem like that commit exists anymore

**Comment by avshvetsov** [comment]
@jitpack-io , reprodused same issue: https://jitpack.io/com/github/avshvetsov/FastScroll/1e7c6bd457/build.log

Look here please.
