### ISSUE TITLE
Provide status icon that shows status of project build

### ISSUE THREAD

**Issue by shamoh** [jitpack/jitpack.io#371]
It would be great I could display status of the last JitPack build on tom of my `README.md`. Something like Travis CI provides, e.g. https://travis-ci.org/shamoh/mega.svg?branch=master

I'm proud user of JitPack and I believe such icon could help JitPack as a reference to be more known.

**Comment by jitpack-io** [comment]
Hi

Completely agree with you. Will be adding badges in the future. Testing them now:)

**Comment by jitpack-io** [comment]
If you'd like to try it out, the url is:
`https://jitpack.io/v/User/Repo.svg`

`[![Release](https://jitpack.io/v/User/Repo.svg)](https://jitpack.io/#User/Repo)`

[![Release](https://jitpack.io/v/jitpack/maven-simple.svg)](https://jitpack.io/#jitpack/maven-simple)

**Comment by shamoh** [comment]
Does it support just releases? Or should I specify build/version somehow?

https://jitpack.io/v/shamoh/mega.svg returns "..." icon.

**Comment by jitpack-io** [comment]
Ah yes, it was meant to show the latest release. In your case you probably want the last snapshot build?
We could probably add that as well

**Comment by shamoh** [comment]
Yes. But it is probably minor case. I can work with this.

**Comment by shamoh** [comment]
I see you implemented SNAPSHOT support.

But I don't understand what the number in badge icon means.

E.g. for https://jitpack.io/#shamoh/mega/-SNAPSHOT there is `813500d6f0` but I don't see any connection with project git commits.

And the badge is red color. Does it mean there where some problem to build the project? I don't see any problem to see the latest commit.

Thanks,
Libor

**Comment by jitpack-io** [comment]
Good catch! Fixed that now and should be showing the last snapshot version.

**Comment by shamoh** [comment]
Perfect, thanks.
