### ISSUE TITLE
[Feature Request] Pull Request Support

### ISSUE THREAD

**Issue by richardtreier** [jitpack/jitpack.io#3717]
Hello,

is there any plans to support picking specific Pull Requests or commits yet to be merged?

For example like this: https://github.com/liquibase/liquibase-hibernate/pull/181

or like this: https://github.com/liquibase/liquibase-hibernate/tree/847fcd37cca66170839443a431f42489867793ec

I am not well-versed enough to know if the immutability of those URLs is sufficient. I cannot judge how well they would be distinct enough to pin down states of the code-base.

The problem this would solve is allowing people to reference critical fixes when using slowly/poorly maintained projects where people cannot merge useful changes due to issues with the management of the repositories.

**Comment by jitpack-io** [comment]
Is it not possible to build PRs using commit sha as the version?

**Comment by jitpack-io** [comment]
The plan is to add pull request support using version:
 - `PR<NR>-SNAPSHOT`

For example: `com.github.jitpack:gradle-simple:PR4-SNAPSHOT`

**Comment by jitpack-io** [comment]
Now testing pull request builds. For example:
`com.github.jitpack:gradle-simple:PR4-SNAPSHOT`

**Comment by jitpack-io** [comment]
Released.
Version: `PR<NR>-SNAPSHOT`
