### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by ololjvNek** [jitpack/jitpack.io#3718]
Please provide:

- https://jitpack.io/com/github/Sycholic/PermissionsEx/STABLE-1.23.4/build.log

- Yes

``
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5.189 s
[INFO] Finished at: 2017-03-22T14:48:35+00:00
[INFO] Final Memory: 22M/962M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project PermissionsEx: Could not resolve dependencies for project ru.tehkode:PermissionsEx:jar:1.24.0-SNAPSHOT: Failed to collect dependencies at com.zachsthings:netevents:jar:1.1-SNAPSHOT -> org.bukkit:bukkit:jar:1.7.2-R0.1: Failed to read artifact descriptor for org.bukkit:bukkit:jar:1.7.2-R0.1: Could not transfer artifact org.bukkit:bukkit:pom:1.7.2-R0.1 from/to bukkit-repo (http://repo.bukkit.org/content/groups/public/): repo.bukkit.org: unknown error: Unknown host repo.bukkit.org: unknown error -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
EXIT_CODE=1
2017-03-22T14:48:35.415660462Z
Exit code: 1
No build artifacts found

**Comment by jitpack-io** [comment]
Hi,

The error comes from repo.bukkit.org repository. Not sure there's anything we can do on our side
