### ISSUE TITLE
Jitpack is case sensitive while GitHub is not

### ISSUE THREAD

**Issue by JLLeitschuh** [jitpack/jitpack.io#3722]
**Describe the bug**
The username and repository name on Github is not case sensitive, but JitPack shows different information for different capitalization of the same artifact.

**To Reproduce**
1. Look at the release listings for this repo:
 - https://jitpack.io/#williamahartman/jamepad
2. Look at the release listings for this repo:
 - https://jitpack.io/#Williamahartman/jamepad
2. Look at the release listings for this repo:
 - https://jitpack.io/#WilliamAHartman/Jamepad

**Expected behavior**
I would expect that, regardless of whether I specify the repo uppercase or lowercase, the repo would resolve to the same artifact listing.

If JitPack were to treat all Github repositories as case insensitive this will probably reduce the number of builds that JitPack needs to make.

**Caveats**
I don't know if the same is true for non-GitHub repository hosts. I recommend checking how case sensitive they are with names before implementing a sweeping fix.

**Comment by jitpack-io** [comment]
Hi,

Thanks for raising this!
Being case sensitive has it's drawbacks for sure but we can also see some benefits. People often use mixed case for naming their GitHub repos and we think allowing them to use the same case in Gradle is a plus.

The problem we have is that coordinates Gradle/Maven are case sensitive so even if we build a repository just once then we cannot serve the same artifacts for different coordinates with different case.
If someone requests `com.github.jitpack:Gradle-Simple:1.0` then we can't serve them `com.github.jitpack:gradle-simple:1.0` artifacts as that will break in Gradle. As a result we end up re-building the repository.
We could possibly do something clever and re-write the coordinates depending on how you request them.
