### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by Abdelsattar** [jitpack/jitpack.io#3724]
- Link to build log from https://jitpack.io
https://jitpack.io/com/github/OmarAliSaid/CustomTimePicker/1.0.0/build.log

- Does the project build on your machine with the same commands?
it builds successfully on my machine

- What error are you seeing?
Task 'install' is ambiguous in root project 'build'. Candidates are: 'installDebug', 'installDebugAndroidTest'.

**Comment by jitpack-io** [comment]
Hi,

Would recommend adding the android-maven plugin https://jitpack.io/docs/ANDROID/

**Comment by Abdelsattar** [comment]
Hi ,

I added it and it still gives me an error here : https://jitpack.io/com/github/OmarAliSaid/CustomTimePicker/0.1.0/build.log

after the build is successful

**Comment by LapaStudio** [comment]
Hi,

I solved this problem by pushing all project files again to my repo. If you want just follow these steps:
1. Disable your '.gitignore' file -> p.e. rename it to '._gitignore' 
2. Remove all files from cache -> git rm -r --cached . 
3. Update the index and track all files again -> git add .
4. Commit all files -> git commit -m "project restore"
5. Restore your .gitignore and check for any cache files that should be ignored  ( .cxx folders for instance).

**Comment by jitpack-io** [comment]
Hi,

Seems like it is not installing the ':customtimepicker' Gradle module.
It probably needs to be lowercased in:
https://github.com/OmarAliSaid/CustomTimePicker/blob/master/settings.gradle
