### ISSUE TITLE
plugins {} causes an error

### ISSUE THREAD

**Issue by hannesa2** [jitpack/jitpack.io#3725]
https://jitpack.io/com/github/hannesa2/DbPreferences/5.0/build.log

On my local machine it builds.

In the root build.gradle this `plugins {}`causes the error
```
plugins {
    id 'com.github.ben-manes.versions' version '0.20.0'
}
```

**Comment by jitpack-io** [comment]
Hi,

That build looks like it succeeded. What is the issue with it?

**Comment by hannesa2** [comment]
Ok, let me explain with other words
This causes no error
``` 
buildscript {
  repositories {
    ...
  }

  dependencies {
    classpath "com.github.ben-manes:gradle-versions-plugin:0.20.0"
  }
}
```

and this **causes an error**
 
```
plugins {
    id 'com.github.ben-manes.versions' version '0.20.0'
}
```

because this 
```
plugins {
   ...
}
```
 is a common way to specify something and it fails, you should now it and fix it

**Comment by hannesa2** [comment]
Here is an other fail
https://jitpack.io/com/github/hannesa2/RxAudioRecorder/2.2/build.log

**Comment by hannesa2** [comment]
You can only make it work with
https://github.com/hannesa2/RxAudioRecorder/commit/913f30e0bdc709ec3394b6f51e3a04b619ede7ad

But you should enable it, to make it work !

**Comment by hannesa2** [comment]
My test https://github.com/hannesa2/RxAudioRecorder/pull/109/files 
works now https://jitpack.io/#hannesa2/RxAudioRecorder/JitpackTest-SNAPSHOT 👍
