### ISSUE TITLE
Javadoc of multi-module project

### ISSUE THREAD

**Issue by noamtamim** [jitpack/jitpack.io#3728]
**Is your feature request related to a problem? Please describe.**
When browsing for the Javadoc of a multi-module project (`https://jitpack.io/com/github/USER/REPO/VERSION/javadoc/`), nothing is displayed. 

**Describe the solution you'd like**
It would be awesome (and probably very easy to implement) if instead this page shows links to the individual modules' javadocs:
`https://jitpack.io/com/github/USER/REPO/**MODULE1**/VERSION/javadoc`
`https://jitpack.io/com/github/USER/REPO/**MODULE2**/VERSION/javadoc`

**Describe alternatives you've considered**
1. Create a single Javadoc jar of both modules -- I don't know if it's possible and how
2. Tell users to go to the module-specific URL -- ugly IMHO, and I can't build the URL from the repo name without knowing the module names too.

**Comment by jitpack-io** [comment]
Hi,

Thanks for this great suggestion! It will definitely improve the user experience.
We have added this feature and it is available to use. Example:
https://jitpack.io/com/github/jitpack/gradle-modular/v1.3/javadoc/

Let us know if it works for you or not

**Comment by noamtamim** [comment]
It's great, thanks! Exactly what I imagined.
