### ISSUE TITLE
Add artifact links to build API

### ISSUE THREAD

**Issue by noamtamim** [jitpack/jitpack.io#3729]
**Describe the solution you'd like**
Would be awesome if the Single Build API would return the artifacts: jars, aars, source, javadoc and published javadoc URLs.

**Comment by jitpack-io** [comment]
Hi,

Great idea, Thanks for the suggestion!  
Some of those artifacts you can GET with file browsing:
`https://jitpack.io/com/github/<USER>/<REPO>/<TAG>/`

but it gets trickier with multi-module projects so an API would probably make sense.
