### ISSUE TITLE
is jitpack down!! library stop building

### ISSUE THREAD

**Issue by humazed** [jitpack/jitpack.io#3731]
Please provide:

- Link to build log from https://jitpack.io/com/github/humazed/KotlinAndroidUtils/1.8.5/build.log

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install)?
yes
- What error are you seeing?
the library was building fine when I increment the tag version but now suddenly after incrementing the version it stopped building in jitpack

**Comment by jitpack-io** [comment]
Hi,

Seems like it succeeded after rebuild.

**Comment by andylamax** [comment]
Is it down again?

**Comment by Zeyad-37** [comment]
Is it down again?

**Comment by andylamax** [comment]
now it is not

**Comment by anirudhramanan** [comment]
Is it down again?
