### ISSUE TITLE
Build starting... Error building

### ISSUE THREAD

**Issue by michaelcosta** [jitpack/jitpack.io#3733]
This seems to be happening on builds that use RELEASE tags ~the same release but pointing to the commit hash appears to work correctly.~ (We have a private repository but the build log is the same as some other issues posted, and shown below)

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?
Project builds fine locally ~and will also build correctly when targeting the commit hash associated with the tag~
 > Looks like even commit hashes aren't working correctly now

- What error are you seeing?
```
Build starting...
Error building
```

Build log looks the same as: 
https://github.com/jitpack/jitpack.io/issues/3732

**Comment by GRBurst** [comment]
I just faced the same issue in a public repo on commit hashes. I do not think that it is related to RELEASE tags

**Comment by jarmstrong** [comment]
Same issue.

**Comment by thomorl** [comment]
Same issue. Appears to be global.

**Comment by socool** [comment]
Same issue.

**Comment by SilenceDut** [comment]
Same issue.

**Comment by jitpack-io** [comment]
Hi all,

Should be fixed now. If you delete the build and re-build it then we expect it to succeed.
If that doesn't work for some reason then tell us the build log and we'll trigger a rebuilt

**Comment by ErrorxCode** [comment]
> Hi all,
> 
> Should be fixed now. If you delete the build and re-build it then we expect it to succeed. If that doesn't work for some reason then tell us the build log and we'll trigger a rebuilt

Facing this issue again :(

**Comment by Nek-12** [comment]
Not fixed

**Comment by AhlaamK-tap** [comment]
Facing this issue still

**Comment by xcodeBn** [comment]
same issue ...

**Comment by M-Marvin** [comment]
I also have the problem right now, of course exactly then when i urgently need to build something -.-

**Comment by M-Marvin** [comment]
I tired rebuilding multiple times (and made some test commits to test if it just affects one commit), but it always says
Build starting...
Error building

**Comment by jordoncodes** [comment]
I'm also having this issue

**Comment by Nek-12** [comment]
Why is @jitpack-io still down after 24 full hours!? What happened to the SLA?

**Comment by boybeak** [comment]
meet this issue today for multiple times

**Comment by DmitryStarkin** [comment]
this issue today for multiple times

**Comment by jeluchu** [comment]
I thought it was just me and I keep versioning thinking it was a problem with my code, but I keep getting the same error every time even though the project is well configured and previously the versions were OK, and now since yesterday all I get is the same error:

```
Build starting...
Error building
```

**Comment by vrymar** [comment]
@jitpack-io could you please respond to us

**Comment by ErrorxCode** [comment]
It star's working again, try rebuilding your project
