### ISSUE TITLE
Build failing

### ISSUE THREAD

**Issue by MrChaz** [jitpack/jitpack.io#3737]
Please provide:

- Log is this:
Build starting...
Error building

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?
yes

- What error are you seeing?
Sometime clearing the build from jitpack resolves the issue
Thank you!

**Comment by Dovar66** [comment]
the same

**Comment by jitpack-io** [comment]
Should be fixed now.
If you delete the failed build then it should succeed next time.
