### ISSUE TITLE
CastCompanionLibrary-android/v2.7.1 build issue

### ISSUE THREAD

**Issue by yshrsmz** [jitpack/jitpack.io#374]
Log https://jitpack.io/com/github/googlecast/CastCompanionLibrary-android/v2.7.1/build.log

**Comment by jitpack-io** [comment]
Hi!

The project is publishing a few aar files but no .pom file. Currently JitPack only picks up artifacts that publish a pom file along with other files. Nevertheless projects like this should be supported

**Comment by yshrsmz** [comment]
thanks!
