### ISSUE TITLE
lazy-loader/0.1.0 build issue

### ISSUE THREAD

**Issue by codekidX** [jitpack/jitpack.io#375]
Log https://jitpack.io/com/github/codekidX/lazy-loader/0.1.0/build.log

Getting failed to resolve: com.github.codekidX:lazy-loader:0.1.0

**Comment by jitpack-io** [comment]
Hi

Looks like this bit might be missing from build.gradle https://github.com/jitpack/android-example/blob/master/build.gradle#L3-L11

and then this line: https://github.com/jitpack/android-example/blob/master/library/build.gradle#L2
