### ISSUE TITLE
https://jitpack.io/#Cutta/GifView/ build failed

### ISSUE THREAD

**Issue by flyfire** [jitpack/jitpack.io#3750]
Please provide:

- Link to build log from https://jitpack.io
https://jitpack.io/com/github/Cutta/GifView/1.1/build.log
- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?

- What error are you seeing?
When I Use Android Studio,gradle cant resolve this dependency.
Thank you!

**Comment by flyfire** [comment]
In the build.log,it seems all ok,but it got status error on jitpack.

**Comment by xingfukun** [comment]
I got same error:
Caused by: org.gradle.internal.resolve.ArtifactNotFoundException: Could not find LoggingInterceptor.jar (com.github.ihsanbal:LoggingInterceptor:2.0.5).

**Comment by geoffduong** [comment]
It seems to be failing to find the correct build tools version.

> A problem occurred configuring project ':app'.
> A problem occurred configuring project ':library'.
   > failed to find Build Tools revision 23.0.3

**Comment by geoffduong** [comment]
Version 1.0 is failing to build as well.

Please provide:

* Link to build log from https://jitpack.io
  https://jitpack.io/com/github/Cutta/GifView/1.0/build.log
* Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?
  No, Gradle Wrapper needs to be updated.
* What error are you seeing?
> A problem occurred evaluating project ':app'.
> Failed to apply plugin [id 'com.android.application']
   > Gradle version 2.10 is required. Current version is 2.4. If using the gradle wrapper, try editing the distributionUrl in /home/jitpack/build/gradle/wrapper/gradle-wrapper.properties to gradle-2.10-all.zip
