### ISSUE TITLE
build issue

### ISSUE THREAD

**Issue by renancaraujo** [jitpack/jitpack.io#3751]
Please provide:

- Link to build log from https://jitpack.io
https://jitpack.io/com/github/mthli/Slice/v1.2/build.log

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?
Yes

- What error are you seeing?
[When accessing directly the pom file ](https://jitpack.io/com/github/mthli/Slice/v1.2/Slice-v1.2.pom), I seet the following message: 
```
Build failed. See the log at jitpack.io
```

But when I look into the logs, everything seems fine. Apps dependending on the package wont build.

Thank you!

**Comment by DitFranXX** [comment]
Build from same commit(mthli/Slice@d15a09c) is success. Please trigger the build again @jitpack-io.

Temp fix is replace `v1.2` to `d15a09c1cf`

**Comment by jitpack-io** [comment]
Done
