### ISSUE TITLE
build issue: The JAVA_HOME environment variable is not defined correctly

### ISSUE THREAD

**Issue by quantum13** [jitpack/jitpack.io#3752]
Please provide:

- Link to build log from https://jitpack.io
https://jitpack.io/com/github/mile-core/mile-csa-java/0.2.0/build.log

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?
yes

- What error are you seeing?

The JAVA_HOME environment variable is not defined correctly
This environment variable is needed to run this program
NB: JAVA_HOME should point to a JDK not a JRE

Thank you!

**Comment by freimair** [comment]
quite the same here: https://jitpack.io/com/github/JesusMcCloud/tor-binary/-f75ee90665-1/build.log

and here: https://jitpack.io/com/github/JesusMcCloud/tor-binary/8b5d98c6a8/build.log

all I changed from a working build to these builds is including another tor-version.

Any ideas?

**Comment by jitpack-io** [comment]
Hi,

Looking into it...

**Comment by jitpack-io** [comment]
Hi,

Should be fixed now. Rebuilt

**Comment by quantum13** [comment]
Hi, still error
https://jitpack.io/com/github/mile-core/mile-csa-java/0.2.2/build.log

**Comment by jitpack-io** [comment]
@quantum13 Rebuilt that too

**Comment by freimair** [comment]
worked! thanks!

**Comment by quantum13** [comment]
Thanks
