### ISSUE TITLE
Unable to build 1.13.1

### ISSUE THREAD

**Issue by jpsison-io** [jitpack/jitpack.io#3757]
- Link to build log from https://jitpack.io
https://jitpack.io/com/github/esafirm/android-image-picker/1.13.1/build.log

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?
Yes

- What error are you seeing?
Could not resolve all files for configuration ':app:developmentReleaseCompileClasspath'.
> Could not find com.github.esafirm.android-image-picker:imagepicker:1.13.1.

It is the error on bitbucket pipelines causing the build to fail.

**Comment by joshfriend** [comment]
It seems to be fixed now :)

**Comment by jpsison-io** [comment]
thank you @joshfriend
