### ISSUE TITLE
ERROR: Unable to resolve dependency for ':app@debug/compileClasspath'

### ISSUE THREAD

**Issue by pashaoleynik97** [jitpack/jitpack.io#3758]
- Link to build log: https://jitpack.io/com/github/pashaoleynik97/GSBarcodeScannerHelper/0.1.4-alpha/build.log

- Issue: when I trying to add dependency with my newly created artifact, I am getting this errors:

> ERROR: Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve com.github.pashaoleynik97:GSBarcodeScannerHelper:0.1.4-alpha.
> Show Details
> Affected Modules: app
> 
> ERROR: Unable to resolve dependency for ':app@debugAndroidTest/compileClasspath': Could not resolve com.github.pashaoleynik97:GSBarcodeScannerHelper:0.1.4-alpha.
> Show Details
> Affected Modules: app
> 
> ERROR: Unable to resolve dependency for ':app@debugUnitTest/compileClasspath': Could not resolve com.github.pashaoleynik97:GSBarcodeScannerHelper:0.1.4-alpha.
> Show Details
> Affected Modules: app

Details: created new Android project (in Android Studio) and added dependency to app module:

```
dependencies {
    ...
    implementation 'com.github.pashaoleynik97:GSBarcodeScannerHelper:0.1.4-alpha'
}
```

Also, added this code to project-level `build.gradle`:

```
allprojects {
    repositories {
        google()
        jcenter()
        maven { url 'https://jitpack.io' }
    }
}
```

Question on stackoverflow: https://stackoverflow.com/questions/54928706/error-in-library-built-with-jitpack-unable-to-resolve-dependency-for-appdebu

Repo: https://github.com/pashaoleynik97/GSBarcodeScannerHelper

**Comment by tom-domnic** [comment]
@pashaoleynik97, I'm also facing the same problem. Any solution for that?

**Comment by pashaoleynik97** [comment]
@tom-domnik, unfortunately, no.

**Comment by tom-domnic** [comment]
@jitpack-io , Please help us.

**Comment by tom-domnic** [comment]
@pashaoleynik97, I've just resolved it.
All you've to do that:
1. Just go to the your project on jitpack account.
2. Click on Setting icon.
3. Then you can see a lock icon all you've to do that just click on it and make the library readable to everyone.

Hope it works for you as well! All the best (y)

**Comment by bh90210** [comment]
same issue here

**Comment by itaispector** [comment]
> @pashaoleynik97, I've just resolved it.
> All you've to do that:
> 
> 1. Just go to the your project on jitpack account.
> 2. Click on Setting icon.
> 3. Then you can see a lock icon all you've to do that just click on it and make the library readable to everyone.
> 
> Hope it works for you as well! All the best 👍

Where is that Setting icon ?

**Comment by bh90210** [comment]
the button is here
![settings_icon](https://user-images.githubusercontent.com/22690219/58256611-febead00-7d77-11e9-9aff-a1e6043aeed6.png)

but is available only if the repository is private. mine isn't

**Comment by leonardtatum** [comment]
I am also facing this issue. It makes no sense. I created 4 libraries and 3 of 4 of them work. But one of this is receiving this error and the gradle is the exact same as the working libraries.

**Comment by leonardtatum** [comment]
@pashaoleynik97 by making the project available to everyone, aren't you making your project public?

**Comment by bharthik** [comment]
Any update on this?

**Comment by Viacom18-India** [comment]
Just replace maven { url 'https://jitpack.io' } with maven { url 'https://www.jitpack.io' }
it will work.

**Comment by glenfordshadowfernandes** [comment]
Just replace maven { url 'https://jitpack.io' }
with 
maven { url 'https://www.jitpack.io' }

It will work.

**Comment by ccorneliu** [comment]
Is the option to share artifacts publicly still available for private repositories? I don't see the settings icon.

**Comment by jitpack-io** [comment]
@ccorneliu Artifact sharing is still available. The settings icon should appear if your user has push permissions to the git repository. If it doesn't seem to work please let us know via Support button on the website.

**Comment by jitpack-io** [comment]
Would be great if you could run gradle from command line with the flags `--info --refresh-dependencies`. That should provide more details about the error such as the http status code returned by JitPack.
