### ISSUE TITLE
Failed to apply plugin [id 'com.android.library']    > Gradle version 2.8 is required. Current version is 2.7. If using the gradle wrapper, try editing the distributionUrl in /home/jitpack/build/gradle/wrapper/gradle-wrapper.properties to gradle-2.8-all.zip

### ISSUE THREAD

**Issue by FabianTerhorst** [jitpack/jitpack.io#376]
Im getting this error https://jitpack.io/com/github/fabianterhorst/fastadapter/0.5.7/build.log, but i have inside my gradle wrapper distributionUrl=https\://services.gradle.org/distributions/gradle-2.10-all.zip and inside my top level gralde build file task wrapper(type: Wrapper) {
    gradleVersion = '2.10'
}

**Comment by jitpack-io** [comment]
Hi

Fixed it and rebuilt 0.5.7!

**Comment by deviant-studio** [comment]
https://jitpack.io/com/github/deviant-studio/rxcontacts/-0.1-ge65113e-2/build.log
same issue

**Comment by jitpack-io** [comment]
@deviant-studio RxContacts repo is missing the ./gradlew and ./gradlew.bat scripts. They will get generated by running `gradle wrapper`
