### ISSUE TITLE
failed to find target with hash string 'android-23' in: /opt/android-sdk-linux

### ISSUE THREAD

**Issue by yangtianzheng** [jitpack/jitpack.io#3763]
Please provide:

- Link to build log from https://jitpack.io

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?

- What error are you seeing?

Thank you!

- [ ]

**Comment by jitpack-io** [comment]
Hi,

Would recommend using custom commands to install android-23 before the build
