### ISSUE TITLE
dbachelder/CreditCardEntry 1.4.7 build suceess but cannot be pulled

### ISSUE THREAD

**Issue by BrianOn99** [jitpack/jitpack.io#3764]
Please provide:

- Link to build log from https://jitpack.io
https://jitpack.io/com/github/dbachelder/CreditCardEntry/1.4.7/build.log

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?
Yes

- What error are you seeing?
There is no build error, but the aar link https://jitpack.io/com/github/dbachelder/CreditCardEntry/1.4.7/CreditCardEntry-1.4.7.aar shows this: 
`Build failed. See the log at jitpack.io`

My project has been using the version 1.4.7 for a long time in the past with no issue.

Thank you!

**Comment by jitpack-io** [comment]
Hi,

Should be available now.
