### ISSUE TITLE
why"BUILD SUCCESSFUL" is also failed?

### ISSUE THREAD

**Issue by GzxdH** [jitpack/jitpack.io#3766]
Build starting...
Start: Fri Mar 8 05:08:56 UTC 2019 7d8a1dbc0b14
Git:
1.0.2-0-gf7478a5
commit f7478a554e11950792b95591af811e6a29243e5d
Author: 张伟 
Date:   Fri Mar 8 13:00:19 2019 +0800

    修改无法运行的问题

Found Android manifest
Android SDK version: 28. Build tools: 
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2
Warning: File /opt/android-sdk-linux/.android/repositories.cfg could not be loaded.

Installing Android platform 28
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2
Warning: File /opt/android-sdk-linux/.android/repositories.cfg could not be loaded.
Found gradle
Gradle build script
Using gradle wrapper
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2
Downloading https://services.gradle.org/distributions/gradle-4.6-all.zip
.
Unzipping /home/jitpack/.gradle/wrapper/dists/gradle-4.6-all/bcst21l2brirad8k2ben1letg/gradle-4.6-all.zip to /home/jitpack/.gradle/wrapper/dists/gradle-4.6-all/bcst21l2brirad8k2ben1letg
Set executable permissions for: /home/jitpack/.gradle/wrapper/dists/gradle-4.6-all/bcst21l2brirad8k2ben1letg/gradle-4.6/bin/gradle

------------------------------------------------------------
Gradle 4.6
------------------------------------------------------------

Build time:   2018-02-28 13:36:36 UTC
Revision:     8fa6ce7945b640e6168488e4417f9bb96e4ab46c

Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.9 compiled on February 2 2017
JVM:          1.8.0_191 (Oracle Corporation 25.191-b12)
OS:           Linux 4.10.0-28-generic amd64

Getting tasks: ./gradlew tasks --all
0m4.300s
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2
Tasks: install,
Running: ./gradlew clean -Pgroup=com.github.GzxdH -Pversion=1.1.0 -xtest -xlint install
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2
:clean UP-TO-DATE
:app:clean UP-TO-DATE
:app:install

BUILD SUCCESSFUL in 0s
3 actionable tasks: 1 executed, 2 up-to-date
Looking for artifacts...
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2
Looking for pom.xml in build directory and ~/.m2
EXIT_CODE=0
2019-03-08T05:09:24.691079066Z
Exit code: 0
No build artifacts found

How can I solve it?please help me~thank~

**Comment by jitpack-io** [comment]
As the log says: 
```
Looking for pom.xml in build directory and ~/.m2
No build artifacts found
```

Probably no artifacts were published to local maven repository ~/.m2.
Would recommend following steps in the documentation and configure Gradle to publish artifacts.
