### ISSUE TITLE
Android library artifacts not available anymore

### ISSUE THREAD

**Issue by Steppschuh** [jitpack/jitpack.io#3770]
Builds for the [BLE Indoor Positioning Android Library](https://github.com/neXenio/BLE-Indoor-Positioning) on JitPack indicate that something went wrong, however the build log is not showing any errors. Artifacts that have previously been served through JitPack are suddenly not available anymore (e.g. [0.3.8](https://jitpack.io/#neXenio/BLE-Indoor-Positioning/0.3.8)), without any changes.

Neither [Travis CI](https://travis-ci.org/neXenio/BLE-Indoor-Positioning/branches) nor [Codecov](https://codecov.io/gh/neXenio/BLE-Indoor-Positioning/commits) is having any issues. Here is the related issue in the BLE Indoor Positioning repository: neXenio/BLE-Indoor-Positioning#147

- [Link to build log](https://jitpack.io/com/github/neXenio/BLE-Indoor-Positioning/9ede486/build.log)

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install)?
Yes.

- What error are you seeing?

```
BUILD SUCCESSFUL in 5s
10 actionable tasks: 7 executed, 3 up-to-date
Looking for artifacts...
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2
Looking for pom.xml in build directory and ~/.m2
Found artifact: com.github.neXenio:BLE Indoor Positioning:9ede486
EXIT_CODE=0
2019-03-11T15:17:15.649730029Z
Exit code: 0
No build artifacts found
```

```
Could not resolve com.github.neXenio:BLE-Indoor-Positioning:0147-jitpack-not-serving-artifacts-SNAPSHOT
```

**Comment by mantono** [comment]
We are seeing the same pattern [with a build](https://jitpack.io/com/github/zensum/gocardless-pro-java/b7c0e9c05e/build.log).
>BUILD SUCCESSFUL in 5s
7 actionable tasks: 6 executed, 1 up-to-date
Looking for artifacts...
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2
Looking for pom.xml in build directory and ~/.m2
Found artifact:  com.gocardless:gocardless-pro:3.7.3
EXIT_CODE=0
2019-03-11T16:11:11.896592293Z
Exit code: 0
No build artifacts found

**Comment by jitpack-io** [comment]
Hi @Steppschuh ,

There seems to be an issue processing artifacts with spaces in the name:
 `com.github.neXenio:BLE Indoor Positioning:9ede486`
Looking into it

**Comment by jitpack-io** [comment]
Should be fixed now. Rebuilt versions 9ede486 and 0.3.8

**Comment by Steppschuh** [comment]
It's fixed, thanks for your fast response.
