### ISSUE TITLE
com.github.Cutta/GifView is not build failed

### ISSUE THREAD

**Issue by vanatka** [jitpack/jitpack.io#3771]
- Link to build log from https://jitpack.io
the one error message I've is:
https://jitpack.io/com/github/Cutta/GifView/1.1/GifView-1.1.aar

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?
it's impossible to get library from jitpack.io, project does not compile

- What error are you seeing?
https://jitpack.io/com/github/Cutta/GifView/1.1/GifView-1.1.aar
Build failed. See the log at jitpack.io

**Comment by jitpack-io** [comment]
Hi,

Seems like the right build tools version is not installed:
https://jitpack.io/com/github/Cutta/GifView/1.1/build.log
`> failed to find Build Tools revision 23.0.3`

JitPack is detecting the build tools in app/ folder and installing that.
Will have a look how we can fix it.
If you have access to the repo you could install correct build tools using custom commands.
