### ISSUE TITLE
Received status code 502 from server: Bad Gateway

### ISSUE THREAD

**Issue by wenchaosong** [jitpack/jitpack.io#3786]
Please provide:

- Link to build log from https://jitpack.io
https://jitpack.io/com/github/wenchaosong/Banner/2.3.6/build.log

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?
No,my AndroidStudio is run success with ./gradlew install

- What error are you seeing?
Received status code 502 from server: Bad Gateway

Thank you!

**Comment by jitpack-io** [comment]
Hi,

Seems like the tag 2.3.6 no longer exists.

**Comment by wenchaosong** [comment]
@jitpack-io  I deleted, but it was appear yesterday, you can see build not release
