### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by nabriski** [jitpack/jitpack.io#3787]
Please provide:

- Link to build log from https://jitpack.io
https://jitpack.io/com/github/mobfox/MobFox-Android-SDK-Core/3.6.9cd/build.log

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?
Yes

- What error are you seeing?
```
ERROR: Failed to resolve: com.github.mobfox
Affected Modules: app
```

**Comment by jitpack-io** [comment]
Hi,

Rebuilt

**Comment by nabriski** [comment]
thanks
