### ISSUE TITLE
build OK but not found

### ISSUE THREAD

**Issue by ligi** [jitpack/jitpack.io#3788]
I am facing a problem with jitpack currently - the build worked OK:

https://jitpack.io/com/github/walleth/kethereum/0.74.0/build.log

but the artifacts are not found:

https://jitpack.io/com/github/walleth/kethereum/functions/0.74.0/functions-0.74.0.pom

in contrast:

https://jitpack.io/com/github/walleth/kethereum/0.73.3/build.log

and

https://jitpack.io/com/github/walleth/kethereum/functions/0.73.3/functions-0.73.3.pom

**Comment by ligi** [comment]
worked around the problem by adding a new tag to the very same commit

**Comment by ligi** [comment]
PS - gradle 5.3 was not the reason - had the issue also after the revert. Just thought so as I did not have issues before migrating to 5.3 - but this was just correlation no causation

**Comment by jitpack-io** [comment]
Found the issue and those files should be available now.

**Comment by ligi** [comment]
@jitpack-io having the issue again - now for a build that is not under my control so I cannot work around it by tagging a new version:

https://jitpack.io/com/github/status-im/status-keycard-java/2.2.1/build.log

cc @bitgamma

**Comment by ligi** [comment]
ah - nevermind the build appeared now - but looked like the same error
