### ISSUE TITLE
Failed to resolve: com.github.Todd-Davies:ProgressWheel:1.2

### ISSUE THREAD

**Issue by softdev919** [jitpack/jitpack.io#3789]
Failed to resolve: com.github.Todd-Davies:ProgressWheel:1.2  in android studio. 
![Screen Shot 2019-03-22 at 2 25 33 AM](https://user-images.githubusercontent.com/13697648/54813024-d1effb80-4c49-11e9-824c-d733e93481c2.png)

**Comment by jitpack-io** [comment]
There is an issue with the build: https://jitpack.io/com/github/Todd-Davies/ProgressWheel/1.2/build.log

**Comment by mobiledeveloper90** [comment]
How can i resolve it ?  Please guide me.
