### ISSUE TITLE
Add support for latest version via "+"

### ISSUE THREAD

**Issue by haibison** [jitpack/jitpack.io#379]
Would you please add support for latest version via `+`?

For example:

```gradle
compile 'com.test:library:+'
```

Currently it doesn't work.

---

Suggestion: I think you can support latest version `+` with projects providing tag names which follow [Semantic Versioning]. So you can parse the tags and get the latest version from them.

Thank you  `:-)`

[Semantic Versioning]: http://semver.org/

**Comment by jitpack-io** [comment]
Hi

Thanks for the suggestion! That should already be working but only for versions that have already been built. 
When you use `+` version then gradle will request `https://jitpack.io/com/github/:user/:repo/maven-metadata.xml` file to find the latest version and JitPack should provide those files. 
Which library doesn't it work for? Can have a closer look

**Comment by haibison** [comment]
Thank you, that's great.

Actually I've published my first version of my library, then used `+` right away. So because of nothing was built, it didn't work.

I tried again, and it worked perfectly.

Thank you, have a nice week  `:-)`
