### ISSUE TITLE
Build is marked as successful but the artifacts are not  found

### ISSUE THREAD

**Issue by NipunaRanasinghe** [jitpack/jitpack.io#3791]
Please note $subject .

- Link to build log
https://jitpack.io/com/github/NipunaRanasinghe/lsp4intellij/master-0.1.1-g9fc4603-15/build.log
https://jitpack.io/com/github/NipunaRanasinghe/lsp4intellij/improved-diagnostics-0.1.1-gfc98920-16/build.log

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?
Yes!

- What error are you seeing?
Please refer the aforementioned build.log files

Thank you!

**Comment by ligi** [comment]
seems to be the same as #3788
