### ISSUE TITLE
Multi-module syntax not resolving dependency

### ISSUE THREAD

**Issue by etiennelenhart** [jitpack/jitpack.io#3792]
I recently added a new module to my Android library project (https://github.com/etiennelenhart/Eiffel). So it now contains two modules: *eiffel* and *eiffel-test*. When using the normal syntax to download all modules with Gradle both are properly downloaded:
```Groovy
implementation 'com.github.etiennelenhart:eiffel:master-SNAPHOT'
```
However, when using the syntax to download a specific module, I'm getting a "Failed to resolve" error:
```Groovy
implementation 'com.github.etiennelenhart.eiffel:eiffel:master-SNAPHOT'
testImplementation 'com.github.etiennelenhart.eiffel:eiffel-test:master-SNAPHOT'
```

I added the following to the project level *build.gradle*:
```Groovy
buildscript {
    ...
    dependencies {
        ...
        classpath 'com.github.dcendents:android-maven-gradle-plugin:1.5'
    }
}
```
And have the following lines in the *build.gradle* files of both modules:
```Groovy
apply plugin: 'com.android.library'
apply plugin: 'com.github.dcendents.android-maven'
group = 'com.github.etiennelenhart'
```

When looking up the repository on jitpack.io (https://jitpack.io/#etiennelenhart/Eiffel) I'm also not seeing the *Subprojects* chooser. Am I doing something wrong?

**Comment by jitpack-io** [comment]
Hi,

This build seems to have both modules: https://jitpack.io/com/github/etiennelenhart/Eiffel/07ceea3/build.log
Is it working as expected now?

**Comment by etiennelenhart** [comment]
Hey, thank you for the quick reply.

It is indeed working with the newest build, although I have to explicitly use `eiffel-4.1.0` and `eiffel-test-1.0.0` as module names, which doesn't seem right.
Do I have to use the same version for both modules?

**Comment by etiennelenhart** [comment]
Dang it, it was (of course) entirely my fault.
I've been using `setProperty("archivesBaseName", "eiffel-${android.defaultConfig.versionName}")` to better distinguish the built AARs and this seems to be used to create the "subproject" name. I removed the `setProperty` statement and everything is working fine.
Thanks for your assistance.
