### ISSUE TITLE
GitLab lookup doesn't work

### ISSUE THREAD

**Issue by micheljung** [jitpack/jitpack.io#3793]
**Describe the bug**
Looking up GitLab artifacts on the main page doesn't work.

**To Reproduce**
1. Go to https://jitpack.io/#com.gitlab.jitpack-io/gradle-simple
2. Click on 'Look up'

**Expected behavior**
A result table to pop up underneath the search form.

**Screenshots**
![image](https://user-images.githubusercontent.com/1864183/54939830-d5290700-4f29-11e9-91f4-0bb803d8da03.png)

**Additional context**
GitHub lookups work just fine.

**Comment by AllanWang** [comment]
```
Access to XMLHttpRequest at 'https://github.com/login/oauth/authorize?client_id=**********&redirect_uri=https%3A%2F%2Fjitpack.io%2Fcallback%3Fclient_name%3Dgithub2&scope=repo%2Cuser%3Aemail%2Cread%3Aorg%2Cadmin%3Arepo_hook' (redirected from 'https://jitpack.io/api/refs/com.gitlab.jitpack-io/gradle-simple') from origin 'https://jitpack.io' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

Seems like everything goes through the github app now?

**Comment by axel1200** [comment]
Same problem for me with any other gitlab project

**Comment by emreakcan** [comment]
Wasted 2 hr on this, just use github

**Comment by micheljung** [comment]
Still broken I guess
