### ISSUE TITLE
Access private repo

### ISSUE THREAD

**Issue by Hala-Nearmotion** [jitpack/jitpack.io#3794]
Hi,

I always recive this message while trying to access my bitbucket private repo!
![image](https://user-images.githubusercontent.com/48942331/55056261-be43fb00-5076-11e9-978c-22d66327a3d4.png)

I followed those steps and I got the token correctly

Sign In on https://jitpack.io
Click on your username (https://jitpack.io/w/user)
Enter your Bitbucket user and App Password

Thank you!

**Comment by jitpack-io** [comment]
Hi,

What happens if you enter `org.bitbucket.halaenhab/jitpack-test` and press Look Up?

**Comment by Hala-Nearmotion** [comment]
it show me this !
![image](https://user-images.githubusercontent.com/48942331/55073672-61a90600-509f-11e9-8acd-d3d703ba2d27.png)

Although I grantee the read access while generating the app password at bitbucket
