### ISSUE TITLE
Version of the imported .aar module has changed

### ISSUE THREAD

**Issue by huunam1108** [jitpack/jitpack.io#3799]
- The log file: https://jitpack.io/com/github/huunam1108/TestJitPackLib/5.0.1_BETA/build.log

- My sample project: https://github.com/huunam1108/TestJitPackLib.git

- My scenario:

I have 3 libs modules call `base`, `core` and `stream` with dependent together like below:
  - `core` dependent to `base`
  - `stream` dependent to `base`
  - `core` need to dependent to the imported `.aar` module, in my sample is `mux-r.2.8.0`

The libs are built successful, however seem the module of the imported `aar` is changed version like other lib modules. The errors is show below:
```
ERROR: Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve com.github.huunam1108:mux-r2.8.0:5.0.1_BETA.
Show Details
Affected Modules: app


ERROR: Unable to resolve dependency for ':app@debugAndroidTest/compileClasspath': Could not resolve com.github.huunam1108:mux-r2.8.0:5.0.1_BETA.
Show Details
Affected Modules: app


ERROR: Unable to resolve dependency for ':app@debugUnitTest/compileClasspath': Could not resolve com.github.huunam1108:mux-r2.8.0:5.0.1_BETA.
Show Details
Affected Modules: app


ERROR: Unable to resolve dependency for ':app@release/compileClasspath': Could not resolve com.github.huunam1108:mux-r2.8.0:5.0.1_BETA.
Show Details
Affected Modules: app


ERROR: Unable to resolve dependency for ':app@releaseUnitTest/compileClasspath': Could not resolve com.github.huunam1108:mux-r2.8.0:5.0.1_BETA.
Show Details
Affected Modules: app
```
Can I keep the version of imported module `aar`, not `mux-r2.8.0:5.0.1_BETA` ?
How can I work with imported external `aar` lib to my lib?

Thank you!

**Comment by huunam1108** [comment]
@jitpack-io , I hope you saw my problem. :bowing_man: 
Thanks !

**Comment by jitpack-io** [comment]
Hi,

JitPack rewrites the version to match the git tag. 
For your project these dependencies are available:
```
com.github.huunam1108.TestJitPackLib:base:5.0.1_BETA
com.github.huunam1108.TestJitPackLib:core:5.0.1_BETA
com.github.huunam1108.TestJitPackLib:stream:5.0.1_BETA
```

**Comment by huunam1108** [comment]
@jitpack-io 
Thanks for your reply. 
However, as you can see when I add the `core` library to my `app` module (via jitpack), it requires the imported `aar` module (`mux-r2.8.0`), and I got error `Could not resolve com.github.huunam1108:mux-r2.8.0:5.0.1_BETA`. As expected, this is not my libs, so it should appear without `5.0.1_BETA` at the end.

**Comment by huunam1108** [comment]
I make new issue #3806 which easy to understand than this. So, close this.
