### ISSUE TITLE
Hide code of the maven repository

### ISSUE THREAD

**Issue by Hala-Nearmotion** [jitpack/jitpack.io#3800]
Is there a way to hide the source code of the generated maven repository? 

I'm using a private bitbucket repo to hide the source code, however, any one can just hit control + click over the imported class from my repo, and then he will be able to get the complete code! 

Isn't there a way to have my source code private but only the binaries public?

**Comment by jitpack-io** [comment]
Hi,

Could you please send us the URL of your repository? 
Since it is a private repository it's better to use the **Support** button on the [website](https://jitpack.io).

**Comment by jitpack-io** [comment]
Closing the issue for now.
Android Studio is able to show decompiled source code so one option is to look into ProGuard for obfuscation.
