### ISSUE TITLE
Can not use a published lib which dependent to a `.aar`

### ISSUE THREAD

**Issue by huunam1108** [jitpack/jitpack.io#3806]
- Build log: https://jitpack.io/com/github/huunam1108/DependentLib/1.0.1_BETA/build.log

- Github repo: https://github.com/huunam1108/DependentLib

- My scenario: I have a lib that dependent to a `.aar` (I used `mux-r2.8.0.aar`), I import it by **File -> New Module -> Import .JAR/.AAR Package** . After published my lib to `jitpack.io`, the app can not use it. the error log is below. Seem, imported `aar` module is changed its version to `mux-r2.8.0:1.0.1_BETA`.
```
ERROR: Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve com.github.huunam1108:mux-r2.8.0:1.0.1_BETA.
Show Details
Affected Modules: app


ERROR: Unable to resolve dependency for ':app@debugAndroidTest/compileClasspath': Could not resolve com.github.huunam1108:mux-r2.8.0:1.0.1_BETA.
Show Details
Affected Modules: app


ERROR: Unable to resolve dependency for ':app@debugUnitTest/compileClasspath': Could not resolve com.github.huunam1108:mux-r2.8.0:1.0.1_BETA.
Show Details
Affected Modules: app


ERROR: Unable to resolve dependency for ':app@release/compileClasspath': Could not resolve com.github.huunam1108:mux-r2.8.0:1.0.1_BETA.
Show Details
Affected Modules: app


ERROR: Unable to resolve dependency for ':app@releaseUnitTest/compileClasspath': Could not resolve com.github.huunam1108:mux-r2.8.0:1.0.1_BETA.
Show Details
Affected Modules: app

```
What am I wrong? How can I work with this case?

Thank you!

**Comment by huunam1108** [comment]
@jitpack-io 
Do you have any idea on this problem?

**Comment by jitpack-io** [comment]
Hi,

Seems like the mux aar file is currently not being published.
If you want to publish an existing .aar file then that can be done with a few commands in jitpack.yml. 
We have an example here:
https://gist.github.com/jitpack-io/f928a858aa5da08ad9d9662f982da983

Possibly another option could be to use Shadow plugin in order to embed mux into your own library.

**Comment by huunam1108** [comment]
@jitpack-io 
Hi, I don't want to publish the `mux.aar` file because this is not our library.
Is there a way to embed `mux.aar` into our published libs without publish it to `jitpack`?

**Comment by a914-gowtham** [comment]
> Hi,
> 
> Seems like the mux aar file is currently not being published.
> If you want to publish an existing .aar file then that can be done with a few commands in jitpack.yml.
> We have an example here:
> https://gist.github.com/jitpack-io/f928a858aa5da08ad9d9662f982da983
> 
> Possibly another option could be to use Shadow plugin in order to embed mux into your own library.

I published an aar by following that example. but aft
![Screenshot from 2021-03-16 23-38-32](https://user-images.githubusercontent.com/68514286/111358894-dd4b5580-86b0-11eb-8f76-bbcc9e3e75dd.png)
er I used the dependency url and I can't reach the classes that exist on the aar file. it doesn't even available in library folder
