### ISSUE TITLE
use it

### ISSUE THREAD

**Issue by nozuonodienobb** [jitpack/jitpack.io#3808]
Please provide:

- Link to build log from https://jitpack.io

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?

- What error are you seeing?

Thank you!

**Comment by jitpack-io** [comment]
Hi,

What is the error you are seeing? A link to build log would be helpful

**Comment by nozuonodienobb** [comment]
Build starting...
Start: Tue Apr 9 10:51:57 UTC 2019 df9381903dd4
Git:
v4.0.0-0-gf4bb037
commit f4bb0372aceeab938c25ab5d30b8e997dbfd8fac
Author: 小白天神 
Date:   Tue Apr 9 18:50:39 2019 +0800

    no message


Found Android manifest
Android SDK version: 28. Build tools: 
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2
Warning: File /opt/android-sdk-linux/.android/repositories.cfg could not be loaded.

Installing Android platform 28
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2
Warning: File /opt/android-sdk-linux/.android/repositories.cfg could not be loaded.
Found gradle
Gradle build script
Using gradle wrapper
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2
Exception in thread "main" java.lang.RuntimeException: Wrapper properties file '/home/jitpack/build/gradle/wrapper/gradle-wrapper.properties' does not exist.
	at org.gradle.wrapper.WrapperExecutor.forWrapperPropertiesFile(WrapperExecutor.java:43)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:60)
0m0.087s
Getting tasks: ./gradlew tasks --all
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2
Exception in thread "main" java.lang.RuntimeException: Wrapper properties file '/home/jitpack/build/gradle/wrapper/gradle-wrapper.properties' does not exist.
	at org.gradle.wrapper.WrapperExecutor.forWrapperPropertiesFile(WrapperExecutor.java:43)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:60)
Tasks: 

WARNING:
Gradle 'install' task not found. Please add the 'maven' or 'android-maven' plugin.
See the documentation and examples: https://jitpack.io/docs/

Adding maven plugin
Found android library build file in library
Running: ./gradlew clean -Pgroup=com.github.nozuonodienobb -Pversion=4.0.0 install
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2
Exception in thread "main" java.lang.RuntimeException: Wrapper properties file '/home/jitpack/build/gradle/wrapper/gradle-wrapper.properties' does not exist.
	at org.gradle.wrapper.WrapperExecutor.forWrapperPropertiesFile(WrapperExecutor.java:43)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:60)
Looking for artifacts...
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2
Looking for pom.xml in build directory and ~/.m2
EXIT_CODE=0
2019-04-09T10:52:09.668065595Z
Exit code: 0

ERROR: No build artifacts found

**Comment by nozuonodienobb** [comment]
dependencies {
        classpath 'com.android.tools.build:gradle:3.3.2'
        classpath 'com.github.dcendents:android-maven-gradle-plugin:2.1'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }

**Comment by nozuonodienobb** [comment]
apply plugin: 'com.android.library'
apply plugin: 'com.github.dcendents.android-maven'

group='com.github.nozuonodienobb'

**Comment by nozuonodienobb** [comment]
io solved it thankyou

**Comment by asociateapp** [comment]
hey men, how did you solve it? I'm facing the same problem! Thanx in advance

**Comment by nozuonodienobb** [comment]
> hey man, how did you solve it? I'm facing the same problem! Thanx in advance

GitHub will ignore your mainfest file. You need to upload it yourself. You can see if your mainfest file has been uploaded on github. If not, just upload it.
