### ISSUE TITLE
Is there support for HTTP self-hosted repos?

### ISSUE THREAD

**Issue by danialgoodwin** [jitpack/jitpack.io#3811]
Hi, when using the 'Look Up' functionality in jitpack.io, it appears that it automatically converts a 'http' request to 'https'. Unfortunately, that's not working for my use-case, which also includes requiring the use of a VPN.

Am I missing something, or is it currently not possible to use a HTTP URL?

**Comment by jitpack-io** [comment]
Hi,

It should be possible if you configure to use a self-hosted git server: https://jitpack.io/docs/PRIVATE/#self-hosted-git
