### ISSUE TITLE
ERROR: No build artifacts found

### ISSUE THREAD

**Issue by Darkos-den** [jitpack/jitpack.io#3814]
Hello. I make simple library from guide. The log states that the build was assembled but no artifacts were found. I do not understand what the problem is.
https://jitpack.io/com/github/Darkos-den/MustHaveExtensions/1.0.8/build.log

**Comment by hantrungkien** [comment]
@Darkos-den 
After 4 hours I found this problem by default gradlew (seems after gradle ver 4.6+) was incorrect generated. You can using my file to replace in you project.

https://github.com/hantrungkien/tinder-scarlet-lifecycle-android/blob/master/gradlew

**Comment by Darkos-den** [comment]
@hantrungkien 
After the change, an error began to appear:
>* What went wrong:
>Execution failed for task ':library:compileDebugKotlin'.
> Kotlin could not find the required JDK tools in the Java installation '/usr/lib/jvm/java-8-openjdk->amd64/jre' used by Gradle. Make sure Gradle is running on a JDK, not JRE.

How can this be solved?

**Comment by hantrungkien** [comment]
@Darkos-den 
you forgot add dependencies in your lib module
implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
:p

You also can try: https://android.github.io/android-ktx/core-ktx/

**Comment by Darkos-den** [comment]
@hantrungkien 
I added this:
>dependencies {
>    implementation fileTree(include: ['*.jar'], dir: 'libs')
>    implementation 'com.android.support:appcompat-v7:28.0.0'
>    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
>    testImplementation 'junit:junit:4.12'
>    androidTestImplementation 'com.android.support.test:runner:1.0.2'
>    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
>}

but I have the same error

**Comment by hantrungkien** [comment]
Run this command in your terminal in android studio:
./gradlew install

You can see your incorrect.
Example in your class: https://github.com/Darkos-den/MustHaveExtensions/blob/master/library/src/main/java/com/darkos/mustHaveExtensions/fragmentManager/addFragmentWithBackStackAnimDownUp.kt

**Comment by Darkos-den** [comment]
I commented it out. 
./gradlew install causes the same error. Strange but if I return the file to its original state, then there will be no error, but then there will be no artifacts.

**Comment by jitpack-io** [comment]
Hi,

Would recommend adding the 'maven' or 'android-maven' plugin then trying locally with `./gradlew install`.
See the documentation and examples: https://jitpack.io/docs/

**Comment by Yrp** [comment]
The same issue here. This is the build log. 
[build.log](https://github.com/jitpack/jitpack.io/files/3818353/build.log)

**Comment by i-schuetz** [comment]
Here too: [build.log](https://jitpack.io/com/github/Co-Epi/app-backend-rust/0.1.16/build.log)

The install command runs fine locally: `./gradlew clean -Pgroup=com.github.Co-Epi -Pversion=0.1.16 -xtest -xlint install`

It's the part with "Looking for artifacts..." that fails, and I can't reproduce it locally since the log doesn't show a command for it.

**Comment by MarcoCiaramella** [comment]
Try following the jitpack [example](https://github.com/jitpack/android-example)

**Comment by seljabali** [comment]
In working on a [Kotlin library](https://github.com/seljabali/java-time-fun), using Gradle 7.1, the following did the trick for me:

root `build.gradle`:
```gradle
plugins {
    id 'maven-publish'
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            groupId = 'foo'
            artifactId = 'bar'
            version = '0.1'

            from components.java
        }
    }
}
```

**Comment by AndroidDeveloperLB** [comment]
@seljabali Shouldn't it be:

```
plugins {
    id 'com.android.library'
    id 'kotlin-android'
    id 'maven-publish'
}

...
android {
    afterEvaluate {
        publishing {
            publications {
                release(MavenPublication) {
                    from components.release
                }
            }
        }
    }
```

?

**Comment by seljabali** [comment]
What I had placed @AndroidDeveloperLB was for a java/kotlin project and not an Android one.

**Comment by AndroidDeveloperLB** [comment]
@seljabali OK no idea in this case, but I think you could remove the parts of `groupId = 'foo',artifactId = 'bar',version = '0.1'` .

**Comment by EnthuDai** [comment]
> @seljabali Shouldn't it be:
> 
> ```
> plugins {
>     id 'com.android.library'
>     id 'kotlin-android'
>     id 'maven-publish'
> }
> 
> ...
> android {
>     afterEvaluate {
>         publishing {
>             publications {
>                 release(MavenPublication) {
>                     from components.release
>                 }
>             }
>         }
>     }
> ...
> ```
> 
> ?

YES!!! It works on my project!!! The question puzzled me for several days.Thanks very much.

**Comment by AndroidDeveloperLB** [comment]
@EnthuDai I still don't understand why we need this. We didn't need it in the past, and now this weird thing I've found somewhere. I don't even understand what it's doing...
