### ISSUE TITLE
Unable to resolve dependency 

### ISSUE THREAD

**Issue by Hala-Nearmotion** [jitpack/jitpack.io#3815]
Hi,

I'm using JitPack to publish a private repo on BitBucket. 

I always get this error. (Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve org.bitbucket.halaehab:SundaySDKv1:-SNAPSHOT.) 

It was working fine before but now it just stooped. 

I tried to Deselect the "Offline work" from the File\Settings\Gradle but it didn't work too

I also added this to my build gradle: 
dexOptions { matchingFallbacks = ['release', 'debug'] } . 
It was my old solution to handle this error but now it doesn't work!

I'm facing this problem with all of my projects. Even the projects that were working before. 

Any solution?

Thank you!

**Comment by acmeuno** [comment]
Same problem here...

**Comment by adsi1407** [comment]
Some problem. Some idea to solve this problem?

**Comment by jitpack-io** [comment]
Hi @Hala-Nearmotion 

It seems that the App Password in your settings are now being rejected by Bitbucket. 
Would recommend checking it or creating a new App Password and then trying to see the releases on here:
https://jitpack.io/#org.bitbucket.halaehab/SundaySDKv1

Another way to check if the password is working is to run this command: 
`git ls-remote https://halaehab:<APP_PASSWORD>@bitbucket.org/halaehab/SundaySDKv1`

**Comment by tulioccalazans** [comment]
Now it is free only for public repositories...
If you put your repository url in [https://jitpack.io](https://jitpack.io) and looked up, you will see the following message as log:

`Subscription not active`
