### ISSUE TITLE
`Make` is missing

### ISSUE THREAD

**Issue by hypest** [jitpack/jitpack.io#3818]
Please provide:

- Link to build log from https://jitpack.io: https://jitpack.io/com/github/wordpress-mobile/gutenberg-mobile/e7bf7987b362e155de1d4bfa823494e9fc315d0b/build.log

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ? **YES**

- What error are you seeing?

Building the `node-sass` NPM module fails because `make` is not available on JitPack.

```
gyp ERR! build error 
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError (/home/jitpack/build/node_modules/which/which.js:13:12)
gyp ERR! stack     at F (/home/jitpack/build/node_modules/which/which.js:68:19)
gyp ERR! stack     at E (/home/jitpack/build/node_modules/which/which.js:80:29)
gyp ERR! stack     at /home/jitpack/build/node_modules/which/which.js:89:16
gyp ERR! stack     at /home/jitpack/build/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /home/jitpack/build/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Linux 4.14.63-xxxx-std-ipv6-64
gyp ERR! command "/tmp/jsbundle/e7bf7987b362e155de1d4bfa823494e9fc315d0b/nodejs/node-v8.11.3-linux-x64/bin/node" "/home/jitpack/build/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /home/jitpack/build/node_modules/node-sass
gyp ERR! node -v v8.11.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
```

Thank you!

**Comment by jitpack-io** [comment]
Hi,

Would it be possible to install `make` before the build with custom commands? 
https://jitpack.io/docs/BUILDING/#custom-commands

**Comment by hypest** [comment]
> Would it be possible to install make before the build with custom commands?

Oh, I was under the impression that we can't install OS packages on the virtual machine.

[Last time I tried to](https://jitpack.io/com/github/wordpress-mobile/gutenberg-mobile/d303afcd4d/build.log) I got this error:
```
E: Could not open lock file /var/lib/dpkg/lock-frontend - open (13: Permission denied)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), are you root?
```

Any special way we need to follow to be able to install packages?

By the way, we could try to install `make` by fetching some binary from the net but chances are that more packages (build-essentials perhaps) might be needed after getting `make` in so, I feel that the `apt install` way will be the most practical.

**Comment by jitpack-io** [comment]
Hi,

Indeed, it'd be better to install make using `apt` so we'll do that.

**Comment by vic** [comment]
Hello @jitpack-io,

I'm having a similar issue (trying to install some dependencies via [asdf](https://asdf-vm.com) which depends on `jq` and `column` (from `util-linux`) being present on the system. I tried adding 

```
before_script:
  - apt-get install jq
```

But get the same permission error since the process is run as user `jitpack`, is there a way to install system dependencies on jitpack? 


Perhaps we could have the jitpack image with `sudo` installed and allow the jitpack user to run `sudo apt-get`?

**Comment by pfichtner** [comment]
Trying to do the same. Calling ```apt-get``` results in ```E: Could not open lock file /var/lib/dpkg/lock-frontend - open (13: Permission denied)```. 
With prefixed ```sudo``` I got ```/script/buildit.sh: line 41: sudo: command not found```

**Comment by cnixbtc** [comment]
@jitpack-io Was this ever resolved? I'm currently facing the same problem as @vic. Can't install anything using `apt-get` since I don't have permissions and cannot use `sudo`.
