### ISSUE TITLE
what ERROR: No build artifacts found ? 

### ISSUE THREAD

**Issue by lua14** [jitpack/jitpack.io#3822]
New feature requests are very welcome!

If submitting a build issue please provide:
 1. Link to build log from https://jitpack.io 
 2. Does the project build on your machine with the same commands?
 3. What error are you seeing?

Thank you!

https://jitpack.io/com/github/lua14/ReGame/TTP/build.log

**Comment by RDIL** [comment]
Do you have a `build.gradle`, `pom.xml`, etc. in the base repository folder?

**Comment by drdrej** [comment]
same problem. and yes, i have pom.xml in my repo!

**Comment by drdrej** [comment]
> New feature requests are very welcome!
> 
> If submitting a build issue please provide:
> 
>     1. Link to build log from https://jitpack.io
> 
>     2. Does the project build on your machine with the same commands?
> 
>     3. What error are you seeing?
> 
> 
> Thank you!
> 
> https://jitpack.io/com/github/lua14/ReGame/TTP/build.log

I think you have missed to release/tag the project in github.

**Comment by Hammurabi** [comment]
This issue is still persisting, I'm having the same exact output in the log files from this project:
https://github.com/hammurabi/p2p4j

**Comment by RDIL** [comment]
@jitpack-io

**Comment by Hammurabi** [comment]
fixed my issue by looking at https://github.com/jitpack/maven-modular
make sure to double-check your poms!

**Comment by jitpack-io** [comment]
`No build artifacts found` can happen in multiple scenarios:
- If the build fails
- If there are no pom.xml or .pom files in build directory
- If artifacts are not copied to `$HOME/.m2/...`

@drdrej There's a build error: `.mvn/wrapper/maven-wrapper.jar: No such file or directory`
