### ISSUE TITLE
Build not working. It does not generate log.

### ISSUE THREAD

**Issue by Pabloku** [jitpack/jitpack.io#3824]
Please provide:

- Link to build log from https://jitpack.io
It should be https://jitpack.io/org/bitbucket/snowstorm/wallbox-android-sdk/2019.4.23.dev1/build.log but it is not generated

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?
Yes

- What error are you seeing?
The problem is that I start seeing the loading in the log column in the web but it seems it does not generate it.

Thank you!

**Comment by jitpack-io** [comment]
Hi,

Is that a private repository?
If it is then it requires a bit of configuration https://jitpack.io/docs/PRIVATE/#bitbucket

**Comment by Pabloku** [comment]
The problem was a dependency to a private repository submodule... Thanks!
