### ISSUE TITLE
Jitpack forces TLS 1.2

### ISSUE THREAD

**Issue by ThadHouse** [jitpack/jitpack.io#3842]
We have an artifact server that uses TLS 1.0 (we are trying to update it, but we don't own the server the files are hosted on), and whenever anyone tries to use a library using our dependencies on jitpack it fails. It looks like jitpack by default adds `-Dhttps.protocols=TLSv1.2` to the `JAVA_TOOL_OPTIONS`. This causes the following failure

`The server selected protocol version TLS10 is not accepted by client preferences [TLS12]`

Even though the builds work fine locally? Is there anyway to set this option in the jitpack build? We have a few very confused users, because this worked a few weeks ago, then our web host added the TLS 1.0 cert and things are now breaking.

Here's one of the build logs
https://javadoc.jitpack.io/com/github/HillelCoates/freezylib/-4ff54737e5-1/build.log

**Comment by jitpack-io** [comment]
Hi,

One workaround is to build using custom commands:
https://jitpack.io/docs/BUILDING/#custom-commands

and put `export JAVA_TOOL_OPTIONS="-Dfile.encoding=UTF-8"` as the first command. That should override our default.
