### ISSUE TITLE
openjdk12 is not supported (falls back to JDK 8)

### ISSUE THREAD

**Issue by msgilligan** [jitpack/jitpack.io#3845]
Please provide:

- Link to build log from https://jitpack.io

https://jitpack.io/com/github/ConsensusJ/bitcoinj/consensusj-master-supernaut-v0.12-g29f8431-1362/build.log

NOTE: Part of the build is dependent on the JDK version and is skipped when run with an earlier version. So although the output looks successful an important Gradle subproject was skipped.

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?

Yes. If I'm running under JDK 12 **all** modules build, but when I'm running under JDK 11 JavaDoc fails due to:
https://bugs.openjdk.java.net/browse/JDK-8208269

- What error are you seeing?

It seems that `openjdk12` is not found so it reverts to the default JDK 8, see the JVM version listed in the output below: 

```
------------------------------------------------------------
Gradle 5.4.1
------------------------------------------------------------

Build time:   2019-04-26 08:14:42 UTC
Revision:     261d171646b36a6a28d5a19a69676cd098a4c19d

Kotlin:       1.3.21
Groovy:       2.5.4
Ant:          Apache Ant(TM) version 1.9.13 compiled on July 10 2018
JVM:          1.8.0_191 (Oracle Corporation 25.191-b12)
OS:           Linux 4.14.63-xxxx-std-ipv6-64 amd64

```

Thank you!

**Comment by msgilligan** [comment]
For reference, here is a "successful" build with the workaround of specifying JDK 11 and disabling the JavaDoc portion of the build.

**Comment by jitpack-io** [comment]
Hi,

Indeed, there is no JDK 12 available yet on JitPack.
For the time being perhaps it can be installed before the build using custom commands:
https://jitpack.io/docs/BUILDING/#custom-commands

**Comment by utybo** [comment]
Anything new on this?

**Comment by jitpack-io** [comment]
Hi all,

JDK12 is now available on JitPack and can be specified using jitpack.yml:
```
jdk:
  - openjdk12
```

**Comment by wdavies973** [comment]
Is JDK 14 supported yet?

**Comment by pcantrell** [comment]
Is there a list of supported JDK versions published somewhere? I searched for that before finding this issue.
