### ISSUE TITLE
Downloads API not responsive

### ISSUE THREAD

**Issue by calebcartwright** [jitpack/jitpack.io#3849]
The [download stats API](https://jitpack.io/docs/API/#downloads) is not responsive/timing out. 

This is can be seen with any target, including the one used in the API docs: https://jitpack.io/api/stats/com.github.jitpack/gradle-modular

Would it be possible to get this API back up and stabilized, and/or is there a different API available that provides the same download stat information?

Thanks!

**Comment by jitpack-io** [comment]
Hi,

For the time being perhaps you could use the `downloads` API:
https://jitpack.io/api/downloads/com.github.jitpack/gradle-modular

**Comment by calebcartwright** [comment]
That actually looks even better! Thanks @jitpack-io
