### ISSUE TITLE
how to rebuild

### ISSUE THREAD

**Issue by MrWangChong** [jitpack/jitpack.io#3852]
I want to delete the builded version or all version ,Excuse me how to do？or I sended a should not project，but it is builded，how to delete it？

**Comment by jitpack-io** [comment]
Hi,
If you Sign In on the website then you you should be able to remove old build.

**Comment by MrWangChong** [comment]
Thank you, but when I click close it point out “Tag builds older than 7 days can't be deleted“，excuse me how to do I can delete or rebuild the project？
