### ISSUE TITLE
before can build success , but now always build failed.

### ISSUE THREAD

**Issue by xbdcc** [jitpack/jitpack.io#3855]
now error to build, but before version can build and implementation.
- log links:https://jitpack.io/com/github/xbdcc/Cutils/0.0.15/build.log
- the log message is :
```
Build starting...
Error building
```

**Comment by xbdcc** [comment]
Nothing changes, but why i publish a 0.1.0 version can success, but 0.0.15 version is always fail?
![image](https://user-images.githubusercontent.com/13348741/58541590-69fff780-822e-11e9-8740-87373cb56654.png)

**Comment by flier268** [comment]
Me too.
![image](https://user-images.githubusercontent.com/19989232/58548317-ac7c0100-823b-11e9-88a6-5dcab1a8b5c1.png)

**Comment by ESchouten** [comment]
Same issue

**Comment by jitpack-io** [comment]
Hi @xbdcc 

Deleted and re-built version 0.0.15.
As @ESchouten pointed out, you can do the same from the website.
