### ISSUE TITLE
Gradle wrapper not found

### ISSUE THREAD

**Issue by zcwipe** [jitpack/jitpack.io#3856]
Please provide:

- Link to build log from https://jitpack.io

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?

- What error are you seeing?

Thank you!

**Comment by Sergioct** [comment]
Minimum supported Gradle version is 5.1.1. Current version is 4.8.1. If using the gradle wrapper, try editing the distributionUrl in /home/jitpack/build/gradle/wrapper/gradle-wrapper.properties to gradle-5.1.1-all.zip

Always this error  :S
