### ISSUE TITLE
release fail

### ISSUE THREAD

**Issue by hellojessehao** [jitpack/jitpack.io#3859]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by hellojessehao** [comment]
release fail

**Comment by jitpack-io** [comment]
Hi,
Which project and version?

**Comment by hellojessehao** [comment]
project : hellojessehao/HandyGridView
version 1.0.0 and 1.0.1 both are error.
