### ISSUE TITLE
Build error: unable to find valid certification path

### ISSUE THREAD

**Issue by KennethWussmann** [jitpack/jitpack.io#3864]
Hey!

> Link to build log from https://jitpack.io
* https://jitpack.io/com/github/KennethWussmann/mock-fuel/1d572abdf1/build.log

> Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?

Yes the command
```
./gradlew clean -Pgroup=com.github.KennethWussmann -Pversion=1d572abdf1 install
```
runs locally. Also on Travis CI everything works fine:
https://travis-ci.org/KennethWussmann/mock-fuel/builds/543197227
(Travis CI is not running `./gradlew install` but it can download the dependency that seems to make problems on jitpack)

> What errors are you seeing?
```
> Could not GET 'https://plugins.gradle.org/m2/info/picocli/picocli/2.3.0/picocli-2.3.0.pom'.
> sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```

```
> Could not GET 'https://plugins.gradle.org/m2/org/jetbrains/kotlin/kotlin-native-utils/1.3.31/kotlin-native-utils-1.3.31.pom'.
> sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```

I can download the above files and the SSL certificate for `https://plugins.gradle.org` also looks fine.
Do you have an idea what the problem could be?

Thank you,
Kenneth

**Comment by jitpack-io** [comment]
Hi,

It seems one of our servers has trouble connecting to plugins.gradle.org. We have contacted their support.

**Comment by jitpack-io** [comment]
Do you require Java 10 for this project?

**Comment by KennethWussmann** [comment]
No, Java 8 is enough

**Comment by jitpack-io** [comment]
The issue is that the build runs with Java 10 which doesn't have all the same certificates.
https://stackoverflow.com/questions/53246399/jdk8-jdk10-pkix-path-building-failed-suncertpathbuilderexception-unable-to

We are going to fix it for Java 10 but you could also add a jitpack.yml to specify Java 8 https://jitpack.io/docs/BUILDING/#custom-commands

**Comment by jitpack-io** [comment]
Fixed: https://jitpack.io/com/github/KennethWussmann/mock-fuel/1d572abdf1/build.log

**Comment by KennethWussmann** [comment]
Awesome, thanks for the fast fix!

**Comment by hstr0100** [comment]
We're currently having a similar issue consistently reproducible across multiple devices exclusively with the armhf 32bit version of AdoptOpenJDK 11 on debian based distros.

`Could not resolve dependencies for project x: Failed to collect dependencies at x: Failed to read artifact descriptor for x: Could not transfer artifact x from/to jitpack.io (https://jitpack.io): PKIX path validation failed: java.security.cert.CertPathValidatorException: signature check failed: Signature does not match.`

on 64bit arm, and x86_64 OpenJDK the build succeeds just fine.
I do believe this is a issue with the JDK itself, but I'm reporting it here just for sake of awareness as I didn't find any recent reports whatsoever about this specific issue.
