### ISSUE TITLE
I can't find my new tag

### ISSUE THREAD

**Issue by adxcorp** [jitpack/jitpack.io#3865]
Hi, I've added a new tag for build and release, but I can't see my new tag at your dashboard.

[](https://jitpack.io/#adxcorp/ADXLibrary_Android)

And, I need 1.13.2.3 build, but your system can't find 1.13.2.3 tag.

![image](https://user-images.githubusercontent.com/24836078/59177337-bd5f3780-8b96-11e9-9201-1f49fa7b6028.png)

[](https://jitpack.io/com/github/adxcorp/ADXLibrary_Android/1.13.2.3/build.log)

Can you check it?

Best,
Chiung Choi.

**Comment by jitpack-io** [comment]
Hi,

The tag is available to download:
https://jitpack.io/com/github/adxcorp/ADXLibrary_Android/1.13.2.3/build.log

But it doesn't show on the dashboard because it only shows the top 5 versions.

**Comment by Albinzr** [comment]
We are still having this issue
