### ISSUE TITLE
Subscription not active

### ISSUE THREAD

**Issue by vetsplusmore** [jitpack/jitpack.io#3866]
Please provide:

- Link to build log from https://jitpack.io
https://jitpack.io/org/bitbucket/Invision-006/vetsframework/2.4/build.log

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?
no

- What error are you seeing?
Could not GET 'https://www.jitpack.io/org/bitbucket/Invision-006/vetsframework/vetsframeworklibrary/2.4/vetsframeworklibrary-2.4.pom'. Received status code 403 from server: Forbidden

Hi, i have already bought the subscription but still i am getting 403 from server on my private repo, and also i am getting this error "Subscription not active" on checking repo logs on jitpack

Thank you!
@jitpack-io

**Comment by jitpack-io** [comment]
Hi,

Should be working now.

**Comment by vetsplusmore** [comment]
okay thanks it's working now, Wondering why it was not working before?

**Comment by jitpack-io** [comment]
The subscription wasn't properly linked to build from bitbucket.org/invision-006 repositories.
Glad it is working for you now!

**Comment by sam43** [comment]
@jitpack-io , I accidently **cancelled** the project from here [https://jitpack.io/w/user#](https://jitpack.io/w/user#)
<img width="1177" alt="Screen Shot 2021-08-17 at 11 03 39 PM" src="https://user-images.githubusercontent.com/4275505/129769684-cacd8cd0-c6bb-4a2c-8e90-5f714bae333e.png">
Now, I am unable to **Active** the project again. What should I do to **Active** it again? Please let me know. Thanks

**Comment by sam43** [comment]
@jitpack-io how can I add another private repo to the subscription?

**Comment by tauseeq-grace** [comment]
Check out this @sam43  i have done this Solution
