### ISSUE TITLE
smoney-java-client/release~16.01u1 build

### ISSUE THREAD

**Issue by 0xbaadf00d** [jitpack/jitpack.io#387]
Hi,

compilation fail on Jitpack but work on local computer (tested with mvn 3.x / Java 8u66 on Linux and Windows)

Log https://jitpack.io/com/github/payintech/smoney-java-client/release~16.01u1/build.log

**Comment by jitpack-io** [comment]
Hi!

The build failed because JitPack is building the project with Java 7 and there is a call to a Java 8 method.  It picks the Java version from pom.xml https://github.com/payintech/smoney-java-client/blob/master/pom.xml#L73

**Comment by 0xbaadf00d** [comment]
Hi,

any chance to upgrade JitPack.IO to Java (or OpenJDK) 8 ?

**Comment by jitpack-io** [comment]
It's possible to build with Java 8 If you change the pom.xml. Just set the source/target version to 1.8 in these lines https://github.com/payintech/smoney-java-client/blob/master/pom.xml#L73.
Would that work for you?

**Comment by 0xbaadf00d** [comment]
Ok thanks for helping. We will modify the file to fix compilation on your service.
