### ISSUE TITLE
Git error. Retrying.

### ISSUE THREAD

**Issue by TJHello** [jitpack/jitpack.io#3873]
Git error. Retrying.
Git error. https://gitee.com/tjbaobao/GoogleBilling.git: cannot open git-upload-pack

**Comment by jitpack-io** [comment]
Hi,

Which version was it that produces this error?

**Comment by zzhhz** [comment]
Git error. Retrying.
Git error. https://gitee.com/zzhhz/ViewUpdater.git: cannot open git-upload-pack

version 1.1.0
