### ISSUE TITLE
missing ANDROID_NDK variable

### ISSUE THREAD

**Issue by hannesa2** [jitpack/jitpack.io#3875]
- Link to build log from https://jitpack.io
https://jitpack.io/com/github/hannesa2/android-database-sqlcipher/4.2.0.0/build.log

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?
Yes, it works on Travis

- What error are you seeing?
>ANDROID_NDK_ROOT environment variable not set, set and rerun

In `.travis.yaml` I've set this variable https://github.com/hannesa2/android-database-sqlcipher/blob/6ab61dc90a36d62fd57c62c446fba9d9315a6bd1/.travis.yml#L37 

What I've to do, to make it work, that jitpack.io knows this variable too ?

**Comment by hannesa2** [comment]
I made here https://github.com/jitpack/android-example/issues/20 an issue too

**Comment by hannesa2** [comment]
Can I set this ANDROID_NDK anyhow, or is there a similar variable ? 
How/Where can I ask, which NDK is used currently by Jitpack ? A url, or similar ?

**Comment by jitpack-io** [comment]
Hi,

At the moment JitPack sets a `NDK_HOME` variable. We'll be setting `ANDROID_NDK_ROOT` too.

**Comment by hannesa2** [comment]
Thank you for you fast answer.
It's nice to set an additional variable `ANDROID_NDK_ROOT` but unfortunately it will not solve my issue, because I'm forced to use a specific NDK (That's why there is such a variable).
Is there a way to set anyhow the usage of NDK 15c, or can I anyhow change build process to do so ?

**Comment by jitpack-io** [comment]
sdkmanager is available on the build server that you could call from jitpack.yml:
```yml
before_install:
 - yes | $ANDROID_HOME/tools/bin/sdkmanager "<PACKAGES>"
```
to install specific packages from Android SDK.
Would that help?

**Comment by phildow** [comment]
Re-opening this issue. I'm trying to build on jitpack with a specific version of the NDK. I have a jitpack.yml file calling jitpack.sh script that downloads the required NDK using the sdkmanager according to the above instructions:

```yml
before_install: 
  ./jitpack.sh
```

```sh
NDK_VERSION=19.2.5345600

echo "Installing NDK ${NDK_VERSION}"
yes | $ANDROID_HOME/tools/bin/sdkmanager --install "ndk;${NDK_VERSION}"
# sdkmanager --install "ndk;${NDK_VERSION}"

export ANDROID_NDK_HOME=$ANDROID_HOME/ndk/${NDK_VERSION}
export NDK_HOME=$ANDROID_HOME/ndk/${NDK_VERSION}
```

The logs show that the sdk manager does in fact download NDK 19.2.5345600 and unzip it. In my build.gradle file I explicitly set android.ndkVersion to "19.2.5345600". However, when the build step begins it errors out with the following message:

```
Requested NDK version 19.2.5345600 did not match the version 21.1.6352462 requested by ndk.dir at /opt/android-sdk-linux/ndk-bundle
```

You'll notice I try to resolve this by exporting ANDROID_NDK_HOME and NDK_HOME to where I expect the side-by-side ndks to be, but I continue to see the same build error, and no matter what I try I cannot get ndk.dir to point at the right NDK or the build system to recognize that I have installed NDK 19.2.5345600. You can find the complete log here:

https://jitpack.io/com/github/doc-ai/tensorio-tensorflow-android/0.1.1/build.log

It is still not clear how I can let the build system know where NDK 19.2.5345600 is installed and actually use that NDK for a build.

**Comment by feresr** [comment]
+1 Having the same problem

**Comment by hannesa2** [comment]
> Requested NDK version 19.2.5345600 did not match the version 21.1.6352462 requested

Often this error disappear by using most recent stable Android Studio. (I forgot which version exactly removes this build error)

**Comment by feresr** [comment]
The error only happens when building in Jitpack CI (builds ok locally in my machine)
Which makes me think jitpack creates a local.properties file and defines `ndk.dir` in there (but honestly I have no idea what I'm talking about)

**Comment by hannesa2** [comment]
What's about to simple delete this line  ? https://github.com/doc-ai/tensorio-tensorflow-android/blob/b98f9be41a9f976c8b20ce228fee5db7d2b875c8/javaexample/build.gradle#L6

**Comment by feresr** [comment]
If remove this line I get an (seemingly) unrelated issue. But then again, only in jitpack, works ok locally. I might look into publishing the artifacts myself.

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeDexRelease'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.DexMergingTaskDelegate
   > There was a failure while executing work items
      > A failure occurred while executing com.android.build.gradle.internal.tasks.DexMergingWorkAction
         > com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: 
           Type com.feresr.shaded.BuildConfig is defined multiple times: /home/jitpack/build/app/build/intermediates/project_dex_archive/release/out/com/feresr/shaded/BuildConfig.dex, /home/jitpack/build/shaded/build/.transforms/6a21bfb45885ec0997b9d48410e13be8/transformed/classes/classes.dex
```
