### ISSUE TITLE
Loading a Javadoc webpage takes about 2 minutes every time.

### ISSUE THREAD

**Issue by 64json** [jitpack/jitpack.io#3876]
**Describe the bug**
It takes about 2 minutes to load a Javadoc webpage every time. I tried both in Seoul, Korea and through VPN in Atlanta, USA. It is due to `https://javadoc.jitpack.io/org/algorithm-visualizer/tracers.java/v2.3.7/javadoc/resources/fonts/dejavu.css` returning a HTTP status code of 504 (a timeout occurred), which blocks the loading of the webpage.

**To Reproduce**
https://javadoc.jitpack.io/org/algorithm-visualizer/tracers.java/v2.3.7/javadoc/

**Expected behavior**
It should be loaded with a second or so once it got built.

**Screenshots**
<img width="995" alt="Screen Shot 2019-06-22 at 7 12 44 AM" src="https://user-images.githubusercontent.com/1618732/59953993-93264780-94bd-11e9-8b17-389e257d4293.png">

**Comment by parkjs814** [comment]
Actually, this issue is caused by a bug in Javadoc (https://bugs.openjdk.java.net/browse/JDK-8093199), but when I published the same library to Maven Central and served it on https://javadoc.io/doc/org.algorithm-visualizer/tracers-java/2.3.4, it worked fine.
