### ISSUE TITLE
Build stuck at `Build starting...`.

### ISSUE THREAD

**Issue by 64json** [jitpack/jitpack.io#3877]
Please provide:

- Link to build log from https://jitpack.io
https://jitpack.io/org/algorithm-visualizer/tracers.java/v2.3.16/build.log
https://jitpack.io/org/algorithm-visualizer/tracers.java/v2.3.13/build.log

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?
Yes.

- What error are you seeing?
It gets stuck at `Build starting...` forever. It happens very often.

Thank you!

**Comment by jitpack-io** [comment]
Hi,

At the moment it seems like those tags don't exist. Perhaps they were removed?
