### ISSUE TITLE
Build stuck at `Build starting...` #2

### ISSUE THREAD

**Issue by Frotty** [jitpack/jitpack.io#3878]
Hi, I have the same issue as this guy https://github.com/jitpack/jitpack.io/issues/3877
but unlike him I'm just trying to build commits, not a custom tag.

Project https://jitpack.io/#inwc3/wc3libs

A build https://jitpack.io/com/github/inwc3/wc3libs/fb45590af4/build.log

The commits fb45590af4 and 0a9436826a both don't work.
The build is stuck at starting but the icon indicates a finished job.
The artifact cannot be resolved by maven/gradle.

The CI for both commits succeeds: https://circleci.com/gh/inwc3/wc3libs

**Comment by jitpack-io** [comment]
Hi,

Should be fixed now.

**Comment by Frotty** [comment]
Hi, the build is fixed, but suddenly the JDK used to compile changed to 11, I need the project to target 8, otherwise it's causing problems when used as dependency
