### ISSUE TITLE
github ran-jit/tomcat-cluster-redis-session-manager build issue

### ISSUE THREAD

**Issue by smacritchie** [jitpack/jitpack.io#3883]
Please provide:

- Link to build log from https://jitpack.io
https://jitpack.io/com/github/ran-jit/tomcat-cluster-redis-session-manager/3.0.2/build.log

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?
Yes

- What error are you seeing?
Based on the jitpack log it seems like tomcat dependencies might not be resolving properly

Thank you!

**Comment by jitpack-io** [comment]
Hi,

Seems like there's a compilation error
