### ISSUE TITLE
Failed to resolve android library

### ISSUE THREAD

**Issue by Forestchong93** [jitpack/jitpack.io#3889]
- Link to build log from https://jitpack.io
https://jitpack.io/com/github/Forestchong93/AndroidSampleSDK/0.01/build.log

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?

- What error are you seeing?

Thank you!

library published in Jitpack

but when install the library from jitpack,

trigged `ERROR: Failed to resolve:`

tried #3687 (comment)  but is not working

**Comment by jitpack-io** [comment]
Hi,

The error is `Task 'install' not found in root project 'build'.`
Would recommend adding the maven or android-maven plugin.

**Comment by Forestchong93** [comment]
> Hi,
> 
> The error is `Task 'install' not found in root project 'build'.`
> Would recommend adding the maven or android-maven plugin.

Hi,
Problem Solved.
Thanks
