### ISSUE TITLE
android-viewbadger/master build

### ISSUE THREAD

**Issue by adsl99801** [jitpack/jitpack.io#389]
Log https://jitpack.io/com/github/jgilfelt/android-viewbadger/master/build.log
can't download from here .please

**Comment by jitpack-io** [comment]
Hi

Looks like that project is no longer maintained and the content is quite old. Also there are no gradle files for us to build with.
If you'd like to build it on JitPack then would recommend forking and adding gradle build files.

Hope this helps

**Comment by renaudcerrato** [comment]
@jitpack-io  is right, you can use mine instead:

```gradle
compile 'com.github.renaudcerrato:ViewPagerIndicator:2.4.1-gradle@aar'
```
