### ISSUE TITLE
CrushedPixel/PacketGate/33902a1 build issue

### ISSUE THREAD

**Issue by mmis1000** [jitpack/jitpack.io#3890]
Please provide:

- Link to build log from https://jitpack.io
https://jitpack.io/com/github/CrushedPixel/PacketGate/33902a1/build.log
- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?
Yes
- What error are you seeing?
Actually build success, but the jitpack believe it is a failed build and return 404 on all artifact
Thank you!

**Comment by jitpack-io** [comment]
Hi,

Should be working now
