### ISSUE TITLE
Java 8 projects built with 11 now

### ISSUE THREAD

**Issue by Frotty** [jitpack/jitpack.io#3895]
Hi, my builds here https://jitpack.io/com/github/inwc3/
are still "failing", because even though it's a java 8 project, it's being compiled by java 10 or 11, and setting the `flag: --release 8` doesn't seem to work.
Any way to compile with JDK 8 on jitpack now?

**Comment by jitpack-io** [comment]
Hi,

Yes, java 8 is available and can be specified using jitpack.yml https://jitpack.io/docs/BUILDING/#custom-commands

It could be picking up a hight java version from travis.yml

**Comment by Frotty** [comment]
Thanks
