### ISSUE TITLE
Gradle's publishToMavenLocal task not called

### ISSUE THREAD

**Issue by sschuberth** [jitpack/jitpack.io#3898]
Please provide:

- Link to build log from https://jitpack.io

https://jitpack.io/com/github/heremaps/oss-review-toolkit/c5d3d3964e/build.log

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?

Yes.

- What error are you seeing?

`./gradlew install` is being called although [according to the docs](https://jitpack.io/docs/BUILDING/) it should be `./gradlew publishToMavenLocal` as the project uses the `maven-publish` plugin.

Please note also [my PR](https://github.com/jitpack/jitpack.io/pull/3897) which actually fixes the name of the plugin to be `maven-publish` (not `maven-publishing`) in the docs.

**Comment by jitpack-io** [comment]
Hi,

JitPack is using `./gradlew tasks --all` to get a list of tasks and tries to find `publishToMavenLocal` in that list. It seems it couldn't find it.

**Comment by sschuberth** [comment]
Right, but the question is *why* it couldn't find it, because it's present:

```
$ ./gradlew tasks --all | grep publishToMavenLocal
analyzer:publishToMavenLocal - Publishes all Maven publications produced by this project to the local Maven cache.
cli:publishToMavenLocal - Publishes all Maven publications produced by this project to the local Maven cache.
downloader:publishToMavenLocal - Publishes all Maven publications produced by this project to the local Maven cache.
evaluator:publishToMavenLocal - Publishes all Maven publications produced by this project to the local Maven cache.
model:publishToMavenLocal - Publishes all Maven publications produced by this project to the local Maven cache.
reporter:publishToMavenLocal - Publishes all Maven publications produced by this project to the local Maven cache.
scanner:publishToMavenLocal - Publishes all Maven publications produced by this project to the local Maven cache.
spdx-utils:publishToMavenLocal - Publishes all Maven publications produced by this project to the local Maven cache.
test-utils:publishToMavenLocal - Publishes all Maven publications produced by this project to the local Maven cache.
utils:publishToMavenLocal - Publishes all Maven publications produced by this project to the local Maven cache.
```

Maybe your parsing is too strict and expects "publishToMavenLocal" to be present without a project name prefix?
