### ISSUE TITLE
Patio does not support JitPack

### ISSUE THREAD

**Issue by wviana** [jitpack/jitpack.io#39]
Patio not supporting JitPack,

more information.

http://stackoverflow.com/questions/29800449/how-to-import-patio-library-in-my-project

Maybe something about it could be done:

https://github.com/jitpack/jitpack.io/blob/master/BUILDING.md

**Comment by jitpack-io** [comment]
@wviana https://github.com/jitpack/jitpack.io/blob/master/ANDROID.md

**Comment by wviana** [comment]
Sorry, I did post the issue in the wrong repository.
