### ISSUE TITLE
Builds not generated anymore

### ISSUE THREAD

**Issue by danielpeintner** [jitpack/jitpack.io#390]
Hi,

We are working on the thingweb project (see https://github.com/thingweb) with several subprojects.

Unfortunately jitpack stopped to create the JARs.
e.g., calling gradlew for https://github.com/thingweb/thingweb-gui/blob/master/build.gradle fails.

The dependency "com.github.thingweb.thingweb:thingweb-client:master-SNAPSHOT" cannot be retrieved given that it is not build.
Note: we do have the same issues with releases.

e.g., https://jitpack.io/com/github/thingweb/thingweb/ does not show "v0.1.9" which does exist on github (see https://github.com/thingweb/thingweb/releases)

Thanks for looking into the issue!

**Comment by jitpack-io** [comment]
Hi 

Having a look. Will post updates here
Thanks!

**Comment by jitpack-io** [comment]
Should be resolved now! Sorry about the interruption.
There was an issue related to recent hardware upgrades but hopefully your builds will be faster from now on. 
Cheers

**Comment by danielpeintner** [comment]
Hi,

thanks for the quick fix!
In our past experience it always happened if someone checked in code that did not compile properly (e.g., due to API changes or so).

Anyhow.. it seems to work now.

Thanks!
