### ISSUE TITLE
Jitpack picks a different jdk and kotlin version than the ones specified

### ISSUE THREAD

**Issue by elect86** [jitpack/jitpack.io#3901]
- [Link](https://jitpack.io/com/github/kotlin-graphics/kotlin-unsigned/514405a59b/build.log) to build log

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ? Yes

- What error are you seeing?

Jdk 12 is used instead 11 and kotlin 1.3.31 instead 1.3.41 (as [specified](https://github.com/kotlin-graphics/kotlin-unsigned/blob/master/build.gradle#L3))

For the jdk, I tried either

```
jdk:
  - openjdk11
```
and
```
jdk: openjdk11
```
none has worked out

**Comment by jitpack-io** [comment]
Hi,

Thank you for raising this issue! Working on a fix

**Comment by jitpack-io** [comment]
Should be fixed now. Rebuilt and it is now using jdk11

**Comment by elect86** [comment]
jdk is right now, but kotlin is still 1.3.31..

**Comment by elect86** [comment]
@jitpack-io sorry to bother, but Jitpack keep picking a different kotlin version than the one specified
