### ISSUE TITLE
Add support for git-lfs

### ISSUE THREAD

**Issue by jitpack-io** [jitpack/jitpack.io#3905]
git-lfs should be made available on build containers.

**Comment by IMarchuk** [comment]
It will help us so much! 
We store our .aar library in GitLFS and it requires a lot of effort to make it working with Jitpack.

**Comment by andre-paraense** [comment]
@IMarchuk how did you get it working?

**Comment by IvanRomanovski** [comment]
@jitpack-io It seems that git-lfs was added to jitpack [docker image](https://github.com/jitpack/dockerfiles/commit/20ac0865f16f637bda09fcced4c533ff6b584d41), however git lfs files don't seem to be downloaded from a github repo automatically:

```
> Task :zumokit:packageReleaseResources
/opt/android-sdk-linux/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-strip: error: '/home/jitpack/build/zumokit/build/intermediates/merged_native_libs/release/out/lib/arm64-v8a/libzumocore.so': The file was not recognized as a valid object file
```

https://www.jitpack.io/com/github/zumo/zumokit-android/2.4.0/build.log

Are there some extra steps necessary to enable git lfs?
