### ISSUE TITLE
Appium java-client v7.1.0 is not available through jitpack.io

### ISSUE THREAD

**Issue by sen4ik** [jitpack/jitpack.io#3906]
Appium java-client v7.1.0 is not available as a maven dependency through jitpack.io.

Link to build log: https://jitpack.io/com/github/appium/java-client/v7.1.0/build.log

Does the project build on your machine with **the same** commands (e.g. ./gradlew install)? 
I am not appium java-client developer, I am just a guy who wants to use appium java-client v7.1.0 in my project.

**Comment by jitpack-io** [comment]
Hi,

Appium project is running the build with their own commands:
https://github.com/appium/java-client/blob/master/jitpack.yml

and, at the moment, those commands result in an error.
