### ISSUE TITLE
Android Matrix SDK build fail

### ISSUE THREAD

**Issue by bmarty** [jitpack/jitpack.io#3908]
Please provide:

- Link to build log:

 https://jitpack.io/com/github/matrix-org/matrix-android-sdk/v0.9.24/build.log

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?

Yes, but sometimes, the olm dependency, also provided by jitpack failed to be retrieved

- What error are you seeing?

```
* What went wrong:
Could not determine the dependencies of task ':matrix-sdk:compileReleaseKotlin'.
> Could not resolve all files for configuration ':matrix-sdk:debugRuntimeClasspath'.
   > Could not find org.matrix.gitlab.matrix-org:olm:3.1.2.
     Searched in the following locations:
       - https://jitpack.io/org/matrix/gitlab/matrix-org/olm/3.1.2/olm-3.1.2.pom
```

https://jitpack.io/org/matrix/gitlab/matrix-org/olm/3.1.2/olm-3.1.2.pom is now available, so I request a new build of project for v0.9.24 of https://jitpack.io/#matrix-org/matrix-android-sdk

Thank you!

**Comment by bmarty** [comment]
https://jitpack.io/org/matrix/gitlab/matrix-org/olm/3.1.2/olm-3.1.2.aar is not accessible, I do not understand why. Can you explain this please?

**Comment by bmarty** [comment]
Finally Olm get accessible, (I do not know why), and creating a new tag (v0.9.24.3) has forced jitpack to build again my library...

**Comment by jitpack-io** [comment]
Hi,

Seems there was a temporary (network) error. We've rebuilt that version now

**Comment by Bubu** [comment]
These temporary network errors seem to be happening more often then not. I still get
> Repository not found: https://gitlab.matrix.org/matrix-org/olm

:-(

**Comment by bahadylbekov** [comment]
OLM not accessible work right now as well. Please check

**Comment by Toni111111** [comment]
@bmarty OLM not accessible right now as well. Please check

**Comment by bmarty** [comment]
I'm still having the same issue with version 0.9.27 (see https://jitpack.io/com/github/matrix-org/matrix-android-sdk/v0.9.27/build.log) @jitpack-io .
Is the network issue coming from your side or from https://gitlab.matrix.org/matrix-org/olm ?
It's a really annoying problem, because it's break the CI build very often. How can I help to fix it?

**Comment by Toni111111** [comment]
@bmarty i just add matrix android sdk in my project.I think that this problem from https://gitlab.matrix.org/matrix-org/olm

**Comment by BillCarsonFr** [comment]
I have a repository not found (404) with https://jitpack.io/org/matrix/gitlab/matrix-org/olm/3.1.2/olm-3.1.2.jar when trying from my desktop, but I can get the jar when trying from my mobile device (on same network)

**Comment by hrj** [comment]
@BillCarsonFr Are you logged into jitpack from your mobile device, by any chance?

**Comment by BillCarsonFr** [comment]
> @BillCarsonFr Are you logged into jitpack from your mobile device, by any chance?

nop :/

**Comment by BillCarsonFr** [comment]
> I have a repository not found (404) with https://jitpack.io/org/matrix/gitlab/matrix-org/olm/3.1.2/olm-3.1.2.jar when trying from my desktop, but I can get the jar when trying from my mobile device (on same network)

Ok i checked the mobile browser is getting a 404 also, but is downloading the response body as a jar file....

```
date:
Fri, 30 Aug 2019 08:14:10 GMT
content-type: text/plain; charset=utf-8
content-length: 62
connection: keep-alive
set-cookie: __cfduid=d4235e433b75e90f62671302xxxx1567152850; expires=Sat, 29-Aug-20 08:14:10 GMT; path=/; domain=.jitpack.io; HttpOnly
cf-cache-status: HIT
cache-control: private, max-age=1800
cf-ray: 50e54f431fd0cd7b-CDG
age: 72
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
vary: Accept-Encoding
x-jp-cf: 1
server: cloudflare

**Comment by BillCarsonFr** [comment]
Now it says 
> File not found. Build ok

**Comment by BillCarsonFr** [comment]
And it's gone again
> Repository not found: https://gitlab.matrix.org/matrix-org/olm

**Comment by bmarty** [comment]
Olm seems to be accessible right now:
<img width="869" alt="image" src="https://user-images.githubusercontent.com/3940906/64019629-f83a9100-cb2f-11e9-8deb-29b8ca9c3150.png">

But it's very very VERY unstable

**Comment by bmarty** [comment]
@jitpack-io is it possible to rebuild Android Matrix SDK v0.9.27 please, since Olm Sdk is availble now?

<img width="887" alt="image" src="https://user-images.githubusercontent.com/3940906/64022039-98df7f80-cb35-11e9-8a67-8f7a33d90895.png">

It will be appreciated :)

**Comment by t0mmar** [comment]
I'm also running into same problems:

```
   > Could not find com.github.matrix-org:matrix-android-sdk:v0.9.27.
     Required by:
         project :vector
```

**Comment by Toni111111** [comment]
@bmarty i also have Could not find com.github.matrix-org:matrix-android-sdk:v0.9.27.

**Comment by ara4n** [comment]
to be clear: we're not aware of any issues at the gitlab.matrix.org end. this looks like network issues at the jitpack end, which is impacting rolling out releases for [security issues](https://medium.com/@RiotChat/matrix-android-sdk-security-issue-affecting-riot-android-36b4792ea0d6)...

**Comment by hannojg** [comment]
Still getting this from time to time

**Comment by hannojg** [comment]
This is beyond being hyper annoying 😓  (yes, still happens)

**Comment by Bubu** [comment]
Failing here too: https://f-droid.org/wiki/index.php?title=im.vector.app/lastbuild_40100100&oldid=282428

**Comment by maksim77** [comment]
Its still happen :(
It's been almost two years. Maybe there is some news?

**Comment by bmarty** [comment]
Once again:

<img width="585" alt="image" src="https://user-images.githubusercontent.com/3940906/116828949-2f353580-aba2-11eb-8054-80e9ccda4bc5.png">

**Comment by bmarty** [comment]
Olm and the Android Matrix SDK are now published on MavenCentral.

**Comment by raxod502** [comment]
Where? I only see Jitpack listed at https://mvnrepository.com/artifact/org.matrix.gitlab.matrix-org/olm.
