### ISSUE TITLE
Build log is empty file with "Ok".

### ISSUE THREAD

**Issue by VcSaJen** [jitpack/jitpack.io#391]
https://jitpack.io/com/github/VcSaJen/CuboidLocale/d4900d7d7f/build.log
No "BUILD SUCCESSFUL" or "BUILD FAILED" in the log, just empty file with "Ok".

**Comment by renaudcerrato** [comment]
@VcSaJen : I noticed those strange logs output too, they disappeared after a while, but none of today's builds are working. https://github.com/jitpack/jitpack.io/issues/392

**Comment by jitpack-io** [comment]
@VcSaJen Should be showing the correct log now
