### ISSUE TITLE
Git error? Service down?

### ISSUE THREAD

**Issue by renaudcerrato** [jitpack/jitpack.io#392]
It seems that jitpack suddenly stopped working for me today, with weird errors.

Trying to test the `SNAPSHOT` version, the logs showed that [error](https://jitpack.io/com/github/renaudcerrato/SlidingUpPaneLayout/-SNAPSHOT/build.log):

```
Git error:
Index: 1, Size: 1
```

The strange thing is that the report from the snapshot's hash id (`906af32969`) [reports a successfull build](https://jitpack.io/com/github/renaudcerrato/SlidingUpPaneLayout/906af32969/build.log)!

So far so good, I decided to use the commit hash id directly:

```gradle
compile 'com.github.renaudcerrato.SlidingUpPaneLayout:library:906af32969'
```

But I was welcomed with a "not found" error:

```
Error:Artifact 'library.aar (com.github.renaudcerrato.SlidingUpPaneLayout:library:906af32969)' not found.
Searched in the following locations:
    https://jitpack.io/com/github/renaudcerrato/SlidingUpPaneLayout/library/906af32969/library-906af32969.aar
```

Nonetheless, older builds (!= today) are still working :

```gradle
compile 'com.github.renaudcerrato.SlidingUpPaneLayout:library:65644f284f'
```

Any clue?

**Comment by jitpack-io** [comment]
Hi

Will have a look. The build with commit hash id should be available now.
Thanks!

**Comment by renaudcerrato** [comment]
hi! Still unable to get it working using the hash reference:

```
Error:Artifact 'library.aar (com.github.renaudcerrato.SlidingUpPaneLayout:library:906af32969)' not found.
Searched in the following locations:
    https://jitpack.io/com/github/renaudcerrato/SlidingUpPaneLayout/library/906af32969/library-906af32969.aar
```

But working with an older build (< today).

**Comment by jitpack-io** [comment]
Mmm, strange. Does that url open for you a in browser or via wget?

**Comment by renaudcerrato** [comment]
I should have try that: yep, both wget and browser fetching works... Any idea what's wrong?

**Comment by jitpack-io** [comment]
Probably stuck in gradle cache. Running gradle with `--refresh-dependencies` flag should fix it. If not deleting the gradle cache

**Comment by renaudcerrato** [comment]
Yep, the cache was stuck, did a refresh again and it worked. That's probably related to this morning's errors (https://github.com/jitpack/jitpack.io/issues/391). 

I let you decide to close or not this issue.

tks.

**Comment by jitpack-io** [comment]
Snapshot is also working now so we probably can close this

Thanks!
