### ISSUE TITLE
Can't load commit from jitpack

### ISSUE THREAD

**Issue by kdenzel** [jitpack/jitpack.io#3920]
https://jitpack.io/com/github/bachtrong43/libgdx/master-gdx-parent-1.9.10-g9887192-8/build.log

Does not find the implementation for some reason.

**Comment by jitpack-io** [comment]
Hi,

Would recommend adding the 'maven' or 'android-maven' plugin: https://jitpack.io/docs/
and then running this command locally: ./gradlew install

**Comment by kdenzel** [comment]
Sorry i do not understand. I did the following:
`    dependencies {
        ...
        classpath 'com.github.dcendents:android-maven-gradle-plugin:2.1'
    }`
but still got the error message.
