### ISSUE TITLE
Git Error

### ISSUE THREAD

**Issue by HeathLoganCampbell** [jitpack/jitpack.io#3922]
Please provide:
So I spent a bit of time fixing this before and it worked. but now it's erroring again. the deploy keys are setup and the third Party application has been approved.

This is for a private repos and I'm on the $9 subscription 
* BevsCore
* BevsSpigot

- Link to build log from https://jitpack.io
https://jitpack.io/com/github/bevsgames/BevsSpigot/e2f12834a0/build.log

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?
Yes, It build correctly 

- What error are you seeing?
Git error

Thank you!

**Comment by HeathLoganCampbell** [comment]
It seems 50/50 on when it happens

**Comment by jitpack-io** [comment]
Hi,

That build seems to be successful now but let us know if it happens again. Git error can happen in several scenarios.
