### ISSUE TITLE
Jitpack corrupts binary files in gradle jar task

### ISSUE THREAD

**Issue by Frotty** [jitpack/jitpack.io#3923]
**Describe the bug**
When I use a jitpack dependency in my project, all classes and text files load fine.
However, all binary files, such as .png images, are corrupted and do not load.
![](https://i.imgur.com/T2izgDs.jpg)

When I build the jar myself with `gradlew jar`, the images inside the output jar are not corrupted and load fine.

**To Reproduce**
1. Go to https://jitpack.io/com/github/frotty/meta/2c8ab8a1cc/build.log
2. See that the build succeeded and seems normal
3. Use `'com.github.frotty:meta:2c8ab8a1cc'` as a dependency in a gradle project
4. Check the downloaded .jar inside the gradle cache
5. Observe that all binary files are broken, e.g. by extracting `icon.png` and trying to open it.

**Expected behavior**
The images shouldn't be broken - it works when I run the task locally.

**Additional context**
I uploaded a zip archive containing both jars. The `desktop-1.0.jar` is locally built and contains the working images. `desktop-2c8ab8a1cc.jar` is from my gradle cache and the images are broken.

[libs.zip](https://github.com/jitpack/jitpack.io/files/3464799/libs.zip)

**Comment by tommyettinger** [comment]
Seems broken in the repo too. https://github.com/Frotty/Meta/blob/master/runtime/assets/textures/meta_logo.png Can you try replacing the textures in the repo with the ones that work from desktop-1.0.jar ?

**Comment by Frotty** [comment]
oh, true. Strange. The local files are fine but the github repo is somehow corrupt? 
Thanks for the hint 👍

**Comment by jitpack-io** [comment]
Does it help if you set the images as binary in .gitattributes file:
https://stackoverflow.com/questions/19411981/images-corrupt-after-git-push ?

**Comment by Frotty** [comment]
Doesn't look like it. I pushed the gitattributes you linked but the image is still not displaying https://github.com/Frotty/Meta/blob/master/runtime/assets/icon.png

**Comment by Frotty** [comment]
Okay adding the gitattributes and then removing + recommiting all the files worked.
Thanks @tommyettinger @jitpack-io
