### ISSUE TITLE
ihsanbal/LoggingInterceptor 2.0.5 build failed

### ISSUE THREAD

**Issue by MohMah** [jitpack/jitpack.io#3924]
Please provide:

- Link to build log from https://jitpack.io
https://jitpack.io/com/github/ihsanbal/LoggingInterceptor/2.0.5/build.log

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?
Yes

- What error are you seeing?
ERROR: Failed to resolve: com.github.ihsanbal:LoggingInterceptor:2.0.5

Thank you!

**Comment by jitpack-io** [comment]
Hi,

Seems like updating Gradle wrapper worked. Latest snapshot builds:
https://jitpack.io/com/github/ihsanbal/LoggingInterceptor/master-5e679d11a6-1/build.log
