### ISSUE TITLE
CORB too strict on API

### ISSUE THREAD

**Issue by sbaier1** [jitpack/jitpack.io#3925]
**Describe the bug**

The CORB policy on the API is too strict. Other APIs like GitHub's allow client side JavaScript to make requests freely.

**To Reproduce**
1. Go to any page on the web
2. Make a request to the jitpack API, e.g. `fetch('http://jitpack.io/api/builds/groupid/artifactid')` using the javascript console

**Expected behavior**
The fetch request should return a response from the API

**Screenshots**
![Bildschirmfoto 2019-08-06 um 11 43 45](https://user-images.githubusercontent.com/20339314/62529729-7b254000-b83f-11e9-990c-527e484fdcd0.png)

**Additional context**
GitHub sets other headers on the server side to avoid this it seems. While also setting the same  `Referrer-Policy` headers, they also set e.g. `Access-Control-Allow-Origin = *`.
I am not familiar with how to properly implement XSS protection mechanisms, but it seems that making requests from client side JavaScript e.g. from a GitHub page would be a pretty genuine use case for your API.

**Comment by jitpack-io** [comment]
Hi,

Thank you for bringing this up!
Should be working now.

**Comment by sbaier1** [comment]
yep, appears to be working now. thank you.
