### ISSUE TITLE
Subscription not active

### ISSUE THREAD

**Issue by mwteam-3d** [jitpack/jitpack.io#3926]
Hi, I already bought a $99/year subscription for org.bitbucket.magicweaverteam/sdk , but I still got error like this:
Could not resolve org.bitbucket.magicweaverteam:sdk:1.0.9.

In addition when I click log it shows Subscription not active.
@jitpack-io

**Comment by jitpack-io** [comment]
Hi,

Should be resolved now. Please let us know if you still experience the issue
