### ISSUE TITLE
Wrong artifact version used in POM for modules from multi-module project

### ISSUE THREAD

**Issue by sschuberth** [jitpack/jitpack.io#3932]
**Describe the bug**

When requesting the artifact for a specific commit of a multi-module project, the POM for that project contains wrong version numbers for dependencies on other modules from the same project.

**To Reproduce**

See e.g. https://jitpack.io/com/github/heremaps/oss-review-toolkit/analyzer/jitpack-713d20d5c2-1/analyzer-jitpack-713d20d5c2-1.pom, which depends on the `model` artifact which is a module in the same project. As version `jitpack-713d20d5c2-1` of the `analyzer` module is used, also version `jitpack-713d20d5c2-1` of the `model` module should be used.

**Expected behavior**

The versions of artifacts for modules in multi-module projects should match. Instead, if `analyzer` depends on `model`, and version `jitpack-713d20d5c2-1` of `analyzer` is requested, then version `jitpack-SNAPSHOT` of `model` is being used. But the latter should also be version `jitpack-713d20d5c2-1`.

**Comment by jitpack-io** [comment]
Hi,

Thank you for reporting! It seems the 'jitpack' branch no longer exists in the project. Is there another branch we can reproduce this on?

**Comment by sschuberth** [comment]
While trying to reproduce the issue with a commit on the `master` branch I realized that I probably got something wrong WRT how JitPack creates versions for branches. Anyway, looking at e.g. https://jitpack.io/com/github/heremaps/oss-review-toolkit/analyzer/f48532905d/analyzer-f48532905d.pom now, I see that it correctly uses `<version>f48532905d</version>` for its multi-module dependencies, so I'm closing this.

**Comment by Bleoo** [comment]
I have the same problem. How did you solve it?

**Comment by sschuberth** [comment]
I can't remember to have done anything specific. The problem just disappeared AFAIR as soon as I started publishing from `master` instead of from a branch.
