### ISSUE TITLE
Random directory chosen

### ISSUE THREAD

**Issue by Vampire** [jitpack/jitpack.io#3937]
For jmockit/jmockit1 (not my project, just consuming), JitPack chooses a random folder to cd into before doing the `mvn install`.
This causes to sometimes having the correct artifacts from `main`, sometimes the wrong artifacts from `coverage-tests`.

**Comment by jitpack-io** [comment]
Hi,

Seems like there is no build file in the root of the directory so jitpack doesn't know which directory to build. 
One solution is to specify custom build commands in jitpack.yml but that needs to be committed to the repo.

**Comment by Vampire** [comment]
Yeah, I thought so, but choosing a random directory is maybe not the best idea and also not reliable.
I'm only a consumer of that lib and I doubt the owner will add JitPack config to his repo, especially as JitPack is not something he says one should use, I just wanted to try the latest version without compiling myself.
Maybe in such a case it would be a good idea to search whether there are multiple `pom.xml` and if so like in this case treat it as multi-module build, so that consumers can decide which module they want explicitly by using different coordinates.

**Comment by Vampire** [comment]
.

**Comment by Vampire** [comment]
As far as I can see this did not change, can anyone please reopen this?
