### ISSUE TITLE
Bumptech Glide 4.7.1

### ISSUE THREAD

**Issue by jtang-ml** [jitpack/jitpack.io#3970]
Please provide:

- Link to build log from https://jitpack.io
https://jitpack.io/com/github/bumptech/glide/v4.7.1/build.log

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?
Haven't tried building locally. 

- What error are you seeing?
Could not resolve all files for configuration ':app:betaReleaseRuntimeClasspath'.
> Could not resolve com.github.bumptech.glide:glide:4.7.1.
  Required by:
      project :app > project :react-native-fast-image
   > Could not resolve com.github.bumptech.glide:glide:4.7.1.
      > Could not get resource 'https://jitpack.io/com/github/bumptech/glide/glide/4.7.1/glide-4.7.1.pom'.
         > Could not GET 'https://jitpack.io/com/github/bumptech/glide/glide/4.7.1/glide-4.7.1.pom'. Received status code 522 from server: Origin Connection Time-out

Thank you!

**Comment by FranziscaZarrai** [comment]
Build fails locally as well after clearing my gradle cache to force a complete re-download and rebuild with above error message (bumptech/glide) since we're using that library as well

**Comment by eenglish49** [comment]
I have same issue.  We have a million active daily users that can't get an update because of Jitpack.  What a mistake to use Jitpack for all our private library repos.  We can't even build our own project because of this.

**Comment by appach22** [comment]
I've found a workaround:
`maven { url "https://www.jitpack.io" }`
(added `www`)
