### ISSUE TITLE
522 error downloading dependency on build server

### ISSUE THREAD

**Issue by wdtaylor** [jitpack/jitpack.io#3976]
Could not resolve all artifacts for configuration ':classpath'. 

 > Could not resolve gradle.plugin.org.jlleitschuh.gradle:ktlint-gradle:4.1.0. 

 Required by: 

 project : 

 > Could not resolve gradle.plugin.org.jlleitschuh.gradle:ktlint-gradle:4.1.0. 

 > Could not get resource 'https://jitpack.io/gradle/plugin/org/jlleitschuh/gradle/ktlint-gradle/4.1.0/ktlint-gradle-4.1.0.jar'. 

 > Could not HEAD 'https://jitpack.io/gradle/plugin/org/jlleitschuh/gradle/ktlint-gradle/4.1.0/ktlint-gradle-4.1.0.jar'. Received status code 522 from server: Origin Connection Time-out 

Can't download this file during build process.  jitpack.io down as well.    
https://jitpack.io/gradle/plugin/org/jlleitschuh/gradle/ktlint-gradle/4.1.0/ktlint-gradle-4.1.0.jar

Thank you!

**Comment by draperunner** [comment]
Duplicate of https://github.com/jitpack/jitpack.io/issues/3973

**Comment by jitpack-io** [comment]
Hi,

Are you still experiencing this? At the moment it's returning 404 is it might have been temporary.

**Comment by olivierGATSNCF** [comment]
Hi,
A similar issue is encountered.

When i do: curl -I  https://jitpack.io/com/bea/jolt/1/jolt-1.pom => 404 Not Found
and when this request is done by nexus, from request "https://mynexus/repository/maven-jitpack-proxy/com/bea/jolt/1/jolt-1.pom",  logs are good : https://jitpack.io/com/bea/jolt/1/jolt-1.pom < HTTP/1.1 404 Not Found
Good

When i do: curl -I https://jitpack.io/com/bea/jolt/9.1.098/jolt-9.1.098.pom => 404 Not Found

But when this request is done by nexus, from request "https://mynexus/repository/maven-jitpack-proxy/com/bea/jolt/9.1.098/jolt-9.1.098.pom" , logs are : https://jitpack.io/com/bea/jolt/9.1.098/jolt-9.1.098.pom < HTTP/1.1 522 Origin Connection Time-out

**Comment by alanlai1989** [comment]
`Could not GET 'https://jitpack.io/com/zopim/android/sdk-api/1.4.5/sdk-api-1.4.5.pom'. Received status code 522 from server: Origin Connection Time-out
`
It is still happen

**Comment by creshal** [comment]
Still/again happening:

```
Could not GET 'https://jitpack.io/org/webkit/android-jsc/maven-metadata.xml'. Received status code 522 from server: Origin Connection Time-out
```
