### ISSUE TITLE
Nexus maven proxy failed.

### ISSUE THREAD

**Issue by CreateChance** [jitpack/jitpack.io#3978]
**Describe the bug**
Can not make proxy of jitpack with nexus maven local server.

**To Reproduce**
1. Create new proxy, fill with below info:
![image](https://user-images.githubusercontent.com/9158995/64955395-b8f39a80-d8ba-11e9-8b08-734b3772dca0.png)
![image](https://user-images.githubusercontent.com/9158995/64955426-c872e380-d8ba-11e9-9e99-c523cb75146f.png)
2. try to sync rxjava 2.2.12 with gradle:
```bash
implementation 'com.github.ReactiveX:RxJava:v2.2.12'
```
and got error:
```bash
[Fatal Error] RxJava-v2.2.12.pom:1:44: content is not allowed in prolog.
```
3. login nexus server, and see this:
![image](https://user-images.githubusercontent.com/9158995/64955575-31f2f200-d8bb-11e9-9d6e-9762495c4416.png)
As you can see, pom file is empty, that means proxy download failed.

**Expected behavior**
Proxy can download any repo file.

**Additional context**
nexus version: 3.15.2.01
Network: ping jitpack.io ok
Disk space: 70% left

What can I do now? Please help me, thanks very much!

**Comment by mikeholler** [comment]
Seems like this might be fixed with #3977. Also try this cleanup procedure:

https://github.com/jitpack/jitpack.io/issues/3977#issuecomment-532756771

**Comment by jitpack-io** [comment]
Yes, this should be resolved now.

**Comment by CreateChance** [comment]
Thanks buddy. :)
