### ISSUE TITLE
Subscription not active

### ISSUE THREAD

**Issue by eenglish49** [jitpack/jitpack.io#3999]
- Link to build log from https://jitpack.io
https://jitpack.io/com/rm-apps-gitlab/git/Apps/Mobile.Android.Launcher.Core/1.1.38/build.log

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?
No

- What error are you seeing?
Could not GET 'https://jitpack.io/com/rm-apps-gitlab/git/Apps/Mobile.Android.Launcher.Core/1.1.38/Mobile.Android.Launcher.Core-1.1.38.pom'. Received status code 403 from server: Forbidden

**Comment by jitpack-io** [comment]
Hi,

Should be resolved now as we've updated the subscription to work with your git server.
Please reopen if issue persists
