### ISSUE TITLE
Sbt support

### ISSUE THREAD

**Issue by jitpack** [jitpack/jitpack.io#4]
We can use 'sbt publishM2' to install in the local maven repository

- [x] update documentation

**Comment by VladUreche** [comment]
+1 - would really like to have that!

**Comment by tkawachi** [comment]
:+1:

**Comment by johandahlberg** [comment]
:+1:

**Comment by jitpack** [comment]
Ok then, sbt 0.13.7 is in place! 
Here's one example sbt project: https://github.com/jitpack/scala-akka-hello-world that worked great.

**Comment by jitpack** [comment]
To use jitpack repository from sbt add this to build.sbt:
```sbt
resolvers += "jitpack" at "https://jitpack.io"
```
and then use:
```sbt
libraryDependencies += "com.github.User" % "Repo" % "Tag"
```

**Comment by VladUreche** [comment]
Nice! I have a repository where I will use this feature in the next 2-3 weeks. Looking forward to seeing it in action!

**Comment by jitpack** [comment]
@VladUreche Enjoy!:) Will be curious to learn how it goes

**Comment by kag0** [comment]
@jitpack how would sbt projects be set up with private repos?

**Comment by jitpack-io** [comment]
Hi @kag0 

Added sbt info to private repository docs:
https://github.com/jitpack/jitpack.io/blob/master/PRIVATE.md#sbt-setup

Sorry it wasn't documented before. Thanks for inquiring!

**Comment by kag0** [comment]
@jitpack-io awesome, thanks!
