### ISSUE TITLE
Jitpack Team not providing support

### ISSUE THREAD

**Issue by eenglish49** [jitpack/jitpack.io#4000]
I have written an email. I have posted in this Issues section. I have posted in "Ask" chat room.
I HAVE NOT RECEIVED ONE BIT OF SUPPORT.  This is a bad business model.  If my team's issue isn't resolved shortly, we will take out business elsewhere and be very vocal about it.

Link to build log from https://jitpack.io
https://jitpack.io/com/rm-apps-gitlab/git/Apps/Mobile.Android.Launcher.Core/1.1.38/build.log

Does the project build on your machine with the same commands (e.g. ./gradlew install) ?
No

What error are you seeing?
Could not GET 'https://jitpack.io/com/rm-apps-gitlab/git/Apps/Mobile.Android.Launcher.Core/1.1.38/Mobile.Android.Launcher.Core-1.1.38.pom'. Received status code 403 from server: Forbidden

**Comment by jitpack-io** [comment]
Hi,

Apologies about the delay. There was an issue with the subscription which should be resolved now.

**Comment by plutus-finwizard** [comment]
I have been trying to reach your support team for weeks now. My subscription shows inactive whereas we have already done the payment. My account still shows inactive and is leading to issues with our clients.
