### ISSUE TITLE
Android Libraries fail to resolve with https://jitpack.io

### ISSUE THREAD

**Issue by geoffduong** [jitpack/jitpack.io#4002]
**Describe the bug**
If you have maven { url "https://jitpack.io" } as your resolving url, then Jitpack will only return the POM for the Android dependency causing the Gradle sync to fail.  The workaround currently is to wipe the dependency from your cache and update the resolving url to maven { url "https://**www**.jitpack.io" }

**To Reproduce**
1. Setup a new Android Studio project
2. Add maven { url "https://jitpack.io" } to your root build.gradle
3. Add implementation 'com.github.PhilJay:MPAndroidChart:v3.1.0' to your app module's build.gradle

**Expected behavior**
POM, AAR, and sources.jar are all resolved for the dependency.

**Screenshots**

**Additional context**

**Comment by Gryzor** [comment]
@vasiledoe this issue has been raised on May 17th, 2018. The response is from October, 2018. This issue was created seven days ago. The the StackOverflow question _points to this_ issue...

**Comment by jitpack-io** [comment]
Hi,

What is the error you are seeing when installing `com.github.PhilJay:MPAndroidChart:v3.1.0` ?
It'd be great if you could run gradle with the `--info` flag. That way it'll provide a more detailed error message

**Comment by nre-ableton** [comment]
Using `www.jitpack.io` resolved the issue for me, see https://github.com/expo/expo/commit/bb2d4b04845f6e4813e51b02149c3f5eef1b606b

**Comment by Gryzor** [comment]
I had troubles with https://github.com/franmontiel/PersistentCookieJar too, I can test later to see if I can repro the issue. (Since it was an old lib, I forked it and included it in my source). I recall I did the fork because it wasn't working when used via Gradle to some developers; we didn't think of trying the www.jitpack vs. just jitpack back then.

**Comment by mbwhite** [comment]
We're seeing issues with both www.jitpack.io and jitpack.io now...

**Comment by geoffduong** [comment]
> Hi,
> 
> What is the error you are seeing when installing `com.github.PhilJay:MPAndroidChart:v3.1.0` ?
> It'd be great if you could run gradle with the `--info` flag. That way it'll provide a more detailed error message

@mbwhite Can you run gradle with the '--info' flag as suggested above and please post the error message? Thanks!

**Comment by brandonrains77** [comment]
Has anyone figured out a workaround, been struggling with this for days, with both www.jitpack.io and jitpack.io now

**Comment by nre-ableton** [comment]
ping @jitpack-io, this issue is quite severe!

**Comment by zeroleak** [comment]
Same issue here, dependency not downloading anymore from android studio.
DNS inconsistency
> jitpack.io.		3	IN	A	104.24.22.62
> www.jitpack.io.		5	IN	A	149.56.28.39
Critical issue blocking our developers!

**Comment by zeroleak** [comment]
it seems upgrading to gradle 3.5.1 (and latest android studio) fixed the problem... or maybe it's a coincidence

**Comment by gupta-sachin** [comment]
Tried with Studio v3.5.1, android-gradle 3.5.1 and gradle 5.4.1, it failed with below error-

Unable to load Maven meta-data from https://www.jitpack.io/com/github/xxx/xxx/dev-SNAPSHOT/maven-metadata.xml

Worked when used Studio v3.5.1, android-gradle 3.4.1 and gradle 5.2.1

**Comment by mbwhite** [comment]
> > Hi,
> > What is the error you are seeing when installing `com.github.PhilJay:MPAndroidChart:v3.1.0` ?
> > It'd be great if you could run gradle with the `--info` flag. That way it'll provide a more detailed error message
> 
> @mbwhite Can you run gradle with the '--info' flag as suggested above and please post the error message? Thanks!

Sorry been distracted with other work... the issue is acknowledged at least in the issue @alextrotsenko mentions above... they have at least responded to somebody on twitter as wel.

**Comment by helen-jiayuhan** [comment]
I'm trying to use BarChart and gradle buildings are fine but the xml files says "missing class" error for chart tag I'm using...
![image](https://user-images.githubusercontent.com/51962895/83220442-53301000-a1b6-11ea-969e-bcb390dbd27c.png)

**Comment by Gryzor** [comment]
@helen-jiayuhan I don't see how this is related, but have you tried StackOverflow? 

In addition, try `Android Studio -> File -> Invalidate Caches -> Invalidate Caches and Restart`. Tends to fix most A.S. problems.

**Comment by helen-jiayuhan** [comment]
> @helen-jiayuhan I don't see how this is related, but have you tried StackOverflow?
> 
> In addition, try `Android Studio -> File -> Invalidate Caches -> Invalidate Caches and Restart`. Tends to fix most A.S. problems.

sorry it's just something stupid with my AndroidStudio.... It just need to close the project and restart... Got me crazy for a long time to find this solution...

**Comment by mohit-sharma-87** [comment]
@geoffduong : I would like to reopen this issue. Today I just faced the same issue.

**Comment by SchmidtKBS** [comment]
Hey, I also faced this issue and I was not able to fix it. I tried to invalidate the gradle cache and change the url from 'https://jitpack.io' to 'https://www.jitpack.io' but both had no effect. It's really strange, that it was working until i changed the commit hash in my gradle file to a newer version of the dependency.

**Comment by max-usenko-aura** [comment]
> Hey guys, we've encountered this issue an hour ago and the solution was to remove the previous workaround ('www') and move it to the bottom of the repository list. - `maven { url 'https://jitpack.io' }`

works! thank you

**Comment by mirse** [comment]
in android studio2022.1.1 patch2  gradle plugin version 7.4.2 gradle version 7.5

also have this problem

**Comment by nxywxy** [comment]
> in android studio2022.1.1 patch2 gradle plugin version 7.4.2 gradle version 7.5
> 
> also have this problem
I also encountered a similar problem. 
Android Studio Flamingo | 2022.2.1 Patch 2
gradle plugin version 7.4.1
gradle version 7.5

I was able to download the dependencies yesterday, and I found this problem when I was working today.

**Comment by Lancerer** [comment]
> > 在android studio2022.1.1 patch2 gradle插件版本7.4.2 gradle版本7.5
> > 也有这个问题
> 
> 我也遇到了类似的问题。 Android Studio 火烈鸟 | 2022.2.1补丁2 gradle插件版本7.4.1 gradle版本7.5
> 
> 昨天还能下载依赖，今天工作的时候发现了这个问题。

请问怎么解决的

**Comment by Lancerer** [comment]
> > in android studio2022.1.1 patch2 gradle plugin version 7.4.2 gradle version 7.5
> > also have this problem
> 
> I also encountered a similar problem. Android Studio Flamingo | 2022.2.1 Patch 2 gradle plugin version 7.4.1 gradle version 7.5
> 
> I was able to download the dependencies yesterday, and I found this problem when I was working today.

How was it solved？
