### ISSUE TITLE
[error] -Dsbt.log.noformat=true - expected ';'

### ISSUE THREAD

**Issue by Synesso** [jitpack/jitpack.io#4006]
Please provide:

- Link to build log from https://jitpack.io

https://jitpack.io/com/github/synesso/scala-stellar-sdk_2.12/0.10.0/build.log

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?

No

- What error are you seeing?

```[error] Expected ';'
[error] -Dsbt.log.noformat=true
[error]                        ^
```

The command issued `sbt ++2.12.0 -Dsbt.log.noformat=true clean publishM2`

should instead be

`sbt -Dsbt.log.noformat=true ++2.12.0 clean publishM2`

**Comment by nightscape** [comment]
Same issue here. @jitpack-io any known workarounds, e.g. is it possible to provide a custom `jitpack.yml` that is still able to cross-publish?

**Comment by nightscape** [comment]
Temporary (ugly) workaround:
```yaml
# jitpack.yml
install:
   - sbt `echo $ARTIFACT | sed 's/.*2.11$/++2.11.12/;s/.*2.12$/++2.12.10/'` publishM2
```

**Comment by derek9gag** [comment]
This is fixed in newer sbt-launcher. It works with `1.3.8`. @jitpack-io  can we have the `sbt` launcher package upgraded please?

See: https://github.com/sbt/sbt/issues/3921

**Comment by milin-k** [comment]
> Temporary (ugly) workaround:
> 
> ```yaml
> # jitpack.yml
> install:
>    - sbt `echo $ARTIFACT | sed 's/.*2.11$/++2.11.12/;s/.*2.12$/++2.12.11/;s/.*2.13$/++2.13.1/'` publishM2
> ```
Does this solution work for private repo- I was getting permision issue in jitpack build log

**Comment by nightscape** [comment]
@milin-k I don't have any experience with private repos, but imo this should be unrelated.

**Comment by nightscape** [comment]
@jitpack-io any chance to fix this?
It's probably a one-line change and currently requires forking every single Scala SBT project I want to use with JitPack...

**Comment by zt1983811** [comment]
sbt version 1.6.2 failed again 
https://jitpack.io/com/github/zt1983811/scalapb-json4s_2.12/allow_numeric_boolean_parsing_scala_2.12_new-v0.12.0-g2c41ad3-84/build.log

**Comment by nightscape** [comment]
@zt1983811 I think your issue is completely unrelated to this issue.
As far as I can tell, the issue here has been fixed silently 😉
