### ISSUE TITLE
You can't build because gradle is lower version.

### ISSUE THREAD

**Issue by NoteJGPak** [jitpack/jitpack.io#4010]
Please provide:

- Link to build log from 
 * https://jitpack.io/com/github/NoteJGPak/df_editor_android/0.0.2/build.log

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?
 * no

- What error are you seeing?

My Gradle version is 5.4.1.
The configuration information in gradle-wrapper.properties is 
"distributionUrl = https \: //services.gradle.org/distributions/gradle-5.4.1-all.zip".
But the part that keeps on error is saying that my gradle version should not be 4.8.1.

------
> A problem occurred evaluating project ': nativericheditor'.
> Failed to apply plugin [id 'com.android.library']
    > Minimum supported Gradle version is 5.4.1. Current version is 4.8.1. If using the gradle wrapper, try editing the distributionUrl in /home/jitpack/build/gradle/wrapper/gradle-wrapper.properties to gradle-5.4.1-all.zip
------
Is there any way to fix it?

Thank you!

**Comment by jitpack-io** [comment]
Hi,

It seems that the`gradlew` script is missing in the repository.

**Comment by NoteJGPak** [comment]
Thank you!
