### ISSUE TITLE
Could not determine dependencies of Multi-Module library.

### ISSUE THREAD

**Issue by jcchavezm** [jitpack/jitpack.io#4011]
Please provide:

- Link to build log from https://jitpack.io:
https://jitpack.io/com/github/ClipMX/mobile.Android.Sdk/0.0.3/build.log

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?
Yes

- What error are you seeing?
We have published a Multi-Module library on JitPack. When running the project we get a 401 error for the modules that the main module is dependent on.
Read access has been set to "Everyone" on JitPack's configs.

This is what Android Studio returns:

`Could not determine the dependencies of task ':app:processDebugResources'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve com.github.ClipMX:network:0.0.3.
     Required by:
         project :app > com.github.ClipMX:mobile.Android.Sdk:0.0.3
      > Could not resolve com.github.ClipMX:network:0.0.3.
         > Could not get resource 'https://jitpack.io/com/github/ClipMX/network/0.0.3/network-0.0.3.pom'.
            > Could not GET 'https://jitpack.io/com/github/ClipMX/network/0.0.3/network-0.0.3.pom'. Received status code 401 from server: Unauthorized
   > Could not resolve com.github.ClipMX:terminal:0.0.3.
     Required by:
         project :app > com.github.ClipMX:mobile.Android.Sdk:0.0.3
      > Could not resolve com.github.ClipMX:terminal:0.0.3.
         > Could not get resource 'https://jitpack.io/com/github/ClipMX/terminal/0.0.3/terminal-0.0.3.pom'.
            > Could not GET 'https://jitpack.io/com/github/ClipMX/terminal/0.0.3/terminal-0.0.3.pom'. Received status code 401 from server: Unauthorized
   > Could not resolve com.github.ClipMX:storage:0.0.3.
     Required by:
         project :app > com.github.ClipMX:mobile.Android.Sdk:0.0.3
      > Could not resolve com.github.ClipMX:storage:0.0.3.
         > Could not get resource 'https://jitpack.io/com/github/ClipMX/storage/0.0.3/storage-0.0.3.pom'.
            > Could not GET 'https://jitpack.io/com/github/ClipMX/storage/0.0.3/storage-0.0.3.pom'. Received status code 401 from server: Unauthorized
   > Could not resolve com.github.ClipMX:dspread:0.0.3.
     Required by:
         project :app > com.github.ClipMX:mobile.Android.Sdk:0.0.3
      > Could not resolve com.github.ClipMX:dspread:0.0.3.
         > Could not get resource 'https://jitpack.io/com/github/ClipMX/dspread/0.0.3/dspread-0.0.3.pom'.
            > Could not GET 'https://jitpack.io/com/github/ClipMX/dspread/0.0.3/dspread-0.0.3.pom'. Received status code 401 from server: Unauthorized`

Thank you!

**Comment by AnD010** [comment]
Hi! @jcchavezm  
I have the same error.... could you fix it?
Thanks!

**Comment by jcchavezm** [comment]
@AnD010 in our case the error was due to the account.
Turns out that, when purchasing the license, the account was pointing to other organization, different from the the one in which we have the repository.
Contacted JitPack support and now everything works.
Best!
