### ISSUE TITLE
Is it possible to make path for single library as for project with many libraries?

### ISSUE THREAD

**Issue by Chumva** [jitpack/jitpack.io#4016]
I created an aar library and it imports well. 

Current path is "com.github.osmandapp:osmand:2.0.0"
Is it possible to make it  "com.github.osmandapp.osmand:osmand-api:2.0.0" without adding another one library to project?

I have searched a bit and It looks like impossible-_-

https://github.com/jitpack-io/multi-flavor-lib-demo

"If the project includes a single library, the repository name gets to be the artifactId, even if you specify otherwise."

https://twitter.com/jitpack/status/943842378011602944?lang=en

**Comment by jitpack-io** [comment]
Hi,

At the moment this is not possible and requires another module in the repository.
