### ISSUE TITLE
can not download my public repository jar

### ISSUE THREAD

**Issue by alfredhua** [jitpack/jitpack.io#4026]
Please provide:
I build success;
I can download tag 1.0.0

can not download tag 1.0.1，

about five hours after I can  download tag 1.0.1

this is  public repository

- Link to build log from https://jitpack.io

this is build log；

https://jitpack.io/com/github/guozhenhua/common-spring-boot-start/1.0.1/build.log

https://jitpack.io/#guozhenhua/common-spring-boot-start

Thank you!

build.gradle

 repositories {
        mavenLocal()
        jcenter()
        maven { url 'https://jitpack.io' }
        mavenCentral()

    }
dependencies{
        implementation ('com.github.guozhenhua:common-spring-boot-start:1.0.1')
}

**Comment by jitpack-io** [comment]
Hi,

So is it working now for you?
