### ISSUE TITLE
Only one artifact from several are punlished from a Kotlin Multiplatform project

### ISSUE THREAD

**Issue by lamba92** [jitpack/jitpack.io#4028]
It publishes just fine in Maven local, but only one of all the found artifacts is actually expanded and published in the [project](https://github.com/lamba92/kotlin-multiplatform-coroutines-runtest/packages). Have a look at the build [here](https://jitpack.io/com/github/lamba92/kotlin-multiplatform-coroutines-runtest/0.0.3-alpha/build.log).

**Comment by jitpack-io** [comment]
Hi,

Seems like the build skips publication of other artifacts:
`> Task :publishMetadataPublicationToMavenLocal SKIPPED`
