### ISSUE TITLE
public repo is regarded as private repo

### ISSUE THREAD

**Issue by Vove7** [jitpack/jitpack.io#4034]
**Describe the bug**
when I   `implementation 'com.github.Vove7:BottomDialog:2.1.4'` use gradle. I got 401 UnAuthorized. 

but the `Vove7/BottomDialog`  repo is public .

  And [https://jitpack.io/#Vove7/BottomDialog](https://jitpack.io/#Vove7/BottomDialog) is report `
Please Sign In first`

**To Reproduce**\

`implementation 'com.github.Vove7:BottomDialog:2.1.4'`

Or

1. Go to 'https://jitpack.io/#Vove7/BottomDialog'
2. Click on 'Look Up'
3. See error

**Please Sign In first**

And my repo is public `https://github.com/Vove7/BottomDialog`

**Comment by leif81** [comment]
I'm seeing the same problem today. 

A  colleague of mine has forked a project. His fork is public. When I try to retrieve the artifacts from jitpack I get an unauthorized message.

```
Downloading: https://jitpack.io/com/github/MurrayMcDonald16/gt-shapefile/esri_compact_cache-SNAPSHOT/maven-metadata.xml
[WARNING] Could not transfer metadata com.github.MurrayMcDonald16:gt-shapefile:esri_compact_cache-SNAPSHOT/maven-metadata.xml from/to jitpack.io (https://jitpack.io): Not authorized , ReasonPhrase:Unauthorized.
```

**Comment by Vove7** [comment]
> I'm seeing a similar error today.
> 
> A colleague of mine has forked a project. His fork is public. When I try to retrieve the artifacts with Maven I get an unauthorized message.
> 
> ```
> Downloading: https://jitpack.io/com/github/MurrayMcDonald16/gt-shapefile/esri_compact_cache-SNAPSHOT/maven-metadata.xml
> [WARNING] Could not transfer metadata com.github.MurrayMcDonald16:gt-shapefile:esri_compact_cache-SNAPSHOT/maven-metadata.xml from/to jitpack.io (https://jitpack.io): Not authorized , ReasonPhrase:Unauthorized.
> ```

my repo is back to normal for now; (without login)

**Comment by leif81** [comment]
Ok I'm still having problems, might be a different problem, I'll open a new issue.
