### ISSUE TITLE
Build stuck in "queued" for more than 1h

### ISSUE THREAD

**Issue by alvarolaserna** [jitpack/jitpack.io#4035]
**Describe the bug**
Build for a public repository hosted in github gets stuck for too long (testdevlab/TestUI)

**To Reproduce**
1. Use in your project:
```
 <dependency>
            <groupId>com.github.testdevlab</groupId>
            <artifactId>TestUI</artifactId>
            <version>50948d695c</version>
        </dependency>
```

2. and add the jitpack repository to the maven pom.xml

**Expected behavior**
The repository commit or tag gets downloaded

**Actual result**
It hangs for several minutes, and never gets downloaded. In the jitpack page, when you search for the repository, the build seems to be building in queue forever.

**Comment by AlexTrotsenko** [comment]
I have also "queued" for pushed tag for more than hour.
 https://jitpack.io/#AlexTrotsenko/RxActivityResult

Given, that build commit based artefact can't be downloaded (https://github.com/jitpack/jitpack.io/issues/1458) I pushed new tag, but it's "queued" for more then several hours already. 


Given original HTTP error related issue of JitPack (#3973) and having no ability to do work-around became  quite a serious issue at the moment.

**Comment by lsoares** [comment]
it also happens to me.

**Comment by spylight-zz** [comment]
also me too
