### ISSUE TITLE
401 from public repository

### ISSUE THREAD

**Issue by BWMuller** [jitpack/jitpack.io#4039]
Getting a 401 unauthorised error on a public repo. This is not isolated to just this one repo as it happens with a few others as well

```
Could not determine the dependencies of task ':app:compileStagingReleaseJavaWithJavac'.
> Could not resolve all dependencies for configuration ':app:stagingReleaseRuntimeClasspath'.
   > Could not determine artifacts for com.github.BWMuller.EasyGallery:easygallery-core:0.0.3
      > Could not get resource 'https://jitpack.io/com/github/BWMuller/EasyGallery/easygallery-core/0.0.3/easygallery-core-0.0.3.aar'.
         > Could not HEAD 'https://jitpack.io/com/github/BWMuller/EasyGallery/easygallery-core/0.0.3/easygallery-core-0.0.3.aar'. Received status code 401 from server: Unauthorized
```

**Comment by AlexTrotsenko** [comment]
Same issue with another public repo:

```
Cached resource https://www.jitpack.io/com/github/AlexTrotsenko/RxActivityResult/newExplicitIntent-SNAPSHOT/maven-metadata.xml is up-to-date (lastModified: Mon Oct 21 13:49:47 CEST 2019).
Cached resource https://www.jitpack.io/com/github/AlexTrotsenko/RxActivityResult/newExplicitIntent-SNAPSHOT/RxActivityResult-newExplicitIntent-087ed305fd-1.pom is up-to-date (lastModified: Mon Oct 21 13:49:47 CEST 2019).
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:preFullDebugBuild'.
> Could not resolve all task dependencies for configuration ':app:fullDebugRuntimeClasspath'.
   > Could not resolve com.github.AlexTrotsenko:RxActivityResult:newExplicitIntent-SNAPSHOT.
     Required by:
         project :app > project :common
      > Could not resolve com.github.AlexTrotsenko:RxActivityResult:newExplicitIntent-SNAPSHOT.
         > Unable to load Maven meta-data from https://www.jitpack.io/com/github/AlexTrotsenko/RxActivityResult/newExplicitIntent-SNAPSHOT/maven-metadata.xml.
            > Could not HEAD 'https://www.jitpack.io/com/github/AlexTrotsenko/RxActivityResult/newExplicitIntent-SNAPSHOT/maven-metadata.xml'. Received status code 401 from server: Unauthorized

* Try:
Run with --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.internal.tasks.TaskDependencyResolveException: Could not determine the dependencies of task ':app:preFullDebugBuild'.
	at org.gradle.api.internal.tasks.CachingTaskDependencyResolveContext.getDependencies(CachingTaskDependencyResolveContext.java:66)
...
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration$ArtifactResolveException: Could not resolve all task dependencies for configuration ':app:fullDebugRuntimeClasspath'.
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.rethrowFailure(DefaultConfiguration.java:1054)
...
	at org.gradle.api.internal.tasks.CachingTaskDependencyResolveContext.getDependencies(CachingTaskDependencyResolveContext.java:64)
	... 90 more
Caused by: org.gradle.internal.resolve.ModuleVersionResolveException: Could not resolve com.github.AlexTrotsenko:RxActivityResult:newExplicitIntent-SNAPSHOT.
Required by:
    project :app > project :common
```

@jitpack-io any ideas what is the root of the problem or how to work-around it meanwhile?

**Comment by stanma** [comment]
Seems the same as been at #3759

**Comment by BWMuller** [comment]
@stanma true it is the same but that was meant to have been fixed in March then already.

**Comment by leif81** [comment]
I'm seeing the same thing over in https://github.com/jitpack/jitpack.io/issues/4042

**Comment by dongluyang** [comment]
the same issue just happened


      > Could not resolve com.google.protobuf:protobuf-java:2.6.1.
         > Could not parse POM https://jcenter.bintray.com/com/google/protobuf/protobuf-java/2.6.1/protobuf-java-2.6.1.pom
            > Could not download google.pom (com.google:google:1)
               > Could not get resource 'http://maven.apiusage.com/repository/maven-public/com/google/google/1/google-1.pom'.
                  > Could not HEAD 'http://maven.apiusage.com/repository/maven-public/com/google/google/1/google-1.pom'. Received status code 401 from server: Unauthorized
      > Could not resolve com.google.protobuf:protobuf-java:2.6.1.
         > Could not parse POM https://jcenter.bintray.com/com/google/protobuf/protobuf-java/2.6.1/protobuf-java-2.6.1.pom
            > Could not download google.pom (com.google:google:1)
               > Could not get resource 'http://maven.apiusage.com/repository/maven-public/com/google/google/1/google-1.pom'.
                  > Could not HEAD 'http://maven.apiusage.com/repository/maven-public/com/google/google/1/google-1.pom'. Received status code 401 from server: Unauthorized
      > Could not resolve com.google.protobuf:protobuf-java:2.6.1.
         > Could not parse POM https://jcenter.bintray.com/com/google/protobuf/protobuf-java/2.6.1/protobuf-java-2.6.1.pom
            > Could not download google.pom (com.google:google:1)
               > Could not get resource 'http://maven.apiusage.com/repository/maven-public/com/google/google/1/google-1.pom'.
                  > Could not HEAD 'http://maven.apiusage.com/repository/maven-public/com/google/google/1/google-1.pom'. Received status code 401 from server: Unauthorized
      > Could not resolve com.google.protobuf:protobuf-java:2.6.1.
         > Could not parse POM https://jcenter.bintray.com/com/google/protobuf/protobuf-java/2.6.1/protobuf-java-2.6.1.pom
            > Could not download google.pom (com.google:google:1)
               > Could not get resource 'http://maven.apiusage.com/repository/maven-public/com/google/google/1/google-1.pom'.
                  > Could not HEAD 'http://maven.apiusage.com/repository/maven-public/com/google/google/1/google-1.pom'. Received status code 401 from server: Unauthorized

**Comment by Bartvhelvert** [comment]
I am having the same issue on my public repo, even though I can download the files through my browser Gradle will fail at the unauthorized message.

**Comment by TrueDevProfile** [comment]
The same issue with my repo

**Comment by nre-ableton** [comment]
ping @jitpack-io -- please have a look

**Comment by nre-ableton** [comment]
> I am having the same issue on my public repo, even though I can download the files through my browser Gradle will fail at the unauthorized message.
> 
> I am trying to access 'https://jitpack.io/com/github/guthix/Jagex-ByteBuf/ff61704caa/Jagex-ByteBuf-ff61704caa.jar' on gradle version 5.6.4.

FWIW, that is not the case for me. Our public artifacts return 401, both from gradle and a web browser, and both for `jitpack.io` and `www.jitpack.io`.

**Comment by jitpack-io** [comment]
Hi all,

There was an issue connecting to GitHub at the time which made JitPack assume it was a private repository.

**Comment by ligi** [comment]
@jitpack-io seems this happened again?:

```
* What went wrong:
Could not determine the dependencies of task ':android:kaptForFDroidDebugKotlin'.
> Could not resolve all task dependencies for configuration ':android:kapt'.
   > Could not resolve com.github.hotchemi:permissionsdispatcher-processor:4.6.0.
     Required by:
         project :android
      > Could not resolve com.github.hotchemi:permissionsdispatcher-processor:4.6.0.
         > Could not get resource 'https://jitpack.io/com/github/hotchemi/permissionsdispatcher-processor/4.6.0/permissionsdispatcher-processor-4.6.0.pom'.
            > Could not GET 'https://jitpack.io/com/github/hotchemi/permissionsdispatcher-processor/4.6.0/permissionsdispatcher-processor-4.6.0.pom'. Received status code 401 from server: Unauthorized

```

**Comment by brandikun** [comment]
@jitpack-io This is happening for me as well on a public repo


```
org.gradle.api.resources.ResourceException: Could not get resource 'https://jitpack.io/com/github/stephenc/jcip/jcip-annotations/1.0-1/jcip-annotations-1.0-1.pom'. 
org.gradle.internal.resource.transport.http.HttpErrorStatusCodeException: Could not GET 'https://jitpack.io/com/github/stephenc/jcip/jcip-annotations/1.0-1/jcip-annotations-1.0-1.pom'. Received status code 401 from server: Unauthorized |  
org.gradle.api.resources.ResourceException: Could not get resource 'https://jitpack.io/com/github/stephenc/jcip/jcip-annotations/1.0-1/jcip-annotations-1.0-1.pom'. |  
org.gradle.internal.resource.transport.http.HttpErrorStatusCodeException: Could not GET 'https://jitpack.io/com/github/stephenc/jcip/jcip-annotations/1.0-1/jcip-annotations-1.0-1.pom'. Received status code 401 from server: Unauthorized |  
```

**Comment by ToxicMushroom** [comment]
I'm also getting this

**Comment by phanirithvij** [comment]
This still occurs after one year.
```
[   +1 ms] > Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
[   +9 ms]    > Could not resolve com.github.phanirithvij:bubbles:1.2.1.
[   +2 ms]      Required by:
[   +2 ms]          project :app
[   +6 ms]       > Could not resolve com.github.phanirithvij:bubbles:1.2.1.
[   +1 ms]          > Could not get resource 'https://jitpack.io/com/github/phanirithvij/bubbles/1.2.1/bubbles-1.2.1.pom'.
[   +3 ms]             > Could not GET 'https://jitpack.io/com/github/phanirithvij/bubbles/1.2.1/bubbles-1.2.1.pom'. Received status code 401 from server: Unauthorized
[   +2 ms] * Try:
```

**Comment by fanzhiri** [comment]
> @jitpack-io This is happening for me as well on a public repo
> 
> ```
> org.gradle.api.resources.ResourceException: Could not get resource 'https://jitpack.io/com/github/stephenc/jcip/jcip-annotations/1.0-1/jcip-annotations-1.0-1.pom'. 
> org.gradle.internal.resource.transport.http.HttpErrorStatusCodeException: Could not GET 'https://jitpack.io/com/github/stephenc/jcip/jcip-annotations/1.0-1/jcip-annotations-1.0-1.pom'. Received status code 401 from server: Unauthorized |  
> org.gradle.api.resources.ResourceException: Could not get resource 'https://jitpack.io/com/github/stephenc/jcip/jcip-annotations/1.0-1/jcip-annotations-1.0-1.pom'. |  
> org.gradle.internal.resource.transport.http.HttpErrorStatusCodeException: Could not GET 'https://jitpack.io/com/github/stephenc/jcip/jcip-annotations/1.0-1/jcip-annotations-1.0-1.pom'. Received status code 401 from server: Unauthorized |  
> ```

me too

**Comment by jimblackler** [comment]
I am also seeing this issue on a public repo.

**Comment by bidadh** [comment]
I have the same issue

**Comment by Vlad-M-1** [comment]
I have the same issue

**Comment by chriscoomber** [comment]
I'm seeing this currently with https://jitpack.io/#CanHub/Android-Image-Cropper
e.g. https://jitpack.io/com/github/Canato/Android-Image-Cropper/3.0.0/Android-Image-Cropper-3.0.0.pom asks me for username and password, despite this being a public repo.

**Comment by bidadh** [comment]
any updates on this issue ?

**Comment by bidadh** [comment]
such a bad support! Started getting 401 and 403 errors which stops me doing my job and even subscription didn't help! what am I supposed to do ?

**Comment by jahnical** [comment]
Still getting the same problem:

Could not GET 'https://jitpack.io/com/github/stealthcopter/AndroidNetworkTolls/0.4.5.3/AndroidNetworkTolls-0.4.5.3.pom'. Received status code 401 from server: Unauthorized

**Comment by breskeby** [comment]
same here for me when trying to resolve this from gradle 7.1.1:

```
      > Could not resolve com.github.breskeby:rewrite-rules:1.0.
         > Could not get resource 'https://jitpack.io/com/github/breskeby/rewrite-rules/1.0/rewrite-rules-1.0.pom'.
            > Could not GET 'https://jitpack.io/com/github/breskeby/rewrite-rules/1.0/rewrite-rules-1.0.pom'. Received status code 401 from server: Unau
```

**Comment by RewardzSG** [comment]
I am also getting the same issue.

Could not HEAD 'https://jitpack.io/com/github/RewardzSG/RewardsSdk/v1.3/RewardsSdk-v1.3.pom'. Received status code 401 from server: Unauthorized
Disable Gradle 'offline mode' and sync project


Is there something I can do to resolve this.

**Comment by summer-zhoujie** [comment]
any update?

**Comment by aakash-jain-sopra** [comment]
Any updates ?

**Comment by daimonkor** [comment]
Please check the same error

```Could not GET 'https://jitpack.io/com/github/icebergteam/mupdf-android-viewer/1.19.1/mupdf-android-viewer-1.19.1.pom'. Received status code 401 from server: Unauthorized```

**Comment by dazjean** [comment]
How to resove this problem? now a day is 2022

**Comment by jitpack-io** [comment]
Hi @daimonkor 
That project has a submodule pointing to a private repository https://github.com/icebergteam/mupdf-android-viewer/blob/master/.gitmodules 
As a result JitPack can't clone it and returns 401.

**Comment by MihailYa** [comment]
Had the same issue with `com.github.barteksc:android-pdf-viewer:2.8.2`

Fixed by adding `gradlePluginPortal()` into repositories list in project gradle:

```
allprojects {
  repositories {
    google()
    mavenCentral()
    maven { url 'https://jitpack.io' }
    gradlePluginPortal()
  }
}
```

[Source](https://github.com/barteksc/AndroidPdfViewer/issues/1076)

**Comment by soujiro32167** [comment]
401 on all artifacts here https://jitpack.io/#soujiro32167/zio-zip/0.0.2
sadness

**Comment by mpivchev** [comment]
Happens sometimes for our lib as well: https://jitpack.io/#DoubleSymmetry/KotlinAudio

**Comment by anupsamanta** [comment]
> Had the same issue with `com.github.barteksc:android-pdf-viewer:2.8.2`
> 
> Fixed by adding `gradlePluginPortal()` into repositories list in project gradle:
> 
> ```
> allprojects {
>   repositories {
>     google()
>     mavenCentral()
>     maven { url 'https://jitpack.io' }
>     gradlePluginPortal()
>   }
> }
> ```
> 
> [Source](https://github.com/barteksc/AndroidPdfViewer/issues/1076)

Thanks. It worked like a charm in React-Native App.

**Comment by rohith-thummanapally** [comment]
Hi I am trying to build the android apk and I am on expo eas setup, I am also getting the same error

Could not GET 'https://www.jitpack.io/com/github/barteksc/android-pdf-viewer/3.1.0-beta.1/android-pdf-viewer-3.1.0-beta.1.pom'. Received status code 401 from server: Unauthorized

I won't have gradle file , how can I resolve the issue?

**Comment by soujiro32167** [comment]
ok, figured it out: the jitpack UI gives the wrong sbt coordinates.

For example: https://jitpack.io/#soujiro32167/zio-zip/0.1.0

gives: `libraryDependencies += "com.github.soujiro32167" % "zio-zip" % "Tag"`

however, if you go to the exact `Release` and click on `Get It`, the coordinate is correct:

`libraryDependencies += "com.github.soujiro32167.zio-zip" % "zio-zip_3" % "v0.1.0" `

**Comment by stereodenis** [comment]
It's not stale

**Comment by BWMuller** [comment]
Sad that this issue still exists since 2019

**Comment by seailz** [comment]
ugh... same issue

**Comment by d-costa** [comment]
Facing the same issue

**Comment by dabichosilva** [comment]
2023 and this still happens. I assume is a "hiccup" in the service, and it should be back online after some time.
Strangest thing is that a build succeeded, and a few hours later, the same pipeline failed with this error.

**Comment by stonefarmer9** [comment]
Currently having the same issue as @dabichosilva, built fine locally and in appcenter on wednesday, thursday through to today getting:


 > Could not resolve all files for configuration ':app:releaseRuntimeClasspath'.
   > Could not resolve com.github.barteksc:android-pdf-viewer:2.8.2.
     Required by:
         project :app > project :react-native-view-pdf
      > Could not resolve com.github.barteksc:android-pdf-viewer:2.8.2.
         > Could not get resource 'https://www.jitpack.io/com/github/barteksc/android-pdf-viewer/2.8.2/android-pdf-viewer-2.8.2.pom'.
            > Could not GET 'https://www.jitpack.io/com/github/barteksc/android-pdf-viewer/2.8.2/android-pdf-viewer-2.8.2.pom'. Received status code 401 from server: Unauthorized


Have used GradlePluginPortal and did not resolve the issue.

**Comment by JumperOnJava** [comment]
same issue

**Comment by PavlovVladimir** [comment]
Same issue on another public repo. Have used GradlePluginPortal doesn't help resolve issue.

**Comment by SoulForeverInPeace** [comment]
Same problem

**Comment by luchonetvvni** [comment]
The same problem but with private repository... How can to resolve the problem?

**Comment by h3clikejava** [comment]
The same problem but with private repository... Using Token, it worked normally yesterday, but not today. How can to resolve the problem?

**Comment by Daniel-Kang-FFX** [comment]
The same issue happened on another public repo. 
▸ > Could not GET '[https://jitpack.io/com/github/chartbeat/android_sdk/v1.6.7/android_sdk-v1.6.7.pom'](https://jitpack.io/com/github/chartbeat/android_sdk/v1.6.7/android_sdk-v1.6.7.pom). Received status code 401 from server: Unauthorized

**Comment by andriishpek-sigma** [comment]
The same problem with public repo https://github.com/GIGAMOLE/ComposeCollapsingToolbar

<img width="1159" alt="image" src="https://github.com/jitpack/jitpack.io/assets/89791149/fdd7555f-c724-4e4b-89e7-9b74ff215044">

**Comment by tiferet-blazepod** [comment]
Happening to me as well, when using git actions... locally it works great, but when running the cd using github actions it cannot retreive it and fails...
`Could not GET 'https://jitpack.io/com/github/zyyoona7/pickerview/1.0.9/pickerview-1.0.9.pom'. Received status code 401 from server: Unauthorized`

**Comment by MacaulayKoontz** [comment]
Happening to me as well. 

`              > Could not resolve com.github.leancode:patrol:3.9.0.
                 > Could not get resource 'https://jitpack.io/com/github/leancode/patrol/3.9.0/patrol-3.9.0.pom'.
                    > Could not GET 'https://jitpack.io/com/github/leancode/patrol/3.9.0/patrol-3.9.0.pom'. Received status code 401 from server: Unauthorized
`

**Comment by techxiji** [comment]
this issue still happening. I've tried add token in maven settings but still doesn't work.
speechless.

**Comment by tamimattafi** [comment]
Same issue, happening today

**Comment by pinomartin** [comment]
> Same issue, happening today
  Required by:
         project :app > project :react-native-pdf
  > Could not resolve com.github.barteksc:android-pdf-viewer:3.1.0-beta.1.
         > Could not get resource 'https://jitpack.io/com/github/barteksc/android-pdf-viewer/3.1.0-beta.1/android-pdf-viewer-3.1.0-beta.1.pom'.
            > Could not GET 'https://jitpack.io/com/github/barteksc/android-pdf-viewer/3.1.0-beta.1/android-pdf-viewer-3.1.0-beta.1.pom'. Received status code 401 from server: Unauthorized

**Comment by AntineutronVS** [comment]
Same issue. Build through the code magic:

> * What went wrong:
Execution failed for task ':app:mapReleaseSourceSetPaths'.
> Could not resolve all files for configuration ':app:releaseRuntimeClasspath'.
   > Could not resolve com.github.barteksc:android-pdf-viewer:3.0.0-beta.4.
     Required by:
         project :app > project :pdf_viewer_plugin
      > Could not resolve com.github.barteksc:android-pdf-viewer:3.0.0-beta.4.
         > Could not get resource 'https://www.jitpack.io/com/github/barteksc/android-pdf-viewer/3.0.0-beta.4/android-pdf-viewer-3.0.0-beta.4.pom'.
            > Could not GET 'https://www.jitpack.io/com/github/barteksc/android-pdf-viewer/3.0.0-beta.4/android-pdf-viewer-3.0.0-beta.4.pom'. Received status code 401 from server: Unauthorized

**Comment by techxiji** [comment]
My workaroud: Fork / clone the original repo and push it to your own github repo, wait a second then try search it on jitpack.

**Comment by befstrat1969** [comment]
Same issue. I get 401 both from gradle and browser when downloading pom dependencies. Tried both www.jitpack.io and jitpack.io

**Comment by tamimattafi** [comment]
Not stale

**Comment by ericmadson** [comment]
Same issue. None of the workarounds commented here could help me

**Comment by Tavorc** [comment]
I have same issue now.
any idea how to solve it?

**Comment by befstrat1969** [comment]
I had the same issue last week (see my previous comment) and it was resolved automatically next day...
I guess that it will also be resolved again by the jitpack team, but it's really very frustrating to have the same issue appearing again and again to a repo so widely used... Jitpack team, please, find a correct and stable solution for this...

**Comment by gogetsu4024** [comment]
Same issue today 
Any ideas ? 
Could not GET 'https://jitpack.io/com/github/barteksc/android-pdf-viewer/2.6.1/android-pdf-viewer-2.6.1.pom'. Received status code 401 from server: Unauthorized

**Comment by hb-yashr** [comment]
> Same issue today Any ideas ? Could not GET 'https://jitpack.io/com/github/barteksc/android-pdf-viewer/2.6.1/android-pdf-viewer-2.6.1.pom'. Received status code 401 from server: Unauthorized

Did you find any solution, getting same error!!

**Comment by mamali** [comment]
Same issue today
Any ideas ?

**Comment by Tavorc** [comment]
The solution that works for me is: i downloaded the files of the library and put it locally in my repo. Not the best solution but for now it's fine.

**Comment by gogetsu4024** [comment]
@hb-yashr 
So what worked for me is to use a fork that i found of the library 
for some reason the only binaries that work here are from version 3 

i'm originally using 2.6.0 and considering it's a major version change some issues might pop up 
i'm using it as part of https://github.com/idnow/de.idnow.android and so far it seems fine

Instructions : 

added this to android/build.gradle

allprojects {
    configurations {
        all {
            resolutionStrategy {
                dependencySubstitution {
                    substitute(module("com.github.barteksc:android-pdf-viewer"))
                            .using(module("com.github.mhiew:android-pdf-viewer:3.2.0-beta.3"))
                            .because("401 error in main repo")
                }
            }
        }
    }
}

**Comment by ivydag** [comment]
The solution provided by [gogetsu4024](https://github.com/gogetsu4024) is working for me, but I'm also having the same issue with two other libraries: com.theartofdev.edmodo:android-image-cropper:2.8.0 and me.dm7.barcodescanner:zxing:1.9.13. Does anyone know why this is happening?

**Comment by hb-yashr** [comment]
> sunsetting

Thanks for the solution. I will surely check this out. But I have one question. I am facing this error only on the laptop in which project was not setup earlier. The project is working and building quite well in the laptop in which it was developed.
I also tried to delete .gradle folder and Invalidated the caches, but still the project builds perfectly there. From where it is taking the data then??

**Comment by befstrat1969** [comment]
Gradle caches downloaded dependencies on <user_root>/.gradle/caches/modules-2/files-2.1
So it takes them from there.

**Comment by hb-yashr** [comment]
> Gradle caches downloaded dependencies on <user_root>/.gradle/caches/modules-2/files-2.1 So it takes them from there.

Yes just founded, by thanks for replying.

**Comment by iip-ritase** [comment]
> Same issue today Any ideas ? Could not GET 'https://jitpack.io/com/github/barteksc/android-pdf-viewer/2.6.1/android-pdf-viewer-2.6.1.pom'. Received status code 401 from server: Unauthorized

me too
how to fix this?

**Comment by aemreesen27** [comment]
> > Same issue today Any ideas ? Could not GET 'https://jitpack.io/com/github/barteksc/android-pdf-viewer/2.6.1/android-pdf-viewer-2.6.1.pom'. Received status code 401 from server: Unauthorized
> 
> me too how to fix this?

* Clone the library
* Create an AAR output -> `./gradlew assembleRelease`
* It will create an AAR in this directory for you -> library/build/outputs/aar/example.aar
* Create a folder named **libs** in your project.
* Move your AAR file to the **libs** folder and add it as a dependency -> 
```
repositories {
    flatDir {
        dirs 'libs'
    }
}

dependencies {
    implementation(name: 'example', ext: 'aar')
}
```

**Comment by ngocdiep23** [comment]
Same issue today. Any ideas?
I have errors with another libs of jitpack.io too.

**Comment by usamayasin** [comment]
I am facing the same issue for this `com.github.florent37:inline-activity-result-kotlin:1.0.4`

Any solution for this ? 
I am getting `Received status code 401 from server: Unauthorized`

@jitpack-io

**Comment by befstrat1969** [comment]
As @vrozin said, the reason is the sunsetting of JCenter. Now I'll try to give more details about the 4th option he proposes, that is copying the package to you own repository.
First of all, the proposed solution works if somehow you do have access to the packages. The solution works if someone else in your team had already the project setup and working, and you just cloned it from a repo and you can't build it, or if you have the project building at your old computer and you want to transfer it to a new one. In all these cases the missing packages are already downloaded and cached at the gradle folder and more specificaly at <user_root>/.gradle/caches/modules-2/files-2.1 (of the computer that can build the project) In order to copy them to your computer you must follow these steps:

At the <user_root>/.gradle/ folder create a new directory named "init.d"  and there create a new file named "offline.gradle" with the following content
`def reposDir = new File(System.properties['user.home'], ".android/manual-offline-m2")
def repos = new ArrayList()
reposDir.eachDir {repos.add(it) }
repos.sort()
allprojects {
    buildscript {
        repositories {
            for (repo in repos) {
                maven {
                    name = "injected_offline_${repo.name}"
                    url = repo.toURI().toURL()
                }
            }
        }
    }
    repositories {
        for (repo in repos) {
            maven {
                name = "injected_offline_${repo.name}"
                url = repo.toURI().toURL()
            }
        }
    }
}`
This makes gradle take into account your local repositories.

Then go to <user_root>/.android and create a new folder named "manual-offline-m2" and inside it a new folder named "myRepo".
Now for each missing package create into myRepo all directory structure of the package name. For example for the most commonly missing package com.github.barteksc:android-pdf-viewer: 2.6.0 your directory structure should be:
manual-offline-m2>myRepo>com>github>barteksc
In this folder paste the contents of the original package (found on the working computer). Attention only the contents, not the package folder itself. So you should paste the "android-pdf-viewer" directory.
Opening this directory you should find another directory named after the version. So in our example you should find a directory "2.6.0". Open this directory. Inside you will find some directories (usually 4) named with strange hashes. Open each one of them and copy the content to the "2.6.0" directory. Then you can safely delete the hashes directories.
So the final structure for our example should be:
<user_root>/.android/manual-offline-m2/myRepo/com/github/barteksc/android-pdf-viewer/2.6.0 and in this folder there are the following files: android-pdf-viewer-2.6.0.aar, android-pdf-viewer-2.6.0.pom, android-pdf-viewer-2.6.0-javadoc.jar, android-pdf-viewer-2.6.0-sources.jar.
Do this for every missing dependency. After that android studio should be able to find the dependencies and build your project.

**Comment by Mr-Ramzan** [comment]
+1 for some libraries

**Comment by Muitsu** [comment]
Any workarounds? I've been stuck for a week and still haven't found a solution.

 Could not GET https://jitpack.io/com/github/barteksc/android-pdf-viewer/2.8.2/android-pdf-viewer-2.8.2.pom. Received status code 401 from server: Unauthorized

Caused by: org.gradle.api.resources.ResourceException: Could not get resource 'https://jitpack.io/com/github/barteksc/android-pdf-viewer/2.8.2/android-pdf-viewer-2.8.2.pom'.

Caused by: org.gradle.internal.resource.transport.http.HttpErrorStatusCodeException: Could not GET 'https://jitpack.io/com/github/warkiz/widget/indicatorseekbar/2.1.2/indicatorseekbar-2.1.2.pom'. Received status code 401 from server: Unauthorized

Caused by: org.gradle.internal.resolve.ModuleVersionResolveException: Could not resolve com.github.warkiz.widget:indicatorseekbar:2.1.2.

Caused by: org.gradle.api.resources.ResourceException: Could not get resource 'https://jitpack.io/com/github/warkiz/widget/indicatorseekbar/2.1.2/indicatorseekbar-2.1.2.pom'.

**Comment by usamayasin** [comment]
Try to search it on Jitpack.io and you will get these dependencies from there. I solved my issue using this approach. 
It will work 100%.  @Muitsu @Mr-Ramzan

**Comment by HimanshuNarang** [comment]
**Facing the same issue for below libs**

Failed to resolve: org.mockito.kotlin:mockito-kotlin:1.10.19
Failed to resolve: org.mockito:mockito-inline:1.10.19
Failed to resolve: com.amitshekhar.android:debug-db:1.0.6
Failed to resolve: com.beloo.widget:ChipsLayoutManager:0.3.7
Failed to resolve: dev.dworks.libs:astickyheader:0.1.0
Failed to resolve: com.firebase:firebase-jobdispatcher:0.8.6
Failed to resolve: com.github.barteksc:android-pdf-viewer:2.8.2

Any solution?

**Comment by M1ke** [comment]
I tried the suggested

```
 substitute(module("com.github.barteksc:android-pdf-viewer"))
                            .using(module("com.github.mhiew:android-pdf-viewer:3.2.0-beta.3"))
                            .because("401 error in main repo")
```

However when running `./gradlew build` the process raised an error

```
 Failed to apply plugin [class 'org.gradle.api.plugins.BasePlugin']
   > No signature of method: org.gradle.api.internal.artifacts.ivyservice.dependencysubstitution.DefaultDependencySubstitutions$1.using() is applicable for argument types: (org.gradle.internal.component.external.model.DefaultModuleComponentSelector) values: [com.github.mhiew:android-pdf-viewer:3.1.0-beta.1]
     Possible solutions: find(), use([Ljava.lang.Object;), print(java.io.PrintWriter), print(java.lang.Object), find(groovy.lang.Closure), wait()
```

This is running Gradle 5 which is quite old. I checked their docs and came up with

```
resolutionStrategy.eachDependency { DependencyResolveDetails details ->
                if (details.requested.name == 'android-pdf-viewer') {
                    details.useTarget "com.github.mhiew:android-pdf-viewer:3.2.0-beta.3"
                    details.because "401 error in main repo"
                }
            }
```

Which seems to serve the same purpose

**Comment by HimanshuNarang** [comment]
@M1ke thanks, I will try with resolution strategy but the issue is, for using this I have to find the alternative to all the dependencies I mentioned in the above comment

**Comment by ajdamiao** [comment]
Same problem here, with a lot of dependencies 
Could not resolve all files for configuration ':app:debugCompileClasspath'.
   > Could not find com.wang.avi:library:2.1.3.
     Required by:
         project :app
         
 Could not HEAD 'https://jitpack.io/com/github/florent37/runtime-permission-kotlin/1.0.1/runtime-permission-kotlin-1.0.1.pom'. Received status code 401 from server: Unauthorized

**Comment by dominikdoric** [comment]
Same issue today.
This issue has been raised 5 years ago and still there is no fix to this.

**Comment by ak40923** [comment]
> The solution provided by [gogetsu4024](https://github.com/gogetsu4024) is working for me, but I'm also having the same issue with two other libraries: com.theartofdev.edmodo:android-image-cropper:2.8.0 and me.dm7.barcodescanner:zxing:1.9.13. Does anyone know why this is happening?

Same issue, any fix?

**Comment by Mehdi-KHALFALLAH** [comment]
same issue

**Comment by zeleng** [comment]
the same issue for the last 2 days

**Comment by tdinckaya** [comment]
same problem ?

Could not determine the dependencies of task ':app:mergeReleaseNativeLibs'.
> Could not resolve all task dependencies for configuration ':app:releaseRuntimeClasspath'.
   > Could not resolve com.redmadrobot:inputmask:4.1.0.
     Required by:
         project :app > project :react-native-text-input-mask
      > Could not resolve com.redmadrobot:inputmask:4.1.0.
         > Could not get resource 'https://www.jitpack.io/com/redmadrobot/inputmask/4.1.0/inputmask-4.1.0.pom'.
            > Could not GET 'https://www.jitpack.io/com/redmadrobot/inputmask/4.1.0/inputmask-4.1.0.pom'. Received status code 401 from server: Unauthorized

**Comment by dhpanteon** [comment]
Same issue with 
https://jitpack.io/io/github/sac/SocketclusterClientJava/2.0.0/SocketclusterClientJava-2.0.0.pom

**Comment by vitaminwater** [comment]
Looks like it's still there today:

```
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve me.carda:AndroidAwnCore:[0.9.3, 0.10.0).
     Required by:
         project :app > project :awesome_notifications
      > Failed to list versions for me.carda:AndroidAwnCore.
         > Unable to load Maven meta-data from https://jitpack.io/me/carda/AndroidAwnCore/maven-metadata.xml.
            > Could not HEAD 'https://jitpack.io/me/carda/AndroidAwnCore/maven-metadata.xml'. Received status code 401 from server: Unauthorized
      > Failed to list versions for me.carda:AndroidAwnCore.
         > Unable to load Maven meta-data from https://jitpack.io/me/carda/AndroidAwnCore/maven-metadata.xml.
            > Could not HEAD 'https://jitpack.io/me/carda/AndroidAwnCore/maven-metadata.xml'. Received status code 401 from server: Unauthorized
```
