### ISSUE TITLE
iBotPeaches/apktool build

### ISSUE THREAD

**Issue by omervk** [jitpack/jitpack.io#404]
Hi guys,

These builds no longer work. I used 2.0.2 on December 27th and it worked well. Today I tried both that and 2.0.3 and the build failed to create artifacts. It looks like the build itself is failing with 2.0.3, but 2.0.2 is no longer building (regression?).

Thanks!

Logs:
1. https://jitpack.io/com/github/iBotPeaches/Apktool/2.0.2/build.log
2. https://jitpack.io/com/github/iBotPeaches/Apktool/2.0.3/build.log

**Comment by jitpack-io** [comment]
Hi

2.0.3 seems to have compile errors and that's why it doesn't work.
2.0.2 was fine but it it was showing up as a failed build. Fixed that. Does it work for you now?

**Comment by omervk** [comment]
Works great now, thank you!

Relevant: https://github.com/iBotPeaches/Apktool/issues/1142

**Comment by omervk** [comment]
Looks like that project has more build steps to it. Any chance of supporting them?
