### ISSUE TITLE
Build too long. Can't see logs page during build.

### ISSUE THREAD

**Issue by codeerow** [jitpack/jitpack.io#4040]
Hi, guys. I have been released new version of https://github.com/codeerow/spirit
But build is too slow and i can't see logs during the building. 

For other libraries appear similar issue: it builds too long, can't see logs and after build is successful i can't use library in 30 minutes or like that.

**Comment by fractalpixel** [comment]
Had the same issue with my libs.  The jitpack status page seems to indicate they had/have some problems with their servers: https://status.jitpack.io/

**Comment by xiaojinzi123** [comment]
我也有同样的问题呀！！！
