### ISSUE TITLE
The build succeeded but `No build artifacts found`

### ISSUE THREAD

**Issue by fracassi-marco** [jitpack/jitpack.io#4045]
Hello, the build succeeded but `No build artifacts found`

- https://jitpack.io/com/github/fracassi-marco/daikon/0.2.8/build.log

- Run on my machine with `./gradlew clean -Pgroup=com.github.fracassi-marco -Pversion=0.2.8 -xtest build publishToMavenLocal` and output
```
BUILD SUCCESSFUL in 2s
4 actionable tasks: 3 executed, 1 up-to-date
```
- Th error is `ERROR: No build artifacts found`

Thank you!

**Comment by jitpack-io** [comment]
Hi,

Seems like it's fixed in a newer version.
Thanks for reaching out!
