### ISSUE TITLE
mobile-automation-util/v1.8 build

### ISSUE THREAD

**Issue by MohanadRiziq** [jitpack/jitpack.io#405]
Log https://jitpack.io/com/github/AspireInfotech/mobile-automation-util/v1.8/build.log

**Comment by jitpack-io** [comment]
Hi @MohanadRiziq 

Looks like the build couldn't find a this class from Guava:
```
com/google/common/util/concurrent/MoreExecutors
```
Does mvn install succeed locally for you?

**Comment by MohanadRiziq** [comment]
Hi,

It's work perfectly locally
