### ISSUE TITLE
Could not resolve all files for configuration. (Kotlin multi-platform)

### ISSUE THREAD

**Issue by shanling** [jitpack/jitpack.io#4052]
**Log:** [https://jitpack.io/tools/stellark/kotlin-xdr/master-34e7f5d8ca-1/build.log](https://jitpack.io/tools/stellark/kotlin-xdr/master-34e7f5d8ca-1/build.log)

```
Execution failed for task ':compileKotlinJs'.
> Could not resolve all files for configuration ':jsCompileClasspath'.
   > Could not find tools.stellark.kotlin-xdr:kotlin-xdr-js:0.0.2-SNAPSHOT.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/tools/stellark/kotlin-xdr/kotlin-xdr-js/0.0.2-SNAPSHOT/maven-metadata.xml
       - https://repo.maven.apache.org/maven2/tools/stellark/kotlin-xdr/kotlin-xdr-js/0.0.2-SNAPSHOT/kotlin-xdr-js-0.0.2-SNAPSHOT.module
       - https://repo.maven.apache.org/maven2/tools/stellark/kotlin-xdr/kotlin-xdr-js/0.0.2-SNAPSHOT/kotlin-xdr-js-0.0.2-SNAPSHOT.pom
       - https://oss.sonatype.org/content/repositories/snapshots/tools/stellark/kotlin-xdr/kotlin-xdr-js/0.0.2-SNAPSHOT/maven-metadata.xml
       - https://oss.sonatype.org/content/repositories/snapshots/tools/stellark/kotlin-xdr/kotlin-xdr-js/0.0.2-SNAPSHOT/kotlin-xdr-js-0.0.2-SNAPSHOT.module
       - https://oss.sonatype.org/content/repositories/snapshots/tools/stellark/kotlin-xdr/kotlin-xdr-js/0.0.2-SNAPSHOT/kotlin-xdr-js-0.0.2-SNAPSHOT.pom
       - https://jcenter.bintray.com/tools/stellark/kotlin-xdr/kotlin-xdr-js/0.0.2-SNAPSHOT/maven-metadata.xml
       - https://jcenter.bintray.com/tools/stellark/kotlin-xdr/kotlin-xdr-js/0.0.2-SNAPSHOT/kotlin-xdr-js-0.0.2-SNAPSHOT.module
       - https://jcenter.bintray.com/tools/stellark/kotlin-xdr/kotlin-xdr-js/0.0.2-SNAPSHOT/kotlin-xdr-js-0.0.2-SNAPSHOT.pom
       - https://jitpack.io/tools/stellark/kotlin-xdr/kotlin-xdr-js/0.0.2-SNAPSHOT/maven-metadata.xml
       - https://jitpack.io/tools/stellark/kotlin-xdr/kotlin-xdr-js/0.0.2-SNAPSHOT/kotlin-xdr-js-0.0.2-SNAPSHOT.module
       - https://jitpack.io/tools/stellark/kotlin-xdr/kotlin-xdr-js/0.0.2-SNAPSHOT/kotlin-xdr-js-0.0.2-SNAPSHOT.pom
     Required by:
         project : > tools.stellark.kotlin-xdr:kotlin-xdr:master-SNAPSHOT
```

<img width="581" alt="Screen Shot 2019-11-07 at 11 13 28 PM" src="https://user-images.githubusercontent.com/4241774/68457081-43b68e80-01b4-11ea-8da3-c5c7de46a683.png">

What is strange is that the maven metadata, module and pom all seem to be hosted correctly (e.g. [https://jitpack.io/tools/stellark/kotlin-xdr/kotlin-xdr-js/master-34e7f5d8ca-1/maven-metadata-local.xml](https://jitpack.io/tools/stellark/kotlin-xdr/kotlin-xdr-js/master-34e7f5d8ca-1/maven-metadata-local.xml)), but it cannot find it within jitpack when trying to get the dependency for some reason.

The project I built and hosted on Jitpack is a Kotlin multiplatform project with jvm and js targets. The project I am trying to use it in is a Kotlin Multiplatform project as well. Relevant `build.gradle.kts` file (some things omitted for brevity):

```
repositories {
    mavenCentral()
    maven(url = "https://oss.sonatype.org/content/repositories/snapshots/")
    jcenter()
    maven (url="https://jitpack.io")
}

kotlin {
    jvm()
    js()

    sourceSets {
        val commonMain by getting {
            //some things omitted for brevity
            implementation("tools.stellark.kotlin-xdr:kotlin-xdr:master-SNAPSHOT")
        }
    }
}
```

It correctly assigns the `metadata` artifact to `common`, the `jvm` artifact to `jvmMain`, and the `js` artifact to `jsMain`, but can't seem to actually resolve the artifact itself. I manually downloaded the artifact from the latest build from jitpack and checked that the contents were built properly, and they were.

Not sure where to go from here when debugging. 🤔

**Comment by rnett** [comment]
Take a look at https://github.com/jitpack/jitpack.io/issues/4091#issuecomment-562824426, does that work for you?

**Comment by andylamax** [comment]
This problem still persist even for me. I also have multiplatform libs with jvm, android and js targets. Still gradle won't resolve. It has something to do with jitpack deleting metadata from pom files. (Not sure if I got that correct)

**Comment by DetachHead** [comment]
@andylamax maybe give this a shot https://github.com/jitpack/jitpack.io/issues/3853#issuecomment-816067194
