### ISSUE TITLE
Gradle wrapper version needs an update

### ISSUE THREAD

**Issue by MohamedWael** [jitpack/jitpack.io#4055]
**Describe the bug**
When trying to build a project with a gradle wrapper version 5.4.1, the failure report states that the current gradle wrapper version is 4.8.1.

Check the [failure report](https://jitpack.io/com/github/MohamedWael/UtilsLibrary/master-a3dd0f8b6a-1/build.log)

**To Reproduce**
1. Go to https://jitpack.io
2. try to build the master branch of the project `MohamedWael/UtilsLibrary`
3. find the failure report

**Expected behavior**
Gradle wrapper version updated to the latest version 5.4.1 at the time of this issue

**Comment by jitpack-io** [comment]
Hi,

Would recommend adding the Gradle wrapper to your git repository

**Comment by MohamedWael** [comment]
Thanks, I added it since that and it worked
