### ISSUE TITLE
Timeout when downloading libraries from organization repo

### ISSUE THREAD

**Issue by mufit-developer** [jitpack/jitpack.io#4056]
**Describe the bug**
We granted a read access to my organization repository on gitlab.com on 8 November 2019, and was able to download our libraries using Gradle. But suddenly it is no longer working, and jitpack is unable to perform lookup on those repositories, even on previously built artifacts.  

Running `./gradlew assembleDebug --debug` on our Android project will also return a SocketTimeoutException. However, not all libraries are affected.

**To Reproduce**
1. Go to https://www.jitpack.io/com/gitlab/mufit-tech/mufit-android-communications/communications/0.3.2/communications-0.3.2.pom
2. No errors are returned - previously it would redirect to jitpack authorization page.
3. Alternatively, go to https://jitpack.io/com/gitlab/mufit-tech/mufit-android-communications/0.3.0/build.log. This was accessible when we first built the artifacts with jitpack

**Expected behavior**
Able to lookup our repositories on jitpack.io and download it using gradle.

**Screenshots**
![image](https://user-images.githubusercontent.com/56709969/68573868-3b53a180-049b-11ea-8c45-1f760cc4f29c.png)
Unable to lookup our library.

![image](https://user-images.githubusercontent.com/56709969/68573906-57574300-049b-11ea-8579-5a21d411b6c0.png)
For comparison, this is our other library

**Additional context**

**Comment by mufit-developer** [comment]
Not sure if this helps -- but we just received an error when looking up the repo

![image](https://user-images.githubusercontent.com/56709969/68574197-f4b27700-049b-11ea-8727-165f6b313f33.png)

**Comment by jitpack-io** [comment]
Hi,

What does it show you if you open:
https://jitpack.io/com/gitlab/mufit-tech/mufit-android-communications/0.3.0/build.log
in the browser?
We've checked your account and it should have access.

**Comment by mufit-developer** [comment]
Hi, it's working now!

We're not sure what happened before -- but thanks for your help!
