### ISSUE TITLE
Maven build successful, but reported as error by JitPack

### ISSUE THREAD

**Issue by heinrichreimer** [jitpack/jitpack.io#4058]
Link to build log: https://jitpack.io/com/github/mam10eks/jtreceval/-8e8dbe0f26-1/build.log

Does the project build on your machine with **the same** commands (e.g. ./gradlew install)? Yes

What error are you seeing?
- Build exited with code 0
- Artifacts found

**Comment by jitpack-io** [comment]
Hi,

The build seems ok now.
