### ISSUE TITLE
common.android.utils/0.3.4 build

### ISSUE THREAD

**Issue by kibotu** [jitpack/jitpack.io#406]
Log https://jitpack.io/com/github/kibotu/common.android.utils/0.3.4/build.log

ok what's wrong? it states Build Successful but i can't use it :(

**Comment by jitpack-io** [comment]
Hi

It seems the dots in the project name triggered a bug on jitpack side. Looking into it

**Comment by jitpack-io** [comment]
Ok, fixed and rebuilt. Should be available now.
