### ISSUE TITLE
ERROR: No build artifacts found

### ISSUE THREAD

**Issue by DeMoss15** [jitpack/jitpack.io#4067]
- Link to build log from https://jitpack.io
https://jitpack.io/com/github/DeMoss15/PaginatorRenderKit/1.0-prealpha1/build.log

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?
Yes, everything works fine on the my machine

- What error are you seeing?
ERROR: No build artifacts found
after successful build...

Gradle version 5.4.2
I've followed the [tutorial](https://medium.com/@erluxman/publishing-java-android-kotlin-libraries-on-jitpack-b33d0d26dc8a) from the documentation to publish my lib.

**Comment by DeMoss15** [comment]
seems it was my fault. I've missed that in the library's build.gradle file was 
`apply plugin: 'com.android.application'`
instead of
`apply plugin: 'com.android.library'`

sorry for the issue

**Comment by jitpack-io** [comment]
Looks like the [android-maven-gradle-plugin](https://github.com/dcendents/android-maven-gradle-plugin) does not support Gradle 5.
They recommend using https://github.com/sky-uk/gradle-maven-plugin instead

At the moment to use it, you'd have to use custom build commands in jitpack.yml:
```yml
install:
   - ./gradlew publish -PmavPublishToMavenLocal=true
```
