### ISSUE TITLE
Private Artifactory sharing issue

### ISSUE THREAD

**Issue by lostlegacy** [jitpack/jitpack.io#4069]
Hi, I'm trying to make one of my library private (has multiple transitive dependencies to another public jitpack/non jitpack library) by making it private repository on github and making the artifact private as well which I expect this library can only be downloaded if there’s authToken provided. but when I tried it on my android project without providing any authToken, it’s still working, i need to prevent this action from happen. I’ve set the artifactory sharing options to private (represented by the locked padlock icon). what did I do wrong?

**Steps to reproduce the behavior:**
1.  click look up on private repository
2.  set sharing options to private, represented by locked padlock
3. project level .gradle
```
allprojects {
    repositories {
        google()
        jcenter()
        maven { url 'https://jitpack.io' } //no auth token provided
    }
}
```
4. define implementation in application level .gradle
`implementation "com.github.dudidam:xxxx:1.0.0"`

**Expected behavior**
without auth token provided the gradle sync should be fail, the gradle sync still success even if we dont provide the authToken.

**Additional context**
the library has dependency to another public jitpack artifactory

**Comment by lostlegacy** [comment]
@jitpack-io please me review this

**Comment by jitpack-io** [comment]
Hi,

Was the repository public initially and then converted to private?
Another thing to check is whether the artifact has been cached in Gradle (~/.gradle/caches). We recommend running Gradle with `--refresh-dependencies` in this case.
It would be great if you could send the repository details via Support button on our website. That way we can investigate.

**Comment by lostlegacy** [comment]
Hi, I have resolved this issue, so actually I'm trying to make a clone of my currently a public library, and make it a private version of it. but then when I implement the private one on my android project, the authentication not working. I resolve this by changing the package name in my manifest file.

**Comment by lostlegacy** [comment]
but I got another question, if i want to make my currently public library to be private. are there going to be a problem?
