### ISSUE TITLE
Jitpack has already paid for it, and the release has been successful. The authToken has been configured as OK, but it can't be pulled down. Error: unable to resolve dependency for is prompted. It can be used before

### ISSUE THREAD

**Issue by NBXXF** [jitpack/jitpack.io#4074]
Jitpack has already paid for it, and the release has been successful. The authToken has been configured as OK, but it can't be pulled down. Error: unable to resolve dependency for is prompted. It can be used before @jitpack-io

**Comment by jitpack-io** [comment]
Hi,

For issues regarding subscriptions we recommend opening a ticket via the Support button on jitpack.io

Thank you!
