### ISSUE TITLE
Wrong jdk used in the build log (8 instead of 13)

### ISSUE THREAD

**Issue by raffaeleragni** [jitpack/jitpack.io#4085]
Please provide:

- Link to build log from https://jitpack.io
https://jitpack.io/com/github/raffaeleragni/javalin-addons/1.1/build.log

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?
Yes

- What error are you seeing?
The jdk used in the build log is 8, but this project is built in travis using 13. Also the jitpack.yml is specifying openjdk13 in the project file.
Repo: https://github.com/raffaeleragni/javalin-addons

Thank you!

**Comment by Valkryst** [comment]
I'm also encountering this issue, where jitpack seems to ignore the `openjdk13` option in the `jitpack.yml` file.

### Links
* Build Log - https://jitpack.io/com/github/Valkryst/V2DSprite/770c5cf68f/build.log
* jitpack.yml - https://github.com/Valkryst/V2DSprite/commit/770c5cf68ff963114e5ab9466aa7ee65634df678
* Repository - https://github.com/Valkryst/V2DSprite
