### ISSUE TITLE
Sbt %% syntax for cross builds not working

### ISSUE THREAD

**Issue by nathaniel-may** [jitpack/jitpack.io#4086]
Github repo: https://github.com/nathaniel-may/functional-shuffle

build file dependency:
```
libraryDependencies += "com.github.nathaniel-may" %% "shuffle" % "2.0.0"
```
error:
```
Unable to find credentials for [JitPack @ jitpack.io].
```
when the package name changes...
build file dependency:
```
libraryDependencies += "com.github.nathaniel-may" %% "functional-shuffle" % "2.0.0"
```
error: 
```
sbt.librarymanagement.ResolveException: unresolved dependency: com.github.nathaniel-may#functional-shuffle_2.13;2.0.0: not found
```

This happens with both the github link and my custom domain.

- Jitpack build log: https://jitpack.io/com/nathanielmay/functional-shuffle/2.0.0/build.log

- The project builds and publishes with the same commands locally (as indicated in this [comment](https://github.com/jitpack/jitpack.io/issues/178#issuecomment-145487746)):
`sbt clean "++ 2.13.1" publishM2`
`sbt clean "++ 2.12.10" publishM2`

**Comment by derek9gag** [comment]
@jitpack-io  this is the same issue as #4006.

https://jitpack.io/com/nathanielmay/functional-shuffle_2.13/2.0.0/build.log
