### ISSUE TITLE
AndroidTampering/1.0.1 build

### ISSUE THREAD

**Issue by SandroMachado** [jitpack/jitpack.io#409]
Log https://jitpack.io/com/github/SandroMachado/AndroidTampering/1.0.1/build.log

**Comment by jitpack-io** [comment]
Hi

The build is failing with
```
Plugin is too old, please update to a more recent version, or set ANDROID_DAILY_OVERRIDE environment variable to "40f0794763bb6c2a2820ccba40ec0f171447c83"
```
Should work after upgrading the gradle android plugin to:
`classpath 'com.android.tools.build:gradle:2.0.0+'`
