### ISSUE TITLE
ERROR: No build artifacts found

### ISSUE THREAD

**Issue by hebing0305** [jitpack/jitpack.io#4095]
https://jitpack.io/com/github/hebing0305/AutoFit/v1.5/build.log

**Comment by jitpack-io** [comment]
Hi,

Seems like the `gradlew` script is not executable:
`./gradlew: Permission denied`

**Comment by AsfhtgkDavid** [comment]
> Hi,
> 
> Seems like the `gradlew` script is not executable: `./gradlew: Permission denied`

I have same problem [log](https://jitpack.io/com/github/AsfhtgkDavid/TaskProgressBar/72fa5df149/build.log). I don't understand, why isn't exec?
