### ISSUE TITLE
'Build took too long' even if succeeded in build.log

### ISSUE THREAD

**Issue by mariotaku** [jitpack/jitpack.io#41]
Here's an example. 
I use jitpack for this repo: https://github.com/uucky/ColorPicker-Android , the lastest version is 0.9.4.
I can see build succeeded in build log, https://jitpack.io/com/github/uucky/ColorPicker-Android/0.9.4/build.log
However, it shows 'Build took too long' on jitpack home page.

**Comment by jitpack-io** [comment]
Hi! Sorry about that, it should be ok now. Version 0.9.4 is available
