### ISSUE TITLE
 /script/buildit.sh: git: command not found

### ISSUE THREAD

**Issue by hannesa2** [jitpack/jitpack.io#4104]
To have a deterministic build, I use in my build some shell command like `date` `hostname` `git` `head` `cut` `cp` but all are unknown.

https://jitpack.io/com/github/hannesa2/android-database-sqlcipher/4.3.0.1/build.log

> Build starting...
> /script/buildit.sh: line 3: date: command not found
> /script/buildit.sh: line 3: hostname: command not found
> Start:
> Git:
> /script/buildit.sh: line 5: git: command not found
> /script/buildit.sh: line 6: git: command not found
> /script/buildit.sh: line 6: head: command not found
> /script/buildit.sh: line 6: cut: command not found
> 
> /script/buildit.sh: line 11: cp: command not found
> /script/buildit.sh: line 12: cd: /home/jitpack/build: No such file or directory
> /script/buildit.sh: line 19: dirname: command not found
> /script/buildit.sh: line 27: find: command not found
> Found gradle
> /script/buildit.sh: line 53: /home/jitpack/gradleb.sh: No such file or directory
> Build tool exit code: 0
> /script/buildit.sh: line 106: cp: command not found
> Looking for artifacts...
> /script/buildit.sh: line 110: gradle: command not found
> /script/buildit.sh: line 111: gradle: command not found
> 2019-12-22T09:50:50.872127887Z
> Exit code: 0
> 
> ERROR: No build artifacts found

I've no clue what's the root cause or how to solve it.
Maybe you have a hint for me

**Comment by jitpack-io** [comment]
Hi,

Those commands should be available to the build. How does your .jitpack.yml file look like?

**Comment by hannesa2** [comment]
Oops, I have no `.jitpack.yml` ! I found you [hint](https://www.jitpack.io/docs/ANDROID/) the and I search for an example and I didn't found an example.
Do you have an running example with a similar task ?

**Comment by hannesa2** [comment]
Thankyou, I solved this problem by introduce a `.jitpack.yml`

```
before_install:
  - cd samples
```
