### ISSUE TITLE
Strange of version when use Github package registry

### ISSUE THREAD

**Issue by chaluemwut** [jitpack/jitpack.io#4107]
**Describe the bug**
I use Github package registry which is new feature of Github. Jitpack create strange of version.

**Expected behavior**
<img width="627" alt="Screen Shot 2562-12-25 at 06 48 27" src="https://user-images.githubusercontent.com/5268784/71426826-b20ecc00-26e2-11ea-9d3e-dd7b11b2b760.png">

**Comment by webilisim** [comment]
You should create a releases on your github.

**Comment by jitpack-io** [comment]
@chaluemwut Those versions are git commits in short form.
If you create releases/tags on GitHub then they will appear on JitPack's releases page.
