### ISSUE TITLE
How to delete Tag builds older than 7 days?

### ISSUE THREAD

**Issue by dongheeleeme** [jitpack/jitpack.io#4108]
I want to delete Tag builds unused anymore. but when i tried to delete Tag builds. i got a below message.
> Tag builds older than 7 days can't be deleted

How do i delete Tag builds?
Thanks :)

**Comment by lzls** [comment]
I have the same request.

**Comment by lzls** [comment]
I have the same requirement.

**Comment by dongheeleeme** [comment]
Yup, i want to know how to delete the oldest tag(>= 7 days) but i don't know yet 😅
