### ISSUE TITLE
Build successful but "ERROR: No build artifacts found"

### ISSUE THREAD

**Issue by marcohc** [jitpack/jitpack.io#4111]
Please provide:

- Link to build log from https://jitpack.io

https://jitpack.io/com/github/marcohc/terminator/1.3.4/build.log

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?

Yes

- What error are you seeing?

Looks like previous version were not running the gradle task:

`installDebugAndroidTest`

and were successful, but now it tries to run it and fails because there's no device connected.

I've tried to skip this task but now it doesn't find any artefact.

Thank you!

**Comment by jitpack-io** [comment]
Hi,

JitPack is running the `./gradlew clean -Pgroup=com.github.marcohc -Pversion=1.3.4 install` command and then is checking for artifacts in $HOME/.m2/repository.

If you run that command locally, does it install your artifacts to that directory?

**Comment by marcohc** [comment]
Hi thanks for replying,

the issue is that the `install` command runs Android Instrumentation tests and these require a connected device or it'll break the build, check this log out:

https://jitpack.io/com/github/marcohc/terminator/1.3.1/build.log

So I tried to ignore that command for the the project, but now it doesn't generate any artefact:

https://jitpack.io/com/github/marcohc/terminator/1.3.4/build.log

**Comment by Oliver-Zimmerman** [comment]
@marcohc was this resolved? I am suddenly getting the same issue

**Comment by marcohc** [comment]
Hi @Oliver-Zimmerman , no it did not :/

I'm using Jitpack to release an Android library / framework (https://github.com/marcohc/terminator) which sample code, I introduced in the same project.

This made Jitpack release process to call 'installDebugAndroidTest' making it to stop.

So I had to extract the Android sample code to a different repository to make it work again.

I tried for a while but I couldn't make it work. Let me know if you're luckier than me.

Cheers

**Comment by Oliver-Zimmerman** [comment]
@marcohc for me the issue seemed to stem from the implementation of JaCoCo I was using which would try run instrument tests as you said. 

I am using Kover now: https://github.com/Kotlin/kotlinx-kover and it seems to be working better with Jitpack.

**Comment by marcohc** [comment]
Hi @Oliver-Zimmerman thanks for the tip, but I have no Jacoco in there, but I'll check Kover for sure, didn't know it, thanks!
