### ISSUE TITLE
Error while building with gradle

### ISSUE THREAD

**Issue by CompanionDelay** [jitpack/jitpack.io#4115]
I'm trying to make a kotlin library and publish that inside jitpack repository. but It fails with a strange exception:
Task 'test' not found in root project 'KAr'.
while I've defined the test task in my tasks.
```
tasks {
    clean {
        rootProject.buildDir
    }
    test {
        useJUnit()
        maxHeapSize = "1G"
    }
}
```
 the code succeed on my machine. so what is the problem?
this is the library link: [KAr](https://github.com/CompanionDelay/KAr/)

[Link to build log](https://jitpack.io/com/github/CompanionDelay/KAr/0.1.1/build.log)

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?
Yes

- What error are you seeing?
Task 'test' not found in root project 'KAr'.

Thank you!

**Comment by romangraef** [comment]
Manually adding the maven plugin fixed that for me.
