### ISSUE TITLE
Android NDK *.so File format not recognized

### ISSUE THREAD

**Issue by hannesa2** [jitpack/jitpack.io#4119]
https://jitpack.io/com/github/hannesa2/openCV-sdk/0.6/build.log

Local `./gradlew install` works, but in `jitpack.io` I run into
```
Unable to strip library '1' due to error /opt/android-sdk-linux/ndk-bundle/toolchains/x86-4.9/prebuilt/linux-x86_64/bin/i686-linux-android-strip returned from '/home/jitpack/build/sdk/build/intermediates/transforms/mergeJniLibs/release/0/lib/x86/libopencv_java4.so', packaging it as is.
/opt/android-sdk-linux/ndk-bundle/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/bin/aarch64-linux-android-strip:/home/jitpack/build/sdk/build/intermediates/transforms/mergeJniLibs/release/0/lib/
arm64-v8a/libopencv_java4.so: File format not recognized
```

Do you have an idea, how to get rid of it ?

**Comment by tomek1911** [comment]
I can see that you have closed this issue, have you solved the problem? I have the same situation and cannot find solution.

**Comment by hannesa2** [comment]
Sorry, I was not able to close. 
I switched to a public self hosted Gitlab, with an own Nexus.

This is the outcome https://github.com/hannesa2/LiveEdgeDetection/blob/master/liveedgedetection/build.gradle#L33-L36

**Comment by tomek1911** [comment]
Thank you for such a quick answer. So far I have hypothesis that it is the case of target build. For my needs I changed manually arm-linux-androideabi-strip to aarch64-linux-android-strip and it worked, but i want to fix it so i don't need replace it manually

**Comment by tomek1911** [comment]
I don't remember well, I haven't been active in this project. If I was to guess it was something with building appropriate Java libs, and put them into Java lib dir
and path but I can be wrong.
