### ISSUE TITLE
grails-rabbitmq-native/3.1.2 build

### ISSUE THREAD

**Issue by robertoschwald** [jitpack/jitpack.io#412]
Wanted to use the grails-rabbitmq-native plugin artifact, but jitpack reports no build file found.
build.gradle is in the grails-3.0.x branch, maybe thats the problem...
 
Log https://jitpack.io/com/github/budjb/grails-rabbitmq-native/3.1.2/build.log

**Comment by jitpack-io** [comment]
Indeed, it works on the `grails-3.0.x` branch:
https://jitpack.io/com/github/budjb/grails-rabbitmq-native/grails-3.0.x-SNAPSHOT/build.log

Using `grails-3.0.x-SNAPSHOT` as the version will build from that branch.
