### ISSUE TITLE
Cannot access snapshot 22Acacia/angled-dream

### ISSUE THREAD

**Issue by LusciousPear** [jitpack/jitpack.io#413]
Hi! Maven is unable to resolve this dependency in this public repo. I'd like latest commit of master: 

    <dependency>
          <groupId>com.github.22Acacia</groupId>
          <artifactId>angled-dream</artifactId>
          <version>-SNAPSHOT</version>
    </dependency>

I am using the correct repo:

      <repositories>
        <repository>
          <id>jitpack.io</id>
          <url>https://jitpack.io</url>
        </repository>
      </repositories>

**Comment by jitpack-io** [comment]
Hi

The dependency looks all right. Tried it from command line and seems to be resolving too.
What error do you get?

**Comment by LusciousPear** [comment]
Oh, confirmed. I think it's a bug in IntelliJ, then. Sorry -- and thanks!

**Comment by jitpack-io** [comment]
There was once a bug where IntelliJ marks snapshots as errors in pom.xml but actually is able to download them. Perhaps that's what you were seeing, not sure

**Comment by LusciousPear** [comment]
Yes, that's exactly it!

**Comment by jitpack-io** [comment]
There are some similar issues https://youtrack.jetbrains.com/issue/IDEA-113485# but not sure yet if it's the same

**Comment by LusciousPear** [comment]
BTW, just wanna say that Jitpack has made my life so much better. Simply building from github is way better than the disaster we were creating trying to use S3 or Sonatype.
