### ISSUE TITLE
My subscription is not active and I cannot pull the code to other projects

### ISSUE THREAD

**Issue by niyaz434** [jitpack/jitpack.io#4131]
Please provide:

-https://jitpack.io/com/github/niyaz434/DateTimePickerLibrary/0.0.2/build.log

I followed the steps accordingly which is mentioned in the documentation. First I add to app level gradle file the following lines 

allprojects {
    repositories {
        google()
        jcenter()
        maven {
            url 'https://jitpack.io'
            credentials {username authToken}
        }
    }
}
authToken i mentioned in my gradle properties correctly without any problem

dependencies {
    implementation 'com.github.niyaz434:DateTimePickerLibrary:0.0.2'
}

Eventhough, I follow all the steps i cannot able to pull the aar file and its simply showing the error mentioned below:

ERROR: Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve com.github.niyaz434:DateTimePickerLibrary:0.0.2.

Help will be appreciated thanks.

Thank you!

**Comment by jitpack-io** [comment]
Hi,

Started a trial for github.com:niyaz434 and it should be working now. For private repositories JitPack requires a subscription.
