### ISSUE TITLE
JitPack support not responding. "Subscription not active" message for Paid repository

### ISSUE THREAD

**Issue by jcchavezm** [jitpack/jitpack.io#4136]
Please provide:

- Link to build log from https://jitpack.io
https://jitpack.io/com/github/ClipMX/payclip-android-sdk/0.3.4/build.log

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?
Yes, the project builds with ./gradlew install command.

- What error are you seeing?
We get a "Subscription not active" message when trying to see the logs from JitPack
The subscription is paid for one year.
It was purchased using the DevOps email account, I am a collaborator with Push Permissions to the repositories. 
We want to know why the builds are not publishing to JitPack when creating releases on GitHub.
I have also tried the ASK chat with no luck.

Thank you!

**Comment by slashnextSDK** [comment]
Hi, i got the same issue , any solutions?

**Comment by appice-androidsdk** [comment]
No support till time, Our clients are stuck because of the same issue. Really very poor support or we can say no support at all.

**Comment by ashishgupta84** [comment]
Was anyone able to get this fixed ? My subscription is inactive for last 1 month even after paying for the full year.

**Comment by gouravspyne** [comment]
Hi Team,
Yesterday, our account suddenly became inactive despite having an active yearly plan that started in February 2023. Due to this confusion, our team made an additional payment today, thinking that the subscription had expired. However, even after the second payment, the account remains inactive.

Our usage of Jitpack is crucial for our client Swiggy and its restaurant partners. Due to the account's inactive status, their services have been disrupted since yesterday.

Account details:
Email- tech@spyne.ai

**Comment by Amirale47** [comment]
@gouravspyne did you get this resolved? I have exactly the same situation, I had a yearly subscription then I paid again last Friday, but my account stills inactive, our dependency is crucial for our clients and we need to get this resolved ASAP. I tired contacting them but their support is ver very poor. Is there any alternative int he market that we can use please?

**Comment by gouravspyne** [comment]
Hi,
This was fixed and working fine for the last 20 days. Now the same issue
reoccurs again and support is very poor from Jitpack.

Regards,
*Gourav*
*TEAM LEAD,*
*Spyne.ai <http://Spyne.ai> 🚀 *

**Comment by tech-app-innovation** [comment]
the same issue facing i tried with 5 card after card detail fill its say purchase successfully and subscription is active but if go in account section it show inactive please anyone has solution of this issue i didn't find other way to fix and there is no support center and mail

**Comment by keith-comodule** [comment]
Same issue. In active and they are not responding.

**Comment by keithloughnane** [comment]
Same issue, subscription inactive after paying. No response from support.
