### ISSUE TITLE
Build Error In Jitpack , please resolved and put release 0.0.8 again

### ISSUE THREAD

**Issue by diigel** [jitpack/jitpack.io#4137]
Please provide:

- Link to build log from https://jitpack.io

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?

- What error are you seeing?

Thank you!

**Comment by jitpack-io** [comment]
Hi,

What repository is this for?

**Comment by diigel** [comment]
for Android ( Kotlin )
