### ISSUE TITLE
Git Submodule not loading  - remote hung up unexpectedly

### ISSUE THREAD

**Issue by stephan-mediamonks** [jitpack/jitpack.io#4142]
- Link to build log from https://jitpack.io
https://jitpack.io/org/bitbucket/mediamonksovp/mobile-android-app/develop-SNAPSHOT/build.log

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?
Project is checked out and builds fine

- What error are you seeing?
Git error. git@bitbucket.org:mediamonksovp/mobile-shared.git: remote hung up unexpectedly

The repository `mobile-shared` is defined as a submodule on the `mobile-android-app` repository. With `--recursive` flag, this checks out nicely locally. Feeding that repository url shows the content of the repository. Building it will not work because the repository only contains assets.

Please advise on what needs to be done to make this work.
Thanks!

**Comment by jitpack-io** [comment]
Hi,

This seems like an authentication issue since the submodule is a private repository.
JitPack clones the app repository using https so cloning the submodule using git+ssh fails. 
Is it an option for you to change the submodule to `https`?
