### ISSUE TITLE
Tag or commit not found, but tag exists in repo

### ISSUE THREAD

**Issue by DeKaN** [jitpack/jitpack.io#4146]
https://jitpack.io/#com.cxpublic/cxense-android shows correct tags, but you can't get artifact for tag "2.0.0". It answers "Tag or commit '2.0.0' not found. Rechecking."

Tag was added more than 24 hours ago

**Comment by DeKaN** [comment]
Artifact was built in 4 days since tag was pushed

**Comment by jitpack-io** [comment]
Hi,

It's possible that tag 2.0.0 was requested from before it existed. JitPack will remember that the tag is missing and will not attempt a new build.
We have now triggered a new build for 2.0.0.

**Comment by Zhuinden** [comment]
https://jitpack.io/#com.cxpublic/cxense-android is not available from Jitpack.io, not 2.0.0 not older versions, is there anything you can do @jitpack-io ?

**Comment by DeKaN** [comment]
@Zhuinden It's available now.
@jitpack-io  it was fixed by log into the account, without changing anything
