### ISSUE TITLE
Old maven version

### ISSUE THREAD

**Issue by asm0dey** [jitpack/jitpack.io#4150]
Please provide:

https://jitpack.io/com/github/apache/spark/160c144baa/build.log

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?

Yes

- What error are you seeing?

`Detected Maven Version: 3.6.1 is not in the allowed range 3.6.3.`

Thank you!

**Comment by asm0dey** [comment]
Bump

**Comment by cicirello** [comment]
@asm0dey I'm not affiliated with jitpack, but I had the same problem or at least a variation of it. It doesn't look like anyone is monitoring issue tracker. Anyway, see this post I put on dev.to with my solution to the old Maven version issue: https://dev.to/cicirello/how-to-configure-jitpack-for-recent-jdk-versions-4pek

Essentially you can configure jitpack to update Maven in a jitpack.yml file in your repo. Currently this will update it to 3.8.6. It would be better if jitpack just installed an up to date Maven. They have an over 3 year old version installed.

**Comment by asm0dey** [comment]
Bump

**Comment by asm0dey** [comment]
Bump
