### ISSUE TITLE
Could not resolve dependency uap-java

### ISSUE THREAD

**Issue by muhammadkholidb** [jitpack/jitpack.io#4153]
I use jitpack.io to add dependency to [uap-java](https://github.com/ua-parser/uap-java) project to my maven project but it failed to build. Here is the maven error message:
```
[ERROR] Failed to execute goal on project xxx: Could not resolve dependencies for project com.xxx:xxx:war:1.0-SNAPSHOT: Failure to find com.github.ua-parser:uap-java:jar:master-SNAPSHOT in https://jitpack.io was cached in the local repository, resolution will not be reattempted until the update interval of jitpack.io has elapsed or updates are forced -> [Help 1]
```
This is the dependency definition in pom.xml:
```
        <dependency>
            <groupId>com.github.ua-parser</groupId>
            <artifactId>uap-java</artifactId>
            <version>master-SNAPSHOT</version>
        </dependency>
```

**Comment by dr0i** [comment]
I tried it, just now it's working.

Maybe that was just a temporary glitch or maybe you use `http` instead of `https` for the jitpack url?

**Comment by muhammadkholidb** [comment]
Yes it works right now, I didn't know why I got that error. The URL has already used `https`. 

Set this issue closed. Thank you.
