### ISSUE TITLE
Subscription not active

### ISSUE THREAD

**Issue by Baragouin** [jitpack/jitpack.io#4157]
Please provide:

- Link to build log from https://jitpack.io
  https://jitpack.io/com/gitlab/iserosteam/body/iserosapi-v3/master-SNAPSHOT/maven-metadata.xml

- Does the project build on your machine with the same commands (e.g. ./gradlew install) ?
   no

- What error are you seeing?
  Could not HEAD 'https://jitpack.io/com/gitlab/iserosteam/body/iserosapi-v3/master-SNAPSHOT/maven-metadata.xml'. Received status code 403 from server: Forbidden

Hi, i have already bought the subscription but still i am getting 403 from server on my private repo, and also i am getting this error "Subscription not active" on checking repo logs on jitpack

Thank you!
@jitpack-io

**Comment by jitpack-io** [comment]
Hi,

The subscription may not have been linked to gitlab.com:iserosteam properly.
Do you know what email was used for the subscription?
For the time being we've activated a trial to avoid disruption.
Also for subscription issues we recommend contacting Support via the button on the website.

**Comment by RHMDHDYT** [comment]
Hi, I'm having the same issue, we are migrating from bitbucket to GitLab. how to link my subscription to GitLab @jitpack-io ?
