### ISSUE TITLE
pom.xml and gradle wrapper together

### ISSUE THREAD

**Issue by sasa7812** [jitpack/jitpack.io#416]
It seems like jitpack.io uses pom.xml to find out JDK version and then builds project with gradle using that version of JDK.

https://jitpack.io/com/github/sasa7812/asterisk-java/master-1919104447-1/build.log 
with failure: build.gradle has 1.7 version while pom.xml has 1.6

https://jitpack.io/com/github/sasa7812/asterisk-java/master-00e6e8ba7d-1/build.log
built successfully after pom.xml correction

**Comment by jitpack-io** [comment]
Hi

Thanks for reporting! Will have a look

**Comment by jitpack-io** [comment]
It's fixed now. No longer picking jdk version from pom if there is a gradle build file.
Re-built that failed snapshot, looks all right. Thanks again!

**Comment by sasa7812** [comment]
My pleasure. Very nice project, thank you for it.
