### ISSUE TITLE
Downloads API Returning Mongo Error

### ISSUE THREAD

**Issue by calebcartwright** [jitpack/jitpack.io#4161]
**Describe the bug**
The [download statistics API](https://github.com/jitpack/jitpack.io/blob/master/API.md#download-statistics) is currently returning an HTTP 200 Response with a body of:
```json
{"name":"MongoError"}
```

**To Reproduce**
1. call the download statistics API with any package:
```bash
$ curl https://jitpack.io/api/downloads/com.github.jitpack/gradle-modular
```
2. observe the response code and body

**Expected behavior**
The Download Statistics API returns the weekly and monthly download statistics as described in the documentation. Also, I'd expect a non-200 response status code if there was an internal error

**Screenshots**

![image](https://user-images.githubusercontent.com/13042488/76146589-949e9c80-6059-11ea-959f-1c7472d2290e.png)

**Comment by Canato** [comment]
@jitpack-io any change to check this please? 

The download column on the right side of the website is missing
<img width="1134" alt="Screenshot 2021-03-18 at 22 02 30" src="https://user-images.githubusercontent.com/15942449/111703510-a6eb1300-8835-11eb-83e9-2aad8f0d089a.png">
