### ISSUE TITLE
A problem occurred evaluating root project 'conductor-mobile'. > Could not set unknown property 'archiveClassifier' for task ':sourcesJar' of type org.gradle.api.tasks.bundling.Jar.

### ISSUE THREAD

**Issue by mrk-han** [jitpack/jitpack.io#4166]
Please provide:

- Link to build log from https://jitpack.io 

https://jitpack.io/com/github/willowtreeapps/conductor-mobile/0.21.1/build.log

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?

yes

- What error are you seeing?

```
* Where:
Build file '/home/jitpack/build/build.gradle' line: 59

* What went wrong:
A problem occurred evaluating root project 'conductor-mobile'.
> Could not set unknown property 'archiveClassifier' for task ':sourcesJar' of type org.gradle.api.tasks.bundling.Jar.
```

Thank you!

**Comment by neo355** [comment]
Ist das meine ipi zufur für meine Anfrage?

**Comment by neo355** [comment]
Api*

**Comment by mrk-han** [comment]
I don't believe so @neo355
