### ISSUE TITLE
ExtractInfo/1.6.8 build

### ISSUE THREAD

**Issue by p4535992** [jitpack/jitpack.io#417]
Log https://jitpack.io/com/github/p4535992/ExtractInfo/1.6.8/build.log
Not sure about this error never seen before.

**Comment by jitpack-io** [comment]
Hi

The build took longer than 15 minutes and time out. Looks like it's downloading a lot of dependencies and perhaps some of them are from slow repositories

**Comment by p4535992** [comment]
k i will try to reduce the dependency ty very much.
