### ISSUE TITLE
Subscription not active

### ISSUE THREAD

**Issue by Alok-Sharma** [jitpack/jitpack.io#4174]
Please provide:

- Link to build log from https://jitpack.io
https://jitpack.io/com/github/postmates/courier-android-proto/v3601/build.log

- What error are you seeing?
`Subscription not active`

We renewed our subscription recently, however I'm still unable to access or run builds. Please advise.

Thank you!

**Comment by Alok-Sharma** [comment]
help @jitpack-io

**Comment by jitpack-io** [comment]
Hi,

Sorry about that. Should be working now.
For subscription issues we recommend using the Support link on jitpack.io
