### ISSUE TITLE
Automatic maven plugin injection fails when repo has java and android modules

### ISSUE THREAD

**Issue by ligi** [jitpack/jitpack.io#4176]
see here:
https://jitpack.io/com/github/walleth/KHardWareWallet/e28fdc30d7/build.log
it only finds:
```
Files: 
com/github/walleth/KHardWareWallet/keycard/e28fdc30d7
com/github/walleth/KHardWareWallet/keycard/e28fdc30d7/keycard-e28fdc30d7-sources.jar
com/github/walleth/KHardWareWallet/keycard/e28fdc30d7/keycard-e28fdc30d7.aar
com/github/walleth/KHardWareWallet/keycard/e28fdc30d7/keycard-e28fdc30d7.pom
com/github/walleth/KHardWareWallet/keycard/e28fdc30d7/keycard-e28fdc30d7.pom.md5
com/github/walleth/KHardWareWallet/keycard/e28fdc30d7/keycard-e28fdc30d7.pom.sha1

com/github/walleth/KHardWareWallet/trezor/e28fdc30d7
com/github/walleth/KHardWareWallet/trezor/e28fdc30d7/trezor-e28fdc30d7-sources.jar
com/github/walleth/KHardWareWallet/trezor/e28fdc30d7/trezor-e28fdc30d7.aar
com/github/walleth/KHardWareWallet/trezor/e28fdc30d7/trezor-e28fdc30d7.pom
com/github/walleth/KHardWareWallet/trezor/e28fdc30d7/trezor-e28fdc30d7.pom.md5
com/github/walleth/KHardWareWallet/trezor/e28fdc30d7/trezor-e28fdc30d7.pom.sha1

```

but it should also find ./trezor_wire/build/libs/trezor_wire.jar

otherwise builds using the trezor module will fail as they cannot resolve trezor_wire
I need to mix android and java as the wire gradle plugin does not support android modules currently

**Comment by mirceanis** [comment]
@ligi AFAIK, at its core jitpack runs `./gradlew install` with some exclusion of tests and then publishes whatever comes out as artifact.

The install task would be added by a maven or android-maven plugin which I'm not seeing applied to that library. Perhaps try adding one of those plugins to the java library module and re-check.

For reference here's a multi-artifact repo with aar and jar artifacts being built and distributed through jitpack:
https://github.com/uport-project/uport-android-sdk

It seems to work just fine even when we `apply plugin: "com.github.dcendents.android-maven"` on java libraries

**Comment by ligi** [comment]
thanks @mirceanis - that was really helpful!
Got it to work when adding the plugins manually. But still keeping this issue open as it would be great if the automatic injection of the plugins would also work.
