### ISSUE TITLE
This project uses AndroidX dependencies, but the 'android.useAndroidX' property is not enabled

### ISSUE THREAD

**Issue by marcauberer** [jitpack/jitpack.io#4180]
An error occurs in my latest build:
https://jitpack.io/com/github/ChilliBits/splash-screen/1.1.5/build.log

The log output says, that I have to enable android.useAndroidX. As you can see on GitHub (https://github.com/ChilliBits/splash-screen/blob/master/gradle.properties#L21), useAndroidX is enabled. On my machine the build works fine.

What can I do to make this build working?

Thanks in advance
Marc

**Comment by marcauberer** [comment]
Hi, does anyone know what to do, to solve this?

**Comment by jitpack-io** [comment]
Hi,

Thank you for raising the issue! Should be fixed now.
Also rebuilt 1.1.5 and it was successful.

**Comment by marcauberer** [comment]
Thanks for fixing this.
