### ISSUE TITLE
Build works locally but not on jitpack, logs attached

### ISSUE THREAD

**Issue by ironjan** [jitpack/jitpack.io#4190]
Please provide:

- Link to build log from https://jitpack.io
https://jitpack.io/com/github/ironjan/jeo/945a663e30/build.log

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?
yes. Local log at https://gist.github.com/ironjan/15ec87538b2d1d4661beaef5d17eeef5

- What error are you seeing?
One of the maven submodules (within a git submodule) is not finding its parent.

**Comment by ironjan** [comment]
It seems jitpack's maven is stricter than mine. Cause of the problem:
```
pom.xml
contrib/pom.xml
contrib/jeo-guava/pom.xml -> marked "util" as parent without adding relative path.
util/pom.xml
```
After changing the parent of `jeo-guava` to `contrib`, the build works as expected.

**Comment by jitpack-io** [comment]
Thank's for explaining!
