### ISSUE TITLE
Artifact Not found

### ISSUE THREAD

**Issue by Muvidevlopers** [jitpack/jitpack.io#4197]
WARNING:
Gradle 'install' task not found. Please add the 'maven' or 'android-maven' plugin.
See the documentation and examples: https://jitpack.io/docs/

Adding maven plugin
Found android library build file in muvi-livestream-sdk
Running: ./gradlew clean -Pgroup=com.edocent.gitlab.root -Pversion=v1.16 install
/usr/bin/env: ‘sh\r’: No such file or directory
Build tool exit code: 0
Looking for artifacts...
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2
Looking for pom.xml in build directory and ~/.m2
2020-04-22T04:47:22.180648348Z
Exit code: 0

ERROR: No build artifacts found

Thanks in advance.

**Comment by jitpack-io** [comment]
Hi,

Would recommend adding the 'maven' or 'android-maven' plugin.
