### ISSUE TITLE
Build fail - maven

### ISSUE THREAD

**Issue by TheSilentPro** [jitpack/jitpack.io#4198]
Please provide:

- Link to build log from https://jitpack.io
https://jitpack.io/com/github/TheSilentPro/IPAPI/1.0/build.log

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?
yes

- What error are you seeing?
No build found (probably can't find the pom.xml but its there and it is there in the release version)

Thank you!

**Comment by jitpack-io** [comment]
Hi,

Is it possible pom.xml didn't exist in version 1.0?
Running latest master build:
https://jitpack.io/com/github/TheSilentPro/IPAPI/master-SNAPSHOT/build.log
