### ISSUE TITLE
Update Android Support Library On Build Server

### ISSUE THREAD

**Issue by T-Spoon** [jitpack/jitpack.io#42]
Hey,

Looks the the server is missing appcompat-v7:22.1.1

Here's the build log: https://jitpack.io/com/github/T-Spoon/Benchit/c2603a1/build.log

**Comment by jitpack-io** [comment]
Hi! Version 22.1.0 should be available for now. Going to upgrade to 22.1.1 some time soon.
Thanks for the heads up!

**Comment by T-Spoon** [comment]
Awesome, thanks!

Really loving this project by the way - super useful!

**Comment by jitpack-io** [comment]
22.1.1 is now available
