### ISSUE TITLE
droptools/v0.8.1-1 build

### ISSUE THREAD

**Issue by jschaf** [jitpack/jitpack.io#420]
Log https://jitpack.io/com/github/benjamin-bader/droptools/v0.8.1-1/build.log

Seems to failing on the sub-module droptools-example.

**Comment by jschaf** [comment]
Also, I couldn't get the snapshot to work on the submodules with this dependency:

`'com.github.benjamin-bader.droptools:dropwizard-jooq:master-SNAPSHOT'`

**Comment by jitpack-io** [comment]
Hi

The master-SNAPSHOT is failing because of this error in the log:
```
org.postgresql.util.PSQLException: Connection refused. 
```
Looks like its trying to connect to a database.

The issue in v0.8.1-1 is that the example module references a parent module with version v0.8.1-1-SNAPSHOT. The version in parent's pom.xml is v0.8.1-1.

**Comment by jschaf** [comment]
He updated to 0.9.1-1-SNAPSHOT on sonatype, so this is less of an issue for me.
