### ISSUE TITLE
[Fatal Error] huge.xml:2:7: An invalid XML character (Unicode: 0x8) was found in the element content of the document.

### ISSUE THREAD

**Issue by soberich** [jitpack/jitpack.io#4200]
https://jitpack.io/com/github/soberich/swagger-ui/master-SNAPSHOT/build.log

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?
 
yes

- What error are you seeing?
```console
[Fatal Error] huge.xml:2:7: An invalid XML character (Unicode: 0x8) was found in the element content of the document.
```
Thank you!

**Comment by jitpack-io** [comment]
Hi,

Is there a file called ` huge.xml` in the repository or being produced by the build?

**Comment by soberich** [comment]
@jitpack-io no, off course not.
