### ISSUE TITLE
Multi-project builds don't rewrite gradle module metadata

### ISSUE THREAD

**Issue by nedtwigg** [jitpack/jitpack.io#4205]
**Describe the bug**
JitPack should rewrite the gradle module metadata in the same way it rewrites the POM.

**To Reproduce**
For a build of https://github.com/diffplug/spotless at `855306c42cd14e9dcbdfd45ab9b7d4693030b608` 

- the [build log](https://jitpack.io/com/github/diffplug/spotless/855306c42cd14e9dcbdfd45ab9b7d4693030b608/build.log)
- the [`.pom` for plugin-gradle](https://jitpack.io/com/github/diffplug/spotless/spotless-plugin-gradle/855306c42cd14e9dcbdfd45ab9b7d4693030b608/spotless-plugin-gradle-855306c42cd14e9dcbdfd45ab9b7d4693030b608.pom) is correctly rewritten
- the [`.module` for plugin-gradle](https://jitpack.io/com/github/diffplug/spotless/spotless-plugin-gradle/855306c42cd14e9dcbdfd45ab9b7d4693030b608/spotless-plugin-gradle-855306c42cd14e9dcbdfd45ab9b7d4693030b608.module) redirects to a non-existent `1.29.0-SNAPSHOT`

If someone uses gradle to get the artifact, they get [this error](https://github.com/diffplug/spotless/pull/568#issuecomment-624797533):

```
A problem occurred configuring root project 'gradle-project'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not resolve com.github.diffplug:spotless-lib:1.29.0-SNAPSHOT.
     Required by:
         project : > com.github.diffplug.spotless:spotless-plugin-gradle:855306c42cd14e9dcbdfd45ab9b7d4693030b608
      > Could not resolve com.github.diffplug:spotless-lib:1.29.0-SNAPSHOT.
         > Unable to load Maven meta-data from https://jitpack.io/com/github/diffplug/spotless-lib/1.29.0-SNAPSHOT/maven-metadata.xml.
            > Could not get resource 'https://jitpack.io/com/github/diffplug/spotless-lib/1.29.0-SNAPSHOT/maven-metadata.xml'.
               > Could not GET 'https://jitpack.io/com/github/diffplug/spotless-lib/1.29.0-SNAPSHOT/maven-metadata.xml'. Received status code 401 from server: Unauthorized
   > Could not resolve com.github.diffplug:spotless-lib-extra:1.29.0-SNAPSHOT.
     Required by:
         project : > com.github.diffplug.spotless:spotless-plugin-gradle:855306c42cd14e9dcbdfd45ab9b7d4693030b608
      > Could not resolve com.github.diffplug:spotless-lib-extra:1.29.0-SNAPSHOT.
         > Unable to load Maven meta-data from https://jitpack.io/com/github/diffplug/spotless-lib-extra/1.29.0-SNAPSHOT/maven-metadata.xml.
            > Could not get resource 'https://jitpack.io/com/github/diffplug/spotless-lib-extra/1.29.0-SNAPSHOT/maven-metadata.xml'.
               > Could not GET 'https://jitpack.io/com/github/diffplug/spotless-lib-extra/1.29.0-SNAPSHOT/maven-metadata.xml'. Received status code 401 from server: Unauthorized
```

**Expected behavior**
I would expect JitPack to rewrite the `.module` file along the same lines that it rewrites the `.pom` file.

**Workaround**
Add the following `metadataSources` block:

```gradle
repositories {
  maven {
    url 'https://jitpack.io'
    metadataSources {
      ignoreGradleMetadataRedirection() // not available until Gradle 5.6+
      mavenPom()
    }

**Comment by jitpack-io** [comment]
Hi Ned,

Thank you for the super detailed bug report! You could say it is... spotless.
With your help we've identified what's missing and deployed a fix to rewrite dependency versions. At the moment JitPack should be rewriting:
- component
- variants
- variant files
- variant dependencies (requires and prefers)

We are planning to handle other sections of .module file too. Looking at the [spec](https://github.com/gradle/gradle/blob/master/subprojects/docs/src/docs/design/gradle-module-metadata-latest-specification.md) we will also need dependencyContraints. 

New [build log](https://jitpack.io/com/github/diffplug/spotless/855306c42c/build.log) and [module](https://jitpack.io/com/github/diffplug/spotless/spotless-plugin-gradle/855306c42c/spotless-plugin-gradle-855306c42c.module).

**Comment by nedtwigg** [comment]
Thanks for fix!  Took me a while, but finally confirmed fixed :)
