### ISSUE TITLE
Unable to access private JavaDocs

### ISSUE THREAD

**Issue by caojohnny** [jitpack/jitpack.io#4207]
**Describe the bug**
I am unable to access the JavaDocs published through JitPack from a private GitHub repository when access to everyone is disabled. 

I am inclined to believe this is a bug because while I am able to access the library artifacts from Gradle on my machine in addition to being able to access the build log, I am unable to browse the JavaDocs from the same browser I am using to look at the build log.

**To Reproduce**
1. Create a private GitHub repository. I have some minimal code located [here](https://github.com/AgentTroll/jitpack-private-javadoc-test) that you can fork that will reproduce the issue.
2. Create a new release
3. Go to JitPack and look up the private repository and build the release
4. Visit the JavaDocs page. Instead of opening the JavaDocs, you will be redirected to [this page](https://jitpack.io/private) instead.

**Expected behavior**
Rather than being redirected, I would expect to be able to browse my JavaDocs.

**Screenshots**
None applicable.

**Additional context**
I first suspected there may be some strange cookie or authentication issues with Firefox, so I tried with Chrome and ensured that all local and third-party cookies were allowed with no success. In addition, as I mentioned above, I am able to view the private build.log, so I don't think this is the source of the error.

I also added my own username to the users with access in the settings tab on JitPack, also with no effect.

Allowing everyone to access the builds also allowed me to successfully view the JavaDocs. The build is completely fine, it's just that all builds must be available publically in order to view a supposedly private JavaDoc. This is not desirable.

**Comment by jitpack-io** [comment]
Hi,

Thank you for the detailed report! We are looking into this.
Just to clarify, is the repository under your own account on github or an organization?
Does it change anything if you re-authorize JitPack:
1. Sign out of JitPack.io
2. Revoke JitPack Application on https://github.com/settings/applications
3. Open https://jitpack.io/auth

**Comment by AgentTroll** [comment]
The repository is under a GitHub organization. I am a member of that organization, but have administrative access to my own repositories.

I followed the steps you outlined to reauthorize JitPack. Nothing changed. I still have access to all the artifacts (build.log, jar file etc) but I still cannot access the JavaDocs.

**Comment by AgentTroll** [comment]
Hi, has there been any updates to this issue in the past 2 weeks?

**Comment by AgentTroll** [comment]
Hi, has any progress been made on this issue in the last 2 months or so? I’m eager to know more about whether this will get fixed or if there is a solution for this issue that I’m not seeing.

**Comment by AgentTroll** [comment]
Hi, I always hate to badger people continuously, but I can’t help but feel that this issue has been left on the back burner. Has anything changed in the past 3 months? Can I give any additional information that would expedite the process of resolving this issue? Has my previous response to your suggestion been received? Are you working on the issue or do you have any plans to begin doing so? I hope that I haven’t missed anything.
