### ISSUE TITLE
Could not resolve all artifacts for configuration ':classpath'

### ISSUE THREAD

**Issue by matshou** [jitpack/jitpack.io#4211]
Please provide:

- *Link to build log*
https://jitci.com/gh/yooksi/CocoLib/builds/b1E896Z5QE2ASW1S3WNQ8A18EH/build.log

- *Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?*
The project builds normally on my machine with `gradlew build` and `gradlew install`

- *What error are you seeing?*
`Could not resolve all artifacts for configuration ':classpath'.`

**Comment by Shahroz16** [comment]
@yooksi did you find any solution for this?

**Comment by yooksi** [comment]
Unfortunately I did not since I gave up on using Jitpack after many error like this.
