### ISSUE TITLE
Unable to publish distTar artifacts from a gradle project

### ISSUE THREAD

**Issue by yschimke** [jitpack/jitpack.io#4214]
Please provide:

- Link to build log from https://jitpack.io

https://jitpack.io/com/github/yschimke/rsocket-cli/1.20.0/build.log

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?

Yes.

build/distributions/rsocket-cli-master-3feb2fb-dirty.tgz

- What error are you seeing?

No tgz file published

Build artifacts:
com.github.yschimke:rsocket-cli:1.20.0

Files: 
com/github/yschimke/rsocket-cli/1.20.0
com/github/yschimke/rsocket-cli/1.20.0/build.log
com/github/yschimke/rsocket-cli/1.20.0/rsocket-cli-1.20.0-sources.jar
com/github/yschimke/rsocket-cli/1.20.0/rsocket-cli-1.20.0.jar
com/github/yschimke/rsocket-cli/1.20.0/rsocket-cli-1.20.0.module
com/github/yschimke/rsocket-cli/1.20.0/rsocket-cli-1.20.0.pom
com/github/yschimke/rsocket-cli/1.20.0/rsocket-cli-1.20.0.pom.md5
com/github/yschimke/rsocket-cli/1.20.0/rsocket-cli-1.20.0.pom.sha1

Thank you!

**Comment by jitpack-io** [comment]
Hi,

Thank you for raising the issue!
`.tgz` files are currently excluded but we are going change that. `tar` and `tar.gz` files should work just fine.

**Comment by yschimke** [comment]
Disabling compression fixed it immediately. Thanks.
