### ISSUE TITLE
CastCompanionLibrary-android/v2.7.3 build

### ISSUE THREAD

**Issue by tommyd3mdi** [jitpack/jitpack.io#422]
Log https://jitpack.io/com/github/googlecast/CastCompanionLibrary-android/v2.7.3/build.log

**Comment by jitpack-io** [comment]
Hi!

The project is publishing a few aar files but no .pom file. Currently JitPack only picks up artifacts that publish a pom file along with other files. 
Planning to support this kind of projects in the future.

**Comment by tommyd3mdi** [comment]
Ok, thanks for the info!
