### ISSUE TITLE
Read timeout when downloading dependency from JitPack.io

### ISSUE THREAD

**Issue by MaxwellCody** [jitpack/jitpack.io#4226]
One of my project's build is failing because some of its dependencies are hosted on JitPack.io and cannot be downloaded.

The dependencies are:
* `com.github.kotlin-graphics.imgui:imgui-core:-SNAPSHOT`
* `com.github.kotlin-graphics.imgui:imgui-gl:-SNAPSHOT`
* `com.github.kotlin-graphics.imgui:imgui-glfw:-SNAPSHOT`

It appears to be happening on a lot of (if not all) other public dependencies hosted on JitPack.io since I can't even access the javadoc page for the example library listed on this GitHub page:
```
$ curl -m 60 'https://jitpack.io/com/github/jitpack/gradle-simple/latest/javadoc/'
curl: (28) Operation timed out after 60001 milliseconds with 0 bytes received
```

**Comment by Marcono1234** [comment]
https://status.jitpack.io/ shows that the "Queue" is down.

**Comment by MaxwellCody** [comment]
> https://status.jitpack.io/ shows that the "Queue" is down.

Yes but it still lists "Snapshot Builds" and "Javadoc" as being up when they don't seem to be.

**Comment by jdvp** [comment]
@MaxwellCody I had been having this same issue yesterday but looks like the service is up again now and my builds are running, maybe check now?
