### ISSUE TITLE
403: Forbidden from server

### ISSUE THREAD

**Issue by jimmy-hello-world** [jitpack/jitpack.io#4227]
Hi,

Yesterday my project was able to compile and fetch the added repositories. However, now I am getting 403 error while compiling. I tried to get the authToken again from jitpack.io however the `sign in` doesn't seem to be working. Even after sign in and redirecting I can still see sign in button on the home page and the `Authorize` button doesn't seem to be doing anything. I have commented out the name of the repositories due to privacy reasons.

```
> Could not resolve com.github.Project:android-XYZ-Project:develop-SNAPSHOT.
     Required by:
         project :app
      > Could not resolve com.github.Project:android-XYZ-Project:develop-SNAPSHOT.
         > Unable to load Maven meta-data from https://jitpack.io/com/github/ABC/android-XYZ-Project/develop-SNAPSHOT/maven-metadata.xml.
            > Could not get resource 'https://jitpack.io/com/github/ABC/android-XYZ/develop-SNAPSHOT/maven-metadata.xml'.
               > Could not GET 'https://jitpack.io/com/github/ABC/android-XYZ-Project/develop-SNAPSHOT/maven-metadata.xml'. Received status code 403 from server: Forbidden
```
Thank you!

**Comment by woodyLam** [comment]
I got this issues too. it was happening in this morning and yesterday everything worked fine.

**Comment by exneval** [comment]
@woodyLam same with me, it just happened an hour ago

**Comment by jimmy-hello-world** [comment]
Yup, I guess it was due to server being down. It is up again.
