### ISSUE TITLE
My Jitpack Library Build are in queue since long time

### ISSUE THREAD

**Issue by androidKamal** [jitpack/jitpack.io#4228]
Please provide:

- Link to build log from 
https://jitpack.io/com/github/androidKamal/LibraryApplication/1.0.107/build.log
- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?

- What error are you seeing?
No error I see

Thank you!

**Comment by exneval** [comment]
known issue #4227 #4226 

Unable to load [https://www.jitpack.io/com/github/prscx/bottomsheetbuilder/fixes-SNAPSHOT/maven-metadata.xml](this one)
