### ISSUE TITLE
Read Java version from build file

### ISSUE THREAD

**Issue by Bartvhelvert** [jitpack/jitpack.io#4238]
**Is your feature request related to a problem? Please describe.**
It should be possible to read the Java version from the build file and build using a compatible version of the JDK.

**Describe the solution you'd like**
Jitpack uses the build files to decide which JDK it is going to use.

**Additional context**
In this project for example: https://github.com/Bartvhelvert/gradle-modular Jitpack should use JDK 11 while it uses JDK 8.

**Comment by jitpack-io** [comment]
Thank you for the suggestion and the example!
At the moment it is possible to specify java version using jitpack.yml config.
