### ISSUE TITLE
Exception in thread "main" java.lang.NoSuchMethodError: org.sosy_lab.common.Classes.makeExtendedURLClassLoader()Lorg/sosy_lab/common/Classes$ClassLoaderBuilder;

### ISSUE THREAD

**Issue by PallaviBagga** [jitpack/jitpack.io#4240]
Hi every time I am trying to build my project, it shows the following exception: 
Exception in thread "main" java.lang.NoSuchMethodError: org.sosy_lab.common.Classes.makeExtendedURLClassLoader()Lorg/sosy_lab/common/Classes$ClassLoaderBuilder;

I have tried all the different versions, but no success. This is a code https://github.com/sosy-lab/java-smt/blob/master/src/org/sosy_lab/java_smt/example/Interpolation.java which I am trying to run.

**Comment by p4l1ly** [comment]
I have the same problem, what did the trick, please?
