### ISSUE TITLE
Requested subscription

### ISSUE THREAD

**Issue by Panyite** [jitpack/jitpack.io#4244]
**Describe the bug**
Subscription is not active right now
Requested subscription: github.com/SomeTeam. 
Your subscriptions are listed in User Settings.
Please contact Support or repository admins if you need assistance.

**To Reproduce**
1. Go to https://jitpack.io/private
2. Type url repo in search SomeTeam/android-utils
2. Click on 'Look up'
3. In list with version click on Click on 'Log icon' 
4. See error :
Subscription is not active right now
Requested subscription: github.com/postufteam. 
Your subscriptions are listed in User Settings.
Please contact Support or repository admins if you need assistance.

**Expected behavior**
Build log

**Screenshots**
<img width="1790" alt="Снимок экрана 2020-06-19 в 10 25 15" src="https://user-images.githubusercontent.com/62097306/85103269-66fbee80-b217-11ea-8895-cb7a7d811570.png">
<img width="1790" alt="Снимок экрана 2020-06-19 в 10 27 32" src="https://user-images.githubusercontent.com/62097306/85103422-ac202080-b217-11ea-90cb-f04cf03062c5.png">
<img width="1789" alt="Снимок экрана 2020-06-19 в 10 30 02" src="https://user-images.githubusercontent.com/62097306/85103517-e689bd80-b217-11ea-9e4e-91d83efe6bb6.png">

**Additional context**
In Github account I see nothing and support didn't answer me, what should I do?

**Comment by ashishgupta84** [comment]
I have been in similar situation. Trying to reach out support to fix the subscription but they there is no response from them. It has been 2 weeks now.

**Comment by sceneratest** [comment]
same error i am facing . no support for private repository for jitpack.

**Comment by liangxiaotiao** [comment]
我也遇到了这样的问题，之前发布过一个版本是成功了，现在更新了代码想重新发布就失败了。不知道怎么解决

**Comment by jian936396665** [comment]
> 成功

解决了没有，通过support发邮件可以激活吗

**Comment by tauseeq-grace** [comment]
i am also facing this issue i have simply updated the library version and this issue is Coming Kindly Guide or tell any solution what is the basic reason of this 
![image](https://github.com/jitpack/jitpack.io/assets/144904817/9cf25376-554d-4aa1-bf5b-17c093a44535)
