### ISSUE TITLE
gradle wrapper ./gradlew install

### ISSUE THREAD

**Issue by Hu12037102** [jitpack/jitpack.io#4246]
Please provide:

- Link to build log from https://jitpack.io

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?

- What error are you seeing?

Thank you!

**Comment by yalematta** [comment]
Make sure you're inserting  maven { url "https://jitpack.io" } inside repositories of allprojects {...}

**Comment by cyb3rko** [comment]
Please add the requested information
