### ISSUE TITLE
Instructions to disable jitpack are missing

### ISSUE THREAD

**Issue by Lanchon** [jitpack/jitpack.io#4250]
I don't want jitpack builds of an github open source project of mine.

i can't find documentation on how to configure my project to disable jitpack builds.

how do i go about disabling jitpack? or is the company so incredibly disrespectful of the developer community that it doesn't provide a way?

**Comment by tr7zw** [comment]
I second this. People blindly use the jitpack builds which are built incorrectly causing a ton of problems. How can I turn off that jitpack tries to provide these broken jars?
