### ISSUE TITLE
I am already using gradle 6.1.1, but jitpack shows this error

### ISSUE THREAD

**Issue by niraj-prajapati** [jitpack/jitpack.io#4252]
- Link to build log from https://jitpack.io
https://jitpack.io/com/github/niraj-prajapati/scanner/1.0.3/build.log

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?
yes

- What error are you seeing?
> Failed to apply plugin [id 'com.android.internal.version-check']
   > Minimum supported Gradle version is 6.1.1. Current version is 4.8.1. If using the gradle wrapper, try editing the distributionUrl in /home/jitpack/build/gradle/wrapper/gradle-wrapper.properties to gradle-6.1.1-all.zip

Thank you!

**Comment by jeffque** [comment]
Related to #4261

**Comment by jitpack-io** [comment]
Hi,

There is an issue with the gradle wrapper:
`WARNING: gradle/wrapper/gradle-wrapper.jar does not exist! Needs to be committed.`
