### ISSUE TITLE
jitpack service is down. Unable to login nor able to reach  'https://jitpack.io/com/...'

### ISSUE THREAD

**Issue by pradeep-plenty** [jitpack/jitpack.io#4258]
**Describe the bug**
Jitpack service is down.
We are unable to login or access the repository

**To Reproduce**
1. just try to signin and it goes into a endless loop

**Expected behavior**
signin to iitpack

**Comment by alexandrebouchard** [comment]
Same here.

**Comment by soportepagando** [comment]
Having the same problem

**Comment by jhuzetrackvia** [comment]
Same here.

**Comment by xujichang** [comment]
+1

**Comment by asmenter360** [comment]
+1

**Comment by pradeep-plenty** [comment]
Builds are still failing. Any update on this issue?

**Comment by juannazarevich** [comment]
+1

**Comment by leo-pedidosya** [comment]
+1
Getting 521 Http error

**Comment by pringleActivity** [comment]
+1

**Comment by sina-tabriziyan** [comment]
+1
