### ISSUE TITLE
build issue No build artifacts found

### ISSUE THREAD

**Issue by khoyron** [jitpack/jitpack.io#4263]
Please provide:

https://jitpack.io/com/github/mkhoiron/Actionsheet-android/0.5/build.log

BUILD SUCCESSFUL in 0s
3 actionable tasks: 2 executed, 1 up-to-date
Build tool exit code: 0
Looking for artifacts...
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2
Looking for pom.xml in build directory and ~/.m2
2020-07-06T08:51:54.193839176Z
Exit code: 0

ERROR: No build artifacts found

Thank you!

**Comment by jeffque** [comment]
When you try in your machine, the command creates the `pom.xml` in the `.m2` directory?
