### ISSUE TITLE
Version with plus sign not working properly

### ISSUE THREAD

**Issue by jeffque** [jitpack/jitpack.io#4265]
## Link to build log from https://jitpack.io

https://jitpack.io/com/gitlab/geosales-open-source/totalcross-resultset-extractor/-1.0.0+retrolambda-ge57c03c-1/build.log

This build was triggered when I added the dependency `com.gitlab.geosales-open-source:totalcross-resultset-extractor:1.0.0+retrolambda` in my project.

The tag in my project is there for further reference https://gitlab.com/geosales-open-source/totalcross-resultset-extractor/-/tags/1.0.0+retrolambda

## Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?

Yes, it does build. Indeed, when I changed to dash, it worked fine https://jitpack.io/com/gitlab/geosales-open-source/totalcross-resultset-extractor/1.0.1-retrolambda/build.log

## What error are you seeing?

> Invalid version: -1.0.0+retrolambda-ge57c03c-1

🤷 

As what I understood from [SemVer](https://semver.org/#backusnaur-form-grammar-for-valid-semver-versions), when I build my project with a different "build flavor" I should make it appearant with a `+<BUILD>` at the end of the version string. So, in some projects I have a need of a Java 8 vanilla build and, for some special purposes I need a "retrolambdized" flavor. So I would denote this flavor with a `+retrolambda` string at the end of the version.

To work around this apparent problem with JitPack, I discarded the plus sign and used the dash, so the "retrolambdized" flavor is denoted now with a `-retrolambda`. And I feel that this isn't properly the SemVer way.

**Comment by jitpack-io** [comment]
Hi,

The `+` symbol works inside git branches and tags but it is not valid in Maven/Gradle if part of version. This is unfortunate.

**Comment by jeffque** [comment]
I use the plus sign in my artifacts with no problem. Indeed I can serve my artifact with it using Artifactory https://maven.totalcross.com/artifactory/webapp/#/artifacts/browse/tree/General/repo1-release/br/com/softsite/totalcross-functional-toolbox/2.0.0+NOOP+retrolambda (please note that I am not using TotalCross Maven Artifactory anymore). And adding the dependency

```xml
<dependency>
    <groupId>br.com.softsite</groupId>
    <artifactId>totalcross-functional-toolbox</artifactId>
    <version>2.0.0+NOOP+retrolambda</version>
</dependency>
```

is alright. I don't know about Maven central. Gradle solved the transitive dependency `br.com.softsite:totalcross-functional-toolbox:2.0.0+NOOP` also.
