### ISSUE TITLE
Custom domain for organization not working

### ISSUE THREAD

**Issue by Silthus** [jitpack/jitpack.io#4271]
**Describe the bug**
I want to configure a custom domain for one of my projects that resides in an organization: https://github.com/art-framework/art-framework. In this project I have multiple modules that should be published under the custom subdomain/groupId: `net.silthus.art`.

I also configured the corresponding DNS records to map the groupId `net.silthus.art` to my organization.
![image](https://user-images.githubusercontent.com/755327/87349660-f8c8f400-c556-11ea-8c08-bb26573a7ee5.png)

However I am not able to query jitpack for any of the modules/repositories: 

![image](https://user-images.githubusercontent.com/755327/87350335-02069080-c558-11ea-93ed-be0a9f60a5a7.png)
![image](https://user-images.githubusercontent.com/755327/87350366-0b8ff880-c558-11ea-8e74-ec236f9b81af.png)

**Expected behavior**
I expect my submodules to be published under the custom domain name.

Am I doing something wrong? How can I get my one project inside the organization to publish its sub-modules into the custom groupid?

**Comment by jitpack-io** [comment]
Hi,

It seems there is an existing DNS entry for `git.silthus.net` pointing to `"https://github.com/silthus"`
That will take precedence and will try to resolve to repository `https://github.com/silthus/art` with the assumption that there might be a module named `art-core`.

For debugging we have an API to custom dns resolutions:
https://jitpack.io/api/resolve/net.silthus.art/art-core/1.0

**Comment by Silthus** [comment]
Hi,

thanks for the answer. But shouldn’t this be the other way around? So that subdomains take precedence over the top domains?
From a user perspective I would expect that I can create a primary dns entry pointing to my main domain and then specific subdomains for other group ids.

Should this be considered a bug?
