### ISSUE TITLE
Error Building message with no explanation

### ISSUE THREAD

**Issue by egeucak** [jitpack/jitpack.io#4276]
**Describe the bug**
Hi! First of all, thanks for the great product.

I can't build my project in jitpack anymore even though my builds were working couple of months ago, and maven package works perfectly fine in my environment.

**To Reproduce**
1. Go to https://jitpack.io/#Paraboly/excel-reports-lib/
2. Click on get a version, and go to the logs.
3. Scroll down to bottom

**Expected behavior**
I expect my build to succeed, and be able to access it from my other product.

**Screenshots**
![image](https://user-images.githubusercontent.com/15627365/87811186-ec021400-c866-11ea-9321-c03f34d8e3d8.png)
It says build success, and then says 'Error building'. Isn't it weird?

**Additional context**

**Comment by jeffque** [comment]
Can you link the repo from this library?

**Comment by RoinujNosde** [comment]
@egeucak it seems Jitpack is working for you now. How did you fix it? I'm having a similar problem.

**Comment by egeucak** [comment]
> @egeucak it seems Jitpack is working for you now. How did you fix it? I'm having a similar problem.

Honestly I have no idea. I was changing random stuff in pom.xml then it worked.
