### ISSUE TITLE
Stopped work for me :(    https://jitpack.io/#paivaric/rollbar-logback/0.1.4

### ISSUE THREAD

**Issue by paivaric** [jitpack/jitpack.io#428]
Downloading: https://jitpack.io/com/github/paivaric/rollbar-logback/0.1.4/rollbar-logback-0.1.4.pom
[WARNING] The POM for com.github.paivaric:rollbar-logback:jar:0.1.4 is missing, no dependency information available
Downloading: https://jitpack.io/com/github/paivaric/rollbar-logback/0.1.4/rollbar-logback-0.1.4.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE

**Comment by jitpack-io** [comment]
Hi @paivaric 

How's now? Could you please retry

**Comment by paivaric** [comment]
Now yeat!!!
Great!!!
Than you so much!!!
