### ISSUE TITLE
Jawajer

### ISSUE THREAD

**Issue by mohagj-hhfs** [jitpack/jitpack.io#4292]
Please provide:

- Link to build log from https://jitpack.io

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?

- What error are you seeing?

Thank you!

**Comment by cyb3rko** [comment]
It seems like your issue is empty. Please delete it or edit it to explain your problem.

**Comment by mohagj-hhfs** [comment]
في الاثنين، 10 آب، 2020 3:18 م Cyb3rKo <notifications@github.com> كتب:
