### ISSUE TITLE
failure to build with jitpack but builds fine on computer

### ISSUE THREAD

**Issue by dtracers** [jitpack/jitpack.io#43]
https://jitpack.io/com/github/fakemongo/fongo/66a66f19c8b4d68f9c1a725d5ee10b029b372180/build.log

here is a comment about the failure on the specified repository:
https://github.com/fakemongo/fongo/issues/101#issuecomment-96436874

It builds fine locally on a MacOSX 10.10.3

specifically build failure is missing the java Path class
```
[ERROR] /build/src/test/java/com/github/fakemongo/impl/index/IndexTest.java:[60,4] cannot access java.nio.file.Path
class file for java.nio.file.Path not found
    assertThat(resultObject).isEqualTo(sourceObject);
```

Path did not exist till the 1.7 jdk could this be causing the issue?

**Comment by jitpack-io** [comment]
Hi
Yes, the jdk version is causing it to fail. The pom.xml specifies jdk 1.6 so JitPack uses  that to build https://github.com/fakemongo/fongo/blob/master/pom.xml#L183

Not sure why Path is used in fongo together with 1.6...

**Comment by dtracers** [comment]
It appears they recently merged in a change which breaks the build.  I addressed the issue on their repository.  So This can be closed.
If the issue continues even with the build being fixed on their end then ill reopen it.

Thanks!
