### ISSUE TITLE
passport/1.0 build

### ISSUE THREAD

**Issue by deadpixelsociety** [jitpack/jitpack.io#430]
Log https://jitpack.io/com/github/deadpixelsociety/passport/1.0/build.log

Kotlin project failed with PermGen build error.

**Comment by deadpixelsociety** [comment]
I believe it was an issue with a large heap size setting I had in gradle.properties. After removing that and pointing to the new commit it seems to compile fine.

**Comment by jitpack-io** [comment]
Hi 

Rebuilt 1.0 and it looks all right now. Pom and aar are there.

**Comment by deadpixelsociety** [comment]
Yup, everything looks square. Thanks.
