### ISSUE TITLE
JitPack builds are currently down

### ISSUE THREAD

**Issue by gdude2002** [jitpack/jitpack.io#4303]
![image](https://user-images.githubusercontent.com/204153/91236808-e1258380-e730-11ea-9923-89a1979418f2.png)

Gotta love that roll-over.

Any ETA on this? It's causing build timeouts and we can't get our fixes out, as one of our dependencies exclusively uses JitPack.

**Comment by dominikaaaa** [comment]
![image](https://user-images.githubusercontent.com/17222512/91241324-96950e80-e712-11ea-89b7-7c5cf31ffd21.png)
Can confirm it's still down. Really inconvenient as some of my stuff is also only on jitpack

**Comment by dabitdev** [comment]
same issue here, this is blocking my releases today

**Comment by gdude2002** [comment]
It appears to be back, after around 5h30m.

**Comment by Hmawn** [comment]
#4303

**Comment by gdude2002** [comment]
That is this issue, yes.
