### ISSUE TITLE
Jitpack is down again

### ISSUE THREAD

**Issue by pradeep-plenty** [jitpack/jitpack.io#4304]
Jitpack service is down again.
We are unable to login or access the repository

To Reproduce

just try to signin and it goes into a endless loop
Expected behavior
signin to iitpack

**Comment by pradeep-plenty** [comment]
> Jitpack service is down again.
> We are unable to login or access the repository
> 
> To Reproduce
> Steps to reproduce the behavior:
> 
> just try to signin and it goes into a endless loop
> Expected behavior
> signin to iitpack

Seems like jitpack is still down?

**Comment by Hmawn** [comment]
Gooò
