### ISSUE TITLE
[Gradle] 'maven' plugin is deprecated and is incompatible with Gradle 7

### ISSUE THREAD

**Issue by elect86** [jitpack/jitpack.io#4308]
**Describe the bug**
Jitpack relies on the `install` task of the `maven` plugin. This plugin is however marked as deprecated

Is there an alternative right now?

I tried `maven-publish` but it misses the `install` task

The options I can see are:
- having a possibility to define a custom task to run
- define and simulate the `install` task manually

**Comment by elect86** [comment]
Fixed by using `maven-publish` and adding

```
publishing.publications.register("mavenJava", MavenPublication::class) {
    from(components["java"])
    artifact(sourceJar)
}
```

**Comment by sahlone** [comment]
@elect86  I did the same but I am getting error on MavenPublication::class
