### ISSUE TITLE
java.lang.OutOfMemoryError: Metaspace

### ISSUE THREAD

**Issue by elect86** [jitpack/jitpack.io#4310]
Please provide:

- [build log](https://jitpack.io/com/github/kotlin-graphics/kotlin-unsigned/093f3525/build.log)

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ? Yep

- What error are you seeing?

> java.lang.OutOfMemoryError: Metaspace

Whenever I have the `dokkaJavadocJar` task enabled, then the build fails

I know it says 

> Task :compileJava FAILED

But actually the problem is the `dokkaJavadocJar` since whenever I disabled it, it works flawless

Any hint?

**Comment by Im-Fran** [comment]
I found out a solution to this issue: https://github.com/Kotlin/dokka/issues/1405#issue-688547883
