### ISSUE TITLE
Builds fails with git-upload-pack error. Tags arent refreshing 

### ISSUE THREAD

**Issue by anuragdalia** [jitpack/jitpack.io#4317]
Please provide:

- Link to build log from https://jitpack.io
   **https://jitpack.io/com/gitlab/anuragdalia/ads-interface/c6a1c00e64/build.log**

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?
   **yes**

- What error are you seeing?
```
Git error. Retrying.
Git error. https://gitlab.com/anuragdalia/ads-interface.git: git-upload-pack not permitted on 'https://gitlab.com/anuragdalia/ads-interface.git/'
```

Thank you!

**Comment by kaiott** [comment]
Any luck fixing this? I have the same problem, just happening from one day to another, and it affects all repos.
