### ISSUE TITLE
Snapshot artifacts are not available in -SNAPSHOT url

### ISSUE THREAD

**Issue by shamoh** [jitpack/jitpack.io#432]
File maven-metadata.xml is available in -SNAPSHOT URL, e.g. https://jitpack.io/com/github/shamoh/mega/mega-gradle-plugin/-SNAPSHOT/maven-metadata.xml

```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<metadata modelVersion="1.0.0">
    <groupId>com.github.shamoh.mega</groupId>
    <artifactId>mega-gradle-plugin</artifactId>
    <version>-7d2306cde8-1</version>
    <versioning>
        <snapshot>
            <timestamp>7d2306cde8</timestamp>
            <buildNumber>1</buildNumber>
        </snapshot>
    </versioning>
</metadata>
```

But referenced artifact is not available in `-SNAPSHOT` URL, e.g. https://jitpack.io/com/github/shamoh/mega/mega-gradle-plugin/-SNAPSHOT/mega-gradle-plugin--7d2306cde8-1.pom

I guess it is expected it is available at URL https://jitpack.io/com/github/shamoh/mega/mega-gradle-plugin/-7d2306cde8-1/mega-gradle-plugin--7d2306cde8-1.pom. But maven or gradle has no way how to guess it.

I think that correct fix is that request to https://jitpack.io/com/github/shamoh/mega/mega-gradle-plugin/-SNAPSHOT/maven-metadata.xml is automatically redirected to https://jitpack.io/com/github/shamoh/mega/mega-gradle-plugin/-7d2306cde8-1/maven-metadata.xml.

---

This issue describes regression of Jitpack. Couple of weeks again everything worked without problem. See https://travis-ci.org/shamoh/mega-examples/builds.

**Comment by jitpack-io** [comment]
Hi

Thanks for the detailed report! Looks like it works with maven but not gradle. Will have a look...

Getting this output when installing via maven:
```
Downloading: https://jitpack.io/com/github/shamoh/mega/mega-gradle-plugin/-SNAPSHOT/maven-metadata.xml
Downloaded: https://jitpack.io/com/github/shamoh/mega/mega-gradle-plugin/-SNAPSHOT/maven-metadata.xml (392 B at 0.3 KB/sec)
Downloading: https://jitpack.io/com/github/shamoh/mega/mega-gradle-plugin/-ca1c2c6637-1/mega-gradle-plugin--ca1c2c6637-1.pom
Downloaded: https://jitpack.io/com/github/shamoh/mega/mega-gradle-plugin/-ca1c2c6637-1/mega-gradle-plugin--ca1c2c6637-1.pom (417 B at 2.3 KB/sec)
Downloading: https://jitpack.io/com/github/shamoh/mega/mega-gradle-plugin/-ca1c2c6637-1/mega-gradle-plugin--ca1c2c6637-1.jar
Downloaded: https://jitpack.io/com/github/shamoh/mega/mega-gradle-plugin/-ca1c2c6637-1/mega-gradle-plugin--ca1c2c6637-1.jar (24 KB at 29.0 KB/sec)
```

**Comment by jitpack-io** [comment]
Ok, fixed and works on the latest snapshot.
