### ISSUE TITLE
Build failed due to gradle

### ISSUE THREAD

**Issue by Autnhiveadmin** [jitpack/jitpack.io#4324]
Please provide:

- https://jitpack.io/org/bitbucket/Autnhive/intactlib-and/1.0-alpha02/build.log

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ? - YES

- What error are you seeing? - FAILURE: Build failed with an exception.

* Where:
Build file '/home/jitpack/build/app/build.gradle' line: 1

* What went wrong:
A problem occurred evaluating project ':app'.
> Failed to apply plugin [id 'com.android.internal.version-check']
   > Minimum supported Gradle version is 5.6.4. Current version is 4.8.1. If using the gradle wrapper, try editing the distributionUrl in /home/jitpack/build/gradle/wrapper/gradle-wrapper.properties to gradle-5.6.4-all.zip

Thank you!

**Comment by AkashaP** [comment]
Bump. Same issue

Please provide:

- Link to build log from https://jitpack.io
* What went wrong:
```
An exception occurred applying plugin request [id: 'org.jetbrains.kotlin.jvm', version: '1.4.10']
> Failed to apply plugin [id 'org.jetbrains.kotlin.jvm']
   > The current Gradle version 4.8.1 is not compatible with the Kotlin Gradle plugin. Please use Gradle 5.3 or newer, or the previous version of the Kotlin plugin.
```


- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?
yes


Why is jitpack gradle 2 entire releases outdated anyway?
