### ISSUE TITLE
Jitpack shows error unable to resolve dependency 

### ISSUE THREAD

**Issue by karanveer0802** [jitpack/jitpack.io#4329]
Please provide:

- Link to build log from https://jitpack.io

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?

- What error are you seeing?

Thank you!

**Comment by karanveer0802** [comment]
Could not resolve com.github.karanveer0802:flightmaptelematry:1.0.0.

**Comment by jaeuwi74** [comment]
hi,

i test to create a fresh application

Could not find com.github.potterhsu:RtspLibrary:v1.0.


* What went wrong:
Could not determine the dependencies of task ':app:testDebugUnitTest'.
> Could not resolve all task dependencies for configuration ':app:debugUnitTestRuntimeClasspath'.
   > Could not find com.github.potterhsu:RtspLibrary:v1.0.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/github/potterhsu/RtspLibrary/v1.0/RtspLibrary-v1.0.pom
       - https://jcenter.bintray.com/com/github/potterhsu/RtspLibrary/v1.0/RtspLibrary-v1.0.pom
       - https://jitpack.io/com/github/potterhsu/RtspLibrary/v1.0/RtspLibrary-v1.0.pom




build.gradle (root) -->
allprojects {
    repositories {
        google()
        jcenter()
        maven { url "https://jitpack.io" }

    }
build.gradle (APP) -->
dependencies {
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation 'androidx.appcompat:appcompat:1.1.0'
    implementation 'com.google.android.material:material:1.0.0'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
    implementation 'androidx.navigation:navigation-fragment:2.1.0'
    implementation 'androidx.navigation:navigation-ui:2.1.0'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test.ext:junit:1.1.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'
    implementation 'com.github.PhilJay:MPAndroidChart:v3.1.0'
    implementation 'com.github.potterhsu:RtspLibrary:v1.0'

}
