### ISSUE TITLE
**WHY????????ERROR: No build artifacts found**

### ISSUE THREAD

**Issue by harisucici** [jitpack/jitpack.io#4334]
**WHY????????ERROR: No build artifacts found**
**WHY????????ERROR: No build artifacts found**
**WHY????????ERROR: No build artifacts found**
**WHY????????ERROR: No build artifacts found**

Build starting...
Start: Tue Sep 29 04:46:18 UTC 2020 a23ea21a4c5d
Git:
0.0.1-0-g6ff023e
commit 6ff023e3d87a72a9256c67116893ea7c90f1e517
Author: harisucici 
Date:   Tue Sep 29 12:43:42 2020 +0800

    1.配置gradle

Found Android manifest
Android SDK version: 29. Build tools: 30.0.0
Installing Android platform 29
Installing Build-tools 30.0.0 
Found gradle
Gradle build script
Found gradle version: 6.7.
Using gradle wrapper
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2
Downloading https://services.gradle.org/distributions/gradle-6.7-rc-2-all.zip
.10%.20%.30%.40%.50%.60%.70%.80%.90%.100%

Welcome to Gradle 6.7-rc-2!

Here are the highlights of this release:
 - File system watching is ready for production use
 - Declare the version of Java your build requires
 - Java 15 support

For more details see https://docs.gradle.org/6.7-rc-2/release-notes.html

------------------------------------------------------------
Gradle 6.7-rc-2
------------------------------------------------------------

Build time:   2020-09-25 20:14:44 UTC
Revision:     a57db4f9f8ee3f033fd1137d97d351d6b9c637fd

Kotlin:       1.3.72
Groovy:       2.5.12
Ant:          Apache Ant(TM) version 1.10.8 compiled on May 10 2020
JVM:          1.8.0_252 (Private Build 25.252-b09)
OS:           Linux 4.18.0-25-generic amd64

0m4.404s
Getting tasks: ./gradlew tasks --all
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2
Tasks: 

WARNING:
Gradle 'install' task not found. Please add the 'maven' or 'android-maven' plugin.
See the documentation and examples: https://jitpack.io/docs/

Adding maven plugin
Found android library build file in websocketlib
Running: ./gradlew clean -Pgroup=com.gitee.harisucici -Pversion=0.0.1 install
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2
Received 0 file system events since last build while watching 1 hierarchies
Virtual file system retained information about 225 files, 4 directories and 0 missing files since last build

> Configure project :
Gradle version Gradle 6.7-rc-2

FAILURE: Build failed with an exception.

* What went wrong:
Task 'install' not found in root project 'build'.

* Try:
Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 744ms
Received 0 file system events during the current build while watching 1 hierarchies
Virtual file system retains information about 240 files, 6 directories and 0 missing files until next build
Build tool exit code: 0
Looking for artifacts...
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2
Looking for pom.xml in build directory and ~/.m2
2020-09-29T04:47:07.140599067Z
Exit code: 0

ERROR: No build artifacts found

**Comment by Kieaer** [comment]
Because task ``install`` not found in your build.gradle
