### ISSUE TITLE
Received status code 403 from server: Forbidden

### ISSUE THREAD

**Issue by Kyun9x** [jitpack/jitpack.io#4348]
Hi
Please provide:

- Link to build log from https://jitpack.io
https://jitpack.io/com/github/Kyun9x/MarketPlace/1.0.9/build.log

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?
no

- What error are you seeing?
Could not GET 'https://www.jitpack.io/com/github/Kyun9x/zalopay/1.0.9/zalopay-1.0.9.pom'. Received status code 403 from server: Forbidden

My lib import sdk name zalopay to Lib and i cannot rebuild in my Project. Do you have a solution for this?
Thank you!

**Comment by Kyun9x** [comment]
Hi, Anyone can support me here? thank.

**Comment by Kyun9x** [comment]
@jitpack-io

**Comment by maxoyano** [comment]
@jitpack-io similar error here Could not HEAD 'https://jitpack.io/org/jitsi/react/jitsi-meet-sdk/2.4.0/jitsi-meet-sdk-2.4.0.pom'. Received status code 403 from server: Forbidden

**Comment by jitpack-io** [comment]
Hi all,

A 403 usually indicates that a trial has expired for a private repository. 
If you get a 403 we recommend opening the build log which should provide more details.
