### ISSUE TITLE
Badge url "flat-squared"

### ISSUE THREAD

**Issue by MDXDave** [jitpack/jitpack.io#435]
Better using ```?style=flat-square``` insted of ```?style=flat-squared``` to avoid confusing (or allowing both parameters).
Because [shield.io](https://shield.io) using ```flat-square``` without ending _d_ and its used by many developers :smile:

**Comment by jitpack-io** [comment]
Good point! Will be switching to `?style=flat-square`
Thanks!

**Comment by jitpack-io** [comment]
Done and updated docs https://jitpack.io/docs/#badges
