### ISSUE TITLE
Can't compile artifact for java 15

### ISSUE THREAD

**Issue by vananiev** [jitpack/jitpack.io#4355]
Packaging ends up with an error
![2020-10-26_00-27-03](https://user-images.githubusercontent.com/11336712/97119535-f5323500-1721-11eb-88c3-32d40f128f88.png)
Report shows
```
Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project table-wrapper-api: Fatal error compiling: invalid target release: 15 -> [Help 1]
```

**Comment by vananiev** [comment]
I found solution for java 14 in gh-4260.
```yaml
$ cat jitpack.yml
before_install:
  - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh
  - source install-jdk.sh --feature 14
  - jshell --version
```
But it does not work for java 15. Can you add support for openjdk15? Usual configuration way
```yaml
$ cat jitpack.yml
jdk:
  - openjdk14 # or openjdk15
```
will be best solution. Thanks!

**Comment by raffaeleragni** [comment]
I am in the same situation, trying to compile a java 15 project.

**Comment by jeffque** [comment]
@vananiev , I am now with this situation.

sormuras/bach project now supposedly supports Java 15 and for what I understood Java 16, but I have not tested it yet. I'm going to try [sdkman](https://sdkman.io/)

**Comment by jeffque** [comment]
It worked, albeit I am sure that it is a really ugly workaround.

- `jitpack.yml` https://gitlab.com/geosales-open-source/toolbox-serialization/-/blob/b646efcee2c22a5380f5e7b58cad0ec8995316fc/jitpack.yml
- `ensure-java-15` homebrewed script: https://gitlab.com/geosales-open-source/toolbox-serialization/-/blob/b646efcee2c22a5380f5e7b58cad0ec8995316fc/ensure-java-15

**Comment by ice1000** [comment]
I'm stucking in this situation too, and this one works

**Comment by OpenSrcerer** [comment]
> It worked, albeit I am sure that it is a really ugly workaround.

I did have a small problem during the Jitpack build, due to the lack of proper permissions for that homebrewed script you uploaded. Thus, if you get this error:

```log
Running before_install command:
./ensure-java-15 install
/script/buildit.sh: line 41: ./ensure-java-15: Permission denied
Running install command:
if ! ./ensure-java-15 use; then source ~/.sdkman/bin/sdkman-init.sh; fi;java -version;./mvnw -pl gwt,default install
/script/buildit.sh: line 50: ./ensure-java-15: Permission denied
```

Make sure that your `ensure-java-15` sh file has execution permissions. You can do that as such:
```
git update-index --add --chmod=+x build.sh
git commit -m 'Make build.sh executable'
git push
```

Found the solution [here](https://stackoverflow.com/a/42187039/15565934).  
Only went smoothly afterwards. Thank you for the script and config.

**Comment by ice1000** [comment]
@OpenSrcerer try `bash ensure-java-15 install`

**Comment by OpenSrcerer** [comment]
> @OpenSrcerer try `bash ensure-java-15 install`

Seems like this works as well, thanks!

**Comment by jeffque** [comment]
@OpenSrcerer , thanks for the feedback. I have commited it as executable but had not mentioned it 

I will edit the comment so that it can be more helpful for more people

**Comment by PikaMug** [comment]
Is anyone else having issues with this workaround lately? SDKman defaults to previous installation at `/home/jitpack/.sdkman/` and ends in `⚠️ ERROR: No build artifacts found` on a basic Maven project. [Log](https://jitpack.io/com/github/Browsit/MilkGUI/a4722aa1f4/build.log)

**Comment by jeffque** [comment]
@PikaMug , add `--show-version` to your `mvn` command line arguments. It will show you exactly what version of java maven is using. For me it seems that it is running Java 16.

For some time now I changed the way of distributing my open source jars build. I just used my CI tooling to publish the jar (I just saw that GitHub actions can publish your jar as a package).

**Comment by OpenSrcerer** [comment]
lol
