### ISSUE TITLE
Subscription issue

### ISSUE THREAD

**Issue by vmosconecds** [jitpack/jitpack.io#4368]
Please provide:

- Link to build log from https://jitpack.io

N/A

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?

Yes

- What error are you seeing?

Subscription is not active right now
Requested subscription: github.com/pngme. 
Your subscriptions are listed in User Settings.
Please contact Support or repository admins if you need assistance.

Thank you!

**Comment by doconline-health** [comment]
I have the same issue Pls help me get through this.

Subscription is not active right now
Requested subscription: gitlab.com/doconline-android. 
Your subscriptions are listed in User Settings.
Please contact Support or repository admins if you need assistance.

**Comment by doconline-health** [comment]
What's the direct channel to contact jitpack support team
