### ISSUE TITLE
Log not available

### ISSUE THREAD

**Issue by SandroMachado** [jitpack/jitpack.io#437]
I have no access to https://jitpack.io/com/github/SandroMachado/BitcoinPaymentURI/1.0.0/build.log

I got this message: `Subscription not found for github.com/sandromachado. Contact support.`

Now the users need to pay to get access to the logs or to the assets?

I am trying to find why I cannot access to the library using the `compile` and I cannot see if the build was built successfully.

**Comment by jitpack-io** [comment]
Hi

Not seeing that message at the moment. Is it still happening?

**Comment by SandroMachado** [comment]
Not, It is working now. Thanks :+1:

**Comment by jitpack-io** [comment]
Ah good, sorry for the trouble! It could be that JitPack couldn't connect GitHub and assumed it was a private repository.

**Comment by SandroMachado** [comment]
Thanks @jitpack-io! Great service and great support.
