### ISSUE TITLE
android-gpuimage/-v1.1.1-g366033c-174 build

### ISSUE THREAD

**Issue by skonb** [jitpack/jitpack.io#439]
Log https://jitpack.io/com/github/skonb/android-gpuimage/-v1.1.1-g366033c-174/build.log

Hi,  `'A problem occurred starting process 'command '/android/ndk/ndk-build'` when 
`android.useDeprecatedNdk=true` and use old DSL for ndk.

It compiles locally. Is there anything wrong with the [build.gradle](https://github.com/skonb/android-gpuimage/blob/master/library/build.gradle) file to be built on Jitpack?

Thanks in advance.

**Comment by jitpack-io** [comment]
Hi

There was a file permission issue that is now fixed. Rebuilt that version too

**Comment by skonb** [comment]
Hi,

Thanks for the quick fix!
It's working now : )
