### ISSUE TITLE
jitpack interdependencies cannot be resolved

### ISSUE THREAD

**Issue by hoesler** [jitpack/jitpack.io#44]
My jitpack gradle build failed because of not being able to resolve a jitpack dependency: ```Connection to https://jitpack.io refused```

See [build.log](https://jitpack.io/com/github/asoem/greyfish/v1.2.1/build.log)

**Comment by jitpack-io** [comment]
Yes looks like the connection was interrupted during build time. Rebuilt it and it's allright now: https://jitpack.io/#asoem/greyfish/v1.2.1
