### ISSUE TITLE
reark/-v0.1-gcf25d14-70 build

### ISSUE THREAD

**Issue by kypeli** [jitpack/jitpack.io#441]
Log https://jitpack.io/com/github/reark/reark/-v0.1-gcf25d14-70/build.log

**Comment by jitpack-io** [comment]
Hi

There's an error in the log:
`: error: package rx.android.schedulers does not exist`

Haven't looked in detail yet but perhaps a dependency is missing?

**Comment by kypeli** [comment]
Thanks for looking into this! I had to clone the Reark repo myself and Gradle does give me the same error. It doesn't prevent me from compiling the package though, but clearly something wrong with the Reark repo and not Jitpack :)
