### ISSUE TITLE
metrics-opentsdb/metrics-opentsdb-1.0.4 build

### ISSUE THREAD

**Issue by KMax** [jitpack/jitpack.io#442]
Log https://jitpack.io/com/github/sps/metrics-opentsdb/metrics-opentsdb-1.0.4/build.log

**Comment by jitpack-io** [comment]
Hi

Error in the log: `edu/umd/cs/findbugs/FindBugs2 : Unsupported major.minor version 51.0`
Which java version does this project require?

**Comment by KMax** [comment]
The 1.6th version according to the pom.xml:

```
...
<plugin>
  <groupId>org.apache.maven.plugins</groupId>
  <artifactId>maven-compiler-plugin</artifactId>
  <version>3.1</version>
  <configuration>
    <source>1.6</source>
    <target>1.6</target>
  </configuration>
</plugin>
...
```

@sps, please, correct me if I'm wrong.

**Comment by jitpack-io** [comment]
Ah, the issue was that the build was running findbugs which requires java 7. 
Works after disabling findbugs.
