### ISSUE TITLE
Impact of transferring a repo to a different organization

### ISSUE THREAD

**Issue by mduesterhoeft** [jitpack/jitpack.io#4421]
This is a rather a request for information than a feature request. 

We have a [public GitHub repository built with gradle](https://jitpack.io/#moia-dev/lambda-kotlin-request-router). Now we want to transfer this repository to another GitHub organization.

We are wondering about the impact of such an action regarding jitpack. 
- Will the existing builds still be available after the transfer - so will the JitPack maven repo still resolve the old artefacts?
- Will the group id change to the new GitHub organization after the transfer?

Thanks a lot in advance.

**Comment by jitpack-io** [comment]
Hi,

Thanks for reaching out!
The existing builds will be still available with existing groupId.
New organization will have its own groupId. You could even rebuild previous releases under the new groupId.

The other thing to consider is using a custom domain name. That way groupId remains consistent between GitHub organization changes.

**Comment by mduesterhoeft** [comment]
@jitpack-io thanks a lot - this answers my question.
