### ISSUE TITLE
Failed to publish new version

### ISSUE THREAD

**Issue by Chen-Alexander** [jitpack/jitpack.io#4431]
I had such a situation when I was using jitpack.io. I released a version 1.0.0, and then I found a bug in this version during use, so I did the following
1: Delete the version 1.0.0 from the two lists of Releases and Builds;
2: After fixing this bug in the code, compile aar locally and test and find that the bug is fixed;
3: I submitted the latest code to github, and deleted the tag and release of 1.0.0 on github;
4: Then I re-released version 1.0.0 on jitpack.io;
5: Then I cleared the gradle cache and resynchronized the project;
(All the above operations on github occurred under the same branch; all the release operations on jitpack.io were done in accordance with the document guidelines;)
After doing this, I found that the newly downloaded aar code is still a buggy version.
I have repeated the above steps many times, but still cannot download the latest code.
Please help, thanks.

**Comment by Chen-Alexander** [comment]
All of the above happened within two hours, never more than seven days.

**Comment by dkim19375** [comment]
I don't think anyone's going to respond because there are so many spam issues, but I recommend just making a new version

**Comment by Chen-Alexander** [comment]
my god，so crazy.
