### ISSUE TITLE
How do the developers subscribe to the jitpack subscription if someone else signed up for it?

### ISSUE THREAD

**Issue by angelaheelydc** [jitpack/jitpack.io#4437]
Hi,
One of my managers signed up (paid) for jitpack via the site. They don't want to authorize jitpack access to entire suite of repositories.
So, she asked one of the developers to subscribe through their account but they still see the trial version in there. Is there a way to switch the subscription to the developer instead from the manager?
If not possible, how do we cancel managers subscription to jitpack ?

**Comment by jitpack-io** [comment]
Hi,

Yes, it is possible to change but you need to get in touch with Support.

There are other options as well:
- use SSH keys https://jitpack.io/docs/PRIVATE/#ssh-key-authentication to give JitPack access to a specific repository
- Create a new user on GitHub that only has access to specific repositories.
