### ISSUE TITLE
Build failed with ERROR: Time-out getting container status

### ISSUE THREAD

**Issue by mvglasow** [jitpack/jitpack.io#4439]
### Link to build log from https://jitpack.io
https://jitpack.io/org/traffxml/traff-source-android/master-36ef0715cd-1/build.log

### Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?
Yes, see CI log at https://gitlab.com/traffxml/traff-source-android/-/jobs/976036753
For the commands used see the CI script at https://gitlab.com/traffxml/traff-source-android/-/blob/master/.gitlab-ci.yml (essentially `mvn deploy`—no idea what commands JitPack uses).
Also note that the artifact gets built successfully; the error occurs after that.

### What error are you seeing?
The last lines of the log read:

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  18.995 s
[INFO] Finished at: 2021-01-23T06:52:54Z
[INFO] ------------------------------------------------------------------------
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2
Found module: org.traffxml:traff-source-android:0.0.1-SNAPSHOT
Build tool exit code: 0
Looking for artifacts...
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2
Looking for pom.xml in build directory and ~/.m2
Found artifact: org.traffxml:traff-source-android:0.0.1-SNAPSHOT
ERROR: Time-out getting container status
Error building
```

So, apparently, the jar got built but fetching container status failed after that.

### Additional information
This happened at a time when the infrastructure seemed to be having issues: when trying to retrieve artifacts (first build), I got timeout errors most of the time and it took several retries to get the artifacts to build. The issue seemed to have been fixed around the time this build ran; could be related.

I have a couple of other libraries which built successfully, all based off the same boilerplate POM. Off the top of my head, I could not name any differences which could play a role here. I highly suspect this was an infrastructure hiccup rather than faulty code.

**Comment by mvglasow** [comment]
Update: I had to make some changes to my code, resulting in a new git commit, which built successfully this time. Hence, this issue is no longer as urgent as before.

Still I’d like to know what else I can do (other than pushing a new commit) to retry a build. (The change I made was just a change in a dependency version, hence the failure was almost definitely not due to a bug in my code.)

**Comment by jitpack-io** [comment]
Another way to redo the build is to login on https://jitpack.io and delete the build that failed.
Requesting the same version again will result in a new build.
