### ISSUE TITLE
material-dialogs/0.8.5.5 build

### ISSUE THREAD

**Issue by afollestad** [jitpack/jitpack.io#444]
Log https://jitpack.io/com/github/afollestad/material-dialogs/0.8.5.5/build.log

Version 23.2.0 of Google's libs appear to be missing.

**Comment by AzureusSme** [comment]
+1

**Comment by JulienDev** [comment]
+1

**Comment by sdeff** [comment]
+1

**Comment by jitpack-io** [comment]
Hi all
Updated the support library and rebuilt

**Comment by AzureusSme** [comment]
Yay! ♥

**Comment by kaushikb1996** [comment]
Still facing the same issue !

**Comment by PavelSynek** [comment]
Do you import the library like this

    compile('com.github.afollestad.material-dialogs:core:0.8.5.5@aar') {
            transitive = true
    }

? Have you cleaned the project?
