### ISSUE TITLE
How to obtain shaded jar?

### ISSUE THREAD

**Issue by OnyxianSoul** [jitpack/jitpack.io#4447]
Hey there, I recently found out it was possible to obtain the jar jitpack has built prior to the installation, and found it very helpful. #https://github.com/jitpack/jitpack.io/issues/886

**While it works great for me** ( I can obtain the jar from: https://jitpack.io/com/github/OnyxianSoul/ProjectName/version#/ProjectName-#version#.jar ) **i can't seem to figure out how to obtain the shaded jar**

**Is there any way to obtain the shaded jar created by the maven shade plugin? What would be the URL?**

This is the result of one of my builds
https://jitpack.io/com/github/OnyxianSoul/OnyxianCore/ab9987b069/build.log
& The normal jar can be obtained with this URL:
https://jitpack.io/com/github/OnyxianSoul/OnyxianCore/ab9987b069/OnyxianCore-ab9987b069.jar

**Comment by jitpack-io** [comment]
Hi,

You would need to configure Maven to publish the shaded jar along with the normal jar.
Basically if you run `mvn install` the shaded jar should end up in ~/.m2

**Comment by OnyxianSoul** [comment]
Thank you for your answer! I'll try it out when i have the time !
