### ISSUE TITLE
Unable to "GET" latest release from private repository

### ISSUE THREAD

**Issue by geniesit** [jitpack/jitpack.io#4448]
https://github.com/geniesinc/android-composer-library
release 0.0.11

Subscription is not active right now
Requested subscription: github.com/geniesinc. 
Your subscriptions are listed in https://jitpack.io/w/user
Please contact Support or repository admins if you need assistance.
Your active subscriptions: 
github.com:geniesit

**Comment by jitpack-io** [comment]
Hi,

Should be resolved now.

This happens often and here is the reason:
- The subscription was created for repositories under github.com/geniesit (GitHub user)
- The user intended to build repositories under github.com/geniesinc (GitHub organization)
- It is possible to switch your subscription on https://jitpack.io/w/user but that doesn't always work if there already is a trial subscription for your organization created by a different user. In that case you should contact Support.  

When you order a subscription there is dropdown to select an organization that you want to use. However it only lists organizations where your membership is public.
The other option is to click 'Other...' and enter the organization manually. 

Hope this helps
