### ISSUE TITLE
Received status code 403 from server: Forbidden

### ISSUE THREAD

**Issue by khattab93-chamberds** [jitpack/jitpack.io#4450]
Hi,
I got this error 
Could not GET 'https://www.jitpack.io/com/github/superdad-apps/magicblox-android/0.0.3/magicblox-android-0.0.3.pom'. Received status code 403 from server: Forbidden

githup user -> magicblox
githup repo -> superdad-apps/magicblox-android
version -> 0.0.3

**Comment by jitpack-io** [comment]
Hi,

Can confirm that your token has access to the repository.
```
curl -v -u<TOKEN>: 'https://jitpack.io/com/github/superdad-apps/magicblox-android/0.0.3/magicblox-android-0.0.3.pom'
```

A few things to check
1. That you are using the latest token from https://jitpack.io/private#auth
2. That Gradle is configured to send the token to JitPack. Especially if JitPack repository is configured in multiple build files.
