### ISSUE TITLE
Custom domain for multiple organizations does not appear to work

### ISSUE THREAD

**Issue by TobiasDeBruijn** [jitpack/jitpack.io#4454]
**Describe the bug**
Basically what the title says. I've got multiple TXT records with the same name, which to my knowledge is supported by the dns standards (or whatever that is called), since CertBot uses it as well.

Repository: https://github.com/DutchyPlugins/DutchyCore
Domain: thedutchmc.nl

**To Reproduce**
1. Have two organizations
2. Have the same domain for both of them
3. Try to get a build from Jitpack
4. One wont work

**Expected behavior**
Both organizations should work under the same custom domain

**Screenshots**
![image](https://user-images.githubusercontent.com/28569170/107270108-d0509c00-6a4a-11eb-888a-f7fda4b483aa.png)

**Additional context**

**Comment by jitpack-io** [comment]
Hi,

Thanks for raising the issue!
Indeed, this could be made to work as at the moment we just pick the first organization in DNS.

**Comment by TheDutchMC** [comment]
That is a good point yeah. Maybe add to the groupid the organization? so e.g ``nl.thedutchmc.dutchyplugins:dutchycore:version``, basically the same how the default ``com.github.ORG:REPO:VERSION`` is
