### ISSUE TITLE
User still get access to the library after removing his access from the repo

### ISSUE THREAD

**Issue by khattab93** [jitpack/jitpack.io#4456]
Hi,

I tried to test the private share feature. I added this GitHub user `khattab93` to the private repo and gave him read access. He used his JitPack access token within an android project to download the library. Then, I removed him from the repo and he has no longer access to the repo, but he still can use his access token and use the library in the android project and in new projects too.  

githup user -> khattab93
githup repo -> superdad-apps/magicblox-android
version -> 0.0.4

**Comment by khattab93** [comment]
@jitpack-io  Any updates, please? 

After revoking a collaborator from the repo, he still accesses the artifacts and sees the repo in the lookup search for 12 hours later.

Could you please solve this for me? I need to prevent a collaborator from accessing the artifacts immediately after revoking him from the repo.

**Comment by khattab93** [comment]
@jitpack-io Any help please?

**Comment by jitpack-io** [comment]
Hi @khattab93 

Could you please send us the repository url via Support button so we can look into this?
Git access is cache on JitPack for performance/rate-limit reasons but it does eventually expire.
