### ISSUE TITLE
SNAPSHOT build hangs indefinitely

### ISSUE THREAD

**Issue by matshou** [jitpack/jitpack.io#4460]
Please provide:

- Link to build log from https://jitpack.io

   https://jitpack.io/com/github/real-coco-labs/pz-zdoc/hotfix~3.0.1-SNAPSHOT/build.log

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?

   Yes, `gradle build` works just fine on my machine.

- What error are you seeing?

   Build never finishes and the log will not load (it just hangs).

**Comment by yooksi** [comment]
Related: https://github.com/jitpack/jitpack.io/issues/4035
