### ISSUE TITLE
Android Gradle plugin requires Java 11 to run. You are currently using Java 1.8

### ISSUE THREAD

**Issue by amanv8060** [jitpack/jitpack.io#4474]
Please provide:

- https://jitpack.io/com/github/amanv8060/aboutpagelib/0.0.3/build.log

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?

- Android Gradle plugin requires Java 11 to run. You are currently using Java 1.8

Thank you!

**Comment by josejulio** [comment]
I think this could help you: https://jitpack.io/docs/BUILDING/#java-version
> Alternatively create a jitpack.yml file in the root of your repository and specify a jdk version:
```yaml
 jdk:
  - openjdk9
```
> If your project requires a specific Java build then you can use Custom Commands to install it before the build.

**Comment by jitpack-io** [comment]
Hi,

Thank you @josejulio! That's right.
For other java versions you can also use SDK Man that is available on the build servers.

You can use SDKMan in `jitpack.yml`:
```yaml
before_install:
   - sdk install java 11.0.10-open
   - sdk use java 11.0.10-open
```

**Comment by amanv8060** [comment]
https://jitpack.io/com/github/amanv8060/aboutpagelib/492c10d987/build.log 
still does not work

**Comment by zhujiang521** [comment]
before_install:
  - sdk install java 11.0.10-open
  - sdk use java 11.0.10-open

还是不行，报错信息和上面一样，帮忙看看吧

**Comment by HuixingWong** [comment]
> The solution is what @josejulio suggested.
> 
> You can check on [SO](https://stackoverflow.com/a/68756946/3117650) too.
> 
> Create the `jitpack.yml` on your project root folder.

This solution not work it still report this error

**Comment by odbol** [comment]
The sdkman solution in the documentation doesn't seem to work:

https://jitpack.io/com/github/google/tweakr/jitpack-v2.2.0-g66194de-3/build.log

```
Running before_install command:
sdk install java 11.0.10-open;sdk use java 11.0.10-open
/script/buildit.sh: line 41: sdk: command not found
/script/buildit.sh: line 41: sdk: command not found
```
