### ISSUE TITLE
Build fails when using `maven-patch-plugin`

### ISSUE THREAD

**Issue by josejulio** [jitpack/jitpack.io#4475]
Please provide:

- Link to build log from https://jitpack.io : https://jitpack.io/com/github/RedHatInsights/insights-schemas-java/caaaa3c/build.log

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?  Yes

- What error are you seeing? 
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-patch-plugin:1.2:apply (patch) on project insights-notification-schemas-java: Failed to apply patch: Action.java.patch. See debug output for more information. Error while executing process. Cannot run program "patch" (in directory "/home/jitpack/build/insights-notification-schemas-java/src/main/java"): error=2, No such file or directory -> [Help 1]
```

Thank you!

I'm using [maven-patch-plugin](https://maven.apache.org/plugins/maven-patch-plugin/)  and it requires the binary `patch` in the PATH. Is there any way to have it?

**Comment by josejulio** [comment]
I tried using `apt-get install patch` but that fails as in here: https://github.com/jitpack/jitpack.io/issues/3818#issuecomment-633107724

**Comment by diederikMrAwesome** [comment]
I've seen some of out builds also fail with `patch` not being on the image.  From what I've seen so far (warning small sample size) is that the `Ubuntu 16.04.7 LTS 4.18.0-25-generic` images seem to have it installed, but the `Ubuntu 16.04.6 LTS 4.10.0-28-generic` ones does not. :/
