### ISSUE TITLE
Jitpack generates wrong Gradle metadata

### ISSUE THREAD

**Issue by elect86** [jitpack/jitpack.io#4476]
**Describe the bug**

Wrong Gradle metadata generated from build

**To Reproduce**
1. trigger a new build of [kool](https://github.com/kotlin-graphics/kool)
2. Check the `.module` metadata file, this is wrong

```
    "dependencies" : [ {
      "group" : "kx.platform",
      "module" : "source",
      "version" : {
        "requires" : "0.0.9"
      }
    }, {
```

**Expected behavior**

Run the very same command locally, you should get instead the following

```
      "dependencies": [
        {
          "group": "kx.platform",
          "module": "source",
          "version": {
            "requires": "0.0.9"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
```

This is a blocker, because downstream will cause the Idea Gradle project reload to fail because `kx.platform:source:0.0.9` will be seen as a normal dependency instead of a platform

**Comment by skalarproduktraum** [comment]
I am having the same issue. Any chance for this getting fixed? Thanks 👍

**Comment by breandan** [comment]
cc: @jitpack

**Comment by elect86** [comment]
For anyone having this problem, there may be a solution: in your project instead adding the dependency to a classic platform

`implementation(platform("sciJava:platform:30.0.0+6"))`

just apply a plugin which defines [the constraints](https://github.com/elect86/sciJava-platform/blob/master/platform/src/main/kotlin/sciJava/platform.gradle.kts#L46-L118)

This can play well with Gradle 7.0 catalogs with this [workaround](https://github.com/gradle/gradle/issues/15383#issuecomment-779893192)

**Comment by ljjh20** [comment]
I have the same issue.

**Comment by skalarproduktraum** [comment]
I have found a workaround: It works by disabling the Gradle metadata entirely, as the POM created as actually correct. 

Here's the snippet that needs to be added to the `build.gradle.kts`:

```kotlin
if(System.getenv("JITPACK") != null) {
    tasks.withType<GenerateModuleMetadata> {
        enabled = false
    }
}
```
