### ISSUE TITLE
Unable to change subscription repo to organization

### ISSUE THREAD

**Issue by PancastMobileDev** [jitpack/jitpack.io#4477]
**Describe the bug**
When I go to https://jitpack.io/w/user and try and change my repo to my organization repo `Pancast-Product`. The change fails with `Error: Subscription owned by undefined`. The organization github auth for jitpack is correct, so I'm not sure why this does not work?
Jitpack builds are currently failing with:
```
Subscription is not active right now
Requested subscription: github.com/pancast-product. 
Your subscriptions are listed in https://jitpack.io/w/user
Please contact Support or repository admins if you need assistance.
```
But your settings page does not allow me to correct this?

**Screenshots**
![image](https://user-images.githubusercontent.com/79429049/110397219-87314d80-80c5-11eb-8347-d658ee36e1d4.png)

**Comment by jitpack-io** [comment]
Hi,

We've updated the subscription and extended the trial.
For subscription issues we recommend reaching out via the Support button as there could be sensitive information.

Best regards
