### ISSUE TITLE
Badge version String: Should use latest tag by release date

### ISSUE THREAD

**Issue by codebulb** [jitpack/jitpack.io#448]
When using JitPack's shield.io badge on e.g. a GitHub markup page, its version String apparently doesn't refer to the latest build. (Does it possibly refer to the last tag name by alphabetic order? Can't tell for sure). It really would make sense, however, to always refer to the tag name of the latest build because that's the build you want to promote.

Take my "[crudlet](https://github.com/codebulb/crudlet/releases)" project as an example: The three latest tags created were 0.2_RC-1, then 0.2_RC-2, and then 0.2 (the latest tag). Having created a JitPack badge by using the code proposed at https://jitpack.io/#codebulb/crudlet/0.2, the rendered badge does now still refer to 0.2_RC-2, even though 0.2 is the latest release which I would expect it to  refer to.

Badge code:
```
[![](https://jitpack.io/v/codebulb/crudlet.svg)](https://jitpack.io/#codebulb/crudlet)
```

Outcome:
[![](https://jitpack.io/v/codebulb/crudlet.svg)](https://jitpack.io/#codebulb/crudlet) instead of 0.2 (the latest tag)

Since the tag in question has been created 2 days ago now, I don't suspect any sort of caching problem; rather, it seems that the logic which chooses the tag to be displayed is wrong. It **should use the latest tag by release date**.

**Comment by jitpack-io** [comment]
Hi

The jitpack badge shows the latest version by comparing all versions according to semantic versioning. It would show 0.2 as the latest if the rc was called "0.2-RC-2". Unfortunately doesn't work if you have underscores in the version.

**Comment by codebulb** [comment]
Oh, I see. Thank you for clarifying this.
I will thus adapt my versioning schema for future versions.

If you have no further plans to (optionally) change the badge versioning strategy to "ordered by tag release timestamp", you may close this issue. Thank you.
