### ISSUE TITLE
DBFlow 4.2.4 build failed (Impact all expo builds)

### ISSUE THREAD

**Issue by alexyangjie** [jitpack/jitpack.io#4485]
Please provide:

- Link to build log https://www.jitpack.io/com/github/Raizlabs/DBFlow/dbflow/4.2.4/build.log (Version 4.2.4)
- Does the project build on your machine? (Nos sure. This should be a historical build)
- What error are you seeing? N/A

This dependency is used by expo apps, and currently all expo build are failing because of this dependency. Could you please have a look to see what is going on? Thanks.

**Comment by zamplyy** [comment]
I also have this issue.
