### ISSUE TITLE
Cannot resolve com.github.ralfstuckert.pdfbox-layout:pdfbox2-layout:1.0.0

### ISSUE THREAD

**Issue by danielsoro** [jitpack/jitpack.io#4487]
Please provide:

- Link to build log from https://jitpack.io
https://jitpack.io/com/github/ralfstuckert/pdfbox-layout/1.0.0/build.log

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?
Nops.

- What error are you seeing?
I can't download the library for my project and it is breaking my project build.

Thank you!

**Comment by spadigala0** [comment]
I am also having same issue since today. It's working fine yesterday
