### ISSUE TITLE
Is it possible to serve sources and javadoc jars with my library?

### ISSUE THREAD

**Issue by VladoCC** [jitpack/jitpack.io#4489]
I have a release in my project and it contains all three types of jars: library itself, sources and javadoc. But when I get it through gradle I can only see the first one, can't read code or check docs. 

**Describe the solution you'd like**
I'd like it to serve all three of this jars to the receiver auotmatically.

**Alternative solution**
If this thing is implemented already, make it clearer how it's working and what steps are necessary.

**Additional context**
It might be that I'm just missing something. Sorry if so. But I've searched through your FAQ and Docs and wasn't sble to find anything.

**Comment by jitpack-io** [comment]
Hi,

Sure, if your project publishes sources jar and javadoc jar then they will be available on JitPack.

One example: https://github.com/jitpack/gradle-simple
