### ISSUE TITLE
PdfBox-Android/1.8.7 build

### ISSUE THREAD

**Issue by ZinoKader** [jitpack/jitpack.io#449]
Log https://jitpack.io/com/github/TomRoush/PdfBox-Android/1.8.7/build.log

**Comment by jitpack-io** [comment]
Hi

1.8.7 didn't have gradle build files yet but that latest snapshot works
`com.github.TomRoush:PdfBox-Android:2f9fe34`

**Comment by ZinoKader** [comment]
@jitpack-io Thanks!
