### ISSUE TITLE
deano2390/FlowTextView is failing on build machine but not always, shows failure on jitpack website.

### ISSUE THREAD

**Issue by babramovitch** [jitpack/jitpack.io#4493]
Please provide:

- Link to build log from https://jitpack.io

https://jitpack.io/#deano2390/FlowTextView
https://jitpack.io/com/github/deano2390/FlowTextView/2.0.5/build.log

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?

yes

- What error are you seeing?

Could not determine the dependencies of task ':app:compileInternalDebugKotlin'.
> Could not resolve all files for configuration ':app:productionDebugRuntimeClasspath'.
   > Could not resolve com.github.deano2390:FlowTextView:2.0.5.

Note - this is failing on the build machine, but it doesn't fail every time.  It's nearly every time, but sometimes if I start the build again from scratch it works.  It's been working unchanged for a couple years now in the app.

**Comment by jitpack-io** [comment]
Hi,

Rebuilt the project. Should be available now.
