### ISSUE TITLE
Time-out getting container status: AxiosKt/9aabc68f36 + axioskt/1.0.1 build

### ISSUE THREAD

**Issue by twiese99** [jitpack/jitpack.io#4494]
When I wanted to build my project and the build was finished successfully (by gradle), a timeout occurred while querying the container status (see log).

Previously I ran the Gradle build local, there it was successful. The Gradle build scripts are written in Kotlin and the local build was done with Java 11.

- **Build log:** https://jitpack.io/de/twiese99/AxiosKt/9aabc68f36/build.log
- **Build time:** 2020-08-25 15:51:49 UTC

```log
BUILD SUCCESSFUL in 29s
32 actionable tasks: 30 executed, 2 up-to-date
Build tool exit code: 0
Looking for artifacts...
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2
Looking for pom.xml in build directory and ~/.m2
Found artifact: de.twiese99:AxiosKt-js:1.0.0
Found artifact: de.twiese99:AxiosKt:1.0.0
ERROR: Time-out getting container status
Error building
```

**Comment by twiese99** [comment]
Noticed my mistake: the name of my project was capitalized. Lower case works. I'll change the GitHub repository name accordingly.

**Comment by twiese99** [comment]
### Update:
I just wanted to build another version, of the same project. Also this time a TimeOut occurred.

Possibly there is an error (bug) in the communication between a service of JitPack and the build containers.

**Build: https://jitpack.io/de/twiese99/axioskt/1.0.1/build.log**

**Comment by shalva97** [comment]
What was the soluion?
