### ISSUE TITLE
Version 1.0.0 is broken in jitpack repository

### ISSUE THREAD

**Issue by Raul52** [jitpack/jitpack.io#4495]
Hello,

Version 1.0.0 seems broken on https://jitpack.io/#ralfstuckert/pdfbox-layout

I wanted to download the dependency, but it does not recognize it.

Build log: - https://jitpack.io/com/github/ralfstuckert/pdfbox-layout/1.0.0/build.log

**Comment by bmontuelle** [comment]
Hello,
We encountered the same issue here, pdfbox-layout version 1.0.0 yields a 404 in our builds. Seems it is missing since the 25/03
Probable duplicate of #4502

Any input on the issue will be greatly appreciated
