### ISSUE TITLE
Provide a way for users to rebuild a project 

### ISSUE THREAD

**Issue by jitpack-io** [jitpack/jitpack.io#45]
If the build didn't succeed the first time.

**Comment by shkschneider** [comment]
+1

**Comment by johnzeringue** [comment]
:+1:

**Comment by jitpack-io** [comment]
Good news! You can now rebuild a project. 
Sign In on the website you'll see a remove [x] link next to versions of your own projects:
![image](https://cloud.githubusercontent.com/assets/11161622/7794628/5faa55c0-02c4-11e5-91ff-689c5634883f.png)

After removing it can be rebuilt from scratch.

**Comment by mariotaku** [comment]
awesome! thanks!

**Comment by tueda** [comment]
Is there any way to rebuild a build that seemingly succeeded?

I have a build, for which the build status is fine, but somehow the Javadoc page does not appear.

**tueda/donuts/v0.0.2**
Log: https://jitpack.io/com/github/tueda/donuts/v0.0.2/build.log
Javadoc page: https://javadoc.jitpack.io/com/github/tueda/donuts/v0.0.2/javadoc/index.html

The build with the same commit successfully generated the Javadoc page. So, I expect that rebuilding v.0.0.2 may generate its Javadoc page.

**tueda/donuts/fa9d101696** (the same commit as v0.0.2) 
Log: https://jitpack.io/com/github/tueda/donuts/fa9d101696/build.log
Javadoc page: https://javadoc.jitpack.io/com/github/tueda/donuts/fa9d101696/javadoc/index.html

**Comment by tueda** [comment]
When I wrote [my comment above](https://github.com/jitpack/jitpack.io/issues/45#issuecomment-1164127154), the Javadoc page for the second one was correctly displayed, but now both the Javadoc pages show just
```
META-INF/
com/
```
which makes me really confused...
