### ISSUE TITLE
sdk: command not found

### ISSUE THREAD

**Issue by M5rian** [jitpack/jitpack.io#4506]
I'm trying to build a Java 15 project with Jitpack.

# Build log
Latest build log:
> https://jitpack.io/com/github/M5rian/JdaCommandHandler/15921857b5/build.log

GitHub repo:
> https://github.com/M5rian/JdaCommandHandler

# Building on my local machiene
When I build my project I use `./gradlew build`. Using this command it works fine.

Never used `./gradlew install`, but when I run it I get the following output:
```
Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.8.3/userguide/command_line_interface.html#sec:command_line_warnings
```

# Error
Jitpack doesn't use JDK 15 and I get the following error:
```
Running before_install command:
sdk install java 15.0.2-opent;sdk use java 15.0.2-open
/script/buildit.sh: line 41: sdk: command not found
/script/buildit.sh: line 41: sdk: command not found
Found gradle
Gradle build script
Found gradle version: 6.8.3.
Using gradle wrapper
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2
Downloading https://services.gradle.org/distributions/gradle-6.8.3-bin.zip
.10%.20%.30%.40%.50%.60%.70%.80%.90%.100%

[...]

> Task :compileJava
/home/jitpack/build/src/main/java/com/github/m5rian/jdaCommandHandler/commandServices/DefaultCommandService.java:113: error: : expected
            }
             ^
/home/jitpack/build/src/main/java/com/github/m5rian/jdaCommandHandler/commandServices/DefaultCommandService.java:116: error: : expected
            }
             ^
/home/jitpack/build/src/main/java/com/github/m5rian/jdaCommandHandler/commandServices/DefaultCommandService.java:119: error: : expected
            }
             ^
/home/jitpack/build/src/main/java/com/github/m5rian/jdaCommandHandler/commandServices/DefaultCommandService.java:120: error: : expected
            default -> {
                   ^
/home/jitpack/build/src/main/java/com/github/m5rian/jdaCommandHandler/commandServices/DefaultCommandService.java:120: error: illegal start of expression
            default -> {
                    ^
/home/jitpack/build/src/main/java/com/github/m5rian/jdaCommandHandler/commandServices/DefaultCommandService.java:120: error: ';' expected
            default -> {
                      ^
/home/jitpack/build/src/main/java/com/github/m5rian/jdaCommandHandler/commandServices/DefaultCommandService.java:125: error: class, interface, or enum expected
}
```

Thanks in advance!

**Comment by OpenSrcerer** [comment]
I can reproduce this issue in my Maven project. 

### Build Log
https://jitpack.io/com/github/OpenSrcerer/BytesToJava/master-3b777c1601-1/build.log

### Github Repo
https://github.com/OpenSrcerer/bytestojava

---

### Building on my local machine
I use `mvn compile` and everything works neatly. The problem resides in how JitPack doesn't recognize the `sdkman` commands and uses Java 8 when instructed to use Java 15.

### Error
Similarly to @M5rian, here is a snippet of `sdk` failing to execute:
```log
Running before_install command:
sdk install java 15.0.2-open;sdk use java 15.0.2-open
/script/buildit.sh: line 41: sdk: command not found
/script/buildit.sh: line 41: sdk: command not found
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2
Apache Maven 3.6.1 (d66c9c0b3152b2e69ee9bac180bb8fcc8e6af555; 2019-04-04T19:00:29Z)
Maven home: /opt/apache-maven-3.6.1
Java version: 1.8.0_252, vendor: Private Build, runtime: /usr/lib/jvm/java-8-openjdk-amd64/jre // As seen here, the project still uses Java 8 for compilation
Default locale: en, platform encoding: UTF-8
OS name: "linux", version: "4.14.63-xxxx-std-ipv6-64", arch: "amd64", family: "unix"
```

And here's my build failing:
```log
[INFO] Compiling 24 source files to /home/jitpack/build/target/classes
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  9.014 s
[INFO] Finished at: 2021-04-08T10:22:38Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project BytesToJava: Fatal error compiling: invalid target release: 15 -> [Help 1]
```

**Comment by OpenSrcerer** [comment]
@M5rian After some more research, I managed to fix the problem thanks to this comment on [a previously opened issue](https://github.com/jitpack/jitpack.io/issues/4355#issuecomment-744678253).

**Comment by M5rian** [comment]
Yeah, I saw this comment too, but when adding the shell script I get the following error
> /script/buildit.sh: line 41: ./ensure-java-15: Permission denied
I don't think I can do something about that, since that's not running on my system.


> [*full error code*](https://jitpack.io/com/github/M5rian/JdaCommandHandler/85bfdf612c/build.log)

**Comment by OpenSrcerer** [comment]
Read [my and Ice's comments below](https://github.com/jitpack/jitpack.io/issues/4355#issuecomment-815680809).

**Comment by M5rian** [comment]
Thank you! That actually hepled a lot! But there is still an error
```
ERROR: No build artifacts found
```
Build log:
> https://jitpack.io/com/github/M5rian/JdaCommandHandler/c68b48843e/build.log

The weird thing is, that it works now on my local machiene. But not with jitpack. I tried a few solutions, which were suggested online, but they did not change anything. Do you have an idea why? Maybe this has something to do with gradle.

**Comment by derklaro** [comment]
I'm unsure if this helps someone: I resolved the issue like this:
```
before_install:
  - source "$HOME/.sdkman/bin/sdkman-init.sh"
  - sdk update
  - sdk install java 16.0.1.hs-adpt
  - sdk use java 16.0.1.hs-adpt
  ```
Which seems to work fine.

**Comment by PikaMug** [comment]
> 
> 
> I'm unsure if this helps someone: I resolved the issue like this:
> 
> ```
> before_install:
>   - source "$HOME/.sdkman/bin/sdkman-init.sh"
>   - sdk update
>   - sdk install java 16.0.1.hs-adpt
>   - sdk use java 16.0.1.hs-adpt
> ```
> 
> Which seems to work fine. [Example build log](https://jitpack.io/com/github/derklaro/ProtocolLib/13ebc90/build.log)

This worked great for me. Thank you.

**Comment by M5rian** [comment]
Meanwhile I actually switched to JFrog. I'll try this out at a later point.

Thank you for your help!
