### ISSUE TITLE
publishToMavenLocal will not be called.

### ISSUE THREAD

**Issue by toyota-m2k** [jitpack/jitpack.io#4517]
Please provide:

- Link to build log from https://jitpack.io
  https://jitpack.io/com/github/toyota-m2k/bind-it/2f81a46a69/build.log

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?
```
> gradlew tasks --all | grep publish
   libbindit:publish - Publishes all publications produced by this project.
   libbindit:publishReleasePublicationToMavenLocal - Publishes Maven publication 'release' to the local Maven repository. 
   libbindit:publishToMavenLocal - Publishes all Maven publications produced by this project to the local Maven cache.
```
```
> gradlew publishToMavenLocal
   BUILD SUCCESSFUL
```  
- What error are you seeing?

I'm using "maven-publish" as instructed in [Guide to publishing Android libraries](https://jitpack.io/docs/ANDROID/), so I expect 'publishToMavenLocal' will be called, but the build log says "install task not found".
why?
```
WARNING:
Gradle 'install' task not found. Please add the 'maven' or 'android-maven' plugin.
...
FAILURE: Build failed with an exception.

* What went wrong:
Task 'install' is ambiguous in root project 'bind-it'. Candidates are: 'installDebug', 'installDebugAndroidTest'.
...
BUILD FAILED in 1s
Build tool exit code: 0
Looking for artifacts...
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2
Looking for pom.xml in build directory and ~/.m2
2021-04-13T11:29:05.860352451Z
Exit code: 0

ERROR: No build artifacts found
```

Thank you!

**Comment by creepinson** [comment]
Same issue, I think it might be trying to use the outdated maven plugin, instead of maven-publish. However, I can't seem to find a way to make it use the publishToMaven task either.
