### ISSUE TITLE
More JDK support

### ISSUE THREAD

**Issue by LovinLifee** [jitpack/jitpack.io#4535]
My application requires features from JDK 14 and above but it appears I can only use JDK 11, and it seems that if I don't specify a JDK it defaults to 1.8. I'm assuming that Jitpack only supports LTS but it'd be nice to see some newer JDK's. Also I couldn't find any documentation on which JDK's Jitpack supports, maybe making that more clear would have saved a little bit of frustration. 😝

**Comment by pzygielo** [comment]
> and it seems that if I don't specify a JDK it defaults to 1.8. 

indeed: [building#java-version](https://docs.jitpack.io/building/#java-version)

> I'm assuming that Jitpack only supports LTS but it'd be nice to see some newer JDK's

>> Alternatively create a jitpack.yml file in the root of your repository and specify a jdk version

and use `openjdk17`.
