### ISSUE TITLE
Gradle 7.0 fails during publish (solved)

### ISSUE THREAD

**Issue by hannesa2** [jitpack/jitpack.io#4536]
Please provide:

- Link to build log https://jitpack.io/com/github/appdevnext/moka/0.7.1/build.log

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?
  
> No, there is no `install`

- What error are you seeing?

```
Script '/script/maven-plugin.gradle' line: 2

* What went wrong:
A problem occurred evaluating script.
> Failed to apply plugin 'com.github.dcendents.android-maven'.
   > Could not create plugin of type 'AndroidMavenPlugin'.
      > Could not generate a decorated class for type AndroidMavenPlugin.
         > org/gradle/api/publication/maven/internal/MavenPomMetaInfoProvider
```

**Comment by hannesa2** [comment]
Same error with Gradle `7.0.2` https://jitpack.io/com/github/AppDevNext/Moka/0.9.1/build.log

**Comment by serivesmejia** [comment]
the maven plugin has been eliminated in gradle 7.0, see the maven-publish plugin instead.

**Comment by serivesmejia** [comment]
[here's my gradle 7.0 script that uses maven-publish](https://github.com/serivesmejia/EOCV-Sim/blob/62b2f1ab2ffc6dcb156afb7b35bdb3b44ad735df/EOCV-Sim/build.gradle#L15), in case you need an example

**Comment by hannesa2** [comment]
@serivesmejia You use Gradle 7.0 with `v2.2.1` but jitpack.io doesn't work https://jitpack.io/com/github/serivesmejia/EOCV-Sim/v2.2.1/build.log
```
FAILURE: Build failed with an exception.

* What went wrong:
Task 'install' not found in project ':EOCV-Sim'.
```

Any yes, a **working** example would be perfect !

**Comment by serivesmejia** [comment]
yes, jitpack doesn't work on the tagged release but it's fixed on the dev branch. i linked my gradle file that's on the dev branch working :), see https://jitpack.io/com/github/serivesmejia/EOCV-Sim/dev-62b2f1ab2f-1/build.log

**Comment by hannesa2** [comment]
Thanks to @serivesmejia  I made it work. Here you see my complete changes
https://github.com/AppDevNext/Moka/pull/77 and now it works https://jitpack.io/#AppDevNext/moka/1.0

**Comment by xanscale** [comment]
what's the correct solution to use gradle 7 in jitpack ?

just wait official support or we need to do something in our projects  ??

thz
