### ISSUE TITLE
Is jitpack.io down?

### ISSUE THREAD

**Issue by advissor** [jitpack/jitpack.io#4539]
Please provide:

- Link to build log from https://jitpack.io

Could not resolve all files for configuration ':contracts:compileClasspath'.
   > Could not resolve com.r3.corda.lib.accounts:accounts-contracts:1.0.
     Required by:
         project :contracts
      > Could not resolve com.r3.corda.lib.accounts:accounts-contracts:1.0.
         > Could not get resource 'https://jitpack.io/com/r3/corda/lib/accounts/accounts-contracts/1.0/accounts-contracts-1.0.pom'.
            > Could not GET 'https://jitpack.io/com/r3/corda/lib/accounts/accounts-contracts/1.0/accounts-contracts-1.0.pom'.
               > Read timed out
               
               

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?

In local VM, exactly same error with a project without any cached dependencies

- What error are you seeing?

Website :https://jitpack.io/  502 Bad Gateway 
From Giltab CI, graddle build => Read timed out

Thank you!

**Comment by sigmanil** [comment]
Having similar problems with papsign:Ktor-OpenAPI-Generator both from local machine and build server (github actions).

**Comment by advissor** [comment]
Their website is down, package registry is down
Which is weird...

**Comment by alex-a-pereira** [comment]
thanks for posting, same issue here for React Native in build pipeline run on MS AppCenter
```
 Required by:
         project :app > project :react-native-inappbrowser-reborn
      > Failed to list versions for org.greenrobot:eventbus.
         > Unable to load Maven meta-data from https://www.jitpack.io/org/greenrobot/eventbus/maven-metadata.xml.
            > Could not get resource 'https://www.jitpack.io/org/greenrobot/eventbus/maven-metadata.xml'.
               > Could not GET 'https://www.jitpack.io/org/greenrobot/eventbus/maven-metadata.xml'. Received status code 502 from server: Bad Gateway
```

**Comment by ubuntudroid** [comment]
At least the Webpage is up again. But repo is still down.

**Comment by hbb20** [comment]
Keep an eye on service status page: https://status.jitpack.io/

**Comment by buremba** [comment]
The status says the queue is down but it looks like the downloads are down too.

**Comment by valeriyo** [comment]
https://jitpack.io/ is dead

**Comment by cellis** [comment]
Any ideas of what to do?

**Comment by brnogz** [comment]
Is there any public mirror of jitpack ? Otherwise I guess we have to wait.

**Comment by abd0ibrahim** [comment]
yup totally down 
Cannot sync dependencies, any other alternatives ? any one ?
happening with android studio "com.github.plnice:canidropjetifier:0.5"

**Comment by lramosduarte** [comment]
same here:
```
Downloading from jitpack.io: https://jitpack.io/software/amazon/eventstream/eventstream/1.0.1/eventstream-1.0.1.jar
Downloading from jitpack.io: https://jitpack.io/software/amazon/awssdk/http-client-spi/2.16.32/http-client-spi-2.16.32.jar
Downloading from jitpack.io: https://jitpack.io/software/amazon/awssdk/regions/2.16.32/regions-2.16.32.jar
Downloading from jitpack.io: https://jitpack.io/software/amazon/awssdk/annotations/2.16.32/annotations-2.16.32.jar
ERROR: Job failed: execution took longer than 1h0m0s seconds
```

https://status.jitpack.io/776679744/calendar

**Comment by btuck044** [comment]
same here

**Comment by L3au** [comment]
has been down for hours, and didn't find a backup mirror for this service...

**Comment by HadiModarres** [comment]
armaggedon is upon us

**Comment by alejandrorangel** [comment]
has anyone known if there has been any type of communication from Jitpack? I haven't seen anything yet

**Comment by hoorsa** [comment]
same here

```
   > Could not resolve com.intellij:annotations:+.
      > Failed to list versions for com.intellij:annotations.
         > Unable to load Maven meta-data from https://jitpack.io/com/intellij/annotations/maven-metadata.xml.
            > Could not get resource 'https://jitpack.io/com/intellij/annotations/maven-metadata.xml'.
               > Could not GET 'https://jitpack.io/com/intellij/annotations/maven-metadata.xml'.
                  > Read timed out
```

**Comment by dskoushik** [comment]
Facing same issue - Any updates from Jitpack?
 Could not get resource 'https://www.jitpack.io/com/github/bumptech/glide/compiler/4.9.0/compiler-4.9.0.pom'.
            > Could not GET 'https://www.jitpack.io/com/github/bumptech/glide/compiler/4.9.0/compiler-4.9.0.pom'.
               > Read timed out

**Comment by nekkan** [comment]
same here

**Comment by Yulia-Epshteyn** [comment]
same here

**Comment by mickstar** [comment]
Decided to build my dependencies manually and just use .jar libraries

**Comment by vinnyA3** [comment]
Jitpack has been very slow to respond today; however, they just tweeted that things should be operational now: https://twitter.com/jitpack/status/1389766485057363968

Let's see 🤷🏽

**Comment by hannesa2** [comment]
It works again

**Comment by advissor** [comment]
Fixed
