### ISSUE TITLE
TimelinePostContainer/2.0.2 build

### ISSUE THREAD

**Issue by alirezaaa** [jitpack/jitpack.io#454]
Log https://jitpack.io/com/github/alirezaaa/TimelinePostContainer/2.0.2/build.log

**Comment by jitpack-io** [comment]
Hi

Looks like the gradle wrapper isn't fully committed. From the log:
`WARNING: gradle/wrapper/gradle-wrapper.jar does not exist! Needs to be committed.`

https://github.com/alirezaaa/TimelinePostContainer/tree/master/gradle/wrapper

**Comment by alirezaaa** [comment]
Thanks man. You're right. That's a problem with ordering of `.gitignore` file rules which has been reported already.
