### ISSUE TITLE
Android Gradle plugin requires Java 11 to run. You are currently using Java 1.8

### ISSUE THREAD

**Issue by sudopk** [jitpack/jitpack.io#4553]
Please provide:

- Link to build log from https://jitpack.io
  https://jitpack.io/com/github/sudopk/KAndroid/1.1.1/build.log

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?
  Yes

- What error are you seeing?
  Jitpack fails with error: Android Gradle plugin requires Java 11 to run. You are currently using Java 1.8. See the build log above for more details

Thank you!

**Comment by sudopk** [comment]
I was using latest Android gralde plugin: 7.0.0-alpha15

Downgrading it to version 4.2.0 works (this version uses jdk 8)

**Comment by hannesa2** [comment]
But this is no solution, Jitpack should support Gradle 7

**Comment by kylecorry31** [comment]
I found that adding the following file to the root of my project resolves it: https://github.com/kylecorry31/Trail-Sense-Core/blob/main/jitpack.yml
