### ISSUE TITLE
StickyListHeaders 2.7.1 Build Failing

### ISSUE THREAD

**Issue by zaffudo** [jitpack/jitpack.io#4560]
Please provide:

- Link to build log from https://jitpack.io
https://jitpack.io/com/github/mtotschnig/StickyListHeaders/2.7.1/build.log

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?
No

- What error are you seeing?
Build fails because 2.7.1 is missing on JitPack

Thank you!

**Comment by mtotschnig** [comment]
Is there a reason why you can't use 2.8.0 ?
