### ISSUE TITLE
Subscription issues and 403

### ISSUE THREAD

**Issue by argyle-deployment-account** [jitpack/jitpack.io#4574]
Hi. A few weeks back we migrated from JCenter, got a JitPack subscription for private repos and everything was working just fine until a few days back when we could no longer download the package due to this error:

```
Subscription is not active right now
Requested subscription: github.com/argyle-systems. 
Your subscriptions are listed in https://jitpack.io/w/user
Please contact Support or repository admins if you need assistance.
```

We inspected https://jitpack.io/w/user and apparently there were two entries - this account (active subscription) and GitHub organisation that the account belongs to (inactive subscription). Bought another subscription for the organisation and package became available again but the question is why this happened and whether we can merge two current subscriptions into one.

**Comment by starface1133** [comment]
> Hi. A few weeks back we migrated from JCenter, got a JitPack subscription for private repos and everything was working just fine until a few days back when we could no longer download the package due to this error:
> 
> ```
> Subscription is not active right now
> Requested subscription: github.com/argyle-systems. 
> Your subscriptions are listed in https://jitpack.io/w/user
> Please contact Support or repository admins if you need assistance.
> ```
> 
> We inspected https://jitpack.io/w/user and apparently there were two entries - this account (active subscription) and GitHub organisation that the account belongs to (inactive subscription). Bought another subscription for the organisation and package became available again but the question is why this happened and whether we can merge two current subscriptions into one.
