### ISSUE TITLE
Subscription not active / Received status code 403 from server: Forbidden

### ISSUE THREAD

**Issue by amit-semusi** [jitpack/jitpack.io#4578]
Hi Jitpack team: 

- Link to build log from https://jitpack.io
below is log file:
https://jitpack.io/com/gitlab/grp_appice/src_android_appice-sdk/2.5.00/build.log

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?
no

- What error are you seeing?
Could not HEAD 'https://jitpack.io/com/gitlab/grp_appice/src_android_appice-sdk/sdk/2.5.00/sdk-2.5.00.pom'. Received status code 403 from server: Forbidden
Disable Gradle 'offline mode' and sync project

Hi, i have already bought the subscription but still i am getting 403 from server on my private repo, and also i am getting this error "Subscription not active" on checking repo logs on jitpack
 
Thank you!
<img width="1440" alt="Screenshot 2021-06-03 at 5 38 00 PM" src="https://user-images.githubusercontent.com/60190609/120647797-9b080800-c498-11eb-80c1-54202d018bb5.png">

**Comment by jitpack-io** [comment]
Hi,

Replied to your support ticket regarding this account. Should be working now
