### ISSUE TITLE
Library aar or files are not found in client app after adding library from Jitpack

### ISSUE THREAD

**Issue by mohsinajavaidslashnext** [jitpack/jitpack.io#4579]
After publishing library from jitpack when i add the library in other app it  builds successfully but i could not find my library arr or classes in the app. My library is build on multi module.

<img width="1407" alt="Screenshot 2021-06-03 at 5 44 18 PM" src="https://user-images.githubusercontent.com/84960350/120646994-8aa15e80-c493-11eb-8a1a-b8fd05f0044d.png">

**Comment by mohitdholakia** [comment]
Same issue. Do you get any fix for this? @mohsinajavaidslashnext

**Comment by slashnextSDK** [comment]
Yes. I were using password protected zip file in my SDK so it was giving build warning as android doesn't support password protected zips. You need to check all errors or warnings while building your library it will give you a clue most probably
