### ISSUE TITLE
ERROR: Time-out getting container status

### ISSUE THREAD

**Issue by marcin-szelag** [jitpack/jitpack.io#4583]
I would like to report a build error for ruleLearn project from github.

Link to build log from https://jitpack.io  ->  https://jitpack.io/com/github/ruleLearn/rulelearn/0.21.2/build.log

The project builds on my machine with **the same** commands, i.e. with "gradlew all", using Java 8 and also using Java 11. 

At the end of log I can see:

BUILD SUCCESSFUL in 8s
9 actionable tasks: 8 executed, 1 up-to-date
Build tool exit code: 0
Looking for artifacts...
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2
Looking for pom.xml in build directory and ~/.m2
Found artifact: org.rulelearn:ruleLearn:0.21.2
ERROR: Time-out getting container status
Error building

Please let me fix this.

Kind regards,
Marcin Szelag

**Comment by marcin-szelag** [comment]
I retried build several times and finally it worked. Strange though...

**Comment by Alkisum** [comment]
I have exactly the same error as described here. It happened to me several times on different days.

This error occurs only around 3 AM UTC though.
