### ISSUE TITLE
BUILD Failure | HIGH PRIORITY

### ISSUE THREAD

**Issue by Regilan** [jitpack/jitpack.io#4586]
Please provide:

https://jitpack.io/#skillscy/QCCommons/1.21.0- Link to build log from https://jitpack.io

I am getting jar when I run `gradlew build` on my local machine

Gradle dependencies in the project are not downloading on the Jitpack io machine

Thank you!

**Comment by ueen** [comment]
https://techcrunch.com/2021/06/08/numerous-popular-websites-are-facing-an-outage/amp/
