### ISSUE TITLE
How to build an Android project with CMake?

### ISSUE THREAD

**Issue by mohsinajavaidslashnext** [jitpack/jitpack.io#4589]
I have an android studio project the makes use of

externalNativeBuild 
        cmake {
            path 'src/main/jni/CMakeLists.txt'
        }

The project build correctly and when someone else pulls the code it also work correctly.

The issue I am having is. When i try to using Jitpack.IO to pull the release from git hub i get the following issue.
![image](https://user-images.githubusercontent.com/84960350/121543439-59d8a080-ca22-11eb-8a1c-b7ed98aa86a7.png)

If i remove the
![image](https://user-images.githubusercontent.com/84960350/121543599-7b398c80-ca22-11eb-8353-a080b5e514e7.png)

Jitpack works correctly. But in that case i am not able to get my Native code from Jitpack and then my code crashes.

Here is log file  to get an idea of issue in detail:
https://jitpack.io/com/github/mohsinajavaidslashnext/testingLib/12.1/build.log

**Comment by tapow** [comment]
I am also facing the issue. Is there any solutions?

**Comment by testingsdk** [comment]
still didn't get any fix @tapow do you find anything?
