### ISSUE TITLE
Subscription is not active right now 

### ISSUE THREAD

**Issue by nickjtch** [jitpack/jitpack.io#4595]
**Describe the bug**
Getting subscription is not active right now when trying to access build logs of a public jitpack repo (created from a private github repository)

**Expected behavior**
We weren't facing any problems with this until today. We tried subscribing to Jitpack (another person within the organization purchased it) and it still does not work.

**Screenshots**
![image](https://user-images.githubusercontent.com/9370214/121920811-11cabe00-cd41-11eb-8fbc-747c0fbb5222.png)

**Comment by DeviousM** [comment]
@nickjtch - did it end up working for you? I have a similar issue and I also paid for one year up-front.

**Comment by nickjtch** [comment]
@DeviousM emailed support and got fixed directly.

**Comment by DeviousM** [comment]
Did you use `jitpack@jitpack.io` email?

**Comment by nickjtch** [comment]
Yes. Also, sent a message via live chat (available on website)

**Comment by DeviousM** [comment]
@nickjtch, ok, cool, thanks! I did the same but to no avail so far.

**Comment by DeviousM** [comment]
Just to update you - they never replied, even though I messaged them at least a couple of times.

**Comment by umarpazir11** [comment]
Yes same for me no response from them I am getting same issue.

**Comment by DeviousM** [comment]
@umarpazir11 - I'd just assume that your money was lost. They still did not reply to me after all this time 😉

**Comment by DeviousM** [comment]
This shouldn't be closed as it was not resolved.
