### ISSUE TITLE
Android Gradle plugin requires Java 11 to run. You are currently using Java 1.8.

### ISSUE THREAD

**Issue by LimeVista** [jitpack/jitpack.io#4597]
Environment:
Android Studio Arctic Fox
Gradle Plugin 7.0

Error:
Android Gradle plugin requires Java 11 to run. You are currently using Java 1.8.

**Comment by xht418** [comment]
I got the same error today.

**Comment by DJSeokHo** [comment]
same error..any solution??

**Comment by wakaztahir** [comment]
https://stackoverflow.com/a/68756946/3343503

**Comment by MarcoCiaramella** [comment]
from https://jitpack.io/docs/BUILDING/

Java version
JitPack will compile projects using OpenJDK Java 8. See the example projects on how to set a different target version in your build file.

Maven projects that specify a target version in their pom will be built with that target version.

If your project uses Travis or Circle CI then JitPack will read the lowest jdk version from yml file and use that to build.

Alternatively create a jitpack.yml file in the root of your repository and specify a jdk version:

jdk:
  - openjdk9
If your project requires a specific Java version then you can use SDKMAN in jitpack.yml:

before_install:
   - sdk install java 11.0.10-open
   - sdk use java 11.0.10-open

**Comment by Canato** [comment]
Duplicate of #4474 
There is a solution on it, please use the same thread.
