### ISSUE TITLE
First fetch can hang for numerous minutes

### ISSUE THREAD

**Issue by asarazan** [jitpack/jitpack.io#46]
Don't know if this is just a backed up build queue or something, but the first request for a repo can take anywhere from 5-10 minutes. Anything that can be done about this?

```
15:04:53.023 [DEBUG] [org.apache.http.impl.conn.DefaultClientConnection] Sending request: GET /com/github/Levelmoney/ObserveFragment/0.5/ObserveFragment-0.5.pom HTTP/1.1
15:04:53.024 [DEBUG] [org.apache.http.headers] >> GET /com/github/Levelmoney/ObserveFragment/0.5/ObserveFragment-0.5.pom HTTP/1.1
15:04:53.024 [DEBUG] [org.apache.http.headers] >> Accept-Encoding: gzip,deflate
15:04:53.025 [DEBUG] [org.apache.http.headers] >> Host: jcenter.bintray.com
15:04:53.025 [DEBUG] [org.apache.http.headers] >> Connection: Keep-Alive
15:04:53.025 [DEBUG] [org.apache.http.headers] >> User-Agent: Gradle/2.2.1 (Mac OS X;10.10.2;x86_64) (Oracle Corporation;1.8.0_25;25.25-b02)
```

**Comment by jitpack-io** [comment]
Hi @asarazan 

The android support library being used in the ObserveFragment project was newer than the one we had on our build servers. After updating the library the build is fine:
https://jitpack.io/#Levelmoney/ObserveFragment/0.5

Sorry about the inconvenience.

Are there other projects where it seems slow? Sometimes build jobs stay longer in the queue however this doesn't happen very often. If you experience it please let us know

**Comment by asarazan** [comment]
In my experience it's happened every time I've tried to use it, so I've had to switch back to maven every time. To be fair they've all been my projects and probably had the same support dependency.

The most frustrating part was that there just wasn't any feedback or visibility into why it was failing. Some kind of warning up-front or an FAQ page would go a long way here.

**Comment by jitpack-io** [comment]
You're totally right. The feedback mechanism needs improvement. 

The way we provide feedback at the moment is by keeping the build log:
https://jitpack.io/com/github/Levelmoney/ObserveFragment/0.5/build.log

And you would see a link to the build log on the main website if the build failed:
https://jitpack.io/#Levelmoney/ObserveFragment/0.5

It's mentioned in the Status section of the main website and here on GitHub https://github.com/jitpack/jitpack.io/blob/master/BUILDING.md#troubleshooting . 

We would like to make it more prominent but not entirely sure how. All suggestions welcome:)

For example, this project has one version with build error: https://jitpack.io/#neopixl/PixlUI

**Comment by asarazan** [comment]
iiiiinteresting. I was definitely looking at the build list and never saw the error message, I really think it got into some loop without technically failing.

One useful signal might be "has this release ever built". I assume it's a lazy system, so if nobody has ever pulled a certain version, the "Get It" button could have a different color or slightly different text to indicate a possible wait while things are fetched.

**Comment by jitpack-io** [comment]
That's an excellent idea. Opened issue #47 and planning to implement it

**Comment by asarazan** [comment]
Glad to hear it.

FYI I'm getting a pretty long hang trying to pull in `compile 'com.github.Levelmoney:Velodrome:0.5'`as well.

**Comment by jitpack-io** [comment]
Up and running
![version_colors](https://cloud.githubusercontent.com/assets/11161622/7430504/205863a0-f00c-11e4-8e68-8c1b1a8bb076.png)

Closing this for now.

**Comment by shkschneider** [comment]
I still don't get why the first pull takes so much time.

The build is complete: https://jitpack.io/com/github/shkschneider/android_Skeleton/4.1.1/build.log
But my IDE still hangs on resolving that dependency.

**Comment by jitpack-io** [comment]
@shkschneider Yes, normally it shouldn't take long but there was a glitch at the build servers at the time of your build. Sorry about that. It's an issue that we are aware of and are working on fixing. 
Rebuilt your project just in case. Also planning to add a way for you to rebuild the project.

**Comment by Mprogrammer2020** [comment]
@jitpack-io Build is taking too long and it stucks on the "queued" status. I have been trying since 3 hours.

Any Idea?
![Screenshot from 2022-07-01 15-09-11](https://user-images.githubusercontent.com/8416856/176869565-bc07a919-306a-48f6-b3fc-2794beb66361.png)
