### ISSUE TITLE
Add Native Support for Gradle 7.x and JDK 11

### ISSUE THREAD

**Issue by wiryadev** [jitpack/jitpack.io#4615]
**Is your feature request related to a problem? Please describe.**
I'm building something that needs Gradle 7.x and JDK 11, and it frustates me because it always failing to build and require JDK 1.8

**Describe the solution you'd like**
I want jitpack to be able to build app or library that built locally using Gradle 7.x and JDK 11.

**Additional context**
![image](https://user-images.githubusercontent.com/26060382/123967260-58c2df80-d9e0-11eb-90a7-4ae215540455.png)

**Comment by Bqckword** [comment]
Hello, I'm experiencing the same problems with Gradle 7+. Have you had any luck finding a solution? They haven't responded to my email or my GitHub issue.
