### ISSUE TITLE
jitpack doesn't want to compile using java 16 even when told yo

### ISSUE THREAD

**Issue by TheSilentPro** [jitpack/jitpack.io#4627]
Please provide:

- Link to build log from https://jitpack.io
https://jitpack.io/com/github/TheSilentPro/HeadDB/2.4.0/build.log

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?
yes

- What error are you seeing?
Fatal error compiling: invalid target release: 16

I have followed the guide:
https://jitpack.io/docs/BUILDING/#java-version
but it still errors when building

**Comment by inpercima** [comment]
Same issue here: https://jitpack.io/com/github/inpercima/rest-api/v1.0.2/build.log. Java 16 seems not to be accepted.

> Maven projects that specify a target version in their pom will be built with that target version.
I did java 16

> If your project requires a specific Java version then you can use SDKMAN in jitpack.yml
```
before_install:
  - sdk install java 16.0.1.hs-adpt
  - sdk use java 16.0.1.hs-adpt
```

doesn't help.

**Comment by inpercima** [comment]
> Same issue here: https://jitpack.io/com/github/inpercima/rest-api/v1.0.2/build.log. Java 16 seems not to be accepted.
> 
> > Maven projects that specify a target version in their pom will be built with that target version.
> 
> I did java 16
> 
> > If your project requires a specific Java version then you can use SDKMAN in jitpack.yml
> 
> ```
> before_install:
>   - sdk install java 16.0.1.hs-adpt
>   - sdk use java 16.0.1.hs-adpt
> ```
> 
> doesn't help.

Now I use java 11 as default. Changed java version from 16 to 11 only in the files and it works.

**Comment by cyberpwnn** [comment]
No matter what I do it continues to use Java 8
