### ISSUE TITLE
Problem with switching admin role between two accounts (support does not respond)

### ISSUE THREAD

**Issue by Michael-Rang** [jitpack/jitpack.io#4628]
I already tried to contact Jitpack via support chat and via email, but did not get a reply yet.

I have a problem with switching subscriptions for specific Github-Accounts.

The situation is the following:
- we have two accounts: Github-Account A & Github-Account B
- both A & B have access to Github-Account C
- I created a subscription for repositories of Account C with Account A
- With that Account A got the Admin role for the Account C repositories (displayed cog-wheel to adjust public/private access of artifacts)
- I cancelled the subscription for Account A (Michael-Rang) and subscribed for repositories of Account C with Account B 
- the subscription for Account C was successfully added but it seems like Account C is not regarded as the admin of Account C  -> no cog-wheel is displayed for adjusting public/private access for artifacts

**Comment by straic-android** [comment]
It's working now, thx :)

**Comment by Michael-Rang** [comment]
It's working now, thx!
