### ISSUE TITLE
MEiDIK/Cipher.so - dev-SNAPSHOT missing

### ISSUE THREAD

**Issue by Gazer** [jitpack/jitpack.io#4629]
- https://jitpack.io/com/github/MEiDIK/Cipher.so/dev-v0.0.4-g8581777-15-Cipher.so-dev-v0.0.4-g8581777-15/build.log

**Comment by WadeXHong** [comment]
I use this library in my project and run into the same problem as well. It looks the package's build process on jitpack is somehow trigger and failed so the old one has been wipe. However, the request to jitpack on Bitbucket Pipeline still success sometimes, which might results from cache.
My workaround is to get the cache jar file from my local machine ```~/.gradle/caches/modules-2/files-2.1/``` and put it into the project, then change the dependency in gradle to file import.

**Comment by rubysuki** [comment]
> I use this library in my project and run into the same problem as well. It looks the package's build process on jitpack is somehow trigger and failed so the old one has been wipe. However, the request to jitpack on Bitbucket Pipeline still success sometimes, which might results from cache.
> My workaround is to get the cached jar file from my local machine `~/.gradle/caches/modules-2/files-2.1/` and put it into the project, then change the dependency in gradle to file import.

Hi, can you tell me how you change the dependency in gradle to file import. 
Thankyou so much.
