### ISSUE TITLE
https://jitpack.io can not be accessible  

### ISSUE THREAD

**Issue by adarzulfu** [jitpack/jitpack.io#4632]
We can not access https://jitpack.io, blocker issue for us, builds fail
could not determine artifacts for kizitonwose1.0.3
<img width="1075" alt="Screen Shot 2021-07-09 at 12 15 47" src="https://user-images.githubusercontent.com/22280504/125054967-6c8cd680-e0af-11eb-8a29-2831566694cf.png">

**Comment by wannabelikeyoda** [comment]
same issue with downloading https://github.com/Baseflow/PhotoView library

**Comment by Papashkin** [comment]
The same for me:

```
> Could not resolve com.github.franmontiel:PersistentCookieJar:v1.0.1.
     Required by:
         project :indigo
      > Skipped due to earlier error
   > Could not resolve com.github.PhilJay:MPAndroidChart:v3.0.3.
     Required by:
         project :indigo
      > Skipped due to earlier error
   > Could not resolve com.github.kenglxn.QRGen:android:2.6.0.
     Required by:
         project :indigo
      > Skipped due to earlier error
 ```
 
 And site is infinite loading :/

**Comment by ThanhNguyen140797** [comment]
same issue
Could not determine the dependencies of task ':app:mergeDebugAssets'.
> Could not resolve all dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not determine artifacts for com.github.yalantis:ucrop:2.2.2-native
      > Could not get resource 'https://jitpack.io/com/github/yalantis/ucrop/2.2.2-native/ucrop-2.2.2-native.aar'.
         > Could not HEAD 'https://jitpack.io/com/github/yalantis/ucrop/2.2.2-native/ucrop-2.2.2-native.aar'.
            > Read timed out

**Comment by ThanhNguyen140797** [comment]
same issue 
```
Could not determine the dependencies of task ':app:mergeDebugAssets'.
> Could not resolve all dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not determine artifacts for com.github.yalantis:ucrop:2.2.2-native
      > Could not get resource 'https://jitpack.io/com/github/yalantis/ucrop/2.2.2-native/ucrop-2.2.2-native.aar'.
         > Could not HEAD 'https://jitpack.io/com/github/yalantis/ucrop/2.2.2-native/ucrop-2.2.2-native.aar'.
            > Read timed out
```

**Comment by Palshyn** [comment]
Same here

**Comment by bashellwang** [comment]
same problem

**Comment by Papashkin** [comment]
seems fixed. 👍

**Comment by adarzulfu** [comment]
yes it is accessible.
