### ISSUE TITLE
Jitpack throwing ERROR: No build artifacts found

### ISSUE THREAD

**Issue by Picono435** [jitpack/jitpack.io#4634]
Info:

- https://jitpack.io/com/github/Picono435/PicoJobs/610ddfa29f/build.log

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ? Yes

- What error are you seeing? ERROR: No build artifacts found

**Comment by Picono435** [comment]
Fixed the issue.

**Comment by familyachil** [comment]
native-file-system-adapter/test.js at master · jimmywarting/native-file-system-adapter<a href="https://example.com">
<a `href="/relative/path/file">#diamondtitaniummicroprojectspartansystemguardiansdatasurfforceteam.mhtml#microyoutubehelpsurvivedidindexteamforce.mhtml#microyoutubehelpsurvivedidindexteamforce.mhtml#microsoftindexsurviveteam.mhtml#microsofhelptsurvivedidindexteam.mhtml#micromarshmallowhelpsurvivedidindexteam.mhtml#micromarlinhelpsurvivedidindexteam.mhtml#microbluelinehelpsurvivedidindexteam.mhtml`
