### ISSUE TITLE
ERROR: No build artifacts found

### ISSUE THREAD

**Issue by SevenYang9527** [jitpack/jitpack.io#4635]
Build starting...
Start: Sat Jul 10 06:44:04 UTC 2021 16b40fb4a812
Git:
1.0.7-0-gd464027
commit d464027714931a46e61320129b50044a046bd298
Author: Y8530199yxm 
Date:   Sat Jul 10 14:40:09 2021 +0800

    6

Found Android manifest
Android SDK version: 30. Build tools: 30.0.3
Installing Android platform 30
Installing Build-tools 30.0.3 
Going into directory: ./SdkSampleProject
Gradle build script
Found gradle version: 6.5.
Using gradle wrapper
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2
Downloading https://services.gradle.org/distributions/gradle-6.5-bin.zip
.
Unzipping /home/jitpack/.gradle/wrapper/dists/gradle-6.5-bin/6nifqtx7604sqp1q6g8wikw7p/gradle-6.5-bin.zip to /home/jitpack/.gradle/wrapper/dists/gradle-6.5-bin/6nifqtx7604sqp1q6g8wikw7p
Set executable permissions for: /home/jitpack/.gradle/wrapper/dists/gradle-6.5-bin/6nifqtx7604sqp1q6g8wikw7p/gradle-6.5/bin/gradle

------------------------------------------------------------
Gradle 6.5
------------------------------------------------------------

Build time:   2020-06-02 20:46:21 UTC
Revision:     a27f41e4ae5e8a41ab9b19f8dd6d86d7b384dad4

Kotlin:       1.3.72
Groovy:       2.5.11
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          1.8.0_252 (Private Build 25.252-b09)
OS:           Linux 4.14.63-xxxx-std-ipv6-64 amd64

0m2.932s
Getting tasks: ./gradlew tasks --all
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2
Tasks: 

WARNING:
Gradle 'install' task not found. Please add the 'maven' or 'android-maven' plugin.
See the documentation and examples: https://jitpack.io/docs/

Looking for android-library
Looking for com.android.application
Adding maven plugin
Found android library build file in app
Running: ./gradlew clean -Pgroup=com.github.Y8530199yxm -Pversion=1.0.7 install
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2

> Configure project :
Gradle version Gradle 6.5

> Task :clean UP-TO-DATE
> Task :app:clean UP-TO-DATE
> Task :app:install

BUILD SUCCESSFUL in 1s
3 actionable tasks: 1 executed, 2 up-to-date
Build tool exit code: 0
Looking for artifacts...
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2
Looking for pom.xml in build directory and ~/.m2
2021-07-10T06:44:40.553306188Z
Exit code: 0

ERROR: No build artifacts found

**Comment by hukacode** [comment]
Could you upgrade Gradle to version 7 then follow this?
https://github.com/jitpack/jitpack.io/issues/4645#issuecomment-886151067
