### ISSUE TITLE
JitPack must stop using deprecated ndk.dir in local.properties and support android.ndkVersion in build.gradle instead

### ISSUE THREAD

**Issue by Robyer** [jitpack/jitpack.io#4638]
In my project I need to use specific version of NDK, because of some compatibility issues. I am using `ndkVersion` property, which is a recommended way as stated by Google [here](https://developer.android.com/studio/projects/configure-agp-ndk).

It seems JitPack doesn't respect this property and forces specific NDK version to be used during build. See the build log:
https://jitpack.io/com/github/adaptech-cz/tesseract4android/3.0.0/build.log

See the error:
```
* What went wrong:
A problem occurred configuring project ':tesseract4android'.
> com.android.builder.errors.EvalIssueException: NDK from ndk.dir at /opt/android-sdk-linux/ndk-bundle had version [21.1.6352462] which disagrees with android.ndkVersion [20.1.5948944]
```

The build works correctly on my machine.

I see this may be related to issue #1776 , but that is almost 4 years old. Certainly there must be a way how to specify what NDK version should be used when building with JitPack.

**Comment by Robyer** [comment]
JitPack forcing own local.properties file with deprecated ndk.dir property is breaking builds that depends on specific NDK version (or builds that just uses current recommended way of doing things).

My [build log](https://jitpack.io/cz/adaptech/tesseract4android/3.0.0/build.log) is full of:

> WARNING:: NDK was located by using ndk.dir property. This method is deprecated and will be removed in a future release. Please delete ndk.dir from local.properties and set android.ndkVersion to [21.1.6352462] in all native modules in the project. https://developer.android.com/r/studio-ui/ndk-dir

I can install custom NDK versions before build starts by creating file `jitpack.yml` with content:
```
before_install:
  - yes | sdkmanager --uninstall "ndk-bundle" | sdkmanager --install "ndk;22.1.7171670" "ndk;20.1.5948944"
```

But this doesn't help, since **JitPack puts the `ndk.dir` property into `local.properties` file which take priority over `android.ndkVersion` property defined in `build.gradle`.**

@jitpack-io This really needs to be fixed. Can you tell me your plans regarding this? Thanks.

**Comment by G10h4ck** [comment]
This bug breaks libretroshare AAR jitpack.io build too

```
FAILURE: Build failed with an exception.

* Where:
Build file '/home/jitpack/build/build.gradle' line: 168

* What went wrong:
A problem occurred evaluating root project 'libretroshare'.
> NDK is not installed
```

As you can see here https://jitpack.io/com/gitlab/g10h4ck/libretroshare/d5c3c938ed/build.log

Same repository, same commit

`./gradlew publishToMavenLocal`

works perfectly on my laptop or on a fresh docker container

**Comment by Robyer** [comment]
@jitpack-io Any update on this?

**Comment by Robyer** [comment]
@jitpack-io This is still not fixed as far as I know.

**Comment by Robyer** [comment]
I am still waiting for this to be fixed. Or at least any statement from the @jitpack-io regarding this.

**Comment by jitpack-io** [comment]
Hi @Robyer 

Thank you for your patience! We made a change to no longer put ndk.dir in local.properties. 
Are you experiencing the same issue?

**Comment by Robyer** [comment]
@jitpack-io I can confirm this is working correctly now. Thank you!
