### ISSUE TITLE
stagemonitor/0.20.0 build

### ISSUE THREAD

**Issue by felixbarny** [jitpack/jitpack.io#464]
Log https://jitpack.io/com/github/stagemonitor/stagemonitor/0.20.0/build.log

Jitpack executes `./gradlew clean -Pgroup=com.github.stagemonitor -Pversion=0.20.0 -xtest install` which fails because of the shade plugin. The stagemonitor build needs to do a `compileJava` before install:

```
./gradlew clean compileJava -Pgroup=com.github.stagemonitor -Pversion=0.20.0 -xtest install
```

Is there a way to customize the build? Maybe via `.jitpack.yml`?

**Comment by jitpack-io** [comment]
Hi 

There are plans to have a custom install command #354 but we're not there yet.
In your case you could make compileJava run before install with:
```
task install
install.dependsOn subprojects.compileJava
```
Would that work for you?

Seems to build fine https://jitpack.io/com/github/jitpack-io/stagemonitor/-0.20.0-ga6c31e1-35/build.log
after this commit https://github.com/jitpack-io/stagemonitor/commit/a6c31e1d13e16c1f61f6786aea7bdbddd1b27347

**Comment by felixbarny** [comment]
thx, its working. you are awesome! :)
