### ISSUE TITLE
Multiple JDK versions in a multi-modular Maven project doesn't work for versions above Java 8

### ISSUE THREAD

**Issue by Revxrsal** [jitpack/jitpack.io#4640]
**Describe the bug**
When attempting to build a multi-modular project ([the project I'm building](https://github.com/ReflxctionDev/tuna-bytes)), where each module specifies a target Java version (Java 8, 9 and 11), the [build fails](https://jitpack.io/com/github/ReflxctionDev/tuna-bytes/5d0e62c385/build.log) with the following error:
```invalid target release: 9```

Which is clearly saying that JDK 9 is not supported (and thus the compilation of the Java 11 one was skipped). I've checked https://jitpack.io/docs/BUILDING/#java-version as well as other issues regarding support for Java 9+, and saw that the solution would be with defining SDKMAN before_install commands in `jitpack.yml`, however the build.log mentions that the commands were invalid.
```Running before_install command:
sdk install java 9.0.4-oracle;sdk use java 9.0.4-oracle;sdk install java 11.0.10-open;sdk use java 11.0.10-open
/script/buildit.sh: line 41: sdk: command not found
/script/buildit.sh: line 41: sdk: command not found
/script/buildit.sh: line 41: sdk: command not found
/script/buildit.sh: line 41: sdk: command not found
```
([full build.log](https://jitpack.io/com/github/ReflxctionDev/tuna-bytes/5d0e62c385/build.log))

**Expected behavior**
Build appropriately with different targeted Java versions, or allow SDKMAN! commands to install the correct Java version

I do believe I may have done incorrect configuration in the [jitpack.yml](https://github.com/ReflxctionDev/tuna-bytes/blob/master/jitpack.yml), especially with the fact that none of the documentation state anything about targeting multiple versions.
Thank you for your time, ❤️ jitpack.io

**Comment by Auxilor** [comment]
Same error with Java 16
