### ISSUE TITLE
No build artifacts found

### ISSUE THREAD

**Issue by azzztec** [jitpack/jitpack.io#4645]
Please provide:

- https://jitpack.io/com/github/azzztec/JitpackTest/v1.0.3/build.log

- dont have "install" command, but others complete successfully

- The error is: ERROR: No build artifacts found

Thank you!

**Comment by hukacode** [comment]
I answered your question here. Could you try it?
https://stackoverflow.com/a/68515859/6484502

**Comment by ice1000** [comment]
> I answered your question here. Could you try it?
> https://stackoverflow.com/a/68515859/6484502

I have all your configurations but I got the error too

**Comment by hukacode** [comment]
@ice1000 
Could you share your build config? Is it Gradle 7?

**Comment by ice1000** [comment]
> @ice1000
> Could you share your build config? Is it Gradle 7?

Yes, the project is https://github.com/aya-prover/aya-dev

**Comment by ice1000** [comment]
> @ice1000
> Could you share your build config? Is it Gradle 7?

#4646

**Comment by hukacode** [comment]
https://jitpack.io/com/github/aya-prover/aya-dev/main-SNAPSHOT/build.log
It is okay with your SNAPSHOT build

On e5c9d9b632, you missed maven-publish:
`Gradle 'install' task not found. Please add the 'maven' or 'android-maven' plugin.`

On v0.8, you used Java 16, I think you can override by use this file:
https://github.com/hukacode/huka-common/blob/main/jitpack.yml

**Comment by ice1000** [comment]
> https://jitpack.io/com/github/aya-prover/aya-dev/main-SNAPSHOT/build.log
> It is okay with your SNAPSHOT build
> 
> On e5c9d9b632, you missed `maven-publish`:
> `Gradle 'install' task not found. Please add the 'maven' or 'android-maven' plugin.`

I have maven-publish plugin applied, does that imply maven?

> On v0.8, you used Java 16, I think you can override by use this file:
> https://github.com/hukacode/huka-common/blob/main/jitpack.yml

Java 16 is not available. I used a third party script to download Java 16 for the build, which didn't work. I hope there's a way to rebuild to see if the network issue is temporary

**Comment by ice1000** [comment]
#4355 discussed the Java 15/16 issue.

**Comment by hukacode** [comment]
> I have maven-publish plugin applied, does that imply maven?
Yes. I just mean that on that build version, you missed `maven-publish`. On the main branch, I saw you add `maven-publish`, then it was published.
You can try it by use `main-SNAPSHOT` version or release a new version.

**Comment by ice1000** [comment]
@hukacode I rebuilt 0.8 and it worked now (yes, the problem is temporary). Thanks for your help!

**Comment by hukacode** [comment]
If you fixed it by follow these steps, please consider upvote on stackoverflow link. :)

**Comment by ice1000** [comment]
> If you fixed it by follow these steps, please consider upvote on stackoverflow link. :)

I fixed it by rebuilding the project on jitpack.io

**Comment by azzztec** [comment]
SOLVED! https://stackoverflow.com/a/68515859/6484502

Thanks to @hukacode

**Comment by hukacode** [comment]
Glad to hear that 🎉
