### ISSUE TITLE
ERROR: No build artifacts found

### ISSUE THREAD

**Issue by zhongjhATC** [jitpack/jitpack.io#4651]
https://www.jitpack.io/com/github/zhongjhATC/AlbumCameraRecorder/1.1.10X/build.log

That was fine before

**Comment by zhongjhATC** [comment]
Using.\gradlew installRelease is fine
BUILD SUCCESSFUL in 1m 13s

**Comment by azzztec** [comment]
try https://github.com/jitpack/jitpack.io/issues/4645
