### ISSUE TITLE
Failed Build in Android Gradle Plugin 7.0.0

### ISSUE THREAD

**Issue by amirisback** [jitpack/jitpack.io#4654]
An exception occurred applying plugin request [id: 'com.android.application']
> Failed to apply plugin 'com.android.internal.application'.
   > Android Gradle plugin requires Java 11 to run. You are currently using Java 1.8.
     You can try some of the following options:
       - changing the IDE settings.
       - changing the JAVA_HOME environment variable.
       - changing `org.gradle.java.home` in `gradle.properties`.

**Comment by kylecorry31** [comment]
I found that adding the following file to the root of my project resolves it: https://github.com/kylecorry31/Trail-Sense-Core/blob/main/jitpack.yml

**Comment by amirisback** [comment]
thanks for the solution
