### ISSUE TITLE
Android Gradle plugin requires Java 11 to run. You are currently using Java 1.8.

### ISSUE THREAD

**Issue by necatisozer** [jitpack/jitpack.io#4656]
Please provide:

- Link to build log from https://jitpack.io
- https://jitpack.io/com/github/waterboys/CurrencyEdittext/1.1.0/build.log

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?
- yes

- What error are you seeing?
- Java 11 should be used for build instead of 8

Thank you!

**Comment by wakaztahir** [comment]
https://github.com/timeline-notes/portamento/blob/main/jitpack.yml
Download this file to your project root and try again !

**Comment by wakaztahir** [comment]
https://stackoverflow.com/a/68756946/3343503

**Comment by Canato** [comment]
Duplicate of #4474 
There is a solution on it, please use the same thread.
