### ISSUE TITLE
Support is not responding

### ISSUE THREAD

**Issue by guness** [jitpack/jitpack.io#4657]
We have paid multiple times by mistake, and have used the `Contact Us` form for a refund. No one cares about support tickets. 

Please reach out for details.

**Comment by guness** [comment]
any update on this one @jitpack-io  ?

**Comment by guness** [comment]
any update on this one?

**Comment by guness** [comment]
any update on this one @jitpack-io ?

**Comment by jitpack-io** [comment]
Hi

Happy to have a look but couldn't find the support ticket? Would it be ok if you re-submit the ticket, please? 

Many thanks

**Comment by guness** [comment]
> Hi
> 
> Happy to have a look but couldn't find the support ticket? Would it be ok if you re-submit the ticket, please?
> 
> Many thanks

I have just sent it again.

**Comment by jitpack-io** [comment]
Thanks, replied. We can continue there
