### ISSUE TITLE
support jdk 11

### ISSUE THREAD

**Issue by kouxinhong** [jitpack/jitpack.io#4661]
https://jitpack.io/com/github/kouxinhong/SystemBarsCompat/0.2/build.log

**Comment by smokelaboratory** [comment]
Same issue : https://jitpack.io/com/github/smokelaboratory/freedom/2.0.0/build.log

**Comment by AndroidDeveloperLB** [comment]
Same:

https://github.com/jitpack/jitpack.io/issues/4777#issuecomment-964863492
