### ISSUE TITLE
Update Java 8 to 11

### ISSUE THREAD

**Issue by HDNAdministrator** [jitpack/jitpack.io#4664]
Hi,

I'm getting a build [error](https://jitpack.io/org/bitbucket/homodigitalisnetwork/core/1.4.4/build.log).
I've tested locally without any issues.
Best regards,

Nuno Silveira

**Comment by kylecorry31** [comment]
I found that adding the following file to the root of my project resolves it: https://github.com/kylecorry31/Trail-Sense-Core/blob/main/jitpack.yml
