### ISSUE TITLE
Build failed, cannot set jdk16 in jitpack.yml

### ISSUE THREAD

**Issue by qyl27** [jitpack/jitpack.io#4685]
Please provide:

- Link to build log from https://jitpack.io
https://jitpack.io/com/github/AmemiyaSigure/LeangleCore/37e1d50f70/build.log

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?
Yes.

- What error are you seeing?
I saw the Jitpack building system still use the jdk8, even though I have specified openjdk16 in the `jitpack.yml`.

Thank you!

**Comment by Trengs** [comment]
Yes
