### ISSUE TITLE
After update to Gradle 7.0.2, jitpack always failed to build. (Build on Travis is ok)

### ISSUE THREAD

**Issue by Pjumpod** [jitpack/jitpack.io#4706]
Please provide:

Link to build log from https://jitpack.io
- https://jitpack.io/com/github/Pjumpod/RetrofitRssConverterFactory/1.0.1/build.log
Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?

- I use .travis.yml and already have result from Travis website. => here : https://app.travis-ci.com/Pjumpod/RetrofitRssConverterFactory.svg?branch=master
- My local use Android studio and I didn't found issue either.

What error are you seeing?
- Jitpack use JDK8 but gradle 7.0.2 require jdk11.
- my travis.yml also request jdk11 and there is setup step but jitpack do not follow it.
- I think jitpack just do gradlew only.

**Comment by Arsh069** [comment]
I am facing the same issue do you got any solution.??

**Comment by Pjumpod** [comment]
> I am facing the same issue do you got any solution.??

No not yet, But I see someone already got solved by admin. maybe case-by-case.

**Comment by kylecorry31** [comment]
I found that adding the following file to the root of my project resolves it: https://github.com/kylecorry31/Trail-Sense-Core/blob/main/jitpack.yml

**Comment by Pjumpod** [comment]
> I found that adding the following file to the root of my project resolves it: https://github.com/kylecorry31/Trail-Sense-Core/blob/main/jitpack.yml

Thank you very much, this issue has closed.
