### ISSUE TITLE
Android Gradle plugin requires Java 11 to run. You are currently using Java 1.8.

### ISSUE THREAD

**Issue by uncn** [jitpack/jitpack.io#4708]
https://jitpack.io/com/sunzn/banner/2.3.5/build.log

* What went wrong:
A problem occurred evaluating project ':Library'.
> Failed to apply plugin 'com.android.internal.library'.
   > Android Gradle plugin requires Java 11 to run. You are currently using Java 1.8.
     You can try some of the following options:
       - changing the IDE settings.
       - changing the JAVA_HOME environment variable.
       - changing `org.gradle.java.home` in `gradle.properties`.

**Comment by kylecorry31** [comment]
@uncn this happened to me as well, but I found that adding the following file to the root of my project resolves it: https://github.com/kylecorry31/Trail-Sense-Core/blob/main/jitpack.yml

**Comment by Canato** [comment]
Duplicate of #4474 
There is a solution on it, please use the same thread.
