### ISSUE TITLE
Android Gradle plugin requires Java 11 to run. You are currently using Java 1.8.

### ISSUE THREAD

**Issue by HZHAndroid** [jitpack/jitpack.io#4709]
Build starting...
Start: Mon Aug 30 14:12:28 UTC 2021 5e8dc123d09e
Git:
v1.4-0-g7560e37
commit 7560e370240e812b34c86dd0e1139f36f3122b0f
Author: 蓝月羽 
Date:   Mon Aug 30 22:08:07 2021 +0800

    add：1、添加了发布插件；1111

Found Android manifest
Android SDK version: . Build tools: 30.0.3
Installing Build-tools 30.0.3 
Found gradle
Gradle build script
Found gradle version: 7.0.2.
Using gradle wrapper
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2
Downloading https://services.gradle.org/distributions/gradle-7.0.2-bin.zip
.10%.20%.30%.40%.50%.60%.70%.80%.90%.100%

------------------------------------------------------------
Gradle 7.0.2
------------------------------------------------------------

Build time:   2021-05-14 12:02:31 UTC
Revision:     1ef1b260d39daacbf9357f9d8594a8a743e2152e

Kotlin:       1.4.31
Groovy:       3.0.7
Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020
JVM:          1.8.0_252 (Private Build 25.252-b09)
OS:           Linux 4.10.0-28-generic amd64

0m3.500s
Getting tasks: ./gradlew tasks --all
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2

FAILURE: Build failed with an exception.

* Where:
Build file '/home/jitpack/build/app/build.gradle' line: 2

* What went wrong:
An exception occurred applying plugin request [id: 'com.android.application']
> Failed to apply plugin 'com.android.internal.application'.
   > Android Gradle plugin requires Java 11 to run. You are currently using Java 1.8.
     You can try some of the following options:
       - changing the IDE settings.
       - changing the JAVA_HOME environment variable.
       - changing `org.gradle.java.home` in `gradle.properties`.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

Jitpack.yam has been added, but an error is reported

**Comment by Canato** [comment]
Duplicate of #4474 
There is a solution on it, please use the same thread.
