### ISSUE TITLE
How to re-trigger failed builds?

### ISSUE THREAD

**Issue by wujek-srujek** [jitpack/jitpack.io#4714]
Every now and then a build fails with `ERROR: Time-out getting container status`. What I've been doing so far is pushing another commit on top which is completely empty (I want to build exactly the same code), change the dependency in the dependant and re-trigger its build, which will in turn re-trigger JitPack.
According to https://jitpack.io/docs/BUILDING/#rebuilding there should be a way, but what exactly am I supposed to do? There is no remove button.
Is there any other way to re-trigger failed builds? I couldn't find anything in the Web-based UI, but maybe I missed something.

**Comment by WinterAlexander** [comment]
The need to pollute git history to retrigger builds that failed for reasons unrelated to the code is highly inconvenient. Hope a better option comes to light
