### ISSUE TITLE
need JDK11

### ISSUE THREAD

**Issue by HouChengYue** [jitpack/jitpack.io#4720]
Please provide:
**the log link:**[https://jitpack.io/com/github/HouChengYue/AiraDownload/v1.0.3/build.log](url)
I think it's means,should fix some gradle setting,and I don't know how to do fix it. it's in AndtroidStudio looks like well
- Link to build log from https://jitpack.io

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?

- What error are you seeing?

Thank you!

**Comment by marcocipriani01** [comment]
It is supported, take a look:
[jitpack.yml](https://jitpack.io/docs/BUILDING/#java-version)
[Support JDK 10 and 11](https://github.com/jitpack/jitpack.io/issues/2567)

**Comment by cyberpwnn** [comment]
With jitpack.yml
```
jdk:
- openjdk9
```

or 

```
jdk:
- openjdk10
```

or 

```
jdk:
- openjdk11
```

```
Kotlin:       1.4.31
Groovy:       3.0.7
Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020
JVM:          1.8.0_252 (Private Build 25.252-b09)
OS:           Linux 4.14.63-xxxx-std-ipv6-64 amd64
```

Useless

**Comment by shiziwen** [comment]
How can I specify the oracle java 11 instead of openjdk?
