### ISSUE TITLE
Build fails with "Timed out after 20 min"

### ISSUE THREAD

**Issue by bmarty** [jitpack/jitpack.io#4721]
Please provide:

- Link to build log from https://jitpack.io

https://jitpack.io/com/github/matrix-org/matrix-android-sdk2/v1.2.0-RC2/build.log

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?

Yes

- What error are you seeing?

Exit code: 0
Timed out after 20 min

This is my current configuration file: https://github.com/matrix-org/matrix-android-sdk2/blob/main/jitpack.yml

Is it possible to increase the time out value in the file jitpack.yml?

One other small remark: building binaries from jitpack is very long to start at the moment, it's a bit painful when trying to debug build issue.

**Comment by bmarty** [comment]
`matrix-android-sdk2` is now hosted by MavenCentral, so I prefer to close this issue myself.

**Comment by Osiris-Team** [comment]
@bmarty Its back, however it doesnt event attempt to build: https://jitpack.io/com/github/Osiris-Team/HBrowser/3.0.5/build.log
