### ISSUE TITLE
login support

### ISSUE THREAD

**Issue by MuratO** [jitpack/jitpack.io#4728]
Hi, we cannot login to the dashboard because our jitpack login information belongs to our former employee. 

Our payments are made automatically on a regular basis. 
The only information we can share is the card information from which the payments were made. If you share the e-mail address of the user account, maybe we can login. 

Can you help me ?

Thank you!

**Comment by jitpack-io** [comment]
Hi,

Sure, we should be able to help if you contact us via the Support button on jitpack.io
