### ISSUE TITLE
Cannot retrieve dependencies

### ISSUE THREAD

**Issue by ligi** [jitpack/jitpack.io#4729]
I cannot retrieve dependencies that I could retrieve before
Also the status dashboard shows problems:

![image](https://user-images.githubusercontent.com/111600/133020396-1aff243c-fbd9-4216-80d1-3c0d7c8e51f8.png)

any info when jitpack will be operational again? Kinda blocked by this currently - bummer

**Comment by ice1000** [comment]
JitPack is down for me too

**Comment by ice1000** [comment]
![image](https://user-images.githubusercontent.com/16398479/133022611-ffca709d-d2e8-442b-a7dc-ee016aa76db2.png)

**Comment by helloclareai** [comment]
I am also same.

**Comment by CarGuo** [comment]
JitPack is down for me too ，login fail & could not publish

**Comment by ice1000** [comment]
Why are people reacting with 'confused' and 'eyes' emojii to my screenshot? It's a badge created by shields.io and it currently cannot retrieve the version information of my published repo. Is that very confusing? 🤦‍♀️

**Comment by ligi** [comment]
Reacted with that as I wanted to react with a face that is not happy. Really sad about the situation and there is no sad-face - the confusing emoji was the closest to that - but removed it now ..

**Comment by jsprincep** [comment]
@jitpack-io What's the ETA for a resolution on this issue? Looks like it's been down for several hours now, and it's affecting all users, including paying users with concerned customers.

**Comment by Shane-Park** [comment]
It's back now.

**Comment by ligi** [comment]
yea it's back - closing
