### ISSUE TITLE
Build failure of TeamNewPipe/NewPipeExtractor

### ISSUE THREAD

**Issue by XiangRongLin** [jitpack/jitpack.io#4731]
Please provide:

- Link to build log from https://jitpack.io
https://jitpack.io/com/github/TeamNewPipe/NewPipeExtractor/v0.21.10/build.log

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?
Yes and Jitpack itself also builds it successfully
command was `./gradlew clean -Pgroup=com.github.TeamNewPipe -Pversion=v0.21.10 -xtest build publishToMavenLocal`

- What error are you seeing?
ERROR: Time-out getting container status

The build based on the commit is succeeding https://jitpack.io/#TeamNewPipe/NewPipeExtractor/ce8cabb9f8
See commit hash of release https://github.com/TeamNewPipe/NewPipeExtractor/releases/tag/v0.21.10

Thank you!

**Comment by TobiGr** [comment]
Rebuilding fixed this
