### ISSUE TITLE
Well, There's no such thing like free trial now. And I am only using one private repo from team repo to create a library by Jitpack. However, I get this error.

### ISSUE THREAD

**Issue by chanjungkim** [jitpack/jitpack.io#4735]
Well, There's no such thing like free trial now. And I am only using one private repo from team repo to create a library by Jitpack. However, I get this error.

```
Subscription is not active right now
Requested subscription: github.com/myteam. 
Your subscriptions are listed in https://jitpack.io/w/user
Please contact Support or repository admins if you need assistance.
```

[Jitpack pricing](https://jitpack.io/private#subscribe) says, up to 3 private repo, it's free. I don't know why I get this error and can't use the dependency.

_Originally posted by @chanjungkim in https://github.com/jitpack/jitpack.io/issues/2913#issuecomment-920516851_

**Comment by charlietangomobile** [comment]
Sigh.. I get the same - thought it was me.. I have bought Individual subscription, but it still shows "Starter" though i can see my invoice for the payment. Please help!

**Comment by jitpack-io** [comment]
Hi @chanjungkim and @charlietangomobile 

There could be several reasons why the subscription is not active and it'd be best to contact Support to look at this.
For example some users purchase a subscription for their own account but have not yet enabled it for an organisation. We can adjust that.

**Comment by jitpack-io** [comment]
@charlietangomobile Replied to your support ticket

**Comment by MikluhaMaclay** [comment]
Same problem here. I created ticket week ago

**Comment by jitpack-io** [comment]
@MikluhaMaclay Found your ticket and responded

**Comment by smithaaron** [comment]
I have the same problem and have sent several emails over the past week. Can someone please sort it out?

**Comment by chanjungkim** [comment]
why closed..?
