### ISSUE TITLE
ERROR: No build artifacts found

### ISSUE THREAD

**Issue by IM-IgniteDEV** [jitpack/jitpack.io#4737]
Please provide:

- Link to build log from https://jitpack.io: https://jitpack.io/com/github/2DevsStudio/2Devs-ProtocolFetcher/8f7b48502d/build.log

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ? Yes

- What error are you seeing? ERROR: No build artifacts found

Thank you!

**Comment by jitpack-io** [comment]
Hi,

We expect the build command to install artifacts in  $HOME/.m2/repository/com/ignitedev/2Devs-ProtocolFetcher/1.0.0
but seems it couldn't find them. We recommend running the build command locally to see if it installs in that directory.
