### ISSUE TITLE
No build artifact found

### ISSUE THREAD

**Issue by kshitijsharma6325** [jitpack/jitpack.io#4739]
Please provide:

- Link to build log from https://jitpack.io

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?

- What error are you seeing?

Thank you!

https://jitpack.io/com/github/kshitij6325/bilder/1.0.11/build.log

It is building fine on my local with command `./gradlew install`

**Comment by jitpack-io** [comment]
Hi,

It seems to be running :app:install while normally you would use JitPack to build libraries.
https://jitpack.io/docs/ANDROID/

**Comment by kshitijsharma6325** [comment]
My library was another git repo which was included as a submodule to the main repo, hence it was referencing the commit rather than the whole module. I removed the submodule and added my lib as a normal module and it worked.
