### ISSUE TITLE
AndroidValidatedForms/1.1.5 build

### ISSUE THREAD

**Issue by flibbertigibbet** [jitpack/jitpack.io#474]
Log https://jitpack.io/com/github/azavea/AndroidValidatedForms/1.1.5/build.log

It seems jitpack used to re-run the build if the `assemble` task needs to happen before `install`, but this no longer happens. Modifying the `gradlew` task to attempt to force `assemble` run before `install` has not worked.

**Comment by jitpack-io** [comment]
Hi

Looks like the build for 1.1.8 succeeded. Is the issue resolved then?

**Comment by flibbertigibbet** [comment]
Thank you for your response. For 1.1.8, I added the intermediate jar generated by the `assemble` task to the repository as a workaround. I'd like to see 1.1.5 be able to build.

**Comment by flibbertigibbet** [comment]
Why was this closed?

**Comment by jitpack-io** [comment]
We now support custom build commands in jitpack.yml which should be enough to build the project:
https://jitpack.io/docs/BUILDING/#build-customization

Doesn't seem like there's anything left on our side to resolve this issue.

**Comment by flibbertigibbet** [comment]
Thanks for the info, and the build customization!
