### ISSUE TITLE
BUILD SUCCESSFUL but build still not available?

### ISSUE THREAD

**Issue by jimblackler** [jitpack/jitpack.io#4746]
Please provide:

- Link to build log from https://jitpack.io

https://jitpack.io/net/jimblackler/jsonschemafriend/0.11.0/build.log

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?

Yes

- What error are you seeing?

It just says "Status:error" on mouseover on https://jitpack.io/#net.jimblackler/jsonschemafriend

As far as I can see the build succeeded though, with "BUILD SUCCESSFUL in 18s"

**Comment by jimblackler** [comment]
Appears to be transitory. Once I could sign in, I was able to force rebuild and it seems to be working now.

**Comment by BongoJitpack** [comment]
@jimblackler hi,
I am facing the same issue since morning and couldn't figure out what's wrong. Can you please help me out with this issue? Please help me out...
