### ISSUE TITLE
When trying to use wordpress-mobile/wellsql: SNAPSHOT expected but sha1 found

### ISSUE THREAD

**Issue by maxme** [jitpack/jitpack.io#476]
I tried to build this project: https://github.com/wordpress-mobile/wellsql (branch `jitpack`), by adding the following to my build.gradle file:

``` gradle
compile 'com.github.wordpress-mobile:wellsql:jitpack-SNAPSHOT'
```

But I get this error

```
   > Could not resolve com.github.wordpress-mobile:wellsql:jitpack-SNAPSHOT.
     Required by:
         org.wordpress:WordPressStores:0.1
      > Could not resolve com.github.wordpress-mobile:wellsql:jitpack-SNAPSHOT.
         > inconsistent module metadata found. Descriptor: com.github.wordpress-mobile:wellsql:jitpack-1.0.6-gca357d2-1 Errors: bad version: expected='jitpack-SNAPSHOT' found='jitpack-1.0.6-gca357d2-1'
```

Related log: https://jitpack.io/com/github/wordpress-mobile/wellsql/jitpack-1.0.6-gca357d2-1/build.log

**Comment by jitpack-io** [comment]
Hi

What about `com.github.wordpress-mobile.wellsql:wellsql:jitpack-SNAPSHOT` ? Seems to be working in AS.
Since it's a multi-module project you need to specify the modules you're interested in.
