### ISSUE TITLE
build successful but no artifact found

### ISSUE THREAD

**Issue by valkriaine** [jitpack/jitpack.io#4762]
Please provide:

- Link to build log from https://jitpack.io
  https://jitpack.io/com/github/valkriaine/Bouncy/2.0/build.log

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?
  The project builds successfully

- What error are you seeing?
  It appears to build successfully on Jitpack but shows no artifact found at the end.

BUILD SUCCESSFUL in 55s
119 actionable tasks: 116 executed, 3 up-to-date
Build tool exit code: 0
Looking for artifacts...
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2
Looking for pom.xml in build directory and ~/.m2
2021-10-02T00:35:15.180857671Z
Exit code: 0

ERROR: No build artifacts found

Thank you!

**Comment by Vipinbalakrishnan** [comment]
@valkriaine 

Please check and following below steps.

1.Update gradle plugin version to the latest in build.gradle file
-of the project root in the dependencies section as below.

dependencies {
    classpath "com.android.tools.build:gradle:7.0.2"
}

2.Add jitpack.io repository to build.gradle file of the root as well as the library module of the project as below. 

repositories {
    google()
    mavenCentral()
    maven { url "https://jitpack.io" }
}

 3.Add plugin maven-publish in the build.gradle file of the module as below along with library plugin.

plugins {
    id 'com.android.library'
    id 'maven-publish'
}

4.Add jitpack.yml in the root of the project for JAVA 11 support. 
Create a file with name as 'jitpack.yml' with the following content

jdk:
  -openjdk11

5.Change java version to 11 in build.gradle file of the app module and library module inside android {} as below.
New gradle plugin builds on java 11.

compileOptions {
    sourceCompatibility JavaVersion.VERSION_11
    targetCompatibility JavaVersion.VERSION_11
}

6.Add maven publication settings as below in the build.gradle of module.

afterEvaluate {
    publishing {
        publications {
            // Creates a Maven publication called "release".
            release(MavenPublication) {
                from components.release
                groupId = 'com.github.Vipinbalakrishnan'
                artifactId = 'ribbonlayout'
                version = '1.1'
            }
        }
    }
}

Note:- Sixth step is necessary.

**Comment by AndroidDeveloperLB** [comment]
@Vipinbalakrishnan About the 6-th step, to have a more general solution, you can also use this instead:

```
    afterEvaluate {
        publishing {
            publications {
                release(MavenPublication) {
                    from components.release
                }
            }
        }
    }
```
