### ISSUE TITLE
"Error No artifacts found" after a successful build.

### ISSUE THREAD

**Issue by Vipinbalakrishnan** [jitpack/jitpack.io#4766]
"Error No artifacts found" after a successful build.
I am trying to publish an Android library.
It is building in local machine.
But when try to publish it in jitpack.io,
I am getting the error.

BUILD SUCCESSFUL in 1m 13s
119 actionable tasks: 116 executed, 3 up-to-date
Build tool exit code: 0
Looking for artifacts...
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2
Looking for pom.xml in build directory and ~/.m2
2021-10-01T15:49:00.208744998Z
Exit code: 0

ERROR: No build artifacts found

**To Reproduce**
1. trying to build the library git repo 'https://jitpack.io/#Vipinbalakrishnan/ribbon-layout'
2. See the error log in https://jitpack.io/com/github/Vipinbalakrishnan/ribbon-layout/0.0.6/build.log

**Additional context**
1. I am using gradle  version 'com.android.tools.build:gradle:7.0.2'
2. I have also added maven-publish plugin in module build.gradle file as below
plugins {
    id 'com.android.library'
    id 'maven-publish'
}

3. In application build.gradle file, I have added maven repo as well as seen below.
maven { url "https://jitpack.io" }

Please advice to publish my library to jipack without any issues.

**Comment by Bae-tory** [comment]
I have same issue..
