### ISSUE TITLE
WordPress-Stores-Android/jitpack-250a7eb504-1 build

### ISSUE THREAD

**Issue by maxme** [jitpack/jitpack.io#477]
Everything seems ok when I run `gradle install` locally, but I get this log  https://jitpack.io/com/github/wordpress-mobile/WordPress-Stores-Android/jitpack-250a7eb504-1/build.log

Apparently It tries  to build the sample project "example" but `android-maven-gradle-plugin` is only applied on the library project:

https://github.com/wordpress-mobile/WordPress-Stores-Android/blob/jitpack/WordPressStores/build.gradle#L14

**Comment by jitpack-io** [comment]
Hi

The error occurs when running `./gradlew tasks` and it returns tasks for all projects. 
One way to work around this is to check if file exists before reading it into properties.
