### ISSUE TITLE
 Android Gradle plugin requires Java 11 to run. You are currently using Java 1.8.

### ISSUE THREAD

**Issue by gregko** [jitpack/jitpack.io#4772]
FAILURE: Build failed with an exception.

* Where:
Build file '/home/jitpack/build/app/build.gradle' line: 2

* What went wrong:
An exception occurred applying plugin request [id: 'com.android.application']
> Failed to apply plugin 'com.android.internal.application'.
   > Android Gradle plugin requires Java 11 to run. You are currently using Java 1.8.
     You can try some of the following options:
       - changing the IDE settings.
       - changing the JAVA_HOME environment variable.
       - changing `org.gradle.java.home` in `gradle.properties`.

Please provide:

- Link to build log from https://jitpack.io
- https://jitpack.io/com/github/gregko/Mini-WebDAV-server-for-Android/1.6.3/build.log

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?
- Yes

- What error are you seeing?
- " Android Gradle plugin requires Java 11 to run. You are currently using Java 1.8."

Thank you!

**Comment by Vipinbalakrishnan** [comment]
@gregko Please do the below 2 steps.

First, change JAVA8 from your build.gradle(app module) file to 11 like below

compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
}
    
Secondly, add a file in the root folder of your project-
-named jitpack.yml file with the following content.

jdk:
  - openjdk11
  
  
These two steps will solve the problem that you are facing.

This happens because of the gradle build tools version.
Latest versions requires Java 11.

**Comment by Vipinbalakrishnan** [comment]
@gregko 

For the current issue, you need to specify the maven plugin and 
- 'afterEvaluate' section in build.gradle file of your module.

Please check the below steps that are necessary to publish a library to jitpack.io

Omit the ones related to java 11 as you have already did those.

1. Added jitpack.io to build.gradle file of the root of the project ad below.  maven { url "https://jitpack.io" }

 2. Added plugin maven-publish in the build.gradle file of the module as below along with library plugin.

plugins {
    id 'com.android.library'
    id 'maven-publish'
}

3.Added jitpack.yml in the root of the project for JAVA 11 support

As below  jdk:
  - openjdk11

4.Change java version to 11 in build.gradle file of the app module and library module inside android {} as below

compileOptions {
    sourceCompatibility JavaVersion.VERSION_11
    targetCompatibility JavaVersion.VERSION_11
}

5.Add maven publication settings as below in the build.gradle of module  

afterEvaluate {
    publishing {
        publications {
            // Creates a Maven publication called "release".
            release(MavenPublication) {
                from components.release
                groupId = 'com.github.yourgitid'
                artifactId = 'your-repository'
                version = 'x.x'
            }
        }
    }
}

**Comment by gregko** [comment]
Thank you for your help! Looks like it worked.

**Comment by Vipinbalakrishnan** [comment]
@gregko, 

Glad that it helped you.

Please close the issue if it is worked.

Thank you.

**Comment by alkathirikhalid** [comment]
Useful,

I had the same problem the solution provided resolved it:
- Could not generate a decorated class for type AndroidMavenPlugin.

Code Changes
- https://github.com/alkathirikhalid/connection/commit/e3195cae4e83eceaf430d7aa497088422e4b7ee3

Build / Logs
- https://jitpack.io/com/github/alkathirikhalid/connection/v1.0.9/build.log

Thank you.
