### ISSUE TITLE
Error when choosing release

### ISSUE THREAD

**Issue by mahdi-1384** [jitpack/jitpack.io#4774]
Hello

I have one github repository and it has one release.
When I enter the address of the repository and choose the release , it gives me error and doesn't finish successfully. What is the problem?
![Screenshot_۲۰۲۱-۱۰-۰۸-۰۳-۵۶-۴۴-۱۱۹_org mozilla firefox](https://user-images.githubusercontent.com/72357634/136479633-c3c8946e-99cc-4435-95bb-e3b750a4fc7a.jpg)

Thank you!

**Comment by Vipinbalakrishnan** [comment]
@mahdi-1384 

Please click on the red outlined document icon against the build and see the error details.

**Comment by Vipinbalakrishnan** [comment]
@mahdi-1384 

There can be two main problems.

One is regarding java 11 version.

And another is artifacts not found error after a successful build.

Java 11 error can happen when your gradle version requires Java version 11 to build.
But jitpack.io by default is using Java 1.8.

So you need to tell to use Java 11 by creating a file named 'jitpack.yml' in the root of the project with the following content.

jdk:
  -openjdk11.
  
But for fixing the other issues, please refer to the below detailed steps.

I am able to successfully release my library to jitpack.io by the following steps.

1.Updated gradle plugin version to the latest in build.gradle file
- of the project root in the dependencies section as below.

dependencies {
    classpath "com.android.tools.build:gradle:7.0.2"
}

2.Added jitpack.io repository to build.gradle file of the root as well as the library module of the project as below. 

repositories {
    google()
    mavenCentral()
    maven { url "https://jitpack.io" }
}

 3.Added plugin maven-publish in the build.gradle file of the module as below along with library plugin.

plugins {
    id 'com.android.library'
    id 'maven-publish'
}

4.Added jitpack.yml in the root of the project for JAVA 11 support. 
Create a file with name as 'jitpack.yml' with the following content

jdk:
  -openjdk11

5.Changed java version to 11 in build.gradle file of the app module and library module inside android {} as below.
New gradle plugin builds on java 11.

compileOptions {
    sourceCompatibility JavaVersion.VERSION_11
    targetCompatibility JavaVersion.VERSION_11
}

6.Added maven publication settings as below in the build.gradle of module.

afterEvaluate {
    publishing {
        publications {
            // Creates a Maven publication called "release".
            release(MavenPublication) {
                from components.release
                groupId = 'com.github.Vipinbalakrishnan'
                artifactId = 'ribbonlayout'
                version = '1.1'
            }
        }
    }
}

Note:- Sixth step is necessary.
