### ISSUE TITLE
FAILURE: Build failed with an exception.

### ISSUE THREAD

**Issue by astrit-veliu** [jitpack/jitpack.io#4777]
Please provide:

- Link to build log from https://jitpack.io
- https://jitpack.io/com/github/astrit-veliu/Smoolider/1.2/build.log

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?
- The build works fine on my machine

- What error are you seeing?

FAILURE: Build failed with an exception.

* Where:
Build file '/home/jitpack/build/app/build.gradle' line: 2

* What went wrong:
An exception occurred applying plugin request [id: 'com.android.application']
> Failed to apply plugin 'com.android.internal.application'.
   > Android Gradle plugin requires Java 11 to run. You are currently using Java 1.8.
     You can try some of the following options:
       - changing the IDE settings.
       - changing the JAVA_HOME environment variable.
       - changing `org.gradle.java.home` in `gradle.properties`.

**Comment by AndroidDeveloperLB** [comment]
Can you please make it auto-use the JDK 11 based on what's in the gradle file? Or even make the new default?
New projects nowadays on Android use JDK 11 by default...

**Comment by AndroidDeveloperLB** [comment]
@Vipinbalakrishnan Adding the jitpack.yml file didn't work. I tried to add it in either the root path and in the library module path, and both got me the same issue:

https://jitpack.io/#AndroidDeveloperLB/FastScrollerAndRecyclerViewFixes/8071e11d97
https://jitpack.io/com/github/AndroidDeveloperLB/FastScrollerAndRecyclerViewFixes/8071e11d97/build.log

https://jitpack.io/#AndroidDeveloperLB/FastScrollerAndRecyclerViewFixes/edc01fdb5b
https://jitpack.io/com/github/AndroidDeveloperLB/FastScrollerAndRecyclerViewFixes/edc01fdb5b/build.log

**Comment by omwilliams** [comment]
fuck u nigger and white nigger whores

**Comment by astrit-veliu** [comment]
@Vipinbalakrishnan, @AndroidDeveloperLB thank you for your suggestion, will try them and see if it fixes the issue :)
