### ISSUE TITLE
Unable to set jdk17

### ISSUE THREAD

**Issue by xia-weiyang** [jitpack/jitpack.io#4778]
```
jdk:
  - openjdk17
```
I set it like this, still jdk1.8, but I can successfully set jdk11.

**Comment by javlock** [comment]
@xia-weiyang 
1.you need to create a config for jitpack in the root of the repository,
2. [look at my config](https://github.com/javlock/ostools/blob/dfb8a9d0d53dd5733019ca1141953c9bdcc5f881/jitpack.yml), just wrote for openjdk17
3. Support me introducing the [feature in this issue](https://github.com/jitpack/jitpack.io/issues/4891)

**Comment by xia-weiyang** [comment]
Thank you, It succeeded!

**Comment by tehnewb** [comment]
This issue still occurs for me.

This is my jitpack.yml in my root repository:
`jdk:
  - openjdk17
before_install:
  - sdk install java 17.0.1-open
  - sdk use java 17.0.1-open`
  
  This is the build file from your website:
  `Build starting...
Start: Mon Dec 11 16:43:54 UTC 2023 88e04582ff6d
Git:
1.0-0-g500f04c
commit 500f04c295e5a34f48ef14964a7aeed2285fbdef
Author: Wildskiller 
Date:   Mon Dec 11 09:11:01 2023 -0600

    Update publish-workflow.yml


Init SDKMan
Found gradle
Gradle build script
Found gradle version: 8.5.
Using gradle wrapper
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2
Downloading https://services.gradle.org/distributions/gradle-8.5-bin.zip
.10%.20%.30%.40%.50%.60%.70%.80%.90%.100%

------------------------------------------------------------
Gradle 8.5
------------------------------------------------------------

Build time:   2023-11-29 14:08:57 UTC
Revision:     28aca86a7180baa17117e0e5ba01d8ea9feca598

Kotlin:       1.9.20
Groovy:       3.0.17
Ant:          Apache Ant(TM) version 1.10.13 compiled on January 4 2023
JVM:          1.8.0_292 (Private Build 25.292-b10)
OS:           Linux 4.14.63-xxxx-std-ipv6-64 amd64

0m3.293s
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2
openjdk version "1.8.0_292"
OpenJDK Runtime Environment (build 1.8.0_292-8u292-b10-0ubuntu1~16.04.1-b10)
OpenJDK 64-Bit Server VM (build 25.292-b10, mixed mode)
Getting tasks: ./gradlew tasks --all
Tasks: publishToMavenLocal,
Found javadoc task
Running: ./gradlew clean -Pgroup=com.github.tehnewb -Pversion=1.0 -xtest assemble publishToMavenLocal
> Task :clean UP-TO-DATE
> Task :Benchmarking:clean UP-TO-DATE
> Task :Collections:clean UP-TO-DATE
> Task :ECS:clean UP-TO-DATE
> Task :Event:clean UP-TO-DATE
> Task :Game:clean UP-TO-DATE
> Task :IO:clean UP-TO-DATE
> Task :Math:clean UP-TO-DATE
> Task :Network:clean UP-TO-DATE
> Task :Utilities:clean UP-TO-DATE
> Task :compileJava NO-SOURCE
> Task :processResources NO-SOURCE
> Task :classes UP-TO-DATE
> Task :jar
> Task :sourcesJar
> Task :assemble
> Task :Utilities:compileJava FAILED
13 actionable tasks: 3 executed, 10 up-to-date
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':Utilities:compileJava'.
> invalid source release: 17

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 941ms
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2
Build tool exit code: 0
Looking for artifacts...
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2
Looking for pom.xml in build directory and ~/.m2
2023-12-11T16:44:08.494729968Z
Exit code: 0

⚠️ ERROR: No build artifacts found
`

**Comment by saeedjavazanjan** [comment]
> This issue still occurs for me.
> 
> This is my jitpack.yml in my root repository:
> 
> ```
> jdk:
>   - openjdk17
> before_install:
>   - sdk install java 17.0.1-open
>   - sdk use java 17.0.1-open
> ```
> 
> This is the build file from your website:
> 
> ```
> Build starting...
> Start: Mon Dec 11 16:43:54 UTC 2023 88e04582ff6d
> Git:
> 1.0-0-g500f04c
> commit 500f04c295e5a34f48ef14964a7aeed2285fbdef
> Author: Wildskiller 
> Date:   Mon Dec 11 09:11:01 2023 -0600
> 
>   Update publish-workflow.yml
> 
> 
> Init SDKMan
> Found gradle
> Gradle build script
> Found gradle version: 8.5.
> Using gradle wrapper
> Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2
> Downloading https://services.gradle.org/distributions/gradle-8.5-bin.zip
> .10%.20%.30%.40%.50%.60%.70%.80%.90%.100%
> 
> ------------------------------------------------------------
> Gradle 8.5
> ------------------------------------------------------------
> 
> Build time:   2023-11-29 14:08:57 UTC
> Revision:     28aca86a7180baa17117e0e5ba01d8ea9feca598
> 
> Kotlin:       1.9.20
> Groovy:       3.0.17
> Ant:          Apache Ant(TM) version 1.10.13 compiled on January 4 2023
> JVM:          1.8.0_292 (Private Build 25.292-b10)
> OS:           Linux 4.14.63-xxxx-std-ipv6-64 amd64
> 
> 0m3.293s
> Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2
> openjdk version "1.8.0_292"
> OpenJDK Runtime Environment (build 1.8.0_292-8u292-b10-0ubuntu1~16.04.1-b10)
> OpenJDK 64-Bit Server VM (build 25.292-b10, mixed mode)
> Getting tasks: ./gradlew tasks --all
> Tasks: publishToMavenLocal,
> Found javadoc task
> Running: ./gradlew clean -Pgroup=com.github.tehnewb -Pversion=1.0 -xtest assemble publishToMavenLocal
> > Task :clean UP-TO-DATE
> > Task :Benchmarking:clean UP-TO-DATE
> > Task :Collections:clean UP-TO-DATE
> > Task :ECS:clean UP-TO-DATE
> > Task :Event:clean UP-TO-DATE
> > Task :Game:clean UP-TO-DATE
> > Task :IO:clean UP-TO-DATE
> > Task :Math:clean UP-TO-DATE
> > Task :Network:clean UP-TO-DATE
> > Task :Utilities:clean UP-TO-DATE
> > Task :compileJava NO-SOURCE
> > Task :processResources NO-SOURCE
> > Task :classes UP-TO-DATE
> > Task :jar
> > Task :sourcesJar
> > Task :assemble
> > Task :Utilities:compileJava FAILED
> 13 actionable tasks: 3 executed, 10 up-to-date
> Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':Utilities:compileJava'.
> > invalid source release: 17
> 
> * Try:
> > Run with --stacktrace option to get the stack trace.
> > Run with --info or --debug option to get more log output.
> > Run with --scan to get full insights.
> > Get more help at https://help.gradle.org.
> 
> BUILD FAILED in 941ms
> Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2
> Build tool exit code: 0
> Looking for artifacts...
> Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2
> Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2
> Looking for pom.xml in build directory and ~/.m2
> 2023-12-11T16:44:08.494729968Z
> Exit code: 0
> 
> ⚠️ ERROR: No build artifacts found
> ```

you should update your tag version
