### ISSUE TITLE
No build artifacts found

### ISSUE THREAD

**Issue by KrystilizeNevaDies** [jitpack/jitpack.io#4785]
- Link to build log from https://jitpack.io
https://jitpack.io/com/github/KrystilizeNevaDies/JLSL/cf54cc3af5/build.log

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?
Yep, it builds using `./gradlew clean -Pgroup=com.github.KrystilizeNevaDies -Pversion=cf54cc3af5 -xtest build publishToMavenLocal`

- What error are you seeing?
No apparent error:
```
BUILD SUCCESSFUL in 2s
3 actionable tasks: 2 executed, 1 up-to-date
Build tool exit code: 0
Looking for artifacts...
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2
Looking for pom.xml in build directory and ~/.m2
2021-10-13T05:48:25.786632252Z
Exit code: 0

ERROR: No build artifacts found
```
Thank you!

**Comment by KrystilizeNevaDies** [comment]
Update, this has been solved:
```
publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
        }
    }
}
```
This code has fixed my issues, thanks.

**Comment by SharmaShubham07** [comment]
I was having the same issue today and finally it has been resolved 

The thing i did is just deleted my .yml file and let the compiler find it manually and the isuue will be resolved. 


Hope this finds you well and will help you.
