### ISSUE TITLE
How to delete my library on jitpack?

### ISSUE THREAD

**Issue by AfterFinal** [jitpack/jitpack.io#4815]
How to delete my library on jitpack?

**Comment by jitpack-io** [comment]
Hi

Libraries can only be deleted within the first 7 days of publishing.
We recommend releasing a new version if there is an issue with the library.

**Comment by AfterFinal** [comment]
I want to delete all my libraries for legal issues, What should I do?

**Comment by toymachiner62** [comment]
I also need to delete my package for legal issues. How can a package be deleted from jitpack?
