### ISSUE TITLE
AboutLibraries/v6.0.0 build

### ISSUE THREAD

**Issue by prudencioj** [jitpack/jitpack.io#482]
This build is failing, I don't understand why. Can anyone help me?

Log https://jitpack.io/com/github/andrebcmarinho/AboutLibraries/v6.0.0/build.log

**Comment by jitpack-io** [comment]
Hi

The project is trying to import this class https://github.com/andrebcmarinho/AboutLibraries/blob/develop/library/src/main/java/com/mikepenz/aboutlibraries/util/UIUtils.java#L13
but it doesn't seem to be there.
