### ISSUE TITLE
Error build with gradle 7.0.2

### ISSUE THREAD

**Issue by ngtien137** [jitpack/jitpack.io#4824]
Please provide:

- Link to build log from https://jitpack.io

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?

- What error are you seeing?

Thank you!

**Comment by cyb3rko** [comment]
Please close this issue as there is no additional information given.

**Comment by orlando-dev-code** [comment]
Wrong build
I tried to upload two test modules and in both cases I got the same error.

This is the last
https://jitpack.io/com/github/orlando-dev-code/random-text/0.0.2-alpha/build.log

`* What went wrong:
An exception occurred applying plugin request [id: 'com.android.application']
> Failed to apply plugin 'com.android.internal.application'.
   > Android Gradle plugin requires Java 11 to run. You are currently using Java 1.8.
     You can try some of the following options:
       - changing the IDE settings.
       - changing the JAVA_HOME environment variable.
       - changing `org.gradle.java.home` in `gradle.properties`.`

I changed the version from Java 1.8 to Java 11 and it kept giving the same error.

**Comment by cyb3rko** [comment]
Take a look at https://github.com/jitpack/jitpack.io/issues/4777.

Vipinbalakrishnan explains that you have to add a jitpack.yml file in the root directory and implement maven publish settings as well.
Worked for me.

**Comment by orlando-dev-code** [comment]
Yes @cyb3rko work for me too

**Comment by AndroidDeveloperLB** [comment]
@cyb3rko Why is it needed now? Why can't it automatically choose what it should use, as was done so far, without extra files?
Jitpack used to be so easy, and now it requires extra files...

**Comment by cyb3rko** [comment]
@AndroidDeveloperLB I have no idea, I just searched for solutions and it worked lol :D

**Comment by AndroidDeveloperLB** [comment]
@cyb3rko OK I thought you are one of its developers or something

**Comment by asywalulfikri** [comment]
can you show me the steps @cyb3rko

**Comment by javlock** [comment]
1.you need to create a config for jitpack in the root of the repository,
2. look at [my config](https://github.com/javlock/ostools/blob/dfb8a9d0d53dd5733019ca1141953c9bdcc5f881/jitpack.yml), just wrote for openjdk17 (added amazon corretto opendjk installation)
3. Support me introducing the [feature in this issue](https://github.com/jitpack/jitpack.io/issues/4891)

**Comment by AndroidDeveloperLB** [comment]
@javlock For some reason, one project I have has issues (some/all classes can't be found when using it via Jitpack), and another doesn't have any issues, even though I have tried the same steps:

https://github.com/AndroidDeveloperLB/FastScrollerAndRecyclerViewFixes - bad on recent commits
https://github.com/AndroidDeveloperLB/CommonUtils - works fine

How could it be?
