### ISSUE TITLE
java11 support

### ISSUE THREAD

**Issue by 1106035348** [jitpack/jitpack.io#4829]
- Link to build log from https://jitpack.io
https://jitpack.io/com/github/skynetcapital/solanaj/1.6-SNAPSHOT/build.log
- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?
yes
- What error are you seeing?
invalid target release: 11

**Comment by jitpack-io** [comment]
Hi,

There's way to specify java version using custom commands: https://jitpack.io/docs/BUILDING/#java-version
