### ISSUE TITLE
Skipping task ':install' as it has no source files and no previous output files.

### ISSUE THREAD

**Issue by i-vasilev** [jitpack/jitpack.io#4833]
Hello! I try to deploy my library using jitpack, but I have an error.

- Link to build log from https://jitpack.io/com/github/i-vasilev/Selenile/9ab580b9f6/build.log

I have the same problem on my machine:
> Task :install NO-SOURCE
Skipping task ':install' as it has no source files and no previous output files.
:install (Thread[Execution worker for ':',5,main]) completed. Took 0.001 secs.

What can be problem? I am trying to make it 3 days.
Thank you!

**Comment by jitpack-io** [comment]
Hi

We recommend adding the `maven-publish` plugin and including this `publishing` section in the build file:
https://docs.gradle.org/current/userguide/publishing_maven.html#sec:identity_values_in_the_generated_pom

**Comment by i-vasilev** [comment]
@jitpack-io I added this plugin and section, but it doesn't work:

https://github.com/i-vasilev/Selenile/blob/releases/build.gradle
