### ISSUE TITLE
Infinite build

### ISSUE THREAD

**Issue by afollestad** [jitpack/jitpack.io#484]
One of my libraries appear to be stuck in an infinite build.

The build log for the latest commit is blank and ongoing: https://jitpack.io/com/github/afollestad/bridge/fbac9746e4/build.log

**Comment by snotyak** [comment]
I'm having the same thing here - https://jitpack.io/com/github/snotyak/android-ui/1.0.0/build.log

**Comment by ben-manes** [comment]
Seeing the same problem when jitpack is queried for a dependency during the build.

```
$ wget jitpack.io/com/github/jbellis/jamm/v0.3.1/jamm-v0.3.1.pom
--2016-03-21 23:25:45--  http://jitpack.io/com/github/jbellis/jamm/v0.3.1/jamm-v0.3.1.pom
Resolving jitpack.io... 104.24.22.62, 104.24.23.62
Connecting to jitpack.io|104.24.22.62|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://jitpack.io/com/github/jbellis/jamm/v0.3.1/jamm-v0.3.1.pom [following]
--2016-03-21 23:25:45--  https://jitpack.io/com/github/jbellis/jamm/v0.3.1/jamm-v0.3.1.pom
Connecting to jitpack.io|104.24.22.62|:443... connected.
HTTP request sent, awaiting response...
```

**Comment by jitpack-io** [comment]
Hi all

Should be resolved now, builds were getting queued up.

**Comment by snotyak** [comment]
@jitpack-io Thanks!

**Comment by Maxr1998** [comment]
@jitpack-io Main website and build server still extremely sluggish for me.. I can't even get to the list of commits on jitpack.
