### ISSUE TITLE
Kotlin build failed to execute kaptDebugKotlin

### ISSUE THREAD

**Issue by nitinblotout** [jitpack/jitpack.io#4840]
Please provide:

- [Link to build log from https://jitpack.io/com/github/blotoutio/sdk-android/restore_kapt_2/build.log]

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ? Yes

- What error are you seeing? 
   It failed to execute kaptDebugKotlin , without kotlin-kapt it works , but it is very much needed. 

Thank you!

**Comment by jitpack-io** [comment]
Hi

Looks like that tag doesn't exist anymore.
