### ISSUE TITLE
why?

### ISSUE THREAD

**Issue by L-Rvld** [jitpack/jitpack.io#4848]
Please provide:

- Link to build log from 
[log.txt](https://github.com/jitpack/jitpack.io/files/7592392/log.txt)
https://jitpack.io

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?

- What error are you seeing?

Thank you!

**Comment by jitpack-io** [comment]
Hi

It is possible to set Java version to 11 using custom commands https://jitpack.io/docs/BUILDING/#custom-commands
