### ISSUE TITLE
Bitbucket with Private Repository builds successfull but @AAR not generated with Access Token 

### ISSUE THREAD

**Issue by mohitdholakia** [jitpack/jitpack.io#4849]
I have created Bitbucket private repo and which I have configured with JItpack.

In Jitpack console build is getting success full and once I put Gradle in my project @AAR files are not getting generated

I have also used 

```
maven {
            credentials {
                username "JITPACK-ACCESS-TOKEN"
            }
            url "https://jitpack.io"
 }
```

Any help on how to access my private repo's dependency?

Thanks in advance

**Comment by jitpack-io** [comment]
Hi

We'd recommend looking at the build log to see if the .aar file was generated. There is a list of published artifacts at the very end.
If the aar file is there then it's useful to know what kind of error Gradle is getting from JitPack - what kind of HTTP status code. To get more details about the error you could add `--info` flag to Gradle and run it from command line.
