### ISSUE TITLE
CubeGrid/1.2.1 build

### ISSUE THREAD

**Issue by alighters** [jitpack/jitpack.io#486]
Log https://jitpack.io/com/github/david-wei/CubeGrid/1.2.1/build.log

**Comment by jitpack-io** [comment]
Hi 

The issue here was the cyclic dependency https://github.com/david-wei/CubeGrid/blob/d7d2ebd5527cff5a34040e6f53f9c5192a18b002/app/build.gradle#L26-L27
But it looks like you've removed it since
