### ISSUE TITLE
Report issue

### ISSUE THREAD

**Issue by alikamran07** [jitpack/jitpack.io#4871]
Please provide:

- Link to build log from https://jitpack.io

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?

- What error are you seeing?

Thank you!

**Comment by alikamran07** [comment]
facing problem with jitpack always generate a report when i copy paste of my project file to jitpack

**Comment by alikamran07** [comment]
please give my answer of my problem soon

**Comment by javlock** [comment]
I found the answer, I need to write a config in the repository, but automatic recognition of the java version would also be important for me

https://jitpack.io/docs/BUILDING/#java-version
