### ISSUE TITLE
My JDK is 11 but Jitpack reports me built on jdk 1.8

### ISSUE THREAD

**Issue by SkybirdBits** [jitpack/jitpack.io#4878]
**I used this package with JDK 11 compile options and i set my gradle to use jdk 11 in ide settings too but every time i request get
Jitpack answers me the same problem:**
------------------------------------------------------------

Build time:   2021-08-17 09:59:03 UTC
Revision:     a773786b58bb28710e3dc96c4d1a7063628952ad

Kotlin:       1.5.21
Groovy:       3.0.8
Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020
JVM:          1.8.0_252 (Private Build 25.252-b09)
OS:           Linux 4.10.0-28-generic amd64

Getting tasks: ./gradlew tasks --all
0m4.132s
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2

FAILURE: Build failed with an exception.

* Where:
Build file '/home/jitpack/build/lib/build.gradle' line: 1

* What went wrong:
A problem occurred evaluating project ':lib'.
> Failed to apply plugin 'com.android.internal.library'.
   > Android Gradle plugin requires Java 11 to run. You are currently using Java 1.8.

<a href="https://jitpack.io/com/github/skybirdbits/PersianDatePicker/b7b3589561/build.log">**log link in jitpac**k</a>

**Comment by javlock** [comment]
@SkybirdBits 
1.you need to create a config for jitpack in the root of the repository,
2. look at [my config](https://github.com/javlock/ostools/blob/dfb8a9d0d53dd5733019ca1141953c9bdcc5f881/jitpack.yml), just wrote for openjdk17 (added amazon corretto opendjk installation)
3. Support me introducing the [feature in this issue](https://github.com/jitpack/jitpack.io/issues/4891)
