### ISSUE TITLE
Support for Boot

### ISSUE THREAD

**Issue by xcthulhu** [jitpack/jitpack.io#488]
Increasingly more and more Clojure projects are migrating away from leiningen to [Boot](http://boot-clj.com/).

It would be nice if jitpack.io supported `boot`... but of course you are already heroes for supporting leiningen and doing this service to the Clojure community.

**Comment by jitpack-io** [comment]
Hi @xcthulhu 

Thank you for the suggestion! In the first instance we'll be supporting custom build commands #354 which should allow you to use Boot on JitPack. In time we can probably add out-of-the-box support if there's community interest.
