### ISSUE TITLE
multi jdk support (java 8(now) and others)

### ISSUE THREAD

**Issue by javlock** [jitpack/jitpack.io#4891]
1.My project needs new jdk features. Need a different jdk version.

2. When trying to build the repository, I received an error (there is no such artifact), I started to rummage through what was going on, came to your solution, drew attention to the red assembly mark, went into the log and saw that jdk 8 was being used, on property 17 it wrote: "`invalid target release: 17 `"
[link to the project log, (Outdated after successful build)](https://jitpack.io/com/github/javlock/ostools/main-f37c1b4b4b-1/build.log)

3. The solution is to read starting from the parent pom of the project and going down to the current project, overwriting the version in memory:
```
<maven.compiler.target>17</maven.compiler.target>
<maven.compiler.source>17</maven.compiler.source>
```

Or the 'maven-compiler-plugin' plugin setting:

```
<plugin>
   <artifactId> maven-compiler-plugin </artifactId>
   <configuration>
       <source>HERE</source>
       <target>HERE</target>
   </configuration>
</plugin>
```
After that, a suitable `jdk is selected` and the assembly of the project begins.
PROFIT

**Comment by javlock** [comment]
[Here is an alternative error with gradle](https://github.com/jitpack/jitpack.io/issues/4881)
I am not good at gradle projects

and my point 3 of this issue refers to maven projects

**Comment by javlock** [comment]
I found the answer, I need to write a config in the repository, but automatic recognition of the java version would also be important for me

https://jitpack.io/docs/BUILDING/#java-version

**Comment by jitpack-io** [comment]
Hi @javlock 

We now have this feature in beta testing where JitPack will attempt to find the version in pom.xml.
Any feedback is appreciated.

**Comment by AndroidDeveloperLB** [comment]
@jitpack-io Any news about this? Do we still have to have the "jitpack.yml" file?
Jitpack used to be so easy to publish to. Just create an Android library and that's it.
Now we need to mess around with settings and files...

Many various weird errors without any explanation of what needs to be done inside of them.
