### ISSUE TITLE
Would be nice to request `git describe --tags` versions

### ISSUE THREAD

**Issue by angryziber** [jitpack/jitpack.io#4893]
**Is your feature request related to a problem? Please describe.**
When testing an unreleased version, it would be much better to specify a `git describe --tags` style version, so that it's more visible where the commit hash is derived from.

E.g. `0.9-16-g7e69ada` is much better than just '7e69ada`.
Docs say that using `master-SNAPSHOT` would result in a `git describe`-style version, e.g. `master-0.9-16-g7e69ada`, however you cannot depend on such version string directly.

**Describe the solution you'd like**
If user requests a version in git describe style e.g. `0.9-16-g7e69ada`, please extract commit hash from it e.g. `7e69ada` and serve that build. Should be easy to implement, as commit hash versions are already supported.

**Describe alternatives you've considered**
The alternative is to use meaningless commit hashes as version numbers.

**Comment by jitpack-io** [comment]
Hi @angryziber ,

Thank you for the suggestion, it would indeed be nicer!
If you use the `main-SNAPSHOT` syntax to build the latest commit then it will get resolved to `git describe` style version.
