### ISSUE TITLE
Build issue Max repo size 250MB exceeded

### ISSUE THREAD

**Issue by sjd753** [jitpack/jitpack.io#4898]
Please provide:

- Link to build log from https://jitpack.io
- https://jitpack.io/com/github/bulldog-dev/aggdirect-android-lens/v2.7.0/build.log

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?
- yes

- What error are you seeing?
- Git error. Retrying.
- Git error. Max repo size 250MB exceeded

Thank you!

**Comment by gouravspyne** [comment]
facing same issue with the paid plan of jitpack.

**Comment by sjd753** [comment]
We're also in paid plan. Still not sure what's the actual problem is and how to solve it. Let me know if you find any clues. @gouravspyne

**Comment by gouravspyne** [comment]
Plan Starter(Individual).

If I pushed the whole code on a different repository then jitpack allows me to create 1-2 releases and the same error occurs after that.
Tried with three different repositories and the same pattern repeats again and again.

**Comment by sjd753** [comment]
is this a problem of Jitpack or github itself? not sure.. either way no solution yet....

**Comment by sjd753** [comment]
@gouravspyne i found a solution for it. i came back to inform you what i did which may also work for you..

To reduce repo size i deleted unneeded branches from the repo and then the build worked for me. Hope it helps you too!
