### ISSUE TITLE
On the website, order tags/releases of a package by creation date.

### ISSUE THREAD

**Issue by lokkju** [jitpack/jitpack.io#49]
Currently, the 'Look Up' feature seems to sort by alphabetical descending, which if you have non-releases related tags can make your release version tags not event show up.

**Comment by jitpack-io** [comment]
You're right the ordering should be improved. At the moment it just displays in the order we get from GitHub api. Somehow that's different than the one displayed on the GitHub website. Needs more investigation...
Perhaps we should just sort by semantic versioning

**Comment by jitpack-io** [comment]
@lokkju Do you have a project where the order looks wrong? Would like to have a closer look

**Comment by lokkju** [comment]
Unfortunately, I deleted the tag that was out of order for my project.  I can find a test case; I'll update this issue when I do.

**Comment by jitpack-io** [comment]
No problem, will find something

**Comment by lokkju** [comment]
I've updated one of my repositories at https://github.com/lokkju/spring-boot-starter-batch-web/releases to demonstrate the issue.  It seems to be a github API problem, as I can't get the API to return them in created order either.
I've contacted support@github.com with the issue, and will update if I hear anything.

**Comment by lokkju** [comment]
I heard back from github, and per them:
> Sorting tags by created_at is not all that possible. Git tags come in two flavors -- lightweight and annotated -- and for the lightweight type Git doesn't store any metadata (like who created the tag and when). For that reason, the best you can do is look at the commit which the tag is pointing to and take that commit's metadata.

>That's basically what we do when we sort tags on github.com -- we take the date of the commit for lightweight tags and the date of the tag for annotated tags. You should be able to use the same approach via the API. You can fetch the date for annotated tags via this endpoint:

>https://developer.github.com/v3/git/tags/#get-a-tag

>We might include an option in the API to sort tags using these rules, but I don't expect that to happen in the near future. The API currently returns tags as they are returned by Git when you run the git tag command.

essentially, it sounds like a "wontfix", and I understand why.  I have a proposed solution...

**Comment by lokkju** [comment]
Since the tags can't be ordered correctly without lots of back and forth, what about just always listing the latest release first?  Github supports this via the API, and it would only add one additional API request:
https://developer.github.com/v3/repos/releases/#get-the-latest-release

**Comment by jitpack-io** [comment]
Sounds great. Let's give it a quick try...

**Comment by jitpack-io** [comment]
Ok, now the website fetches /releases first and if those don't exist then it fetches /tags. Looks better on some projects. Unfortunately the tags are not in the right order 
`curl https://api.github.com/repos/lokkju/spring-boot-starter-batch-web/releases/latest`

**Comment by lokkju** [comment]
It seems you now show built releases first, then just the latest release if a latest release exists, then tags if it doesn't.
This doesn't affect functionality, really, just how it's displayed on the site.  Not sure what the solution should be...

**Comment by jitpack-io** [comment]
Ah yes, if none of the releases were build but another tag was built then it will show that tag. We should look into ordering by version numbers and a lot of projects use semver anyways

**Comment by jitpack-io** [comment]
Now the tags are ordered according to semantic versioning
