### ISSUE TITLE
Build is failing.

### ISSUE THREAD

**Issue by urbanclap-admin** [jitpack/jitpack.io#4902]
Please provide:

- Link to build log from https://jitpack.io

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?

- What error are you seeing?

Thank you!

**Comment by urbanclap-admin** [comment]
Build is failing with error.

Git error. Retrying.
Git error. Max repo size 250MB exceeded

**Comment by gouravspyne** [comment]
Plan Starter(Individual).

If I pushed the whole code on a different repository then jitpack allows me to create 1-2 releases and the same error occurs after that.
Tried with three different repositories and the same pattern repeats again and again.
