### ISSUE TITLE
Max repo size 250MB exceeded

### ISSUE THREAD

**Issue by cherbert** [jitpack/jitpack.io#4903]
`Git error. Retrying.`
`Git error. Max repo size 250MB exceeded`

Please can you explain if this is a limitation for the free version only or paid versions too?

i.e if we subscribe to a paid plan will this restriction be lifted? Or is there some other reason why we are getting this error?!

It's really frustrating that if there are limits why this question isn't answered in the FAQ.

**Comment by gouravspyne** [comment]
facing the same issue with paid plan of jitpack.

**Comment by PratthamArora** [comment]
which plan do you have?
i have Individual plan but facing the same issue

**Comment by PratthamArora** [comment]
> facing the same issue with paid plan of jitpack.

which plan do you have?
i have Individual plan but facing the same issue

**Comment by gouravspyne** [comment]
Plan Starter(Individual).

If I pushed the whole code on a different repository then jitpack allows me to create 1-2 releases and the same problem occurs after that.
Tried with three different repositories and the same pattern repeats again and again.
