### ISSUE TITLE
Jitpack build is failing due to the use of Gradle 4.8.1

### ISSUE THREAD

**Issue by AviranAbady** [jitpack/jitpack.io#4906]
Hello,
The latest version of the Android library [CookieBar2](https://github.com/AviranAbady/CookieBar2) requires JDK 11 and Gradle 7+ (Due to maven central publish plugins)
Jitpack seems to work by default with Gradle 4.8.1

The library repository does not contain any gradle wrapper files (as they are not part of the the project itself and should not be shipped with it)

I have added the file `jitpack.yml` to the root of the project with the following content:
```yaml
jdk:
  - openjdk11
install:
  - gradle wrapper --gradle-version 7.0.2
  - ./gradlew build :cookiebar2:publishToMavenLocal
```

With the purpose to configure JDK11 and generate the correct the Gradle wrapper into the build tools.

Jitpack build process initiates `Gradle 4.8.1` and fails on the first command `gradle wrapper --gradle-version 7.0.2`

With the following error:
```
* Where:
Build file '/home/jitpack/build/build.gradle' line: 21

* What went wrong:
An exception occurred applying plugin request [id: 'io.github.gradle-nexus.publish-plugin', version: '1.1.0']
> Failed to apply plugin [id 'io.github.gradle-nexus.publish-plugin']
   > Could not create an instance of type io.github.gradlenexus.publishplugin.NexusPublishExtension_Decorated.
      > org.gradle.api.provider.Property.value(Ljava/lang/Object;)Lorg/gradle/api/provider/Property;
```

**Link to build log from https://jitpack.io** (Log file has been invalidated by a re-build in a new config - See first comment for details)
https://jitpack.io/com/github/AviranAbady/CookieBar2/1.1.5/build.log

How do I make Jitpack use Gradle v7+ and generate the necessary wrapper?
(Adding those files to the repository is wrong by design, but I have tried that as well and encountered other build errors)

**Comment by AviranAbady** [comment]
A rebuild with new project configuration re-wrote the log. 
The new log display the current state of the master branch, where all the gradle files and wrapper are committed into the project.
Jitpack downloads gradle 7.0.2 but fails due to:

```
* Where:
Build file '/home/jitpack/build/build.gradle' line: 40

* What went wrong:
A problem occurred evaluating root project 'build'.
> Could not read script '/home/jitpack/build/publishing-scripts/publish-root.gradle' as it does not exist.
```

**Comment by jitpack-io** [comment]
Hi

The error seems to be caused by this [line](https://github.com/AviranAbady/CookieBar2/blob/ed24e56/build.gradle#L40)  in build.gradle
`apply from: "${rootDir}/publishing-scripts/publish-root.gradle"`

It appears that 'publishing-scripts' directory does not exist in the git repository.

**Comment by AviranAbady** [comment]
Thanks
