### ISSUE TITLE
Git error. Max repo size 250MB exceeded

### ISSUE THREAD

**Issue by gouravspyne** [jitpack/jitpack.io#4908]
Please provide:

- Link to build log from https://jitpack.io

https://jitpack.io/com/github/gouravspyne/SpyneShootLibrary/6.5/build.log

- What error are you seeing?

Git error. Max repo size 250MB exceeded

Thank you!

**Comment by PratthamArora** [comment]
> Please provide:
> 
> * Link to build log from https://jitpack.io
> 
> https://jitpack.io/com/github/gouravspyne/SpyneShootLibrary/6.5/build.log
> 
> * What error are you seeing?
> 
> Git error. Max repo size 250MB exceeded
> 
> Thank you!

which plan do you have?
i have Individual plan but facing the same issue

**Comment by gouravspyne** [comment]
**Plan	Starter(Individual).**

If I pushed the whole code on a different repository then jitpack allows me to create 1-2 releases and the same problem occurs after that.
Tried with three different repositories and the same pattern repeats again and again.

**Comment by cherbert** [comment]
The lack of support on this is shocking. Even my emails have been ignored.

**Comment by jitpack-io** [comment]
Hi

We are looking into this.

**Comment by jitpack-io** [comment]
@gouravspyne The build has now succeeded https://jitpack.io/com/github/gouravspyne/SpyneShootLibrary/6.5/

If anyone else is facing this issue please delete the old build and retry.

**Comment by cherbert** [comment]
> 

Do we need a paid plan or not to avoid this error?

**Comment by cherbert** [comment]
> @gouravspyne The build has now succeeded https://jitpack.io/com/github/gouravspyne/SpyneShootLibrary/6.5/
> 
> If anyone else is facing this issue please delete the old build and retry.

Do we need a paid plan or not to avoid this error?

**Comment by qyang-nj** [comment]
I see a similar error but with 500MB limit in an open source project.
```
Git error. Retrying.
Git error. Max repo size 500MB exceeded
```

> If anyone else is facing this issue please delete the old build and retry.

It doesn't seem those builds can be deleted :(
