### ISSUE TITLE
Android project build fails everytime -- Subscription is not active right now.

### ISSUE THREAD

**Issue by wonderslate-git** [jitpack/jitpack.io#4912]
**Issue Details:** 
When I pull the release from Github to Jitpack using the Get It button, the build is failing always. This same build runs on my local system. This started happening suddenly since last week. Till build version v0.1.8, publishing through Jitpack from Github was working fine. The moment I pulled v0.1.9 from Github, it started failing every single time. Then when i am checking the previous builds which were successfully built and were available for access are not accessible anymore. They too now are showing error logs, when I open the log file of the previously successful builds. 

**Issue: - Jitpack build log --**
Subscription is not active right now
Requested subscription: github.com/wonderslate-git. 
Your subscriptions are listed in https://jitpack.io/w/user
Please contact Support or repository admins if you need assistance.

**Issue: - Gradle dependency log --**
Could not HEAD 'https://jitpack.io/com/github/wonderslate-git/aiautility/v0.1.7/aiautility-v0.1.7.pom'. Received status code 403 from server: Forbidden

**Things I have checked ---**
Jitpack account subscription page shows "Status -- Inactive" and "Plan -- Starter". I am publishing a Github Release from my Private Github repo and I have not subscribed to a payment model on Jitpack.

**Question ---**
I understand from the error logs that I have used up my quota or space as a free user. But I couldn't find anywhere a metric as to how many builds can I publish being a Starter Pack user. Please can anyone here tell me, how many private repos does Jitpack allow to fetch-build-publish under the Starter Pack?

**Jitpack build log links:**
v0.1.7: https://jitpack.io/com/github/wonderslate-git/aiautility/v0.1.7/build.log
v0.1.9: https://jitpack.io/com/github/wonderslate-git/aiautility/v0.1.9/build.log

**Comment by AmericanaDigiteam** [comment]
we are also facing the same issue.

**Comment by AmericanaDigiteam** [comment]
@jitpack-io  facing the same issue from last 6 days, i am stuck with my work please help here.

**Comment by omwilliams** [comment]
tell ot to police
