### ISSUE TITLE
purejin/8.1 build

### ISSUE THREAD

**Issue by ExE-Boss** [jitpack/jitpack.io#4914]
Please provide:

-	Link to build log from https://jitpack.io
	https://jitpack.io/com/github/jbee/purejin/8.1/build.log

-	Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?
	It built on **GitHub CI** with `./bach build`: <https://github.com/jbee/purejin/runs/1897201818>

-	What error are you seeing?
	```
	ERROR:
	No build file found. Looking for Gradle/Maven/Sbt/Lein build file in the root of the project
	See the documentation at https://jitpack.io/docs/
	```

Thank you!

---

/cc @jbee

**Comment by jbee** [comment]
@ExE-Boss Jitpack is no longer in use. Please grab the release from https://github.com/jbee/purejin/releases.

**Comment by ExE-Boss** [comment]
@jbee But there’s currently no other way to add **GitHub Releases** as a dependency in [**Gradle**](https://gradle.org/)[^1].

[^1]: <https://discuss.gradle.org/t/use-github-releases-as-dependency-repository-plugin/15944>

**Comment by omwilliams** [comment]
If u gd sorry people dont bring my money and leave me alone m going shoot
all of u

**Comment by jbee** [comment]
@ExE-Boss yeah, I guess I decided to not spend more time supporting a broken build tool. If maven and co cannot pickup artefacts from outside of their world maybe what I say is use a build tool that can.

**Comment by omwilliams** [comment]
Go to exeuhell
