### ISSUE TITLE
Git error. Max repo size 500MB exceeded issue

### ISSUE THREAD

**Issue by agorabuilder** [jitpack/jitpack.io#4916]
Hi ,

- [Link to build log from https://jitpack.io](https://jitpack.io/com/github/agorabuilder/native-full-sdk/3.6.1/build.log)

Git error. Retrying.
Git error. Max repo size 500MB exceeded

how can I resolve this issue?

Thank you!

**Comment by jitpack-io** [comment]
Hi

One option is to split your repository and import other modules as dependencies.
Another option is to use Git submodules.

**Comment by inodb** [comment]
@jitpack-io Thanks for your response! Is it correct that jitpack is using the `size` attribute of the github API to determine the repo size?

I have recently used the BFG repo cleaner to clean our repo. This brought the repo size below 70 MB when cloning:

```
Receiving objects: 100% (86358/86358), 66.88 MiB | 8.45 MiB/s, done.
```

But the API still reports `"size": 419143`: https://api.github.com/repos/inodb/cbioportal-frontend. I saw in other places that the `size` field is not very trustworthy. I just want to confirm if this is indeed the field jitpack uses. It's quite a substantial operation to force rewrite the history of a repo, so just want to confirm it's not something we'll have to do again in a couple of months.

**Comment by inodb** [comment]
Actually looks the `size` field just updated. I guess there was some caching related delay

**Comment by illuspas** [comment]
> @jitpack-io Thanks for your response! Is it correct that jitpack is using the `size` attribute of the github API to determine the repo size?
> 
> I have recently used the BFG repo cleaner to clean our repo. This brought the repo size below 70 MB when cloning:
> 
> ```
> Receiving objects: 100% (86358/86358), 66.88 MiB | 8.45 MiB/s, done.
> ```
> 
> But the API still reports `"size": 419143`: https://api.github.com/repos/inodb/cbioportal-frontend. I saw in other places that the `size` field is not very trustworthy

I found a solution,
Go to the project settings, transfer ownership of the project to your organization, or from the organization to you,
And then do the reverse and convert back.
The size returned by the API is refreshed.
