### ISSUE TITLE
Build stuck in "queued" for more than 6h

### ISSUE THREAD

**Issue by paperrose** [jitpack/jitpack.io#4930]
Build for a public repository hosted in github gets stuck in "queued" state (inappstory/android-sdk)
I tried to build three different commits from one branch and one commit from another - no success

**Comment by Abdelmjid-ASOUAB** [comment]
same problems here
any solutions !!

**Comment by jmir1** [comment]
also having this problem right now.
something seems to have gone wrong at jitpack.
will just try again tomorrow...

**Comment by iwbf** [comment]
got the same issue, even tried with a new repo and with new tags
have been waiting for half a day

**Comment by thomashorta** [comment]
same here, no solution or update from @jitpack-io yet?
