### ISSUE TITLE
main-SNAPSHOT not working with Maven

### ISSUE THREAD

**Issue by Tofpu** [jitpack/jitpack.io#4933]
Hello! I'm not really sure what's the reason, as it never worked with me with any of my repos... any help would be really appreciated! 

You can view the repository here: https://github.com/Tofpu/DynamicClass
JitPack link: https://jitpack.io/#Tofpu/DynamicClass

**Comment by Tofpu** [comment]
An update! it works now...? I haven't changed anything. does it take time for the main-SNAPSHOT to work? from what I can remember, every time I tried using said version, it was after 1-2 minutes of building a version on JitPack

**Comment by jitpack-io** [comment]
Hi 

In what sense does it not work for you? Looks like there is a snapshot [build](https://jitpack.io/com/github/Tofpu/DynamicClass/main-b9b6a164bf-1/build.log) available and this command was able to download it:
```
mvn org.apache.maven.plugins:maven-dependency-plugin:2.1:get \
    -DrepoUrl=https://jitpack.io \
    -Dartifact=com.github.Tofpu:DynamicClass:main-SNAPSHOT
```

**Comment by Tofpu** [comment]
I ran a command, and it worked but for some reason, in my IDE maven is not able to recognize it. here's a screenshot:
![image](https://user-images.githubusercontent.com/47629321/150879108-d3a70bec-d9f5-4499-93da-2a4943ccd76f.png)

**Comment by jitpack-io** [comment]
Thanks for that! It seems to be an IDE issue. The jar gets downloaded and is usable but the pom shows it as an error.
Running `mvn package` from command line also shows that the jar is being downloaded.

![image](https://user-images.githubusercontent.com/11161622/151226807-08f1d1bf-3522-46fe-9120-4819b3bdee8e.png)

**Comment by Tofpu** [comment]
Thank you for responding! you're actually right, I ran the `mvn package` command, and it did show up! Do you think I shall forward this issue to Intellij?
