### ISSUE TITLE
I added jitpack.yml but still the build failed.

### ISSUE THREAD

**Issue by jonghenhan** [jitpack/jitpack.io#4934]
I added jitpack.yml for using lambda expression.
But I think it is not working.

I added jitpack.yml like this:
https://github.com/ConnectSDK/Connect-SDK-Android-Core/blob/master/jitpack.yml

Please provide:

- Link to build log from https://jitpack.io
https://jitpack.io/com/github/ConnectSDK/Connect-SDK-Android-Lite/a721e06218/build.log

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?
Not working.

- What error are you seeing?

> Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.github.ConnectSDK:Connect-SDK-Android-Lite:a721e06218.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/github/ConnectSDK/Connect-SDK-Android-Lite/a721e06218/Connect-SDK-Android-Lite-a721e06218.pom
       - https://jcenter.bintray.com/com/github/ConnectSDK/Connect-SDK-Android-Lite/a721e06218/Connect-SDK-Android-Lite-a721e06218.pom
       - https://jitpack.io/com/github/ConnectSDK/Connect-SDK-Android-Lite/a721e06218/Connect-SDK-Android-Lite-a721e06218.pom
     Required by:
         project :app

Thank you!

**Comment by jitpack-io** [comment]
Hi

Looks like the build was using Java 11 
`JVM:          11.0.2 (Oracle Corporation 11.0.2+9)`

**Comment by jonghenhan** [comment]
> Hi
> 
> Looks like the build was using Java 11 `JVM: 11.0.2 (Oracle Corporation 11.0.2+9)`

So how can I build success?

I also add compatibilities like bellow.

compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

It works in Android studio, but not in jitpack.
