### ISSUE TITLE
FAILURE: Build failed with an exception.

### ISSUE THREAD

**Issue by heihitesh** [jitpack/jitpack.io#4943]
[- Link to build log from https://jitpack.io](https://jitpack.io/com/github/AppIntro/appintro/6.2.0/build.log)https://jitpack.io/com/github/AppIntro/appintro/6.2.0/build.log

**Comment by jitpack-io** [comment]
Hi

The yaml should have this structure:
```yaml
jdk:
  - openjdk11
```

**Comment by jitpack-io** [comment]
Latest build was ok with jitpack.yml https://jitpack.io/com/github/AppIntro/appintro/c8f23fb/build.log
