### ISSUE TITLE
(Android)Minimum supported Gradle version is 7.0.2. Current version is 6.7.1.

### ISSUE THREAD

**Issue by kiranshaw-qi** [jitpack/jitpack.io#4944]
Below is the info provided:

- Link to build log from https://jitpack.io
https://jitpack.io/com/github/kiranshaw-qi/Android-CustomKeyboard/1.5.0/build.log

- Error I am seeing? 
_
A problem occurred evaluating project ':app'.
> Failed to apply plugin 'com.android.internal.version-check'.
   > Minimum supported Gradle version is 7.0.2. Current version is 6.7.1. If using the gradle wrapper, try editing the distributionUrl in /home/jitpack/build/gradle/wrapper/gradle-wrapper.properties to gradle-7.0.2-all.zip_

@jitpack-io  How to resolve this issue?
Thank you!

**Comment by jitpack-io** [comment]
Hi @kiranshaw-qi 

You could edit the gradle/wrapper/gradle-wrapper.properties file and change Gradle to 'gradle-7.0.2-all.zip'
We also have an example here https://github.com/jitpack/android-example
