### ISSUE TITLE
Build is failing due to gradle command

### ISSUE THREAD

**Issue by urbanclap-admin** [jitpack/jitpack.io#4945]
Please provide:

- Link to build log from https://jitpack.io
https://jitpack.io/com/github/urbanclap-admin/android-orion/85425a94dc/build.log

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?
 Yes 

- What error are you seeing?
FAILURE: Build failed with an exception.

 What went wrong:
Task 'findArtifacts' not found in root project 'build'.

Thank you!

**Comment by urbanclap-admin** [comment]
please resolve this

**Comment by urbanclap-admin** [comment]
can anyone please look into this?

**Comment by urbanclap-admin** [comment]
tags that were built successfully earlier are also not building now

**Comment by jitpack-io** [comment]
Hi @urbanclap-admin 

Having a look

**Comment by urbanclap-admin** [comment]
getting the following error
and dependency cannot be resolved

build log - https://jitpack.io/com/github/urbanclap-admin/android-orion/36aed8c9d1/build.log


⚠️ ERROR: No build artifacts found
Expected artifacts in: $HOME/.m2/repository/com/github/urbanclap-admin/sailor/unspecified

**Comment by urbanclap-admin** [comment]
> Hi
> 
> Fixed and rebuilt. The build was successful

kindly check this, we have individual plan as well

**Comment by jitpack-io** [comment]
@urbanclap-admin Rebuilt that commit as well.
If there were others that failed we recommend deleting the old build and then re-request it to rebuild.

**Comment by urbanclap-admin** [comment]
it is working fine, you can close this issue
