### ISSUE TITLE
Build failed. No build artifacts found.

### ISSUE THREAD

**Issue by alexander-kulikovskii** [jitpack/jitpack.io#4946]
Please provide:

- Link to build log from https://jitpack.io/by/epicbot/toster/0.2.3/build.log

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?
  **Yes**

- What error are you seeing?
**ERROR: No build artifacts found**

In comparison with [previous build](https://jitpack.io/by/epicbot/toster/0.2.3/build.log), command `build` was missed

Thank you!

**Comment by jitpack-io** [comment]
Hi

Thank you for reporting! The `build` command is now back and the build succeeded.

**Comment by alexander-kulikovskii** [comment]
Thanks a lot!
