### ISSUE TITLE
No build artifacts found

### ISSUE THREAD

**Issue by 880634** [jitpack/jitpack.io#4948]
Please provide:

- Link to build log from https://jitpack.io

[https://jitpack.io/com/github/getActivity/Logcat/10.2/build.log](https://jitpack.io/com/github/getActivity/Logcat/10.2/build.log)

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?

yes

- What error are you seeing?

⚠️ ERROR: No build artifacts found
Expected artifacts in: $HOME/.m2/repository/build/library/unspecified

**Comment by flexable777** [comment]
We also noticed that the OS seems to be downgraded from 4.x to Linux 3.16.0-10-amd64 amd64 in the new failed builds.

**Comment by guness** [comment]
In our case, different version numbers do not matter. We see failure and success on the same version number when we compare an old build log with a new one.

**Comment by guness** [comment]
Update, on this machine it worked:  Linux 3.16.0-10-amd64 amd64

**Comment by jitpack-io** [comment]
Hi all,

Should be fixed now. We've reran some of the builds but you can also delete the old build

**Comment by tdtran** [comment]
@jitpack-io how can we delete the old build? Specifically delete the old **failed** builds so we can rebuild. Same git commit/tag

**Comment by 880634** [comment]
@tdtran Log in to the Github account on the JitPack to delete records of build failures, but this account must be the main account of the current build project

**Comment by 880634** [comment]
@jitpack-io Hello, the problem has been solved. Thank you very much
