### ISSUE TITLE
https://jitpack.io/com/github/JasleenXemplar/TelematicsSDKPOC/v0.0.30/build.log

### ISSUE THREAD

**Issue by JasleenXemplar** [jitpack/jitpack.io#4949]
Please provide:

- Link to build log from https://jitpack.io

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?

- What error are you seeing?

Thank you!

**Comment by jitpack-io** [comment]
Hi @JasleenXemplar 

Rebuilt
https://jitpack.io/com/github/JasleenXemplar/TelematicsSDKPOC/v0.0.30/build.log
