### ISSUE TITLE
Build fails with "no build artifact found"

### ISSUE THREAD

**Issue by tdtran** [jitpack/jitpack.io#4951]
- Link to build log from https://jitpack.io

https://jitpack.io/com/github/tdtran/nextcloud-android-library/221e581f53/build.log

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?

YES

- What error are you seeing?

```
⚠️ ERROR: No build artifacts found
Expected artifacts in: $HOME/.m2/repository/build/unspecified
```

This error seems to happen to every new build of any Android library project, at least to every project I tried.

**Comment by flexable777** [comment]
Same as https://github.com/jitpack/jitpack.io/issues/4948 ?

**Comment by tdtran** [comment]
Probably same issue.

I don't fully understand the meaning of individual items on

https://status.jitpack.io/

"GitHub status" shows solid red bars for the last two days. Even though it still says "Operational"

**Comment by xanscale** [comment]
same here

https://jitpack.io/com/github/xanscale/LocalhostToolkit/6968b82e42/build.log

**Comment by jitpack-io** [comment]
Hi all,

Deployed a fix and rebuilt.

GitHub status is where we query githubstatus.com and the alert triggers if there is any outage. That could be a partial outage so may or may not affect JitPack.

**Comment by tdtran** [comment]
Looks good now. Thanks.
