### ISSUE TITLE
Feature Request : Download stats improvements

### ISSUE THREAD

**Issue by rh-id** [jitpack/jitpack.io#4953]
Currently it seemed there is no way to know if the downloads were from users that use/download the library from their device or from CI ( example github action download library to perform test on a project ).

It would be nice if the download stats somehow able to provide some accuracy in download count. Perhaps exclude download count from known CI IP address like github action IP for example.

**Comment by jitpack-io** [comment]
Hi @rh-id 

This would be a challenge because we do not track where users download the library from and do not log their IP addresses.

**Comment by rh-id** [comment]
Hi @jitpack-io 

Or perhaps adding new repository URL that skip download count?
