### ISSUE TITLE
JitPack is failing to build : Gradle 'publishToMavenLocal' task not found.

### ISSUE THREAD

**Issue by iamramanjot** [jitpack/jitpack.io#4956]
Please provide:

- https://jitpack.io/com/github/EricssonBroadcastServices/EnigmaRiverAndroid/r3.4.0-BETA-3/build.log

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ? Yes it works

- What error are you seeing? : In jitpack logs i see
```
WARNING:
 Gradle 'publishToMavenLocal' task not found. Please add the 'maven-publish' or 'maven' plugin.
 See the documentation and examples: https://jitpack.io/docs/
```

Thank you!

**Comment by iamramanjot** [comment]
@jitpack-io  : Any suggestions for it.

**Comment by iamramanjot** [comment]
Seems like i missed to add maven-publish plugin

**Comment by iamramanjot** [comment]
I have added `maven-publish `plugin but jitpack build didn't find any artifacts

https://jitpack.io/com/github/EricssonBroadcastServices/EnigmaRiverAndroid/r3.4.0-BETA-11/build.log

**Comment by jitpack-io** [comment]
Hi

These changes should fix it https://github.com/EricssonBroadcastServices/EnigmaRiverAndroid/compare/master...jitpack-io:master
JitPack can add the maven-publish plugin automatically but if you'd like to add it yourself then it needs to be applied to each module together with the `publishing` section.

Build with these changes: https://jitpack.io/com/github/jitpack-io/EnigmaRiverAndroid/1e70acd/build.log

**Comment by iamramanjot** [comment]
Great!  Trying it now.

**Comment by iamramanjot** [comment]
Thanks, JitPack! it worked.
