### ISSUE TITLE
jitpack build error

### ISSUE THREAD

**Issue by ichoes** [jitpack/jitpack.io#4957]
Please provide:

- Link to build log from https://jitpack.io
  https://jitpack.io/com/github/evertec/athmovil-android-sdk/4.0.0/build.log

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?
  Did not try to build in my machine. 

- What error are you seeing?
 Cannot use ATHMovil SDK version 4 on Android because there is a build error in Jitpack.

Thank you!

**Comment by jitpack-io** [comment]
Hi

Rebuilt. Our new build scripts succeeded this time.
