### ISSUE TITLE
New build request for `master-SNAPSHOT` of `photo-editor-android`

### ISSUE THREAD

**Issue by mathieumg** [jitpack/jitpack.io#4960]
Please provide:

- **Link to build log from https://jitpack.io**: 
  https://www.jitpack.io/com/github/prscX/photo-editor-android/master-SNAPSHOT/photo-editor-android-master-f5dc1ff4f3-1.pom

- **Does the project build on your machine with **the same** commands (e.g. ./gradlew install)?**
  No changes to that build for many years, seems affected by https://github.com/jitpack/jitpack.io/issues/4948 Cannot force rebuild from website because doesn't have ownership of the repo. See extra context at https://github.com/prscX/react-native-photo-editor/issues/181#issuecomment-1027315774

- **What error are you seeing?**
  > Build failed. See the log at jitpack.io

Thank you!

**Comment by jitpack-io** [comment]
Hi

Should work with newer gradle https://github.com/jitpack-io/photo-editor-android/commit/d545d22efa042f75bb08e60bda7c3e2b2c3f6fc1

Build: https://jitpack.io/com/github/jitpack-io/photo-editor-android/d545d22/build.log

**Comment by mark-hayward** [comment]
Is there something we can do to fix this? The gradle in my project and the build.gradle in react-native-photo-editor already have versions of gradle higher than the ones in the commit above.

**Comment by jitpack-io** [comment]
Hi @mark-hayward ,
Which project is it? In addition to Gradle `com.android.tools.build:gradle` needs to be version '3.6.0' or greater.

**Comment by mathieumg** [comment]
The solution in this comment worked, I don't know if it can help identify the underlying cause or if it's due to a change in the tooling: https://github.com/prscX/react-native-photo-editor/issues/181#issuecomment-1027987736
