### ISSUE TITLE
Received status code 403 from server: Forbidden and Dependencies are not working

### ISSUE THREAD

**Issue by BongoJitpack** [jitpack/jitpack.io#4968]
**Describe the bug**
Could not GET 'https://www.jitpack.io/com/bongobd/gitlab/Modules/BongoExoplayer/2.2.11/BongoExoplayer-2.2.11.pom'. Received status code 403 from server: Forbidden

**To Reproduce**
Just simply implement the android library with authentication code given for private repo, run the project, and shows this error. It was working for the last 3/4 months but suddenly we are facing this. 

**Expected behavior**
As I have had the subscription for a year, I believe the expected behavior should be working and running the app properly. 

**Screenshots**
![Screen Shot 2022-02-09 at 11 36 35 AM](https://user-images.githubusercontent.com/89194553/153128463-21b7dab5-bfff-402c-bb0e-690f3307c629.png)

**Additional context**
I need an email or a person directly about some issues I have faced the last few days with the jitpack implementation as well. If it's possible to have someone to talk is much appriciated.

**Comment by BongoJitpack** [comment]
@jitpack-io for your concern.

**Comment by jitpack-io** [comment]
Hi @BongoJitpack 

This seems like a subscription issue. Currently the subscription is for 'gitlab.bongobd.com:mobile-dev' however the request is trying to access 'gitlab.bongobd.com/modules'.
If you prefer we can transfer the subscription but in the meantime we eneabled a free trial for two weeks.
