### ISSUE TITLE
sql2o/0.2.9 build

### ISSUE THREAD

**Issue by salbito** [jitpack/jitpack.io#497]
Log https://jitpack.io/com/github/aaberg/sql2o/0.2.9/build.log

**Comment by jitpack-io** [comment]
Hi

That version appears to be old and doesn't have any build files. The newer builds fine:
https://jitpack.io/#aaberg/sql2o/sql2o-1.5.4

`compile 'com.github.aaberg.sql2o:sql2o:sql2o-1.5.4'`
