### ISSUE TITLE
Custom domain not working when use third-level domain.

### ISSUE THREAD

**Issue by qyl27** [jitpack/jitpack.io#4981]
**Describe the bug**
My domain is for some different studios. Every studio has a GitHub Organize.
I want to use the subdomain in the JitPack custom domain feature.
I had set the TXT record in `git.<My organize name>.<My domain>.<TLD> to https://github.com/<My organize>`. 
But JitPack shows me the Repository not found. 
And it seems that it tried to find the repo in `https://<My domain>.<TLD>/<My organize name>/<Repo name>`.

**To Reproduce**
1. Go to Cloudflare set the TXT record.
2. Input `<My organize name>.<My domain>.<TLD>/<Repo name>` to JitPack's 'Look up' text field.
3. Repository not found: `https://<My domain>.<TLD>/<My organize name>/<Repo name>`.

**Expected behavior**
It should be that JitPack searches my repo in the correct organize.

**Comment by jitpack-io** [comment]
Hi

Could you please re-try? This feature should now be available.
If it doesn't seem to work please send us the domain name via Support button on jitpack.io
