### ISSUE TITLE
No version of NDK matched the requested version

### ISSUE THREAD

**Issue by adxcorp** [jitpack/jitpack.io#4989]
Please provide:

- Link to build log from [https://jitpack.io/com/github/adxcorp/ADXLibrary_Android/2.0.9-beta2/build.log](https://jitpack.io/com/github/adxcorp/ADXLibrary_Android/2.0.9-beta2/build.log)

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ? YES

- What error are you seeing?

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':adx-library:adx-library-pangle:stripDebugDebugSymbols'.
> No version of NDK matched the requested version 22.1.7171670. Versions available locally: 21.1.6352462

```

See the link below. Same commit but build succeeded.
[https://jitpack.io/com/github/adxcorp/ADXLibrary_Android/2.0.9-beta1/build.log](https://jitpack.io/com/github/adxcorp/ADXLibrary_Android/2.0.9-beta1/build.log)

Sometimes it succeeds and sometimes it fails even if the NDK version doesn't change.
What is the cause?

Thank you!

**Comment by jitpack-io** [comment]
Hi

If your build requires a specific NDK version we recommend using custom build commands:
https://docs.jitpack.io/building/#custom-commands

to install NDK using `sdkmanager`.
