### ISSUE TITLE
`sodium-fabric` fails to build

### ISSUE THREAD

**Issue by minerva** [jitpack/jitpack.io#4991]
The `mc1.18.1-0.4.0-alpha6` tag of `sodium-fabric` currently fails to build due to an outdated version of Java (`8` to be specific).
This strikes me as strange considering `sodium-fabric`'s `jitpack.yml` specifies `OpenJDK-17`.

- Link to build log: https://jitpack.io/com/github/CaffeineMC/sodium-fabric/mc1.18.1-0.4.0-alpha6/build.log

- The referenced tag does build on my local machine

**Comment by jitpack-io** [comment]
Hi @minerva 

Should work with this syntax: 
```
jdk:
  - openjdk17
```
