### ISSUE TITLE
Build is unable to connect to archive.apache.org

### ISSUE THREAD

**Issue by hufman** [jitpack/jitpack.io#4995]
I've been very satisfied with Jitpack since I started using it last year! However, a recent code change (last commit was in November) has been unable to compile, because the build box is unable to download a dependency from archive.apache.org. I've been trying since yesterday and it hasn't seemed to improve.

First attempt: https://jitpack.io/io/bimmergestalt/IDriveConnectKit/conditional-runtime-0.3-ge7f6b8e-1/build.log
Most recent attempt: https://jitpack.io/io/bimmergestalt/IDriveConnectKit/conditional-runtime-0.3-g8b47bca-1/build.log
```
> Task :downloadEtchCompiler
Download https://archive.apache.org/dist/etch/1.4.0/apache-etch-1.4.0-windows-x86-bin.zip

> Task :downloadEtchCompiler FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':downloadEtchCompiler'.
> de.undercouch.gradle.tasks.download.org.apache.http.conn.ConnectTimeoutException: Connect to archive.apache.org:443 [archive.apache.org/138.201.131.134] failed: connect timed out
```

It builds fine locally, and I can successfully curl the same URL (resolving to the same IP) from my home:
```
$ curl -i https://archive.apache.org/dist/etch/1.4.0/apache-etch-1.4.0-windows-x86-bin.zip
HTTP/1.1 200 OK
Date: Fri, 25 Feb 2022 15:32:35 GMT
Server: Apache
Last-Modified: Fri, 20 Jun 2014 13:44:01 GMT
ETag: "b176a8-4fc44af9b2a40"
Accept-Ranges: bytes
Content-Length: 11630248
Content-Type: application/zip
```

Github Actions was having occasional connection errors to this host yesterday too, but it seems to be working today.

I know network routing troubles are hard to debug, but hopefully this clue can help figure out a problem!

**Comment by hufman** [comment]
Here's Github Actions running the same build: https://github.com/BimmerGestalt/IDriveConnectKit/runs/5335319741?check_suite_focus=true

**Comment by jitpack-io** [comment]
Hi

It seems JitPack servers might have been banned due to many requests.
