### ISSUE TITLE
ERROR: No build artifacts found

### ISSUE THREAD

**Issue by neonMichal** [jitpack/jitpack.io#4997]
Please provide:

- Link to build log from https://jitpack.io

https://jitpack.io/org/bitbucket/neoncubehq/itv-android-sdk/1.9.16.1-tm/build.log

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?

Yes

- What error are you seeing?

ERROR: No build artifacts found
Expected artifacts in: $HOME/.m2/repository/build/itvandroidsdk/unspecified

Any assistance would be appreciated.

**Comment by jitpack-io** [comment]
Hi

We recommend running the same command locally:
`./gradlew clean -Pgroup=org.bitbucket.neoncubehq -Pversion=1.9.16.1-tm -xtest -xlint assemble publishToMavenLocal`

to see if artifacts get installed into `$HOME/.m2` directory. JitPack will look for artifacts there.
