### ISSUE TITLE
"Could not find artifact" on old version - jitpack build log is okay

### ISSUE THREAD

**Issue by laura-dietz** [jitpack/jitpack.io#4999]
Earlier versions of my library seem to be not available for mvn.

When a user aims to use those in their pom.xml , they obtain this error

    Could not find artifact com.github.TREMA-UNH:trec-car-tools-java:jar:13 in jitpack.io (https://jitpack.io) -> [Help 1]

No problem when I switch to more recent versions (16...19)

Please provide:

- Link to build log from https://jitpack.io

https://jitpack.io/com/github/TREMA-UNH/trec-car-tools-java/13/build.log

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?

Yes. ` mvn compile` on version 13  -- build success  (the jitpack log also does not imply any issues)

- What error are you seeing?

When building a project that uses version 13, I obtain the following error

```
[WARNING] The POM for com.github.TREMA-UNH:trec-car-tools-java:jar:13 is missing, no dependency information available

[ERROR] Failed to execute goal on project treccar-tools-example: Could not resolve dependencies for project edu.unh.cs.treccar:treccar-tools-example:jar:0.1: Failure to find com.github.TREMA-UNH:trec-car-tools-java:jar:13 in https://jitpack.io was cached in the local repository, resolution will not be reattempted until the update interval of jitpack.io has elapsed or updates are forced -> [Help 1]
```
(full error log below)

To reproduce:
```
git clone git@github.com:TREMA-UNH/trec-car-tools
cd trec-car-tools/trec-car-tools-example
checkout v13-jitpack-issue
mvn compile
```

Thank you!

Full error log

Picked up JAVA_TOOL_OPTIONS: -Xmx256m
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for edu.unh.cs.treccar:treccar-tools-example:jar:0.1
[WARNING] 'dependencies.dependency.version' for org.jetbrains:annotations-java5:jar is either LATEST or RELEASE (both of them are being deprecated) @ line 37, column 22
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO] 
[INFO] --------------< edu.unh.cs.treccar:treccar-tools-example >--------------
[INFO] Building treccar-tools-example 0.1
[INFO] --------------------------------[ jar ]---------------------------------
[WARNING] The POM for com.github.TREMA-UNH:trec-car-tools-java:jar:13 is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.294 s
[INFO] Finished at: 2022-03-02T20:18:37-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project treccar-tools-example: Could not resolve dependencies for project edu.unh.cs.treccar:treccar-tools-example:jar:0.1: Failure to find com.github.TREMA-UNH:trec-car-tools-java:jar:13 in https://jitpack.io was cached in the local repository, resolution will not be reattempted until the update interval of jitpack.io has elapsed or updates are forced -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
-bash-5.1$

**Comment by jitpack-io** [comment]
Hi

Could you please retry?
