### ISSUE TITLE
LceBinding/1.0.0 build

### ISSUE THREAD

**Issue by talenguyen** [jitpack/jitpack.io#500]
Log https://jitpack.io/com/github/talenguyen/LceBinding/1.0.0/build.log

**Comment by jitpack-io** [comment]
Hi

Is there still an issue with this build? Looks like it succeeded the last time

**Comment by talenguyen** [comment]
At the moment when I ran the build it's failed, cause by can't download the com.github.kt3k.coveralls. But, it's OK now.
