### ISSUE TITLE
Bug: release is supposed to be identical to commit, but it fails to be used, while commit is fine

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [jitpack/jitpack.io#5001]
Please provide:

- Link to build log from https://jitpack.io
https://jitpack.io/com/github/AndroidDeveloperLB/FastScrollerAndRecyclerViewFixes/7/build.log
https://jitpack.io/com/github/AndroidDeveloperLB/FastScrollerAndRecyclerViewFixes/622b3163b7/build.log

Repository:
https://github.com/AndroidDeveloperLB/FastScrollerAndRecyclerViewFixes

I've made a release out of a commit, but the commit works fine when I use it, and yet the release gave me errors...

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?
No, except for the commit one, which is fine.

- What error are you seeing?

```
Welcome to Gradle 7.2!

Here are the highlights of this release:
 - Toolchain support for Scala
 - More cache hits when Java source files have platform-specific line endings
 - More resilient remote HTTP build cache behavior

For more details see https://docs.gradle.org/7.2/release-notes.html

Starting a Gradle Daemon, 2 incompatible and 3 stopped Daemons could not be reused, use --status for details

FAILURE: Build failed with an exception.

* What went wrong:
Task 'install' is ambiguous in root project 'ContactsSync'. Candidates are: 'installDebug', 'installDebugAndroidTest', 'installRelease'.
```

**Comment by AndroidDeveloperLB** [comment]
@jitpack-io I tried yesterday to update it, and for some reason the commit works fine, yet the release still doesn't:

https://jitpack.io/#AndroidDeveloperLB/FastScrollerAndRecyclerViewFixes/7

https://jitpack.io/#AndroidDeveloperLB/FastScrollerAndRecyclerViewFixes/622b3163b7

They are identical, so I expect them both to work fine.

**Comment by jitpack-io** [comment]
Hi

If a tag was built more than 7 days ago then it becomes frozen on JitPack even if the git commit changes.
We recommend creating a new release in these cases.
