### ISSUE TITLE
ERROR: No build artifacts found

### ISSUE THREAD

**Issue by lyqiai** [jitpack/jitpack.io#5003]
Please provide:

- Link to build log from https://jitpack.io
https://jitpack.io/com/github/lyqiai/imagepicker/0.0.1/build.log
- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?
yes
I:\imagepicker>gradlew -Pgroup=com.github.lyqiai -Pversion=0.0.1 publishToMavenLocal

BUILD SUCCESSFUL in 1s
24 actionable tasks: 3 executed, 21 up-to-date

- What error are you seeing?
Build starting...
Start: Thu Mar 10 02:15:20 UTC 2022 50bf09737320
Git:
0.0.1-0-g3e2294b
commit 3e2294b42b90773cbccfc733d667a09df021c352
Author: JMS\liuyanqi 
Date:   Thu Mar 10 10:09:29 2022 +0800

    移除string资源

Init SDKMan
Found Android manifest
Android SDK version: 30. Build tools: 30.0.3
Installing Android platform 30
Installing Build-tools 30.0.3 
Found gradle
Gradle build script
Found gradle version: 6.5.
Using gradle wrapper
/script/gradleb.sh: line 102: ./gradlew: cannot execute binary file: Exec format error
Getting tasks: ./gradlew tasks --all
0m0.001s
Tasks: 

 ⚠️   WARNING:
 Gradle 'publishToMavenLocal' task not found. Please add the 'maven-publish' or 'maven' plugin.
 See the documentation and examples: https://docs.jitpack.io

/script/gradleb.sh: line 162: ./gradlew: cannot execute binary file: Exec format error
Running: ./gradlew -Pgroup=com.github.lyqiai -Pversion=0.0.1 publishToMavenLocal
/script/gradleb.sh: line 181: ./gradlew: cannot execute binary file: Exec format error
/script/gradleb.sh: line 182: ./gradlew: cannot execute binary file: Exec format error
Build tool exit code: 0
Looking for artifacts...
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2
Looking for pom.xml in build directory and ~/.m2
2022-03-10T02:15:44.593160423Z
Exit code: 0

⚠️ ERROR: No build artifacts found

Thank you!

**Comment by jitpack-io** [comment]
Hi

There seems to be a problem with `gradlew` script on Linux.
`./gradlew: cannot execute binary file: Exec format error`

Would recommend re-generating the wrapper and committing to git.

**Comment by lyqiai** [comment]
tk
