### ISSUE TITLE
failed to resolve com.github.yangjie10930:EpMedia:v1.0.1

### ISSUE THREAD

**Issue by NamrataMcode** [jitpack/jitpack.io#5007]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jitpack-io** [comment]
Hi

"failed to resolve" could be caused my multiple different errors.
We recommend running gradle from command line with the `--info` to get more details and the specific error.
