### ISSUE TITLE
Can any lib with aar be released?

### ISSUE THREAD

**Issue by ZXHHYJ** [jitpack/jitpack.io#5011]
Build starting...
Start: Wed Mar 16 16:25:57 UTC 2022 0dda4d929250
Git:
1.0.0-0-g1344162
commit 134416204fe715a6d25ae76162265d35ecd8d7c3
Author: liuxiaoliu66 
Date:   Thu Mar 17 00:14:28 2022 +0800

    使用新的toolkit工具包实现高斯模糊

Init SDKMan
Found Android manifest
Android SDK version: . Build tools: 
Running install command:
./gradlew :library:build :library:publishToMavenLocal;find . -name "*.aar"
./library/libs/renderscript-toolkit-release.aar
Build tool exit code: 0
Looking for artifacts...
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2
Looking for pom.xml in build directory and ~/.m2
2022-03-16T16:26:00.202324691Z
Exit code: 0

⚠️ ERROR: No build artifacts found

I don't plan to carry this aar.
` compileOnly fileTree(include: ['*.?ar'], dir: 'libs')`

**Comment by jitpack-io** [comment]
Hi

If you have additional '.aar' files in your repository then they can be released.
The '.aar' and corresponding '.pom' file need to be installed into $HOME/.m2 as maven artifacts.
The same '.pom' file also needs to be placed in the Git repository so that JitPack can find its coordinates.

**Comment by ZXHHYJ** [comment]
I solved it after migrating the model to a new project, and I don't know the specific reason. puzzling
