### ISSUE TITLE
VERSION environment variable appears to be overwritten by sdkman

### ISSUE THREAD

**Issue by quotidian-ennui** [jitpack/jitpack.io#5012]
**Describe the bug**
According to the docs `VERSION` is set as an environment variable indicating the TAG/COMMIT being built c.f https://docs.jitpack.io/building/#build-environment

However, if you have a custom java installed via sdkman, this env-var is set to be the java version that is being used.

**To Reproduce**

Configure a custom java version via sdkman; in this case we use GraalVM 22 (Java11).

```
before_install:
  - sdk install java 22.0.0.2.r11-grl
  - sdk use java 22.0.0.2.r11-grl
  - env
```

**Expected behavior**

- VERSION env var should be `branch-commithash` or in this specific case `develop-f05112460f-1`

It's relatively easy to work-around but either the documentation is "wrong" or it's a bug.

**Additional context**

- For additional context as to why the VERSION is expected to be `branch-commithash` see https://raw.githubusercontent.com/monkbond/graalvm-binding/f05112460fccf67c0a748bbd16c93d5bb9ef72e6/build.gradle 

The log extract from the build associated with f05112460f is below; otherwise see https://jitpack.io/com/github/monkbond/graalvm-binding/develop-f05112460f-1/build.log if it hasn't been overwritten.

```
Using java version 22.0.0.2.r11-grl in this shell.
BEFORE_INSTALL_CMD=sdk install java 22.0.0.2.r11-grl;sdk use java 22.0.0.2.r11-grl;env
... // skipped for brevity
JAVA_HOME=/home/jitpack/.sdkman/candidates/java/22.0.0.2.r11-grl
VERSION=22.0.0.2.r11-grl
... // skipped for brevity
JITPACK=true
_=/usr/bin/env
Found gradle
Gradle build script
Found gradle version: 7.1.
Using gradle wrapper
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2
...
Running: ./gradlew clean -Pgroup=com.github.monkbond -Pversion=develop-f05112460f-1 -xtest assemble publishToMavenLocal
...
Archive: com.github.monkbond:graalvm-binding:22.0.0.2.r11-grl
Publication: com.github.monkbond:graalvm-binding:22.0.0.2.r11-grl
```

**Comment by jitpack-io** [comment]
Hi @quotidian-ennui 

Thank you for reporting this!
We will now reset the VERSION variable after `before_install` commands.
Good news is that the gradle build itself was able to pick up the correct version:
`./gradlew clean -Pgroup=com.github.monkbond -Pversion=develop-f05112460f-1 -xtest assemble publishToMavenLocal`

**Comment by quotidian-ennui** [comment]
Thanks for fixing, in the end I'm just reusing the `-Pversion=` to handle versioning.
