### ISSUE TITLE
Subscription is not active right now

### ISSUE THREAD

**Issue by Ruaridh-Waire-Health** [jitpack/jitpack.io#5027]
**Describe the bug**
Although our company Git Account pays for a subscription, we can no longer pull our private repositories into projects.

Could not GET '[https://jitpack.io/com/github/WaireHealth/Android-C-Detect-SDK/1.2.0/Android-C-Detect-SDK-1.2.0.pom'.](https://jitpack.io/com/github/WaireHealth/Android-C-Detect-SDK/1.2.0/Android-C-Detect-SDK-1.2.0.pom%27.) Received status code 403 from server: Forbidden
Disable Gradle 'offline mode' and sync project

**To Reproduce**

https://jitpack.io/com/github/WaireHealth/Android-C-Detect-SDK/1.2.0/Android-C-Detect-SDK-1.2.0.pom%27
Accessing the above url give the following message:

**Subscription is not active right now
Requested subscription: github.com/wairehealth. 
Your subscriptions are listed in https://jitpack.io/w/user
Please contact Support or repository admins if you need assistance.**

We have double checked our subscription through our organisation git account, but it claims our status is inactive.
We have been paying for JitPack for the last few months, payment is still valid as we got a confirmation of this.

**Expected behavior**
The current payed for subscription should allow access to our private repository

**Comment by Ruaridh-Waire-Health** [comment]
@jitpack-io If you could please look into this as soon as possible, this is a business critical issue.

**Comment by ft-android-sdk** [comment]
@Ruaridh-Waire-Health we are facing the same issue:
https://github.com/jitpack/jitpack.io/issues/5034

**Comment by josevsq1** [comment]
Same issue here. Honestly I can't understand how this is happening. No proper solution on their side, no answers, no anything.
