### ISSUE TITLE
same issue! how to fix it!!!

### ISSUE THREAD

**Issue by JeremyVic** [jitpack/jitpack.io#5048]
I already purchased a subscription from jitpack and it's active in their portal but still getting this issue.

Subscription is not active right now
Requested subscription: bitbucket.org/egoteamapp. 
Your subscriptions are listed in https://jitpack.io/w/user
Please contact Support or repository admins if you need assistance.

_Originally posted by @umarpazir11 in https://github.com/jitpack/jitpack.io/issues/2492#issuecomment-898399297_

**Comment by aleksandr-usov** [comment]
Same issue

**Comment by priyankagupta-ITT** [comment]
Please update the solution here
