### ISSUE TITLE
Package does not exist

### ISSUE THREAD

**Issue by cech12** [jitpack/jitpack.io#5068]
Please provide:

- Link to build log: https://jitpack.io/com/github/cech12/bucketlib/1.18.2-0.5.3.0/build.log 

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install)? 
Yes. 

- What error are you seeing?
Multiple errors like: `error: package net.minecraft.core does not exist`

I don't know why the packages cannot be found in your environment. Maybe it is a caching issue?  

Thank you!

**Comment by JManikiza** [comment]
Hey man! I know this is a long time ago but did you fix this and how? 

I've tried everything and its all successful my side just JitPacks side

**Comment by cech12** [comment]
Sorry but I cannot remember^^ Maybe setting the exact Java version fixed some issues in the past and I use the assemble task Gradle. But I don't know if that is needed any longer^^
https://github.com/cech12/BucketLib/blob/1.21/jitpack.yml
