### ISSUE TITLE
[⚡Gradle 7 support] - Build successful but no artifact found

### ISSUE THREAD

**Issue by ErrorxCode** [jitpack/jitpack.io#5075]
My build was successful but still, it failed to create an `artifact` and exited with an error status of 0.

Build logs: https://jitpack.io/com/github/ErrorxCode/WebWorker/test2/build.log
Source code: https://github/ErrorxCode/WebWorker

**Comment by gringofe** [comment]
Hi there, having the same error. When you are using Gradle 7, jitpack runs the gradle tasks `assemble` and ` publishToMavenLocal`, which do not seem to work properly(?), whereas on Gradle 6, only `install` is run. So I downgraded to Gradle 6 and now it works.

**Comment by ErrorxCode** [comment]
Thanks for the solution but I can't downgrade gradle due to the android compatibility issue. I hope Jitpack will fix this soon.

**Comment by gringofe** [comment]
maybe you could try to somehow override or extend the `publishToMavenLocal` task to make it run the `install` task?

**Comment by ErrorxCode** [comment]
Wired! I tried to build the project again and this time it worked. 
Miracle log link: https://jitpack.io/com/github/ErrorxCode/WebWorker/test3/build.log

**Might be an issue with my release, I created a new release after updating files and it worked**
