### ISSUE TITLE
 Gradle 'publishToMavenLocal' task not found.  

### ISSUE THREAD

**Issue by 1181631922** [jitpack/jitpack.io#5078]
Please provide:

- Link to build log from https://jitpack.io
- https://jitpack.io/com/github/fanyafeng/ripple_log/0.0.6/build.log

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?
**In my laptop, I can execute "./gradlew ripple_log:publishReleasePublicationToMavenLocal" and succeed, but I can not publish in jitpack**
Welcome to Gradle 7.3.3!

Here are the highlights of this release:
 - Easily declare new test suites in Java projects
 - Support for Java 17
 - Support for Scala 3

For more details see https://docs.gradle.org/7.3.3/release-notes.html

Starting a Gradle Daemon, 2 incompatible Daemons could not be reused, use --status for details

> Configure project :app
Unable to detect AGP versions for included builds. All projects in the build should use the same AGP version. Class name for the included build object: org.gradle.composite.internal.DefaultIncludedBuild$IncludedBuildImpl_Decorated.
app: 'annotationProcessor' dependencies won't be recognized as kapt annotation processors. Please change the configuration name to 'kapt' for these artifacts: 'androidx.room:room-compiler:2.4.2'.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.3.3/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 11s
25 actionable tasks: 25 executed

- What error are you seeing?

Thank you!

**Comment by ErrorxCode** [comment]
Always include your own **gradle files and wrapper** for more success rate. See [this](https://github.com/ErrorxCode/EasyInsta) repo for example.

**Comment by 1181631922** [comment]
> Always include your own **gradle files and wrapper** for more success rate. See [this](https://github.com/ErrorxCode/EasyInsta) repo for example.

I saw your module, my module is android module, it is not the same with yours and my module can build and publish in my laptop, may be the mistake is different from yours
