### ISSUE TITLE
401 from jitpack server for my github public build

### ISSUE THREAD

**Issue by walec51** [jitpack/jitpack.io#51]
Hi,

I've created this release form my fix to Spring Data Cassandra:
https://jitpack.io/#walec51/spring-data-cassandra/DATACASS-182-fix

copy-pasted the right gradle code, but when I try to build I get:

```
:order-service:compileJava

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all dependencies for configuration ':order-service:compile'.
> Could not resolve com.github.walec51:spring-data-commons:DATACASS-182-fix.
  Required by:
      pl.allegro.transaction.order:order-service:0.7.2-SNAPSHOT > com.github.walec51:spring-data-cassandra:DATACASS-182-fix
   > Could not GET 'https://jitpack.io/com/github/walec51/spring-data-commons/DATACASS-182-fix/spring-data-commons-DATACASS-182-fix.pom'. Received status code 401 from server: Repository not found or requires authentication
```

**Comment by jitpack-io** [comment]
Thanks for the report! Looking into it

**Comment by jitpack-io** [comment]
Ok, fixed the problem with dependencies. Unfortunately looks like there's a compilation error:
https://jitpack.io/com/github/walec51/spring-data-cassandra/DATACASS-182-fix/build.log

**Comment by walec51** [comment]
this is strange because I actualy fixed that compilation error in that branch

**Comment by walec51** [comment]
I've created another release to make sure:
https://jitpack.io/#walec51/spring-data-cassandra/DATACASS-182-2
and again I've got 401

**Comment by jitpack-io** [comment]
Oh right, probably because that release was created before our fix. Rebuilt it now and and the artifacts appear to be in place. Tried it in a maven build and it could download them.
How does it look now? Maven might need the `-U` switch to redownload dependencies.

**Comment by walec51** [comment]
The build for my second release seams to be ok:
https://jitpack.io/com/github/walec51/spring-data-cassandra/DATACASS-182-2/build.log

But when I try to get:
https://jitpack.io/com/github/walec51/spring-data-commons/DATACASS-182-fix/spring-data-commons-DATACASS-182-2.pom

I still get a 401 error - the same one I've got in the previous release.

**Comment by jitpack-io** [comment]
Yes, the url in the first error message was wrong. spring-data-commons module does not exist in this project so it returns 401. Currently spring-data-cassandra depends on spring-data-commons but it downloads it from maven central.

If you add the dependency then it should download both:
`compile 'com.github.walec51:spring-data-cassandra:DATACASS-182-fix`

**Comment by walec51** [comment]
I don't understand, I'm still getting 401 on both releasex
all the dependencies are correct, there is a:
		<dependency>
			<groupId>${project.groupId}</groupId>
			<artifactId>spring-data-commons</artifactId>
			<version>${springdata.commons}</version>
		</dependency>
in spring-data-cassandra

**Comment by jitpack-io** [comment]
Indeed and ${project.groupId} is set to org.springframework.data so it won't be downloaded from JitPack. JitPack only handles com.github.* groups. Instead gradle will look in `mavenCentral()` assuming it is added to your build.gradle.

Btw, did you want to use a fork spring-data-commons as well? Its possible but then you'd need to replace the ${project.groupId} with 'com.github.walec51'.

The errors might be due to some errors being cached so maybe deleting ~/.gradle/caches will help. 
Gradle should be downloading this file:
https://jitpack.io/com/github/walec51/spring-data-cassandra/DATACASS-182-2/spring-data-cassandra-DATACASS-182-2.pom
Does it open for you?

Is your build file is on GitHub somewhere? It might make it easier to pinpoint your issue.

**Comment by walec51** [comment]
it worked for com.github.walec51:spring-data-cassandra:DATACASS-182-2 now
thanks !

**Comment by jitpack-io** [comment]
Fantastic! Sorry for the confusion : )

**Comment by walec51** [comment]
also I created another release and no problems happened this time
thanks for the help and a great tool :)

**Comment by jitpack-io** [comment]
Even better! Happy building!:)
