### ISSUE TITLE
android-flowlayout/java-fowlayout-1.9 build

### ISSUE THREAD

**Issue by Ajibola** [jitpack/jitpack.io#513]
Log https://jitpack.io/com/github/rmarau/android-flowlayout/java-fowlayout-1.9/build.log

unable to add this repo.

**Comment by Ajibola** [comment]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':libraries:layouts:signArchives'.
> Cannot perform signing task ':libraries:layouts:signArchives' because it has no configured signatory

**Comment by jitpack-io** [comment]
Hi

The maintainers would need to change their build to skip signing.
