### ISSUE TITLE
How can I set the version of jitpack's compiler?

### ISSUE THREAD

**Issue by zly2006** [jitpack/jitpack.io#5146]
Please provide:

I need java17 to build my program, but jitpack uses 1.8 to build it.

Here's that release.

<https://github.com/zly2006/KookyBot/releases/tag/0.1.1-SNAPSHOT>

Thank you!

**Comment by nostra** [comment]
You need a "jitpack.ym" file to indicate java version. For details, see #5128

**Comment by zly2006** [comment]
Thank you, it works.
