### ISSUE TITLE
Tag moved from one commit to another one doesn't reset the tag build status

### ISSUE THREAD

**Issue by SIMULATAN** [jitpack/jitpack.io#5149]
- Link to build log from https://jitpack.io
https://jitpack.io/com/github/black0nion/pagination-utils/3.1.0/build.log

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?
Yes

- What error are you seeing?
Wrong java version

I pushed my code to GitHub, tagged it (in this case: with `3.1.0`), and found out that because I used java 17 features the build was failing on JitPack. To fix this, I created a `jitpack.yml` file with the right java version, and amended the previous commit. I then removed the tag from the previous commit, and added it to the new one, but because the tag was already built on JitPack (on the old commit), I couldn't get it to re-build on the new commit that now has the tag.

[The `3.1.0` tag in my repo](https://github.com/Black0nion/Pagination-Utils/releases/tag/3.1.0) - you can see that it is on the commit `de2683d`, however, in the [build log of the `3.1.0` tag](https://jitpack.io/com/github/black0nion/pagination-utils/3.1.0/build.log), it shows that it's built on the old commit.

<details>
<summary>Build Log of the old commit</summary>
<small>The link provided probably won't work as soon as the build status gets reset manually (which I hope for)</small>

	  Build starting...
	  Start: Mon Jul 11 18:48:18 UTC 2022 0cb65f58614a
	  Git:
	  3.1.0-0-gcb5adc7
	  commit cb5adc7ff24a95f66f1ba2b5845066d9f8a4e03b
	  Author: SIMULATAN 
	  Date:   Mon Jul 11 20:43:56 2022 +0200

	      Update to JDA 5.0.0-alpha.13
	  
	  Init SDKMan
	  Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2
	  Unrecognized option: --add-opens
	  Error: Could not create the Java Virtual Machine.
	  Error: A fatal exception has occurred. Program will exit.
	  
	  Running: mvn clean install -DskipTests
	  
	  Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2
	  Unrecognized option: --add-opens
	  Error: Could not create the Java Virtual Machine.
	  Error: A fatal exception has occurred. Program will exit.
	  Build tool exit code: 0
	  Looking for artifacts...
	  Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2
	  Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2
	  Looking for pom.xml in build directory and ~/.m2
	  Found artifact: com.github.ygimenez:Pagination-Utils:3.1.0
	  2022-07-11T18:48:22.63394969Z
	  Exit code: 0
	  
	  ⚠️ ERROR: No build artifacts found
	  Expected artifacts in: $HOME/.m2/repository/com/github/ygimenez/Pagination-Utils/3.1.0

</details>

**Comment by RealYusufIsmail** [comment]
Have you tried creating a new tag.

**Comment by SIMULATAN** [comment]
I didn't try re-making the tag, that might be worth trying

**Comment by SIMULATAN** [comment]
I've since tried deleting the tag, it was gone on JitPack, I then made it again (on the same commit), and it showed up on JitPack again, but with the same error (and log, it was the one from the 11th of july), so that didn't work.

**Comment by SIMULATAN** [comment]
bump
