### ISSUE TITLE
Getting 401 – unauthorised on a public repo

### ISSUE THREAD

**Issue by jakubdolejs** [jitpack/jitpack.io#5158]
**Describe the bug**
I added a dependency on my Jitpack project in an Android app. When I build the app project I get the following error:

```
Could not resolve com.github.AppliedRecognition:Ver-ID-Serialization-Android:1.0.0.
     Required by:
         project :sample
      > Could not resolve com.github.AppliedRecognition:Ver-ID-Serialization-Android:1.0.0.
         > Could not get resource 'https://jitpack.io/com/github/AppliedRecognition/Ver-ID-Serialization-Android/1.0.0/Ver-ID-Serialization-Android-1.0.0.pom'.
            > Could not GET 'https://jitpack.io/com/github/AppliedRecognition/Ver-ID-Serialization-Android/1.0.0/Ver-ID-Serialization-Android-1.0.0.pom'. Received status code 401 from server: Unauthorized
```

When I load the link in a browser I get an authentication prompt.

The [repository](https://github.com/AppliedRecognition/Ver-ID-Serialization-Android) is public.

**To Reproduce**
1. Add `maven { url 'https://jitpack.io' }` in build.gradle file under repositories.
2. Add `implementation 'com.github.AppliedRecognition:Ver-ID-Serialization-Android:1.0.0'` dependency in build.gradle.
3. Build the project.
4. Build fails with the above error.

**Expected behavior**
Follow steps 1–3 above. Build completes successfully.

**Comment by hamoid** [comment]
I think I'm getting the same. If I try to load https://jitpack.io/com/gitlab/hamoid/openrndr-abe-libs/v0.0.2/openrndr-abe-libs-v0.0.2.pom in the browser it shows a prompt asking for user and password.

The repo was not public before, then I made it open. I don't know if it's related.
