### ISSUE TITLE
Build fails because of unsupported Java version (JDK 17) - Java Update needed?

### ISSUE THREAD

**Issue by penguineer** [jitpack/jitpack.io#5165]
Please provide:

- Link to build log from https://jitpack.io

https://jitpack.io/com/github/penguineer/cleanURI-common/v0.0.1/build.log

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?

Yes

- What error are you seeing?

Dependency cannot be downloaded because the build fails.

Parts of the log:

```
Java version: 1.8.0_292, vendor: Private Build, runtime: /usr/lib/jvm/java-8-openjdk-amd64/jre
```
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.10.1:compile (default-compile) on project common: Fatal error compiling: invalid target release: 17 -> [Help 1]
```

I think a Java update is needed.

Thank you!

**Comment by LeoFuso** [comment]
Hi there, you'll need to setup the JDK manually in a _jitpack.yml_ file, in the root of your repository.


```yml
jdk:
  - openjdk11
```

and then, you can specify the version you need. Jitpack also should support SDK man, this is well documented [here](https://jitpack.io/docs/BUILDING/#java-version).

**Comment by penguineer** [comment]
How did I not see this in the documentation?  🙈
Thank you very much!

I could not set openjdk17 with
```yaml
jdk:
  - openjdk17
```

but this eventually worked:
```yaml
before_install:
  - sdk update
  - sdk install java 17.0.3-tem
  - sdk use java 17.0.3-tem
```
([Test Build Log](https://jitpack.io/com/github/penguineer/cleanURI-common/8bbba3639141d604fd0f906f44b92dc4b65874e5/build.log))
