### ISSUE TITLE
URGENT: AFTER CHANGING THE ACCOUNT SUBSCRIPTION WE RECEIVE THE PAYMENTS IN BOTH ACCOUNTS (this is the 2nd month)

### ISSUE THREAD

**Issue by jaimegc** [jitpack/jitpack.io#5169]
I wrote to you more than a month ago about this issue and I didn't receive any answer.

I paid a subscription (May 29 – Jun 29, 2022) with my github account @jaimegc. After that, I changed this subscription with my enterprise one @CartoDB that is currently paying the subscription. The problem is that now **BOTH** accounts are receiving the payments. In my account the cancel button for the subscription dissapeared. Now, this button is only in my enterprise account.

At the beginning of July I sent you this problem using your support on the website I didn't receive any answer and the payment was made for July and today for August. Only my company should pay this subscription! Even I cannot access to these invoices in pdf!

My invoice number in May is **1ECA751B-0002**. The rest ones probably don't exist but the payment is activated.

**PLEASE REVIEW THIS PROBLEM URGENTLY AND PAY ME BACK THE MONEY!**

**Comment by jitpack-io** [comment]
Hi @jaimegc 

We'll look into this.
For privacy reasons please reach out to us via Support button on our website.

**Comment by jaimegc** [comment]
@jitpack-io Thanks for your answer. The problem was solved and I got my money back.
