### ISSUE TITLE
Should compile with Java17 but used Java8

### ISSUE THREAD

**Issue by wifi-left** [jitpack/jitpack.io#5170]
Please provide:

- Link to build log from https://jitpack.io
https://jitpack.io/com/github/CaffeineMC/sodium-fabric/mc1.19-0.4.2/build.log
- What error are you seeing?
You are using an outdated version of Java (8). Java 17 or higher is required.
Thank you!

**Comment by cicirello** [comment]
@wifi-left I had the same problem. The JitPack docs aren't entirely clear. Once I figured it out, I posted how to do it on dev.to. Here's what I had to do: https://dev.to/cicirello/how-to-configure-jitpack-for-recent-jdk-versions-4pek
