### ISSUE TITLE
Build status is failed but no error in log

### ISSUE THREAD

**Issue by alexk-hn** [jitpack/jitpack.io#5172]
https://jitpack.io/com/github/sevar83/indeterminate-checkbox/1.0.5/build.log

Couldn't reproduce it locally because my installed Java version is too new and it fails with another problem "Could not determine java version from '17.0.2'". Unfortunately, I cannot easily do a downgrade of my java environment just for testing this. But since the jitpack build log doesn't report an error and the underlying git tag hasn't change, I don't think that is it...

**Comment by jitpack-io** [comment]
Hi

Should be resolved now
https://jitpack.io/com/github/sevar83/indeterminate-checkbox/1.0.5/indeterminate-checkbox-1.0.5.pom
