### ISSUE TITLE
mockito-kotlin/0.3.1 build failed due to intermittent network issue and can't rebuild?

### ISSUE THREAD

**Issue by cojo** [jitpack/jitpack.io#519]
Log https://jitpack.io/com/github/nhaarman/mockito-kotlin/0.3.1/build.log

```
=FAILURE: Build failed with an exception.

* What went wrong:
zA problem occurred configuring root project 'build'.
> Could not resolve all dependencies for configuration ':classpath'.
   > jCould not download gradle-bintray-plugin.jar (com.jfrog.bintray.gradle:gradle-bintray-plugin:1.5)
      > \Could not get resource 'https://plugins.gradle.org/m2/com/jfrog/bintray/gradle/gradle-bintray-plugin/1.5/gradle-bintray-plugin-1.5.jar'.
         > Could not GET 'https://plugins.gradle.org/m2/com/jfrog/bintray/gradle/gradle-bintray-plugin/1.5/gradle-bintray-plugin-1.5.jar'.
            > gradleware-plugins.s3.amazonaws.com:443 failed to respond
```

Seems like there was an intermittent network issue with S3... but since I don't own this repo (just need it as a dependency in Maven and it only supports Gradle by default), it seems like there is no way for me to retrigger a rebuild attempt?  Is this correct? Any suggestions?

Thanks!

**Comment by jitpack-io** [comment]
Hi

You're right, looks like a network problem. Rebuilt the project and this time it was successful.
Thanks for raising the issue!
