### ISSUE TITLE
Error on jitpack build

### ISSUE THREAD

**Issue by basicemotions** [jitpack/jitpack.io#5194]
Error while building on jitpack.io

Library version: 47aa8f782f

------------------------------------------------------------
Gradle 5.4.1
------------------------------------------------------------

Build time:   2019-04-26 08:14:42 UTC
Revision:     261d171646b36a6a28d5a19a69676cd098a4c19d

Kotlin:       1.3.21
Groovy:       2.5.4
Ant:          Apache Ant(TM) version 1.9.13 compiled on July 10 2018
JVM:          1.8.0_252 (Private Build 25.252-b09)
OS:           Linux 4.10.0-28-generic amd64

Getting tasks: ./gradlew tasks --all
0m3.600s
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2
POM relocation to an other version number is not fully supported in Gradle : xml-apis:xml-apis:2.0.2 relocated to xml-apis:xml-apis:1.0.b2.
Tasks: uploadArchives,
Module: ./nfclib/build.gradle
Module: ./implementationApp/build.gradle
Module: ./build.gradle
Running: ./gradlew clean -Pgroup=com.github.appfoundry -Pversion=47aa8f782f -xtest -xlint -xsignArchives uploadArchives
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2

> Configure project :nfclib
Configuring local repo: file:///home/jitpack/.m2/repository
WARNING: API 'variant.getJavaCompile()' is obsolete and has been replaced with 'variant.getJavaCompileProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variant.getJavaCompile(), use -Pandroid.debug.obsoleteApi=true on the command line to display more information.
Configuring local repo: file:///home/jitpack/.m2/repository

> Task :implementationApp:clean UP-TO-DATE
> Task :nfclib:clean
> Task :implementationApp:uploadArchives
> Task :nfclib:preBuild UP-TO-DATE
> Task :nfclib:preReleaseBuild UP-TO-DATE
> Task :nfclib:compileReleaseAidl NO-SOURCE
> Task :nfclib:compileReleaseRenderscript NO-SOURCE
> Task :nfclib:checkReleaseManifest
> Task :nfclib:generateReleaseBuildConfig
> Task :nfclib:generateReleaseResValues
> Task :nfclib:generateReleaseResources
> Task :nfclib:packageReleaseResources
> Task :nfclib:mergeReleaseShaders
> Task :nfclib:compileReleaseShaders
> Task :nfclib:generateReleaseAssets
> Task :nfclib:packageReleaseAssets
> Task :nfclib:packageReleaseRenderscript NO-SOURCE
> Task :nfclib:parseReleaseLibraryResources
> Task :nfclib:processReleaseJavaRes NO-SOURCE
> Task :nfclib:mergeReleaseJniLibFolders
> Task :nfclib:processReleaseManifest
> Task :nfclib:javaPreCompileRelease
> Task :nfclib:mergeReleaseNativeLibs
> Task :nfclib:stripReleaseDebugSymbols
> Task :nfclib:transformNativeLibsWithSyncJniLibsForRelease
> Task :nfclib:prepareLintJarForPublish
> Task :nfclib:generateReleaseRFile

> Task :nfclib:compileReleaseJavaWithJavac
Note: /home/jitpack/build/nfclib/src/main/java/be/appfoundry/nfclibrary/activities/NfcActivity.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

> Task :nfclib:extractReleaseAnnotations
> Task :nfclib:mergeReleaseGeneratedProguardFiles
> Task :nfclib:mergeReleaseConsumerProguardFiles
> Task :nfclib:jarRelease
> Task :nfclib:mergeReleaseJavaResource
> Task :nfclib:transformClassesAndResourcesWithSyncLibJarsForRelease
> Task :nfclib:bundleReleaseAar
> Task :nfclib:uploadArchives FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':nfclib:uploadArchives'.
> Could not publish configuration 'archives'
   > Cannot publish artifact 'nfclib.aar' (/home/jitpack/build/nfclib/build/outputs/aar/nfclib.aar) as it does not exist.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.4.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 12s
28 actionable tasks: 27 executed, 1 up-to-date
Build tool exit code: 0
Looking for artifacts...
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2
Looking for pom.xml in build directory and ~/.m2
2021-03-11T07:16:04.840103778Z
Exit code: 0

ERROR: No build artifacts found

**Comment by jitpack-io** [comment]
Hi

We'd recommend running gradle locally with the same arguments 
```
./gradlew clean -Pgroup=com.github.appfoundry -Pversion=47aa8f782f -xtest -xlint -xsignArchives uploadArchives
```
and then checking if artifacts are published to $HOME/.m2/
