### ISSUE TITLE
Cannot sign in

### ISSUE THREAD

**Issue by 00-XPRT-00** [jitpack/jitpack.io#5196]
**Describe the bug**
When clicking sign in the page only refreshes and does not log me in if i click a few times i get the authorization page and it does get authorized in github but still not being signed in
Tried restarting chrome, clearing site data, deauthorizing jitpack on github and still not signing me in

**To Reproduce**
1. Go to jitpack.io
2. Click on Sign in
4. Page reloads or authorization page shows and after does not get signed in

**Expected behavior**
Expected to be signed in but instead page only reloads

**Video of issue**
https://user-images.githubusercontent.com/74925728/184733367-81fe6b62-2c58-469a-9641-06a57ec5c1b4.mp4

**Comment by jitpack-io** [comment]
Hi

Thank you so much for all the details!
We believe we have identified the issue. 
Could you please re-try to see if it lets you sign in?

**Comment by 00-XPRT-00** [comment]
> Hi
> 
> Thank you so much for all the details! We believe we have identified the issue. Could you please re-try to see if it lets you sign in?

Thanks the issue has been fixed

**Comment by sina-tabriziyan** [comment]
i still have the same issue
