### ISSUE TITLE
Subscription is not active right now

### ISSUE THREAD

**Issue by argyle-deployment-account** [jitpack/jitpack.io#5197]
Hello, 

We have a subscription under https://jitpack.io/#argyle-systems/argyle-plugin-android-source
It's currently marked as Inactive but there is no indication why (payment failure etc)
Trying to build the repo yields this

```
Subscription is not active right now
Requested subscription: github.com/argyle-systems. 
Your subscriptions are listed in https://jitpack.io/w/user
Please contact Support or repository admins if you need assistance.
```

Update:
Clicked on "Upgrade" and upgraded to Small29, then got the card charged and it started worked again but the question why it did not renew automatically still stands.

**Comment by jitpack-io** [comment]
Hi

The billing system did try to renew automatically but there was an issue. Due to privacy reasons we recommend reaching out via Support link on our website and we can provide more details.

**Comment by argyle-deployment-account** [comment]
> Hi
> 
> The billing system did try to renew automatically but there was an issue. Due to privacy reasons we recommend reaching out via Support link on our website and we can provide more details.

Reached out via Support link
Thank you
