### ISSUE TITLE
Working builds disappear or become "not found"

### ISSUE THREAD

**Issue by Barryrowe** [jitpack/jitpack.io#5202]
**Describe the bug**
This has happened to me multiple times over the last year. A package will be available, and working for many builds through Jitpack, then out of no where builds start failing for me, and I find out that a package that has not been updated on my end for months is unable to be found. I go to Jitpack and look at the logs, and the logs show a successful build, but still no artifact is available.

This is not a step-by-step reproducible issue, but I can point to two specific versions that I have had this happen with:

**To Reproduce**
1. Create a new Android project and depend on "com.github.sevar83:indeterminate-checkbox:1.0.5@aar"
2. Make sure jitpack.io is in repositories
3. Attempt to build
4.
``` 
> Could not resolve all files for configuration ':app:devDebugCompileClasspath'.
   > Could not find com.github.sevar83:indeterminate-checkbox:1.0.5.
     Required by:
         project :app
```

**Expected behavior**
The package should be found, and the build should complete successfully

**Screenshots**
CLI issue

**Additional context**
Here is the log from the 1.0.5 version of the artifact that won't load:
https://jitpack.io/com/github/sevar83/indeterminate-checkbox/1.0.5/build.log

**Comment by liangjingkanji** [comment]
Me too, Dependencies that have already been built disappear

<img width="134" alt="image" src="https://user-images.githubusercontent.com/21078112/185040072-b15d0324-0d6c-4cf1-b47f-7d7d4337d6d1.png">

Click the file icon tip: `File not found. Build ok`

Click the file icon will rebuild, but even if it is rebuilt, it will still disappear randomly
This is a serious bugs!
