### ISSUE TITLE
JitPack built my project successfully but can't provide artifact

### ISSUE THREAD

**Issue by SNWCreations** [jitpack/jitpack.io#5207]
Please provide:

- Link to build log from https://jitpack.io
https://jitpack.io/com/github/SNWCreations/KookBC/0.13.9/build.log
- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?
Yes. I've tested my project, and the build is success.
- What error are you seeing?
ERROR: Time-out getting container status
Error building

**Comment by jitpack-io** [comment]
Hi

Seems like a transient issue. Rebuilt and it succeeded this time.
