### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by ahmadmssm** [jitpack/jitpack.io#5208]
Hi,

I’m a member of an organization and the company has a subscription-based account, now when I try to deploy a private repo, I get this error message:

Subscription is not active right now
Requested subscription: [github.com/teavaro](http://github.com/teavaro).
Your subscriptions are listed in https://jitpack.io/w/user
Please contact Support or repository admins if you need assistance.

Why this is happening although we already have a paid account ?

**Comment by jitpack-io** [comment]
Hi

The subscription is currently active for an organization on Bitbucket but not on GitHub.
If needed we can switch the subscription to github.com/teavaro.
Please contact us via Support button to arrange a transfer.
