### ISSUE TITLE
Signing in via Bitbucket accounts

### ISSUE THREAD

**Issue by ghost** [jitpack/jitpack.io#521]
Currently it seems your service supports signing in via GitHub accounts only. It would be great if you add support for Bitbucket (or potentially GitLab...)

Currently if one of my version is failed to build because of some missing dependencies from your server (like #517), and when you update those dependencies, I can't delete that failed build. The only way is to publish new version to let the server build it again.

Thank you  `:-)`

**Comment by jitpack-io** [comment]
Hi @haibison 

Good point, thanks for the suggestion! 
The other way right now is to use our API to delete failed builds https://jitpack.io/docs/API/
Hope that helps!

**Comment by 6bangs** [comment]
Would this same enhancement also give us the ability to build artifacts from BitBucket private repositories? It looks like that feature's missing (and it would be _awesome_).

**Comment by jitpack-io** [comment]
Hi @6bangs 
It is already possible to build private BitBucket repositories. Create a Team in Bitbucket and generate an API key under the team’s [admin page](https://jitpack.io/docs/img/bitbucket-apikey.png). Then simply use the API key as a JitPack authentication token.
https://jitpack.io/docs/PRIVATE/

**Comment by 6bangs** [comment]
Ah cool, just got it working. It's a little confusing because there's only Github integration in the rest of the web interface (which I guess would be addressed by this issue). It may be helpful to have some details about Bitbucket support on [https://jitpack.io/private](https://jitpack.io/private).

**Comment by jitpack-io** [comment]
Got an update on this: We now support BitBucket repositories on https://jitpack.io website.
If you Sign In and click on your username (https://jitpack.io/w/user.html)
you'll see a new setting called *BitBucket API Key*. Set it to your Team API Key and then Look Up your repositories on  https://jitpack.io.

**Comment by 6bangs** [comment]
Cool!

**Comment by jitpack-io** [comment]
We now support BitBucket private repos via App Passwords which you can enter on https://jitpack.io/w/user.html

Once entered you will also see your BitBucket repositories on the main page.

Docs:
https://blog.bitbucket.org/2016/06/06/app-passwords-bitbucket-cloud/

**Comment by quangvi282** [comment]
i have tried with bitbucket but when i import library , it still cannot resolve
