### ISSUE TITLE
Max repo size 500MB exceeded error but repository size is 51.7 MB

### ISSUE THREAD

**Issue by Kieaer** [jitpack/jitpack.io#5210]
Please provide:

- Link to build log from https://jitpack.io
https://jitpack.io/com/github/anuken/Mindustry/v136.1/build.log

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?
Yes.

- What error are you seeing?
```
Git error. Retrying.
Git error. Max repo size 500MB exceeded
```

# Question
Does it include increasing file size when build?

**Comment by jitpack-io** [comment]
Hi

That size is calculated when cloning a repository. Looks like the size after `git clone` is currently more than 1G.

**Comment by Kieaer** [comment]
history seems too big
Is there a way to set git clone ``--depth 1`` ?

**Comment by Marcono1234** [comment]
@Kieaer, did you find a solution to this?

In my case I am working on a fork of a repository with a large Git history. However the latest version of the repository is not very large, when performing a shallow clone with `--depth 1`, Git only reports ~ 20 MB transferred. But unfortunately JitPack refuses to build it, with the "Max repo size" error you encountered.

**Comment by jitpack-io** [comment]
Hi all,

We have an upcoming feature that will allow shallow cloning of repositories.
