### ISSUE TITLE
Seeing Exit code 137, out of memory maybe?

### ISSUE THREAD

**Issue by ndemuszNuix** [jitpack/jitpack.io#5211]
Please provide:

- Link to build log from https://jitpack.io
https://jitpack.io/com/gitlab/ToposLabs/GeoGulp/c32f22b3ee/build.log

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?
Builds on my machine and our CI without issue, using same commands

- What error are you seeing?
Exit code 137

Thank you!

**Comment by imTefa** [comment]
Same issue happen with me

Exit code: 137
⚠️ ERROR: No build artifacts found

But everything run successfully on my local machine with Android studio, also the build artifacts is correct and was always  working

**Comment by sukitha-accolade** [comment]
Did you find a solution? I'm facing the same.

**Comment by ndemuszNuix** [comment]
No I didn't find a solution to this within jitpack. I instead stopped using jitpack for builds and haven't had any issues since.

**Comment by sukitha-accolade** [comment]
@ndemuszNuix what was your alternate? Thanks

**Comment by ndemuszNuix** [comment]
We already had a build servers, so I used that for builds and pushed artifacts to artifactory.
