### ISSUE TITLE
Jitpack servers time out for hours

### ISSUE THREAD

**Issue by Goooler** [jitpack/jitpack.io#5213]
Link #5212, should be the same reason.

```
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':processLawnWithQuickstepDebugResources'.
> Could not resolve all task dependencies for configuration ':lawnWithQuickstepDebugRuntimeClasspath'.
   > Could not resolve com.scwang.smart:refresh-footer-classics:2.0.3.
     Required by:
         project : > project :sms:messages
         project : > project :sms:messages > com.scwang.smart:refresh-header-classics:2.0.3
      > Could not resolve com.scwang.smart:refresh-footer-classics:2.0.3.
         > Could not get resource 'https://jitpack.io/com/scwang/smart/refresh-footer-classics/2.0.3/refresh-footer-classics-2.0.3.pom'.
            > Could not HEAD 'https://jitpack.io/com/scwang/smart/refresh-footer-classics/2.0.3/refresh-footer-classics-2.0.3.pom'.
               > Read timed out
```

**Comment by Goooler** [comment]
Provide a solution, if someone using `com.scwang.smart:refresh*:2.0+`, can migrate to 2.0.5 version on `MavenCentral`, see https://github.com/scwang90/SmartRefreshLayout/releases/tag/V2.0.5

**Comment by jitpack-io** [comment]
Hi

Thank you for reporting! 
That url now returns 404 since it is not published on JitPack with `com.scwang.smart` coordinates.
JitPack builds for that repository are on https://jitpack.io/#scwang90/SmartRefreshLayout
Like `com.github.scwang90.SmartRefreshLayout:refresh-drawable-paint:V2.0.5`

**Comment by Goooler** [comment]
But we use `com.scwang.smart:refresh-layout-kernel:2.0.3` for a so long time, how did the artifact id change?
