### ISSUE TITLE
Trademark issues with groupId artifact naming convention

### ISSUE THREAD

**Issue by carlosame** [jitpack/jitpack.io#5215]
Unless you have your own properly configured domain name, for Github-hosted projects Jitpack enforces a convention for the artifact's group Id: `com.github.User`.

However, I stumbled upon the following [statement allegedly from Github](https://law.stackexchange.com/a/38756):

> Unfortunately, we can't allow you to use io.github in your package name. Use of GitHub in a package name could imply affiliation, sponsorship, or endorsement on GitHub's behalf. Therefore, in order to prevent user confusion, we only allow official GitHub packages to be released using GitHub in the package name. I'm very sorry for the disappointment.

I assume that the same would apply to `com.github` group Ids. Any comment?

**Comment by jitpack-io** [comment]
Hi

Thank you for reaching out!
Agree that using github domains in your package name could be confusing and we wouldn't encourage it either. 
Although com.github in groupId used by many projects  https://search.maven.org/search?q=com.github we would recommend getting a custom domain.
