### ISSUE TITLE
Toaster library

### ISSUE THREAD

**Issue by Suman-Android** [jitpack/jitpack.io#5218]
Please provide:
https://jitpack.io/com/github/Suman-Android/Toaster-Library/1.0/build.log
- Link to build log from https://jitpack.io

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?

- What error are you seeing?

Thank you!

**Comment by jitpack-io** [comment]
Hi

There doesn't seem to be a Toaster-Library repository on https://github.com/Suman-Android?tab=repositories
If it is a private repository then please reach out to us via Support button
