### ISSUE TITLE
Keeps getting Git error. Retrying. Git error. Git clone took longer than 180 s, during build most of the times.

### ISSUE THREAD

**Issue by devops-buildingengines** [jitpack/jitpack.io#5221]
Please provide:

- Link to build log from https://jitpack.io  ->  https://jitpack.io/org/bitbucket/buildingengines/kmm-module/1.5.0/build.log

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?  ->  Yes working fine on local

- What error are you seeing?   ->   Git error. Retrying. Git error. Git clone took longer than 180 s,

Thank you!

**Comment by jitpack-io** [comment]
Hi

Is it a big repository? 
Seems like the build succeeded now https://jitpack.io/org/bitbucket/buildingengines/kmm-module/1.5.0/build.log
