### ISSUE TITLE
Build Not Starting

### ISSUE THREAD

**Issue by plutus-finwizard** [jitpack/jitpack.io#5231]
- Link to build log from https://jitpack.io
=> No logs generated. Build is not starting (no loader next to "get it" button)

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?
=> Yes

- What error are you seeing?
=> Nothing. Build is not starting (no loader next to version tag)

Same thing is happening for all the branches/releases/commits/tags.
Tried on multiple browsers and systems with hard-refresh, cache/cookie clean etc.
It just autoscrolls to "How to" section and nothing happens.

Repo Url: org.bitbucket.finwizardtech/partnersdk

Thank you!
Vikas Borkar

**Comment by Elikill58** [comment]
I'm getting same issue. Infinite queued

**Comment by micycle1** [comment]
![image](https://user-images.githubusercontent.com/9304234/190686972-99669057-4f6c-4f78-ad99-bb1a34958923.png)

**Comment by plutus-finwizard** [comment]
This git resolved for me automatically after retrying on 19 Sep.
Closing it.

**Comment by plutus-finwizard** [comment]
Started happening again today.

**Comment by plutus-finwizard** [comment]
Started working again after few days.
