### ISSUE TITLE
Sporadic Build Failures due to timeouts

### ISSUE THREAD

**Issue by compscidr** [jitpack/jitpack.io#5237]
Please provide:

- Link to build log from https://jitpack.io
  - https://jitpack.io/com/github/compscidr/tun-io/fef3a39b00/build.log
  - https://jitpack.io/com/github/compscidr/tun-io/286c44052e/build.log

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?
  - Yes

- What error are you seeing?
```
ERROR: Time-out getting container status
Error building
```

If I retry the build over and over it eventually works. Is there some type of way I can increase the container status timeout via the jitpack.yml or something?

**Comment by compscidr** [comment]
Used something other that jitpack due to lack of any support :v:

**Comment by Yaseendev** [comment]
@compscidr What did you use?
