### ISSUE TITLE
HttpLibrary/1.0.1 build

### ISSUE THREAD

**Issue by DanielWorld** [jitpack/jitpack.io#524]
Log https://jitpack.io/com/github/DanielWorld/HttpLibrary/1.0.1/build.log

**Comment by jitpack-io** [comment]
Hi

Would be best to add the gradle wrapper to the repo. Otherwise JitPack doesn't know which version to use for builds.

**Comment by DanielWorld** [comment]
distributionUrl=https\://services.gradle.org/distributions/gradle-2.10-all.zip

Since I have installed Android Studio 2.0 tool, It happens..
