### ISSUE TITLE
Cannot use my own library with Gradle

### ISSUE THREAD

**Issue by TetraTheta** [jitpack/jitpack.io#5243]
**Describe the bug**
I'm not sure if this is my code's fault or, JitPack's problem.
I made [a library for Minecraft](https://gitlab.com/exmserver/mol)([JitPack](https://jitpack.io/#com.gitlab.exmserver/mol)) and am trying to test it with JitPack.
The problem is, I can't use my library with Gradle. It seems Gradle downloaded my library from JitPack, but my IDE can't use it. IDE says `package com.gitlab.exmserver does not exist` and `cannot find symbol`.
I've done many things to solve this. Invalidate caches, nuke gradle cache and maven local repository, refresh Gradle, run new build on JitPack... Now I don't know what to do to solve this problem.

**To Reproduce**
1. Make a new Minecraft project with IntelliJ IDEA Community Edition, with Minecraft Development plugin.
2. Use this code as a test.
```java
import org.bukkit.entity.Player;
import org.bukkit.event.EventHandler;
import org.bukkit.event.Listener;
import org.bukkit.event.player.PlayerBucketFillEvent;
import org.bukkit.plugin.java.JavaPlugin;
import com.gitlab.exmserver.mol; // 'gitlab' is marked as red. error: package com.gitlab.exmserver does not exist
 
public final class Test extends JavaPlugin implements Listener {
 
    @Override
    public void onEnable() {
        // Plugin startup logic
 
    }
 
    @Override
    public void onDisable() {
        // Plugin shutdown logic
    }
 
    @EventHandler
    public void onTest(PlayerBucketFillEvent e) {
        Player p = e.getPlayer();
        MPlayer mPlayer = new MPlayer(p); // MPlayer is marked as red. error: cannot find symbol
    }
}
```
and use this as `build.gradle`
```gradle
plugins {
    id 'java'
}
 
group = 'test'
version = '1.0-SNAPSHOT'
 
repositories {
    mavenCentral()
    maven { url = "https://jitpack.io" }
    maven { url = 'https://repo.papermc.io/repository/maven-public/' }
    maven { url = 'https://oss.sonatype.org/content/groups/public/' }
}
 
configurations.implementation.canBeResolved = true
configurations.compileOnly.canBeResolved = true
 
dependencies {
    compileOnly 'io.papermc.paper:paper-api:1.19.2-R0.1-SNAPSHOT'
    implementation "com.gitlab.exmserver:mol:main-SNAPSHOT"
}
```

**Expected behavior**
IDE and Gradle should be able to pick my library as dependency and able to use it.

**Additional context**
If you have any other question about this, feel free to tell me. I'm stuck with this state for few days and this really makes me crazy.

**Comment by deflexable** [comment]
@TetraTheta please were you able to solve it? sadly am also having the same issue 😢

**Comment by TetraTheta** [comment]
@deflexable No, I gave up using jitpack.

I'm still opening this issue because jitpack should know about this, and if they solve their issue, it will help others still are willing to use jitpack.
