### ISSUE TITLE
jitpack service is down. Unable to login

### ISSUE THREAD

**Issue by vtn-dev-ajay** [jitpack/jitpack.io#5263]
**Describe the bug**
Jitpack service is down.
We are unable to log in or access the repository

**To Reproduce**

just try to sign in and it goes into an endless loop

**Expected behavior**
sign in to iitpack

Thank you!

**Comment by amitresearchdev** [comment]
I am facing the same issue with my Paid subscription account but one of my friend who is using public Jitpack service is able to login fine. 

Please fix the issue ASAP

**Comment by Krupson** [comment]
Same here, had that problem yesterday, it was fixed and today it occurs again... This service is pretty unreliable lately

**Comment by amitresearchdev** [comment]
Is there any way i can contact the JITPACK Team like contact or email? I have raised the issue here, on twitter and also submitted the same issue on Jitpack website support -> Contact us popup.

Thank you
