### ISSUE TITLE
Unable to retrieve library dependencies from jitpack io from Microsoft AppCenter ci

### ISSUE THREAD

**Issue by gonztirado** [jitpack/jitpack.io#5264]
When I tried to build a project with dependencies from jitpack io I always retrieved time-out errors. We are using AppCenter as CI server -> http://appcenter.ms/

We see errors like these:

> Could not resolve all task dependencies for configuration ':domain:debugUnitTestRuntimeClasspath'.
   > Could not resolve com.nhaarman.mockitokotlin2:mockito-kotlin:2.2.0.
     Required by:
         project :domain
      > Could not resolve com.nhaarman.mockitokotlin2:mockito-kotlin:2.2.0.
         > Could not get resource 'https://jitpack.io/com/nhaarman/mockitokotlin2/mockito-kotlin/2.2.0/mockito-kotlin-2.2.0.pom'.
            > Could not GET 'https://jitpack.io/com/nhaarman/mockitokotlin2/mockito-kotlin/2.2.0/mockito-kotlin-2.2.0.pom'.
               > Read timed out

or

> Could not resolve all task dependencies for configuration ':domain:debugUnitTestRuntimeClasspath'.
   > Could not resolve net.bytebuddy:byte-buddy-android:1.10.10.
     Required by:
         project :domain > org.mockito:mockito-android:3.4.0
      > Could not resolve net.bytebuddy:byte-buddy-android:1.10.10.
         > Could not get resource 'https://jitpack.io/net/bytebuddy/byte-buddy-android/1.10.10/byte-buddy-android-1.10.10.pom'.
            > Could not GET 'https://jitpack.io/net/bytebuddy/byte-buddy-android/1.10.10/byte-buddy-android-1.10.10.pom'.
               > Read timed out

Thanks in advance for your support!

**Comment by mattmaniak** [comment]
The same case for Unity 2021.39f1 and it's Gradle: https://jitpack.io/com/pangle/global/metasec_pgl/4.3.7-alpha.5-Pgl/metasec_pgl-4.3.7-alpha.5-Pgl.pom
