### ISSUE TITLE
Status queued indefinitely 

### ISSUE THREAD

**Issue by makarid** [jitpack/jitpack.io#5265]
**Describe the bug**
I press the Get It button, a 404 and 405 error occurs after inspection the browser with Developer Tools. After a lot of time Jitpack starts the build with a status: Queued. This status stays for many hours and nothing happens and at some point it just drops. I show on the Developer Tools that there is an issue with mockito dependency also. This happens for every release of every of my projects

**To Reproduce**
1. Go to Jitpack
2. Click on to any project and press Get It
3. Choose Developers Tools on browser and see the 404 and 405 error

**Expected behavior**
It should start the build process after some seconds when you press the Get It button

**Comment by kkaun** [comment]
Same here. Hopefully it can be related to "Queue" service bad uptime last 2 days if we check https://status.jitpack.io/ . Not that it makes things more reliable, but just in case - i'd like to think it'll be fixed soon.

**Comment by kkaun** [comment]
Forgot to note on prev comment: it can be proved if we run curl request of builds as described in https://docs.jitpack.io/api/ . For my project, the result list only shows builds that were successfully finished like 3 days ago and more.

**Comment by makarid** [comment]
Can at least the team response to this issue?

**Comment by makarid** [comment]
I don't think this is the issue, because i used only open source project on my free account without any issue the last 6 months

**Comment by makarid** [comment]
@jitpack-io wtf dudes just tell us what is going on. Will you fix it at some point or we need to find another solution? Thanks

**Comment by Sl1veRChair** [comment]
Same thing here:
![image](https://user-images.githubusercontent.com/113704924/197307359-b52d11be-4f17-47df-ab31-f75acc52378c.png)

**Comment by AomineD** [comment]
Same problem here

**Comment by makarid** [comment]
I think they fix it. Check it

**Comment by kkaun** [comment]
Up: queue service having troubles again:
<img width="1327" alt="Знімок екрана 2022-10-24 о 10 03 12" src="https://user-images.githubusercontent.com/18367040/197467652-9233f14d-ea60-49e8-b64d-59e038215be0.png">
Dear Jitpack, it becoming extremely unrealiable :(
