### ISSUE TITLE
“BUILD SUCCESSFUL,” but then “ERROR: No build artifacts found”

### ISSUE THREAD

**Issue by pcantrell** [jitpack/jitpack.io#5268]
Log file: https://jitpack.io/com/github/mac-comp127/kilt-graphics/main-7a8d2afcd0-1/build.log

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?

Yes, this command succeeds locally:

     ./gradlew build publishToMavenLocal --info

- What error are you seeing?

```
BUILD SUCCESSFUL in 3s
…
Archive: com.github.mac-comp127:kilt-graphics:unspecified
…
Looking for pom.xml in build directory and ~/.m2
Found artifact: com.github.mac-comp127:kilt-graphics:unspecified
2022-10-22T15:16:12.141801096Z
Exit code: 0

⚠️ ERROR: No build artifacts found
Expected artifacts in: $HOME/.m2/repository/com/github/mac-comp127/kilt-graphics/unspecified
```

**Comment by AndroidDeveloperLB** [comment]
@ag2s20150909 What is the publish script? Where?
