### ISSUE TITLE
A previous version of the library has become unavailable, the artifact folder which was present previously is gone.

### ISSUE THREAD

**Issue by AniketSK** [jitpack/jitpack.io#5272]
Please provide:

- Link to build log from https://jitpack.io
https://jitpack.io/com/github/100mslive/webrtc/m104-hms-1.2/build.log

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?
This project was built and in production for over a week.

- What error are you seeing?
```
curl -I https://jitpack.io/com/github/100mslive/webrtc/m104-hms-1.2/webrtc-m104-hms-1.2.aar
HTTP/2 404 
date: Tue, 25 Oct 2022 10:10:45 GMT
content-type: text/plain; charset=utf-8
content-length: 9
cf-ray: 75fa2a037ad885b7-BOM
cache-control: max-age=1800, stale-if-error=604800
expires: Tue, 25 Oct 2022 06:11:55 EDT
last-modified: Tue, 25 Oct 2022 10:10:33 Z
vary: Accept-Encoding
cf-cache-status: EXPIRED
x-jp-cf: 1
report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=siHcZzhXQTIfkVYdNquaz5fYfQuBVSmy1eTPTAktX4JchfHTlWA9z6%2FAdZX9McOXTkWI4Bvz6FRjQJWjBaE6u1gZFhbFq7otwET0EBpdhLTWR1ZtkBdFDZiHdWI%3D"}],"group":"cf-nel","max_age":604800}
nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
server: cloudflare
```

Thank you!

**Comment by gchallen** [comment]
Are you sure that this is a permanent error? We've been seeing sporadic download failures for libraries published on Jitpack for the past 24 hours or so. I just encountered another one, but retrying a few minutes later worked. Happily, once Gradle has it cached it shouldn't need to download it again. But still. Even if sporadic, the download failures are worrisome.

**Comment by AniketSK** [comment]
> Are you sure that this is a permanent error? We've been seeing sporadic download failures for libraries published on Jitpack for the past 24 hours or so. I just encountered another one, but retrying a few minutes later worked. Happily, once Gradle has it cached it shouldn't need to download it again. But still. Even if sporadic, the download failures are worrisome.

Yes it's intermittent and not a permanent error. We release an SDK for other businesses however and an intermittent build issue for our customers is pretty troublesome. Different customers, different engineers encountering it etc.

**Comment by sureshjoshi** [comment]
Is there any update or resolution for anyone? I have 3 of 6 versions of a library unavailable. It seems this has been a recent problem (past 3-4 weeks), but I haven't seen any feedback from jitpack

**Comment by AniketSK** [comment]
> Is there any update or resolution for anyone? I have 3 of 6 versions of a library unavailable. It seems this has been a recent problem (past 3-4 weeks), but I haven't seen any feedback from jitpack

They did write back that the issue was resolved and it was. Though it would be nice to know what caused it and how we can be alerted of such issues in the future.
I've begun releasing in parallel on maven central and I could help you do the same.

**Comment by sureshjoshi** [comment]
> They did write back that the issue was resolved and it was
I ended up trying to delete and re-create the tags, and it took about 4-5 hours before it finally worked on my side as well.

No real explanation why they went away or came back.

Dual releasing on Maven is a good idea!
