### ISSUE TITLE
Old build has disappeared from jitpack.

### ISSUE THREAD

**Issue by AniketSK** [jitpack/jitpack.io#5289]
**Describe the bug**
The build log for a old build is present and shows that artefacts were generated successfully, this was being used in prod for a long time.
Today the files are missing and builds with the library are failing.
This build should be frozen as well but is unavailable.

https://jitpack.io/com/github/100mslive/webrtc/m97/build.log

**Expected behavior**
Old builds remain available.

**Additional context**

**Comment by sureshjoshi** [comment]
Is there any update or resolution for anyone? I have 3 of 6 versions of a library unavailable. It seems this has been a recent problem (past 3-4 weeks), but I haven't seen any feedback from jitpack

**Comment by davidliu** [comment]
Same has happened for us as well. 

https://jitpack.io/com/github/webrtc-sdk/android/104.5112.03/
