### ISSUE TITLE
Getting error while publishing android library

### ISSUE THREAD

**Issue by Niharika-test1** [jitpack/jitpack.io#5292]
**Describe the bug**
Getting this error while creating library from bitbucket

An exception occurred applying plugin request [id: 'com.android.application']
> Failed to apply plugin [id 'com.android.internal.version-check']
   > Minimum supported Gradle version is 7.4. Current version is 4.8.1. If using the gradle wrapper, try editing the distributionUrl in /home/jitpack/build/gradle/wrapper/gradle-wrapper.properties to gradle-7.4-all.zip

**To Reproduce**
1. Create a project in latest android studio 
2. every push giving errors in report file

**Expected behavior**
After using gradle-7.4-all.zip also giving same error

**Additional context**
how to fix this issue

**Comment by AniketSK** [comment]
Should it be an application? You most likely want to publish libraries to jitpack.
That plug-in should be com.android.library

**Comment by Niharika-test1** [comment]
Yes its application 
plugins {
    id 'com.android.application' version '7.3.1' apply false
    id 'com.android.library' version '7.3.1' apply false
    id 'org.jetbrains.kotlin.android' version '1.7.20' apply false
}
I have already added this plugin in build.gradle file

**Comment by AniketSK** [comment]
The module can’t be both an application and a library. If it’s a library
you have to remove the application line

**Comment by AniketSK** [comment]
@Niharika-test1 The module can’t be both an application and a library. If it’s a library you have to remove the application line
