### ISSUE TITLE
Unable to change JDK version

### ISSUE THREAD

**Issue by RacoonDog** [jitpack/jitpack.io#5301]
Please provide:

- Link to build log from https://jitpack.io
https://jitpack.io/com/github/RacoonDog/MeteorSharedAddonUtils/b63a1aed/build.log

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?
Yes

- What error are you seeing?
`You are using an outdated version of Java (8). Java 17 or higher is required.`

Thank you!

I've tried
```
jdk:
- openjdk17
```
```
before_install:
  - sdk update
  - sdk install java 17.0.5-tem
  - sdk use java 17.0.5-tem
  ```
  ```
  before_install:
  - sdk install java 17.0.1-tem
  - sdk use java 17.0.1-tem
  ```
  Nothing seems to work, yet it worked fine 2-3 weeks ago.

**Comment by Dreeam-qwq** [comment]
same issue
