### ISSUE TITLE
Comparison method violates its general contract!

### ISSUE THREAD

**Issue by colbyharrison** [jitpack/jitpack.io#5320]
Please provide:

- Link to build log from https://jitpack.io 

- https://jitpack.io/com/github/hellobloom/bloom_android_sdk_core/268e773758/build.log

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?

yes 

- What error are you seeing?

* Where:
Build file '/home/jitpack/build/core/build.gradle' line: 11

* What went wrong:
A problem occurred evaluating project ':core'.
> Comparison method violates its general contract!

Thank you!

**Comment by j2esu** [comment]
Also happens to me occasionally. @colbyharrison did you find any solution?
