### ISSUE TITLE
How to delete builds from jitpack?

### ISSUE THREAD

**Issue by indrif** [jitpack/jitpack.io#5324]
**Describe the bug**
According to your documentation it looks as if it should be possible to delete builds from jitpack:

> ... To delete a build you need to have git push permissions to your git repository.

We have accidentally published some artifacts without obfuscated code and would like to remove those. So how do we do that? It just says "you need push permissions" which of course I have in my own github repository.

**Expected behavior**
A clear and concise description of how to do this.

**Comment by ui24** [comment]
anyone have this solution i also need to delete my published android library from jitpack.
