### ISSUE TITLE
JitPack is not working

### ISSUE THREAD

**Issue by ppazos** [jitpack/jitpack.io#5338]
**Describe the bug**
When retrieving a repo from the website, like https://github.com/ppazos/openEHR-OPT I get "no reason phrase" error in red.

![Screenshot_2022-12-22_14-42-34](https://user-images.githubusercontent.com/1278556/209194565-e32b3d60-596b-4624-8426-7b04f80cd393.png)

**Comment by ArleyPereira** [comment]
problem happening today

Jitpack.io off
https://prnt.sc/08t1tlmX3VX6

build.gradle(Project)
https://prnt.sc/ec-gUzBk0HZM

build.gradle(Module)
https://prnt.sc/Y4uUjacOSVz1

settings.gradle(Project)
https://prnt.sc/MEUNV3Ukz3iB

Problem
https://prnt.sc/gzJ4WoUBHaN6

**Comment by matt-williams-sa** [comment]
same

**Comment by eygraber** [comment]
Probably better to keep things in one issue https://github.com/jitpack/jitpack.io/issues/5337

**Comment by HoangNgocThang** [comment]
![b1111](https://user-images.githubusercontent.com/54477024/209271765-9b93b163-e4a8-48a1-9a63-706a903cfbdc.PNG)

**Comment by DavidTheExplorer** [comment]
I'm getting the same 521 error and cannot build my projects.

**Comment by ppazos** [comment]
I can confirm today the website is working again 

![Screenshot_2022-12-23_14-32-29](https://user-images.githubusercontent.com/1278556/209377267-ec429c38-6af6-4540-ada7-6aac837ceb25.png)
