### ISSUE TITLE
Why it's no working?? Error 521

### ISSUE THREAD

**Issue by danielhadadwaterio** [jitpack/jitpack.io#5339]
I can't build,
I got status error code 521 from server all day!

**Comment by chloecdn** [comment]
#5337

**Comment by HoangNgocThang** [comment]
> Could not get resource 'https://www.jitpack.io/com/github/barteksc/android-pdf-viewer/2.8.2/android-pdf-viewer-2.8.2.pom'.
            > Could not HEAD 'https://www.jitpack.io/com/github/barteksc/android-pdf-viewer/2.8.2/android-pdf-viewer-2.8.2.pom'. Received status code 521 from server:
            
![b1111](https://user-images.githubusercontent.com/54477024/209271935-423bd0cc-d547-4b88-8057-c3d7f9f16fa9.PNG)

**Comment by ArchangelXu** [comment]
While we are talking, I found it says "All systems operational" at https://status.jitpack.io/ ......

**Comment by pwerry** [comment]
Is this being worked on? 100% of our builds are failing now

**Comment by wlpsunny** [comment]
![image](https://user-images.githubusercontent.com/16948302/209286612-07f45230-b06c-4e95-8bc3-176ca62f8456.png)

**Comment by android-taoge** [comment]
it not working for download dependency ,how long will take you to fix this problem?

**Comment by jcraane** [comment]
Same issue here: Could not GET 'https://jitpack.io/com/github/passsy/gradle-gitVersioner-plugin/v0.5.0/gradle-gitVersioner-plugin-v0.5.0.pom'. Received status code 521 from server:

**Comment by alex-dokienko** [comment]
also can't build project when trying to change any library version (which not even in jitpack) as gradle looks like trying to go and find that version on each remote server and jitpack just breaking whole pipeline with 521 error

**Comment by e1sep0** [comment]
I'm trying too, but the same error(
```
Could not HEAD 'https://jitpack.io/com/google/protobuf/protobuf-java/3.17.2/protobuf-java-3.17.2.pom'. Received status code 521 from server: 
```

**Comment by e1sep0** [comment]
If i add `www` to url, get new error:
```
Could not HEAD 'https://www.jitpack.io/org/bouncycastle/bcpkix-jdk15on/1.67/bcpkix-jdk15on-1.67.pom'. Received status code 521 from server: 
```

But for somebody this trick should help

**Comment by LowScarlet** [comment]
https://github.com/jitpack/jitpack.io/issues/5337#issue-1507278707
