### ISSUE TITLE
Could not GET 'https://jitpack.io/com/github/santalu/mask-edittext/1.0.5/mask-edittext-1.0.5.pom'. Received status code 521 from server:

### ISSUE THREAD

**Issue by gaurav90jain** [jitpack/jitpack.io#5340]
Please provide:

- Could not get resource '[https://jitpack.io/com/github/MFlisar/RxBus2/0.2/RxBus2-0.2.pom'](https://jitpack.io/com/github/MFlisar/RxBus2/0.2/RxBus2-0.2.pom%27).

- Project build is failing

- Received status code 521 from server:

Thank you!

**Comment by DavidTheExplorer** [comment]
https://github.com/jitpack/jitpack.io/issues/5337#issue-1507278707

**Comment by LowScarlet** [comment]
https://github.com/jitpack/jitpack.io/issues/5337#issue-1507278707
