### ISSUE TITLE
 Could not resolve com.facebook.react:react-native.      Required by:          project :react-native-image-crop-picker       > Skipped due to earlier error    > Could not resolve com.github.yalantis:ucrop:2.2.6-native.      Required by:          project :react-native-image-crop-picker

### ISSUE THREAD

**Issue by MunemHabib47** [jitpack/jitpack.io#5341]
allprojects {
    repositories {
        maven {
            url "https://sdks.instabug.com/nexus/repository/instabug-cp"
        }
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url("$rootDir/../node_modules/react-native/android")
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }
        mavenCentral {
            // We don't want to fetch react-native from Maven Central as there are
            // older versions over there.
            content {
                excludeGroup "com.facebook.react"
            }
        }
        google()
        maven { url 'https://www.jitpack.io' }
    }
}

Server throwing 521 
Any Solutions?

**Comment by dvkolesnikov** [comment]
#5337
