### ISSUE TITLE
Incorrect status info

### ISSUE THREAD

**Issue by anton-fedorenko** [jitpack/jitpack.io#5343]
**Describe the bug**
https://status.jitpack.io/ says "All systems operational" during 30 hours service outage

**To Reproduce**
1. Go to 'https://status.jitpack.io/'
2. See status

**Expected behavior**
Message about incident.

**Additional context**
See https://github.com/jitpack/jitpack.io/issues/5337

**Comment by aditdiqdpratama** [comment]
This is the actuall bugs 🤣.

**Comment by knyttl** [comment]
Please don't ignroe this 🙏

**Comment by knyttl** [comment]
This is still relevant.

**Comment by tunikakeks** [comment]
still during the already 9h downtime
