### ISSUE TITLE
Status page does not reflect if the system works

### ISSUE THREAD

**Issue by knyttl** [jitpack/jitpack.io#5345]
**Describe the bug**
https://status.jitpack.io/ incorrectly showed that the jitpack infra works correctly during downtime.

**To Reproduce**
1. Take down jitpack.io infra
2. Open https://status.jitpack.io/
3. It will say everything is fine.

**Expected behavior**
It should correctly show that the infra is down.

**Screenshots**

<img width="1046" alt="Screenshot 2022-12-23 at 14 41 45" src="https://user-images.githubusercontent.com/401107/209345522-ac3f6a01-d6d6-4b3e-9801-16a888e81e48.png">

**Comment by sebastian-peter** [comment]
Duplicate of #5343
