### ISSUE TITLE
Postmortem for The Downtime

### ISSUE THREAD

**Issue by knyttl** [jitpack/jitpack.io#5346]
Hi,

could you please be transparent and provide us with a postmortem report, mitigation solution and the steps that this will not happen again?

I guess everyone is keen to know what happened and if this can be avoided in the future?

Thanks 🙏

**Comment by knyttl** [comment]
Please don't ignore this 🙏

**Comment by knyttl** [comment]
This is still relevant.

**Comment by osipxd** [comment]
Should we tag @jitpack-io to highlight this issue in thousands of other open issues in the repository?

**Comment by osipxd** [comment]
Still relevant

**Comment by osipxd** [comment]
@jitpack-io
