### ISSUE TITLE
Gradle transitive dependency exclusions are dropped

### ISSUE THREAD

**Issue by angryziber** [jitpack/jitpack.io#5349]
**Describe the bug**

When a gradle projects declares some dependencies as excluded, e.g.
https://github.com/codeborne/klite/blob/master/liquibase/build.gradle.kts

Then running `./gradle publishToMavenLocal` will correctly preserve these excludes in both `pom.xml` and Gradle `*.module` files.

However, Jitpack's version somehow omits **excludes** from the `.module` file, which seems to be processed/reformatted from the original version that Gradle produces. The `pom.xml` lists the exclusions correctly, but Gradle has a precedence of it's own `.module`s files and thus doesn't see the exclusions.

Here is what Jitpack puiblishes:
https://jitpack.io/com/github/codeborne/klite/klite-liquibase/1.3.8/klite-liquibase-1.3.8.pom
- this file contains the correct `<exclusions>` list

https://jitpack.io/com/github/codeborne/klite/klite-liquibase/1.3.8/klite-liquibase-1.3.8.module
- this file omits the `excludes` element that is present in the original build artifact.

It should look like this:
```json
"dependencies": [
        {
          "group": "org.liquibase",
          "module": "liquibase-core",
          "version": {
            "requires": "4.18.0"
          },
          "excludes": [
            {
              "group": "com.opencsv",
              "module": "*"
            },
            {
              "group": "org.yaml",
              "module": "*"
            },
            {
              "group": "javax.xml.bind",
              "module": "*"
            }
          ]
        },
...
```

Why do the Gradle .module files are different from what the Gradle itself produces?
How to publish the original `excludes` there?

**Comment by angryziber** [comment]
Ok, it seems a similar issue already exists from November: https://github.com/jitpack/jitpack.io/issues/5295

**Comment by angryziber** [comment]
A workaround is to disable publishing Gradle module metadata, then Gradle reads excludes from pom file and it works correctly:
```kotlin
  tasks.withType<GenerateModuleMetadata> {
    enabled = false
  }
```

**Comment by angryziber** [comment]
Is any more information needed?

**Comment by angryziber** [comment]
Please reopen the issue as it hasn't been fixed

**Comment by 0x3C50** [comment]
just stumbled upon the same problem. thanks jitpack :+1:
