### ISSUE TITLE
Annual Subscription mistake

### ISSUE THREAD

**Issue by jose0796** [jitpack/jitpack.io#5365]
I mistakenly purchased an annual subscription on a StarterPack due to confusion on your website, as prices appear as monthly rated but purchase amount appears as a total for the whole year which leads to confusion. I only wanted a monthly subscription. 

The main issue

I ended up cancelling the annual subscription in favor for a monthly subscription. I already paid the latter. But I haven't got a refund on the annual subscription I cancelled. Can I get refund on this matter?!! 

Regarding the initial thing I mentioned, you can see below that prices appear as monthly rated
![image](https://user-images.githubusercontent.com/29413110/209683328-575c819e-d118-47a4-b9bf-975923c24551.png)

but when it comes to paying annual billing cycle is selected as default (and not PROPERLY DISPLAYED to the user) 

![image](https://user-images.githubusercontent.com/29413110/209683659-f7fdc11a-ffca-484a-8f66-6c7e314dc193.png)

**Comment by gurhankodalak-vektor** [comment]
I have the same issue, I want to cancel my annual subscription and pay it monthly. Any support here? Don't have any useful information about this.

**Comment by jose0796** [comment]
Sadly enough, billing support hasn't answered me, neither through email nor on their website's ticketing system.
