### ISSUE TITLE
Not able to access jitpack gradle dependency for private github repository

### ISSUE THREAD

**Issue by priyankagupta-ITT** [jitpack/jitpack.io#5370]
Around 3-4 months ago, I am able to access private repository through my android studio application, But now i'm getting below error 
"Received status code 403 from server: Forbidden"

Link to build log from https://jitpack.io/
https://jitpack.io/com/github/Kount/kount-android-sdk-source/v4.2.3/build.log
If i clicked on logs for my build on jitpack.io , it is showing below error

Subscription is not active right now
Requested subscription: github.com/kount. 
Your subscriptions are listed in https://jitpack.io/w/user
Please contact Support or repository admins if you need assistance.

we checked our subscription is correct

Please provide solution for this

**Comment by priyankagupta-ITT** [comment]
@jitpack-io  Please reply here for the solution

**Comment by jitpack-io** [comment]
Hi all

The subscription for github.com/kount is now active.
Apologies for the delay

**Comment by priyankagupta-ITT** [comment]
Thank you
