### ISSUE TITLE
Error adding dependecy on NDK sub-module

### ISSUE THREAD

**Issue by gilcarmel** [jitpack/jitpack.io#538]
I am trying to import the 'audio' module from this project (jitpack2 branch):

https://github.com/gilcarmel/Low-Latency-Android-Audio-iOS-Audio-Engine/tree/jitpack2

I'm using the following line in my build.grade:
compile 'com.github.gilcarmel.Low-Latency-Android-Audio-iOS-Audio-Engine:audio:jitpack2-3b2c3bb321-1'

But getting an error (see below).

It's worth noting that this module has NDK code.

Any ideas?

Thanks!
Gil

-----------------------------
Here's the error:

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':DetourEngine'.
> Could not resolve all dependencies for configuration ':DetourEngine:_debugCompile'.
   > Could not find com.github.gilcarmel.Low-Latency-Android-Audio-iOS-Audio-Engine:audio:jitpack2-3b2c3bb321-1.
     Searched in the following locations:
         file:/Applications/Android Studio.app/Contents/gradle/m2repository/com/github/gilcarmel/Low-Latency-Android-Audio-iOS-Audio-Engine/audio/jitpack2-3b2c3bb321-1/audio-jitpack2-3b2c3bb321-1.pom
         file:/Applications/Android Studio.app/Contents/gradle/m2repository/com/github/gilcarmel/Low-Latency-Android-Audio-iOS-Audio-Engine/audio/jitpack2-3b2c3bb321-1/audio-jitpack2-3b2c3bb321-1.jar
         https://jcenter.bintray.com/com/github/gilcarmel/Low-Latency-Android-Audio-iOS-Audio-Engine/audio/jitpack2-3b2c3bb321-1/audio-jitpack2-3b2c3bb321-1.pom
         https://jcenter.bintray.com/com/github/gilcarmel/Low-Latency-Android-Audio-iOS-Audio-Engine/audio/jitpack2-3b2c3bb321-1/audio-jitpack2-3b2c3bb321-1.jar
         https://jitpack.io/com/github/gilcarmel/Low-Latency-Android-Audio-iOS-Audio-Engine/audio/jitpack2-3b2c3bb321-1/audio-jitpack2-3b2c3bb321-1.pom
         https://jitpack.io/com/github/gilcarmel/Low-Latency-Android-Audio-iOS-Audio-Engine/audio/jitpack2-3b2c3bb321-1/audio-jitpack2-3b2c3bb321-1.jar
         http://dl.bintray.com/pixplicity/maven/com/github/gilcarmel/Low-Latency-Android-Audio-iOS-Audio-Engine/audio/jitpack2-3b2c3bb321-1/audio-jitpack2-3b2c3bb321-1.pom
         http://dl.bintray.com/pixplicity/maven/com/github/gilcarmel/Low-Latency-Android-Audio-iOS-Audio-Engine/audio/jitpack2-3b2c3bb321-1/audio-jitpack2-3b2c3bb321-1.jar
         file:/Users/gil/Library/Android/sdk/extras/android/m2repository/com/github/gilcarmel/Low-Latency-Android-Audio-iOS-Audio-Engine/audio/jitpack2-3b2c3bb321-1/audio-jitpack2-3b2c3bb321-1.pom
         file:/Users/gil/Library/Android/sdk/extras/android/m2repository/com/github/gilcarmel/Low-Latency-Android-Audio-iOS-Audio-Engine/audio/jitpack2-3b2c3bb321-1/audio-jitpack2-3b2c3bb321-1.jar
         file:/Users/gil/Library/Android/sdk/extras/google/m2repository/com/github/gilcarmel/Low-Latency-Android-Audio-iOS-Audio-Engine/audio/jitpack2-3b2c3bb321-1/audio-jitpack2-3b2c3bb321-1.pom
         file:/Users/gil/Library/Android/sdk/extras/google/m2repository/com/github/gilcarmel/Low-Latency-Android-Audio-iOS-Audio-Engine/audio/jitpack2-3b2c3bb321-1/audio-jitpack2-3b2c3bb321-1.jar
     Required by:
         detour-client-android:DetourEngine:unspecified

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

**Comment by jitpack-io** [comment]
@gilcarmel Looks like we've resolved this one via email, right?

**Comment by gilcarmel** [comment]
Yes, thanks!
