### ISSUE TITLE
IRecyclerView/0.0.2 build

### ISSUE THREAD

**Issue by Aspsine** [jitpack/jitpack.io#539]
Log https://jitpack.io/com/github/Aspsine/IRecyclerView/0.0.2/build.log

**Comment by twiceyuan** [comment]
是的，我也曾遇到过这种情况，有时候随便改一点让它重新 build 一下就好了

**Comment by Aspsine** [comment]
It seems that google recalled the 'com.android.support:recyclerview-v7:23.3.0' and use old version 'com.android.support:recyclerview-v7:23.2.1' in sdk Manager. I am not sure about this.

'com.github.Aspsine:IRecyclerView:0.0.1' builds fine. The difference between IRecyclerView/0.01 and IRecyclerView/0.02 is that I updated versionCode 1 to 2, versionName 0.0.1 to 0.0.2 and recyclerview verison in dependencies 23.2.1 to 23.3.0

@jitpack-io  Hope these infos would help.

**Comment by jitpack-io** [comment]
@Aspsine Thank you for the info! It will help other users too

**Comment by Aspsine** [comment]
I made an new release which build with 'com.android.support:recyclerview-v7:23.3.0' and it's works fine.
