### ISSUE TITLE
voxer_io_android_sdk/61bae791e9 build

### ISSUE THREAD

**Issue by voxer-jitpackio** [jitpack/jitpack.io#5393]
Please provide:

- Link to build log from https://jitpack.io
- https://jitpack.io/com/github/Voxer/voxer_io_android_sdk/61bae791e9/build.log

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?
- Yes

- What error are you seeing?
- Shows build successful but for one of library modules it complaints before generating the library 
- ERROR: No build artifacts found
Expected artifacts in: $HOME/.m2/repository/com/github/Voxer/audiorouter/unspecified

Thank you!

**Comment by voxer-jitpackio** [comment]
Even ./gradlew clean -Pgroup=com.github.Voxer -Pversion=1172a5afdc -xtest -xlint assemble publishToMavenLocal succeeds on my local machine.

**Comment by AndroidDeveloperLB** [comment]
How did you fix it?
