### ISSUE TITLE
Cannot create release in Jitpack using aar file only

### ISSUE THREAD

**Issue by avitrichenko** [jitpack/jitpack.io#5394]
Please provide:

- Link to build log from https://jitpack.io
- https://jitpack.io/com/github/HeyChargeEVCharging/heycharge-android-sdk/0.0.4/build.log

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?
- No

- What error are you seeing?
- The following artifacts could not be resolved: androidx.room:room-runtime:jar:2.4.3, androidx.lifecycle:lifecycle-livedata-ktx:jar:2.5.1, androidx.core:core-ktx:jar:1.9.0, androidx.work:work-runtime-ktx:jar:2.7.1, androidx.security:security-crypto:jar:1.1.0-alpha04: Could not find artifact androidx.room:room-runtime:jar:2.4.3 in central (https://repo.maven.apache.org/maven2) -> [Help 1]

Thank you!

**Comment by avitrichenko** [comment]
The problem is that I have a private repo and we have developed the SDK for the users.
This SDK has some androidx dependencies like core-ktx,livedata, room etc.
I have jitpack.yml file:
install: 
FILE="-Dfile=android-sdk-1.0.0.aar" 
mvn install:install-file $FILE -DgroupId=com.heycharge -DartifactId=android-sdk -Dversion=1.0.0 -Dpackaging=aar -DpomFile=pom.xml

In pom.xml file I have all the dependencies, but when I create release through Github, Jitpack starts making build and it cannot find any of androidx artifacts.
I get error like this:
The POM for androidx.room:room-runtime:jar:2.4.3 is missing, no dependency information available

**Comment by hms-douglas** [comment]
Any solution??
