### ISSUE TITLE
show sha builds in version list

### ISSUE THREAD

**Issue by dbachelder** [jitpack/jitpack.io#54]
this library has numerous builds from sha.. it would be great to see them in the list with the build date and build log links.

https://jitpack.io/#dbachelder/CreditCardEntry

**Comment by jitpack-io** [comment]
Interesting! If we're displaying the sha then probably it would be useful to see the commit message that came with it.
Adding a list of builds wouldn't be technically difficult but it would be a challenge to keep the UI simple at the same time. Probably we should only show the list if you are logged in and it's your own project.

**Comment by dbachelder** [comment]
You could show the bare minimum and have a mouse over with further details.

**Comment by jitpack-io** [comment]
Yes, possibly. Need to play around with the UI. If its a really long list we might have to make it scrollable.
In general the list of builds is already available to the website: https://jitpack.io/api/com.github.dbachelder/CreditCardEntry

**Comment by jitpack-io** [comment]
Small update: now it's possible to switch between releases and commits on the website.

**Comment by dbachelder** [comment]
this works for me!

**Comment by jitpack-io** [comment]
Another update: you can now also use the special version `-SNAPSHOT`
It will build the last commit in the repo.
By default gradle checks for new versions every 24h but that's configurable with:
```gradle
configurations.all {
    resolutionStrategy.cacheChangingModulesFor 60, 'seconds'
}
```

**Comment by dbachelder** [comment]
that's badass
