### ISSUE TITLE
RxAppState/1.0.0 build

### ISSUE THREAD

**Issue by jenzz** [jitpack/jitpack.io#541]
**Log:** https://jitpack.io/com/jenzz/RxAppState/1.0.0/build.log

```
* What went wrong:
A problem occurred evaluating project ':library'.
> Failed to apply plugin [id 'com.android.library']
   > Could not create plugin of type 'LibraryPlugin'.
```

Interestingly, not using my custom domain [com.jenzz/RxAppState](https://jitpack.io/#com.jenzz/RxAppState)
and using [com.github.jenzz/RxAppState](https://jitpack.io/#com.github.jenzz/RxAppState) instead works just fine.

**Comment by jenzz** [comment]
I did another release of this library.

[v1.0.1](https://jitpack.io/com/jenzz/RxAppState/1.0.1/build.log) seems to work just fine again.

**Comment by jitpack-io** [comment]
Hi

The issue was caused was there because of the Beta version of com.android.library. When it is out of date then it requires the ANDROID_DAILY_OVERRIDE environment variable.

```
Plugin is too old, please update to a more recent version, or set ANDROID_DAILY_OVERRIDE environment variable to "c6930c23d36ab6b6b38444329718db02cc97d20d"
```
