### ISSUE TITLE
403 Forbidden for Private Repository, account for client is active 

### ISSUE THREAD

**Issue by radiohabitat** [jitpack/jitpack.io#5413]
In Android Studio using the private repository and trying to access, I receive "Received status code 403 from server: Forbidden"

Subscription is not active right now
Requested subscription: []
Your subscriptions are listed in https://jitpack.io/w/user
Please contact Support or repository admins if you need assistance.

Confirmed the account is active and current and everything with the account is setup correctly, the client that is trying to access the account is receiving the error message and I am now seeing the error message, this is a urgent matter because the client is now blocked and time sensitive

**Comment by JasonHQuintar** [comment]
We can close this issue the 403 message is now gone
