### ISSUE TITLE
JARs with Classifiers not getting deployed

### ISSUE THREAD

**Issue by lprimak** [jitpack/jitpack.io#5430]
**Describe the bug**
When a Java library has multiple JARs with classifiers with them, jitpack does not deploy them.

**Additional context**
Many libraries support both Pre-Jakarta 9 (javax namespace) and jakarta namespace for 9+
This ia accomplished via the maven shade plugin that attaches JARs with `-jakarta` classifiers.
Jitpack is not deploying those other artifacts with classifiers

**Comment by jitpack-io** [comment]
Hi @lprimak 

If those jars get installed into ~/.m2 after `maven install` then then normally they would get published on JitPack.
We could have a closer look if you have an example project and logs.

**Comment by lprimak** [comment]
Thanks for looking into this. Upon further examination, the issue was caused by the Java compiler version.
Sorry to bother you, classifiers work perfectly.
