### ISSUE TITLE
Issue with "com.android.tools.build:gradle:2.0.0"

### ISSUE THREAD

**Issue by Mahendran-Sakkarai** [jitpack/jitpack.io#544]
Hi,

Check my Library and its version details using the below link.
[https://jitpack.io/#Mahendran-Sakkarai/Progression](https://jitpack.io/#Mahendran-Sakkarai/Progression)

When i use `com.android.tools.build:gradle` version `1.5.0` in top level `build.gradle` it is working fine. When i migrated to version `2.0.0` it is giving the following error.

`Failed to resolve: com.github.Mahendran-Sakkarai:Progression:1.4`

My Android Studio version is `2.0`. 

Gradle distribution URL`(gradle-wrapper.properties)` for `com.android.tools.build:gradle:2.0.0` is 
> distributionUrl=https\://services.gradle.org/distributions/gradle-2.10-all.zip

and for `com.android.tools.build:gradle:1.5.0` is 

> distributionUrl=https\://services.gradle.org/distributions/gradle-2.4-all.zip

I tried to clean and build. I got the below in the `Messages Tab` of Android Studio.

```
Error:A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugCompile'.
   > Could not resolve com.github.Mahendran-Sakkarai:Progression:1.4.
     Required by:
         Testing:app:unspecified
      > Could not resolve com.github.Mahendran-Sakkarai:Progression:1.4.
         > Could not get resource 'https://jitpack.io/com/github/Mahendran-Sakkarai/Progression/1.4/Progression-1.4.pom'.
            > Could not HEAD 'https://jitpack.io/com/github/Mahendran-Sakkarai/Progression/1.4/Progression-1.4.pom'.
               > peer not authenticated
Information:BUILD FAILED
```

Thanks.

**Comment by jitpack-io** [comment]
Hi

Could you try Gradle 2.12? It should have been fixed there

**Comment by Mahendran-Sakkarai** [comment]
Thanks @jitpack-io 

As you mentioned, fixed the issue by updating the gradle version to `2.12` by changing `Gradle distribution URL in gradle-wrapper.properties` file like below.
> distributionUrl=https\://services.gradle.org/distributions/gradle-2.12-all.zip
