### ISSUE TITLE
AppiumTestDistribution/f6b22f8073 build

### ISSUE THREAD

**Issue by saikrishna321** [jitpack/jitpack.io#546]
Log https://jitpack.io/com/github/saikrishna321/AppiumTestDistribution/f6b22f8073/build.log

**Comment by saikrishna321** [comment]
@jitpack-io even if i have the jitpack in the repo url but still its looking for maven

**Comment by jitpack-io** [comment]
Looks like it's successful now https://jitpack.io/com/github/saikrishna321/AppiumTestDistribution/4c5905a50e/build.log

**Comment by saikrishna321** [comment]
@jitpack-io works now :)
