### ISSUE TITLE
Unable to download pom file. Request gets timed out

### ISSUE THREAD

**Issue by DeVysh** [jitpack/jitpack.io#5474]
The build is failing with the below error:

> Could not resolve com.github.Constructor-io:constructorio-client-android:v2.16.0.
         > Could not get resource '[https://jitpack.io/com/github/Constructor-io/constructorio-client-android/v2.16.0/constructorio-client-android-v2.16.0.pom'](https://jitpack.io/com/github/Constructor-io/constructorio-client-android/v2.16.0/constructorio-client-android-v2.16.0.pom).
            > Could not GET '[https://jitpack.io/com/github/Constructor-io/constructorio-client-android/v2.16.0/constructorio-client-android-v2.16.0.pom'](https://jitpack.io/com/github/Constructor-io/constructorio-client-android/v2.16.0/constructorio-client-android-v2.16.0.pom).
               > Read timed out
               
               
I am unable to download pom file from my browser as well. I thought it might be because jitpack is down, but the status page has marked jitpack as 100% operational.

**Comment by DeVysh** [comment]
The issue is resolved for me now

**Comment by jitpack-io** [comment]
Hi

A timeout can occur if the build is in progress or is in the queue. There could have been technical issues as well at the time but if it is resolved then closing this ticket

**Comment by flutter-kim-json** [comment]
> Hi
> 
> A timeout can occur if the build is in progress or is in the queue. There could have been technical issues as well at the time but if it is resolved then closing this ticket

I experienced the same problem yesterday. It hasn't been built since yesterday, and it's working fine now.
The same problem has occurred twice in the last two weeks.

**Comment by flutter-kim-json** [comment]
@jitpack-io 

I experienced the same problem yesterday. It hasn't been built since yesterday, and it's working fine now.
The same problem has occurred twice in the last two weeks.
