### ISSUE TITLE
kt-dbtable/aa7cfe413e build

### ISSUE THREAD

**Issue by xpwu** [jitpack/jitpack.io#5505]
Please provide:

- Link to build log from https://jitpack.io
- https://jitpack.io/com/github/xpwu/kt-dbtable/aa7cfe413e/build.log

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?
- yes. it is ok on my machine

- What error are you seeing?
- Could not resolve com.android.tools.build:gradle:7.4.2.

Thank you!

**Comment by xpwu** [comment]
Could not resolve com.android.tools.build:gradle:7.4.2.

**Comment by Mohsents** [comment]
I  have the same issue. found you any fix?

**Comment by xpwu** [comment]
no
