### ISSUE TITLE
Unable to download public artifact without access token

### ISSUE THREAD

**Issue by amirpervaizQI** [jitpack/jitpack.io#5539]
**Describe the bug**
I built an artifact from a private repo, then for testing I generated an access token and after that made the artifact public by unlocking the icon. But the issue is, after generating the access token, there is no way to delete it and it seems that the access token is always required to download it even after making the artifact public. 

**To Reproduce**
1. Go to a private repo
2. Click on 'Get it'
3. Once the build is ready, click the setting icons and generate an access token. 
4. Once the token is generated, there is no way to delete it, so made the artifact public by unlocking the lock icon. 
5. Gradle is unable to resolve dependency until access token is used. Though it should work without access token since the artifact is made public from the private repo.

**Expected behavior**
 It should work without access token since the artifact is made public from the private repo.

**Screenshots**
<img width="655" alt="jitpack" src="https://user-images.githubusercontent.com/67275445/230650979-ae21a048-160f-4bce-88a5-8466e66ddf5e.png">

**Additional context**

Thanks

**Comment by amirpervaizQI** [comment]
In the above screenshot, generated access token is always there. There is no way to delete it. hence artifacts cannot be downloaded even after making it public.

**Comment by extoldeveloper** [comment]
@jitpack-io could you pls check this?

**Comment by amirpervaizQI** [comment]
@jitpack-io  could you pls check this?
