### ISSUE TITLE
ShoutOut/1.0.0 build

### ISSUE THREAD

**Issue by nisrulz** [jitpack/jitpack.io#555]
Log https://jitpack.io/com/github/nisrulz/ShoutOut/1.0.0/build.log

**Comment by jitpack-io** [comment]
Hi

Looks like the gradle wrapper is missing from this repo
```
WARNING: gradle/wrapper/gradle-wrapper.jar does not exist! Needs to be committed.
WARNING: Gradle wrapper not found. Please add. Using default gradle to build.
```

**Comment by nisrulz** [comment]
I have included the required files, but jitpack is still referring to older commits. I have removed the tag and added the same tag to the latest commit. 

What might I be doing wrong here ?

**Comment by jitpack-io** [comment]
Rebuilt but now there's a different issue:
```
Script 'https://raw.github.com/nisrulz/gradle-mvn-push/master/gradle-mvn-push.gradle' line: 48
> A problem occurred configuring project ':library'.
   > No such property: GROUP 
```
