### ISSUE TITLE
Failed to load library build

### ISSUE THREAD

**Issue by vadimka1206** [jitpack/jitpack.io#5588]
**Describe the bug**
Failed to load library build with jitpack.
https://jitpack.io/com/github/evotor/integration-library/6fc8b21da8/build.log
Build success, but when I try to use this version in my project, gradle shows error "Failed to resolve: com.github.evotor:integration-library:6fc8b21da8"

**To Reproduce**
Try to add dependency
implementation 'com.github.evotor:integration-library:6fc8b21da8' and build project

**Comment by ahmadmssm** [comment]
I'm facing the same issue.

**Comment by ahmadmssm** [comment]
No, I'm still facing the same issue.
