### ISSUE TITLE
My project is not building after pushing with no flags at all.

### ISSUE THREAD

**Issue by ahmadmssm** [jitpack/jitpack.io#5599]
Please provide:

- Link to build log from https://jitpack.io: 
Build is not triggered.

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?
The project is built successfully without any problems but the command `./gradlew install` is invalid.

- What error are you seeing?
Build is not triggered.

Thank you!

**Comment by jcurtis06** [comment]
I am also having this issue. GitHub releases get built, however, snapshot builds from the latest commit do not. No logs are produced.

Here is the link to my project:
https://jitpack.io/#jcurtis06/Kodot

![image](https://user-images.githubusercontent.com/77545656/235522003-4d0d27d4-9005-4a7d-a69b-55d529383426.png)
![image](https://user-images.githubusercontent.com/77545656/235522084-bee2bf74-3e4a-4b3a-a40b-5d27a8373927.png)

**Comment by ahmadmssm** [comment]
Thanks @jcurtis06, Their support is not replying to all my requests and emails.
