### ISSUE TITLE
Android build fails with Xmx6g memory

### ISSUE THREAD

**Issue by sukitha-accolade** [jitpack/jitpack.io#5601]
Looks like the build container does not have enough memory to run the project. Is there a way I can request to increase it? The project needs `org.gradle.jvmargs=-Xmx6g`

- Link to build log from https://jitpack.io/com/github/konciergeMD/plushcore-android/dev~core-b893c04f95-1/build.log

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ? yes, builds successfully with ./gradlew clean -Pgroup=com.github.konciergeMD -Pversion=0.0.5 -xtest -xlint assemble  publishToMavenLocal

- What error are you seeing? Exit code: 137
⚠️ ERROR: No build artifacts found

Thank you!

**Comment by chris-accolade** [comment]
Any updates on this?  I also sent an email to JitPack and have not yet gotten a response.  If we are unable to resolve this, we may have to drop our JitPack subscription and look at another solution.

**Comment by chris-accolade** [comment]
Any updates on this?  My company is willing to pay more for a higher tier with more memory.
