### ISSUE TITLE
Error preparing SDK package Android SDK Platform 33: No space left on device.

### ISSUE THREAD

**Issue by hrodrick** [jitpack/jitpack.io#5617]
- Link to build log from https://jitpack.io : https://jitpack.io/com/github/rootstrap/FlowForms/1.4.1/build.log

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ? Didn't tried it with the very same commands, but given the error (insufficient disk space) I assume it will work correctly, specially because it failed installing android SDK 33 and I already have it locally 😅.

- What error are you seeing?
Preparing "Install Android SDK Platform 33 (revision: 2)".
Warning: An error occurred while preparing SDK package Android SDK Platform 33: No space left on device.:
java.io.IOException: No space left on device

Additional note: This is happening on the release 1.4.1 of this Open Source project https://github.com/rootstrap/FlowForms, so if needed anyone can try to build it locally too, but given the error it shouldn't be needed 🤔 

Thank you!

**Comment by lsafer-meemer** [comment]
I am having the same issue here...
