### ISSUE TITLE
apache/commons-lang/ 8eef2fc922 build (maven enforcer)

### ISSUE THREAD

**Issue by czmdav** [jitpack/jitpack.io#5618]
**Describe the bug**
A project build requires maven version at least "3.6.3" (your's is running on "3.6.1"), and all versions from this point leads to failed builds.

**To Reproduce**
1. Go to 'https://jitpack.io/com/github/apache/commons-lang/8eef2fc922/build.log'
2. Scroll down to 'The bottom'
3. See error

**Expected behavior**
The project build succeeds.

**Screenshots**
![image](https://github.com/jitpack/jitpack.io/assets/18117740/fe4292cd-26b9-4beb-b853-020a0c1120a9)

**Additional context**
The [apache/commons-parent](https://github.com/apache/commons-parent) version was updated of the [apache/commons-lang](https://github.com/apache/commons-lang) at the following commit: [5a825de27d25589a04a6c36f7524580ce7d5d3ae](https://github.com/apache/commons-lang/commit/5a825de27d25589a04a6c36f7524580ce7d5d3ae)
In the new version of [apache/commons-parent](https://github.com/apache/commons-parent), the enforcer rule for maven version was updated to be at least "3.6.3", which you can see in the following commit: [f25740fcd0cc39203be60ea571505e6e78e478ee](https://github.com/apache/commons-parent/commit/f25740fcd0cc39203be60ea571505e6e78e478ee)

Can you please update your Maven version to use at least "3.6.3".

**Comment by codejanovic** [comment]
Hey @czmdav,
how did you solve the maven version issue on Jitpack?
Running into the same issue as the current maven compiler plugin also requires version 3.6.3 and higher.

Cheers

**Comment by czmdav** [comment]
I used the latest commit's hash from the required repository, which had a lower compiler-plugin version, still supported by lower versions of maven.
Other than this, I had to wait for the release of the artifact, so I don't use jitpack anymore.
