### ISSUE TITLE
MariaDB4j/mariaDB4j-2.2.0 build: How to choose the Maven version jitpack.io uses in jitpack.yml?

### ISSUE THREAD

**Issue by vorburger** [jitpack/jitpack.io#563]
Log https://jitpack.io/com/github/vorburger/MariaDB4j/mariaDB4j-2.2.0/build.log

Failure is due to Maven version; this build works with mvn -version Apache Maven 3.3.9, but fails with the very old Apache Maven 3.2.5 which you are using.

It would be great if it was possible to specify the Maven version in jitpack.yml?

**Comment by vorburger** [comment]
I'm stupid! That error was NOT because of the Maven but because of the Java version used to build this project ... in this particular project, maven-compiler-plugin config. in its pom.xml says 1.6 but it then uses the maven-checkstyle-plugin which req. Java 7 already.

https://jitpack.io/docs/BUILDING/#java-version will probably fix this; I'll just try.

Upgrading the Maven version you use would still be cool though?

**Comment by jitpack-io** [comment]
Looks like maven wrapper support would be useful in this case too #593

**Comment by vorburger** [comment]
I'm not sure what you've done, but somehow it works now ... see e.g. https://jitpack.io/com/github/vorburger/MariaDB4j/mariaDB4j-2.2.1/build.log - it's now suddenly running under with Java version: 1.8.0_101 after all, so now it seems to respect https://github.com/vorburger/MariaDB4j/blob/master/jitpack.yml. Unless you just changed the default for everyone?

**Comment by jitpack-io** [comment]
@vorburger Yes, we've upgraded to 1.8.0_101 but if you like you can also use the Maven Wrapper. It is supported now.
