### ISSUE TITLE
AdsSdkLibs/1.0 build

### ISSUE THREAD

**Issue by ptreasuresoftsolution** [jitpack/jitpack.io#5666]
Please provide:
issue
 Gradle 'publishToMavenLocal' task not found. Please add the 'maven-publish' or 'maven' plugin.

- Link to build log from https://jitpack.io

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?

- What error are you seeing?

Thank you!

**Comment by amitresearchdev** [comment]
Yes its working on my project and its also creating POM file in the local.

**Comment by ptreasuresoftsolution** [comment]
Set in:
build.gradle

android {
  compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

afterEvaluate {
    publishing {
        publications {
            release(MavenPublication) {
                groupId = 'com.github.ptreasuresoftsolution'
                artifactId = 'AdsSdkLibs'
                version = '1.0.9'
                artifact(bundleReleaseAar)
            }
        }
    }
}


issue is solve and working successfully
