### ISSUE TITLE
KotlinAudio/v0.1.29 build

### ISSUE THREAD

**Issue by ismailassa** [jitpack/jitpack.io#5669]
An issue happend when building KotlinAudio/v0.1.29

Link to build log: https://jitpack.io/com/github/DoubleSymmetry/KotlinAudio/v0.1.29/build.log

The project does build locally with (/gradlew install)

I think it's happening because there is no space left on the server as I see this
`java.io.IOException: No space left on device`

**Comment by shivamp2404** [comment]
how you have fixed this? @ismailassa
