### ISSUE TITLE
Could not get resource from jitpack.io

### ISSUE THREAD

**Issue by aplixy** [jitpack/jitpack.io#5679]
Hi there, 
After I update my gradle file version from gradle-5.6.4-all.zip to gradle-6.1.1-all.zip in Android Studio flamingo, it showed the below infomation:

`Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not resolve com.github.LuckSiege.PictureSelector:picture_library:v2.2.3.
     Required by:
         project :app
      > Could not resolve com.github.LuckSiege.PictureSelector:picture_library:v2.2.3.
         > Could not get resource 'https://jitpack.io/com/github/LuckSiege/PictureSelector/picture_library/v2.2.3/picture_library-v2.2.3.pom'.
            > Could not HEAD 'https://jitpack.io/com/github/LuckSiege/PictureSelector/picture_library/v2.2.3/picture_library-v2.2.3.pom'.
               > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target`

I think I have the correct configuration in my build.gradle file of root project directory like below:
`allprojects {
    repositories {
        google()
        jcenter()
        maven { url 'https://jitpack.io' }
    }
}`

But it's still not working and shows the same issue, how could I do without downgrading the gradle file to an old version?

**Comment by mirse** [comment]
me too

**Comment by alex5241** [comment]
me too.And  i also find , all packages from  https://gitpack.io  and https://www.gitpack.io  are not avaliable.
when i ping  https://www.gitpack.io ,i got  Unknown host error. I am from China , i can not get any packages now.
Anyone can help me  or give me another solution?

**Comment by Lancerer** [comment]
> me too.And i also find , all packages from https://gitpack.io and https://www.gitpack.io are not avaliable. when i ping https://www.gitpack.io ,i got Unknown host error. I am from China , i can not get any packages now. Anyone can help me or give me another solution?

How was it solved？

**Comment by Despical** [comment]
Still can't build or download any of my projects using Jitpack. When I try to build any package it time outs after 20 minutes.

**Comment by liuqi19-tal** [comment]
me too  ..so who solved it ?

**Comment by aplixy** [comment]
> 

2 ways you can try: 
(1) Use mavenCentral() in your build.gradle file in root project, because jcenter() is no longer upgrade any more, maybe the newer gradle version plugin refuse to find relience packages from jcenter(), and jitpack.io happenly don't have the package you need.
(2) Use old version of gradle-wrapper and old version of Java, maybe that was my solution which I don't remember clearly, but not too old version, when I use Java 1.8.0_51, it still report error message, when I use Java 1.8.0_92, it worked well.

**Comment by aplixy** [comment]
> me too.And i also find , all packages from https://gitpack.io and https://www.gitpack.io are not avaliable. when i ping https://www.gitpack.io ,i got Unknown host error. I am from China , i can not get any packages now. Anyone can help me or give me another solution?

不是网的问题，可能是新版Gradle插件不支持从旧的库中获取依赖导致的，试试把mavenCentral()配置到根目录的build.gradle文件或者使用旧的gradle-wrapper，把Java版本也降一下，我也不太清楚为什么Java版本会影响依赖的获取，但是我把gradle降到5.6.4，Java版本都降到1.8.0_92以后就可以了，一定要到Oracle官网下载Java安装包走安装流程，千万不要图省事拷贝一个jdk包

**Comment by aplixy** [comment]
> me too

Try to downgradle your gradle version and java version

**Comment by liuqi19-tal** [comment]
用加速器就可以。什么配置都不用改&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: "xinyuli"; 
Date: 2023年6月29日(星期四) 下午5:52
To: "jitpack/jitpack.io"; 
Cc: "liuqi19-tal"; "Comment"; 
Subject: Re: [jitpack/jitpack.io] Could not get resource from jitpack.io (Issue #5679)

&nbsp;


  
me too.And i also find , all packages from https://gitpack.io and https://www.gitpack.io are not avaliable. when i ping https://www.gitpack.io ,i got Unknown host error. I am from China , i can not get any packages now. Anyone can help me or give me another solution?
  
不是网的问题，可能是新版Gradle插件不支持从旧的库中获取依赖导致的，试试把mavenCentral()配置到根目录的build.gradle文件或者使用旧的gradle-wrapper，把Java版本也降一下，我也不太清楚为什么Java版本会影响依赖的获取，但是我把gradle降到5.6.4，Java版本都降到1.8.0_92以后就可以了，一定要到Oracle官网下载Java安装包走安装流程，千万不要图省事拷贝一个jdk包
