### ISSUE TITLE
Seemingly infinite build time with empty log

### ISSUE THREAD

**Issue by afollestad** [jitpack/jitpack.io#569]
The latest version of one of my libraries has been "building" for quite a while now, and the log is empty:

https://jitpack.io/#afollestad/material-camera

**Comment by afollestad** [comment]
@jitpack-io also, an empty red error box appears if I try to delete (unbuild?) a version:

![capture](https://cloud.githubusercontent.com/assets/1820165/15132549/78ae971e-1620-11e6-916a-251d4b98fdb7.JPG)

**Comment by jitpack-io** [comment]
Hi,

Looks like 0.2.6 is built now
