### ISSUE TITLE
EsotericSoftware/kryonet/kryonet-2.21 build issue

### ISSUE THREAD

**Issue by Ivanov-Alexander** [jitpack/jitpack.io#57]
Log https://jitpack.io/com/github/EsotericSoftware/kryonet/kryonet-2.21/build.log

**Comment by jitpack-io** [comment]
Thanks for getting in touch!
Looks like that version didn't have a build file.
You could try this: https://jitpack.io/#EsotericSoftware/kryonet/7f97676829
or maybe ask the owner to create a new GitHub release.

**Comment by Ivanov-Alexander** [comment]
Thank You.

**Comment by jitpack-io** [comment]
Welcome!
