### ISSUE TITLE
401 on public repository

### ISSUE THREAD

**Issue by humblehacker** [jitpack/jitpack.io#5704]
**Describe the bug**
For the past few days, I've been getting a 401 trying to load a public dependency:
- https://github.com/cachapa/ExpandableLayout
- https://jitpack.io/#cachapa/ExpandableLayout/2.9.2

**To Reproduce**
1. `curl -I https://jitpack.io/net/cachapa/expandablelayout/expandablelayout/2.9.2/expandablelayout-2.9.2.pom`

**Expected behavior**
Normal response to HEAD request

**Observed behavior**
```
HTTP/2 401
date: Thu, 22 Jun 2023 15:52:42 GMT
content-type: text/plain; charset=utf-8
content-length: 35
cf-ray: 7db5a8f2f932c49b-SEA
cf-cache-status: BYPASS
cache-control: no-cache, no-store, must-revalidate, private
expires: 0
vary: Accept-Encoding
www-authenticate: Basic realm="JitPack"
artifact: net.cachapa.expandablelayout:expandablelayout:2.9.2
pragma: no-cache
x-jp-cf: 1
report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=3BtrK5ezVRkzKbcl8gzrPDgTXi%2FA1%2B2TIV6zeR5BOSOg1%2FdzNKbQ8h8qS%2FHRBhBgLqU%2Bp%2FPoXxDxNIXraX6sdVHIir9gxB7kW0VpYNgDfBVVo86CXD9ExwdqC24%3D"}],"group":"cf-nel","max_age":604800}
nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
server: cloudflare
```

**Screenshots**
<img width="1003" alt="Screenshot 2023-06-22 at 8 42 30 AM" src="https://github.com/jitpack/jitpack.io/assets/117582/44a54ab6-feef-4224-bc04-a5ca920e94e6">

**Comment by Angelhandy** [comment]
Same problem

**Comment by rackami** [comment]
@jitpack-io can you help with this?

**Comment by puttonous** [comment]
same problem found. any workarounds/fixes?

**Comment by avaneeshtripathi** [comment]
What's happening here! Builds are blocked. 😢

**Comment by stonefarmer9** [comment]
Currently having the same issue , built fine locally and in appcenter on wednesday. Thursday through to today getting:

Could not resolve all files for configuration ':app:releaseRuntimeClasspath'.
Could not resolve com.github.barteksc:android-pdf-viewer:2.8.2.
Required by:
project :app > project :react-native-view-pdf
> Could not resolve com.github.barteksc:android-pdf-viewer:2.8.2.
> Could not get resource 'https://www.jitpack.io/com/github/barteksc/android-pdf-viewer/2.8.2/android-pdf-viewer-2.8.2.pom'.
> Could not GET 'https://www.jitpack.io/com/github/barteksc/android-pdf-viewer/2.8.2/android-pdf-viewer-2.8.2.pom'. Received status code 401 from server: Unauthorized

Have used GradlePluginPortal and did not resolve the issue.

**Comment by manindertwin** [comment]
@jitpack-io Any Updates on this? Getting this issue from yesterday.

**Comment by PaulNeesham** [comment]
Having same issue for: 
`androidmads.library.qrgenearator:QRGenearator:1.0.4`
and
`com.github.barteksc:android-pdf-viewer:3.2.0-beta.1`

**Comment by sp0rk** [comment]
Same for 
`com.tonyodev.fetch2:fetch2:3.0.12`
and 
`com.github.stfalcon:stfalcon-imageviewer:1.0.1`

None of them seem to be available in other maven repos. 
Guess we need to wait for Jitpack's response or statically import the dependencies in our projects.

**Comment by charliecook2** [comment]
It looks like it could be related to this: https://status.gradle.com/?utm_source=embed

**Comment by humblehacker** [comment]
According to https://status.gradle.com/incidents/7x4wqd7zv715:

> JCenter is now serving artifacts again. 

Let's see if things go back to normal

**Comment by humblehacker** [comment]
My builds are again succeeding. I'm closing this.
