### ISSUE TITLE
Can not be able to build any project

### ISSUE THREAD

**Issue by Despical** [jitpack/jitpack.io#5710]
Hi there,

I can not be able to download any of my libraries from Jitpack. I've also tried with Gradle and still couldn't be able to download. Here is a [build log](https://jitpack.io/com/github/Despical/CommandFramework/9.9.9/build.log) of one of my recent project which timed out after 20 minutes. The issue started yesterday and still continuing.

Many thanks.

**Comment by liuqi19-tal** [comment]
me too

**Comment by Hu12037102** [comment]
mt too

**Comment by liuqi19-tal** [comment]
so ？ how to fix it?

**Comment by Hu12037102** [comment]
download aar



---Original---
From: ***@***.***&gt;
Date: Mon, Jun 26, 2023 09:07 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [jitpack/jitpack.io] Can not be able to build any project (Issue#5710)




 
so ？ how to fix it?

**Comment by programmelearn** [comment]
我也是

**Comment by yj970** [comment]
me too, jitpack 443

**Comment by SaboAceLuffy** [comment]
jitpack 443

**Comment by zhengzhong1** [comment]
jitpack 443

**Comment by programmelearn** [comment]
有解决方案吗

**Comment by zhengzhong1** [comment]
Connect to jitpack.io:443  failed: (connect failed)

**Comment by Motwelve** [comment]
me too

**Comment by programmelearn** [comment]
你们不要 me too 了，有没有迁移方案推荐一下

**Comment by Motwelve** [comment]
我也想知道有没有啥解决方案，卡了两天了，一行代码没写

**Comment by guoyongshun** [comment]
本地正常，部署到线上就超时，华为云、阿里云服务器都不行，现在对网络有限制了吗？💔

**Comment by liuqi19-tal** [comment]
目前是把包 down 下来了。。。

**Comment by Despical** [comment]
Trying with a different connection solved for me to download packages from Jitpack.

**Comment by zhengzhong1** [comment]
what is different connection ？

**Comment by Despical** [comment]
> what is different connection ？

I used my mobile to connect my pc to internet then I forced Maven to install dependencies again.

**Comment by Hu12037102** [comment]
I can solve it, but the fee is 50 RMB per visit! I kid you not! Need to add vx:1069305953
我能解决，但是收费，50人民币一次！童叟无欺！需要加vx:1069305953

**Comment by Hu12037102** [comment]
I can solve it, but the fee is 100 RMB per visit! I kid you not! Need to add vx:1069305953
我能解决，但是收费，100人民币一次！童叟无欺！需要加vx:1069305953

**Comment by Motwelve** [comment]
换手机wifi能下载一部分库，目前还没跑起来，你们也可以试试

**Comment by programmelearn** [comment]
> I can solve it, but the fee is 100 RMB per visit! I kid you not! Need to add vx:1069305953 我能解决，但是收费，100人民币一次！童叟无欺！需要加vx:1069305953

我也有办法就是麻烦一点

**Comment by programmelearn** [comment]
> 本地正常，部署到线上就超时，华为云、阿里云服务器都不行，现在对网络有限制了吗？💔

本地是缓存，要同步一份到私有库

**Comment by Hu12037102** [comment]
> I can solve it, but the fee is 100 RMB per visit! I kid you not! Need to add vx:1069305953 我能解决，但是收费，100人民币一次！童叟无欺！需要加vx:1069305953



> 

麻烦交给我，你只管用

**Comment by programmelearn** [comment]
> 

需要多长时间解决，我们是在cicd打包

**Comment by programmelearn** [comment]
> > I can solve it, but the fee is 100 RMB per visit! I kid you not! Need to add vx:1069305953 我能解决，但是收费，100人民币一次！童叟无欺！需要加vx:1069305953
> 
> > 
> 
> 麻烦交给我，你只管用

需要多长时间解决，我们是在cicd打包

**Comment by Hu12037102** [comment]
> > > I can solve it, but the fee is 100 RMB per visit! I kid you not! Need to add vx:1069305953 我能解决，但是收费，100人民币一次！童叟无欺！需要加vx:1069305953
> > 
> > 
> > > 
> > 
> > 
> > 麻烦交给我，你只管用
> 
> 需要多长时间解决，我们是在cicd打包

10 分钟内搞定啦

**Comment by programmelearn** [comment]
> > > > I can solve it, but the fee is 100 RMB per visit! I kid you not! Need to add vx:1069305953 我能解决，但是收费，100人民币一次！童叟无欺！需要加vx:1069305953
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > 麻烦交给我，你只管用
> > 
> > 
> > 需要多长时间解决，我们是在cicd打包
> 
> 10 分钟内搞定啦

麻烦同意下好友
