### ISSUE TITLE
gradle 一直处于下载状态,在app中找不到对应的功能.

### ISSUE THREAD

**Issue by shenzhinishimeng** [jitpack/jitpack.io#5711]
我按照文档进行配置,在我的电脑无法添加1.0.4依赖, 但是我的朋友的电脑可以. 
![image](https://github.com/jitpack/jitpack.io/assets/23020269/07925b52-17f3-4713-8d30-de4765d32b10)

**Comment by programmelearn** [comment]
这是我建的QQ群833710991，集思广益进群讨论一下，jitpack应该不行了
