### ISSUE TITLE
Jitpack Server is down unable download

### ISSUE THREAD

**Issue by GomajiAlanLee** [jitpack/jitpack.io#5727]
Please provide:

- Link to build log from https://jitpack.io

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?

- What error are you seeing?

Could not determine the dependencies of task ':app:compileDevDebugKotlin'.
> Could not resolve all files for configuration ':app:devDebugRuntimeClasspath'.
   > Could not resolve com.github.gomaji:KLog:-SNAPSHOT.
     Required by:
         project :app
      > Could not resolve com.github.gomaji:KLog:-SNAPSHOT.
         > Unable to load Maven meta-data from https://dl.bintray.com/patrickfav/maven/com/github/gomaji/KLog/-SNAPSHOT/maven-metadata.xml.
            > Could not GET 'https://dl.bintray.com/patrickfav/maven/com/github/gomaji/KLog/-SNAPSHOT/maven-metadata.xml'.
               > dl.bintray.com: nodename nor servname provided, or not known
   > Could not resolve com.github.gomaji:material-calendarview:-SNAPSHOT.
     Required by:
         project :app
      > Could not resolve com.github.gomaji:material-calendarview:-SNAPSHOT.
         > Unable to load Maven meta-data from https://dl.bintray.com/patrickfav/maven/com/github/gomaji/material-calendarview/-SNAPSHOT/maven-metadata.xml.
            > Could not GET 'https://dl.bintray.com/patrickfav/maven/com/github/gomaji/material-calendarview/-SNAPSHOT/maven-metadata.xml'.
               > dl.bintray.com

Thank you!

**Comment by jitpack-io** [comment]
Hi

Are you still seeing this issue? Seems to be working at the moment:
https://jitpack.io/com/github/gomaji/KLog/-SNAPSHOT/maven-metadata.xml
