### ISSUE TITLE
Getting subscription error while making build even though we have Yearly plan subscribed

### ISSUE THREAD

**Issue by urbanclap-admin** [jitpack/jitpack.io#5731]
Please provide:

- Link to build log  - https://jitpack.io/com/github/urbanclap-admin/android-orion/0575d663ea/build.log

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) - yes

- What error are you seeing?
Subscription is not active right now
Requested subscription: github.com/urbanclap-admin. 
Your subscriptions are listed in https://jitpack.io/w/user
Please contact Support or repository admins if you need assistance.

Thank you!

**Comment by urbanclap-admin** [comment]
@jitpack-io please help here on priority

**Comment by urbanclap-admin** [comment]
status changed to inactive for our account
<img width="797" alt="image" src="https://github.com/jitpack/jitpack.io/assets/12625531/63f005fe-70dc-41f3-a0a3-c87c3b38a4e3">

You can clearly see the start date for Yearly plan subscription is - Wed, 17 May 2023

@jitpack-io kindly help here at the earliest as our app releases our blocked due to this

**Comment by urbanclap-admin** [comment]
Also not able to access old generated builds as well!

**Comment by urbanclap-admin** [comment]
Also, we did not receive the invoice for the same this time, like last year.
@jitpack-io please help

**Comment by urbanclap-admin** [comment]
@jitpack-io any help here?

**Comment by jitpack-io** [comment]
Hi

Replied to the Support ticket. Should be resolved now as the subscription shows up as active.

Happy building!
