### ISSUE TITLE
API returning an Empty Object

### ISSUE THREAD

**Issue by CoolDCB** [jitpack/jitpack.io#5735]
**Describe the bug**
I have a build on my jitpack but the api (https://jitpack.io/api/builds/com.github.cooldcb/GardeningTweaks/latestOk) is returning an empty object

**To Reproduce**
1. Go to 'https://jitpack.io/api/builds/com.github.cooldcb/GardeningTweaks/latestOk'
2. See issue

**Expected behavior**
Expected it to return something along the lines of:
```
{
  "status" : "ok",
  "message" : "Not found",
  "time" : 0000000000000,
  "isTag" : true,
  "commit" : "xxxxxxxxxxxxxxxxx",
  "private" : false,
  "version" : "1.3"
}
```

**Comment by jitpack-io** [comment]
Hi

Should be resolved now.
