### ISSUE TITLE
Subscription error, despite having subscription

### ISSUE THREAD

**Issue by JohnRucker4** [jitpack/jitpack.io#5736]
Good morning.
My team and I are trying to use a library in a different project, but we are running into subscription errors, even though we have a subscription that covers the library.

- **Link to build log from https://jitpack.io**
     - https://jitpack.io/com/github/blinkupsdk/bLinkupAndroidSDK/1.0.1/build.log

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?
     - The project syncs in both Android Studio and Terminal, but stops building when it gets to  checking Debug Aar Meta data

- What error are you seeing?
     - Could not GET 'https://jitpack.io/com/github/blinkupsdk/bLinkupAndroidSDK/1.0.1/bLinkupAndroidSDK-1.0.1.pom'. Received status code 403 from server: Forbidden

Thank you!

**Comment by jitpack-io** [comment]
Hi

Replied to your Support ticket.
