### ISSUE TITLE
plugin_projet/8.0.2-alpha.3 build

### ISSUE THREAD

**Issue by tezov** [jitpack/jitpack.io#5740]
Please provide:

- Link to build log from https://jitpack.io

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?

- What error are you seeing?

Thank you!

**Comment by hannesa2** [comment]
This issue comes without useful info. In this state it's pointless and noise

**Comment by hannesa2** [comment]
It's still open

**Comment by hannesa2** [comment]
It's still open
