### ISSUE TITLE
Account status is INACTIVE from yesterday and i have yearly subscription

### ISSUE THREAD

**Issue by gouravspyne** [jitpack/jitpack.io#5747]
Please provide:

- Link to build log from https://jitpack.io
 https://jitpack.io/com/github/Spyne-Tech/spyne-food-sdk/ecbe2c090c/build.log

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?
Nope

- What error are you seeing?
Subscription is not active right now
Requested subscription: github.com/spyne-tech. 
Your subscriptions are listed in https://jitpack.io/w/user
Please contact Support or repository admins if you need assistance.

Hi Team,

I hope you're doing well. I'm writing to address an urgent concern regarding our Jitpack account.

Yesterday, our account suddenly became inactive despite having an active yearly plan that started in February 2023. Due to this confusion, our team made an additional payment today, thinking that the subscription has expired. However, even after the second payment, the account remains inactive.

We kindly request your immediate assistance in resolving the following issues:
1. Please investigate and rectify the reason for our account being inactive since yesterday. We need it to be reactivated urgently.
2. As we made an unintentional duplicate payment, we would appreciate a prompt refund to the same source account.

Account details:
Email- [tech@spyne.ai](mailto:tech@spyne.ai)

Our usage of Jitpack is crucial for our client Swiggy and its restaurant partners. Due to the account's inactive status, their services have been disrupted since yesterday.

We sincerely request your quick action to address this matter and restore our account's functionality. Thank you for your understanding and support.

Best regards,
Gourav
Team Lead, Spyne.Ai

**Comment by gouravspyne** [comment]
Hi @jitpack-io 
Please check the below screenshots, after making the payment again I received a mail that your subscription is active and ready for use but the status on my Jitpack account is still inactive.


<img width="1161" alt="Screenshot 2023-07-17 at 7 24 29 PM" src="https://github.com/jitpack/jitpack.io/assets/80242080/2279f4a1-17ad-4c6b-91ff-13f14746e0d5">
<img width="1083" alt="Screenshot 2023-07-18 at 12 16 08 PM" src="https://github.com/jitpack/jitpack.io/assets/80242080/9c3c2f12-37d4-4d14-84ee-d28a59762a78">

**Comment by Spyne-Tech** [comment]
Hi @jitpack-io, This was fixed 20 days back and i have yearly subscription. Now today same thing happen again. Need help here. 
Email- tech@spyne.ai
logs- https://jitpack.io/com/github/Spyne-Tech/spyne-food-sdk/6b5c76bad3/build.log

**Comment by tech-app-innovation** [comment]
Hii @jitpack-io  please also my issue the issue is same mentioned by @gouravspyne  please resolve this issue we are losing users


![image](https://github.com/jitpack/jitpack.io/assets/106601695/ae2d14e2-18fb-4282-9263-9d25e599f405)

![image](https://github.com/jitpack/jitpack.io/assets/106601695/36ce3f12-b087-4185-8f2c-17b9332d61e9)

![Screenshot_18](https://github.com/jitpack/jitpack.io/assets/106601695/b8f08b6d-9aa8-4d20-bf49-fc39d59b0335)

**Comment by tech-app-innovation** [comment]
@gouravspyne  please share jitpack support email 
Thanks in advance
