### ISSUE TITLE
Jitpack is not able to finish the build

### ISSUE THREAD

**Issue by VictorAlbertos** [jitpack/jitpack.io#575]
Hi :)

I've been using jitpack for all my libraries and this is the first time that something like that happened. 

The previous build worked fine:
https://jitpack.io/com/github/VictorAlbertos/RxGcm/0.2.4/build.log

But the last one is not finishing: 
https://jitpack.io/com/github/VictorAlbertos/RxGcm/0.2.5/build.log

All builds:
https://jitpack.io/#VictorAlbertos/RxGcm

Thanks!

**Comment by marcohc** [comment]
The same here:

https://jitpack.io/com/github/marcohc/android-clean-architecture/2.9.0/build.log

**Comment by dmccrory-efl** [comment]
Same issue:
https://jitpack.io/com/github/eflglobal/applicant-journey-sdk-core-android/-SNAPSHOT/build.log

**Comment by kassisdion** [comment]
Same here:
https://jitpack.io/com/github/kassisdion/Android-animated-toolbar/v1.1.0/build.log

**Comment by kassisdion** [comment]
Now working

**Comment by VictorAlbertos** [comment]
Thanks @kassisdion 

It's working now.

**Comment by dmccrory-efl** [comment]
@VictorAlbertos thanks for the update on this issue. It seems to resolve the issue for some of our repos but not others. Check https://jitpack.io/com/github/eflglobal/discovery-module-consumer-mobileusage-mobile/-SNAPSHOT/build.log (private repo) for an example of repo that JitPack isn't finishing the build on.

**Comment by VictorAlbertos** [comment]
Ok! I'll leave it open until @jitpack-io closes it.

**Comment by dmccrory-efl** [comment]
it's working for us now. this can be closed.
