### ISSUE TITLE
Account status is INACTIVE from yesterday and i have yearly subscription

### ISSUE THREAD

**Issue by amitresearchdev** [jitpack/jitpack.io#5761]
Please provide:

- Link to build log from https://jitpack.io
- https://jitpack.io/org/bitbucket/amitresearchdev/AdsSdkMaster/1.8-alpha19/build.log

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?
- yes

- What error are you seeing?

My account is showing inactive. Please see the screenshot

![image](https://github.com/jitpack/jitpack.io/assets/45256092/ba53bc33-7d05-4fe5-80d5-63dd5e2ed6b2)

And if click to see the build log it give the error below

**Subscription is not active right now
Requested subscription: bitbucket.org/amitresearchdev. 
Your subscriptions are listed in https://jitpack.io/w/user
Please contact Support or repository admins if you need assistance.**

Build log : https://jitpack.io/org/bitbucket/amitresearchdev/AdsSdkMaster/1.8-alpha19/build.log

I also got the email for the upgrade as my trial is expired but i have early subscription. 

![image](https://github.com/jitpack/jitpack.io/assets/45256092/f4815c05-33c6-4a67-a618-f5294e9b17f2)

I have already mailed you Invoice and receipt copy -> jitpack@jitpack.io

Please resolve this on the priority basis as we have to rollout new build.

Thank you!

**Comment by Spyne-Tech** [comment]
Hi, Im facing the same issue and this happened second time in last one month. Please fix this issue on priority @jitpack-io 
Account details and logs-
logs- https://jitpack.io/com/github/Spyne-Tech/spyne-food-sdk/6b5c76bad3/build.log
Email- tech@spyne.ai
