### ISSUE TITLE
jadx/v0.6.0 build

### ISSUE THREAD

**Issue by fschrofner** [jitpack/jitpack.io#579]
Unfortunately it tries to build the test-app instead of the actual project.

Log https://jitpack.io/com/github/skylot/jadx/v0.6.0/build.log

**Comment by jitpack-io** [comment]
Hi,

It should work if you add the android-maven plugin
https://jitpack.io/docs/ANDROID/

**Comment by fschrofner** [comment]
No, the problem is, that the project itself is not an android project, but a library/application that allows you to extract android applications. The test-app is just there for testing purposes, but jitpack tries to build it. I'm pretty sure now, that this is not an issue with jitpack itself (I just had different expectations), so this can be closed now.

Anyhow, I got it to work by forking the repository and removing everything I did not need. But then I ran into issue #383
