### ISSUE TITLE
ksoichiro/Android-ObservableScrollView/v1.5.1 build issue

### ISSUE THREAD

**Issue by Bernix01** [jitpack/jitpack.io#58]
Log https://jitpack.io/com/github/ksoichiro/Android-ObservableScrollView/v1.5.1/build.log

also v1.5.0  generates error on build "com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Program Files\Java\jdk1.8.0_45\bin\java.exe'' finished with non-zero exit value 2"

**Comment by jitpack-io** [comment]
Indeed it was building with the wrong java version.
Fixed now: https://jitpack.io/#ksoichiro/Android-ObservableScrollView

Thanks for opening the issue!
