### ISSUE TITLE
Older version of library "build OK, file not found"

### ISSUE THREAD

**Issue by Zhuinden** [jitpack/jitpack.io#5800]
**Describe the bug**
An old version of library is no longer available for download to consumers, even though the project, release, and library still exist.

**To Reproduce**

Try downloading com/github/Zhuinden/simple-stack/1.12.0/simple-stack-1.12.0.aar

From https://jitpack.io/#Zhuinden/simple-stack/1.12.0

**Expected behavior**

The dependency AAR shouldn't "magically disappear" from Jitpack.

**Additional context**

There is no way to force a rebuild of the artifact.

**Comment by Zhuinden** [comment]
That's not exactly my fault, is it?

**Comment by Zhuinden** [comment]
@jitpack-io  does anyone still monitor this?

**Comment by Zhuinden** [comment]
This issue is not stale.

**Comment by LaurynasM-iproyal** [comment]
Noticed same issue. Only the latest release version is available to download, previous version cannot be resolved

**Comment by Zhuinden** [comment]
Well that sure is one way to "fix bugs", isn't it..
