### ISSUE TITLE
abstracraft/1.0 build

### ISSUE THREAD

**Issue by orbyfied** [jitpack/jitpack.io#5824]
- [Build Log](https://jitpack.io/com/github/redstonetools/abstracraft/aba1d87bb0/build.log)
- `gradlew install` works fine on my machine
- `Could not create service of type ScriptPluginFactory using BuildScopeServices.createScriptPluginFactory().`

Thank you!

**Comment by SHamzaHMergn** [comment]
Any further updates on the issue ?

**Comment by orbyfied** [comment]
nah i ended up fixing it it hink
