### ISSUE TITLE
nmmp/1.3.0 build

### ISSUE THREAD

**Issue by timscriptov** [jitpack/jitpack.io#5865]
Please provide:

- Link to build log from https://jitpack.io
- https://jitpack.io/com/github/TimScriptov/nmmp/1.3.0/build.log

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?

- What error are you seeing?

Thank you!

**Comment by TimScriptov** [comment]
https://github.com/TimScriptov/nmmp
