### ISSUE TITLE
Collapsible-Calendar-View-Android/2.0.33 build

### ISSUE THREAD

**Issue by jjchan1** [jitpack/jitpack.io#5884]
Please provide:

- Link to build log from https://jitpack.io
https://jitpack.io/com/github/hyperexternal/Collapsible-Calendar-View-Android/2.0.33/build.log

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?
Yes

- What error are you seeing?
ERROR: Time-out getting container status

Thank you!

**Comment by shalva97** [comment]
It's weird, there are 38 issues similar to this and they all get auto closed
