### ISSUE TITLE
Improve Maven example

### ISSUE THREAD

**Issue by php-coder** [jitpack/jitpack.io#59]
In Maven example site suggests to add the following:
```xml
<repository>
    <id>jitpack.io</id>
    <url>https://jitpack.io</url>
</repository>
```
But it's not enough, because Maven complains about ` Unrecognised tag: 'repository'`.

So, I suggest to add also tag `<repositories>` to example.

**Comment by jitpack-io** [comment]
Did you mean the maven snippet on the website or in the example projects https://github.com/jitpack/maven-simple ? or both? : )

**Comment by php-coder** [comment]
I've tried example from the site, but most likely it's better to update both of them.

**Comment by jitpack-io** [comment]
Yes, good point. Updated the maven example project. The only concern is that extra xml will add more verbosity to the website and it will take more space. It's just some things we'd prefer to avoid. Need to do some planning on how to present it nicely

**Comment by jitpack-io** [comment]
Added
