### ISSUE TITLE
Support Maven wrapper

### ISSUE THREAD

**Issue by bsideup** [jitpack/jitpack.io#593]
Hi!

There is Maven wrapper project similar to Gradle wrapper:
https://github.com/takari/maven-wrapper

Would be great if JitPack will support it to allow users to control Maven version

**Comment by KostyaSha** [comment]
Guys, specifying maven version is **critical** because maven 3.3 has regressions in reactor ordering during shading operations. Also i want run the same maven version that i tested locally and don't have accidental updates in build system.

**Comment by jitpack-io** [comment]
Added! If there's  a ./mvnw script in the repository then JitPack will use that instead of mvn.

**Comment by bsideup** [comment]
@jitpack-io this is great! Thank you!

**Comment by KostyaSha** [comment]
Thank you!

**Comment by KostyaSha** [comment]
#621 failed :(
