### ISSUE TITLE
[URGENT & IMPORTANT] We've paid 5 times today for a subscription to be active, and it still says that we're on trial for 15 days

### ISSUE THREAD

**Issue by customerglu-code** [jitpack/jitpack.io#5954]
Please help us setup a call with your customer support to understand why this occurred in the first place, we need a RCA, as it has caused a significant business downtime for us and our customers.

We're also evaluating other package managers if the reliability of Jitpack is in question.

Thanks.

**Comment by jhetrifork** [comment]
@customerglu-code Have you found a solution with help of the Jitpack team or have you looked at a different package manager?
