### ISSUE TITLE
Subscription not active after pay yearly subscription 

### ISSUE THREAD

**Issue by shuftipro** [jitpack/jitpack.io#5962]
Team,
Our finance team renews yearly subscription but my account status is still inactive.
We again subscribe for one month but still payment deducted but account inactive.
Please check this on priority because my client is facing issues.
Thanks
github.com:shuftipro

**Comment by shuftipro** [comment]
@jitpack-io please check now its critical.

**Comment by jitpack-io** [comment]
Hi,

Should be resolved now

**Comment by shuftipro** [comment]
@jitpack-io thank God you finally reply.
Please check my complete issue.
Yesterday i resubscribe my small plan and make annual payment but payment deduct and account still inactive.
We again make monthly payment but now again payment deduct and account still inactive.
Today we again purchase individual plan but again amount deduct and account inactive.

**Comment by shuftipro** [comment]
@jitpack-io Now i don't know my which plan is active now.
Can you please tell me my which plan is active now.
Also please return my additional packages amount that i already send you an email with SS.
Thanks

**Comment by shuftipro** [comment]
Hi Team,
I make below payments
7 Nov = Small Plan for year
7 Nov = Small plan for month
8 Nov = individual Plan for month
Now my account active but individual plan is active.
Can you please activate Small plan for an year and return my monthly plan payment or small and individual.
Thanks

**Comment by jitpack-io** [comment]
Could you please send this via Support button on our website? GitHub is more for tech issues and support for subscriptions.

**Comment by shuftipro** [comment]
@jitpack-io 
We already contacted more than 20 times via Support button but not received any response even i send multiple emails.
But as per your suggestion i will again contact via support button.

**Comment by shuftipro** [comment]
@jitpack-io 
Sorry to tag you again but your team still not change my package details and not reimburse my amount even after contacting various times. Now i am worried about next month and don't know whether i will go through your hectic procedures  or should move towards any other service provider.
Anxiously waiting to enable my yearly subscription of small plan that i already paid and reimbursed other 2 subscription plans amount.

**Comment by sanalogi-admin** [comment]
jitpack is a stupid system. no one cares. there are a lot of bugs. JİTPACK IS SCAM
