### ISSUE TITLE
Inactive Subscription Issue

### ISSUE THREAD

**Issue by FaciaMobile** [jitpack/jitpack.io#5966]
I am facing issues with my subscription. Despite making a payment, my subscription remains inactive. This is affecting my project.
I paid for monthly subscription but it is still Inactive.
It is urgent, please resolve it.
@jitpack-io

**Comment by FaciaMobile** [comment]
@jitpack-io Please have a look on it, it is a critical issue.

**Comment by FaciaMobile** [comment]
@jitpack-io Please have a look on it, it is a critical issue.

**Comment by JoeBakalor** [comment]
@jitpack-io  
We are facing the same issue
https://github.com/onceLabs

**Comment by ahmedsalemelzeiny** [comment]
@jitpack-io We are facing the same issue please we need urgent help https://github.com/MoneyHash

**Comment by ahmedsalemelzeiny** [comment]
@JoeBakalor @FaciaMobile did you find any way to solve it ?

**Comment by sanalogi-admin** [comment]
jitpack is a stupid system. no one cares. there are a lot of bugs. JİTPACK IS SCAM

**Comment by JoeBakalor** [comment]
Problem solved.  We switched to GitHub Packages

**Comment by JoeBakalor** [comment]
> @JoeBakalor @FaciaMobile did you find any way to solve it ?

Switched to Github packages
