### ISSUE TITLE
Jitpack LOST a build

### ISSUE THREAD

**Issue by MFlisar** [jitpack/jitpack.io#5973]
**Describe the bug**
One old version build of one of my libraries suddenly got lost... I know it did work in the past because I used this version quite some time myself.

**To Reproduce**
1. Open https://jitpack.io/com/github/MFlisar/CacheFileProvider/
2. You will see it has a build for 0.2
3. Try to open https://jitpack.io/com/github/MFlisar/CacheFileProvider/0.2/
4. You will get a  "Not found" error

**Expected behavior**
The old build should still be available

**Comment by gchallen** [comment]
I'm seeing failed requests for both old and new builds. Fairly random: some artifacts load, others don't.

After years of using Jitpack I'm moving my projects to Maven Central. Huge PITA, but I feel like Jitpack reliability has worsened recently.

**Comment by riddancegd** [comment]
I'm also experiencing this issue. Our app uses CacheFileProvider 0.2 and we are unable to build without this dependency. I would love to have a solution for this.

**Comment by MFlisar** [comment]
In the meantime the build did vanish completely and trying to open the log file did trigger a rebuild... sadly it does not build anymore because the used gradle version to build the library is not the same anymore as in the past (I assume). Sadly I did not define a gradle wrapper back then when I wrote the problematic version...

**Nevertheless, the successful build did vanish for no reason...**

**Comment by riddancegd** [comment]
Oh no, those are bad news 😓, I think I would need to go for one of the
more hard, time-costly routes. The thing is that we are already super busy
working on other stuff in the app and this just complicates things. I will
talk to the managers and ask just how important it is for them to have log
files emailed lol.
Thanks a lot anyways Michael, this has been extremely helpful. If you know
anything else please let me know, I will appreciate it a lot 🙏

**Comment by qinwang1023** [comment]
I would be very grateful if this issue is resolved.

**Comment by MFlisar** [comment]
This seems to be a bigger issue, I jsut wanted to comile another old oroject of mine, updated gradle from 7 to 8 and tried to compile it and following can not be found anymore:

- https://jitpack.io/com/github/MFlisar/Lumberjack/lumberjack-viewer/5.2.5/lumberjack-viewer-5.2.5.pom
  - although lumberjack-viewer is listed under https://jitpack.io/com/github/MFlisar/Lumberjack/ trying to open https://jitpack.io/com/github/MFlisar/Lumberjack/lumberjack-viewer does not work

Same for https://jitpack.io/com/github/MFlisar/MaterialPreferences/screen-input/0.5.4/screen-input-0.5.4.pom 

And the issue occurs for all modules that belong the respectve library...

**Comment by memoeslink** [comment]
Yes, I am seeing some missing builds as well.

**Comment by memoeslink** [comment]
Yeah, I have some missing builds as well.
