### ISSUE TITLE
Subscription still Inactive after making multiple payments

### ISSUE THREAD

**Issue by plutus-finwizard** [jitpack/jitpack.io#5976]
I have made 2 payments against my subscription but the account still shows inactive subscription.
My clients are not able to add dependency for my SDK and it is impacting us in a major way.
Please look into this asap.

**Comment by plutus-finwizard** [comment]
@jitpack-io Please help me with the resolution. Its really critical for us.

**Comment by ahmedsalemelzeiny** [comment]
@jitpack-io  We are facing the same issue please we need urgent help https://github.com/MoneyHash

**Comment by ahmedsalemelzeiny** [comment]
@plutus-finwizard did you find any way to solve it?

**Comment by jhetrifork** [comment]
@jitpack-io We are also facing the same issue. Can you please respond on your website @jitpack-io or in here? Your product is unusable if you do not have proper support. :(

**Comment by plutus-finwizard** [comment]
> @plutus-finwizard did you find any way to solve it?

@ahmedsalemelzeiny Yes, finally jitpack support team is active. Subscription is active now.

**Comment by sanalogi-admin** [comment]
jitpack is a stupid system. no one cares. there are a lot of bugs. JİTPACK IS SCAM
