### ISSUE TITLE
File not found. Build ok 

### ISSUE THREAD

**Issue by N7ghtm4r3** [jitpack/jitpack.io#5982]
My library contains mostly Java files, but has also one Kotlin file, I don't know if this need situation to be managed, anyway the result is: **File not found. Build ok**

- Log: https://jitpack.io/com/github/N7ghtm4r3/Pandoro/0.0.0.9/build.log
- Result: https://jitpack.io/com/github/N7ghtm4r3/Pandoro/0.0.0.9/Pandoro-0.0.0.9.jar
- Gradle kts (build.gradle.kts):
```
plugins {
    id("java")
    id("maven-publish") 
}

...

afterEvaluate {
    publishing {
        publications {
            create<MavenPublication>("Maven") {
                groupId = "com.tecknobit.pandoro"
                artifactId = "Pandoro"
                version = "0.0.0.7"
                from(components["java"])
            }
        }
    }
}
```

I created a comment also [here](https://github.com/jitpack/jitpack.io/issues/3295)

**Comment by N7ghtm4r3** [comment]
@jitpack-io I know there are other issues to handle, but it's urgent

**Comment by wenerme** [comment]
Same problem for https://jitpack.io/com/github/CarGuo/GSYVideoPlayer/v8.3.5-release-jitpack/
