### ISSUE TITLE
Subscription is still inactive

### ISSUE THREAD

**Issue by devops-buildingengines** [jitpack/jitpack.io#5985]
Please provide:

- Link to build log from https://jitpack.io
  https://jitpack.io/private#org.bitbucket.buildingengines/kmm-module/1.24.17

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?
 Yes

- What error are you seeing?

Subscription is not active right now
Requested subscription: bitbucket.org/buildingengines. 
Your subscriptions are listed in https://jitpack.io/w/user
Please contact Support or repository admins if you need assistance.

I paid for a new subscription but still the subscription is inactive. Can you help here?
<img width="571" alt="Screenshot 2023-11-20 at 8 15 11 PM" src="https://github.com/jitpack/jitpack.io/assets/44210507/e68002bd-4d42-4ce4-9769-32f1ff6b988f">

<img width="1091" alt="Screenshot 2023-11-20 at 8 15 33 PM" src="https://github.com/jitpack/jitpack.io/assets/44210507/5ca09152-29b5-4d6b-a103-2de9913de3b5">

Thank you!

**Comment by devops-buildingengines** [comment]
Hi @jitpack-io  , Can you please look into this urgently? We are blocked from releasing our apps.

**Comment by brunofmf** [comment]
A similar thing happened to me... Any luck with a response from their side?

**Comment by sanalogi-admin** [comment]
jitpack is a stupid system. no one cares. there are a lot of bugs.

**Comment by sanalogi-admin** [comment]
jitpack is a stupid system. no one cares. there are a lot of bugs. JİTPACK IS SCAM

**Comment by maykfery** [comment]
+1
