### ISSUE TITLE
JitPack has charged me both yearly and monthly fees, yet they continue to keep my account inactive. Moreover, their support team has remained unresponsive.

### ISSUE THREAD

**Issue by naphatamity** [jitpack/jitpack.io#5986]
JitPack has charged me both yearly and monthly fees, yet they continue to keep my account inactive. Moreover, their support team has remained unresponsive. How can I get a refund?

<img width="955" alt="Screenshot 2566-11-21 at 17 51 15" src="https://github.com/jitpack/jitpack.io/assets/78838224/be0b85a1-0e53-4945-906a-a12db482621a">

<img width="975" alt="Screenshot 2566-11-21 at 17 52 54" src="https://github.com/jitpack/jitpack.io/assets/78838224/00f07ab1-ab78-4d39-b7e1-df0b391a9dc0">

**Comment by naphatamity** [comment]
they still not responding.. beware for their services.

**Comment by brunofmf** [comment]
A similar thing happened to me... Any luck with a response from their side?

**Comment by naphatamity** [comment]
And this month they charge all of my cards again. Even I removed and unsubsribed everything from them.
They are nothing but Thief !!
