### ISSUE TITLE
Download statistics

### ISSUE THREAD

**Issue by jitpack** [jitpack/jitpack.io#6]
- Download stats API
- Badge with number of downloads

**Comment by vbauer** [comment]
:+1:

**Comment by shkschneider** [comment]
:+1:

**Comment by dbachelder** [comment]
other stats too.. artifact sizes, build times, etc.. even showing that over time.. General project info would be good to.. build history, links to logs, build status, links to artifacts, link to github project

**Comment by shkschneider** [comment]
+1

**Comment by haibison** [comment]
Would it be possible to add this stats to GitHub `README` file? It will be cool  :-D

Thanks,

**Comment by totalvoidness** [comment]
:+1:

**Comment by jitpack-io** [comment]
@haibison Great idea! Right now we're showing download stats on the website but the plan is to make it into an API too. After that adding stats to badges is straightforward.
