### ISSUE TITLE
Add to documentation that we can build from commit

### ISSUE THREAD

**Issue by php-coder** [jitpack/jitpack.io#60]
It's a quote from dialog on gitter:
>is it possible to build certain branch?
>>Hi @php-coder
>>yes, multiple ways
>>you could put a tag on a commit in that branch and then build by that tag
>>or just build by commit id

I suggest to add such feature to documentation because I didn't find it on the site.

**Comment by jitpack-io** [comment]
Thanks for bringing this up! Updated the readme on GitHub https://github.com/jitpack/jitpack.io/commit/b993282b732b608ad97f18592b332250474369d7
