### ISSUE TITLE
INactive account even after I subscribed a plan

### ISSUE THREAD

**Issue by xuuhaoo** [jitpack/jitpack.io#6002]
As the following img, I'm enough of it , need unsubscrib link and refund the pay!!!!!

<img width="1157" alt="image" src="https://github.com/jitpack/jitpack.io/assets/10423664/3492c3c4-a7ce-4cde-aa8b-ca3147b3b6bc">

**Comment by sanalogi-admin** [comment]
jitpack is a stupid system. no one cares. there are a lot of bugs.
