### ISSUE TITLE
Unable to Integrate Older Builds from Private Repository. 

### ISSUE THREAD

**Issue by BeginiMobileDev** [jitpack/jitpack.io#6008]
We are encountering difficulties integrating older builds from our private repository into local projects. Builds which are created more than a week ago are inaccessible, while newer builds integrate seamlessly.

We have published numerous builds under our private repository, but only the most recent ones are accessible for integration. Attempts to integrate older builds result in the following error:

`Failed to resolve: com.github.beg-xxxxxxxx-sdk-android:2.0.0`

This error does not occur when attempting to integrate newer builds.

Additionally, the GitHub repository (Account 1) associated with the build displays an active subscription but indicates a starter plan. Despite paying $21.6 monthly since April 2022, the subscription status remains unchanged.

To address this issue, we also purchased a subscription for another account (Account 2) with admin privileges to the same repository. However, this account also shows an inactive subscription status.

We have attached relevant screenshots to illustrate the issue.

**Expected Behavior**:

Older builds from our private repository should be accessible for integration into local projects without any errors.

**Actual Behavior:**

Older builds from our private repository are inaccessible for integration into local projects, resulting in the error "Failed to resolve: com.github.beg-xxxxxxxx-sdk-android:2.0.0."

Screenshots:
Screenshot of Account 1. (status active but shows starter plan)
![image(2)](https://github.com/jitpack/jitpack.io/assets/102358323/2f2fc039-8cd9-459a-9233-951675feb37e)

Screenshot of Account 2.(status inactive)
![image](https://github.com/jitpack/jitpack.io/assets/102358323/2789d3b9-1f54-4289-b107-5651619aec4d)

We kindly request your assistance in resolving this issue as it is hindering our development progress.

**Comment by mawi-alvarez** [comment]
@jitpack-io kindly help here at the earliest as our client's SDK integration is blocked due to the issues raised above.

**Comment by BeginiMobileDev** [comment]
@jitpack-io  Waiting for your response, Please check the issue.
