### ISSUE TITLE
CircularReveal/2.0.0--try3 build

### ISSUE THREAD

**Issue by ozodrukh** [jitpack/jitpack.io#603]
Log https://jitpack.io/com/github/Ozodrukh/CircularReveal/2.0.0--try3/build.log

**Comment by jitpack-io** [comment]
Hi,

The project is getting compiled with Java 7 but looks like you are using Java 8.
If you'd like to change it then we support configuration in jitpack.yml: https://jitpack.io/docs/BUILDING/#java-version

**Comment by ozodrukh** [comment]
Did it still facing troubles

**Comment by jitpack-io** [comment]
Rebuilt 2.0.0, looks ok now
https://jitpack.io/com/github/ozodrukh/CircularReveal/2.0.0/build.log
