### ISSUE TITLE
Account status InActive

### ISSUE THREAD

**Issue by hetpatel98** [jitpack/jitpack.io#6030]
I renewed my Jitpack.io subscription to the starter pack with the username hetpatel98.

I successfully made a payment for the subscription and I have received confirmation of the payment and the invoice shows under my account. However, when I log into my account, the subscription status is still showing as "inactive." Due to inactive status all my dependencies are throwing 403 errors.

I would appreciate if this can be resolved ASAP.

**Comment by maykfery** [comment]
+1
