### ISSUE TITLE
11

### ISSUE THREAD

**Issue by apusaiiafahmad12** [jitpack/jitpack.io#6078]
<?xml version="1.0" encoding="utf-8"?>
<manifest
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:versionCode="50603"
    android:versionName="5.6.3"
    android:installLocation="auto"
    compileSdkVersion="33"
    compileSdkVersionCodename="13"
    package="eu.thedarken.sdm"
    platformBuildVersionCode="33"
    platformBuildVersionName="13">

    <uses-sdk
        android:minSdkVersion="21"
        android:targetSdkVersion="33"/>
    <uses-permission android:name="android.permission.BROADCAST_CLOSE_SYSTEM_DIALOGS"/>
    <uses-permission android:name="android.permission.READ_MEDIA_STORAGE"/>
    <uses-permission android:name="android.permission.SCHEDULE_EXACT_ALARM"/>
    <uses-permission android:name="android.permission.WRITE_MEDIA_STORAGE"/>
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.KILL_BACKGROUND_PROCESSES"/>
    <uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>
    <uses-permission android:name="android.permission.VIBRATE"/>
    <uses-permission android:name="android.permission.GET_PACKAGE_SIZE"/>
    <uses-permission android:name="android.permission.WAKE_LOCK"/>
    <uses-permission android:name="android.permission.REQUEST_DELETE_PACKAGES"/>
    <uses-permission android:name="com.android.launcher.permission.INSTALL_SHORTCUT"/>
    <uses-permission android:name="android.permission.FOREGROUND_SERVICE"/>
    <uses-permission android:name="android.permission.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS"/>
    <uses-permission android:name="android.permission.POST_NOTIFICATIONS"/>
    <uses-permission android:name="android.permission.CLEAR_APP_CACHE"/>
    <uses-permission android:name="android.permission.PACKAGE_USAGE_STATS"/>
    <uses-permission android:name="android.permission.MANAGE_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.QUERY_ALL_PACKAGES"/>

    <supports-screens
        android:anyDensity="true"
        android:smallScreens="true"
        android:normalScreens="true"
        android:largeScreens="true"
        android:xlargeScreens="true"/>

    <uses-feature
        android:name="android.hardware.touchscreen"
        android:required="false"/>

    <application
        android:theme="@2131886620"
        android:label="@2131820593"
        android:icon="@2131623936"
        android:name="eu.thedarken.sdm.App"
        android:allowBackup="true"
        android:largeHeap="true"
        android:banner="@2131231002"
        android:networkSecurityConfig="@2132017155"
        android:roundIcon="@2131623939"
        appComponentFactory="androidx.core.app.CoreComponentFactory"
        requestLegacyExternalStorage="true"
        preserveLegacyExternalStorage="true">

        <activity
            android:theme="@2131886569"
            android:label="@2131820593"
            android:name="eu.thedarken.sdm.main.ui.SDMMainActivity"
            android:exported="true"
            android:launchMode="singleTop"
            android:configChanges="locale">
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>

        <activity-alias
            android:label="@2131820593"
            android:name="eu.thedarken.sdm.SDMMainHiddenLaunch"
            android:exported="true"
            android:targetActivity="eu.thedarken.sdm.main.ui.SDMMainActivity">
            <intent-filter>
                <category android:name="android.intent.action.MAIN"/>
            </intent-filter>
        </activity-alias>

        <provider
            android:name="androidx.core.content.FileProvider"
            android:exported="false"
            android:authorities="eu.thedarken.sdm.provider"
            android:grantUriPermissions="true">

            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@2132017153"/>
        </provider>

        <activity
            android:theme="@2131886622"
            android:name="eu.thedarken.sdm.main.ui.settings.SettingsActivity"
            android:configChanges="locale"
            android:parentActivityName="eu.thedarken.sdm.main.ui.SDMMainActivity">

            <meta-data
                android:name="android.support.PARENT_ACTIVITY"
                android:value=".main.ui.SDMMainActivity"/>
        </activity>

        <activity
            android:theme="@16973909"
            android:name="eu.thedarken.sdm.oneclick.ShortcutTrickActivity"
            android:finishOnTaskLaunch="true"
            android:noHistory="true"/>
        <activity android:name="eu.thedarken.sdm.main.ui.errors.CoreErrorActivity"/>

        <service
            android:label="SD Maid Worker"
            android:icon="@2131623936"
            android:name="eu.thedarken.sdm.main.core.SDMService"
            android:exported="false"/>
        <service android:name="eu.thedarken.sdm.tools.debug.recording.core.RecorderService"/>

        <activity
            android:theme="@2131886412"
            android:name="eu.thedarken.sdm.setup.core.ui.SetupActivity"
            android:launchMode="singleTop"
            android:configChanges="locale"
            android:parentActivityName="eu.thedarken.sdm.main.ui.SDMMainActivity">

            <meta-data
                android:name="android.support.PARENT_ACTIVITY"
                android:value=".main.ui.SDMMainActivity"/>
        </activity>

        <activity
            android:theme="@2131886619"
            android:label="@2131820768"
            android:name="eu.thedarken.sdm.systemcleaner.ui.filter.FilterManagerActivity"
            android:launchMode="singleTop"
            android:configChanges="locale"
            android:parentActivityName="eu.thedarken.sdm.main.ui.SDMMainActivity">

            <meta-data
                android:name="android.support.PARENT_ACTIVITY"
                android:value=".main.ui.SDMMainActivity"/>
        </activity>

        <activity
            android:theme="@2131886324"
            android:name="eu.thedarken.sdm.main.ui.settings.PersistetUriPermissionActivity"
            android:launchMode="singleTop"
            android:configChanges="locale"
            android:parentActivityName="eu.thedarken.sdm.main.ui.settings.SettingsActivity">

            <meta-data
                android:name="android.support.PARENT_ACTIVITY"
                android:value=".main.ui.SDMMainActivity"/>
        </activity>

        <activity
            android:theme="@2131886623"
            android:name="eu.thedarken.sdm.main.ui.upgrades.UpgradeActivity"
            android:exported="true"
            android:excludeFromRecents="true"
            android:configChanges="locale">
            <intent-filter autoVerify="true">
                <action android:name="android.intent.action.VIEW"/>
                <category android:name="android.intent.category.DEFAULT"/>
                <category android:name="android.intent.category.BROWSABLE"/>

                <data
                    android:scheme="https"
                    android:host="apps.darken.eu"
                    android:path="/inapp/eu.thedarken.sdm/licenses"/>
            </intent-filter>
        </activity>

        <receiver
            android:name="eu.thedarken.sdm.corpsefinder.core.watcher.UninstallWatcherReceiver"
            android:enabled="false"
            android:exported="false">
            <intent-filter>
                <action android:name="android.intent.action.PACKAGE_FULLY_REMOVED"/>
                <data android:scheme="package"/>
            </intent-filter>
        </receiver>

        <receiver
            android:name="eu.thedarken.sdm.scheduler.core.SchedulerReceiver"
            android:exported="false"/>

        <receiver
            android:name="eu.thedarken.sdm.scheduler.core.SchedulerWard"
            android:exported="false">
            <intent-filter>
                <action android:name="android.intent.action.MY_PACKAGE_REPLACED"/>
            </intent-filter>
            <intent-filter>
                <action android:name="android.intent.action.BOOT_COMPLETED"/>
            </intent-filter>
        </receiver>

        <activity
            android:theme="@2131886620"
            android:name="eu.thedarken.sdm.ui.picker.PickerActivity"
            android:configChanges="locale"/>

        <activity
            android:theme="@2131886619"
            android:name="eu.thedarken.sdm.appcontrol.ui.details.AppObjectActivity"
            android:configChanges="locale"/>

        <activity
            android:theme="@2131886619"
            android:name="eu.thedarken.sdm.corpsefinder.ui.details.CorpseDetailsPagerActivity"
            android:configChanges="locale"/>

        <activity
            android:theme="@2131886619"
            android:name="eu.thedarken.sdm.systemcleaner.ui.details.FilterDetailsPagerActivity"
            android:configChanges="locale"/>

        <activity
            android:theme="@2131886619"
            android:name="eu.thedarken.sdm.systemcleaner.ui.filter.user.FilterEditorActivity"
            android:configChanges="locale"/>

        <activity
            android:theme="@2131886619"
            android:name="eu.thedarken.sdm.appcleaner.ui.details.AppCleanerDetailsPagerActivity"
            android:configChanges="locale"/>

        <activity
            android:theme="@2131886619"
            android:name="eu.thedarken.sdm.appcleaner.ui.filter.FilterManagerActivity"
            android:configChanges="locale"/>

        <activity
            android:theme="@2131886619"
            android:name="eu.thedarken.sdm.duplicates.ui.details.DuplicatesDetailsPagerActivity"
            android:configChanges="locale"/>

        <activity
            android:theme="@2131886619"
            android:name="eu.thedarken.sdm.tools.clutter.report.ReportActivity"
            android:configChanges="locale"/>

        <activity
            android:theme="@2131886619"
            android:name="eu.thedarken.sdm.tools.bugs.reporter.ReportActivity"
            android:configChanges="locale"/>

        <activity
            android:theme="@2131886623"
            android:name="eu.thedarken.sdm.tools.debug.recording.ui.RecorderActivity"
            android:configChanges="locale"/>

        <activity
            android:theme="@2131886619"
            android:name="eu.thedarken.sdm.statistics.ui.chronic.ChronicActivity"
            android:configChanges="locale"/>

        <receiver
            android:name="eu.thedarken.sdm.main.core.ExternalTaskReceiver"
            android:exported="false"/>

        <activity
            android:theme="@2131886324"
            android:name="eu.thedarken.sdm.exclusions.ui.ExcludeActivity"
            android:configChanges="locale"/>

        <activity
            android:theme="@2131886620"
            android:label="@2131821169"
            android:name="eu.thedarken.sdm.oneclick.widget.OneClickWidgetConfigActivity"
            android:exported="true">
            <intent-filter>
                <action android:name="android.appwidget.action.APPWIDGET_CONFIGURE"/>
            </intent-filter>
        </activity>

        <activity
            android:theme="@2131886619"
            android:name="eu.thedarken.sdm.duplicates.ui.autoselection.AutoSelectionConfigActivity"
            android:configChanges="locale"/>

        <receiver
            android:label="@2131821170"
            android:name="eu.thedarken.sdm.oneclick.widget.QuickAccessWidgetProvider"
            android:enabled="true"
            android:exported="true">
            <intent-filter>
                <action android:name="android.appwidget.action.APPWIDGET_UPDATE"/>
                <action android:name="eu.thedarken.sdm.ACTION_EXTERNAL_EVENT"/>
            </intent-filter>

            <meta-data
                android:name="android.appwidget.provider"
                android:resource="@2132017181"/>
        </receiver>

        <service
            android:name="eu.thedarken.sdm.accessibility.core.ACCService"
            android:permission="android.permission.BIND_ACCESSIBILITY_SERVICE"
            android:exported="false">
            <intent-filter>
                <action android:name="android.accessibilityservice.AccessibilityService"/>
            </intent-filter>

            <meta-data
                android:name="android.accessibilityservice"
                android:resource="@2132017152"/>
        </service>

        <receiver
            android:name="eu.thedarken.sdm.explorer.core.modules.installer.session.InstallSessionReceiver"
            android:exported="false"/>

        <provider
            android:name="androidx.lifecycle.ProcessLifecycleOwnerInitializer"
            android:exported="false"
            android:multiprocess="true"
            android:authorities="eu.thedarken.sdm.lifecycle-process"/>
    </application>
</manifest>

**Comment by brenoepics** [comment]
What is the issue?
