### ISSUE TITLE
AndroidJSCore/2.2-pre2 build

### ISSUE THREAD

**Issue by mikeyxkcd** [jitpack/jitpack.io#610]
Log https://jitpack.io/com/github/ericwlange/AndroidJSCore/2.2-pre2/build.log

Jitpack seems to fall flat on it's face whenever a sub project has the same name as the parent, in this case `AndroidJSCore/AndroidJSCore`.

**Comment by jitpack-io** [comment]
Hi @mikeyxkcd 

It's unlikely that we can fix it on our side as the error comes from Gradle. Looks like the best option out there is to rename the submodule http://include-memory.blogspot.co.uk/2015/12/build-woes-gradle-different.html
