### ISSUE TITLE
When new releases are created, previous release .aar files can no longer be found

### ISSUE THREAD

**Issue by jeremynorman89** [jitpack/jitpack.io#6123]
**Describe the bug**

We use a specific version (e.g. `0.1.120`), we upload (e.g. `0.1.121`) and suddenly all our builds that rely on `0.1.120` start failing with the following error:

```
Caused by: org.gradle.internal.resolve.ArtifactNotFoundException: Could not find Android-Phone-Integration-Lib-0.1.120.aar (com.github.open-voip-alliance:Android-Phone-Integration-Lib:0.1.120).
Searched in the following locations:
https://jitpack.io/com/github/open-voip-alliance/Android-Phone-Integration-Lib/0.1.120/Android-Phone-Integration-Lib-0.1.120.aar
```

According to the page on Jitpack the build is still available but the `.aar` is missing when we actually try to use it. The build is frozen so it can't be deleted and re-generated.

**To Reproduce**

1. Upload a version `0.1.120`
2. Depend on this in a project
3. Upload a version `0.1.121`
4. Builds using `0.1.120` now fail

**Expected behavior**

Builds using a previous version continue working.

**Additional context**

This doesn't happen with any consistency, at a guess I'd say it happens 25% of the time.

**Comment by Wolf2323** [comment]
I think i have the same issue for my java project.

It seems for me, that after some time, actual files are deleted, maybe a clean up police, and then the build fails too. And if you click get it, it does not rebuild it. But if you look up the log file, it realize, that the file is missing and starts to build it again.

With this work around i could solve my issue for now, but i need to do this again and again (maybe every like 4-8 weeks?)

It would be nice if artifacts would be kept, as long as someone access it.
