### ISSUE TITLE
Disable -sources.jar publication/generation

### ISSUE THREAD

**Issue by amirraza** [jitpack/jitpack.io#6132]
According to the jitpack created issue (https://github.com/jitpack/jitpack.io/issues/3664)

- -sources.jar will NOT be created for private repositories.

However, for my private repo, jitpack is still producing **-sources.jar** and publishing.

What configuration is required to disable the generation and publication of the **-sources.jar**.

I am using:

- AGP 8.2.2
- Gradle 8.2
- Kotlin 1.9.22
- AS Hedgehog
- Java 17

Here is the log details: [Link](https://jitpack.io/com/github/amirraza/MyPrivate/1b0059a18c/build.log)

✅ Build artifacts:
com.github.amirraza:MyPrivate:1b0059a18c

Files: 
com/github/amirraza/MyPrivate/1b0059a18c
com/github/amirraza/MyPrivate/1b0059a18c/MyPrivate-1b0059a18c-sources.jar
com/github/amirraza/MyPrivate/1b0059a18c/MyPrivate-1b0059a18c.aar
com/github/amirraza/MyPrivate/1b0059a18c/MyPrivate-1b0059a18c.module
com/github/amirraza/MyPrivate/1b0059a18c/MyPrivate-1b0059a18c.pom
com/github/amirraza/MyPrivate/1b0059a18c/MyPrivate-1b0059a18c.pom.md5
com/github/amirraza/MyPrivate/1b0059a18c/MyPrivate-1b0059a18c.pom.sha1
com/github/amirraza/MyPrivate/1b0059a18c/build.log

**Comment by jitpack-io** [comment]
Hi

According to build log this task is run as part of the build
`> Task :hello:releaseSourcesJar`
which generates the -sources.jar.

JitPack does not use that task to generate sources though.

**Comment by amirraza** [comment]
So my problem has been resolved by adding the task in kotlin gradle as below, this will not be executed to generate **-sources.jar**

```
tasks.withType<AbstractArchiveTask> {
    if(this.name == "releaseSourcesJar" || this.name == "debugSourcesJar") {
        enabled = false
    }
}
```

**Comment by feiandytan** [comment]
Is that a behavior change in Kotlin Gradle Plugin? Because I do not see debugSourcesJar in KGP v1.8.0, but it is enabled in KGP v1.9.22.
