### ISSUE TITLE
Build starting... Error building)

### ISSUE THREAD

**Issue by SlimeBluKing** [jitpack/jitpack.io#6161]
Please provide:

- Link to build log from https://jitpack.io
https://jitpack.io/com/github/SlimeBluKing/SlimeCommons/0.1.5-alpha/build.log

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?
Project builds fine locally

- What error are you seeing?
```
Build starting...
Error building
```

**Comment by SlimeBluKing** [comment]
I opened a duplicate issue, I'm sorry

#3733

**Comment by SlimeBluKing** [comment]
fixed

**Comment by ErrorxCode** [comment]
> fixed

How bro? I am still facing the same issue

**Comment by SlimeBluKing** [comment]
Read #3733

**Comment by ErrorxCode** [comment]
It was fixed earlier but then it happened again. Now everyone is facing the same issue even after trying building multiple times

**Comment by ErrorxCode** [comment]
It start's working again, try rebuilding your project
