### ISSUE TITLE
kuza-pos-printer/1.0.5 build

### ISSUE THREAD

**Issue by victormwangi** [jitpack/jitpack.io#6168]
Please provide:

- Link to build log from https://jitpack.io

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ? YES

- What error are you seeing?: Build starting..., Error building

Thank you!

**Comment by boybeak** [comment]
It seems to be the Jitpack's server error. This is my [error log](https://jitpack.io/com/github/byte-cat/basic-kt/pre-0.0.23/build.log). It can be build normally for previous versions. But for new versions, the error will happen.
```
Build starting...
Error building
```
The error log only 2 lines.
