### ISSUE TITLE
Private repo build, nothings being recognized?

### ISSUE THREAD

**Issue by Orbyt** [jitpack/jitpack.io#618]
Alright, I have a private repo ( owned by an organization, which my account is part of). I have created a release and using the "Look Up" button on jitpack.io shows a successful build log.

This repo is just some internally library.

I then add the dependency to my sample application. I add `compile 'com.github.RockMyWorld:rockmyrun_android_sdk_source:1.3.1'` in the sample apps build.gradle. I also have the following defined in the samples apps same build.gradle:

```
repositories {
    maven {
        url "https://jitpack.io"
        credentials {
            username = 'orbyt' //<--this is my github username. This is correct yes?
            password = '05485308gsfljgfgslfg' //<-- my (fake) auth token. This is supposed to go here correct?
        }
    }
}
```

After syncing gradle, I still cant access any of the code in my library. What is going on? How could the build log show a succeeded build but I cant get it?

**Comment by jitpack-io** [comment]
Hi

This should work:
```
credentials {
            username '05485308gsfljgfgslfg' 
}
```
although it would be better to store the token in your home directory $HOME/.gradle/gradle.properties and then reference in the build file https://jitpack.io/private#auth

**Comment by Promulgate** [comment]
How do you reference the authToken in $HOME/.grade/grade.properties from the build file?

**Comment by jitpack-io** [comment]
Like this:
```
credentials {
             username authToken
        }
```

**Comment by pradhumn-moriya** [comment]
I'm getting 403 Forbidden. While implementing dependency in build.gradle with authToken in settings.gradle.
