### ISSUE TITLE
Bug exists in the content file reference of *.module files generated online by JitPack

### ISSUE THREAD

**Issue by liyuhaolol** [jitpack/jitpack.io#6192]
Recently, I discovered that libraries dependent on JitPack cannot be viewed in source code form; only decompiled class files are available. Clicking on Download Source also fails directly. Later, I found that the source code file address pointed to by the *.module file is incorrect.

Here's an example that illustrates the issue:

Dependency: `com.github.liyuhaolol:CommonUtils:1.4.9`
Corresponding link: https://jitpack.io/com/github/liyuhaolol/CommonUtils/1.4.9/

![filelist](https://github.com/jitpack/jitpack.io/assets/16422963/3196359e-5247-474d-a002-487dab74ca13)

As shown in the image, we can see that the files generated by JitPack are `CommonUtils-1.4.9-javadoc.jar` and `CommonUtils-1.4.9-sources.jar`. 

![moudlefile](https://github.com/jitpack/jitpack.io/assets/16422963/69ce12bf-639a-403f-aa4b-f5ccad677f3f)

However, when we view the `CommonUtils-1.4.9.module` file, as shown in the image, the file it points to has an incorrect file name and does not exist.

As a result, after adding this dependency to my project, I am unable to view the source code because the source code download is for a non-existent file.

However, when I locally execute the command `./gradlew publishToMavenLocal`, the files referenced in the module file are correct. Moreover, when testing with local dependencies, I can see the source code.

Therefore, I have to suspect that there is a bug in JitPack's online compilation.

I would appreciate it if the administrator could provide an explanation or suggest a command to modify the file reference in the module file."

Please note that I've translated the content exactly as provided. If there are any specific technical terms or jargon that may have different translations, please let me know, and I'll be happy to assist further.

**Comment by liyuhaolol** [comment]
whatever

**Comment by toasterofbread** [comment]
This bug breaks Kotlin/Compose Multiplatform resources in my library.
![image](https://github.com/user-attachments/assets/989daab7-f043-4c34-adad-dc4bbfe93ead)

The `kotlin_resources` file name is overwritten, and as a result this file isn't included in builds using the library which leads to crashes at runtime due to missing resources.

Is there any chance of a fix? I'd rather not have to move the project off of JitPack, but this doesn't seem like it's something that can be worked around.
