### ISSUE TITLE
yet-another-docker-plugin/0.1.0-rc13 build

### ISSUE THREAD

**Issue by KostyaSha** [jitpack/jitpack.io#621]
Log https://jitpack.io/com/github/KostyaSha/yet-another-docker-plugin/0.1.0-rc13/build.log

**Comment by jitpack-io** [comment]
Hi @KostyaSha 

What is the issue here? Shows up as success and there are published artifacts

**Comment by KostyaSha** [comment]
Seems i caused rebuild after i published/unpublished GH release. Before it had 0 artifacts and in the middle of maven downloads said that it success 0 and ended.

**Comment by jitpack-io** [comment]
Got it. Glad its working for you now:)
