### ISSUE TITLE
fad7/22.0.2 build

### ISSUE THREAD

**Issue by haibison** [jitpack/jitpack.io#623]
Hi JitPack,

Currently it fails to build one of my projects. I checked the log but I'm not sure what the problem is. Would you please have a look? https://jitpack.io/org/bitbucket/haibison/fad7/22.0.2/build.log

Thank you,

**Comment by jitpack-io** [comment]
Hi

Sure, the android-maven plugin seems to be is missing https://jitpack.io/docs/ANDROID/

**Comment by haibison** [comment]
Thank you. It seems this is new? My last builds didn't need that plugin. I'll update my project then.

Have a great weekend  `:-)`
