### ISSUE TITLE
Android debug and release buildTypes

### ISSUE THREAD

**Issue by kalevan** [jitpack/jitpack.io#6245]
Hey There, first of all i'm totally new to Android Library releases and its my first time using jitpack.

**Describe the bug**
I created a demo application here: [DemoLibrary](https://github.com/kalevan/DemoLibrary-Application)
It has an android application and the library module which gets published on jitpack (doing it all manually). After a few hours of trial and error i found a config that works with gradle 8.4 and kotlin. So i have a running jitpack build.

But now I have issues with the library I created and added as a dependency within the demo app.
In the build.gradle of the library I defined 2 MavenPublications, one for the debug build and one for the release build. Have done it because the integrating app has both default android variants defined and if i didn't add both, the dependency from jitpack could not be resolved for one or the other.
```
afterEvaluate {
    publishing {
        publications {
            val sdkGroupId = "com.github.kalevan"
            val sdkArtifactId = "DemoLibrary-Application"

            create<MavenPublication>("debug") {
                groupId = sdkGroupId
                artifactId = sdkArtifactId
                version = "0.0.8"
                from(components["debug"])
            }
            create<MavenPublication>("release") {
                groupId = sdkGroupId
                artifactId = sdkArtifactId
                version = "0.0.8"
                from(components["release"])
            }
        }
    }
}
```
So if someone uses debug they will be able to see some logs and in release mode not.

When i now build the Android application with buildVariant "debug", it always creates the BuildConfig of the library in release mode.

Maybe I miss something, but how can i achieve, the the integrating application of the library can access the debug and release artifact and depending on their applicationConfig (either debug or release) the correct artifact is used?

**To Reproduce**
1. Checkout the repo
2. Use buildVariant "debug" and build the app
3. Check the BuildConfig of the library, it shows:
```
package com.custom.testlibrary;

public final class BuildConfig {
    public static final boolean DEBUG = false;
    public static final String LIBRARY_PACKAGE_NAME = "com.custom.testlibrary";
    public static final String BUILD_TYPE = "release";

    public BuildConfig() {
    }
}

```

**Expected behavior**
In my "dream world" it would have picked the debug build of the library and only if i change the buildVariant of the application to "release" it will also use release build of the library.

**Comment by deka91** [comment]
I have the same issue. Is there any solution for this?

**Comment by kalevan** [comment]
still not having a proper solution for this, can anyone help @jitpack-io ?
