### ISSUE TITLE
android-widgets/1.0.0.2 build

### ISSUE THREAD

**Issue by keygenqt** [jitpack/jitpack.io#625]
Log https://jitpack.io/com/github/keygenqt/android-widgets/1.0.0.2/build.log

**Comment by jitpack-io** [comment]
Hi

Looks like later builds succeeded. Is there still an issue?

**Comment by keygenqt** [comment]
All happened in all figured out already, thank you!

**Comment by jitpack-io** [comment]
Great! Good to hear!:)
