### ISSUE TITLE
ActionBarAPI/1.0 build

### ISSUE THREAD

**Issue by vNoobblade** [jitpack/jitpack.io#6284]
Please provide:

- Link to build log from https://jitpack.io 
- https://jitpack.io/com/github/vNoobblade/ActionBarAPI/1.0/build.log

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?
- curl -o BuildTools.jar https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar && java -jar BuildTools.jar --rev 1.8.8

- What error are you seeing? 
-  Failed to execute goal on project ActionBarAPI: Could not resolve dependencies for project net.noobblade:ActionBarAPI:jar:1.0: Could not find artifact org.spigotmc:spigot:jar:1.8.8-R0.1-SNAPSHOT in spigotmc-repo (https://hub.spigotmc.org/nexus/content/repositories/snapshots/) -> [Help 1]

Thank you!

**Comment by PikaMug** [comment]
You're trying to get `org.spigotmc:spigot` but you want `org.spigotmc:spigot-api`

**Comment by vNoobblade** [comment]
I want org.spigotmc:spigot because i have to use nms and org.spigotmc:spigot-api does not have nms

**Comment by PikaMug** [comment]
Well https://hub.spigotmc.org/nexus/content/repositories/snapshots/ doesn't have `org.spigotmc:spigot` so you'll have to get it somewhere else.

**Comment by vNoobblade** [comment]
https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar This has org.spigotmc:spigot 
 java -jar BuildTools.jar --rev 1.8.8

**Comment by PikaMug** [comment]
That's not a Maven repository. Even if that file did have `org.spigotmc:spigot` inside (and looking inside the jar, it doesn't) you would need to depend on it locally. Therefore, Jitpack wouldn't have access to it.

Maybe this tutorial will help you understand Maven better: https://blog.jeff-media.com/how-to-create-your-first-minecraft-plugin-using-the-spigot-api-and-maven/

**Comment by vNoobblade** [comment]
https://www.spigotmc.org/wiki/buildtools/ Please check this

**Comment by PikaMug** [comment]
> https://www.spigotmc.org/wiki/buildtools/ Please check this

BuildTools may generate a jar you can use locally (meaning _your_ machine), but that has absolutely nothing to with Jitpack (_not_ your machine). Either find/create a Maven repository with the necessary library, or stick to compiling locally and avoid Jitpack altogether. Good luck, and if you need more help try the SpigotMC forum https://www.spigotmc.org/forums/spigot-plugin-development.52/
