### ISSUE TITLE
uucky/ColorPicker-Android/0.9.6 build issue

### ISSUE THREAD

**Issue by mariotaku** [jitpack/jitpack.io#63]
Log https://jitpack.io/com/github/uucky/ColorPicker-Android/0.9.6/build.log

I forgot to push tag 0.9.6 to repo, then I added it to dependency and build. After I push 'real' 0.9.6 version to repo, I can't get that version rebuilt.

**Comment by jitpack-io** [comment]
Rebuilt 0.9.6 and now you should be able to get it.

**Comment by mariotaku** [comment]
@jitpack-io is is possible to trigger rebuilt by library developers manually?

**Comment by jitpack-io** [comment]
Not yet, but it is planned #45

**Comment by mariotaku** [comment]
Thanks!

**Comment by jitpack-io** [comment]
@mariotaku Rebuilds a now possible #45
