### ISSUE TITLE
Fetch/3.2.0 build

### ISSUE THREAD

**Issue by sdex** [jitpack/jitpack.io#6377]
Please provide:

- Link to build log from https://jitpack.io
https://jitpack.io/com/github/tonyofrancis/Fetch/3.2.0/build.log

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?
Yes.

- What error are you seeing?
None.

Thank you!

**Comment by AlexandruPAccess** [comment]
The 3.2.0 Fetch status is still Error
