### ISSUE TITLE
react-native-reanimated not building on jitpack

### ISSUE THREAD

**Issue by shivamp2404** [jitpack/jitpack.io#6380]
Please provide:

- Link to build log from https://jitpack.io
 Private repos

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?
   yes, it Is building on my macos machine

- What error are you seeing?

  Execution failed for task ':react-native-reanimated:configureCMakeDebug[x86_64]'.
  > [CXX1210] /home/jitpack/build/node_modules/react-native-reanimated/android/CMakeLists.txt debug|x86_64 : No compatible library found

Thank you!

**Comment by shivamp2404** [comment]
@jitpack-io please help

**Comment by Ayota-Daniel** [comment]
i got the same issue on kali linux
