### ISSUE TITLE
shkschneider/android_Skeleton/4.1.2 build issue

### ISSUE THREAD

**Issue by shkschneider** [jitpack/jitpack.io#64]
Log https://jitpack.io/com/github/shkschneider/android_Skeleton/4.1.2/build.log

Looks like GooglePlayService 7.3.0 are not there.

What is the highest supported version?

PS: now using Gradle 1.2.3

**Comment by jitpack-io** [comment]
Installed GooglePlayService 7.3.0.
Now the build is successful

**Comment by shkschneider** [comment]
The build succeeded indeed, thanks.

But I can't get the AAR file: https://jitpack.io/com/github/shkschneider/android_Skeleton/4.1.2/android_Skeleton-4.1.2.jar

    {"message":"Not found","status":"error","details":{"files":["com/github/shkschneider/android_Skeleton/4.1.2/android_Skeleton-4.1.2.pom.md5","com/github/shkschneider/android_Skeleton/4.1.2/android_Skeleton-4.1.2.pom.sha1","com/github/shkschneider/android_Skeleton/4.1.2/android_Skeleton-4.1.2.pom","com/github/shkschneider/android_Skeleton/4.1.2/android_Skeleton-4.1.2-sources.jar","com/github/shkschneider/android_Skeleton/4.1.2/build.log","com/github/shkschneider/android_Skeleton/4.1.2/android_Skeleton-4.1.2.aar"],"other":["com/github/shkschneider/android_Skeleton"]}}

**Comment by jitpack-io** [comment]
You're right. Should have checked

**Comment by jitpack-io** [comment]
Oh, the 'aar' file is there but not the 'jar' file
https://jitpack.io/com/github/shkschneider/android_Skeleton/4.1.2/android_Skeleton-4.1.2.aar

were you expecting a jar as well?

**Comment by shkschneider** [comment]
No, fine. It works :)
