### ISSUE TITLE
CalendarView/1.1.0 build

### ISSUE THREAD

**Issue by PatrickHum-at** [jitpack/jitpack.io#6400]
**Describe the bug**
The AAR for this build is missing. We previously used this in our builds and it appears that it should be there - the .aar.sha1 is available but the .aar is not.

[https://jitpack.io/com/github/kizitonwose/CalendarView/1.1.0/](https://jitpack.io/com/github/kizitonwose/CalendarView/1.1.0/)

From the build.log it was first created in 2022 and the build succeeded.

**To Reproduce**
Use the `com.github.kizitonwose:CalendarView:1.1.0` dependency in gradle. Observe the build fails due to the missing aar

```
   > Could not find CalendarView-1.1.0.aar (com.github.kizitonwose:CalendarView:1.1.0).
     Searched in the following locations:
         https://jitpack.io/com/github/kizitonwose/CalendarView/1.1.0/CalendarView-1.1.0.aar
```

**Expected behavior**
The AAR from the build should be available

**Comment by PatrickHum-at** [comment]
For those who are struggling with the same problem, the artifact ID seems to have changed from 
`CalendarView -> Calendar`

Try using `com.github.kizitonwose:Calendar:1.1.0` instead.

**Comment by choongyouqi** [comment]
This is so weird..

https://jitpack.io/com/github/kizitonwose/CalendarView/1.0.3/ ❌ 
https://jitpack.io/com/github/kizitonwose/CalendarView/1.0.4/ ✅

**Comment by PatrickHum-at** [comment]
The aar moved back to CalendarView:1.1.0 💀

**Comment by PatrickHum-at** [comment]
@jitpack-io it is frustrating to have the aar move around like this.
