### ISSUE TITLE
" Gradle 'publishToMavenLocal' task not found." , but I already have it 

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [jitpack/jitpack.io#6411]
Please provide:

- Link to build log from https://jitpack.io
https://jitpack.io/com/github/AndroidDeveloperLB/ColorPicker/3fc7f345bd/build.log

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?
I use this:
```
gradlew tasks --all
```

And I can clearly see this in the results:

```
...
Publishing tasks
----------------
library:generateMetadataFileForReleasePublication - Generates the Gradle metadata file for publication 'release'.
library:generatePomFileForReleasePublication - Generates the Maven POM file for publication 'release'.
library:publish - Publishes all publications produced by this project.
library:publishReleasePublicationToMavenLocal - Publishes Maven publication 'release' to the local Maven repository.
library:publishToMavenLocal - Publishes all Maven publications produced by this project to the local Maven cache.
...
```

If I use the `gradlew install` command, I get this, which is different:

```
FAILURE: Build failed with an exception.

* What went wrong:
Task 'install' is ambiguous in root project 'ColorPicker' and its subprojects. Candidates are: 'installDebug', 'installDebugAndroidTest'.

* Try:
> Run gradlew tasks to get a list of available tasks.
> For more on name expansion, please refer to https://docs.gradle.org/8.8/userguide/command_line_interface.html#sec:name_abbreviation in the Gradle documentation.
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 5s
```

Via Android Studio, though, all builds fine.

- What error are you seeing? 

```
⚠️   WARNING:
 Gradle 'publishToMavenLocal' task not found. Please add the 'maven-publish' or 'maven' plugin.
 See the documentation and examples: https://docs.jitpack.io
```

Attached the project here:

[ColorPicker.zip](https://github.com/user-attachments/files/16417410/ColorPicker.zip)

Origin:
https://github.com/AndroidDeveloperLB/ColorPicker

I already have this in the library module:

```
plugins {
    id 'com.android.library'
    id 'kotlin-android'
    id 'maven-publish'
}
```

And I also have this, as it was in another repository I use:

```
afterEvaluate {
    publishing {
        publications {
            release(MavenPublication) {
                from components.release
            }
        }
    }
}
```

In the past it was so easy to publish on jitpack. Now it's always with errors in beginning...
:(

**Comment by ahmadmssm** [comment]
Also facing the same error.

**Comment by AndroidDeveloperLB** [comment]
Somehow I solved it. You can see my solutions here:
https://github.com/AndroidDeveloperLB/CommonUtils
https://github.com/AndroidDeveloperLB/FastScrollerAndRecyclerViewFixes/

Sadly I forgot what I did. Maybe some of what I did isn't even needed.
