### ISSUE TITLE
CommandsAPI/1.4.0 build

### ISSUE THREAD

**Issue by Traqueur-dev** [jitpack/jitpack.io#6416]
Please provide:

- https://jitpack.io/com/github/Traqueur-dev/CommandsAPI/1.4.0/build.log

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ? Yes

- What error are you seeing? 
ERROR: Time-out getting container status
Error building

**Comment by PukPukov** [comment]
How did you solved it?

**Comment by Traqueur-dev** [comment]
I just run a another build with same code just another tag id and it's work
