### ISSUE TITLE
Could not GET 'https://jitpack.io/com/github/barteksc/android-pdf-viewer/2.8.2/android-pdf-viewer-2.8.2.pom'. Received status code 401 from server: Unauthorized

### ISSUE THREAD

**Issue by nicknamepiyapong** [jitpack/jitpack.io#6423]
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':react-native-view-pdf:compileDebugAidl'.
> Could not resolve all task dependencies for configuration ':react-native-view-pdf:debugCompileClasspath'.
   > Could not resolve com.github.barteksc:android-pdf-viewer:2.8.2.
     Required by:
         project :react-native-view-pdf
      > Could not resolve com.github.barteksc:android-pdf-viewer:2.8.2.
         > Could not get resource 'https://jitpack.io/com/github/barteksc/android-pdf-viewer/2.8.2/android-pdf-viewer-2.8.2.pom'.
            > Could not GET 'https://jitpack.io/com/github/barteksc/android-pdf-viewer/2.8.2/android-pdf-viewer-2.8.2.pom'. Received status code 401 from server: Unauthorized
      > Could not resolve com.github.barteksc:android-pdf-viewer:2.8.2.
         > Could not get resource 'https://www.jitpack.io/com/github/barteksc/android-pdf-viewer/2.8.2/android-pdf-viewer-2.8.2.pom'.
            > Could not GET 'https://www.jitpack.io/com/github/barteksc/android-pdf-viewer/2.8.2/android-pdf-viewer-2.8.2.pom'. Received status code 401 from server: Unauthorized

Thank you!

**Comment by TareqKhalili** [comment]
Same issue for me. though it only happens in Bitrise. Build succeeds in android studio

**Comment by conghuahuadan** [comment]
I also have the same problem

**Comment by ketankhandelwal** [comment]
Hi! Any update on the given problem. I have the issue and after adding authtoken of jit getting 403 forbidden error although the packages I'm using are public.

      > Could not resolve com.amitshekhar.android:android-networking:1.0.2.
         > Could not get resource 'https://jitpack.io/com/amitshekhar/android/android-networking/1.0.2/android-networking-1.0.2.pom'.
            > Could not HEAD 'https://jitpack.io/com/amitshekhar/android/android-networking/1.0.2/android-networking-1.0.2.pom'. Received status code 403 from server: Forbidden

**Comment by Nayan014** [comment]
After trying numerous solutions, this one finally worked for me. [Link](https://github.com/DImuthuUpe/AndroidPdfViewer/issues/1037#issuecomment-2307015289)

**Comment by codewithrish** [comment]
> After trying numerous solutions, this one finally worked for me. [Link](https://github.com/DImuthuUpe/AndroidPdfViewer/issues/1037#issuecomment-2307015289)

Thanks this worked for me as well

**Comment by jitpack-io** [comment]
Hi all,

That [repository](https://github.com/barteksc/android-pdf-viewer) has is not hosted on JitPack but because GitHub returns 404 we assume it is private so you receive a 401.

**Comment by Khadijaikram** [comment]
implementation 'com.github.BeCoders:AndroidPdfViewer:2.8.1'
 use this
