### ISSUE TITLE
Android-Image-Cropper/1.1.1 build

### ISSUE THREAD

**Issue by jwilschrey** [jitpack/jitpack.io#6429]
Please provide:

- Link to build log from https://jitpack.io
https://www.jitpack.io/com/github/CanHub/Android-Image-Cropper/1.1.1/build.log

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?
nop, I clone the project from scratch

- What error are you seeing?

In the build processs:

* What went wrong:
Could not determine the dependencies of task ':expo-image-picker:compileDebugAidl'.
> Could not resolve all task dependencies for configuration ':expo-image-picker:debugCompileClasspath'.
   > Could not find com.github.CanHub:Android-Image-Cropper:1.1.1.
     Required by:
         project :expo-image-picker
         
        
I can't update the 'expo-image-picker' module because the project is very old and would break many references.

Thank you!!!!

**Comment by janithl** [comment]
+1, please help @jitpack-io 🙏

**Comment by DmitryUgryumov** [comment]
+1

**Comment by pp-aaronjiang** [comment]
I fixed it by using the last commit of the version `1.1.1` and patch the `expo-image-picker`.
```
implementation "com.github.CanHub:Android-Image-Cropper:e81a7d8eb1d"
```
