### ISSUE TITLE
i get this issue when run the app: Received status code 401 from server: Unauthorized

### ISSUE THREAD

**Issue by Tavorc** [jitpack/jitpack.io#6452]
Caused by: org.gradle.internal.resource.transport.http.HttpErrorStatusCodeException: Could not GET 'https://jitpack.io/com/github/barteksc/android-pdf-viewer/3.1.0-beta.1/android-pdf-viewer-3.1.0-beta.1.pom'. Received status code 401 from server: Unauthorized

also for 
org.jetbrains.anko:anko-commons:0.10.5
https://jitpack.io/org/jetbrains/anko/anko-commons/0.10.5/anko-commons-0.10.5.pom

any idea how to solve it?

- Link to build log from https://jitpack.io
    https://jitpack.io/com/github/barteksc/android-pdf-viewer/3.1.0-beta.1/android-pdf-viewer-3.1.0-beta.1.pom
https://jitpack.io/org/jetbrains/anko/anko-commons/0.10.5/anko-commons-0.10.5.pom

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?
   yes

- What error are you seeing?
   Received status code 401 from server: Unauthorized
Thank you!

**Comment by conghuahuadan** [comment]
I also have the same problem, It has already affected the compilation of many projects, please fix it as soon as possible

**Comment by Tavorc** [comment]
The solution that works for me is, i download the files of the library and put it locally in my repo.

**Comment by conghuahuadan** [comment]
> 对我有用的解决方案是，我下载了库的文件并将其位置放在我的存储库中。

dealing with every project like this would be overwhelming and frustrating.

**Comment by Nayan014** [comment]
After trying numerous solutions, this one finally worked for me. [Link](https://github.com/DImuthuUpe/AndroidPdfViewer/issues/1037#issuecomment-2307015289)

**Comment by ezeamalukamsiyo** [comment]
use this for your pdf viewer 


    implementation 'com.github.DImuthuUpe:AndroidPdfViewer:2.8.1'

**Comment by SantoshNayak** [comment]
Caused by: org.gradle.internal.resource.transport.http.HttpErrorStatusCodeException: Could not GET 'https://jitpack.io/com/github/barteksc/android-pdf-viewer/3.1.0-beta.1/android-pdf-viewer-3.1.0-beta.1.pom'. Received status code 401 from server: Unauthorized

**Comment by Siddhesh-crypt** [comment]
Could not GET 'https://jitpack.io/com/github/smarteist/autoimageslider/1.3.9/autoimageslider-1.3.9.pom'. Received status code 401 from server: Unauthorized
How to Solve this error

**Comment by huzaifa3212** [comment]
Could not HEAD 'https://jitpack.io/com/amitshekhar/android/jackson-android-networking/0.3.0/jackson-android-networking-0.3.0.pom'. Received status code 401 from server: Unauthorized

I got this issue
How to solve this error?
