### ISSUE TITLE
Jitpack.io dependencies suddenly showing 401 unauthorized

### ISSUE THREAD

**Issue by kaarthicksiyer** [jitpack/jitpack.io#6463]
I am using Android Studio Koala 2024.1.1 

Since yesterday evening my gradle build keeps failing because it is unable to download dependencies that are hosted on jitpack.io. It was working fine before yesterday. These are my gradle logs

`> Could not resolve com.stepstone.stepper:material-stepper:4.3.1.
     Required by:
         project :app
      > Could not resolve com.stepstone.stepper:material-stepper:4.3.1.
         > Could not get resource 'https://jitpack.io/com/stepstone/stepper/material-stepper/4.3.1/material-stepper-4.3.1.pom'.
            > Could not GET 'https://jitpack.io/com/stepstone/stepper/material-stepper/4.3.1/material-stepper-4.3.1.pom'. Received status code 401 from server: Unauthorized`

This is the github repo for that dependency: https://github.com/stepstone-tech/android-material-stepper

It is very much alive and its not private. All of this started to suddenly happen and its consuming a lot of my dev time because i am unable to build anything. 

One more thing I noticed is if I click on, it shows like this although its a public repo :

<img width="981" alt="Screenshot 2024-08-21 at 4 04 34 PM" src="https://github.com/user-attachments/assets/b30f7c68-63af-447b-bb6e-8286c4615fbf">

If you dismiss then it shows like this
<img width="786" alt="Screenshot 2024-08-21 at 4 05 05 PM" src="https://github.com/user-attachments/assets/7adce4bf-8dcd-4696-89c0-8a85035ac1df">

We are using gradle 7.5. My other fellow devs don't have this problem. I cleared the gradle cache for some other issue and since then i have been encountering this continuously. This is how the jitpack.io url is configured

`    repositories {
        mavenCentral()
        google()
        maven { url "https://jitpack.io" }
        maven {
            url "https://plugins.gradle.org/m2/"
        }
    }`

**Comment by isti-xander** [comment]
We have the same issue, but not for all artifacts from jitpack. Some of artifacts are loaded successfully.

**Comment by kaarthicksiyer** [comment]
@jitpack-io I request you to seriously help us understand whats going on because i am sure it is impacting a lot of people.

**Comment by demiangmz** [comment]
@kaarthicksiyer you are in luck, you just need to change the import to `implementation 'com.github.stepstone-tech.android-material-stepper:espresso-material-stepper:v4.3.1'` and it will work for you, to the rest of us we are stuck with legacy packages dependant on jCenter stored pom's. 

Jitpack is not the culprit here, it's a consequence of jCenter shutting down on 8/15: https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

**Comment by kaarthicksiyer** [comment]
@demiangmz thanks for your suggestion. We have a few legacy libraries too that could not be accessed so i had to get the jar files from my teammate's gradle cache and use it instead of providing the dependency url.

**Comment by VishalGunasekaran** [comment]
@kaarthicksiyer im also facing the same unauthorized issue in my android application,im new to android developement i cant build my project at all,previously i had some experience on building flutter applications,so can you help me solving this error ,it would be greatly helpful to me.my email:vishalvijay1904@gmail.com .Thankyou

**Comment by kaarthicksiyer** [comment]
@VishalGunasekaran Try to find the jar / aar files of the failing libraries and include them into your project. That should work.
