### ISSUE TITLE
LoadingButtonAndroid/2.2.0 build

### ISSUE THREAD

**Issue by izzy-i** [jitpack/jitpack.io#6468]
Please provide:

- Link to build log from https://jitpack.io/com/github/leandroBorgesFerreira/LoadingButtonAndroid/2.2.0/build.log

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) 
   yes

- What error are you seeing?
Failed to transform LoadingButtonAndroid-2.2.0.aar (com.github.leandroBorgesFerreira:LoadingButtonAndroid:2.2.0) to match attributes {artifactType=android-databinding, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Could not find LoadingButtonAndroid-2.2.0.jar (com.github.leandroBorgesFerreira:LoadingButtonAndroid:2.2.0).
        Searched in the following locations:
            https://jitpack.io/com/github/leandroBorgesFerreira/LoadingButtonAndroid/2.2.0/LoadingButtonAndroid-2.2.0.aar

Thank you!

**Comment by rtsketo** [comment]
https://github.com/jitpack/jitpack.io/issues/6472#issuecomment-2337361114
