### ISSUE TITLE
LoadingButtonAndroid/2.2.0 build

### ISSUE THREAD

**Issue by rtsketo** [jitpack/jitpack.io#6472]
Build on Jitpack fails and the library can no longer be found...

I've posted in the comments a temporary alternative build.

Thank you!

**Comment by rtsketo** [comment]
What are you referring to? I was about to post an issue, but I didn't after all.

**Comment by ezeamalukamsiyo** [comment]
i have this error when i try to build a project that has : Failed to resolve: br.com.simplepass:loading-button-android: 2.1.5

**Comment by ezeamalukamsiyo** [comment]
please do u have any solution to this ?

**Comment by rtsketo** [comment]
You can use my build if you want `com.github.rtsketo:LoadingButtonAndroid:no-signing-SNAPSHOT`.
It's temporary solution and it's unsigned package! Change changes [here](https://github.com/rtsketo/LoadingButtonAndroid/commits/master/).

I'll reopen the this issue and report it properly.

**Comment by ezeamalukamsiyo** [comment]
thank you, do you know the exact repo jitpack uses?

**Comment by rtsketo** [comment]
I have no idea why I posted this on jitpack.io or why you looked for that in jitpack.io ... But anyway, I'll leave it here in case someone else needs it.

What do you mean by exact repo jitpack uses? You can publish artifacts there.
