### ISSUE TITLE
Failed to resolve: org.adblockplus:adblock-android-webview:4.4.0

### ISSUE THREAD

**Issue by hostingvosting** [jitpack/jitpack.io#6474]
Failed to resolve: org.adblockplus:adblock-android-webview:4.4.0

**Comment by iang12** [comment]
> Failed to resolve: org.adblockplus:adblock-android-webview:4.4.0

same errro here too

**Comment by midou221** [comment]
any solution !?

**Comment by decryptable** [comment]
![Image](https://github.com/user-attachments/assets/2faabd09-24c8-4f17-9026-a3a0021092b2)

As shown in the screenshot above, the maven repository tells me that the artifact library [`org.adblockplus:adblock-android:4.4.0`](https://mvnrepository.com/artifact/org.adblockplus/adblock-android/4.4.0) is located in [`Appodeal`](https://mvnrepository.com/repos/appodeal-public). So I added a new maven repository url in my `build.gradle.kts` with :

```build.gradle.kts
maven { url = uri("https://artifactory.appodeal.com/appodeal-public/") }
```

```build.gradle.kts
pluginManagement {
    repositori {
        google {
            konten {
                includeGroupByRegex("com\\.android.*")
                includeGroupByRegex("com\\.google.*")
                includeGroupByRegex("androidx.*")
            }
        }
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositori {
        google()
        mavenCentral()
        maven { url = uri("https://artifactory.appodeal.com/appodeal-public/") }
    }
}

rootProject.name = "Browser"
include(":app")
```

But when searching for the library [`org.adblockplus:adblock-android-webview:4.4.0`](https://mvnrepository.com/artifact/org.adblockplus/adblock-android-webview/4.4.0), the Maven repository actually points to the repository [`JCenter`](https://jcenter.bintray.com/). I'm not sure why it points to the [`JCenter`](https://jcenter.bintray.com/) repository.

![Image](https://github.com/user-attachments/assets/7cdc35e1-77ed-4a33-8c99-6f39a6dc5e85)

But surely the artifact library `org.adblockplus:adblock-android-webview:4.4.0` is not in the repository [`JCenter`](https://jcenter.bintray.com/). So just configure the Maven repository url to

```
https://artifactory.appodeal.com/appodeal-public/
```

as in the first step. And that works for now.

![Image](https://github.com/user-attachments/assets/c37e9324-37b8-4aba-84e0-1b571cc2e967)
