### ISSUE TITLE
Support Java 21

### ISSUE THREAD

**Issue by kaspernielsen** [jitpack/jitpack.io#6479]
Currently the latest supported version is Java 17. Would be nice with a newer version of Java.

There is support for Java 19, however this fails with the following error

00:01 $ wget -nv https://download.java.net/java/early_access/jdk19/5/GPL/openjdk-19-ea+5_linux-x64_bin.tar.gz -O /home/jitpack/tools/jdk19/jdk19.tar.gz
23.	https://download.java.net/java/early_access/jdk19/5/GPL/openjdk-19-ea+5_linux-x64_bin.tar.gz:
24.	2024-08-26 13:39:14 ERROR 404: Not Found.
25.	Command exit code: 8

**Comment by Ezrnest** [comment]
It seems that adding a `jitpack.yml` with
```
jdk:
  - openjdk21
```
works for me.
