### ISSUE TITLE
Could not find com.nabinbhandari.android:permissions:3.8.

### ISSUE THREAD

**Issue by joaquin-perezbarroso** [jitpack/jitpack.io#6497]
We provide:

- Link to build log from  https://jitpack.io/com/github/CartoDB/AENA/1.4.9/build.log

- This project was build here perfectly. After some problems with new version, we deleted and try to recreate, we have the same issue than new versiones.

- What error are you seeing? Could not find dependencies than really exist, like:  com.nabinbhandari.android:permissions:3.8., org.koin:koin-android:2.2.2.

Thank you!

**Comment by Mirxomitov** [comment]
i am getting error too

**Comment by Hashem-Tabbaa** [comment]
where any one able to resolve it?

**Comment by Mirxomitov** [comment]
I replaced library to another one. Also, adding library as new module must be solution
