### ISSUE TITLE
Build failed unexpectedly

### ISSUE THREAD

**Issue by johnzeringue** [jitpack/jitpack.io#65]
Similar to #44, my [`build.log`](https://jitpack.io/com/github/johnzeringue/topsoil/5bffa9d/build.log) seems to indicate a server failure.

Could you please rebuild this project?

**Comment by jitpack-io** [comment]
Hi! That commit doesn't seem to exist anymore. 
Could it be that history was rewritten with `git push -f`?

**Comment by johnzeringue** [comment]
Oops! You're right, I ran `git commit --amend && git push -f` in order to try forcing a new build myself.

[Here](https://jitpack.io/com/github/johnzeringue/topsoil/1909627/build.log)'s the new log.

**Comment by jitpack-io** [comment]
Ah ok. Rebuilt the new version. Seems allright now

**Comment by johnzeringue** [comment]
Looks good on my end too. Thanks!

**Comment by johnzeringue** [comment]
Still getting failed builds frequently. [Here](https://jitpack.io/com/github/johnzeringue/topsoil/5147a7c/build.log)'s the latest.

Is there anything I can do on my end?

**Comment by jitpack-io** [comment]
Unfortunately not. Found the problem on our end. Looking for a fix

**Comment by jitpack-io** [comment]
Should be fixed now. Sorry about that, firewall was too strict:)

**Comment by johnzeringue** [comment]
Thanks again! Looking good here.
