### ISSUE TITLE
Build Error, jitpack cannot find artifact?

### ISSUE THREAD

**Issue by Abyssal101** [jitpack/jitpack.io#6501]
Please provide:

- Link to build log from https://www.jitpack.io/com/github/Abyssal101/Overstuffed/1.0-1.20.1/build.log 

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ? **Yup, It builds and I've been able to use the jars created succesfull**

- What error are you seeing? 
**My project seems to build correctly locally, but when I look at the jitpack logs it justs doesn't to build. I've at other issues and none seem to be quite the same, or they said "fixed it" and don't document what they did. I think it's mainly related to this error, but what's confusing me is that it says it found the artifact, and then gives an error saying it DIDNT find it? 
- 
BUILD FAILED in 7s
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2
Archive: net.willsbr.overstuffed:overstuffed:1.0-1.20.1
Publication: net.willsbr.overstuffed:build:1.0-1.20.1
Publication: net.willsbr.overstuffed:build:1.0-1.20.1
Build tool exit code: 0
Looking for artifacts...
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2
Looking for pom.xml in build directory and ~/.m2
Found artifact: net.willsbr.overstuffed:overstuffed:1.0-1.20.1
Found artifact: net.willsbr.overstuffed:build:1.0-1.20.1
2024-08-30T01:19:12.491558729Z
Exit code: 0

⚠️ ERROR: No build artifacts found
Expected artifacts in: $HOME/.m2/repository/net/willsbr/overstuffed/build/1.0-1.20.1**

**Comment by rtsketo** [comment]
https://github.com/jitpack/jitpack.io/issues/6472#issuecomment-2337361114

**Comment by Hatzen** [comment]
this might relate to jcenters shutdown, older versions of android toolchain were only hosted on jcenter.

you might want to have a look at #6458
