### ISSUE TITLE
Build Artifact failed

### ISSUE THREAD

**Issue by doananhtuan22111996** [jitpack/jitpack.io#6503]
Context:
- Repo: https://github.com/doananhtuan22111996/android-core
- JitPack: https://jitpack.io/#doananhtuan22111996/android-core

I run successfully these commands in my local side: `./gradlew install` and `./gradlew publishToMavenLocal`
But failed when publish to https://jitpack.io. I can't download this artifact

![image](https://github.com/user-attachments/assets/e66614b4-104d-4fee-a708-f1fecc32820b)

Please help!
Thank you!

**Comment by rtsketo** [comment]
https://github.com/jitpack/jitpack.io/issues/6472#issuecomment-2337361114
