### ISSUE TITLE
Could not GET 'https://jitpack.io/io/github/vvb2060/ndk/boringssl/1.0/boringssl-1.0.pom'. Received status code 401 from server: Unauthorized 

### ISSUE THREAD

**Issue by MuhammadUsamaSiddiqui** [jitpack/jitpack.io#6518]
FAILURE: Build failed with an exception.

What went wrong:
Execution failed for task ':app:checkDevDebugAarMetadata'.
Could not resolve all files for configuration ':app:devDebugRuntimeClasspath'.
Could not resolve io.github.vvb2060.ndk:xposeddetector:1.0.
Required by:
project :app
> Could not resolve io.github.vvb2060.ndk:xposeddetector:1.0.
> Could not get resource 'https://jitpack.io/io/github/vvb2060/ndk/xposeddetector/1.0/xposeddetector-1.0.pom'.
> Could not GET 'https://jitpack.io/io/github/vvb2060/ndk/xposeddetector/1.0/xposeddetector-1.0.pom'. Received status code 401 from server: Unauthorized
Could not resolve io.github.vvb2060.ndk:boringssl:1.0.
Required by:
project :app
> Could not resolve io.github.vvb2060.ndk:boringssl:1.0.
> Could not get resource 'https://jitpack.io/io/github/vvb2060/ndk/boringssl/1.0/boringssl-1.0.pom'.
> Could not GET 'https://jitpack.io/io/github/vvb2060/ndk/boringssl/1.0/boringssl-1.0.pom'. Received status code 401 from server: Unauthorized

Try:
Run with --stacktrace option to get the stack trace.
Run with --info or --debug option to get more log output.
Run with --scan to get full insights.

Get more help at https://help.gradle.org/
BUILD FAILED in 53s
[!] Gradle threw an error while downloading artifacts from the network.

**Comment by dominikdoric** [comment]
Hi, did you find solution or workaround for this?

**Comment by MuhammadUsamaSiddiqui** [comment]
This issue is resolved by updating to the versions which are available on Maven Central:

**xposeddetector:** https://central.sonatype.com/artifact/io.github.vvb2060.ndk/xposeddetector/versions
**boringssl:** https://central.sonatype.com/artifact/io.github.vvb2060.ndk/boringssl/versions

But I am getting another error which I mentioned [here](https://github.com/vvb2060/BoringSSL_Android/issues/9). I guess my project is not compatible with the updated versions.
