### ISSUE TITLE
finished Download info Failed to resolve: br.com.simplepass:loading-button-android:1.6.3

### ISSUE THREAD

**Issue by ezeamalukamsiyo** [jitpack/jitpack.io#6530]
Please provide:

- Link to build log from https://jitpack.io

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?

- What error are you seeing?

Thank you!

**Comment by rtsketo** [comment]
https://github.com/jitpack/jitpack.io/issues/6472#issuecomment-2337361114
