### ISSUE TITLE
Failed to resolve: com.github.davideas:FlexibleAdapter:

### ISSUE THREAD

**Issue by james-furlong** [jitpack/jitpack.io#6536]
Please provide:

- Link to build log from https://jitpack.io - https://jitpack.io/com/github/davideas/FlexibleAdapter/5.1.0/build.log

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ? No?

- What error are you seeing?
`Failed to resolve: com.github.davideas:FlexibleAdapter:5.1.0`

Thank you!

**Comment by mgpx** [comment]
I'm also having the same problem...
I tried to compile locally and was unsuccessful...
If you succeed, please let me know.

**Comment by mgpx** [comment]
I downloaded the repository and compiled it locally, I had to make some changes, but now my project can be compiled

Download file: flexible-adapter-5.1.0.aar  ([flexible-adapter-release.zip](https://github.com/user-attachments/files/17249201/flexible-adapter-release.zip))

Place the file in the libs folder, and add this to gradle

`implementation fileTree(dir: 'libs', include: ['*.aar'])`
