### ISSUE TITLE
Android-PickerView/v1.9 build

### ISSUE THREAD

**Issue by John-Constantine** [jitpack/jitpack.io#654]
Log https://jitpack.io/com/github/John-Constantine/Android-PickerView/v1.9/build.log

**Comment by jitpack-io** [comment]
Hi

Looks like the android-maven plugin is missing from build.gradle. Docs https://jitpack.io/docs/ANDROID/

**Comment by John-Constantine** [comment]
Thanks.This document help me.I have solved this problem.
