### ISSUE TITLE
gradle-node-plugin/master build

### ISSUE THREAD

**Issue by ritvick** [jitpack/jitpack.io#6575]
Please provide:

- Link to build log from https://jitpack.io
https://jitpack.io/com/github/srs/gradle-node-plugin/master/build.log

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ? Yes

- What error are you seeing?
Could not resolve all artifacts for configuration ':classpath'.
   > Could not find org.codehaus.groovy.modules.http-builder:http-builder:0.7.2.

Thank you!

**Comment by chinmaydash007** [comment]
I am also getting the same error.
