### ISSUE TITLE
AndroidPdfViewer/3.0.0-beta.4 build

### ISSUE THREAD

**Issue by rizkijuliansyaham** [jitpack/jitpack.io#6590]
**Describe the bug**
error show like this 

Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
[   +1 ms]    > Could not find com.github.DImuthuUpe:AndroidPdfViewer:3.0.0-beta.4.
[        ]      Searched in the following locations:
[        ]        - https://repo.maven.apache.org/maven2/com/github/DImuthuUpe/AndroidPdfViewer/3.0.0-beta.4/AndroidPdfViewer-3.0.0-beta.4.pom
[        ]        - https://dl.google.com/dl/android/maven2/com/github/DImuthuUpe/AndroidPdfViewer/3.0.0-beta.4/AndroidPdfViewer-3.0.0-beta.4.pom
[        ]        - https://storage.googleapis.com/download.flutter.io/com/github/DImuthuUpe/AndroidPdfViewer/3.0.0-beta.4/AndroidPdfViewer-3.0.0-beta.4.pom
[        ]        - https://jcenter.bintray.com/com/github/DImuthuUpe/AndroidPdfViewer/3.0.0-beta.4/AndroidPdfViewer-3.0.0-beta.4.pom
[        ]        - file:/home/rizki/.m2/repository/com/github/DImuthuUpe/AndroidPdfViewer/3.0.0-beta.4/AndroidPdfViewer-3.0.0-beta.4.pom
[        ]        - https://www.jitpack.io/com/github/DImuthuUpe/AndroidPdfViewer/3.0.0-beta.4/AndroidPdfViewer-3.0.0-beta.4.pom
[        ]      Required by:
[        ]          project :app
[   +1 ms]    > Could not resolve com.github.barteksc:android-pdf-viewer:3.0.0-beta.4.
[   +1 ms]      Required by:
[        ]          project :app > project :pdf_viewer_plugin
[        ]       > Could not resolve com.github.barteksc:android-pdf-viewer:3.0.0-beta.4.
[        ]          > Could not get resource 'https://www.jitpack.io/com/github/barteksc/android-pdf-viewer/3.0.0-beta.4/android-pdf-viewer-3.0.0-beta.4.pom'.
[        ]             > Could not GET 'https://www.jitpack.io/com/github/barteksc/android-pdf-viewer/3.0.0-beta.4/android-pdf-viewer-3.0.0-beta.4.pom'. Received status code 401 from
server: Unauthorized

**Comment by cmmmmmmmmmmmmmmmmmmmmmmmm** [comment]
请问有解决办法吗 一样的报错
