### ISSUE TITLE
UsbSerial/6.1.0 build

### ISSUE THREAD

**Issue by iapetod** [jitpack/jitpack.io#6641]
- Link to build log from https://jitpack.io
https://jitpack.io/com/github/felHR85/UsbSerial/6.1.0/build.log

- What error are you seeing?
Build failed. See the log at jitpack.io

**Comment by ravisvf** [comment]
> Could not find UsbSerial-6.1.0.aar (com.github.felHR85:UsbSerial:6.1.0).
  Searched in the following locations:
      https://jitpack.io/com/github/felHR85/UsbSerial/6.1.0/UsbSerial-6.1.0.aar
      https://jitpack.io/com/github/felHR85/UsbSerial/6.1.0/UsbSerial-6.1.0.jar
Does the project build on your machine with the same commands (e.g. ./gradlew install) ? NO

Launching lib\main.dart on SM G975F in debug mode...
Running Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.

What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
Failed to transform UsbSerial-6.1.0.aar (com.github.felHR85:UsbSerial:6.1.0) to match attributes {artifactType=android-aar-metadata, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}.
> Could not find UsbSerial-6.1.0.aar (com.github.felHR85:UsbSerial:6.1.0).
Searched in the following locations:
https://jitpack.io/com/github/felHR85/UsbSerial/6.1.0/UsbSerial-6.1.0.aar
https://jitpack.io/com/github/felHR85/UsbSerial/6.1.0/UsbSerial-6.1.0.jar

Try:
Run with --stacktrace option to get the stack trace.
Run with --info or --debug option to get more log output.
Run with --scan to get full insights.

Get more help at https://help.gradle.org/
Thank you!
