### ISSUE TITLE
Jitpack LOST a build

### ISSUE THREAD

**Issue by CarGuo** [jitpack/jitpack.io#6645]
Describe the bug

One old version build of one of my libraries suddenly got lost, but not all... I know it did work in the past because I used this version before.

To Reproduce

```
 implementation "com.github.CarGuo.GSYVideoPlayer:GSYVideoPlayer:v8.5.0-release-jitpack"
```

one build  tag `v8.5.0-release-jitpack`, but :

- ❌lost : https://jitpack.io/com/github/CarGuo/GSYVideoPlayer/gsyVideoPlayer-armv7a/v8.5.0-release-jitpack/gsyVideoPlayer-armv7a-v8.5.0-release-jitpack.pom

- ✅ right： https://jitpack.io/com/github/CarGuo/GSYVideoPlayer/gsyVideoPlayer-arm64/v8.5.0-release-jitpack/gsyVideoPlayer-arm64-v8.5.0-release-jitpack.pom	

- ❌lost : https://jitpack.io/com/github/CarGuo/GSYVideoPlayer/gsyVideoPlayer-armv64/v8.5.0-release-jitpack/

- ✅ right：https://jitpack.io/com/github/CarGuo/GSYVideoPlayer/gsyVideoPlayer-armv7a/v8.5.0-release-jitpack/

<img width="1146" alt="image" src="https://github.com/user-attachments/assets/e991e6a9-cbb1-421f-8549-07eb99c602cd">

**Comment by jitpack-io** [comment]
Hi

Does it work with version `8.5.0-release-jitpack` (without v)?

**Comment by CarGuo** [comment]
There are two tags: `8.5.0-release-jitpack` and `v8.5.0-release-jitpack`, In this example, `8.5.0-release-jitpack`  has been lost something:

<img width="634" alt="image" src="https://github.com/user-attachments/assets/8155c57c-177e-4f72-9288-6f0a51571e27">

not only `8.5.0-release-jitpack` , also like ：

✅ right：https://jitpack.io/com/github/CarGuo/GSYVideoPlayer/gsyVideoPlayer-arm64/v8.3.5-release-jitpack/gsyVideoPlayer-arm64-v8.3.5-release-jitpack.pom

✅ right：https://jitpack.io/com/github/CarGuo/GSYVideoPlayer/gsyVideoPlayer-arm64/v9.0.0-release-jitpack/gsyVideoPlayer-arm64-v9.0.0-release-jitpack.pom


❌lost : https://jitpack.io/com/github/CarGuo/GSYVideoPlayer/gsyVideoPlayer-arm64/v8.3.1-release-jitpack/gsyVideoPlayer-arm64-v8.3.1-release-jitpack.pom

❌lost : https://jitpack.io/com/github/CarGuo/GSYVideoPlayer/gsyVideoPlayer-arm64/v8.3.0-release-jitpack/gsyVideoPlayer-arm64-v8.3.0-release-jitpack.pom



![image](https://github.com/user-attachments/assets/ff625631-15ad-4094-b336-30488d69cf34)

![image](https://github.com/user-attachments/assets/115dd6cb-6614-49ca-a8f9-4bdc161cc559)


**So it looks strange, like the history pack will be randomly lost **.

**Comment by CarGuo** [comment]
any update ?
