### ISSUE TITLE
Android-ViewPagerIndicator/2.4.1 build

### ISSUE THREAD

**Issue by vincentbrison** [jitpack/jitpack.io#668]
Hi,
I can not use this repo, have you any idea what is going on ?

Log https://jitpack.io/com/github/BurntBrunch/Android-ViewPagerIndicator/2.4.1/build.log

**Comment by jitpack-io** [comment]
Hi @vincentbrison 

It looks like the project was build using an older version of Maven than the one JitPack is using (3.2.5). One thing you could try is to add a Maven Wrapper that builds with an older version.

**Comment by vincentbrison** [comment]
Thanks for reply,

I did fork the repo and updated the project to use more recent tools, so problem solved.

BR.
