### ISSUE TITLE
Read timeout:  Could not resolve com.sailthru.mobile.sdk:sailthru-mobile:15.0.0.

### ISSUE THREAD

**Issue by rameshkumarkhatri** [jitpack/jitpack.io#6741]
Please provide:

- What error are you seeing?
Generating build throw error 

> > Could not resolve com.sailthru.mobile.sdk:sailthru-mobile:15.0.0.
> 60 actionable tasks: 52 executed, 8 from cache
>      Required by:
>          project :app
>       > Could not resolve com.sailthru.mobile.sdk:sailthru-mobile:15.0.0.
>          > Could not get resource 'https://jitpack.io/com/sailthru/mobile/sdk/sailthru-mobile/15.0.0/sailthru-mobile-15.0.0.pom'.
>             > Could not GET 'https://jitpack.io/com/sailthru/mobile/sdk/sailthru-mobile/15.0.0/sailthru-mobile-15.0.0.pom'.
>                > Read timed out
>    > Could not resolve ai.sierra:sierra-android-sdk:v0.20240517.7150847.
>      Required by:
>          project :app
>       > Could not resolve ai.sierra:sierra-android-sdk:v0.20240517.7150847.
>          > Could not get resource 'https://jitpack.io/ai/sierra/sierra-android-sdk/v0.20240517.7150847/sierra-android-sdk-v0.20240517.7150847.pom'.
>             > Could not GET 'https://jitpack.io/ai/sierra/sierra-android-sdk/v0.20240517.7150847/sierra-android-sdk-v0.20240517.7150847.pom'.
>                > Read timed out
> * Try:`

```

Thank you!

**Comment by thalida** [comment]
Is there a place to see status updates that's not twitter/X? I'm not on the platform, so don't know if anything has been posted there. According to the status page it's been about 3 hours, so want to know if there's been any ETA or other updates posted.

(Deciding if I should stay up to redo my build or wait till the morn. 😭)

**Comment by andrewlvr** [comment]
> Is there a place to see status updates that's not twitter/X? I'm not on the platform, so don't know if anything has been posted there. According to the status page it's been about 3 hours, so want to know if there's been any ETA or other updates posted.
> 
> (Deciding if I should stay up to redo my build or wait till the morn. 😭)

All I could finnd was this: https://status.jitpack.io/

**Comment by maxphillipsdev** [comment]
:( same

**Comment by ScubaAddict** [comment]
They have not posted any status on twitter.  Not even an acknowledgement of being down.

**Comment by AcHsu104** [comment]
Where can I currently check the service status?

**Comment by funkybob** [comment]
As @androidacy-user said: https://status.jitpack.io/

**Comment by rameshkumarkhatri** [comment]
Closing this out since most of the services are working now. 
Thanks everyone.

**Comment by yfzu** [comment]
All systems operational now
