### ISSUE TITLE
Could not GET 'https://www.jitpack.io/jp/co/osstech/libjeid-full/maven-metadata.xml'.

### ISSUE THREAD

**Issue by Kazuya-Sakamoto** [jitpack/jitpack.io#6743]
**Describe the bug**

When attempting to resolve the dependency jp.co.osstech:libjeid-full:latest.integration using JitPack, the process fails due to a connection timeout. Accessing the metadata URL directly (https://www.jitpack.io/jp/co/osstech/libjeid-full/maven-metadata.xml) also results in a connection error.

The error message shown when accessing the URL directly is:
"Connection: There seems to be an issue connecting to our servers. Please try again in a few minutes."

Thank you!

![スクリーンショット 2024-12-19 15 04 27](https://github.com/user-attachments/assets/27147538-9e36-4d57-97f5-ceb132044c40)

**Comment by duynnnnnn** [comment]
Same to me!

**Comment by ivan-horchakov** [comment]
Same issue!

**Comment by shalva97** [comment]
A sign from above to take a day off!!

**Comment by yfzu** [comment]
G 啦

**Comment by mmjc29** [comment]
WHAT THE FXXK server down again

**Comment by duynnnnnn** [comment]
https://status.jitpack.io/
<img width="1029" alt="image" src="https://github.com/user-attachments/assets/4805818a-994d-479f-b1b2-834f2cc56f3c" />

**Comment by programmelearn** [comment]
Same issue!

**Comment by Phong-TH** [comment]
Same issue!

**Comment by labrute974** [comment]
Can confirm from Australia, and thus for a number of hours now

**Comment by biplobAtCT** [comment]
Same issue. from Bangladesh..

**Comment by nangongmoyan** [comment]
Can anyone tell me how long it will take to recover?

**Comment by iazrael** [comment]
me too！

**Comment by sun141421** [comment]
the server is down confirmed from china

**Comment by DatTranMyLong** [comment]
the server is down confirmed from Viet Nam

**Comment by kroune** [comment]
same issue in russia

**Comment by JaeEeLee** [comment]
the server is down confirmed from Korea 🇰🇷

**Comment by strive4mydream** [comment]
same issue! 😡🤯

**Comment by zainempg** [comment]
Server is down . confirmed from Pakistan 🇵🇰

**Comment by HYEOK999** [comment]
Server is down . Republic of Korea 🇰🇷

**Comment by Kazuya-Sakamoto** [comment]
it was also mentioned in the Expo community.

https://x.com/expo_status/status/1869522419603701977

**Comment by lee-eau** [comment]
救救我 救救我

**Comment by biplobAtCT** [comment]
Templary a fix worked for me now - 

Here's a shortened version that you can post on the GitHub issue:

---

### Solution to Redirect `www.jitpack.io` to `jitpack.io` on macOS:

1. **Edit `/etc/hosts`**:
   Open terminal and run:
   ```bash
   sudo nano /etc/hosts
   ```

2. **Add the following line** to the end of the file:
   ```
   185.199.108.133 www.jitpack.io
   ```

3. **Save and close the file**:
   - Press `Control + O`, then `Enter` to save.
   - Press `Control + X` to exit.

4. **Flush DNS Cache**:
   Run the following commands:
   ```bash
   sudo dscacheutil -flushcache
   sudo killall -HUP mDNSResponder
   ```

5. **Test**:
   Use `curl` to test the redirection:
   ```bash
   curl -I https://www.jitpack.io
   ```

---

This should forward `www.jitpack.io` to `jitpack.io` and resolve the issue.

**Comment by labrute974** [comment]
@biplobAtCT I confirm that did the trick for me!

**Comment by sha3rawi33** [comment]
same issue EG Cairo

**Comment by kurbanali-webelight** [comment]
Same to me!

https://www.jitpack.io/me/carda/AndroidAwnCore/maven-metadata.xml

**Comment by ted-prnd** [comment]
저도 안돼요

**Comment by jesseminn** [comment]
Already happened 2 years ago before Christmas

https://github.com/jitpack/jitpack.io/issues/5337

**Comment by entioentio** [comment]
> Same to me!
> 
> https://www.jitpack.io/me/carda/AndroidAwnCore/maven-metadata.xml

Doesn't work for firebase related stuff unfortunately:
`https://jitpack.io/com/google/firebase/firebase-messaging/maven-metadata.xml`

**Comment by DevDengChao** [comment]
> Already happened 2 years ago before Christmas
> 
> #5337

Maybe the server is going to have a break on every Christmas ? 🤣

**Comment by mesaglam** [comment]
I hope it'll be fixed soon....

**Comment by DevDengChao** [comment]
Maybe it's time to setup a self-hosted Nexus repository.

**Comment by nangongmoyan** [comment]
> A temporary fix worked for me now -一个临时修复现在对我有用 -
> 
> Here's a shortened version that you can post on the GitHub issue:以下是您可以在 GitHub 问题上发布的缩短版本：
> 
> ### Solution to Redirect `www.jitpack.io` to `jitpack.io` on macOS:
> 在 macOS 上将`www.jitpack.io`重定向到`jitpack.io`的解决方案：
> 1. **Edit `/etc/hosts`**:**编辑`/etc/hosts`** ：
>    Open terminal and run:  打开终端并运行：
>    ```shell
>    sudo nano /etc/hosts
>    ```
> 2. **Add the following line** to the end of the file:**将以下行添加**到文件末尾：
>    ```
>    185.199.108.133 www.jitpack.io
>    ```
> 3. **Save and close the file**:**保存并关闭文件**：
>    
>    * Press `Control + O`, then `Enter` to save.按`Control + O` ，然后`Enter`保存。
>    * Press `Control + X` to exit.按`Control + X`退出。
> 4. **Flush DNS Cache**:**刷新 DNS 缓存**：
>    Run the following commands:运行以下命令：
>    ```shell
>    sudo dscacheutil -flushcache
>    sudo killall -HUP mDNSResponder
>    ```
> 5. **Test**:**测试**：
>    Use `curl` to test the redirection:使用`curl`来测试重定向：
>    ```shell
>    curl -I https://www.jitpack.io
>    ```
> 
> This should forward `www.jitpack.io` to `jitpack.io` and resolve the issue.这应该将`www.jitpack.io`转发到`jitpack.io`并解决问题。
> 
> Source: ChatGPT : https://chatgpt.com/share/6763cd5d-3468-800b-a08d-6375f45c06f1来源：ChatGPT： [https](https://chatgpt.com/share/6763cd5d-3468-800b-a08d-6375f45c06f1) ://chatgpt.com/share/6763cd5d-3468-800b-a08d-6375f45c06f1

I tried it, it seems to work for me

**Comment by auxiliary-kimchi** [comment]
아니 ㅠㅠ 제가 틀린 줄 알았잖아요 ㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠ 짓펙스럽네요 ㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠ 퇴근합시다

**Comment by firdausmaulan** [comment]
Updated Solution for Ubuntu:
1. Redirect to jitpack.io Without www:
Since www.jitpack.io isn’t properly configured, ensure you directly access jitpack.io.

Edit your /etc/hosts file:
`sudo nano /etc/hosts`
Add the following line:
`185.199.108.133 jitpack.io`

Save and close:
Press Ctrl + O, then Enter to save.
Press Ctrl + X to exit.

2. Test Redirection:
Run:
`curl -I jitpack.io`
This should succeed without SSL errors, as it matches the certificate's hostname.

3. Force Gradle to Use the Correct URL:
If your Gradle build script or library uses www.jitpack.io, you may need to override it to use jitpack.io.

Open your build.gradle file.
Find the repositories section and ensure it points to the correct URL:
gradle
```
repositories {
    maven { url 'jitpack.io' }
}
```

4. Bypass SSL Verification Temporarily (Optional):
If the above doesn't work and you're stuck, you can bypass SSL verification temporarily for Gradle builds. This is not recommended for production.

Open gradle.properties in your project.
Add the following line:
properties
`systemProp.gradle.sslVerify=false`
Retry syncing your Gradle project.

**Comment by yfzu** [comment]
事已至此先下班了

**Comment by entioentio** [comment]
Before jumping to fiddling with the hostfile, isn't checking in the browser if the adjusted URL is reachable there a sensible first step?

**Comment by xiaomanwong** [comment]
curl -I https://jitpack.io/com.github.zyyoona7.WheelPicker/pickerview                
                                                                      
HTTP/2 521 
date: Thu, 19 Dec 2024 08:10:24 GMT
content-type: text/html; charset=UTF-8
cf-ray: 8f45ea3b589580d7-NRT
cache-control: private, max-age=0, no-store, no-cache, must-revalidate, post-check=0, pre-check=0
expires: Thu, 01 Jan 1970 00:00:01 GMT
referrer-policy: same-origin
x-frame-options: SAMEORIGIN
x-jp-cf: 1
report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v4?s=FpU%2BqRF6jnIn1pUMAs8W5zObnzQce6Gr0bZ1yQ6EDDauJ5%2FwU4Watkjm8Vmf5ajyzgMLC%2BBdqfX0trDk08kRZKq5oTOHYM3TD7%2Fyzuz%2FfWRXO1cQc%2F%2BFqU3mPDo%3D"}],"group":"cf-nel","max_age":604800}
nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
server: cloudflare
server-timing: cfL4;desc="?proto=TCP&rtt=39153&min_rtt=2759&rtt_var=34309&sent=8&recv=12&lost=0&retrans=0&sent_bytes=2890&recv_bytes=615&delivery_rate=1140736&cwnd=239&unsent_bytes=0&cid=38f1d0260118f2b7&ts=11393&x=0"


It doesn`t work anywhere

**Comment by jiwon2724** [comment]
빨리 고쳐주세여ㅠㅠㅠ

**Comment by dirkvranckaert** [comment]
Same here, as of a couple of hours ago already (about 12 hours) we started to see failures...

**Comment by yfzu** [comment]
![Uploading 截屏2024-12-19 16.30.46.png…]()

**Comment by lilvip9999** [comment]
same issue from Socialist Republic of Viet Nam.

**Comment by Faltenreich** [comment]
Our GitHub Actions are fetching dependencies once again. 🥳

**Comment by wise-danya** [comment]
<img width="227" alt="Screenshot 2024-12-19 at 20 02 28" src="https://github.com/user-attachments/assets/37bfce18-02e7-42db-be50-4936d5d03854" />

Seems like not "Easy to use..."

**Comment by ivan-horchakov** [comment]
Still "Could not GET 'https://jitpack.io/androidx/test/rules/maven-metadata.xml'. Received status code 521 from server"

**Comment by illucc** [comment]
great time to start a  project that needs jitpack !!!!!

**Comment by dirkvranckaert** [comment]
Same here, still not fixed

**Comment by tunikakeks** [comment]
downtime already for 9h

**Comment by songzhaojuchris** [comment]
<img width="1097" alt="image" src="https://github.com/user-attachments/assets/f12c40cf-4c3f-4d48-8af0-f77b62bf6e7b" />
Why do I still get error 521?

**Comment by entioentio** [comment]
I seriously despise the passive-aggressive tone of the most of the comments left here. Can't you be like more civil? I know nothing of jitpack except that it is a sub-dependency of the expo project I work on. I CAN'T BUILD. So what? The downtime and lack of status annoys everybody but these kind of comments do only increase the noise level and doesn't bring anything into the discussion while exercising extra pressure on the devs.

**Comment by arpanpatel510** [comment]
Now its working

**Comment by grgia** [comment]
Same root issue, still encountering `Could not GET 'https://jitpack.io/org/nodejs/node/18.17.1/node-18.17.1.pom'. Received status code 521 from server`
