### ISSUE TITLE
simple-slack-api/master-SNAPSHOT-gb9a8a3d-73 build

### ISSUE THREAD

**Issue by morj** [jitpack/jitpack.io#689]
Log https://jitpack.io/com/github/Ullink/simple-slack-api/master-SNAPSHOT-gb9a8a3d-73/build.log

**Comment by morj** [comment]
ATM log says "Git error. Retrying."

**Comment by jitpack-io** [comment]
Hi

Which version were you using when this error occured?

**Comment by morj** [comment]
I was observing the website version. Not sure how the concept of versions is applied to jitpack.io. Or do you mean version of gradle?
