### ISSUE TITLE
PokeGOAPI-Java/0.2-g8bf31f5-1 build

### ISSUE THREAD

**Issue by DavidVazGuijarro** [jitpack/jitpack.io#690]
Log https://jitpack.io/com/github/Grover-c13/PokeGOAPI-Java/0.2-g8bf31f5-1/build.log

**Comment by jitpack-io** [comment]
Hi

Version 0.2 seems to be ok https://jitpack.io/#Grover-c13/PokeGOAPI-Java/0.2
Does that work for you?
