### ISSUE TITLE
pantry/develop-1.1-g35997ba-58 build

### ISSUE THREAD

**Issue by cldwalker** [jitpack/jitpack.io#705]
The last 3 builds have been empty for us:
* https://jitpack.io/com/github/reifyhealth/pantry/develop-1.1-g35997ba-58/build.log
* https://jitpack.io/com/github/reifyhealth/pantry/develop-1.1-g77dfd6c-40/build.log
* https://jitpack.io/com/github/reifyhealth/pantry/develop-1.1-g9b4b00b-57/build.log

Github's webhook integration is showing a 302 for this endpoint: https://jitpack.io/com/github/reifyhealth/pantry/develop-SNAPSHOT/build.log

This will be blocking us soon on development and we'd like to continue being a paying customer

**Comment by jitpack-io** [comment]
Hi 

This issue should now be resolved. 
The latest develop-SNAPSHOT was successful:  https://jitpack.io/com/github/reifyhealth/pantry/develop-1.2.0-g35997ba-1/build.log

**Comment by cldwalker** [comment]
Seems to be auto-building again. Thanks!
