### ISSUE TITLE
vtm/master-SNAPSHOT build

### ISSUE THREAD

**Issue by devemux86** [jitpack/jitpack.io#765]
I'm developer of [Mapsforge](https://github.com/mapsforge/mapsforge) and [VTM](https://github.com/mapsforge/vtm).

Mapsforge works with JitPack, but VTM does not.

The build log is empty:
Log https://jitpack.io/com/github/mapsforge/vtm/master-SNAPSHOT/build.log

And the url https://jitpack.io/com/github/mapsforge/vtm/master-SNAPSHOT/ shows:
`Git error. Retrying.`

**Comment by devemux86** [comment]
Any hint here?

**Comment by andreynovikov** [comment]
Why is it closed?
