### ISSUE TITLE
Support version ranges

### ISSUE THREAD

**Issue by jitpack-io** [jitpack/jitpack.io#77]
For versions that have been built.

**Comment by mickele** [comment]
This will be great, it's a good feature to support.

**Comment by ademar111190** [comment]
:+1:

**Comment by jitpack-io** [comment]
Good news! Version ranges now can be used with releases that have been built.

**Comment by jitpack-io** [comment]
Another update: you can now also use the special version '-SNAPSHOT'
It will build the last commit in your repo.
