### ISSUE TITLE
Android-DBVarna/0.0.1.3-alpha build

### ISSUE THREAD

**Issue by Kuzna** [jitpack/jitpack.io#771]
Log https://jitpack.io/com/github/Kuzna/Android-DBVarna/0.0.1.3-alpha/build.log

**Comment by jitpack-io** [comment]
Looks like there was an error generating javadoc:
```
AbstractDao.java:21: error: unknown tag: date
 * @date 12.10.15 16:57
   ^
```
Does `./gradlew clean install` work locally for you? Whata java version are you using?
