### ISSUE TITLE
android-components/596c0a8252 build

### ISSUE THREAD

**Issue by larsgrefer** [jitpack/jitpack.io#779]
Log https://jitpack.io/org/bitbucket/cookingfox/android-components/596c0a8252/build.log

freefair/android-gradle-plugins#1

The jitpack build-vm seems to be unable to download a jitpack-dependency: https://jitpack.io/io/freefair/android-gradle-plugins/2.1.2/android-gradle-plugins-2.1.2.jar

**Comment by cookingfox** [comment]
Thanks @larsgrefer for creating the issue.

FYI: this error started appearing when I upgraded Gradle:
- wrapper: gradle-2.10-all.zip --> gradle-2.14.1-all.zip
- android build tool plugin: 'com.android.tools.build:gradle:2.1.2' --> 'com.android.tools.build:gradle:2.1.3'
- android maven plugin: 'com.github.dcendents:android-maven-gradle-plugin:1.3' --> 'com.github.dcendents:android-maven-gradle-plugin:1.4.1' ([required to support Gradle 2.14+](https://github.com/dcendents/android-maven-gradle-plugin#note-on-releases))

**Comment by jitpack-io** [comment]
Hi,

Indeed, looks like there was a connection issue at the time of the build which is a little odd. Rebuilt and it now succeeded: 
https://jitpack.io/org/bitbucket/cookingfox/android-components/596c0a8252/build.log
