### ISSUE TITLE
MonkeySheet/v0.1.0 build

### ISSUE THREAD

**Issue by Pesegato** [jitpack/jitpack.io#784]
Log https://jitpack.io/com/github/Pesegato/MonkeySheet/v0.1.0/build.log

My travis build passes, but Jitpack fails to build it. I think this is because of this line on my build.gradle:

```
isCiServer = System.getenv("TRAVIS")
```

**Comment by Pesegato** [comment]
Are you using teamcity, so that I can detect it?

**Comment by jitpack-io** [comment]
Hi,

There is a JITPACK environment variable set for our builds. Perhaps that'll be useful here?

**Comment by Pesegato** [comment]
I've tried it,

https://github.com/Pesegato/MonkeySheet/blob/master/build.gradle#L22

But still didn't work

**Comment by Pesegato** [comment]
And now what? Am I supposed to open another issue?

**Comment by jitpack-io** [comment]
The latest master seems to have build ok
https://jitpack.io/com/github/Pesegato/MonkeySheet/-SNAPSHOT/build.log

**Comment by Pesegato** [comment]
Indeed!
