### ISSUE TITLE
Erro using Multi-module projects

### ISSUE THREAD

**Issue by danielsanfr** [jitpack/jitpack.io#787]
Hello. First, your services are amazing!

While I am trying to create a [project](https://github.com/danielsanfr/jitpack-test) with multiple modules, I am encountering an error (when I include JitPack dependence to sample app):
> Error:Module 'com.github.danielsanfr:jitpack-test:0.0.3' depends on one or more Android Libraries but is a jar

If I include the modules separately everything works properly. However according to the [documentation](https://jitpack.io/docs/BUILDING/#multi-module-projects):
> (...) To get all modules of a project use the standard syntax:
>
> `compile 'com.github.User:Repo:Tag'`

the project should also work including all at the same time.

Any idea?

**Comment by jitpack-io** [comment]
Hi,

Due to the way Android libraries work it is not possible to get all modules with a single dependency.  You can still add them individually, for example this page https://jitpack.io/#danielsanfr/jitpack-test/0.0.3 let's you select a subproject.
```gradle
dependencies {
        compile 'com.github.danielsanfr.jitpack-test:moduleone:0.0.3'
        compile 'com.github.danielsanfr.jitpack-test:moduletwo:0.0.3'
}
```

**Comment by danielsanfr** [comment]
It's all right. It would be nice if that were possible, but if not, fine.

**Comment by danielsanfr** [comment]
Only to serve as a reference. I found a solution to my problem. I create a module called `all` that depends on everyone else.

So I could have a good result: `compile 'com.github.danielsanfr.jitpack-test:all:0.0.3'`.
