### ISSUE TITLE
create maven meta data

### ISSUE THREAD

**Issue by dbachelder** [jitpack/jitpack.io#80]
I am using this plugin to periodically check for libraries that are out of date in our projects

https://github.com/ben-manes/gradle-versions-plugin

The problem is that for jitpack it can't find the `maven-metadata.xml` to see the available versions. 

https://jitpack.io/com/github/johncarl81/transfuse/transfuse/maven-metadata.xml

would it be possible to generate something? 

I am not sure what metadata you pull in from github... but if you have the timestamp for the releases and commits you could actually set the `latest` and `release` tags to something fairly reasonable. 

```
  <versioning>
    <latest>76327ab363</latest>
    <release>1.3.0</release>
```

**Comment by jitpack-io** [comment]
Yep, going to add this. It's also needed for version ranges #77

**Comment by jitpack-io** [comment]
Ok, we now have metadata for releases that have been built.

**Comment by dbachelder** [comment]
amazing! thanks!
