### ISSUE TITLE
Different maven coordinates for same github repo, based on branches. 

### ISSUE THREAD

**Issue by VictorAlbertos** [jitpack/jitpack.io#817]
Hi :)

Recently with the new release of RxJava2, (rx)libraries need now to have two separate branches, one supporting 1.x and the other one supporting 2.x. 

As suggested by JakeWharton [here](http://jakewharton.com/java-interoperability-policy-for-major-version-updates/),  having two different maven coordinates allows to the users of these libraries to move incrementally from one version to another. 

The problem I'm facing with Jitpack is that I'm not able to provide simultaneous resolution for both versions (precisely because they are different versions but not different artifacts). 

I've created a tag for 1.x version:
https://github.com/VictorAlbertos/RxActivityResult/releases/tag/0.3.6
`compile "com.github.VictorAlbertos:RxActivityResult:0.3.6"`

And another one for 2.xversion:
https://github.com/VictorAlbertos/RxActivityResult/releases/tag/0.3.6-2.x
`compile "com.github.VictorAlbertos:RxActivityResult:0.3.6-2.x"`

Both of them resolve right. But the problem is that when I add the second one to gradle, the first one (0.3.6) will be ignored because it is interpreted as a prior version than 0.3.6-2.x. 

Any thoughts will be appreciate.

Thanks.

**Comment by jitpack-io** [comment]
Hi @VictorAlbertos !

Would it be possible to use a different GitHub projects for the 2.x library?
It looks like Jake is advocating using a different groupId for 2.x versions.

**Comment by VictorAlbertos** [comment]
It seems so :)

And that's impossible with Jitpack using a single repo, right? The only way would be creating another one, then.
