### ISSUE TITLE
Add api to search artifacts by name

### ISSUE THREAD

**Issue by jitpack-io** [jitpack/jitpack.io#82]
Perhaps something like:

```
/api/search?artifactId=libraryName
```

**Comment by cesarferreira** [comment]
+1 
:)

**Comment by shkschneider** [comment]
+1

**Comment by jitpack-io** [comment]
Search API is now available
**GET** `https://jitpack.io/api/search?q=text`
https://jitpack.io/docs/API/#search

PS. Better late than never:)

**Comment by cesarferreira** [comment]
2 years in the making haha :) thanks for remembering @jitpack-io

**Comment by jitpack-io** [comment]
"After all this time?"
"Always"
:)
