### ISSUE TITLE
lt-utils/v1.0.2 build

### ISSUE THREAD

**Issue by vibhay7** [jitpack/jitpack.io#836]
Log https://jitpack.io/com/github/LimeTray/lt-utils/v1.0.2/build.log

**Comment by jitpack-io** [comment]
Hi,

Rebuilding the project worked. If you ever need rebuild a version then you can delete the faulty build and request the same version again.

**Comment by vibhay7** [comment]
Why is it need to be done from clients end?
Can you imagine how much it will effect the clients who are using this,
there should be a failure hook at your end to retry.
