### ISSUE TITLE
Download badges

### ISSUE THREAD

**Issue by jitpack-io** [jitpack/jitpack.io#837]
Add support for badges with weekly and monthly downloads.

/cc @AlmasB

**Comment by jitpack-io** [comment]
Now available as:
`[![](https://jitpack.io/v/USER/REPO/month.svg)](https://jitpack.io/#USER/REPO)`

For example, Monthly:
`[![](https://jitpack.io/v/jitpack/maven-simple/month.svg)](https://jitpack.io/#jitpack/maven-simple)`
[![](https://jitpack.io/v/jitpack/maven-simple/month.svg)](https://jitpack.io/#jitpack/maven-simple)

and weekly:
`[![](https://jitpack.io/v/jitpack/maven-simple/month.svg)](https://jitpack.io/#jitpack/maven-simple)`
[![](https://jitpack.io/v/jitpack/maven-simple/month.svg)](https://jitpack.io/#jitpack/maven-simple)

**Comment by AlmasB** [comment]
Awesome!

**Comment by ice1000** [comment]
Awesome! :+1:

**Comment by tobilarscheid** [comment]
I think these stopped working. The examples above time out for me, same for my own repos.

[![](https://jitpack.io/v/jitpack/maven-simple/month.svg)](https://jitpack.io/#jitpack/maven-simple)

**Comment by nathan-fiscaletti** [comment]
Is there any way to get the total download count? I'm not seeing it anywhere in the docs.

**Comment by Marcono1234** [comment]
See open issue #2092

**Comment by kirtan403** [comment]
@Marcono1234 Anyway to support this feature in near future?

**Comment by Marcono1234** [comment]
I am not a maintainer / member of this project; I just wanted to point to the open issue so you can watch that instead.

**Comment by ErrorxCode** [comment]
What about **total downloads**? Jetpack please add the same batch which shows total downloads.

**Comment by nathan-fiscaletti** [comment]
There is another issue specifically for "all time downloads". https://github.com/jitpack/jitpack.io/issues/2092
