### ISSUE TITLE
RxFastCache/1.0.1 build

### ISSUE THREAD

**Issue by tysheng** [jitpack/jitpack.io#846]
Log https://jitpack.io/com/github/tysheng/RxFastCache/1.0.1/build.log

**Comment by tysheng** [comment]
New to use it, anyone can help me?

**Comment by jitpack-io** [comment]
Hi @tysheng 

The `gradlew` file is empty for some reason and that causes the build to fail:
https://github.com/tysheng/RxFastCache/blob/master/gradlew

**Comment by tysheng** [comment]
@jitpack-io  thanks,I tried   ./gradlew install
but didn't work, even no response.

**Comment by jitpack-io** [comment]
@tysheng Yes, because there is nothing in the file. You should try re-generating the Gradle wrapper https://docs.gradle.org/current/userguide/gradle_wrapper.html#sec:wrapper_generation

**Comment by tysheng** [comment]
@jitpack-io 

now i get this issue
https://jitpack.io/com/github/tysheng/RxFastCache/1.1.1/build.log

why android-maven-gradle-plugin's version is still 1.3 ? I set it to 1.5.

And, why the gradle version is 2.7? I set it to 2.14.1 all the time.

**Comment by jitpack-io** [comment]
Hi,

Looks like it got resolved https://jitpack.io/com/github/tysheng/RxFastCache/1.0.0/build.log

**Comment by tysheng** [comment]
@jitpack-io Yeah,I built a new project, and it works:)
