### ISSUE TITLE
extend-enhance-base/1.0.6 build

### ISSUE THREAD

**Issue by vin89423** [jitpack/jitpack.io#849]
Log https://jitpack.io/com/github/vinexs/extend-enhance-base/1.0.6/build.log

The log said that "Gradle version 2.10 is required. Current version is 2.7".
Is that mean your server using gradle 2.7 to compile the library?
Could you mind telling me how to workaround and build my library?

Many thanks!

**Comment by jitpack-io** [comment]
Hi @vin89423 

Best way is to use a Gradle Wrapper in your project. That way our build will use the version you specify.

**Comment by vin89423** [comment]
Thanks a lot ! I can use my project through your Jitpack now =)
