### ISSUE TITLE
DynaML/v1.4.1-beta.1 build

### ISSUE THREAD

**Issue by mandar2812** [jitpack/jitpack.io#882]
Log https://jitpack.io/com/github/mandar2812/DynaML/v1.4.1-beta.1/build.log

**Comment by jitpack-io** [comment]
Hi,

Looks like that build is timing out. It takes quite a long time to resolve and download all the dependencies and we have a limit if 15 minutes. How long does it normally take?

**Comment by mandar2812** [comment]
Hello,

It generally takes about 8-10 minutes anyway.

**Comment by mandar2812** [comment]
Hi @jitpack-io 

The problem persists in DynaML v1.4.1-beta.2 as well, I tried removing a certain dependency hoping that it would reduce dependency resolution time, but it makes no difference the build is timing out. 

Click [here](https://jitpack.io/com/github/mandar2812/DynaML/v1.4.1-beta.2/build.log) for logs on the new DynaML version 1.4.1-beta.2

**Comment by jitpack-io** [comment]
Hi,

Managed to speed up the build by caching some of the dependencies. Latest build looks ok:
https://jitpack.io/com/github/mandar2812/DynaML/v1.4.1-beta.2/build.log

**Comment by mandar2812** [comment]
Hi,

Yes its building now, thank you!
