### ISSUE TITLE
Build and download JAR from JitPack website?

### ISSUE THREAD

**Issue by thomasnield** [jitpack/jitpack.io#886]
First off, awesome product. This is possibly the future of dependency builds. 

I do have an idea though that I'm hoping _might_ be easy to implement given what you've built already. 

Would it be possible to build the JAR and download it right from the JitPack.io website? There are those of us who work behind a corporate firewall and it is difficult to build snapshots locally on our machines. But if the builds are already occurring on the JitPack server, maybe you can conveniently make them accessible via the site too? Like below:

![image](https://cloud.githubusercontent.com/assets/7420801/19197847/a617810c-8c81-11e6-9726-cf62ed75f28d.png)

**Comment by thomasnield** [comment]
I know that some libraries need dependencies from other libraries. Those can either be out of scope for this feature, or you can put them all in a ZIP folder?

**Comment by jitpack-io** [comment]
Hi,

Thanks for the suggestion! We don't have download links at the moment but there's something that might help you. If you click on the build log then remove 'build.log' from the URL then you should see a list if files. All of those are downloadable
Would that work?

**Comment by thomasnield** [comment]
Oh wow,  I was wondering if there was a little hack hidden somewhere. I'll take a look in a moment. Thanks!

**Comment by thomasnield** [comment]
Does this work for getting the ~SNAPSHOT too?

**Comment by thomasnield** [comment]
Oh nice, never mind I figured it out. Thanks!

For future readers, you can trigger a build and then navigate to that directory when it is done. 

For the [TornadoFX](https://github.com/edvin/tornadofx) project, I would navigate to here to trigger a build for the snapshot. 

https://jitpack.io/#edvin/tornadofx/-SNAPSHOT

Then I would append the JAR file name to that URL to download it.

**Comment by sebtrif** [comment]
For those reaching this years later, be aware that removing build.log from the URL no longer works

**Comment by zunjae** [comment]
@sebtrif still works for me! Example link: https://jitpack.io/com/github/iammert/ExpandableLayout/1.4.1/

**Comment by souvik-bera** [comment]
No It doesnot work anymore.

**Comment by zunjae** [comment]
Can confirm, still works for me

**Comment by ali-bagheri** [comment]
yes

Convert https://jitpack.io/#mathiazhagan01/DrawableColorChange/1.4
To:
https://jitpack.io/com/github/mathiazhagan01/DrawableColorChange/1.4
and view ,jar or .aar files

OR

https://jitpack.io/com/github/mathiazhagan01/DrawableColorChange/1.4/build.log
and find download link on file.

I found (com/github/mathiazhagan01/DrawableColorChange/1.4/DrawableColorChange-1.4.aar)
and add to https://jitpack.io/

end> https://jitpack.io/com/github/mathiazhagan01/DrawableColorChange/1.4/DrawableColorChange-1.4.aar

enjoy
