### ISSUE TITLE
JavaDoc viewing failing

### ISSUE THREAD

**Issue by andrew-codechimp** [jitpack/jitpack.io#89]
When trying to view the javadoc via
https://jitpack.io/com/github/andrew-codechimp/androidutils/1.8/javadoc/
I'm getting 
{"message":"Not found","status":"error"}

Not a gradle expert but I've followed the examples and can't see what's up with it.
https://github.com/andrew-codechimp/AndroidUtils/blob/master/library/build.gradle

**Comment by jitpack-io** [comment]
Hi!
The gradel build needs to be able to produce a javadoc.jar. Probably its not making one at the moment when running: gradle install

We don't have an android javadoc example unfortunately but perhaps this will help: http://mtdevuk.com/2014/10/23/how-to-generate-javadoc-for-android-using-gradle/ ?

**Comment by andrew-codechimp** [comment]
Many thanks for the pointer, a bit of adjustment and I've got it working.
Only started with JitPack yesterday, loving it so far.

**Comment by jitpack-io** [comment]
Awesome! That's great to hear!:)
