### ISSUE TITLE
Ability to search for artifacts

### ISSUE THREAD

**Issue by jitpack** [jitpack/jitpack.io#9]
Ability to search by group, artifact and version of artifacts that have been built.

**Comment by fancellu** [comment]
Simple http browsing would be a nice start. i.e. open up directory browsing.

**Comment by jitpack-io** [comment]
Directory browsing is now enabled starting from group 
jitpack.io/`com/github/jitpack/maven-simple/`

Planing to make them into clickable links later on.

**Comment by jitpack-io** [comment]
Search API is now available
**GET** `https://jitpack.io/api/search?q=text`
https://jitpack.io/docs/API/#search
