### ISSUE TITLE
enStageInc/wibmo-iap-sdk-android/1.1.0 build issue

### ISSUE THREAD

**Issue by akshath** [jitpack/jitpack.io#90]
Log https://jitpack.io/com/github/enStageInc/wibmo-iap-sdk-android/1.1.0/build.log

**Comment by jitpack-io** [comment]
Fixed https://jitpack.io/#enStageInc/wibmo-iap-sdk-android 
Thanks for reporting and sorry about the hiccup!

**Comment by akshath** [comment]
Thank you for the quick reply.

However there still look to be 2 problems:

1. When we use this (compile 'com.github.enStageInc:wibmo-iap-sdk-android:1.1.0') in our build file we get the following error

>Error:Artifact 'wibmo-iap-sdk-android.jar (com.github.enStageInc:wibmo-iap-sdk-android:1.1.0)' not found.
>Searched in the following locations:
    https://jitpack.io/com/github/enStageInc/wibmo-iap-sdk-android/1.1.0/wibmo-iap-sdk-android-1.1.0.jar

2. Also on the website https://jitpack.io/#enStageInc/wibmo-iap-sdk-android/1.1.0 the Gradle build instruction looks to be wrong

it currently shows this: 
>compile 'com.github.enS1.1.0eInc:wibmo-iap-sdk-android:tag'

It should have been this ?
>compile 'com.github.enStageInc:wibmo-iap-sdk-android:1.1.0'
