### ISSUE TITLE
Android-Base-Utils/V1.4.0 build mission Android 25

### ISSUE THREAD

**Issue by qiyulan** [jitpack/jitpack.io#907]
Log https://jitpack.io/com/github/qiyulan/Android-Base-Utils/V1.4.0/build.log

**Comment by timrijckaert** [comment]
Same issue 
https://jitpack.io/com/github/timrijckaert/FloatingMusicActionButton/v1.6/build.log

**Comment by qiyulan** [comment]
for now,biuld passed.

BUILD SUCCESSFUL

Total time: 7.172 secs
Gradle exit code 0
Looking for artifacts...
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
Found artifact: com.github.qiyulan:baseutils:V1.4.0
EXIT_CODE=0
2016-10-24T03:30:05.857951181Z
Exit code: 0

Build artifacts:
com.github.qiyulan:Android-Base-Utils:V1.4.0
