### ISSUE TITLE
Can't see organization repos

### ISSUE THREAD

**Issue by ericwjr** [jitpack/jitpack.io#909]
I created an organization and I have a private repo there...all in github.

When I log into jitpack with my github personal account...it does not show the repos in my organization.

I have subscribed for jitpack trial.

**Comment by jitpack-io** [comment]
Hi,

It might be that the organization needs to approve JitPack application:
https://help.github.com/articles/connecting-with-third-party-applications/#third-party-applications-and-organizations
If that's not the case, let us know and we'll have another look

**Comment by jitpack-io** [comment]
Please reopen if the issue still exists
