### ISSUE TITLE
protyposis/ITEC_MediaPlayer does not build. Signing config?

### ISSUE THREAD

**Issue by Ph1b** [jitpack/jitpack.io#91]
https://jitpack.io/com/github/protyposis/ITEC-MediaPlayer/v1.3/build.log

This one does not build. Shouldnt be the singing configs be omited?

**Comment by jitpack-io** [comment]
Looks like the build didn't mind signing configs but lint did fail:

```
 Fix the issues identified by lint, or add the following to your build script to proceed with errors:
  ...
  android {
      lintOptions {
          abortOnError false
      }
  }
  ```
