### ISSUE TITLE
Can't share an artifact from Bitbucket Private Repo

### ISSUE THREAD

**Issue by jaumeDW** [jitpack/jitpack.io#910]
Hello,

I'm using Jitpack with a private Bitbucket repository. I'm trying to share an artifact publicly following these steps: https://jitpack.io/docs/PRIVATE/#artifact-sharing

But, when I look up my private repo I receive this error: 

No read access to repo

Is there a way to look up for a Bitbucket private repository? I'm not seeing any place in the website where I can put my team API KEY. And without looking up, I can't make public my library.

Thanks

**Comment by jitpack-io** [comment]
Hi @jaumeDW 

Got an update on this: We now support BitBucket repositories on https://jitpack.io website.
If you Sign In and click on your username (https://jitpack.io/w/user.html)
you'll see a new setting called *BitBucket API Key*. Set it to your Team API Key and then Look Up your repositories on  https://jitpack.io.

**Comment by jaumeDW** [comment]
Thanks!
