### ISSUE TITLE
enStageInc/wibmo-iap-sdk-android/1.1.0 build issue 

### ISSUE THREAD

**Issue by akshath** [jitpack/jitpack.io#92]
Two Issues:

1) When we use this (compile 'com.github.enStageInc:wibmo-iap-sdk-android:1.1.0') in our build file we get the following error

>Error:Artifact 'wibmo-iap-sdk-android.jar (com.github.enStageInc:wibmo-iap-sdk-android:1.1.0)' not found.
>Searched in the following locations:
    https://jitpack.io/com/github/enStageInc/wibmo-iap-sdk-android/1.1.0/wibmo-iap-sdk-android-1.1.0.jar

2) Also on the website https://jitpack.io/#enStageInc/wibmo-iap-sdk-android/1.1.0 the Gradle build instruction looks to be wrong

it currently shows this: 
>compile 'com.github.enS1.1.0eInc:wibmo-iap-sdk-android:tag'

It should have been this ?
>compile 'com.github.enStageInc:wibmo-iap-sdk-android:1.1.0'

**Comment by jitpack-io** [comment]
1) Might have to run gradle with `--refresh-dependencies` flag the first time. It probably cached the previous result. If that doesn't help then another option is deleting: $HOME/.gradle/caches
Another thing to try: `compile 'com.github.enStageInc:wibmo-iap-sdk-android:1.1.0@aar'`
Tried it locally and gradle is now able to fetch the library.

2) Fixed the version on the website. Thanks for pointing it out!

**Comment by akshath** [comment]
Thank you for the quick reply :)
