### ISSUE TITLE
How to resolve test artifact?

### ISSUE THREAD

**Issue by ben-manes** [jitpack/jitpack.io#924]
I'd like to source the tests from [jctools-core](https://github.com/JCTools/JCTools/tree/master/jctools-core) in order to use the tests for a manually shaded class. Since the test jar isn't published on Central, I can't use a classifier to qualify the artifact and thought jitpack might be the best option. I haven't figured out yet how to do that, though.

**Comment by jitpack-io** [comment]
Hi Ben,

Looks like jctools doesn't publish a tests jar at the moment https://jitpack.io/com/github/JCTools/JCTools/jctools-core/v2.0/.
If the build produced a tests jar then it would also be published by JitPack. It could be that the build needs additional configuration.

**Comment by ben-manes** [comment]
Oh okay, thanks. For some reason I thought maven always did that (haven't used in a while) and configure it to do that in Gradle.
