### ISSUE TITLE
vbfischer/spring-social-dropbox/9a8c8bd build issue

### ISSUE THREAD

**Issue by a1u** [jitpack/jitpack.io#95]
The maven option should be used instead of gradle. Both files pom.xml and gradle are present. How to use maven only?

Log https://jitpack.io/com/github/vbfischer/spring-social-dropbox/9a8c8bd/build.log

**Comment by jitpack-io** [comment]
Not possible at the moment. How about forking the project and deleting the gradle file?

**Comment by jitpack-io** [comment]
Opened issue #98 to fix that

**Comment by a1u** [comment]
>> How about forking the project and deleting the gradle file?
Have no other way then. Thanks.
