### ISSUE TITLE
jkwiecien/CountingTextView/1.0.1 build issue

### ISSUE THREAD

**Issue by jkwiecien** [jitpack/jitpack.io#96]
Log https://jitpack.io/com/github/jkwiecien/CountingTextView/1.0.1/build.log

It throws 
```Failed to notify ProjectEvaluationListener.afterEvaluate(), but primary configuration failure takes precedence.
java.lang.IllegalArgumentException: android.compileSdkVersion is missing!```

but I setup the library the same way than couple of previous ones.

**Comment by jitpack-io** [comment]
Hi!

Noticed that you're project's don't use a Gradle wrapper. If there isn't one then we build libraries with Gradle 2.4 and this causes the build to fail. Sorry about that, we've recently switched to this new version of Gradle and should have announced it earlier.
Couple of things can be done:
1. Add Gradle wrapper (preferred)
2. Use newer android-maven plugin:  https://github.com/dcendents/android-maven-gradle-plugin#usage

**Comment by jitpack-io** [comment]
Did that help?
