### ISSUE TITLE
unable to build root maven project when a gradle project exists in same github tree

### ISSUE THREAD

**Issue by s-bortolussi** [jitpack/jitpack.io#97]
Hello,

I am facing the following issue while getting a maven artefact using jitpack.

Scenario :
Given my github project is a multi-module maven project
Given a gradle project is also available in a subfolder of my github project
When jitpack builds my github project
Then it should build the root multi-module maven project -> FAILED

Instead, jitpack seems to build the gradle project (available in a subfolder of my github project)

Thanks for your help

Sebastien

**Comment by jitpack-io** [comment]
Hi Sebastien,

You're right, it was looking for a nested build.gradle file first. Fixed that!
Now it will build the pom first if there is no build.gradle in the root of the directory.
We can kick off a new build for you or if you prefer you can delete the old build on the website.

**Comment by jitpack-io** [comment]
Did that work for you?
Planing to make it configurable via a .jitpack.yml file eventualy.

**Comment by s-bortolussi** [comment]
Your fix works fine !

Thanks a lot guys

**Comment by jitpack-io** [comment]
Great to hear! You're welcome!
