### ISSUE TITLE
spark/v2.1.0-rc1 build

### ISSUE THREAD

**Issue by Yachironi** [jitpack/jitpack.io#982]
Log https://jitpack.io/com/github/apache/spark/v2.1.0-rc1/build.log

**Comment by jitpack-io** [comment]
Hi,

Looks like it failed because we're building with a different Maven version than what Spark expects:
```
[WARNING] Rule 1: org.apache.maven.plugins.enforcer.RequireMavenVersion failed with message:
Detected Maven Version: 3.2.5 is not in the allowed range 3.3.9.
```

Best way around it is to add the Maven Wrapper to the project. It will let you use a specific Maven version.
