### ISSUE TITLE
Support for AndroidAnnotations (and possibly other android-apt)

### ISSUE THREAD

**Issue by Goutte** [jitpack/jitpack.io#996]
Is there support for libs using the [android-apt plugin](https://bitbucket.org/hvisser/android-apt), such as [AndroidAnnotations](https://github.com/androidannotations/androidannotations) ?

I forked the lib to add a feature I needed, but this lib has _somewhat special_ dependencies :

```
// Android Annotations needs this
buildscript {
    repositories {
        mavenCentral()
        maven { url "https://jitpack.io" } // not sure this one is needed, but I'm desperate
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.2.2'
        classpath 'com.neenbedankt.gradle.plugins:android-apt:1.8'
    }
}

repositories {
    mavenCentral()
    mavenLocal()
    maven { url "https://jitpack.io" } // awesomeness
}

dependencies {
    compile 'org.androidannotations:androidannotations-api:4.1.0'
    apt     'org.androidannotations:androidannotations:4.1.0'
    compile 'org.androidannotations:rest-spring-api:4.1.0'
    apt     'org.androidannotations:rest-spring:4.1.0'
}
```

I tagged a `4.1.1` on my fork, and tried every flavor of `compile 'com.github.Goutte:androidannotations:4.1.1'` I could think of, including those for multiple artifacts, for a handful of hours, and I'm now in a complete state of disarray. Can someone please _please_ **please** tell me if it's even doable before I sacrifice my first born to the Byte Gods ?

---

Note: I use jitpack with success on a bunch of other libs in the same project, and it's awesome !

**Comment by jitpack-io** [comment]
Hi @Goutte ,

Android Apt shouldn't be a problem but having a look at the builds https://jitpack.io/#Goutte/androidannotations
there's a few errors: https://jitpack.io/com/github/Goutte/androidannotations/4.1.1/build.log

The `Unsupported major.minor version 52.0` error suggests that Java 8 should be used for building. This can be specified using jitpack.yml https://jitpack.io/docs/BUILDING/#build-customization

The other error is related to functional tests.

**Comment by Goutte** [comment]
Woah !

Thanks for the fast answer ! I'll look it up tonight after work ; my bad for not seeing that we could watch the logs, having disabled javascript by default. I had the same Java 8 troubles on my local build so I know what the error means, but thanks for taking the time to clarify it, it shows insane professionalism ! :clap: 

---

I'll probably close this ticket tonight. Thanks again !

**Comment by Goutte** [comment]
You really helped me out of a pitfall with bloody pikes and bleached bones there...
It finally works ! Nothing worse than being stuck, unable to write code.

For whomever stumbles upon this, here's my final gradle config, after adding the `jitpack.yml` to my fork :

``` gradle
compile 'com.github.Goutte.androidannotations:androidannotations-api:4.1.2'
apt     'org.androidannotations:androidannotations:4.1.0'
compile 'org.androidannotations:rest-spring-api:4.1.0'
apt     'org.androidannotations:rest-spring:4.1.0'
```

Thanks again, and keep up the good work ! And a final thank you for being free for moneyless open-source devs such as me :+1:
