### ISSUE TITLE
react-native/0.39.0-AndroidSupportLibrary25.0.1-v0.23.0-rc-gbf5ad52-3105 build

### ISSUE THREAD

**Issue by jpshelley** [jitpack/jitpack.io#997]
Log https://jitpack.io/com/github/jpshelley/react-native/0.39.0-AndroidSupportLibrary25.0.1-v0.23.0-rc-gbf5ad52-3105/build.log

Created a fork of react native and assumed I could host the .aar for the Android Library included in `ReactAndroid` folder. Unsupported Major Minor issue though. Thoughts?

**Comment by jitpack-io** [comment]
Hi @jpshelley 

Yes, looks like it's building with Java 7 when Java 8 is required.
There's a way to set the Java version: https://jitpack.io/docs/BUILDING/#build-customization

**Comment by jpshelley** [comment]
@jitpack-io I added the jitpack.yml but it doesn't show up on the jitpack website so I'm not sure if its building or not yet.
https://github.com/facebook/react-native/compare/master...jpshelley:0.39.0-AndroidSupportLibrary25.0.1#diff-5a6c00112197901aac836c1242d66a0eR2

**Comment by jpshelley** [comment]
Fixed with `jitpack.yml`. Opened another issue for another problem though. Thanks
